= Upgrade tool - The Requirements
:page-since: 4.8
:page-toc: top

WARNING: This page is a work in progress.

== Scenarios to Support

* object validation (deprecated, planned removal, others schema changes)
** should we validate initial objects in this phase?
** automatic migration recommendation(e.g. for move when replacement is defined, if element
 was removed we can remove, ...)
* DB schema upgrade
* import initial objects
** prepare not only initial objects in "absolute state" (good for new deployments) but also deltas which can be applied in existing environments
* provide detailed result what was done, status of the operations, success/error rate?
* configurable options, e.g. stop on error or continue but report?

Non functional requirements:

* Should be effective for small and medium size deployments.
* think about modularity and usability, maybe not everything is suitable in evry environment, e.g. small vs. big deployments
* Progress reporting should be improved. User has to know what happened, what's happening, why it's happening

See also https://jira.evolveum.com/issues/?jql=resolution%20%3D%20Unresolved%20AND%20labels%20%3D%20ninja[JIRA issues].

=== Upgrade midpoint

* from old LTS to new LTS (now 4.4 -> 4.8, 4.7 -> 4.8)
* from feature release to next one

// TODO viliam

== Functional Requirements

* audit how to migrate?

// TODO viliam

== Non-functional requirements

* Only deployments with native PostgresSQL repository supported
* Repository size (object count) support: up to 100k
* Check whether midPoint is running before upgrade starts

// TODO viliam

== Other

// TODO viliam

* display differences in initial import objects vs those currently stored in repository
* verify objects in midPoint
** what about verification results? dump list to CSV or something?
* update DB schema
* update binaries

* check 4.4 LTS schema versus 4.8 schema, make sure there's upgrade path for changes in schema
** see also xref:/midpoint/devel/design/schema-cleanup-4.8/schema-cleanup.adoc[Schema cleanup]