= Requirements
:page-since: 4.8
:page-toc: top

WARNING: This page is a work in progress.

== Introduction

This document contain description of requirements for new _upgrade_ feature, which should help users simplify the process of midPoint upgrade.
One part of upgrade procedure will be the update of objects stored in midPoint repository according to schema updates (see also xref:/midpoint/devel/design/schema-cleanup-4.8/schema-cleanup.adoc[Schema cleanup]).

== Functional Requirements

* Object validation (deprecated, planned removal, others schema changes)
** Should we validate initial objects in this phase?
#TODO#
** Automatic migration recommendation(e.g. for move when replacement is defined, if element was removed we can remove, ...)
** Reporting on changes that would be executed on objects
* Initial objects
** Import new, if necessary upgrade existing
** Prepare not only initial objects in "absolute state" (good for new deployments) but also deltas which can be applied in existing environments
* Upgrade DB schema
* Upgrade _<midpoint.home>_
* Upgrade binaries, start/stop scripts
* Upgrade objects in DB
* Upgrade audit records in DB #TODO Confirm#
* Configurable options, e.g. stop on error or continue but report?
#TODO more specific#

== Non-functional requirements

* Upgrade path
** From old LTS to new LTS (e.g. 4.4 -> 4.8)
** From feature release to next one (e.g. 4.7 -> 4.8)
* Should be effective for small and medium size deployments
** Up to 250k objects in repository #TODO CONFIRM#
** Only deployments with native PostgresSQL repository supported
* Upgrade process doesn't have to run when midPoint is operational (running)
* Progress reporting necessary
** Provide detailed result what was done, status of the operations, success/error rate?
** User has to know what happened, what's happening, why it's happening
** See also https://jira.evolveum.com/issues/?jql=resolution%20%3D%20Unresolved%20AND%20labels%20%3D%20ninja[JIRA issues]
* Think about modularity and usability, maybe not everything is suitable in every environment, e.g. small vs. big deployments

== Other

* Integration with ninja
** Possible switch to spring shell/batch
* Display differences in initial import objects vs those currently stored in repository
** What about verification results? dump list to CSV or something?
* Check 4.4 LTS schema versus 4.8 schema, make sure there's upgrade path for changes in schema
** See also xref:/midpoint/devel/design/schema-cleanup-4.8/schema-cleanup.adoc[Schema cleanup]

== Opened questions for meeting

* How to update object during upgrade procedure?
** When reading object with old repository impl, we can't update is according to new one
** When reading object with new repository impl, we will not get any info about elements that were removed.
Currently, only warning to log - if schema migration exist, else exception is thrown.