---
release-version: '4.2'
---
= MidPoint 4.2 "Maxwell"
:page-layout: release
:release-version: 4.2
:page-wiki-name: Release 4.2
:page-wiki-id: 48824550
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2020-04-09T14:59:05.552+02:00
:page-wiki-metadata-modify-user: virgo
:page-wiki-metadata-modify-date: 2021-02-08T17:39:53.840+01:00
:page-liquid:

Release {release-version} is a thirty-third midPoint release code-named _Maxwell_.
The {release-version} release brings new reporting mechanism, updates to auditing implementation, continued improvement for authentication and handful of other interesting improvements.
Most importantly, midPoint {release-version} brings experimental updates to the very foundations of midPoint.

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
    <a href="https://en.wikipedia.org/wiki/James_Clerk_Maxwell">James Clerk Maxwell</a> (1831 - 1879) was a Scottish scientist in the field of mathematical physics.
    He is best known for Maxwell equations that form a foundation of classical electromagnetism, classical optics and electric circuits.
    The equations are part of a theory of electromagnetic radiation, bringing together for the first time theories of electricity, magnetism and light.
    Maxwell's work was theoretical, but it has profound effect on both theoretical and practical parts of science and engineering.
    Maxwell has described the path that we follow up to this day.
</p>
<p>
    Similarly to Maxwell's theories, midPoint 4.2 lays down theoretical foundations with significant potential for the future.
    Most of them are results of <a href="https://docs.evolveum.com/midpoint/midprivacy/">midPrivacy initiative</a>.
    <i>Axiom</i> is a new modeling language that works on conceptual levels to provide support for metadata schemas.
    Axiom was used to implement data provenance functionality deep in midPoint core data layers.
    The insights that originated from the provenance effort inspired fundamental improvements in processing of midPoint mappings.
    Overall, the work on midPoint 4.2 provided a lot of inspiration and theoretical foundations for the future.
    MidPoint code is almost a decade old.
    The Maxwell release builds up essential theories that would allow midPoint to flourish for decades to come.
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

== Changes With Respect To Version 4.1

=== New Features and Improvements

* Major features

** wiki:Report+Configuration#ReportConfiguration-Newreport[Native reports] (a.k.a. "Jasper-less reports")

** Audit subsystem based on midPoint query language

** Flexible authentication for REST service

** xref:/midpoint/projects/midprivacy/phases/01-data-provenance-prototype/[MidPrivacy: Data provenance prototype] (experimental)

** wiki:Report+Configuration#ReportConfiguration-%27Importreport%27[Custom data imports] (a.k.a. "reverse reports") (experimental)


* User interface improvements

** Improved user experience of the search bar

** "Copy environment info" button on the About page

** Selection of columns for CSV exports

** Audit log viewer user experience improvements

** Minor shopping cart user experience improvements



* Model, Provisioning and Synchronization

** wiki:Resource+Maintenance+State[Resource maintenance mode (contributed)]

** wiki:Multiaccounts+HOWTO#MultiaccountsHOWTO-OutboundMappings[Outbound multiaccounts]

** wiki:Linked+objects[Linked objects]

** wiki:Role+Autoassign+Configuration[Restriction of autoassignment mappings to a given focus type(s)]

** wiki:Archetype+Configuration#ArchetypeConfiguration-MultipleArchetypes[Support for multiple archetypes]



* Miscellaneous improvements

** Indestructible objects: accidental delete prevention

** wiki:Flexible+Authentication+Configuration[Authentication policy for node group]

** wiki:Report+Configuration[Expression profiles for GUI/report column expressions]



* Internals and Development

** xref:/midpoint/reference/security/audit/configuration/[Decoupling of audit and repository databases]

** Code cleanups and dependency upgrades

** xref:/midpoint/projects/midprivacy/phases/01-data-provenance-prototype/axiom/spec/[Axiom data modeling language] (experimental)

** Data provenance metadata (experimental)



=== Deprecation, Feature Removal And Incompatible Changes

* Support for all SOAP services was removed.
Please use xref:/midpoint/reference/interfaces/rest/[RESTful interface] instead.
It is still possible to create custom SOAP services in overlay projects.
However, midPoint no longer includes SOAP infrastructure (Apache CXF SOAP components).
Overlay authors are responsible for specifying appropriate dependencies and maintenance of their compatibility with current and future midPoint versions.

* Use of HQL query language for audit log queries and dashboard widgets is deprecated.
Please use midPoint query language instead.

* .NET remote connector server is no longer supported.

* Apache Tomcat 8.5 is no longer supported.

* Use of Jasper-based reports in midPoint is deprecated in favor of the new "native" reports.
Preliminary plan is to keep Jasper-based reports supported for several releases, but it is recommended to migrate the reports as soon as possible.

* Support for Microsoft Internet Explorer is deprecated.

* Support for MySQL and MariaDB is deprecated.
Those databases will be supported for some time (possibly long time), but wiki:Repository+Database+Support[support for them will be eventually removed]. It is strongly recommended to use PostgreSQL instead.

* Explicit deployment to an external web container is deprecated since midPoint 4.1.

* MidPoint plug-in for Eclipse IDE was never officially supported and it will not be developed any more.
This plugin is abandoned in favor of IntelliJ IDEA environment (xref:/midpoint/tools/studio/[MidPoint Studio]).

* Unofficial option to use Spring Security modules is no longer available.
It was replaced by xref:/midpoint/reference/security/authentication/flexible-authentication/[flexible authentication] mechanisms.

* Unofficial JasperSoft Studio plugin for midPoint is no longer available.
There is no plan to make it available again.


=== Releases Of Other Components

* ConnId framework was released as Evolveum release 1.5.0.17.
This adds support for "is null" or "not present" filters.

* New versions of xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector], xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector] and xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable Connector] were released during the course of midPoint 4.2 development.

* Release of Java REST client is planned shortly after midPoint 4.2 release.

* TODO: Overlay projects and other associated artifacts were released together with midPoint 4.2.

* xref:/midpoint/tools/studio/[MidPoint Studio] plugin for IntelliJ IDEA will be released in beta quality around the same time as midPoint 4.2 release.


++++
{% include release-quality.html %}
++++

=== Limitations

Following list provides summary of limitation of this midPoint release.

* Functionality that is marked as xref:/midpoint/versioning/experimental/[Experimental Functionality] is not supported for general use (yet).
Such features are not covered by midPoint support.
They are supported only for those subscribers that funded the development of this feature by the means of xref:/support/subscription-sponsoring/[Subscriptions and Sponsoring] or for those that explicitly negotiated such support in their support contracts.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector]. Support for LDAP connector is included in standard midPoint support service, but there are limitations.
This "bundled" support only includes operations of LDAP connector that 100% compliant with LDAP standards.
Any non-standard functionality is explicitly excluded from the bundled support.
We strongly recommend to explicitly negotiate support for a specific LDAP server in your midPoint support contract.
Otherwise only standard LDAP functionality is covered by the support.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] page for more details.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)]. Support for AD connector is included in standard midPoint support service, but there are limitations.
Only some versions of Active Directory deployments are supported.
Basic AD operations are supported, but advanced operations may not be supported at all.
The connector does not claim to be feature-complete.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)] page for more details.

* Functionality developed in scope of xref:/midpoint/projects/midprivacy/phases/01-data-provenance-prototype/[midPrivacy data provenance prototype] is part of this release.
However, it is not considered to be production-ready and it should be considered _experimental_.

* MidPoint user interface has flexible (fluid) design and it is able to adapt to various screen sizes, including screen sizes used by some mobile devices.
However, midPoint administration interface is also quite complex and it would be very difficult to correctly support all midPoint functionality on very small screens.
Therefore midPoint often works well on larger mobile devices (tablets) it is very likely to be problematic on small screens (mobile phones).
Even though midPoint may work well on mobile devices, the support for small screens is not included in standard midPoint subscription.
Partial support for small screens (e.g. only for self-service purposes) may be provided, but it has to be explicitly negotiated in a subscription contract.

* There are several add-ons and extensions for midPoint that are not explicitly distributed with midPoint.
This includes Java client library, various samples, scripts, connectors and other non-bundled items.
Support for these non-bundled items is limited.
Generally speaking those non-bundled items are supported only for platform subscribers and those that explicitly negotiated the support in their contract.

* MidPoint contains a basic case management user interface.
This part of midPoint user interface is not finished.
The only supported part of this user interface is the part that is used to process requests and approvals.
Other parts of case management user interface are considered to be experimental, especially the parts dealing with manual provisioning cases.

* Multi-node task distribution had a limited amount of testing, due to inherent complexity of the feature.
It is likely that there may be problems using this feature.
We recommend not to use this feature unless it is absolutely necessary.

This list is just an overview and it may not be complete.
Please see the documentation regarding detailed limitations of individual features.


== Platforms

MidPoint is known to work well in the following deployment environment.
The following list is list of *tested* platforms, i.e. platforms that midPoint team or reliable partners personally tested with this release.
The version numbers in parentheses are the actual version numbers used for the tests.

It is very likely that midPoint will also work in similar environments.
But only the versions specified below are supported as part of midPoint subscription and support programs - unless a different version is explicitly agreed in the contract.

Support for some platforms is marked as "deprecated".
Support for such deprecated versions can be removed in any midPoint release.
Please migrate from deprecated platforms as soon as possible.


=== Java

* OpenJDK 11 (11.0.8).
This is a *recommended* platform.

OpenJDK 11 is a recommended Java platform to run midPoint.

Support for Oracle builds of JDK is provided only for the period in which Oracle provides public support (free updates) for their builds.
As far as we are aware, free updates for Oracle JDK 11 are no longer available.
Which means that Oracle JDK 11 is not supported for MidPoint any more.
MidPoint is an open source project, and as such it relies on open source components.
We cannot provide support for platform that do not have public updates as we would not have access to those updates and therefore we cannot reproduce and fix issues.
Use of open source OpenJDK builds with public support is recommended instead of proprietary builds.


=== Web Containers

MidPoint is bundled with an embedded web container.
This is the default and recommended deployment option.
See xref:/midpoint/reference/deployment/stand-alone-deployment/[Stand-Alone Deployment] for more details.

Apache Tomcat is supported as the only web container for midPoint.
Support for no other web container is planned.
Following Apache Tomcat versions are supported:

* Apache Tomcat 9.0 (9.0.37)

Apache Tomcat 8.0.x and 8.5.x are no longer supported.


=== Databases

MidPoint supports several databases.
However, performance characteristics and even some implementation details can change from database to database.
Since midPoint 4.0, *PostgreSQL is the recommended database* for midPoint deployments.

* H2 (embedded).
Supported only in embedded mode.
Not supported for production deployments.
Only the version specifically bundled with midPoint is supported. +
H2 is intended only for development, demo and similar use cases.
It is *not* supported for any production use.
Also, upgrade of deployments based on H2 database are not supported.

* PostgreSQL 13, 12, 11 and 10.* PostgreSQL 13 or 12 is strongly recommended* option.

* MariaDB (10.0.28) - DEPRECATED

* MySQL 5.7 (5.7) - DEPRECATED

* Oracle 12c

* Microsoft SQL Server 2016 SP1

Our strategy is to officially support the latest stable version of PostgreSQL database (to the practically possible extent).
PostgreSQL database is the only database with clear long-term support plan in midPoint.
We make no commitments for future support of any other database engines.
See wiki:Repository+Database+Support[Repository Database Support] page for the details.

Only a direct connection from midPoint to the database engine is supported.
Database and/or SQL proxies, database load balancers or any other devices (e.g. firewalls) that alter the communication are not supported.


=== Supported Browsers

* Firefox
* Safari
* Chrome
* Edge
* Opera

Any recent version of the browsers is supported.
That means any stable stock version of the browser released in the last two years.
We formally support only stock, non-customized versions of the browsers without any extensions or other add-ons.
According to the experience most extensions should work fine with midPoint.
However, it is not possible to test midPoint with all of them and support all of them.
Therefore, if you chose to use extensions or customize the browser in any non-standard way you are doing that on your own risk.
We reserve the right not to support customized web browsers.


== Important Bundled Components

[%autowidth]
|===
| Component | Version | Description

| Tomcat
| 9.0.37
| Web container

| ConnId
| 1.5.0.17
| ConnId Connector Framework

| LDAP connector bundle
| 3.1
| LDAP, Active Directory and eDirectory connector

| CSV connector
| 2.4
| Connector for CSV files

| DatabaseTable connector
| 1.4.4.0
| Connector for simple database tables

|===

++++
{% include release-download.html %}
++++


== Upgrade

MidPoint is software that is designed for easy upgradeability.
We do our best to maintain strong backward compatibility of midPoint data model, configuration and system behavior.
However, midPoint is also very flexible and comprehensive software system with a very rich data model.
It is not humanly possible to test all the potential upgrade paths and scenarios.
Also some changes in midPoint behavior are inevitable to maintain midPoint development pace.
Therefore we can assure reliable midPoint upgrades only for link:https://evolveum.com/services/[midPoint subscribers]. This section provides overall overview of the changes and upgrade procedures.
Although we try to our best it is not possible to foresee all possible uses of midPoint.
Therefore the information provided in this section are for information purposes only without any guarantees of completeness.
In case of any doubts about upgrade or behavior changes please use services associated with link:https://evolveum.com/services/[midPoint subscription] or purchase link:https://evolveum.com/services/professional-services/[professional services].


=== Upgrade From MidPoint 4.1.x

MidPoint 4.2 data model is not completely backwards compatible with previous midPoint versions.
However, vast majority of data items is compatible.
Therefore xref:/midpoint/reference/upgrade/database-schema-upgrade/[the usual upgrade mechanism] can be used.
There are some important changes to keep in mind:

* Database schema needs to be upgraded using the xref:/midpoint/reference/upgrade/database-schema-upgrade/[usual mechanism].

* Version numbers of some bundled connectors have changed.
Therefore connector references from the resource definitions that are using the bundled connectors need to be updated.

* Channel namespaces (and hence qualified names and URIs) were unified.
This affects configurations where channel URIs are used, most notably flexible authentication configuration.
Channel names need to be updated during the upgrade, otherwise the authentication may not work at all.
When in doubt, it is recommended to disable flexible authentication (remove the configuration) before upgrade, conduct an upgrade with default authentication configuration, and re-enable the flexible authentication after upgrade (with new channel names).
Channel name changes are documented below.

* If you use custom version of starting script (normally `bin/midpoint.sh`) adjustments are needed, otherwise custom JARs in `$MIDPOINT_HOME/lib` will not be loaded to classpath. Consult the provided `midpoint.sh`, notice how `-cp ... -Dloader.path=...` and different main class are used.


=== Upgrade From MidPoint 4.0.x Or Older

Upgrade from midPoint 4.0.x or older is not supported directly.
Please upgrade to midPoint 4.1.x first.


=== Changes In Initial Objects Since 4.1

MidPoint has a built-in set of "initial objects" that it will automatically create in the database if they are not present.
This includes vital objects for the system to be configured (e.g. role `Superuser` and user `administrator`). These objects may change in some midPoint releases.
But to be conservative and to avoid configuration overwrite midPoint does not overwrite existing objects when they are already in the database.
This may result in upgrade problems if the existing object contains configuration that is no longer supported in a new version.
Therefore the following list contains a summary of changes to the initial objects in this midPoint release.
The complete new set of initial objects is in the `config/initial-objects` directory in both the source and binary distributions.
Although any problems caused by the change in initial objects is unlikely to occur, the implementors are advised to review the changes and assess the impact on case-by-case basis.

There were numerous changes to initial objects in this release.
Please review link:https://github.com/Evolveum/midpoint/commits/master/gui/admin-gui/src/main/resources/initial-objects[source code history] for list of changes.


=== Bundled Connector Changes Since 4.1

* ConnId connector framework was upgraded to version 1.5.0.17.
This version is backwards compatible with previous versions.

* LDAP ad AD connectors were upgraded to the latest available version 3.1.

* DatabaseTable connector was upgraded to the latest available version 1.4.4.0.


=== Behavior Changes Since 4.1

* Flexible authentication implementation was extended to cover REST service.
If you already have configuration for flexible authentication, then you have to add appropriate section for REST service.
In case that you are not using flexible authentication, REST service authentication will work in the same way as in midPoint 4.1.

* Mapping processing was improved and cleanup, mostly as a side effect of xref:/midpoint/projects/midprivacy/phases/01-data-provenance-prototype/[midPrivacy: Data Provenance Prototype]

** Experimental "push changes" option: Since midPoint 4.2 the phantom changes, i.e. changes that do not modify focus object state, are filtered out.
A typical example is disabling user that is already disabled.
Before 4.2, such operation would result in propagating the disabled state to projections, assuming that appropriate mappings are in place.
Starting with midPoint 4.2, such a change is not propagated by default.
In order to do that, "push changes" option has to be set.

** Processing of strong mapping was changed in some edge cases: Before 4.2, if a item value was deleted (by primary or secondary delta) but the same value also mandated by a strong mapping, a `PolicyViolationException` was thrown.
This behavior has changed: such a situation is still considered non-standard (because in some point of view a strong mapping represents a kind of policy that is to be held) but instead of exception, only a warning is issued.
Of course, the value mandated by the mapping is not deleted.
It is kept in the item.

** Evaluation of normal mappings was changed, when in presence of related secondary delta: Originally, any delta on target item suppressed evaluation of normal mappings for that target.
This is understandable for primary deltas but not so clear for secondary deltas.
So, for secondary deltas the behavior is changed now: normal mappings targeted to items that have been changed previously (by secondary delta) are evaluated.

** New `afterProjections` template mapping evaluation phase was added.
Some mappings (e.g. those that need to "see" `hasLinkedAccount` function transition) should be executed after projection activation is computed, but before projector results are committed.
For such cases we have created experimental `afterProjections` evaluation phase.

** Representation of secondary deltas in model context was changed slightly.
Please see wiki:Deltas+in+Projector+and+Clockwork[Deltas in Projector and Clockwork] for more information.

* Following expression variables are still deprecated: `user`, `account`, `shadow`. These variables will be removed soon.
Please change your script to use `focus` and `projection` variables instead.

* Property `subtype` is still deprecated.
It will be removed soon.
Please change your configuration to use archetypes instead.

* Channel namespaces (and hence qualified names and URIs) were unified.
All built-in channels have `http://midpoint.evolveum.com/xml/ns/public/common/channels-3` namespace now..
Please update channel names and URIs in your configuration according to the following table:

|===
| Old channel namespace (4.1 and earlier) | New channel namespace (4.2 and later)

| `http://midpoint.evolveum.com/xml/ns/public/provisioning/channels-3#liveSync`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#liveSync`


| `http://midpoint.evolveum.com/xml/ns/public/provisioning/channels-3#asyncUpdate`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#asyncUpdate`


| `http://midpoint.evolveum.com/xml/ns/public/provisioning/channels-3#reconciliation`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#reconciliation`


| `http://midpoint.evolveum.com/xml/ns/public/provisioning/channels-3#recompute`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#recompute`


| `http://midpoint.evolveum.com/xml/ns/public/provisioning/channels-3#discovery`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#discovery`


| `http://midpoint.evolveum.com/xml/ns/public/provisioning/channels-3#import`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#import`


| `http://midpoint.evolveum.com/xml/ns/public/model/channels-3#webService`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#webService`


| `http://midpoint.evolveum.com/xml/ns/public/model/channels-3#objectImport`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#objectImport`


| `http://midpoint.evolveum.com/xml/ns/public/model/channels-3#rest`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#rest`


| `http://midpoint.evolveum.com/xml/ns/public/model/channels-3#actuator`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#actuator`


| `http://midpoint.evolveum.com/xml/ns/public/model/channels-3#remediation`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#remediation`


| `http://midpoint.evolveum.com/xml/ns/public/model/channels-3#user`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user`


| `http://midpoint.evolveum.com/xml/ns/public/gui/channels-3#init`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#init`


| `http://midpoint.evolveum.com/xml/ns/public/gui/channels-3#selfRegistration`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#selfRegistration`


| `http://midpoint.evolveum.com/xml/ns/public/gui/channels-3#resetPassword`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#resetPassword`


| `http://midpoint.evolveum.com/xml/ns/public/gui/channels-3#user`
| `http://midpoint.evolveum.com/xml/ns/public/common/channels-3#user`


|===


==== Channel URI migration

In order to facilitate migration of channel URIs, some of them are migrated automatically (see link:https://jira.evolveum.com/browse/MID-6547[MID-6547]):

. Channel URIs in tasks.
These are automatically migrated when the task is run for the first time under midPoint 4.2.

. Channel URIs in object, assignment, and credentials metadata (`metadata.createChannel`). This property is automatically migrated when the object, assignment, or credentials metadata is updated for the first time under midPoint 4.2.

. Channel URIs in serialized model operation context, e.g. in approval cases.
These are not migrated in the repository, but de-serialized into new form when model operation context is read from the repository.

The following channel URIs are *not* migrated automatically, because they are part of the configuration:

. `channel` and `exceptChannel` properties in mappings,

. `channel` in synchronization reaction definition (in `synchronization`  section of resource definition),

. channels in flexible authentication configuration.

The following channel URIs are also not migrated automatically:

. channel information in the audit log.
However, audit log viewer in midPoint GUI was modified to be able to filter on both old and new channel URIs;

. channel in shadow synchronization situation description,

. channel in task "actions executed" statistics,

. channel in operation execution records.

We assume that channel information under points 2-4 above is not used for any automated processing.
If you need to migrate these, you can write e.g. your own bulk action that will do so.


=== Public Interface Changes Since 4.1

* Prism API was changes in several places.
However, this is not yet stable public interface therefore the changes are are not tracked in details.

* There were changes to the wiki:IDM+Model+Interface[IDM Model Interface] (Java).
Please see source code history for details.

* xref:/midpoint/reference/legacy/soap/[IDM Model Web Service Interface] (SOAP) was removed.


=== Important Internal Changes Since 4.1

These changes should not influence people that use midPoint "as is".
These changes should also not influence the XML/JSON/YAML-based customizations or scripting expressions that rely just on the provided library classes.
These changes will influence midPoint forks and deployments that are heavily customized using the Java components.

* There were changes in internal code structure, most notably changes in Prism and GUI.
Most changes were related to the xref:/midpoint/projects/midprivacy/[midPrivacy] effort and Axiom prototype.
Heavy customizations of midPoint 4.1.x may break in midPoint 4.2.

++++
{% include release-issues.html %}
++++

Some of the known issues are listed below:

* There is a support to set up storage of credentials in either encrypted or hashed form.
There is also unsupported and undocumented option to turn off credential storage.
This option partially works, but there may be side effects and interactions.
This option is not fully supported yet.
Do not use it or use it only at your own risk.
It is not included in any midPoint support agreement.

* Native attribute with the name of 'id' cannot be currently used in midPoint (bug:MID-3872[]).
If the attribute name in the resource cannot be changed then the workaround is to force the use of legacy schema.
In that case midPoint will use the legacy ConnId attribute names (icfs:name and icfs:uid).

* We have seen issues upgrading H2 instances to a new version.
Generally speaking H2 is not supported for any particular use.
We try to make H2 work and we try to make it survive an upgrade, but there are occasional issues with H2 use and upgrade.
Make sure that you backup your data in a generic format (XML/JSON/YAML) in regular intervals to avoid losing them.
It is particularly important to backup your data before upgrades and when working with development version of midPoint.