= Prism Schema
:page-nav-title: Schema
:page-wiki-name: Prism Schema

WARNING: This page is a stub, it is a work in progress.

Prism is a completely schema-based system.
It is supposed to know definition of every data item it works with.
Prism knows whether the item is string, whether it is a structured container, what data items it contains, whether it is single-value of multi-valued and so on.

== Static and Dynamic Schema

Prism is built on an assumption that the basic part of the data model (schema) is available during compile time.
This _static schema_ is used to generate the code for the "bean" Java classes, used to access Prism data structures.
However, Prism can also work with dynamic schemas that are available at run-time.
This method is usually used to extend the basic data model with custom data items (_schema extension_).
However, Prism can work with a schema that is dynamically discovered at run-time.

== See Also

* link:basic-definitions/[Basic Prism Schema Definitions]
