= Can I use newer version of XYZ with midPoint?

== The Question

Can I use a newer PostgreSQL database than that which is specified in release notes?

Can I use newer version of Active Directory than which is mentioned in connector documentation?

Can I use the most recent browser version with midPoint?

== Short Answer

Yes.
However, we have not tested that version yet.
Therefore it may not be entirely smooth ride.
However, in most cases, we will gladly fix midPoint as long as you are midPoint subscriber.

== Long Answer

Our strategy is to support the most recent versions of databases, source systems, target systems, browsers and any other software components that we live with.
That is the strategy.
However, there are practical limitations.
It is not enough to just declare support for some particular version.
The declaration itself is not a magic charm that make things works.
What is needed here is testing.
Lot of testing.
And fixes for the bugs that might be found.
That requires time.

If you are conservative and you want to be sure that you have completely supported solution and that we will fix any bugs that you might found please use the recommended version.
And make sure you are covered by support agreement.
We will not fix community issues related to a specific kind and version of a database or any other system.
We will do that only for customers covered by support agreements.

If you like to live on an edge then go ahead and try a newer version.
Especially if the component in question is an open source component with a good reputation, such as PostgreSQL. In that case it is very likely that your system will work smoothly.
And if there are some minor issues, we will be more than happy to fix them (you still need support agreement, of course).
Especially if you are a platform subscriber.
However, there is still some danger.
Some databases and systems have a bad habit to cause nasty problems when a newer version is used.
This often happens with commercial components.
In that case we still want to support the most recent version - eventually.
But we might not be able to fix those issues in time for your project.
We will try.
However, some of those issues may be too complex and may require major changes in the integration code.
Many commercial products are notoriously difficult to predict.
Therefore we cannot make any hard promises here.

This general support for newer versions has some limitations.
It does not apply to *deprecated* or *experimental* components.
There may also be some cases, where we so not foresee a bright future supporting a particular component.
In that case we may not be willing to fix issues related to newer versions.
However, such cases are usually very rare.

== Summary

If you feel like you want to try a newer version, please do so.
Just make sure you are covered by https://wiki.evolveum.com/display/midPoint/Subscriptions+and+Sponsoring[support agreement] or even better by https://wiki.evolveum.com/display/midPoint/Subscriptions+and+Sponsoring[platform subscription].
If you run into problems we will do our best to help you.
However, we cannot predict all the possible issues, therefore we cannot make any hard promises.
Therefore, please make sure you have a "plan B" to roll back to a supported version of the component in the worst case.

== See Also

* link:/faq/[Frequently Asked Questions]
