= Is Tomcat deployment still supported?
:page-wiki-name: Is Tomcat deployment still supported?

TL;DR: Yes, but it is deprecated.
Please use stand-alone deployment instead.

Midpoint 3.7 introduced stand-alone deployment model for midPoint.
There were many good reasons for that change.
But perhaps the strongest motivation was to lower entry barrier by making midPoint installation simpler.
There are other advantages too: midPoint is now bundled with a matching version of Tomcat.
This combination gets better testing, as it is unrealistic to test midPoint with all existing versions of Tomcat.
The bundling may make some upgrade easier (especially upgrades where Tomcat needs to be upgraded as well).
With stand-alone deployment we are bundling startup scripts that are customized for midPoint and ready to use.
And so on, and so on.
There is a lot of small advantages that make it easier to use midPoint in stand-alone mode - especially for users that are not entirely at home in Java EE world.

Stand-alone deployment is now the primary deployment method.
But it is not the only one.
Now there are two deployment methods:

* Stand-alone deployment (recommended)
* Tomcat deployment (deprecated)

Stand-alone deployment is recommended option.
Explicit deployment to Tomcat is deprecated.

== See Also

* link:/faq/[Frequently Asked Questions]
