= Why is my bug not fixed yet? I have reported it weeks ago!
:page-wiki-name: Why is my bug not fixed yet
:page-wiki-id: 24084817
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2016-12-19T14:44:54.163+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2020-10-01T19:26:18.413+02:00

The short answer is: because you do not have https://wiki.evolveum.com/display/midPoint/Subscriptions+and+Sponsoring[midPoint subscription].

The long answer is ... well ... long.
MidPoint is a comprehensive system.
It is by far the biggest open source identity management and governance system currently available.
MidPoint can do almost anything that you may need.
Even though midPoint is open source and it is _libre_ ("free as in speech"), it is not necessarily _gratis_ ("free as in beer").
MidPoint is developed by professional developers that need to feed their families and pay their bills.
Nobody is going to give us free food and let us live in his house just because we work on open source software.
Evolveum is the company that funds vast majority of the development.
Evolveum is a self-funded company.
We do not have any rich investor or any other magic source of income.
All the money that we need for development, testing and bugfixing must come from midPoint subscriptions.

Therefore, it is perfectly natural we pay (much) more attention to the bugs that affect midPoint subscribers and contributors.
These are the people that keep midPoint project going.
After that, the next priority is maintenance of the system and development of new features.
This is absolutely crucial for midPoint to be an efficient long-term IDM solution - and this is the reason why the subscribers are paying their subscription fees.
The fixes of "community" bugs is the very lowest priority.
We will do what we can.
However, you have to understand that without subscribers there would be no midPoint at all.
Therefore, you have to wait until the developers are done with their work and have some free time for the community.
This can be a very long wait.
The entire development team is usually very busy and there just is no free time to dedicate to the community.
It may happen that the low-impact bugs will remain unfixed for many years.
Even though we are trying to do our best we still need to play by the rules of market economy, and we haven't found any better way how to fund the development yet.

If you want the bug to be fixed there are two reliable methods:

* Get midPoint subscription.
Right when you activate your subscription your bug will become a priority.
In addition to that: if we have more money from the subscription we can hire more developers to work on midPoint.

* Fix the bug yourself and contribute the fix.
MidPoint is always open to contributions.

== See Also

* xref:../i-have-found-a-bug/[I have found a bug]
* xref:/faq/[Frequently Asked Questions]
