= Design
:page-since: 4.8
:page-toc: top

WARNING: This page is a work in progress.

== Introduction

This document contains description of design for upgrade features and related components.

== Terms definition

. _Old midpoint_ - Version of midPoint currently running.
. _New midPoint_ - version of midPoint to which we plan to upgrade.

== Upgrade steps

Upgrade process will have two main phases.
First phase can be started while old midPoint is still running.
Second phase will be started after midPoint was shut down and is ready for main upgrade.

=== First phase:

. Verify installation details
.. Version checks for midPoint and database schema
. Verify objects in midPoint
.. CSV output with warnings, schema issues and changes that will be done during upgrade
.. XML dump of raw schema changes

*Notes regarding first phase*

* Schema will be updated in last 4.4.* and 4.7.* to be able to handle schema changes and parsing

=== Second phase:

. Check current midPoint status, whether it's down
. Download distribution
. Upgrade database schema
.. MidPoint internal repository
.. Audit database
. Upgrade _midpoint.home_ directory
. Upgrade objects in midPoint repository (more details in xref:_verification_and_upgrade_of_midpoint_objects[])
.. Initial objects
.. All other based on CSV from first phase (if it's available)
... There will be option to skip object update

*Notes regarding second phase*

* Tasks doesn't have to be suspended before starting second phase, because midPoint will not run during this phase - only repository will be initialized.
* Resources using bundled connectors (CSV, DBTable, LDAP related) should be upgraded to use new connector version
** Old connector xml should be removed (the one which will not have JAR library available after upgrade)
* Audit DB schema and data upgrade is expected to be schema compatible, fast.
No data upgrade expected.
** Potential option is via renaming existing tables and creating correct new ones

== Ninja notes

* Switch to Spring shell & batch seems to be overkill
** JCommander + JANSI is good enough

== Verification and upgrade of midPoint objects

#TODO#

=== Verification

#TODO#

=== Upgrade of initial objets

#TODO#

=== Objects upgrade

#TODO#

=== Upgrade of resources referencing bundled connectors

#TODO#

== Opened Questions

* Currently, only warning to log - if schema migration exist, else exception is thrown.
* Objects upgrade in database
** What if we want to dry run objects upgrade to review changes?
*** I'd verify objects and execute upgrade on them but then store delta in h2 table (as report from tool).
How to dump delta otherwise for many objects?
* How can upgrade tool upload objects (with recompute) if we're only on repo layer?
* How to wrap up upgrade after new version was started
** What if upgrade process needs to recompute something?
* Initial objects
** diff previous version with next (how to display changes)
** diff next version with current state of repository (how to display delta)

