= Manage Resources in midPoint
:page-nav-title: 'Resources'
:page-display-order: 10
// :page-toc: top
:experimental:
:icons: font
:icon-set: fas

Resources represent applications and information systems connected to midPoint, where resource accounts are managed.

This section contains guides to help you work with resources in the midPoint web administrative interface (GUI).

- xref:./create-resource/[]
- xref:/resource-mappings[Resource mappings TBD]
- xref:/resource-mappings[Correlations TBD]
- xref:/object-type-filtering[Filter and classify resource data via object types]
- xref:./resource-templates/[Create templates for resources TBD]

To list all defined resources or create a new one:

* Click icon:database[] *Resources* > icon:database[] *All resources* in the main menu.

The resources are displayed in a table with basic details:

* Name (in midPoint)
* Connector type
* Version (of the connector)
* Buttons to test, edit, remove the particular resource, and more

You can sort the resource list by name by clicking on the table column header. Reverse the sort order by clicking the header again.

For more information on connectors, refer to the xref:/connectors/[].
