= slapdconf
:page-wiki-name: slapdconf
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2015-04-27T20:34:12.577+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2015-04-27T20:34:12.577+02:00
:page-upkeep-status: green

Administration of OpenLDAP is not exactly easy.
Therefore we have created an `slapdconf` utility to simplify some OpenLDAP administration tasks.
We find `slapdconf` to be an essential survival tool in the OpenLDAP world.

Slapdconf can be downloaded from the source code repository: https://github.com/Evolveum/slapdconf
It is a Perl script.

The script needs some common Perl libraries: `Net::LDAP`, `Authen::SASL` and perldoc.
The libraries can usually be installed from OS packages.
For example, this how to install them on Ubuntu:

[source,bash]
----
sudo apt install libnet-ldap-perl libauthen-sasl-perl perl-doc
----

Slapdconf has a comprehensive help message:

[source,bash]
----
slapdconf --help
----

In Ubuntu, the default OpenLDAP package (`slapd`) is pre-configured to tread the `root` user as LDAP server administrator.
Therefore the easiest way to configure OpenLDAP is to run `slapdconf` as root:

[source,bash]
----
sudo slapdconf list-suffixes
----

This is using the default `slapdconf` setting, which is to use `ldapi:///` endpoint of OpenLDAP and EXTERNAL SASL authentication.
The `ldapi` endpoint may not be enabled by default.
In Ubuntu, it can be enabled by modifying `SLAPD_SERVICES` line in `/etc/default/slapd` file.

== See Also

* link:https://github.com/Evolveum/slapdconf[https://github.com/Evolveum/slapdconf]