= Bundled Support
:page-wiki-name: Bundled Support
:page-wiki-id: 34570366
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2019-07-15T11:59:37.945+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-07-15T13:20:10.774+02:00
:page-moved-from: /midpoint/support/bundled-support/

== Bundled Components

MidPoint distribution contains several components that are not strictly part of the midPoint core product.
Those _bundled components_ include:

* Bundled connectors (LDAP, Active Directory, CSV and DatabaseTable)

* Configuration and code samples

* Generated documentation

Generally speaking, such components are provided in a good faith that they will assist midPoint users.
However, only a very limited support is provided for those components.

Documentation, configuration and code samples are only covered by "reasonable effort" support.
This means that we will consider correcting those components if needed.
However, the priority will be usually quite low.
And we may postpone the fixes for quite a long time in case that the fix is not efficient at the present time or in case that there not enough resources to dedicate to the job.

The connectors are covered by midPoint support.
But the support has its limitations:

* xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] is supported only for those operations that are part of LDAPv3 standards.
Non-standard operations, extensions, controls and any vendor-specific behavior are not supported.

* xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector] is supported for AD DS 2012R2.
Only some AD features are supported.
PowerShell scripting is supported only for usual AD-related maintenance tasks.
Use of PowerShell scripting for provisioning Exchange accounts is not supported.

* xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable Connector] is supported only for standard SQL operations and standard database schemas.
Non-standard database operations and vendor-specific behavior is not supported.

* xref:/connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/[CSV Connector] is supported only for local files on standard local filesystems in Linux and Windows environment (ext4 and NTFS file systems).
Other operating systems are not supported.
Network file systems and unusual (experimental) filesystems are not supported.

This list provides just a quick summary of the limitations.
Please see individual connector pages for all the details regarding all support limitations.

Those limitations apply to "bundled" support, which means the support contract for midPoint system is which connector support is not negotiated explicitly.
However, we *strongly recommend* to explicitly negotiate support for specific LDAP servers, databases, AD versions and operating systems.
In that case we can extend such "bundled" support and we can support specific LDAP servers, databases and operating systems.
This is the way how to make sure that that the connectors will work reliably in your environment.
Such information also provides data for our support team.
We can use such data to build QA environments that reflect the most frequently-used servers and operating systems.
This allows us to make midPoint better.

[TIP]
====
This description applies to support and subscription contracts that were established after the release of midPoint 4.0. For earlier contracts the support details may differ.
In case of doubt we recommend to contact Evolveum representatives.
====

== Non-Bundled Components

There are other components that are often used with midPoint, but those are not bundled into official midPoint distribution.
Those components include:

* xref:/midpoint/tools/studio/[MidPoint Studio]

* MidPoint Java Client

Generally speaking, support for those components is *not* included in standard midPoint support contracts.
This kind of support is usually included in platform subscriptions and similar subscription contracts.
However, we are aware that midPoint Studio used quite often.
Therefore we will apply the "reasonable effort" rule for the Studio support even for ordinary midPoint support contracts.

=== Deprecated Components

Following components were never included in the bundled support, and they are now deprecated:

* xref:/midpoint/reference/legacy/eclipse-plugin/[MidPoint plugin for Eclipse IDE]

* xref:/midpoint/reference/legacy/jaspersoft-studio/[MidPoint-specific integration for Jaspersoft Studio]

== See Also

* xref:/support/subscription-sponsoring/[Subscriptions and Sponsoring]