= Evolveum Support For Systems Connected to MidPoint
:page-nav-title: Connected Systems
:page-since: "4.4"

This page summarizes Evolveum support policy regarding systems connected to midPoint.
This applies to xref:/connectors/[identity connectors] and the systems connected using the connectors.
The same policy applies to all integrations, such as xref:/midpoint/reference/resources/manual/itsm-plugin/[plugins for ITSM systems], asynchronous messaging integrations.

As a general rule, Evolveum supports only such systems that are actively *supported by their vendor under a regular support program*.
This means that Evolveum will not support versions of the systems that are in _end of life_ or _end of support_ state.
This rule applies to open source projects as well.
Open source systems will be supported by Evolveum only as long as project maintainer declares support for a particular versions, or as long as regular updates are released for such version.

Also, Evolveum will *not* support systems that are under _extended support_, _legacy support_, _vintage support_ or any similar premium support service provided by their vendors.
Such systems are *not* supported under regular midPoint support programs.
These systems may be supported under special-purpose support programs provided by Evolveum, if such thing is explicitly negotiated in the contract.
Please contact Evolveum sales for the details.

Evolveum will not announce deprecation of a support for a particular version of a system.
Support will be dropped immediately, as soon as Evolveum learns that particular version is in _end of life_, _extended support_ or similar state.
It is a best practice to watch status of systems that you are operating, therefore you will probably learn about the imminent end of support before we do.

Evolveum is *not* promising to support _all_ versions of a particular system that are supported by the vendors.
Only selected versions of a particular system may be supported.
When we provide support for a particular version of a system, we need a way to test midPoint, connector and all the other intermediary components with that particular version of the system.
Our testing environment is not unlimited, and we may be able to test only some versions of the system.
Please see documentation of a connector or a plugin for the details.

Support for particular connector or plugin or any other integration method has to be purchased separately from Evolveum, it is not bundled into regular MidPoint support.
The only exceptions are support for xref:bundled-support.adoc[bundled components].

Please note, that the support is provided for _integration_ components, such as connectors and plugins, not for the target system itself.
Evolveum does not provide support for databases, directory services or any other systems integrated with midPoint.
Such support has to be purchased from vendors of such systems.
Evolveum will cooperate on resolution of integration issues, but we will not provide support for the target systems itself, we are not responsible for appropriate set-up and configuration of the target system, we are not responsible for network, operating system and similar issues.
Evolveum may suggest some aspects of target system configuration or operation.
However, these should be considered suggestions only, without any guarantees of correctness or completeness.
Configuration of most systems is a complex matter, requiring understanding of use-cases, broad environment and limitations, which is way out of scope of our responsibilities.
We will gladly help you with integration issues, but you need to have the target system under your control.
