= MidPoint Subscriptions and Sponsoring
:page-nav-title: Subscriptions and Sponsoring
:page-wiki-name: Subscriptions and Sponsoring
:page-moved-from: /midpoint/support/subscription-sponsoring

MidPoint is developed by a team of professional developers with the help of the community.
Vast majority of midPoint development is done by the developers affiliated with Evolveum, the company that started midPoint project and funded early midPoint development.
MidPoint development is now in a sustained phase.
In other words, midPoint development has to pay for itself.
Evolveum is not an investment-fed start-up.
Evolveum is an established self-funded company.
Every cent that Evolveum pays its developers needs to come from the Evolveum business income.
There is no free lunch.
Not even in open source.

MidPoint is evolving, and it will evolve.
However, most of the effort the Evolveum invests to midPoint goes to its maintenance.
In other words the money that we have available are primarily invested to midPoint _quality_, not features.
Funds for new features must come from the customers.
Someone has to pay for it.
Therefore, if you are xref:/faq/i-need-new-feature.adoc[missing a feature] in midPoint you can sit and wait.
However, you will be probably waiting for quite a long time as we will use all of our available resources to satisfy paying customers.
Sitting and waiting is not going to help much.
You need to take an action to make sure your requirements are satisfied.
You have to become midPoint *subscriber*.

Evolveum has several link:https://evolveum.com/services/[subscription programs].
Some of those programs are especially designed to cover development of new features.
If you are interested, please link:https://evolveum.com/about-us/contact-us/[contact us].
Well will discuss what options are available for you.


== See Also

* xref:/faq/i-need-new-feature.adoc[]

* link:https://evolveum.com/about-us/contact-us/[Contact Us]
