= Override incorrect source data
:page-nav-title: 6. Rectify source data
:page-display-order: 600
:experimental:
:icons: font
:page-description: Sometimes, you may need to manually take over the target systems and overwrite the data coming from the source system. This sections explains how to go about it.

In the beginning, there was the Single Source of Truth…

[quote]
One source to rule them all, +
one source to find them, +
once source to bring them all, +
and in the truthfulness bind them.

You have configured midPoint so that all data incongruent with the source system are overwritten and rectified to establish all-encompassing consistency.

But one day, you have found yourself in need of denying the source system the power over all, take the situation into your own hands, and rewrite attributes in a target system to values different than the _Truth_ coming from the Single Source of Truth.

On that day—it was a rainy Friday evening—an employee went rogue.
The malicious user had to be deactivated right away.
It was out of question to wait till Monday when the people from HR would come to work and deactivate him in the HR system properly.
It had to be done _now_.
Fortunately, an IT admin was still on duty to handle the situation.

Head over to the module on xref:/midpoint/methodology/first-steps-training/override-incorrect-source-data/override-user-status/[overriding malicious user status] to learn how the story develops.