= Access Request Process
:page-nav-title: Access Request
:page-display-order: 300
:page-toc: top
:toclevels: 3
:sectnums:
:sectnumlevels: 3

WARNING: This page is a stub, it is a work in progress.

Technically, the Access request process is self-service process of assignment management - their creation, removal and modification. The assignments are defined on assigning roles #or applications#.

== Concepts and terminology

Role request process is designed to be managed, documented and measurable from beginning to end - from role request, through approval, till all provisioning steps are performed. Manual steps are part of the role request monitoring. Role request is finished when all automatic and all manual components are done successfully.

The process is designed as clear as possible::
Exceptions are to be managed by IGA administrator.

One request is processing assignment/removal/modification of one role::
This will decrease complexity of the role request approval, management and troubleshooting. On contrary, it will (significantly) increase number of individual notification and approval steps. As a countermeasure, UI must provide means for easy/fast review of multiple requests on one page and multiple request approval.

Requests are created for operations generated via self-service UI and related REST calls only::
Admin interface operations should not generate requests. IDM administrators manage multiple users. Their work is to perform large cleanups and modifications. Of course, cases for manual operations will be generated even based on such operations.

Process will support delegated administration::
Roles can be requested by the user for himself/herself, or for somebody else. Specific privileges will be needed for this. This feature allows management of access for whole team.

Types of operation::
The table lists types of operation that may appear and how to handle them. We are combining who is requesting, for whom is request done and what operation is being performed.

.Types of operation
[options="header", cols="10,10,15,5,30"]
|===
|Who | To whom | Operation | Approval / Notification | Note

|End user |-self- |Role assignment
|Yes/Yes
a| Standard role request process with approval.

|End user |-self- |Role removal
|No/Yes
a| No approval for removal. +
Decreasing of number of approvals. If needed for particular roles it may be enabled.

|End user |-self- |Change of assignment parameters
|Yes/Yes
a|Examples: +
- Change of team in the cloud team space +
- Increase of role assignment validity +
NOTE: Supported in UI, but not nice.

|End user |Other user |Role assignment
|Yes/Yes
a|Standard approval. +
Additional approval by the affected person may be needed.

|End user |Other user |Role removal
|No/Yes
a|No approval for removal. +
Decreasing of number of approvals. If needed for particular roles it may be enabled.

|End user |Other user |Change of assignment parameters
|Yes/Yes
|Standard approval.
|===


== Process details

#TODO#

// sem tiez use interface - linky na to, ako by malo vyzerat.

== Process Monitoring and Optimization

// sem moznosti, ako je mozne proces monitorovat - co vsetko merat a ako.
#TODO#

== Troubleshooting of the process

// sem to, ze musime podporit delegovanu administraciu tak, aby specializovani admini pre proces vedeli osetrovat vypadky v procese
// proces nebude zlozity, exceptions budu osetrovane ad-hoc -> postupne sa vybuduje knowledge base ako tie veci riesit. -> a veci sa mozu doplnit
#TODO#

== Process example

// tuto prejst na prikladoch, ako by taky proces vyzeral, co by bolo potrebne urobit
#TODO#