---
layout: connector-page
display-order: 500
functionality-status: experimental
development-status: dormant
support-status: unknown
origin: Evolveum
target-systems: Box cloud services
connector-protocol: REST
source-url-master: https://github.com/Evolveum/connector-box-rest
description: Identity connector for Box cloud services.
connid-bundle-name: com.evolveum.polygon.connector.box.rest
upkeep-status: yellow
---
= Box Connector
:page-wiki-name: Box Connector
:page-wiki-metadata-create-user: ksuchanovsky
:page-wiki-metadata-create-date: 2017-09-18T16:48:47.217+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-07-09T14:52:09.038+02:00

NOTE: This connector is not finished.
It was using experimental extension to ConnId framework that haven't passed internal review and was dropped.
This connector will not work without investing an effort to complete the development.

Box Connector for midPoint is REST connector which support basic CRUD operations for accounts, groups, folders and operations related to group as membership (group and users) or collaboration (group and folders). Connector was implemented for ConnID branch results-handler-modification.

== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| Provisioning
| YES
|

| Live Synchronization
| NO
|

| Password
| NO
|

| Activation
| YES
| Only for Account Object Type

| Paging support
| YES
|

| Native Attribute names
| YES
|

| Scripting
| NO
|

|===


== Licensing

The connector itself is available under the terms of Apache License 2.0. To our best knowledge there is no extra license needed to use this connector.

== History

[%autowidth]
|===
| Version | Origin | Binary | Samples | Sources | Build Date | Framework version | Description

| 1.0
| Polygon
| Download jar
| link:https://github.com/Evolveum/midpoint/tree/master/samples/resources/box[GitHub]
| link:https://github.com/Evolveum/connector-box-rest[GitHub]
| September 18th 2017
| 1.4.2.14-SNAPSHOT(branch results-handler-modification)
| Stable version

|===


== Known limitations

Connector operates with some limitations, which were detected during implementation:

* Connector doesnt support filters such as ContainsFilter, StartWithFilter, EndsWithFilter,  AndFilter, OrFilter, NotFilter etc.

* Avatars are supported only for inbound of Account Object Type

* NAME of Account Object Type doesnt support chracters  and

* LOGIN  of Account Object Type doesnt support chracter -'

* Attribute STATUS support only values active (enable) and inactive (disable)

* Maximum length of Name attribute is 50 chracters

[NOTE]
====
Its recomended to enable filteredResultsHandler in configuration because of lack support of query filters
====

== Filters

Connector supports following filters:

[%autowidth,cols="h,1,1"]
|===
|  | EQUALS | STARTWITH

| Account Objects
| UID
| NAME

| Group Objects
| UID
|

| Folder Objects
| UID
|

|===


== Configuration

Box connector requires following property fields so please follow the steps below:

* ClientId

* ClientSecret

* RefreshToken

* AccessToken

* BoxHTTPEndpoint

=== Configuring resource

. Obtain credential codes for Box API. Register at developer.box.com

. Create new Custom App with standard OAuth 2.0 User Authentication

. Set Redirect URI e.g. http://127.0.0.1 and select at least Manage users, Manage groups and Manage enterprise properties options in Application Scopes checkbox.

. In order to authenticate with Box you will also need refreshToken and accessToken. To retrieve it, go to your Box-connector java project and run Main class. Follow the steps described in console. +

. You now have all the information you need to configure the connector resource in the midPoint.


== Tests

Methods for connector testing are divided into the clasess according to correspond Object Type. These classes are located in test package.Before running the test methods please fill the required values as:

* ClientId as in configuration,

* ClientSecret as in configuration,

* RefreshToken current valid state of refreshToken,

* AccessToken  current valid state of accessToken,

* BoxHTTPEndpoint  as in configuration,

in each of testing class.

* invalidRefreshToken invalid or expired refreshToken,

* invalidAccessToken invalid or expired accessToken

in account testing class.Basic tests use attributes with values containing valid special characters (subset of 'ľščťž$#@%^*(?' ) for create, update operation tests and schema consistency test. Filtering and listing tests are divided into methods according to possible filters and options for each object type.