= Solution Architecture of Data Provenance Features

Data provenance is all about _meta-data_: data about data.
Simply speaking, we have to maintain meta-data about every data item.
For example, midPoint may learn that a name of particular person is `John Doe`.
It is not enough to just store that value in our database.
We need to remember when we have learned that value, from which system it came, we may need to remember how reliable that value is (e.g. how it was verified) and so on.
MidPoint is an identity management system, therefore the value is likely to be transformed and provisioned to other systems.
We may want to remember how the value was transformed and which mappings were used.
We want to maintain information about the original source of the value all the way, through all the transformation, for all the copies of the data.
Finally, we have to display the meta-data values in the user interface.

== Metadata Schema

However, meta-data add a whole new dimension of complexity: we have to maintain meta-data for each and every value of every data item.
For example if we maintain three values for a telephone number, we have to main three separate sets of meta-data, one for each value.
Which means maintaining complex meta-data structures for simple string data values.
This is very difficult to do with a conventional data modelling languages.
MidPoint was using XML Schema Definition (XSD) language since the very beginning.
However, XSD falls a bit short in several ways.
But when it comes to meta-data, XSD is not suitable at all.

We have been link:../existing-languages-analysis/[looking for existing data modelling languages] with the hope to find a language that is more suitable for this task.
However, all popular schema languages seem to be focused in modelling data in a particular format (XML, JSON) rather than describing an abstract data model.
We estimate that we would need to significantly "bend" the language to suit even the basic needs of midPoint data modelling, in a similar way that we have modified XSD.
This would be a lot of effort that will not move us forward in any significant way.
What is even less favorable is that none of the existing languages have any signs of meta-data schema (meta-schema) support.

Therefore we have decided to create link:../axiom/[Axiom] - a new data modeling language.
The ambition is to replace XSD in midPoint by Axiom.
However, the first practical use of Axiom will be definition of _meta-schema_: schema for meta-data.
The meta-schema defines data structures that will be maintained as meta-data for every value of an ordinary schema.

But when it comes to meta-schema, there is one big problem.
There is no standard for data provenance meta-data.
Every deployment is likely to work with a different set of meta-data.
And even if there was a standard, it is almost certain that the meta-schema has to be adjusted for every deployment.
Therefore midPoint user (or rather _deployer_) needs a simple way how to adjust and extend meta-schema to the need to a particular deployment.
MidPoint already has a mechanism to extend existing schema by defining schema _extension_.
We would like to reuse the same concept for meta-schema.
Our plan is to create a pre-defined meta-schema with basic meta-data structures that are likely to be used in almost all deployments.
MidPoint deployment will have ability to extend that meta-schema with custom meta-data items to suit their deployments.

MidPoint data handling is based on https://wiki.evolveum.com/display/midPoint/Prism+Objects[Prism framework].
Fortunately, we have foreseen the need for meta-data and Prism has a concept of `PrismValue` class.
`PrismValue` is maintained for every value of every data item that goes through midPoint.
This is a suitable place to wire meta-data with data.

== Mappings

Meta-data support is a basic building block, but we also have to populate the meta-data.
MidPoint is using https://wiki.evolveum.com/display/midPoint/Mapping[mappings] to populate and transform the data.
We plan to re-use the concept to populate and maintain the meta-data as well.

== User Interface

MidPoint user inteface is completely schema-aware.
Most parts of user interface are dynamically generating forms based on data definicions (schema).
We would like to reuse this ability to display meta-data.
The preliminary plan is to add buttons to the input fields in user interface that will display meta data.
The meta data will be shown in generated forms that are generated according to meta-schema definitions.
However, we will need to evaluate whether this approach will provide acceptable user experience.
This evaluation is one of the motivation for this project, as we expect that several iterations may be needed to get the user experience part of the system right.

== See Also

* link:../identity-metadata-in-a-nutshell/[Identity Metadata in a Nutshell]: Introduction to identity metadata and metadata implementation in midPoint.
* link:../axiom/spec/[Axiom Specification]: Specification of Axiom language that is used to model metadata in midPoint
* link:../challenges/[Challenges of Data Provenance]: Documentation of challenges that we have faced during the project.
