= Axiom Design Notes

_Axiom_ is a new data modelling language for Prism and midPoint.
It is developed as part of midPrivacy project.

== Requirements

* Similar basic capabilities than existing schema languages:

** Primitive data types (approx. the level of support of XSD primitive types used by midPoint)

** Complex data types (including support for data types, equivalent to complex types in XSD)

* Insensitive to element ordering

* Extensibility points: ability to extend the data model in runtime.

* Human-readable and preferrable human-friendly.

* Optional complex data "keys" instead of current container identifiers.

* ItemPath concept should remain almost the same.

* Support for objects (identified by OID) and object references.

** Tip: think about "RESTifying" the model.
What happens if the data are exposed in REST?
Would it make sense to replace OIDs with URIs/URLs?
Think about _semantic web_ concepts.

* Support for semantic versioning of the model

* Built-in support for lifecycle properties: `since`, `deprecated`, `plannedRemoval`, etc.

* Support for meta-data (e.g. provenance meta-data). Meta-data schema extensible in runtime.

* Support for "rich" primitive types such as polystring and protected string.

* Built-in documentation support (similar to xsd:documentation, but maybe we would prefer asciidoc?)

* Ability to add custom annotations (similar to XSD annotations)

* Idea: consider data lifecycle/retention.
E.g. we have _operational_ data that are computed.
We have meta data that are _transient_ (not stored) and _persistent_ (stored).
Maybe we can somehow merge and generalize those concepts?

* Question: what about data presentation?
E.g. do we want support for human-readable labels for data model items?

* Tip: think about how new query/filter language can be aligned.

* Tip: think about how midPoint bulk action language can be aligned.

* Tip: think about "natural" representation of objects (non-XML/JSON/YAML).

* Nice to have: ability to define itself (such as XSD syntax can be specified in XSD).

== Why We Do Not Just Use XSD?

#TODO#: Why we do not use XSD, JSON Schema, YANG, SCIM schema, ...
