= Data Provenance Prototype Challenges

== Provenance Metadata

How to *structure built-in meta-data* schema for midPoint?
The metadata that we had in midPoint 4.0 (`MetadataType`) evolved quite spontaneously over the years.
It has to be improved.
We need better structure.
But it looks like there is no standard for meta data.
There is some work in progress (http://www.metadata2020.org/), but nothing that is ready to use.

== Axiom

Axiom was motivated by a lot of *challenges with XSD*, documented in https://evolveum.com/a-road-to-axiom/[blog post].

*Namespaces* are a big nuisance for users, they complicate the modelling.
But they are still useful when several models are mixed.
And in the XML world they were used for compatibility indication and versioning.
How we can dead with namespaces?
Should we abandom them?
Should we hide them from user?

How do we *identify the model*?
Model name, that is difficult to make unique?
Or do we use (namespace) URI?
It can be easily made unique, but it is difficult to use.

== User Interface

How do we display the meta-data in a way that is understandable for users?
When to display meta-data at all?
Provenance data can be complex and they are maintained for every value.
We certainly cannot display them all the time, this would make the user interface very complicated.

== Open Questions and TODOs

Terminology: "Schema" vs "Model". Are those the same?

Three conceptual layers:

* Axiom: abstract data modeling, data types, items, object, schema versioning

* Prism: Basic object structure, deltas, query language, expressions

* MidPoint: IDM-specific data structures

The question of object identifier: UUID? URI? Mapping between UUID and URI?
UUID is better for local use.
But we want to be Web/REST-friendly.
URI/URL will be needed for that.
