= Data Provenance Prototype Challenges

== Provenance Metadata

How to *structure built-in meta-data* schema for midPoint?
The metadata that we had in midPoint 4.0 (`MetadataType`) evolved quite spontaneously over the years.
It has to be improved.
We need better structure.
But it looks like there is no standard for meta data.
There is some work in progress (http://www.metadata2020.org/), but nothing that is ready to use.

It looks like there is almost no scholarly literature on identity provenance.
Designing _provenance_ data structures proved to be a challenge.
It was more difficult than expected, several iterations were needed to get usable design draft.
We need just right amount of provenance metadata to store.
We cannot store everything, otherwise the data storage requirements would be unreasonable.
It was also difficult to align provenance with other planned data protection features, notably lawful basis management.

== Axiom

Axiom was motivated by a lot of *challenges with XSD*, documented in https://evolveum.com/a-road-to-axiom/[blog post].

=== Namespaces

*Namespaces* are a big nuisance for users, they complicate the modelling.
But they are still useful when several models are mixed.
And in the XML world they were used for compatibility indication and versioning.
How we can deal with namespaces?
Should we abandon them?
Should we hide them from user?

*Solution:* We need namespaces, but we need them at the right places.
E.g. we do not need a namespace for every item (element), as we can compute that any time from the model.
But we need namespaces (or _context_) for top-level element, to reliably identify the model.
We also need namespaces for augmentation, as we want to make sure that the models do not conflict.

See also link:axiom/namespaces/[Axiom Namespaces]

=== Model Identification

How do we *identify the model*?
Model name, that is difficult to make unique?
Or do we use (namespace) URI?
It can be easily made unique, but it is difficult to use.

*Solution:* We want to use namespace URI for model identification.
It is a simple and straightforward way.
We can make it less ugly by minimizing the number of times that the URI needs to be specified.

Question: what about model names? Do we need them? How to use them?

Answer: Name are useful for diagnostics. They also make a nice default prefix.

=== MidPoint Resource Schema and Shadow Attributes

Each midPoint resource is bringing its own schema.
How to use it cleanly?
Should each resource schema use a separate namespace?
That is perhaps a clean way, but it may be difficult for the users.
What we should do?

== Metadata Mapping

Integrating link:processing/model/thoughts/metadata-mapping-model/[meta-data mappings] in midPoint proven to be more challenging than we have expected.
One part of the problem was specification of metadata mappings (i.e. where to set up the mappings), but that was resolved with a relative ease.
There was another and slightly unexpected aspect of the problem: value consolidation.

MidPoint is designed to work in a very generic way.
It assumes that there may be many values, originating from many sources, transformed by many mappings stored in multi-value data items.
The same value may originate from several sources, some values may be conditional (such as "initial" value that are set only wne no other value is set), some values may be overidden by others and so on.
This creates quite a complicated system which is at the heart of midPoint's flexibility.
However, all the values must "collapse" to become an ordinary data item at the end.
This final step is referred to as value _consolidation_.

Value consolidation is a complex process, but metadata adds additional dimension of complexity.
The same value may come from several sources.
While the (data) value is the same, metadata may be completely different for each source.
As values are merged together in a consolidation process, metadata need to be merged too.
And this is not always easy to do.

We had to adjust the design of provenance metadata to reflect the consolidation process.
Provenance metadata are built into midPoint core schema.
However, other metadata structures may be completely custom and there is no generic way how to consolidate them.
For example, assurance metadata are likely to choose the highest assurance level to get a single-value assurance metadata for consolidated value.
While other metadata types may merge values from all the sources into a multi-value metadata item, to keep track of all the sources.
There is no generic way.
Therefore we had to specify custom _consolidation mappings_ for metadata types.

It was also challenging to fit this concept into existing midPoint code base.
MidPoint computation engine (known as _Projector_) conducts the computation is several phases.
Each phase had its specifics and special behavior, mostly due to historical reasons.
Existing code had to be link:processing/model/plain/[explored in depth, documented] and improved before metadata consolidation code could be added.

== User Interface

How do we display the meta-data in a way that is understandable for users?
When to display meta-data at all?
Provenance data can be complex and they are maintained for every value.
We certainly cannot display them all the time, this would make the user interface very complicated.

== Open Questions

Terminology and keywords: extension/extends/uses or augmentation/inherit/use? Answer: augmentation/subtyping/inclusion.

minOccurs/maxOccurs or required/multivalue?

Three conceptual layers:

* Axiom: abstract data modeling, data types, items, schema versioning, identifier, path(?), metadata

* Prism: object, basic object structure (oid,name), containers (with identifiers), properties, object referecences, deltas, query language, polystring, expressions, item display properties?

* MidPoint: IDM-specific data structures, relation, orgstruct (also in query), special expression evaluators

The question of object identifier: UUID? URI? Mapping between UUID and URI?
UUID is better for local use.
But we want to be Web/REST-friendly.
URI/URL will be needed for that.

Is the identifier concept right? Especially the `space` thing, it looks like an implementation detail.
Should be use something more abstract?

Path and namespaces?

== TODOs

* Axiom item/container/property theory, definition of AxiomTypeReference and primitive types

* Are primitive types (e.g. string) extendable? Can we inhering from them? Can we augment them?

* Enumerations
