= Data Provenance Prototype Challenges

== Provenance Metadata

How to *structure built-in meta-data* schema for midPoint?
The metadata that we had in midPoint 4.0 (`MetadataType`) evolved quite spontaneously over the years.
It has to be improved.
We need better structure.
But it looks like there is no standard for meta data.
There is some work in progress (http://www.metadata2020.org/), but nothing that is ready to use.

== Axiom

Axiom was motivated by a lot of *challenges with XSD*, documented in https://evolveum.com/a-road-to-axiom/[blog post].

=== Namespaces

*Namespaces* are a big nuisance for users, they complicate the modelling.
But they are still useful when several models are mixed.
And in the XML world they were used for compatibility indication and versioning.
How we can deal with namespaces?
Should we abandon them?
Should we hide them from user?

*Solution:* We need namespaces, but we need them at the right places.
E.g. we do not need a namespace for every item (element), as we can compute that any time from the model.
But we need namespaces (or _context_) for top-level element, to reliably identify the model.
We also need namespaces for augmentation, as we want to make sure that the models do not conflict.

See also link:axiom/namespaces/[Axiom Namespaces]

=== Model Identification

How do we *identify the model*?
Model name, that is difficult to make unique?
Or do we use (namespace) URI?
It can be easily made unique, but it is difficult to use.

*Solution:* We want to use namespace URI for model identification.
It is a simple and straightforward way.
We can make it less ugly by minimizing the number of times that the URI needs to be specified.

Question: what about model names? Do we need them? How to use them?

Answer: Name are useful for diagnostics. They also make a nice default prefix.

=== MidPoint Resource Schema and Shadow Attributes

Each midPoint resource is bringing its own schema.
How to use it cleanly?
Should each resource schema use a separate namespace?
That is perhaps a clean way, but it may be difficult for the users.
What we should do?

== User Interface

How do we display the meta-data in a way that is understandable for users?
When to display meta-data at all?
Provenance data can be complex and they are maintained for every value.
We certainly cannot display them all the time, this would make the user interface very complicated.

== Open Questions

Terminology and keywords: extension/extends/uses or augmentation/inherit/use? Answer: augmentation/subtyping/inclusion.

minOccurs/maxOccurs or required/multivalue?

Three conceptual layers:

* Axiom: abstract data modeling, data types, items, schema versioning, identifier, path(?), metadata

* Prism: object, basic object structure (oid,name), containers (with identifiers), properties, object referecences, deltas, query language, polystring, expressions, item display properties?

* MidPoint: IDM-specific data structures, relation, orgstruct (also in query), special expression evaluators

The question of object identifier: UUID? URI? Mapping between UUID and URI?
UUID is better for local use.
But we want to be Web/REST-friendly.
URI/URL will be needed for that.

Is the identifier concept right? Especially the `space` thing, it looks like an implementation detail.
Should be use something more abstract?

Path and namespaces?

== TODOs

* Axiom item/container/property theory, definition of AxiomTypeReference and primitive types

* Are primitive types (e.g. string) extendable? Can we inhering from them? Can we augment them?

* Enumerations
