= Outcomes Of MidPrivacy: Provenance

This is a summary of outcomes of first phase of link:../..[midPrivacy initiative]: link:..[Data Provenance Prototype].

WARNING: Work in progress

== Axiom

Key component of the solution is a data modeling language capable of expressing not just data models, but also metadata models.
We have been researching for an existing data modeling language that would fit our needs.
Unfortunately, there seems to be no popular or ready-to-use data modeling language with appropriate metadata modeling support.
This result was not very surprising.
Our team is struggling to adapt XML Schema definition (XSD) language for our purposes well over a decade.
Most popular data modeling languages provide capabilities that are roughly equivalent to XSD.
We have realized that we need to make a major leap in technology to satisfy our needs.
Therefore we have designed our own data modeling language: Axiom.

Axiom is a general-purpose data modeling language.
On the surface, Axiom is similar to XSD, JSON Schema or any other modern data modeling language.
But Axiom goes much deeper.
Axiom introduces a concept of _inframodel_ that allows data models to manipulate fundamental concepts of the language and data structures.
The concept of inframodel was used to define _metadata models_.
This approach is used in Axiom to model all the metadata for midPoint.
As far as we know this is a very unique approach, an approach that we have not seen in any existing language.

We have invested significant amount of time and effort to design Axiom.
We have expected that designing a new data modeling language will not be easy.
Existing languages could not be used for inspiration when designing the crucial "meta" and "infra" concepts.
It took several design iterations and some amount of rework to get to Axiom 0.1 specification.

Overall, Axiom is a very promising development and we are very enthusiastic about the results.
We have invested significant amount of time to create Axiom design, language specifications and prototype implementation.
We are aware that this is not yet the final version of Axiom and that we will probably have to make adjustements along the way.
However, we are quite optimistic, as we have chosen one of the most challenging scenarios (metadata) to validate viability of Axiom.

Relevant links:

* link:../axiom/spec/[Axiom Language Specification]
* link:../axiom/concepts/[Axiom Concepts] explains concept of Axiom _inframodel_
* https://github.com/Evolveum/midpoint/tree/feature/axiom/infra/axiom[Implementation of Axiom processors] in midPoint source code

== Metadata Schemas

Axiom provides capability to create metadata models.
However, we still need the actual models.
Initial analysis conducted before the first milestone of the project already indicated that there is no metadata or identity provenance schema that we could readily reuse.
Therefore we had to create suitable metadata schemas.

Design of some metadata schemas was relatively straightforward, especially the schemas that were specific to midPoint.
However, design of generic identity provenance schema proved to be particularly challenging.
There does not seem to be any broad agreement what provenance really means and how provenance metadata should look like.
We have spent significant amount of time designing the schema that can both suit the way how midPoint is dealing with data and that can express generic concepts of data origin and provenance.
We had to create link:../provenance-origin-basis/[rough design of future data protection features] to make sure our provenance concepts are at least roughly correct.
We ended up with a provenance metadata design that we believe could work.

We have put metadata schemas to work by implementing prototype code for metadata mapping and transformation.
This prototyping lead to a realization, that we need to fundamentally change the way how we deal with metadata.
As each data value may originate from several sources, the metadata need to be multi-valued (see below).

== Prototype Code

TODO: Axiom prototype, code generator
TODO: Schemas
TODO: Integration into midPoint, mappings, consolidation
TODO: GUI

== Market Evaluation

TODO: There is demand, but also a lot of uncertainty and confusion.

== Discoveries and Challenges

=== Metadata Multiplicity

=== Metadata User Experience

=== Data Protection

TODO: intimate relationship with data protection features

== See Also

* link:../future-work/[Future Work]
