= Installing MidPoint Server From Distribution Package
:page-nav-title: From Distribution Package
:page-wiki-name: Installing MidPoint Server
:page-wiki-id: 24676039
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2017-12-08T12:43:45.697+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-09-08T15:26:16.271+02:00
:page-display-order: 10
:page-upkeep-status: green
:page-toc: top

{% for v in site.data.midpoint-versions %}{% if v.status == null or v.status == "released" %}{% assign lastReleased = v %}{% endif %}{% endfor %}


This guide that describes how to install midPoint from Evolveum distribution package.
MidPoint will be installed as a server, intended for pre-production or production environment.
The guide assumes an ordinary server environment, running in a server operating system such as Linux.
This is suitable for the installation on a virtual machine or physical hardware.

This guide may be too complex if all you want is just to try midPoint.
In that case please see xref:/midpoint/quickstart[Quickstart guide].

There are also alternative installation methods, such as use of xref:docker/[Docker image] or installing from a xref:source/[source code build].

[TIP]
.MidPoint 4.0 and later
====
This guide applies to midPoint 4.0 and later.
For guides that apply to older releases please see the release notes.
====

== Before You Start

There are few things to check before you start the installation:

* Make sure to see xref:/midpoint/release/[Release Notes] for list of environments that are known to work and for the list of known issues in current release.

* Make sure the xref:/midpoint/install/system-requirements/[System Requirements] are met.

* Make sure you are using a supported version of midPoint.
When in doubt, use the latest midPoint release ({{lastReleased.version}})

++++
{% include release-install-prereq-j11.html release-version=lastReleased.version %}
++++

++++
{% include release-install-download.html this=lastReleased %}
++++

== Installation

=== Installing the Files

Copy the files to an installation directory.
Following directory locations are recommended:

[%autowidth]
|===
| Operating system | Installation directory

| Linux and other UNIX systems
| `/opt/midpoint`

| Windows
| `C:\Program Files\midpoint`

|===

Following instructions will refer to the relative paths inside the installation directory.

=== MidPoint Home Directory

xref:/midpoint/reference/deployment/midpoint-home-directory/[MidPoint Home Directory] is a filesystem directory that midPoint uses to store initial configuration, cryptographic keys, log files and similar "variable" content.
MidPoint home directory is located in the `var` subdirectory by default (e.g. `/opt/midpoint/var`).
This location is acceptable for many installations.
However, some installations may want to separate the static (read-only) parts of the installation and the dynamic (read-write) parts.
In that case the midPoint home directory may be moved to any suitable location.
This can be achieved simply by setting `MIDPOINT_HOME` environment variable (on UNIX systems) or manipulating the JVM options.
Please see xref:/midpoint/reference/deployment/midpoint-home-directory/[MidPoint Home Directory] and xref:/midpoint/reference/deployment/stand-alone-deployment/[Stand-Alone Deployment] pages for details.

MidPoint home directory may be moved even after midPoint is installed.
However, setting the directory correctly during installation may save a lot of work later on.

=== MidPoint Repository

MidPoint comes with an embedded database engine (H2) that is suitable for testing and demo installations.
This database will be used by midPoint after the installation unless other repository is specified.
However, the embedded database is *not* supported for production installations.
Therefore, for anything other than evaluation and demo installations, it is strongly recommended setting up a full-scale database engine.
PostgreSQL database is strongly recommended.
The xref:/midpoint/reference/repository/configuration/[] page provides the instructions.

== Post-Installation

=== Manual Run Control

MidPoint distribution package provides convenient scripts to start and stop midPoint service.
Those scripts are located in the `bin` directory.
The purpose of those scripts is to start and stop midPoint manually.
Those scripts are *not* interacting with any service control facility on operating systems (e.g. systemd).
Those scripts just start and stop midPoint process.

==== Linux (UNIX)

.Starting midPoint (Linux)
[source,bash]
----
./bin/start.sh
----

.Stopping midPoint (Linux)
[source,bash]
----
./bin/stop.sh
----

The `start.sh` and `stop.sh` scripts are just simple wrappers for `midpoint.sh` script.
The `midpoint.sh` script is where all the action happens.
This script can also be invoked directly:

.Using midpoint.sh script (Linux)
[source,bash]
----
./bin/midpoint.sh start
./bin/midpoint.sh stop
----

The `midpoint.sh` script will process the script `setenv.sh` if it exists in the same directory `(/bin`). The script is a convenient place for customizing JVM properties, for example:

[source,bash]
----
#!/bin/sh
export JAVA_OPTS="$JAVA_OPTS -Dmidpoint.nodeId=My_Node1"
----

The `midpoint.sh` script may provide more run control and diagnostics capabilities in the future.

==== Windows

.Starting midPoint (Windows)
[source]
----
bin\start.bat
----

.Stopping midPoint (Windows)
[source]
----
bin\stop.bat
----

The `start.bat` and `stop.bat` scripts are just simple wrappers for `midpoint.bat` script.
The `midpoint.bat` script is where all the action happens.

The `midpoint.bat` script will process the script `setenv.bat` if it exists in the same directory `(bin`). The script is a convenient place for customizing JVM properties.

=== Setting Up a Service

Proper way to run midPoint on a server is to register it to the operating system service control facility.
This procedure is inherently dependent on an operating system.
Following pages provide specific instruction for individual operating systems:

* Linux: xref:/midpoint/install/systemd/[Running midPoint with systemd]

* Windows: xref:/midpoint/install/windows-service/[Installing midPoint as a Windows Service]

== See Also

* xref:/midpoint/reference/deployment/midpoint-home-directory/[MidPoint Home Directory]

* xref:/midpoint/reference/repository/configuration/[]

* xref:/midpoint/reference/deployment/stand-alone-deployment/[Stand-Alone Deployment]
