= MidPoint Installation Guides
:page-nav-title: Installation
:page-wiki-name: Installation Guide
:page-wiki-id: 1310779
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2011-05-11T13:48:08.155+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-02-27T18:38:20.663+01:00
:page-display-order: 80
:page-upkeep-status: green

{% for v in site.data.midpoint-versions %}{% if v.status == null or v.status == "released" %}{% assign lastReleased = v %}{% endif %}{% endfor %}

There are several ways to install midPoint.
Each of the option require different set of step to cover.
The order of the options are set based on the complexity of them.

Please select the method that is most appropriate for your environment:

* *Containers* (recommended option) +
The fastest option how to have all the things done is to use pre-prepared containers.
It is the way we can help you to address the requirements as much as possible.
Also it is safe option to quickly deploy and clean up after run.
The environment dependency is covered (Java environment) so only repository has to be handled.
There is the best fit also for use case like tests or demo. +
Next to the released versions, there are prepared also the containers with development or support versions (including the correction for identified bugs).

** xref:../quickstart/[*Quick Start* installation] +
The easiest way how to start.
There are not describe the possibility of customization but on the other side there is minimum steps we need to have the environment up and running.

** xref:./containers[Installation using *Docker image*] +
The description covering the customization of the configuration.

[NOTE]
====
Independently on the selected install option there are available several version(s).
Next to the supported released versions there are available also snapshots - support branch.

Currently last released version is {{ lastReleased.version }}.
Until the next release there are bug fixes cumulated on support branch.
E.g. for the release 4.8(.x) the relevant support branch is support-4.8.
====

For the traditional approach of the installation we are providing information about bare installation.
The most probably if you don't know the reason for these options right away it is not the best one for you...

* xref:./distribution/[Installation from *distribution package*] +
There is prepared package with the binary (compiled) files which is ready for the deployment.
All the requirements has to be explicitly covered during the installation / before the start. +
There are automatically build also the development versions or the support versions of midPoint.

* xref:./source/[Installation from *source code*] +
As far as we are open source there is option to build the environment from the source code.
This option demand additional requirements for the build environment.
From user point of view we are not recommend this way until you explicitly require this option for any reason.
It is suitable for mainly for the developers.

== See Also

* xref:../quickstart/[]
* xref:/book/[MidPoint Book]
* https://www.youtube.com/channel/UCSDs8qBlv7MgRKRLu1rU_FQ[Evolveum YouTube channel]
* xref:/midpoint/features/current/[]
* xref:../reference/[]
* xref:/support/[Subscription and Support]