= MidPoint Installation Guides
:page-nav-title: Installation
:page-wiki-name: Installation Guide
:page-wiki-id: 1310779
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2011-05-11T13:48:08.155+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-02-27T18:38:20.663+01:00
:page-display-order: 80
:page-upkeep-status: green
:page-toc: float-right

{% for v in site.data.midpoint-versions %}{% if v.status == null or v.status == "released" %}{% assign lastReleased = v %}{% endif %}{% endfor %}

There are several ways to install midPoint.
Each of the option require different set of step to cover.

== How to make a choice

When the decision about the installation came up you have to decide which way to go.
There may be already some working part of environment which should be used.
You could start from scratch.
You may want simply quickly test the application.
All these aspects may have impact which installation option to choice.

=== Required time

We want to help you minimize the time you have to spent with installation.
This criterion will be important in the most of the installation like demo, test of configuration / Proof of Concept, development, etc.

In all these situations the xref:./containers/[*containers*] will be the best option for you.
There are available containers with the midPoint application containing system dependency - ready to run.
There is available description of the configuration,
You can quickly address the most common use cases.

The containers are ready also for the cloud installation.

In case of first contact see xref:../quickstart/[*Quick Start* guide] as a starting point.

=== Legacy approach

There may be the situations when the containers are simply not the case.
You could prefer "standard" distribution installation for any reason.
We are here for you also in these cases.

There is available also option of installation from xref:./distribution/[*distribution package*].
In this case it will take a little bit more time to install.
There are thing you will have to cover yourself like to have available correct version of JAVA.

=== Want to dig in a little bit

We are *open source*!
In case you are developer or you are simply curious there is also option to install from xref:./source/[*source code*].

We would recommend this option just in case you really want - you know why.
Next to the dependency to run the application you need also to have build environment.
Next to time needed to build you will need also more storage space in comparison to other installation options because of build process itself.

== Repository ( "external" dependency )

Next to midPoint there is the need to have available running instance of PostgreSQL for the repository.
It not necessarily have to be dedicated instance.
It can be even remotely available but in that case you should make sure the network connection between midPoint and the repository is working properly without performance issues.

The easiest approach to cover these dependency is to use preconfigured link:https://hub.docker.com/_/postgres[official docker container].
In case you have select the midPoint installation in container the available configuration automatically using it.

In case you prefer local installation of postgreSQL there is xref:/midpoint/reference/repository/native-postgresql/usage/[docs page] with the description of the midPoint's requirements on the DB configuration.

== See Also

* xref:../quickstart/[]
* xref:/book/[MidPoint Book]
* https://www.youtube.com/channel/UCSDs8qBlv7MgRKRLu1rU_FQ[Evolveum YouTube channel]
* xref:/midpoint/features/current/[]
* xref:../reference/[]
* xref:/support/[Subscription and Support]