= Post-Install Orientation
:page-nav-title: Post-Install Orientation
:page-display-order: 100
:page-keywords: installation, next steps, tutorial, first steps, after installation
:page-description: This page provides an overview of the resources available to help you orient yourself after installing midPoint.

This page provides an overview of the resources available to help you orient yourself after installing midPoint.


== Start learning midPoint

Once you have installed midPoint, it will not do much without further configuration.
For example, you will need to connect midPoint to a source or target system (a _resource_).
As midPoint is a very powerful and comprehensive system, there are many things that can be set up, customized, and adjusted when a new _resource_ is connected to midPoint.

There are some great ways to start learning about midPoint:

[#resources]
*  *xref:/midpoint/methodology/first-steps/[First Steps]* methodology.
These steps are also covered by the https://www.youtube.com/watch?v=suo775ym_PE[First Steps Methodology Webinar] video that includes a live demonstration.

video::suo775ym_PE[youtube,title="First Steps Methodology Webinar Video",width="852",height="480"]

* *Video tutorials on the https://www.youtube.com/channel/UCSDs8qBlv7MgRKRLu1rU_FQ[Evolveum YouTube channel]*.
There is a series of tutorials based on xref:/book/[MidPoint Book], together with videos explaining various details of midPoint configuration and deployment.

* *xref:/book/[MidPoint Book]* provides a general introduction to identity management.
It explains how midPoint works, and provides examples, ideas, and tips for the midPoint configuration, deployment, and use.
This is _the_ book to learn about midPoint.
It is freely available for online reading and downloading.

* *https://evolveum.com/services/training-and-certification/[Trainings]* organized by Evolveum.
These are usually remote, instructor-led trainings designed by the midPoint authors.

* *xref:/glossary[Glossary]* explains midPoint terminology.
While midPoint uses terminology that is common in the identity management field, the range of terms is extensive.
This glossary will help you quickly orient yourself with specific terms and their meanings.

There are also additional sources of information that are usually suitable for engineers with some experience:

* *xref:/[docs.evolveum.com]*: This entire site is dedicated to midPoint documentation.

* *xref:/community/mailing-lists/[MidPoint mailing lists]* are a great place to discuss midPoint.

* *xref:/talks/[Conference talks]* and workshop recordings are good resources for people who like to sit back and listen.
