= Installing MidPoint From Source Code
:page-nav-title: From Source Code
:page-wiki-name: Installing midPoint Development Snapshot - Source Code
:page-wiki-id: 4882541
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2012-08-08T17:44:24.330+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-09-19T13:06:15.518+02:00
:page-display-order: 30
:page-upkeep-status: green

{% for v in site.data.midpoint-versions %}{% if v.status == null or v.status == "released" %}{% assign lastReleased = v %}{% endif %}{% endfor %}

This guide provides instruction for installing midPoint from the source code.
It requires software development tools and some experience to build the product.
This is recommended only for engineers that want to participate in midPoint development or have deeper interest in the source code.
Everybody else will probably find installing xref:distribution.adoc[distribution package] or xref:docker/[docker image] much easier.

[TIP]
.MidPoint 4.0 and later
====
This guide applies to midPoint 4.0 and later.
For guides that apply to older releases please see the release notes.
====

== Before You Start

There are few things to check before you start the installation:

* Make sure to see xref:/midpoint/release/[Release Notes] for list of environments that are known to work and for the list of known issues in current release.

* Make sure the xref:/midpoint/install/system-requirements/[System Requirements] are met.

* Development versions of midPoint are, quite obviously, not finished yet.
There may be unfinished parts, bugs, instability and a variety of other problems.
Use it at your own risk only.

== Prerequisites

=== Java Development Kit

MidPoint is a Java application, therefore it requires Java platform to run on.
*Java 11 is a required platform* for MidPoint {{ lastReleased.version }}.
Java platform distributions based on http://openjdk.java.net/[OpenJDK] are recommended.

Please make sure you have full *Java Development Kit (JDK)*, not just the runtime environment (JRE).
Full set of development tools is needed, as you will be building midPoint from source code.

`JAVA_HOME` environment variable should point to the Java installation path.

=== Git

The midPoint source is available from a Git server.
You will need a suitable git client software to clone the source code.
Many operating systems include that as a standard package.
E.g. Debian-based Linux system can install it using `apt`:

[source,bash]
----
sudo apt install git
----

=== Maven

MidPoint source code is built using http://maven.apache.org/[Apache Maven].

Download and install *Maven3*: link:http://maven.apache.org/download.html[http://maven.apache.org/download.html]

`M2_HOME` environment variable should point to the Maven installation path.


== Installation

=== Getting The Source Code

MidPoint source code is hosted on GitHub:

[%autowidth,cols="h,1"]
|===
| GitHub project page
| https://github.com/Evolveum/midpoint

| Git repository HTTPS access
| link:https://github.com/Evolveum/midpoint.git[https://github.com/Evolveum/midpoint.git]

| Git repository SSH access
| `git@github.com:Evolveum/midpoint.git`

|===

Use your git client to clone the source code tree.
For example, Linux system can use `git` command-line client:

[source,bash]
----
git clone -b v{{ lastReleased.version }} https://github.com/Evolveum/midpoint.git
----

Running this command creates `midpoint` directory containing midPoint source code tree.

The `-b` option specifies midPoint version.
You can ommit the option to get the latest development version of midPoint (`master` branch):

[source,bash]
----
git clone https://github.com/Evolveum/midpoint.git
----

For more information about the source repository structure see xref:/midpoint/devel/source/[Source Code].

[NOTE]
====
On Windows, we highly recommend to add the following switch to the `git clone` command: `--config core.autocrlf=false`

Actually, you can use the switch on any platform.
While in theory `autocrlf` works, it does not work well for midPoint projects.
Don't forget to adjust project settings for IDE accordingly (taken care of automatically when xref:/midpoint/devel/guides/environment/idea/[using IntelliJ IDEA]).
====

=== Building MidPoint

Enter the directory with downloaded source code and execute either of the following commands:

[source,bash]
----
mvn install
----

Complete build process also includes unit and integration tests, and it may take more than one hour.
You can speed up the build by skipping automatic tests using the following command:

[source,bash]
----
mvn install -DskipTests=true
----

After the successful build process there will be a binary distribution package located in `dist/target` directory.

[TIP]
.Building the WAR file only
====
If the WAR file is all you need you can speed the build even further by skipping the packaging of the distribution archive.
Use the following command to turn off the `dist` maven profile:

`mvn clean install -DskipTests=true -P -dist`

Please note the minus character (-) before profile name. +
The resulting WAR file can be obtained from `gui/admin-gui/target/midpoint.war`
====


=== Running MidPoint

Continue with installation in the same way as for a binary release.
See xref:distribution.adoc[] page.
However, you need to use your own freshly built distribution package from `dist/target` directory instead of downloading it.


== Next Steps

MidPoint is a comprehensive system, and the source code is quite big.
If you plan to work with midPoint source code, we strongly recommend getting an *integrated development environment (IDE)*.
Most midPoint developers are using IntelliJ IDEA and there is a xref:/midpoint/devel/guides/environment/idea/[short guide to set up IntelliJ IDEA] for midPoint development.
Eclipse Java IDE can also be used.

If you plan to participate in midPoint development, please see the xref:/community/development/[] page.
If you plan to contribute source code, the xref:/community/development/code-contribution-guidelines/[] page provides essential information.

== See Also

* xref:distribution.adoc[]

* xref:/midpoint/devel/source/[Source Code]

* xref:/midpoint/devel/guides/environment/idea/[]

* xref:/community/development/[]

* xref:/community/development/code-contribution-guidelines/[]