= Using Support Branch
:page-wiki-name: Using Support Branch
:page-wiki-id: 13074475
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2013-10-09T17:14:07.278+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2018-08-01T09:53:02.964+02:00
:page-upkeep-status: orange

== What is "Support Branch"?

The support branch is created in git after every minor release.
The support branch contains the "maintenance development" of maintenance versions of midPoint (see wiki:Release+Process[Release Process]). Simply speaking the support branch contains the most recent bugfixes.
It is used as a place where the bugfixes accumulate until next maintenance release.

The support branch does *not* contain new features planned for the next major or minor releases.
This is contained on a current main development branch (currently `master` branch).
But use of the `master` may be quite risky as the code is usually not perfectly stable.
On the other hand the code on the support branch is almost always reasonably stable.


== Location of Support Branch

The support branch is maintained as a branch in our xref:/midpoint/devel/source/git/[Git] repository.
It has the name in the form:


....
support-x.y
....

Where X.Y is the last minor release.
The repository may be fetched by using the usual xref:/midpoint/devel/source/git/[Git] tools.
Once you have got the repository you can switch the workspace to the support branch e.g. by using the following command:

[source]
----
git checkout support-3.7
----

This may vary depending on the specific git tool you are using.
Please refer to the documentation of your git tool for the details.


== Using the Branch

Once the workspace is switched to the support branch you can build the system normally.
E.g. use the instructions described at wiki:Installing+midPoint+Development+Snapshot+-+Source+Code[Installing midPoint Development Snapshot - Source Code] page.
Just instead of `master` use the ``v2.2-support`` branch name (or whatever support branch name applies to the current release).


== See Also

* wiki:Release+Process[Release Process]

* wiki:Backporting+Code+to+Support+Branch[Backporting Code to Support Branch]

* xref:/support/long-term-support/[Long-Term Support]