= Installing midPoint as a Windows Service
:page-nav-title: Windows Service Setup
:page-wiki-name: Installing midPoint as a Windows Service
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2017-12-08T11:12:37.394+01:00
:page-wiki-metadata-modify-user: virgo
:page-wiki-metadata-modify-date: 2021-02-08T17:21:06.015+01:00
:page-upkeep-status: yellow

{% for v in site.data.midpoint-versions %}{% if v.status == null or v.status == "released" %}{% assign lastReleased = v %}{% endif %}{% endfor %}

[WARNING]
====
As of 4.2 Windows Service support is broken because of changes related to Spring Boot upgrades.
It is undetermined when it will be back.
Currently only `start.bat` and `stop.bat` scripts are the alternative.
====

This page describes the method how to setup midPoint server to run as Windows service.
This is the usual setup to start midPoint automatically after system boot on Windows.
The service will be started as MidPoint and will listen on default TCP 8080 port.

++++
{% include release-install-download.html this=lastReleased %}
++++

== Install

. Install MidPoint as service by executing service.bat script from `bin` directory with install argument e.g.:
+
[source]
----
.\Downloads\midpoint\bin\service.bat install
----

. Start, Stop and configure service:

.. Another binaries midpointw.exe, is GUI application which is used to monitor and configure created MidPoint service. Main function of this application is to Start and Stop MidPoint service. Run this application located in \bin directory and Start/Stop MidPoint by click on start/stop.

. Uninstall MidPoint service executing service.bat script from \midpoint-3.7\bin directory with uninstall argument e.g. (Stop the service before uninstallation):
+
[source]
----
.\Downloads\midpoint\bin\service.bat uninstall
----

[TIP]
====
You can also start/stop service with windows Services application.
====

== See Also

* xref:../[Installation Guides]

* wiki:Stand-Alone+Deployment[Stand-Alone Deployment]