= Installing midPoint as a Windows Service
:page-nav-title: Windows Service Setup
:page-wiki-name: Installing midPoint as a Windows Service
:page-wiki-id: 24676017
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2017-12-08T11:12:37.394+01:00
:page-wiki-metadata-modify-user: virgo
:page-wiki-metadata-modify-date: 2021-02-08T17:21:06.015+01:00
:page-upkeep-status: yellow

{% for v in site.data.midpoint-versions %}{% if v.status == null or v.status == "released" %}{% assign lastReleased = v %}{% endif %}{% endfor %}

[WARNING]
====
Windows Service support was broken for 4.2 before 4.2.1 and 4.3 before 4.3.2.
For those versions only `start.bat` and `stop.bat` scripts are the alternative.
====

This page describes the method how to setup midPoint server to run as Windows service.
This is the usual setup to start midPoint automatically after system boot on Windows.
The service will be started as MidPoint and will listen on default TCP 8080 port.

++++
{% include release-install-download.html this=lastReleased %}
++++

== Install

. Install *MidPoint* as service by executing `service.bat` script from `bin` directory with `install` argument:
+
[source]
----
.\Downloads\midpoint\bin\service.bat install
----

. Service can be controlled by common tools for Windows Services.
Alternatively `midpointw.exe` application with GUI is provided in the `bin` directory to start, stop or configure the service.

. Uninstall MidPoint service executing `service.bat` script from `bin` directory with `uninstall`.
Stop the service first, then run:
+
[source]
----
.\Downloads\midpoint\bin\service.bat uninstall
----

[TIP]
====
You can also start/stop service with windows Services application.
====

== See Also

* xref:../[Installation Guides]

* wiki:Stand-Alone+Deployment[Stand-Alone Deployment]