= MidScale Solution Architecture
:page-nav-title: Architecture

WARNING: WORK IN PROGRESS

Goal of link:../[midScale project] is to significantly improve performance and scalability of midPoint.
We would like to make midPoint operate faster (performance).
Even more importantly, we need midPoint to be scalable, i.e. it has to handle large amounts of data and requests without significant degradation of performance.

== History

https://midpoint.evolveum.com/[MidPoint] is a popular and comprehensive open source identity management and governance platform.
However, midPoint has one significant limitation.
MidPoint was originally built to address the needs of mid-size enterprises, agencies and universities.
Initial design of midPoint data store components favored flexibility and time to market.
As midPoint was targeting mid-size organizations the scalability was not high on a list of implementation priorities.
Now, midPoint is being deployed to handle scenarios with large number of identities.
Deployments that manage students, subscribers and consumers are becoming more and more common.
Which makes sense, as these types of users can especially benefit from the data protection capabilities of midPoint.
However, such deployments are hitting scalability limitations of current data storage components of midPoint.

Future scalability issues were foreseen in original midPoint design.
The datastore implementation (repository) was designed as replaceable component.
Based on our previous experience, we have identifier current repository implementation as a major obstacle to scalability.
There are other areas where we suspect performance and scalability limitations, such as Prism, our basic data representation layer.
We expect to improve midPoint clustering, task management mechanisms and other areas.


== Approach

MidScale is all about performance and scalability.
As for the performance, our plan is to proceed systematically and premature optimizations.
Therefore the initial phases of the project are focused on testing environment.
We plan to create a testing environment and use it to identify performance and scalability problems.
We will also use the testing environment and other analytic tools (e.g. profiling) to confirm performance issues that we are currently suspecting.

At the same time, we are conducting a series of link:../design/[design meetings] to identify potential problems and outline solutions.
Data from the testing and prototyping are fed back to the design process.

The testing environment will be used and even expanded during the entire duration of the project - and even permanently maintain after the project.
The intermediate results from the testing will be used to improve the implementation, and even re-evaluate the design if needed.


== Repository

MidPoint is not bound to any particular data store or database.
Thanks to such foresight, midPoint has a flexible and replaceable data storage components.
We would like to take advantage of this design feature and re-implement data storage components in a scalable way.

The current database schema has many limitations, mostly caused by two reasons:

* Current database schema is based on early design that prioritized functionality over scalability.
MidPoint evolution emphasized database schema compatibility, which meant that sub-optimal early design is still limiting the perfomance and scalability of data model.

* Database schema was designed in a generic way that had to fit several database engines (PostgreSQL, MySQL/MariaDB, Oracle, Microsoft SQL).
Therefore the data model could not use any database-specific optimizations.
The obvious method to support several databases at the time when midPoint was designed was to use object-relational mapping (ORM) component, such as Hibernate.
This approach introduces additional limitations and difficulties.

Our plan for scalability improvement has several key aspects:

* Focus on scalability and efficiency in database schema design.
Design database tables and indexes in such a way that supports large data structures, efficient data storage ans searching.

* Choose just one database to support.
Preliminary choice is PostgreSQL, however, that choice has to be validated in early stages of the project.
Choice of one database engine allows us to use database-specific scalability features and optimizations, e.g. hierarchical tables and partitioning.
We can also better "tune" the code for high performance.
Additionally, this choice will simplify testing and lower overall support cost, making the solution more maintainable in the long run.

* Connect to database directly, avoiding ORM.
The ORM layer (Hibernate) is not providing any significant advantage in this case.
Moreover, it can be a source of problems, slow-downs and limitations.

Design of database schema is still work in progress.
Initial tasks in the project are focus on evaluation of current problems, design of solutions and simple rapid prototypes.

Please see link:../design/repository-design.adoc[repository design notes] for the details.

Even after midScale is finished, we still plan to keep the existing Hibernate-based repository implementation (referred to as "legacy" repository implementation).
The plan is to use this implementation to support midPoint running on Oracle and Microsoft SQL databases (support for MySQL/MariaDB is already deprecated).
MidPoint should be able to operate normally by using this repository implementation.
The performance is likely to be low (approximately at current levels).
Yet such performance is still sufficient for many (usually smaller) deployments.
The plan is to support this "legacy" repository implementation at least for the lifetime of miPoint 4.4 LTS, which is planned to end in 2024.
However, the future of the "legacy" implementation starting from midPoint 4.5 is yet to be decided.

== Query Language

TODO

== Clustering

TODO:
We also plan to improve midPoint clustering mechanisms.
Our goal is to support autoscaling capabilities used in cloud platforms, thus enhancing the on demand character of midPoint deployments.
Higher scale also implies harder requirements on stability and robustness of the product.
Therefore we plan to invest part of the effort to improve our quality assurance environment, especially focusing on scalability, performance and stability testing.
MidPoint would greatly benefit from user experience improvements that can make administration of millions of identities easier.


== Prism

TODO: Stability: thread safety

== Testing

TODO

== See Also

* link:../design/[Design meeting notes]
