---
release-version: '4.1'
---
= MidPoint 4.1 "Pasteur"
:page-layout: release
:release-version: 4.1
:page-wiki-name: Release 4.1
:page-wiki-id: 36569421
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2019-09-11T09:26:33.033+02:00
:page-wiki-metadata-modify-user: michael
:page-wiki-metadata-modify-date: 2020-05-27T14:19:54.439+02:00
:page-liquid:

Release {release-version} is a thirty-second midPoint release code-named _Pasteur_.
The {release-version} release brings major authentication improvements, user interface improvements, improved archetype functionality and a number of smaller improvements.

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
    <a href="https://en.wikipedia.org/wiki/Louis_Pasteur">Louis_Pasteur</a> (1822 - 1895) was French biologist, microbiologist and chemist.
    He is remembered for his remarkable breakthroughs in the causes and prevention of diseases, and his discoveries have saved many lives ever since.
    He is best known for process called pasteurization used to preserve our food and drinks.
</p>
<p>
    The processes that Pasteur developed made our world a safer place.
    Similarly to Pasteur's work, the ambition of midPoint 4.1 is to make identity management safer and better.
    New flexible authentication mechanism can be used to safeguard entry to midPoint user interface by using several authentication options.
    User interface improvements and code cleanups make midPoint more "sanitized" and cleaner.
    MidPoint 4.1 another small, but very important step in midPoint 4.x development track.
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

== Changes With Respect to Version 4.0

=== New Features and Improvements

* Major features

** wiki:Flexible+Authentication[Flexible Authentication]

** Service authentication: service objects can log into midpoint similarly to users

** Reworked _server tasks_  pages, added several new features


* User interface improvements

** Audit log viewer improvements

** Support for archetype changes

** Archetypes can hide items in the schema

** UI support for simple conditions in assignment/inducement

** Several archetype-related UI improvements

** Improvements for _recompute members_  tasks

** Save in background

** Misc minor improvements in case management UI

** Language picker is always visible

** Configurable columns for _accounts_ table

** _Triggers_ tab in object details page

** Improvements for display of indirect assignments


* Provisioning and Synchronization

** Conditions for synchronization reactions

** Diagnostic improvements (e.g. last availability status)

** Miscellaneous synchronization task improvements, mostly diagnostic and robustness

** xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)] and wiki:PowerShell+Connector[PowerShell Connector] are separated (see below)

** Connector read+write mode (experimental)


* Miscellaneous improvements

** Asynchronous update task improvements

** Configurable strictness for reference integrity

** Improvements to mapping chaining (focusMappings)

** Support for documentation properties for midScribe documentation generator (prototype, experimental)

** Support for PostgreSQL 12


* Internals and Development

** Build process speedup

** Major test cleanup


=== Deprecation, Feature Removal And Incompatible Changes

* Java 8 is no longer supported.

* PostgreSQL 9.5 (9.5, 9.5.1) is no longer supported.

* Microsoft SQL Server 2014 is no longer supported.

* Support for MySQL and MariaDB is deprecated.
Those databases will be supported for some time (possibly long time), but wiki:Repository+Database+Support[support for them will be eventually removed]. It is strongly recommended to use PostgreSQL instead.

* Microsoft Active Directory 2008R2 is no longer supported.

* Microsoft Windows Server 2008R2 is no longer supported.

* Support for .NET remote connector server is deprecated.

* SOAP-based wiki:IDM+Model+Web+Service+Interface[IDM Model Web Service Interface] is deprecated, and it will be removed in midPoint 4.2. Please use xref:/midpoint/reference/interfaces/rest/[RESTful interface] instead.

* Support for Apache Tomcat 8.5 is deprecated.

* Explicit deployment to an external web container is deprecated.

* MidPoint plug-in for Eclipse IDE was never officially supported.
Despite that, it now has a deprecated status.
The plan is to replace Eclipse with IntelliJ IDEA environment eventually.

* Unofficial option to use Spring Security modules is no longer available.
It was replaced by wiki:Flexible+Authentication[flexible authentication] mechanisms.

* Unofficial JasperSoft Studio plugin for midPoint is no longer available.
There is no plan to make it available again.

* Public API things - copy from link:https://github.com/Evolveum/midpoint/commit/882a2ceb03294affbf589f077102a9f519bbcea8[https://github.com/Evolveum/midpoint/commit/882a2ceb03294affbf589f077102a9f519bbcea8] (select relevant methods).


=== Releases Of Other Components

* New versions of xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] and xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector] were released during the course of midPoint 4.1 development.
There were major improvements and fixes in those connectors, namely separation of wiki:PowerShell+Connector[PowerShell Connector] from the AD connector.
See the connector pages for the details.
MidPoint 4.1 contains most recent versions of those connectors.

* Official release of Java REST client is planned shortly after midPoint 4.1 release.

* Overlay projects and other associated artifacts were released together with midPoint 4.1.


++++
{% include release-quality.html %}
++++

Following list provides summary of limitation of this midPoint release.

* Functionality that is marked as xref:/midpoint/versioning/experimental/[EXPERIMENTAL] is not supported for general use (yet).
Such features are not covered by midPoint support.
They are supported only for those subscribers that funded the development of this feature by the means of xref:/support/subscription-sponsoring/[platform subscription] or for those that explicitly negotiated such support in their support contracts.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector]. Support for LDAP connector is included in standard midPoint support service, but there are limitations.
This "bundled" support only includes operations of LDAP connector that 100% compliant with LDAP standards.
Any non-standard functionality is explicitly excluded from the bundled support.
We strongly recommend to explicitly negotiate support for a specific LDAP server in your midPoint support contract.
Otherwise only standard LDAP functionality is covered by the support.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] page for more details.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)]. Support for AD connector is included in standard midPoint support service, but there are limitations.
Only some versions of Active Directory deployments are supported.
Basic AD operations are supported, but advanced operations may not be supported at all.
The connector does not claim to be feature-complete.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)] page for more details.

* MidPoint user interface has flexible (fluid) design and it is able to adapt to various screen sizes, including screen sizes used by some mobile devices.
However, midPoint administration interface is also quite complex and it would be very difficult to correctly support all midPoint functionality on very small screens.
Therefore midPoint often works well on larger mobile devices (tablets) it is very likely to be problematic on small screens (mobile phones).
Even though midPoint may work well on mobile devices, the support for small screens is not included in standard midPoint subscription.
Partial support for small screens (e.g. only for self-service purposes) may be provided, but it has to be explicitly negotiated in a subscription contract.

* There are several add-ons and extensions for midPoint that are not explicitly distributed with midPoint.
This includes Java client library, various samples, scripts, connectors and other non-bundled items.
Support for these non-bundled items is limited.
Generally speaking those non-bundled items are supported only for platform subscribers and those that explicitly negotiated the support in their contract.
For other cases there is only community support available.
For those that are interested in official support for IDE add-ons there is a possibility to use xref:/support/subscription-sponsoring/[subscription] to help us develop midPoint studio (bug:MID-4701[]).

* MidPoint contains a basic case management user interface.
This part of midPoint user interface is not finished.
The only supported part of this user interface is the part that is used to process requests and approvals.
Other parts of case management user interface are considered to be experimental, especially the parts dealing with manual provisioning cases.

* Multi-node task distribution had a limited amount of testing, due to inherent complexity of the feature.
It is likely that there may be problems using this feature.
We recommend not to use this feature unless it is absolutely necessary.

This list is just an overview and it may not be complete.
Please see the documentation regarding detailed limitations of individual features.



== Platforms

MidPoint is known to work well in the following deployment environment.
The following list is list of *tested* platforms, i.e. platforms that midPoint team or reliable partners personally tested with this release.
The version numbers in parentheses are the actual version numbers used for the tests.

It is very likely that midPoint will also work in similar environments.
But only the versions specified below are supported as part of midPoint subscription and support programs - unless a different version is explicitly agreed in the contract.

Support for some platforms is marked as "deprecated".
Support for such deprecated versions can be removed in any midPoint release.
Please migrate from deprecated platforms as soon as possible.


=== Java

* OpenJDK 11 (11.0.6).
This is a *recommended* platform.

OpenJDK 11 is a recommended Java platform to run midPoint.

Support for Oracle builds of JDK is provided only for the period in which Oracle provides public support (free updates) for their builds.
As far as we are aware, free updates for Oracle JDK 11 are no longer available.
Which means that Oracle JDK 11 is not supported for MidPoint any more.
MidPoint is an open source project, and as such it relies on open source components.
We cannot provide support for platform that do not have public updates as we would not have access to those updates and therefore we cannot reproduce and fix issues.
Use of open source OpenJDK builds with public support is recommended instead of proprietary builds.


=== Web Containers

MidPoint is bundled with an embedded web container.
This is the default and recommended deployment option.
See xref:/midpoint/reference/deployment/stand-alone-deployment/[Stand-Alone Deployment] for more details.

Apache Tomcat is supported as the only web container for midPoint.
Support for no other web container is planned.
Following Apache Tomcat versions are supported:

* Apache Tomcat 8.5 (8.5.31) - DEPRECATED

* Apache Tomcat 9.0 (9.0.24)

Apache Tomcat 8.0.x is no longer supported as its support life is over (EOL).


=== Databases

MidPoint supports several databases.
However, performance characteristics and even some implementation details can change from database to database.
Since midPoint 4.0, *PostgreSQL is the recommended database* for midPoint deployments.

* H2 (embedded).
Supported only in embedded mode.
Not supported for production deployments.
Only the version specifically bundled with midPoint is supported. +
H2 is intended only for development, demo and similar use cases.
It is *not* supported for any production use.
Also, upgrade of deployments based on H2 database are not supported.

* PostgreSQL 12, 11 and 10.* PostgreSQL 12 is strongly recommended* option.

* MariaDB (10.0.28) - DEPRECATED

* MySQL 5.7 (5.7) - DEPRECATED

* Oracle 12c

* Microsoft SQL Server 2016 SP1

Our strategy is to officially support the latest stable version of PostgreSQL database (to the practically possible extent).
PostgreSQL database is the only database with clear long-term support plan in midPoint.
We make no commitments for future support of any other database engines.
See wiki:Repository+Database+Support[Repository Database Support] page for the details.

Only a direct connection from midPoint to the database engine is supported.
Database and/or SQL proxies, database load balancers or any other devices (e.g. firewalls) that alter the communication are not supported.


=== Supported Browsers

* Firefox (any recent version)

* Safari (any recent version)

* Chrome (any recent version)

* Opera (any recent version)

Recent version of browser as mentioned above means any stable stock version of the browser released in the last two years.
We formally support only stock, non-customized versions of the browsers without any extensions or other add-ons.
According to the experience most extensions should work fine with midPoint.
However, it is not possible to test midPoint with all of them and support all of them.
Therefore, if you chose to use extensions or customize the browser in any non-standard way you are doing that on your own risk.
We reserve the right not to support customized web browsers.

Microsoft Internet Explorer compatibility mode is *not* supported.


== Important Bundled Components

[%autowidth]
|===
| Component | Version | Description

| Tomcat
| 9.0.24
| Web container


| ConnId
| 1.5.0.10
| ConnId Connector Framework


| LDAP connector bundle
| 3.0
| LDAP, Active Directory and eDirectory connector


| CSV connector
| 2.4
| Connector for CSV files


| DatabaseTable connector
| 1.4.3.0
| Connector for simple database tables

|===


++++
{% include release-download.html %}
++++



== Upgrade

MidPoint is software that is designed for easy upgradeability.
We do our best to maintain strong backward compatibility of midPoint data model, configuration and system behavior.
However, midPoint is also very flexible and comprehensive software system with a very rich data model.
It is not humanly possible to test all the potential upgrade paths and scenarios.
Also some changes in midPoint behavior are inevitable to maintain midPoint development pace.
Therefore we can assure reliable midPoint upgrades only for link:https://evolveum.com/services/[midPoint subscribers]. This section provides overall overview of the changes and upgrade procedures.
Although we try to our best it is not possible to foresee all possible uses of midPoint.
Therefore the information provided in this section are for information purposes only without any guarantees of completeness.
In case of any doubts about upgrade or behavior changes please use services associated with link:https://evolveum.com/services/[midPoint subscription] or purchase link:https://evolveum.com/services/professional-services/[professional services].


=== Upgrade From MidPoint 4.0.x

MidPoint 4.1 data model is backwards compatible with previous midPoint versions.
Database schema was not changed in midPoint 4.1. Therefore the usual database schema upgrade procedure is not needed.
All that is needed is to replace midPoint 4.0 binaries with binaries from midPoint 4.1 distribution.
However, there are some notable changes in midPoint components, configuration and behavior:

* Version numbers of some bundled connectors have changed.
Therefore connector references from the resource definitions that are using the bundled connectors need to be updated.

* Archetypes were applied to server tasks.
Archetype definitions will be imported automatically from initial objects.
However, existing tasks will not be re-imported and therefore these archetypes will not be applied to tasks.
Archetypes need to be applied to existing tasks manually.
Archetypes does not affect core functionality of the task, therefore the tasks should still work even without the archetypes.
However, archetypes are needed to utilize midPoint GUI to its full potential, therefore applying archetypes to tasks is strongly recommended.

* Although the database schema was not changed, a minor change occurred by introducing the "incomplete" flag.
You need to reindex objects that contain data that are not returned from search by default (such as `jpegPhoto`). It is not strictly necessary, but reindex operation is recommended to fix several issues that were present in midPoint 4.0.


=== Upgrade From MidPoint 3.9.x Or Older

Upgrade from midPoint 3.9.x or older is not supported directly.
Please upgrade to midPoint 4.0.x first.


=== Changes In Initial Objects Since 4.0

MidPoint has a built-in set of "initial objects" that it will automatically create in the database if they are not present.
This includes vital objects for the system to be configured (e.g. role `superuser` and user `administrator`). These objects may change in some midPoint releases.
But to be conservative and to avoid configuration overwrite midPoint does not overwrite existing objects when they are already in the database.
This may result in upgrade problems if the existing object contains configuration that is no longer supported in a new version.
Therefore the following list contains a summary of changes to the initial objects in this midPoint release.
The complete new set of initial objects is in the `config/initial-objects` directory in both the source and binary distributions.
Although any problems caused by the change in initial objects is unlikely to occur, the implementors are advised to review the following list and assess the impact on case-by-case basis:

* `000-system-configuration.xml`: Updated dashboard links, changes related to archetyped tasks, predefined tracing configurations.

* `040-role-enduser.xml`: End user authoriztion fix.

* `110-report-user-list.xml`: Using report.resolveLinkRefs() instead of using shadow search.

* `1*-report-certification-*.xml`: Fixed certifiation report fatal error.

* `5*-archetype-task-*.xml`: Task archetypes (new files)


=== Bundled connector changes since 4.0

* LDAP ad AD connectors were upgraded to the latest available version 3.0. This is a major connector release and it brings some non-compatible changes. +


** Powershell scripting is no longer a part of AD connector.
Use of Powershell is still possible by combining AD connector and Powershell connector.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory connector] page for details.

** Configuration property `baseContextsToSynchronize` was renamed to `baseContextToSynchronize`.



* CSV connector was upgraded to the latest version.


=== Behavior Changes Since 4.0

* Property `publicHttpUrlPattern` is used in wiki:System+Configuration+Object[System Configuration Object] to create links in notifications.
Property `defaultHostname` was used for this purpose before.

* Changes in mapping evaluation (bug:MID-5953[], bug:MID-6040[]).

* Change in Users in Midpoint report.
Re-import of report definition is needed (bug:MID-5908[]).

* Following expression variables are still deprecated: `user`, `account`, `shadow`. These variables will be removed soon.
Please change your script to use `focus` and `projection` variables instead.

* Property `subtype` is still deprecated.
It will be removed soon.
Please change your configuration to use archetypes instead.


=== Public Interface Changes Since 4.0

* Prism API was changes in several places.
However, this is not yet stable public interface therefore the changes are are not tracked in details.

* There were changes to the wiki:IDM+Model+Interface[IDM Model Interface] (Java).
Please see source code history for details.

* wiki:IDM+Model+Web+Service+Interface[IDM Model Web Service Interface] (SOAP) is deprecated.
SOAP will be removed soon.


=== Important Internal Changes Since 4.0

These changes should not influence people that use midPoint "as is".
These changes should also not influence the XML/JSON/YAML-based customizations or scripting expressions that rely just on the provided library classes.
These changes will influence midPoint forks and deployments that are heavily customized using the Java components.

* There were changes in internal code structure, most notably changes in Prism and GUI.
Heavy customizations of midPoint 4.0.x may break in midPoint 4.1.


++++
{% include release-issues.html %}
++++

Some of the known issues are listed below:

* There is a support to set up storage of credentials in either encrypted or hashed form.
There is also unsupported and undocumented option to turn off credential storage.
This option partially works, but there may be side effects and interactions.
This option is not fully supported yet.
Do not use it or use it only at your own risk.
It is not included in any midPoint support agreement.

* Native attribute with the name of 'id' cannot be currently used in midPoint (bug:MID-3872[]). If the attribute name in the resource cannot be changed then the workaround is to force the use of legacy schema.
In that case midPoint will use the legacy ConnId attribute names (icfs:name and icfs:uid).