= Get Value Quickly with Evolveum's Iterative Approach to IGA
:page-nav-title: 'Advantages of Iterative Approach'
:page-display-order: 20

At Evolveum, we recognize that effective identity governance and administration (IGA) is essential for any modern business, be it a commercial enterprise or university.
We also understand that time is valuable and technology evolves rapidly, making it crucial to achieve tangible results quickly.
Moreover, IGA must be flexible and adapt to changes in your systems while enabling the seamless integration of new systems.

That's why our deployment guides and methodology are designed to help you achieve meaningful outcomes in just a matter of days through an iterative implementation process.

Our deployment methodology helps you to get a solid foothold in midPoint, equipping you with the essential know-how to get production-ready results immediately, rather than spending months tweaking your development environment to the last detail.

Once you deploy midPoint, you can connect your first identity resource within one or two days.
The data may not be perfect at this point.
However, perfect is the enemy of done.

After you connect the identity resource, pinpoint any data inconsistencies and inform the data owners about the issues that need fixing on their end.
Move on, mark the problems to be excluded from processing for now, and activate your configuration on production.
While you wait for the troublesome data to be fixed, pick another system and connect it to midPoint.
Escalate any issues with data like you did before, mark them to be dealt with later, and activate the new setup on production.
Once the data from the previous iterations are fixed, tweak the midPoint configuration, automate whatever you can, and remove exceptions that aren't needed anymore.
And repeat.
Engage in a cycle of connecting new systems, cleaning data, optimizing the setup, and automating processes.

Initially, you're going to have multitude of exceptions.
As the other teams fix their data, each iteration improves your data quality, reduces the amount of exceptions, and enhances the security of your organization.
You can continue this process as long as it provides tangible value—simultaneously connect new systems, organize data, and strengthen the overall security of your infrastructure.

Step by step, your production environment centered around midPoint grows.
With each new resource connected and more data cleaned up, you can proudly demonstrate the tangible progress of your IGA project.

image::adopt-midpoint.drawio.svg[100%,title=Timeline of midPoint deployment using the iterative approach]

The strength of this iterative process lies in its adaptability.
As your team members repeat these steps, they can automate increasingly complex tasks, resulting in a more efficient and secure identity governance environment.
This not only leads to continuously improving measurable outcomes and coherent data, but also significantly reduces the costs associated with account and data maintenance.
By streamlining operations, you can focus your resources on strategic initiatives rather than being bogged down by administrative tasks.

At Evolveum, we champion the pursuit of quick wins while fostering a culture of purposeful, long-term progress.
Our methodology is designed to guide you toward meaningful results and deeper knowledge, ensuring that every step you take gets you closer to your goals.
To this end, we invite you to explore how our solution and services can transform your identity governance and administration practices today.