= Evolveum Values
:page-moved-from: /evolveum/values/
:page-display-order: 10

We are the people of *Evolveum*, a company devoted to create unusual things.
We engineer things that help other people do their jobs, things that protect what needs to be protected, things that make life easier.
But most of all, we create things that work.
Practical and useful things.
We do not keep that things just to ourselves.
We share the products of our work freely with the rest of the world.
Because the things that we have created are based on the work of those that came before us.
And we hope that our work will inspire those following us.
Great things can only be achieved by cooperation.

Evolveum is an unusual company.
Unlike most other companies, we do not see profit as a sole reason for our existence.
We go much deeper than that.
Our work is motivated by four fundamental values.

[[tech]]
*Technological excellence* is our first value.
Technology is irresistibly fascinating to us.
We enjoy the process of creating technological marvels, evolving the things that we have created and improving the work of others.
Technology is the reason that Evolveum was created.
It was always technology and knowledge that moved us forward.
Yet, we are no idealists.
We are fully aware that technology is complex.
Creating and maintaining the systems is a very hard work.
It may not be possible to reach perfection.
Nevertheless, we are trying to do our best.
Despite all the obstacles and limitations.
We know that practical working system is always better than perfect, but imaginary system.
Therefore, we are strongly focused on delivering practical results.
We do not hide our products behind a wall of legal obstacles and marketing.
We openly publish the products of our endeavor.
We have nothing to hide.
We are proud of our products.
Because they work.

[[business]]
*Sustainable business* is our second value.
Even though Evolveum is unusual company, it is still a commercial company.
We need money to pay our bills.
While profit is not our only motivation, we fully accept that a reasonable profit is needed for the company to thrive.
Innovation is expensive.
Innovation involves a lot of experimental work, lots of trial and error and huge amount of time spent on research and development.
All of that needs to be paid by the income from our commercial activities.
Evolveum is not based on any venture capital.
The crucial investment to start the company was provided by the founders.
Evolveum runs a completely self-funded business.
Therefore, it is perhaps understandable that our services cannot be provided for free.
Those services are not cheap either.
We charge the usual commercial rates.
The profit is used to advance the technology, to run the company but also to repay the initial investments.
In that aspect we are bound by the rules of market economy.
There is no magic spell that could create money out of nothing.
We are completely devoted to the liberty of software, ideas and knowledge.
However, liberty does not mean "zero cost". There is no free lunch.

Even though we operate in a commercial world, we prefer cooperation over competition.
We actively cooperate with our partners and customers.
We support the community that gathered around our products.
We are even willing to cooperate with some of our competitors to achieve technological excellence and advancement of human knowledge - and in fact we are already doing that.
We believe that one company cannot do everything.
We prefer to focus on areas that we know well and cooperate with others that are experts in their respective areas.
Companies do not need to be huge to create true marvels.
It is cooperation that is a way to greatness.

[[happy]]
*Enjoyable work environment* is our third value.
Whatever a company does, however big or successful it is, it is still a company of people.
People are the most valuable asset in Evolveum.
Evolveum would be just an empty shell without the people.
We deeply care about our colleagues.
We care what they do and how they do it.
We help each other.
But most importantly of all: work in Evolveum has to be fun.
There needs to be passion, devotion, fascination.
We deeply believe that great things can be achieved only if people enjoy what they are doing.
We value the effects of personal freedom in our work.
Our people have significant freedom in their actions, even though the level of freedom is naturally proportional to the seniority of the person involved.
We believe in meritocracy.
It is quality and potential of the idea that matters, not the person who presents the idea.
Even the founders may be wrong and even the youngest trainee may be right.
Nobody is perfect.
We tolerate mistakes and failures as long as the intentions are good and they are not caused by negligence or slacking.
We are strongly oriented towards technology, knowledge and efficiency, but at the same time we try to remain human.

[[social]]
*Social responsibility* is our fourth value.
We do not live in an empty space, there is society all around us.
We want to be good members of the society.
Evolveum is a commercial company, and a lot of things that we do are given by market demand.
However, we do not follow the market blindly.
We always consider our responsibility to the society and environment around us.
We avoid things that are harmful to society, even if market demands it and there may be significant rewards.
We avoid corruption, discrimination and exploitation in any form.
We pay fair wages to our employees, and we pay fair prices to our suppliers.
We try to minimize activities that are harmful to the environment.
Yet, the most significant aspect of our social responsibility is given by the nature of our work: software liberty.
We develop open source products.
We see open source as a crucial mechanism to provide transparency, to share knowledge and to fight harmful business practices.
Our products were open source from the very beginning, all significant parts of the products are open source, and the products will remain open source as long as we have anything to say about it.

Our social responsibility goes beyond avoidance of harmful practices.
We invest a portion of our resources to activities that the society can benefit from.
We support research and development and freely publish all the results of those activities.
We cooperate with universities to share our knowledge and experience with students.
Given our technological focus, we invest in advancement of the technology in ways that are good for the humanity, such as data protection and privacy.
We hope that are modest contributions can advance the collective knowledge of humanity.

There are four values, all of them are equally important.
The values need to work together, they need to be balanced, they need to form a synergy.
Technological excellence would not be possible without sustainable business that funds the innovation.
The business would not work without passionate people.
And none of that would last without caring about the environment and society around us.
All the values are equally important.

We have created Evolveum.
We are shaping the future of the company.
But the company also shapes us.
It cultivates us.
We work together to create unique things, to satisfy our passion and our curiosity, and base all that on a sustainable foundations.
We believe that this is the best way to work and live.