= Open questions related to metadata processing

== Data derived implicitly i.e. not in context of a mapping

An example is deriving `roleMembershipRef` value from an assignment. We should have some rules (e.g. what to propagate and how)
for this case.

In the current proposal it could be resolved like this (in e.g. user template):

----
<objectTemplate ...>
    <name>User template</name>
    <item>
        <ref>roleMembershipRef</ref>
        <metadataTemplateRef oid="123456" />
    </item>
</objectTemplate>
----

and

----
<objectTemplate oid="123456">
    <name>RoleMembershipRef metadata template</name>
    <item>
        <ref>extension/sensibility</ref>
        <source>
            <path>extension/sensibility</path>
        </source>
    </item>
</objectTemplate>
----

Metadata mappings attached to `roleMembershipRef` would be interpreted by the assignment evaluator,
unlike metadata mappings attached to "regular" data items that are interpreted primarily by mapping evaluator.

Where normal metadata mappings get sources from input values that enter data mapping, metadata mappings for `roleMembershipRef`
would get their sources from input values that are used to compute particular `roleMembershipRef` value:
* primary assignment,
* assignments on the path (maybe),
* sources for all conditions that were evaluated during `roleMembershipRef` value computation,
* sources for all other expressions that were evaluated (e.g. filters in target resolution) (maybe).

This is quite complex issue. But, overall, it seems that using `roleMembershipRef` definition in an object template
looks like a good idea.

== Metadata value consolidation (conflicting values)

What if we are merging two equal values (e.g. for `roleMembershipRef`) carrying different metadata?

== Metadata value consolidation (conflicting mappings)

What if different mappings provide different values for single metadata item for a given data value?
(We could perhaps apply existing data consolidation practices here.)
