---
layout: personal
job-title: Development Team Leader
photo: katkav.jpg
academic-titles: Ing (MSc)
profile-github: katkav
profile-twitter: KValalikova
profile-linkedin-url: https://www.linkedin.com/in/katarina-bolemant/
evolveum-blog: https://evolveum.com/author/katka-bolemant_bolemant/
---

= Katarína Bolemant

== Short Bio

Katarina is the Development Team Leader at Evolveum. 

She is one of the founding members of Evolveum, where she started as a Java developer. Her main responsibilities in this role were product bug fixing, new feature development, and testing.
Being part of the development team since the beginning has taught her valuable lessons about midPoint, challenges customers face and how to resolve them from the product perspective, and setting up the processes as the company continued to grow.

Now she leads a team of full-time developers. Their main focus is on midPoint maintenance and new feature development. She is also heavily involved in midPoint’s architecture and design.

== Education

* Inžinier (Ing., master) degree from https://www.stuba.sk/[Slovak University of Technology]

== Publications and Talks (selection)

https://www.youtube.com/watch?v=kSV_2sYhqhk 
Presentation at the European Identity and Cloud Conference 2023 about simulations.

https://www.youtube.com/watch?v=EPQj_4VIfFo
Webinar "What's New in MidPoint 4.7"

https://www.youtube.com/watch?v=AUhvr683wHY[Identity management with open source solution]::
Presentation at Voxxed Days Luxembourg 2019

https://fosdem.org/2018/schedule/event/idm_midpoint/[Identity Governance and Data Protection with midPoint]::
Presentation at FOSDEM 2018, Brussels (with Radovan Semančík)

xref:/talks/files/2015-11-ldapcon-complete-open-source-iam-solution.pdf[Complete Open Source IAM Solution]::
Presentation at LDAPcon 2015, Edinburgh (with Radovan Semančík)

== Project Participation (selection)

xref:/midpoint/[MidPoint]::
since 2011, software architect and lead developer

https://github.com/Evolveum/midpoint-client-java[MidPoint Java Client]::
since 2017, developer and maintainer

OpenIDM version 1 (project discontinued)::
2010-2011, developer
