---
layout: personal
job-title: Chief Product Officer
photo: katkav.jpg
academic-titles: Ing (MSc)
profile-github: katkav
profile-twitter: KValalikova
profile-linkedin-url: https://www.linkedin.com/in/katarina-bolemant/
evolveum-blog: https://evolveum.com/author/katka-bolemant_bolemant/
---

= Katarína Bolemant

== Short Bio

Katarína is the Chief Product Officer at Evolveum.

She is one of the founding members of Evolveum, where she started as a Java developer. Her main responsibilities in this role were design and development of new features, product bug fixing, and testing.
Being part of the development team since the beginning has taught her valuable lessons about midPoint, challenges customers face and how to resolve them from the product perspective, and setting up the processes as the company continued to grow.

As the Chief Product Officer, Katarina now creates midPoint's roadmap and leads teams responsible for development of midPoint and R&D team working on features based on AI/ML algorithms.
She is also heavily involved in midPoint’s architecture and design.


== Education

* MSc degree from https://www.stuba.sk/[Slovak University of Technology]

== Publications and Talks (selection)

https://www.youtube.com/watch?v=tb6gBhtT0bw[What's New In MidPoint 4.8]::
Live online webinar about midPoint 4.8 release

https://www.youtube.com/watch?v=kSV_2sYhqhk[Better Safe than Sorry: A Peek into the Future with IGA]::
Presentation at the European Identity and Cloud Conference 2023 about simulations.

https://www.youtube.com/watch?v=EPQj_4VIfFo[What's New In MidPoint 4.7]::
Live online webinar about midPoint 4.7 release

https://www.youtube.com/watch?v=AUhvr683wHY[Identity management with open source solution]::
Presentation at Voxxed Days Luxembourg 2019

https://fosdem.org/2018/schedule/event/idm_midpoint/[Identity Governance and Data Protection with midPoint]::
Presentation at FOSDEM 2018, Brussels (with Radovan Semančík)

https://www.youtube.com/watch?v=_gPxURDKW7E[How to Govern and Maintain Compliance Using Open Source Identity Management Components]::
Presentation at ApacheCon 2017, Miami (with Shawn McKinney)

https://feathercast.apache.org/2016/12/09/apachecon-seville-2016-next-generation-directory-based-user-management-for-cloud-infrastructure-shawn-mckinney-katarina-valalikova/[Next Generation Directory-Based User Management for Cloud Infrastructure]::
Presentation at ApacheCon 2016, Seville (with Shawn McKinney)

https://archive.fosdem.org/2016/schedule/event/virt_iaas_infrastructure_provisioning/[Infrastructure provisioning in context of organization]::
Presentation at FOSDEM 2016, Brussels

xref:/talks/files/2015-11-ldapcon-complete-open-source-iam-solution.pdf[Complete Open Source IAM Solution]::
Presentation at LDAPcon 2015, Edinburgh (with Radovan Semančík)

== Project Participation (selection)

xref:/midpoint/[MidPoint]::
* 2011 - 2020, Software developer
* since 2020, Chief Product Officer
* since 2023, AI/ML team leader (role mining, outlier detection)

https://github.com/Evolveum/midpoint-client-java[MidPoint Java Client]::
since 2017, developer and maintainer

OpenIDM version 1 (project discontinued)::
2010-2011, developer
