---
layout: personal
job-title: Development Team Leader
photo: katkav.jpg
academic-titles: Ing (MSc)
profile-github: katkav
profile-twitter: KValalikova
profile-linkedin-url: https://www.linkedin.com/in/katarína-bolemant-21a85250/
evolveum-blog: https://evolveum.com/author/katka-bolemant_bolemant/
---

= Katarína Bolemant

== Short Bio

Graduated from the Slovak Technical University with a master degree in Software Engineering.
At the time she works for Evolveum as development team leader, being part of the team from its very beginning.
She leads the development of midPoint, open source identity management and governance platform.

== Education

* Inžinier (Ing., master) degree from https://www.stuba.sk/[Slovak University of Technology]

== Publications and Talks (selection)

https://www.youtube.com/watch?v=AUhvr683wHY[Identity management with open source solution]::
Presentation at Voxxed Days Luxembourg 2019

https://fosdem.org/2018/schedule/event/idm_midpoint/[Identity Governance and Data Protection with midPoint]::
Presentation at FOSDEM 2018, Brussels (with Radovan Semančík)

xref:/talks/files/2015-11-ldapcon-complete-open-source-iam-solution.pdf[Complete Open Source IAM Solution]::
Presentation at LDAPcon 2015, Edinburgh (with Radovan Semančík)

== Project Participation (selection)

xref:/midpoint/[MidPoint]::
since 2011, software architect and lead developer

https://github.com/Evolveum/midpoint-client-java[MidPoint Java Client]::
since 2017, developer and maintainer

OpenIDM version 1 (project discontinued)::
2010-2011, developer
