= Certification - process
:page-nav-title: Certification - process
:page-toc: top
:toclevels: 3
:sectnums:
:sectnumlevels: 3


Certification process should contain following steps:

. Campaign definition
. Recertification
. Remediation
. Summary

#TODO - we need also define what should be in certification template#

== The process

The user interface should be defined in that way, that the campaign can be specified, started and even analyzed by "advanced" business user. It means, that security officer should be able to start new certification or certification campaign.

The campaigns should be started from previously prepared *certification templates*. These templates (our certification definitions) should be prepared by engineers.

=== Campaign Definition
The user interface Should be understandable for an advanced business user (simplify the terminology).
The uuser just selects from a predefined template and then determine which individuals need certification, what to be certified and probably some other details.

Definition of the campaign should consist of following steps:

.Select objects for certification (who/what will be certified)
* object type, list of objects.
* This step can also be omitted (if dealing with all individuals with a specific assignment).

.Specify what needs certification
* Assignments (select desired ones).
* Attributes (and their selection)
** even extended attributes can be selected here (should be defined in template)
* Content of the role (inducements within business role)
* Specific assignment - role owner/approver

The certification may be complex: E.g. certification of business roles - may require certification of all inducements and attribute "description" and approver  as well .


.Who will perform certification
Choose the manager of the individual (according to which organizational structure?), or the role owner can also recertify.


.Possible decisions (types of decisions allowed)
* "Extend validity." - button for extending validity of an assignment
** whether this button should be displayed here
* "Allow "I don't know' response." (our button Not decided)
    ** do we need to display here
* if attributes are being certified, it may happen, that we he wants to provide possible new values for specific attribute

.Recertification aggressiveness
This option can tell what to do with unanswered certification items.
* Normal
* Agressive - the unanswered certified assignments are removed

.Certification validity period
* deadline till which the certification campaign finishes.
* Until closed by the author.

.Remediation method
* Automatic -  what midPoint can remove will be removed
* Report - midpoint prepares remediation report
** what should be in the report ? Revoke or also undecided ?
* Hybrid (?) - what is decided will be revoked automatically, other will be reported in the remediation report

=== Certification

The user interface should be easy to use. #TODO - how should user interface look like ?#

#not sure# The interface should be probably different for certification campaign and microcertification.

We are *displaying direct assignments only*. Each manager will have quite a lot of direct assignments to answer. It would make the overview too complex if he has indirect asignments as well.

#not sure# We will need to display assignments assigned by policy, but we need to explain that this is by some policy.
These assignments (although they can't be removed) must be shown as it should be confusing for users.

User interface should be easy to use just for certification of user validity (e.g. whether the user still works) and some his attributes.

=== Remediation

Automatic/manual / hybrid

#TODO - must be discussed - #

=== Summary

Now the cerification campaign is done. One page nas show some statistics of the campaign.

#?dashboard ? or what else ?# Some dashboard displaying basic information - what it was about.

* Basic report from the certification campaign (basic).
** CSV/Excel - with all responses, for further processing. (users can process it manually - flexibility) +
    For more sophisticated environments, an engineer can modify it.

* Remediation report - if the remediation is set by

