= Certifications
:page-nav-title: Certifications
:page-toc: top
:toclevels: 3
:sectnums:
:sectnumlevels: 3

This document contains certification description for upgrade of design of certifications.
It is prepared for planning of development of *midPoint version 4.9*.

// [#_access_removal_vs_certification_triggered_by_business_user]
== Access removal vs microcertification vs certification

The removal of access can be addressed by directly removing a certain access (your own, someone's specific, or access of a group of people) or by requesting certification of the access.

.Access removal
If I perform the access removal myself, it should be a standard removal. However, if I want to ask someone else to remove the access or make a decision about it, it needs to be handled as a certification.

.Certification
Certification can relate to individual objects (certify assignments of one user) or can relate to multiple objects.
Although the concept is the same, user interface and handling should be slightly different.

Full scale certifications are run in certification campaigns - e.g. "All managers, certify all assignments of your direct subordinates users in your org unit". The person (managers in this case) must review all assignments of all of his subordinates and respond to each assignment.
This may take time, and requires quite a lot of work. Multiple people are required to participate and review access of multiple users.

.Microcertification
The certification request can be specified on much smaller scope - e.g. "Certify assignments of this user."
Such certification of individual objects is called microcertification.

Microcertification should be started ad-hoc by some decision or by events.
Each microcertification case is individual.

The person who performs the certification should respond to the request very easily - ideally on one page.

== Certification reporting
The reporting between certifications and microcertification cases differs.
Certifications are ran in campaigns. Microcertifications are individual.

=== Certification dashboard
Certification dashboard should provide fast overview which chertifications ran oduring defined time period and some statistics to them (e.g. success rate).
The stats should be able to be split by certification campaing type ("template"?).

==== Possible metrics for certifications

Certification metrics should be done per certification campaign / or type.

.Certification overview/results
* All certifications requested/started in the defined time period.
    ** certifications by campaign & date
    ** certifications by template

* avg (total?) number of assignments to certify
* avg (total?) number of responses
* avg (total?) count of answers (Accept / Revoke / Not decided / remove after )

* percentiles (?) calculate something other than averages +
Utilizing percentiles provides a better overview than averages, but algorithms are not straightforward, and explaining them is more challenging.
    ** e.g. 90% of certifications removed below 2 assignments
    ** e.g. 90% of responses ion this campaign were finished within 2 weeks.
    *** despite average can be 3 days - the percentile provides better overview about process

==== Possible metrics for microcertifications

Metrics for microcertification should be computed for defined interval (e.g. month)

.Certification throughput
How many microcertification were performed in organization (e.g. 1000 last month)
* requested
* in progress (certification) - kolko je aktualne v procese certifikacie
* certifications by trigger

.Certification speed
* avg. certification speed -
* 90% certification speed - how long it took to respond (see precentiles above)

.Certification success rate

////
.Certification check result
		- kolko certifikacnych checkov prebehlo minuly mesiac
		- success rate (pocet uspesnych z celkovych)
		- failed certification checks
////

=== Certification reports

#TODO - reports#
-top 10 most removed objects

==== Basic certification report

One report out of certification campaign.
CSV/Excel - with all responses, for further processing. (users can process it manually - flexibility) +
For more sophisticated environments, an engineer can modify it.

==== Remediation report

Certification campaing may be set in a way, that midPoint is not revoking assignments automatically. In such case it generates remediation report. This report lists all assignments that has to be revoked.
Ideally - on technical level grouped by resource.

#TODO - how deep to go in remediation report ? - We should define technicals - remove user from group X. But - can we do that ?#
