---
layout: connector-page
display-order: 200
functionality-status: unknown
development-status: active
support-status: unknown
origin: Evolveum
support-provided-by: Evolveum
target-systems: Grouper (Internet2 et al.)
connector-protocol: JDBC
source-url-master: https://github.com/Evolveum/connector-grouper
description: Identity connector for Grouper. Using JDBC to connect to a PostgreSQL database.
upkeep-status: yellow
---
= Grouper Connector (JDBC)
:page-wiki-name: Grouper Connector (JDBC)

Connector for Grouper access management system.

Group membership management, management of the "Subject" object type and also
capabilities to read additional extension attributes of all object types. PostgreSQL database JDBX driver
is a part of the connector distribution.

== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| Schema
| YES
| Group and Subject object type.
Extension schema is fetched dynamically during configuration discovery. Or can be extended
as configuration property.

| Provisioning
| NO
|

| Live Synchronization
| Yes
|
Using last modification timestamps. Supports "Group", "Subject" and "All" object classes.

| Password
| NO
| Not needed for group membership management.

| Activation
| NO
|

| Filtering changes
| NO
|

| Paging support
| YES
| Pagination using the Private Key which represents object ID

| Native attribute names
| YES
|

|===


== History


[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | Framework version | Bundled with midPoint | Description


|===


== Interoperability

* ConnId 1.5.1.3 (Evolveum release), which is part of midPoint 4.6.
* PostgreSQL 15.2 and higher
* TODO: Grouper versions. etc ...

== Support

This connector is _supportable_ by Evolveum.

Evolveum can provide support for this connector.
However, support for this connector is not provided on a routine basis and some special arrangements
and customizations may be needed.
Please contact Evolveum representative for the details.

== Configuration parameters

[%autowidth]
|===
| Parameter | Note | Example | Configuration discovery

| Host
| Hostname / ulr pointing to the grouper database.
| 127.0.0.1
| No

| TCP Port
| Enter the port number for the connection to the database server.
| 5432
| No

| Database name
| Name of the database schema containing grouper object tables.
| grouper
| No

| User Name
| Name of the management account on the database server with permissions to the grouper schema.
| midpoint
| No

| Validation Timeout
| The number of seconds which represent the limit for connection validation. Setting this parameter to '0' means indefinite.[default value is 10]
| 15
| Yes, configuration discovery will show default value with the possibility of override.

| Password
| Password to the management account.
| 5ecr3t
| No

| Subject Extensions
| Extension Attributes for Subject Object Type. Multivalued property.
| Foo, Baar
| Yes, Configuration discovery will offer possible values.

| Group Extensions
| Extension Attributes for Group Object Type
| Foo, Baar
| Yes , Configuration discovery will offer possible values.

| Exclude Objects marked as Deleted
| This option if set to 'True' excludes the objects marked as Deleted from search results. If set to 'False' this could cause the IAM to misinterpret the object as 'not deleted' in the event of a reconciliation.
| True
| Yes , Configuration discovery will offer possible values.

| Enable ID based Paging
| Id based pagination using the Private Key representing object ID for pagination. [default value is false]
| True
| Yes , Configuration discovery will offer possible values.

| Maximum Page Size
| The maximum number of records which will be returned by any connector operation, after which is processed a next set of records will be requested from the resource for further processing. [Used when 'Enable ID based Paging' is set to true]
| True
| Yes , Configuration discovery will offer possible values.

|===

== Resource Examples
* https://github.com/Evolveum/connector-grouper/blob/main/samples/resources/template/resource-template-grouper.xml[Resource Template]

== Notes

Connector working with the PostgreSQL based deployments of Grouper.

Connector supports pagination and a 'max page size' configuration parameter. This will divide the query into multiple ones
with outputs containing smaller number of rows (based on page size or the 'max page size' configuration parameter).
There still can be the possibility of higher number of rows returned in case of an object having a large number of members or
group memberships or a large number of auxiliary attributes.

With 'Exclude Objects marked as Deleted' set to true the rows marked as 'deleted' are handled as not present.
In case of rows present in the 'main' object tables, the objects will be handled as deleted. In case of
rows present in the membership or auxiliary attributes tables the lack of the row will mean a removal of parameter value.

The "Configuration discovery" operation among other functions will provide you with a list of possible names
of auxiliary attributes which if selected will be incorporated in the attribute schema. This list of attributes can
be changed in the resource configuration, after which the schema should be 'regenerated' ('refreshed').

The "members" and "member_of" ("virtual" attributes) are not retrieved by default, the attribute configuration
in the IAM has to explicitly request these attributes. The same applies to attributes originating from
other tables as the main ones (Tables referred to as the main tables: "gr_mp_subjects" and "gr_mp_groups").

== See Also
TODO