= General Copyright and Licensing Guidelines
:page-visibility: auxiliary
:page-toc: top
:page-description: This article explains midPoint and its documentation licensing, your liberties, obligations, and contribution conditions.
:page-keywords: contribute, contribution, dual licence, licence, liberties, documentation, dual licensing, eupl, apache, open source

Unless explicitly stated otherwise, all work published on this site and all other Evolveum sites is *Copyright © Evolveum, s.r.o., all rights reserved*.

== Documentation license

All Evolveum documentation is available under the terms of *https://creativecommons.org/licenses/by-nc-nd/4.0/[Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0) license]*.

The _documentation_ means all the materials that are publicly available on https://docs.evolveum.com/[docs.evolveum.com] web site.

While the license says _NonCommercial_, you can use the documentation for almost all the usual things that you can think of, that are not primarily intended for commercial advantage or monetary compensation.

Simple speaking, you are *allowed* to:

* *Read the documentation, learn from it and use the knowledge* for any purpose, which may include commercial use.
In fact, commercial use of your knowledge is more than encouraged.
We want you and your organization to prosper.

* *Quote from the documentation*, which means copying short parts of the documentation.
You can use the quoted parts for any purpose, as long as the size of the quoted part is reasonable.
For example, you can copy samples from the documentation and use it in your configuration, even for commercial purposes.
You can copy reasonable parts of the documentation in your academic paper, in your blog, even in a wiki dedicated to your commercial project.
If you are publishing such parts in a form that is supposed to be read by a human, you are supposed to include proper attribution (see below).
Just remember, that these parts must be small.
When in doubt, look up how your applicable copyright legislation defines "fair use".

* *Link to the documentation* from anywhere, whether the source is public or private, commercial or non-commercial.
All the documentation is publicly available, therefore a simple link is usually enough to convey the information.
Linking to our documentation is strongly encouraged.
We want the knowledge to spread far and wide.

* *Share the documentation freely* in your organization, team or research group.
You can save the documentation of off-line use.
You can copy the information as it is and share it.
You can even convert it to a different format, as long as the meaning and general look of the document stays the same.
E.g. you can convert the documents to make them readable for visually-impaired persons.
Just make sure you give proper attribution in all such cases (see below).

If you do this, you do not need to contact us or let us know.
Just go ahead and do it.

While doing that, you *must*:

* *Give attribution*.
You are supposed to mention author of the document when quoting from it or using it in any similar way.
Use appropriate text for that;
it should include a mention of `Evolveum` or `docs.evolveum.com`.
Provide a link to the original document whenever you can.

* *Keep us free from any liability*.
The documentation is provided "AS IS".
While we make reasonable effort to main quality of the documentation, we are people too.
We can make mistakes, we can omit details, we may forget to update outdated information.
Please bear with us.
If you find a problem, let us know.
We fill fix it as soon as possible.
However, we make no guarantees.
If bet your fortune on the information in the documentation, it is your responsibility to make sure the information is correct, complete and up-to-date.

You are *not allowed* to:

* *Copy significant part of the documentation for profit*.
You must not take our documentation, make a book out of it and sell the book.
If you want to do that, please contact us.
We can grant you a special license in exchange for reasonable royalties.
You must not download documents from our site, convert it into a manual for your commercial project and deliver that to the customer.
Linking to our documentation is OK, copying, modifying and reformatting it for your project is not OK.
If you want to do that, please contact us.
We can agree on a license in exchange for a reasonable share of your profit.
You must not use significant parts of our documentation to compile an operation manual for your service provider company.
If you want to do that, please contact us.
We can negotiate a reasonable license that can cover your use case.

* *Modify the documentation and distribute modified versions*.
If you modify the documentation, we no longer know that it is correct.
It may confuse or mislead the users.
Documentation is not code, there is no simple way how to _test_ the documentation.
Therefore we want to keep some degree of control over the quality of the documentation.
If you would like to reuse the documentation for your project, convert or translate the documentation, please contact us.
We will find a way how this could work.
We would just like to have an opportunity to assure the quality of the final result.

We are all in favor of spreading the knowledge, and we want to make your life easier.
However, the use specified above is not allowed under the terms of CC BY-NC-ND license.
Please contact us, and if your case makes sense, we can certainly find a way how to cooperate.

*Consult with us* if you want to:

* *Translate the documentation*.
We fully support internationalization and translation efforts.
However, we like to keep some overview over such efforts, mostly to maintain quality and protect or reputation.
We usually provide royalty-free licenses for translation, as long as your translation is also made available under the terms of CC BY-NC-ND license.

* *Use significant parts of the documentation in your academic or not-for-profit project*.
We would gladly grant you royalty-free license in such case.
We just want to make sure there are reasonable limitations for commercial abuse of the documentation.

Our general recommendation regarding the use of our documentation is to use common sense.
If the thing that you are trying to do is usual, and it feels like an appropriate and fair use, then it is probably allowed.
If it does not feel right, or you feel that you are pushing the boundaries too far, the best strategy would be to contact us.
We will try to find a way how to cooperate.

NOTE: This license applies to _documentation_ only.
You are not allowed to use Evolveum sales, marketing and any other materials.
You are not allowed to use our trademarks.
You will need special license for this.
Such license is usually part of Evolveum partner agreement.

== Source Code Licenses

== Source code licenses

Since version 4.10, midPoint source code is licensed under the terms of link:https://eupl.eu/[European Union Public License 1.2 or later (EUPL)].
The EUPL gives you the following freedoms and obligations:

* You can use the code for pretty much any purpose, including commercial purposes.

* You can redistribute the code, even modify it.
Just maintain the copyright and include license statement.

* You must not hold us liable.
The code is provided as it is, take it or leave it.
It is your responsibility to make sure it works for you, not ours.

* You are not granted any right to use our trademarks.

* If you modify the source code, you must publicly distribute it ("copyleft" license).

MidPoint versions 4.0-4.9 are dual-licensed under the terms of link:https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0 (AL)] and link:https://eupl.eu/[European Union Public License 1.2 (EUPL)].
Dual licensing means that you can choose any of these licenses for your particular use of our source code.

If you choose the Apache licence, you do not have to distribute the source code if you make any modifications to it.

This explanation is simplified.
Please refer to full text of the licenses for details.

NOTE: That are some parts of code that are licensed under Apache License only.
They are not dual-licensed for simplicity, to make contributions easier.
This usually applies to parts of the code that are outside of midPoint core and to auxiliary data such as samples and translations.
Such parts are single-licensed under the terms of Apache License, as this license is more liberal of the two.
Also, the connectors are usually single-licensed under the terms of Apache License.
However, due to historical reasons, some connectors may use a different license, most notably CDDL.
Each project has its own `LICENSE` file that specifies the licensing condition.


=== Contributions

If you decide to contribute to midPoint 4.10 and newer, your contribution will be licensed under the EUPL.
There is no paperwork you would need to sign as long as your contribution stays in the versions 4.10 and newer.

It is more complicated for the dual-licensed versions 4.0-4.9.

Since midPoint versions from 4.0 to 4.9 are dual-licensed under Apache Licence 2.0 and European Union Public License 1.2, there is additional paperwork involved in contributing to these versions.
In short, we need you to sign the _Contributor License Agreement (CLA)_, which allows us to re-license your contribution and publish it under both licences.
Please refer to xref:/community/dual-licensing/#contributions[] for more details.

If you contribute to parts that are not dual-licensed, the CLA is not needed, because licensing conditions are clear in that case.
This applies to midPoint versions 4.10+, translations, configuration samples, and most of the connectors.

== Services

MidPoint is a _free and open source software (FOSS)_.
You can use midPoint for pretty much any purpose and you do not have to pay us.
However, the situation is entirely different when it comes to our services.

*Our software is free, but our services are not.*

Please feel free to use our software for any purpose that you want to.
As long as you do not want anything from us, you do not have to pay anything to us.
However, if you want anything from us, be prepared to compensate us for our time.
If you need a bugfix, if you want to consult your configuration, or even you want us to teach you about midPoint you have to pay a fair price.
There are inherent _liberties_ in open source, but there is also a _cost_ to pay.
The license grants you the liberties of open source _software_, but it does not automatically grant you the time and attention of open source _engineers_.
