= NIS 2 Compliance
:page-nav-title: NIS 2
:page-upkeep-status: red

WARNING: Work in progress!

link:https://eur-lex.europa.eu/eli/dir/2022/2555[Directive (EU) 2022/2555 of European Parliament and of the Council on measures for a high common level of cybersecurity across the Union], known as _NIS 2 Directive_ for short, mandates sound cybersecurity practices for crucial organizations, such as public administration, energy, finance, healthcare, infrastructure and many others.
Affected organizations are expected to establish risk management practices, implement business continuity measures, and report cybersecurity incidents.
It is a part of xref:../#european-union[broader cybersecurity initiative] of European Union.

Being a legislative act, NIS 2 is not very specific when it comes to technical details.
The only "technical" description in the normative part of the directive is article 21, which lists 10 points mentioning cybersecurity measures to implement:

[loweralpha]
. policies on risk analysis and information system security;
. incident handling;
. business continuity, such as backup management and disaster recovery, and crisis management;
. supply chain security, including security-related aspects concerning the relationships between each entity and its direct
suppliers or service providers;
. security in network and information systems acquisition, development and maintenance, including vulnerability
handling and disclosure;
. policies and procedures to assess the effectiveness of cybersecurity risk-management measures;
. basic cyber hygiene practices and cybersecurity training;
. policies and procedures regarding the use of cryptography and, where appropriate, encryption;
. human resources security, access control policies and asset management;
. the use of multi-factor authentication or continuous authentication solutions, secured voice, video and text
communications and secured emergency communication systems within the entity, where appropriate.

The directive repeatedly refers to best practice and international standards.
ISO/IEC 27000 series is explicitly mentioned in Recital 79.

Even though the normative part of NIS 2 Directive is technologically vague, there are some interesting details in the recitals.
Recital 51 encourages use of innovative technologies, including AI.
Recital 52 endorses use of open source technologies.
Recital 89 explicitly mentions identity and access management (IAM).

== Related Documents

* link:https://eur-lex.europa.eu/eli/reg_impl/2024/2690/oj/eng[Commission Implementing Regulation (EU) 2024/2690] laying down rules for the application of NIS2 Directive with regard to digital infrastructure, ICT service management and digital providers.

* link:https://www.enisa.europa.eu/publications/nis2-technical-implementation-guidance[NIS2 Technical Implementation Guidance] published by ENISA. +
Provides technical guidance to support the implementation of the NIS2 Directive for several types of entities in the NIS2 digital infrastructure, ICT service management and digital providers sectors, with respect to Commission Implementing Regulation (EU) 2024/2690.
