= XSD Schema

Welcome to the comprehensive guide on effectively handling the life cycle of XSD (XML Schema Definition) elements.
This document aims to provide you with a clear understanding of the steps involved in managing XSD elements for midPoint schemas throughout their entire life cycle.

== Life cycle for XSD elements

Currently, there are multiple states life-cycle for elements in our XSD is following:

. Created in XSD
. Modified (optionally)
. Deprecated
. Removed
. Deleted from XSD

=== Creation

Designing XSD elements is a crucial aspect of ensuring the integrity and consistency of XML data.
Each new XSD element and type should contain documentation and annotations.

[source,xml]
----
<xsd:annotation>
    <xsd:documentation>
        <!-- TODO -->
    </xsd:documentation>
    <xsd:appinfo>
        <a:since>4.8</a:since>
    </xsd:appinfo>
</xsd:annotation>
----

=== Modification

#TODO#

=== Deprecation

#TODO#

[source,xml]
----
<xsd:annotation>
    <xsd:appinfo>
        <a:since>4.6</a:since>
        <a:deprecated>true</a:deprecated>
        <a:deprecatedSince>4.7</a:deprecatedSince>
        <a:plannedRemoval>4.8</a:plannedRemoval>
    </xsd:appinfo>
</xsd:annotation>
----

=== Element removed

#TODO#

[source,xml]
----
<xsd:annotation>
    <xsd:appinfo>
        <a:since>4.6</a:since>
        <a:deprecatedSince>4.7</a:deprecatedSince>
        <a:removed>true</a:deprecated>
        <a:removedSince>5.0</a:plannedRemoval>
    </xsd:appinfo>
</xsd:annotation>
----

=== Element deleted from XSD

#TODO#

#TODO add schema migration#
