= Missing Pages
:page-visibility: system

We are missing these pages, or following topics are missing in docs.

* Correlation: general introduction to correlation mechanisms, introducing correlators, deprecating correlation expressions

* Reconciliation: general introduction (also link in the glossary)

* License management

* Application catalog: idea, approach, example
** Relation to asset management and risk management
** Why is IGA very close to assets/risks: risk depends on access rights to applications, different rights may meant access to different assets or information sensitivity.

* Log/audit consistency: recommend separation of duties to ensure non-modifiable logs/audit (append-only table), explain problem with non-modifiable audit. - separate docs page

* How to use locations - they are hierarchical

* Difference between: delegated administration, deputy, power of attorney

* RBAC: improvements over NIST RBAC (e.g. PD-RBAC)

* Role engineering guide: role types (application, business), inducement to application, autoassignment, object template mappings, role mining.

* Policy Rules

** orderContraint

== Features

* Object governance: owners, role certification

See also: list of features without any docs: xref:/sys/docless-features/[Docless features]

== Check

Check whether we have this:

* Guide to import AD groups as application roles (step by step)

* Role mining guide for "end users"
