---
layout: connector-page
display-order: 900
functionality-status: stable
development-status: abandoned
support-status: unsupported
origin: Evolveum
target-systems: Novell/NetIQ eDirectory
connector-protocol: LDAP/LDAPS
description: Legacy LDAP-based connector for eDirectory servers.
visibility: hidden
---
= eDirectory Connector
:page-wiki-name: eDirectory Connector

[WARNING]
.Legacy, unsupported
====
This connector was part of LDAP bundle for many years.
However, there is no demand for this connector among midPoint subscribers.
Therefore this connector is considered to be a legacy and was removed from LDAP bundle.
====

This connector is an eDirectory-specific extension of our LDAP connector.
It contains, among others, support for the following attributes:

* user (inetOrgPerson) attributes: groupMembership and securityEquals for maintaining referential integrity

* group (nestedGroupAux) attributes: equivalentToMe and member

See link:http://ldapwiki.willeke.com/wiki/Groups%20Edirectory[this link] for reciprocal attributes overview.

Based on Apache Directory API.
Apache-licensed.

== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| Schema | YES |

| Provisioning
| YES
|

| Live Synchronization
| YES
| Only using modifyTimestamp, but untested.

| Password
| YES
|

| Activation
| YES
| loginDisabled attribute is used

| Filtering changes
|
| currently limited

| Paging support
| YES
| Simple Paged Results and VLV

| Native attribute names
| YES
| Use ri:dn instead of icfs:nameUse ri:entryUUID instead of icfs:uid

|===


=== History

This is an extension of the LDAP connector completely rewritten from scratch.


== Versions

[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | Description

| 1.4.2.0
| Polygon
| link:http://nexus.evolveum.com/nexus/content/repositories/releases/com/evolveum/polygon/connector-ldap/1.4.2.0/connector-ldap-1.4.2.0.jar[download jar]
| link:https://github.com/Evolveum/connector-ldap/tree/v1.4.2.0[GitHub]
| August 2015
| Official release


| 1.4.2.18
| Polygon
| link:http://nexus.evolveum.com/nexus/content/repositories/releases/com/evolveum/polygon/connector-ldap/1.4.2.18/connector-ldap-1.4.2.18.jar[download jar]
| link:https://github.com/Evolveum/connector-ldap/tree/v1.4.2.18[GitHub]
| August 2015
| Official release.
Minor changes.


|===


== Documentation

Be advised there are multiple interesting limitations within the eDirectory (not midPoint):

* CN attribute has a maximum size of 64 characters

* subsequent white spaces (e.g. spaces) and underscores in the attribute values are considered to be the same as single space, so the following objects are considered to be the same and cannot be created simultaneously:

** "cn=this is a space,ou=people,o=example"

** "cn=this   is      a     space,ou=people,o=example"

** "cn=this is a space ,ou=people,o=example"

** "cn=this\_is\_a\_space,ou=people,o=example"

** "cn=\___this\___is\___a\___space,ou=people,o=example"


* searching for values with whitespace e.g. "cn=a\__b\________c" may actually return object "cn=a b c,ou=people,o=example".


== Resource Samples

* link:https://github.com/Evolveum/midpoint/blob/master/samples/resources/edirectory/resource-edirectory-nosync.xml[eDirectory sample from master branch]


== See Also

* wiki:LDAP+Connector+Migration[LDAP Connector Migration]

