---
layout: connector-page
display-order: 800
functionality-status: stable
development-status: unknown
support-status: unknown
origin: ICF
support-provided-by: Evolveum
target-systems: Oracle database (users, administrators)
connector-protocol: JDBC
description: Connector to provision Oracle database accounts.
connid-bundle-name: org.forgerock.openicf.connectors.oracle-connector
upkeep-status: yellow
---
= Oracle Connector
:page-wiki-name: Oracle Connector
:page-wiki-id: 22741385
:page-wiki-metadata-create-user: vix
:page-wiki-metadata-create-date: 2016-05-31T10:57:47.570+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-07-09T14:02:33.928+02:00


[NOTE]
.Unknown status
====
Status of this connector is unknown.
It is not known whether it can work with recent software version.
It was not recently tested and it is not part of any automated QA process.
In case that you are interested in this connector please contact Evolveum sales representatives.
====

Connector to provision Oracle database accounts.
For provisioning other tables use xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable Connector].


== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| Provisioning
| YES
|

| Live Synchronization
| NO
|

| Password
| YES
|

| Activation
| YES
|

|===


=== History

This is almost entirely the original version from Sun ICF.

[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | Description

| 1.1.0.0
| OpenICF trunk version, built and tested by Evolveum
| https://nexus.evolveum.com/nexus/repository/openicf-releases/org/forgerock/openicf/connectors/oracle-connector/1.1.0.0/oracle-connector-1.1.0.0.jar[download jar]
| Evolveum source: link:https://github.com/Evolveum/openicf/tree/master/connectors/java/oracle[https://github.com/Evolveum/openicf/tree/master/connectors/java/oracle]
| May 2016
|


|===

== Notes

Use UPPERCASE characters for user login (icfs:name).
Oracle will uppercase it anyway.