= Task Manager Interface
:page-wiki-name: Task Manager Interface
:page-wiki-id: 2654374
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2011-08-01T18:16:31.504+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2011-09-27T10:44:29.755+02:00
:page-archived: true
:page-outdated: true
*Version:* 0.1 +
*Status:* Public +
*Stability:*[.red]#DRAFT#, WORK IN PROGRESS +
*Platform:* Java +
*Dependencies:*xref:/midpoint/reference/schema/[Data Model]: Common, Identity and Model schema +
*Responsible person:* Radovan Semancik


== Description

Task manager provides controls task execution, coordination, distribution and failover between nodes, etc.

This interface is just a basic framework for task management now.
Although we hope that this is roughly almost final shape of the interface, the implementation is not complete and some changes may happen.

This definition specifies interface of Task Manager - a component that controls (asynchronous) task execution.

The task manager can store the task for later execution, switch them to background resume execution of a task from a different node, etc.
Generally speaking, task manager provides operation to manage tasks in the whole midPoint cluster of IDM nodes.

This interface partially adheres to xref:/midpoint/architecture/concepts/common-interface-concepts/[Common Interface Concepts], but the goals are slightly different.
This interface should be conveniently used also for tasks that are not persistent (synchronous short tasks).
Therefore some methods are made much more user-friendly while tolerating some redundancy in the interface.


== History

[%autowidth]
|===
|  Version  |  Date  |  Description  |  Change Author

|  0.1
|  July 2011
|  Initial version
|  Radovan Semancik


|===


== Documentation

In-line in the interface definition.
Please see _Artifacts_ below.


== Artifacts

[%autowidth]
|===
|  Artifact  |  Version  |  Path  |  Description

|  Interface definition
|  trunk
| link:https://svn.evolveum.com/midpoint/trunk/repo/task-api/src/main/java/com/evolveum/midpoint/task/api/[https://svn.evolveum.com/midpoint/trunk/repo/task-api/src/main/java/com/evolveum/midpoint/task/api/]
|  Java definition of the interface.



|  Interface documentation
|  trunk
| link:http://neptunus.evolveum.com/midPoint/latest/javadocs/[complete javadoc], link:http://neptunus.evolveum.com/midPoint/latest/javadocs/com/evolveum/midpoint/task/api/TaskManager.html[TaskManager]
|  Javadoc documentation of the interface.



|===