= Openness
:page-wiki-name: Openness
:page-upkeep-status: orange

== Pure Open Source

MidPoint is open source product maintained in an open source spirit.
Everything in midPoint is developed under Apache Licence and is publicly available.
There are no open-core or other semi-commercial parts.
MidPoint is open in all aspects.
The source code is publicly available (including the most recent development version) under the OSI-approved Apache open-source license.
The design is openly discussed with the community.
The development team is open to contributions from the public.
Only open protocols and platforms are used.
System interfaces are well documented and open for reuse.
But, most importantly, midPoint is open to use by anyone and for any purpose at no charge (as long as it complies with Apache licence).

This openness gives countless possibilities for midPoint.
Possibilities that are not feasible with other business models.


== What You Can Do

You can do anything with midPoint that does not violate the Apache Licence.
Which means you can do pretty much anything.
Including the following:

* Use midPoint for PoC, testing, pilot and even *production deployments*.

* Create *your own version* of midPoint for your deployment.
You can even publish your own version and you can even use a different name for such version (as long as you give proper credit according to the Apache licence).
It would be nice if your own version had some kind of "based on midPoint" or "powered by midPoint" graphics, but strictly speaking you are not required to do so.

* You can create a *cloud service* based on midPoint.
Or you can use midPoint as one of the components in your cloud service.

* You can create a complete *technology stack* that includes midPoint.
Just take midPoint, LDAP server, access management product and some other bits and pieces and then you can go on and sell complete solution.

* You can provide *professional services* for midPoint deployers and users.

* You can offer a *managed service* solution that includes midPoint, you can offer *IDM-in-a-box*, you can offer midPoint *extended* with custom plug-ins and connectors and so on ...

The possibilities are countless.
You do *not* need any licence or support to do any of the above.
If you need help, assistance or bugfixes we will gladly provide support and consulting services.
We can even arrange a special support service that will partially cover your modifications.
But that is not mandatory.
If you do not need the support you are free to use midPoint - for free.
Just please let us know about your project so we can be proud about our product.


== Maintainer

The role of Evolveum is quite different than the role of traditional software vendors.
Although vast majority of the code in midPoint was created by our developers we do *not* act as an owner of the code.
We rather see ourselves as *maintainer* of the code.
We welcome any kind of contribution, any kind of cooperation.
Although we supply most of the manpower for midPoint development our primary and most important role is to *coordinate the development*. We want to make sure that the individual pieces of code that come to midPoint make sense and that they can work together.
We want to make sure that the long-term architectural vision is maintained.
We want to make sure that midPoint works and is successful.
But we will not turn down any good idea or contribution.
No matter whether it came from our internal development team, from our partner or from an independent developer that just found a bug and created a one-line fix.
We appreciate all contributions.


== How To Contribute

See wiki:Participation[Participation] page for all the details.
There are many ways how to contribute to the project including documentation updates, localizations and even bugfixes and code changes.
We are using distributed source code management (wiki:Git[Git]) therefore you can participate in midPoint even without any explicit permissions in our systems, accounts, etc.
You can learn more on wiki:Development+Participation[Development Participation] page.


== See Also

* wiki:Participation[Participation]

* wiki:Development+Participation[Development Participation]

* wiki:Git[Git]

