= MidPoint Studio

MidPoint studio is an integrated development environment (IDE) to develop solutions based on midPoint.
The primary purpose of MidPoint Studio is to support process of creating, developing and maintaining midPoint configurations.
However, there may be other advanced features in the futures, such as visualizations, configuration wizards and so on.
The Studio is developed in the same iterative way as midPoint.
It will be improved and extended as needed (and as the funding allows).

MidPoint Studio is built on top of open source https://www.jetbrains.com/opensource/idea/[IntelliJ platform] that is the foundation of IntelliJ IDEA, a well-known IDE for Java developers.
While https://www.jetbrains.com/idea/[IntelliJ IDEA] has a commercial  _Ultimate Edition_ (which we recommend), there is also an open source _Community Edition_ of the IDE, that is built on an open source platform.
MidPoint Studio is a plug-in for IntelliJ platform that will work both in the _Community_ and _Ultimate_ editions of IntelliJ IDEA.

== Current Status

MidPoint Studio plugin is currently in alpha stage.
The first beta release is planned soon.

Please see Studio https://github.com/Evolveum/midpoint-studio/blob/master/README.adoc[README file] for the details.

== Getting MidPoint Studio

As the Studio is in the alpha stage, it is available as a _nightly build_ only.

. Download and install https://www.jetbrains.com/idea/[IntelliJ IDEA].
Both _Community_ and _Ultimate_ editions will work.

. Start IntelliJ IDEA

. Go to menu `File` → `Settings (Preferences)` → `Plugins` → `Manage plugin repositories`

. Add repository `https://plugins.jetbrains.com/plugins/Nightly/list`

. Search for `MidPoint Studio` and click on `Install`


== Source Code and Contributions

MidPoint Studion is licensed under the terms of Apache License. Source code is available at GitHub:

https://github.com/Evolveum/midpoint-studio

The community is more than welcome to submit contributions using the usual _pull request_ mechanism.
For contributions, please follow the https://wiki.evolveum.com/display/midPoint/Code+Contribution+Guidelines[code contribution guidelines].
