= Working with midPoint Projects

== Creating midPoint Project

. Start IntelliJ IDEA.
. Go to *File → New → Project...*
. Select *MidPoint* in the left panel
. Set the *Master password* for your encrypted properties store (`Keepass`).
* The master password will be used for encryption of `Keepass` database
* The master password will be stored in your operating system key management subsystem so that you don't not need to enter it each time you start IntelliJ IDEA
* *TODO*: more about this below, link it
. Select a proper *Environment*
* By default there is a `Default` environment for `http://localhost:8080/midpoint`
* You can modify or add new environments for your projects now or later
* *TODO*: link proper section from here
. click *Next*
. Specify *Project name* and *Project location*

IntelliJ IDEA will automatically open your new project.

NOTE: The plugin stores the project configuration under `.idea` project
subdirectory and several files in the main project directory.

TODO not all files must be mentioned here. Select only those which make sense to view or edit.

.The list of files in the project directory
[cols="1,1", options="header"]
|===
^|File
^|Content
|credentials.kdbx
|TODO
|.gitignore
|`.gitignore` file for the main project
|.idea/compiler.xml
|TODO
|.idea/.gitignore
|`.gitignore` file for the plugin configuration within project
|.idea/jarRepositories.xml
|TODO
|./idea/libraries
|TODO
|./idea/midpoint.xml
|TODO
|./idea/misc.xml
|TODO
|./idea/modules.xml
|TODO
|./idea/workspace.xml
|TODO
|objects
|midPoint project object files
|pom.xml
|TODO
|scratches
|TODO
|`ProjectName`.iml
|TODO
|===

== Using IntelliJ IDEA Interface

TODO panels

This section describes the default configuration of the plugin in IntelliJ
IDEA.
It is possible to move and reorder the panels as you like.

`Top left panel`:
* *Project*: contains the list of files in your project. Everything related to
midPoint objects will be in the `objects/` subdirectory.

`Top right panel`:
* contains the currently opened midPoint object(s)

`Bottom left panel`:
* *Browse Objects*: allows searching within midPoint repository and creating bulk actions/tasks from the results. TODO link to chapter
* *Console*: displays midPoint plugin console
* *Credentials*: displays the content of the current Keepass database
** TODO explain the columns based on Viliam's improvements

NOTE: The `Key` column of your Keepass database entries corresponds to the key
name in your operating system's key database.

TODO screenshot?

== Working With Environments

You can create several environments for each project.
This can be used for example to allow connection to TEST, QA and PROD
environments of the same customer.
The environment `Default` is created automatically and points to `http://localhost:8080/midpoint`.
There is a color box specifying the color assigned to the environment for a quick overview of which environment are you currently working with.

NOTE: Unlike in the Eclipse plugin, the environments are now project-based.

=== Selecting Environment

There are several ways how to select a new environment to connect to:

* in the main toolbar, click the name of the current environment
* select the environment to switch to

or:

* in the main toolbar, click the name of the current environment
* select *Edit environments*
** select proper environment and click *Edit* icon
** check *Selected* checkbox
** click *Save* button

or:

* press `Shift` key twice to open the IntelliJ IDEA search window
* start to type `midpoint`
* select the row *MidPoint Settings* to open midPoint project settings
* the list of environments is displayed at the bottom of the page
** select proper environment and click *Edit* icon
** check *Selected* checkbox
** click *Save* button

=== Testing Connection to Environment

You can test the connection to your current environment by clicking the *Test* icon.
The result will be displayed in the *Event log* window and as a popup and will look like this:

====
21:26	Test connection: Connection test for 'Default' was successful. Version: 4.2-SNAPSHOT, build: v4.2devel-1670-g4643e042ec.
====

=== Adding A New Environment

To add a new environment:

* in the main toolbar, click the name of the current environment
* select *Edit environments*
* click *+* icon
* a new window will open, enter the following information:
** *Name*: your new environment name. E.g. `QA`
** *Selected*: check if you want to switch to the new environment
** *Server settings*: select the connection information:
*** *Url*
*** *Username*
*** *Password* TODO will be stored in your keepass database
*** *Ignore SSL Errors*: check to ignore any SSL-related connection errors such as a missing or self-signed certificate
** *Proxy settings*: enter your proxy server settings (optional)
** *Other*: enter the other settings (optional)
*** *Properties file*: select the properties file for this environment TODO link
*** *Color*: select the color for this environment
** click *Test connection* to test the connection to the new environment (optional)
** click *Save* button to save the new environment

=== Updating Existing Environment

* in the main toolbar, click the name of the current environment
* select *Edit environments*
* select the environment to edit
* click *Edit* icon
* modify the desired parameters
* click *Save* button to save the modified environment

=== Deleting Existing Environment

TODO not working properly 28.9.2020

* in the main toolbar, click the name of the current environment
* select *Edit environments*
* select the environment to edit
* click *Delete* icon
* click *Save* button to save the modified environment


== Working with midPoint Objects

You can do the following operations to the midPoint objects.
The actions are available either from the main toolbar or from the context menu *Update Object Actions* for the currently opened file or for selected files in your list of objects.

=== Uploading midPoint objects

This operation will send the selected object to midPoint repository and optionally execute an after-upload action.

The following operations are available either from the main toolbar or from the *Update object actions* context menu:

* *Upload/Execute*: will upload the selected object(s). Tasks may be automatically executed (based on their `executionState`).
* *Upload/Execute (stop on error)*: will upload the selected object(s). Tasks may be automatically executed (based on their `executionState`). The first object with an upload error will stop the action.
* *Upload/Recompute*: will upload the selected object(s) and recompute them after upload.
* *Upload/Test Resource*: will upload the selected object(s) and assuming they are resources, it will also test the connections.

NOTE: Rule of thumb: you typically want to use *Upload/Test Resource* for your resources and *Upload/Execute* for most other cases.

=== Refresh From Server

This operation will re-download the selected object from midPoint repository and overwrite the file.
You can execute this operation for the current window by clicking the *Refresh From Server* toolbar icon, or for file(s) in the list of files by clicking the context menu and selecting *Update object actions → Refresh From Server*.

NOTE: The local file will be overwritten. All XML comments will be lost.

=== Delete (Non-raw)

TODO is this correct?

This operation will delete the selected object(s) from midPoint repository.
Provisioning will be executed to delete also the object's projections, if applicable.
You can execute this operation for the current window by clicking the *Delete (non-raw)* toolbar icon, or for file(s) in the list of files by clicking the context menu and selecting *Update object actions → Delete (non-raw)*.

=== Delete (Raw)

This operation will delete the selected object(s) from midPoint repository with the `raw` flag.
No provisioning will be executed.
You can execute this operation for the current window by clicking the *Delete (raw)* toolbar icon, or for file(s) in the list of files by clicking the context menu and selecting *Update object actions → Delete (raw)*.


=== Bulk Action Generator

TODO

== Working With Object Editor

TODO oid generator
TODO syntax highlighing (mixed xml+groovy)
TODO element completion

== Environment or Project-Specific Properties

Similar to Eclipse plugin, you can use "macro expansions" to avoid hard-coded
properties in your source files.
This allows to have the same source files and use them in multiple
environments where you have different hostnames, ports etc.
The property name can be any string. TODO TODO space??? old plugin cannot use
spaces.
It is references by using `$(propertyName)`.

TODO old plugin supports `$(@filename)`, `$(#project.name)`, `$(#project.dir)`,
`$(#server.displayName)` properties

.Macro expansion example
[source,xml]
----
<resource>
   ...
   <connectorConfiguration>
      <icfc:configurationProperties xmlns:icfcldap="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/com.evolveum.polygon.connector-ldap/com.evolveum.polygon.connector.ldap.LdapConnector">
         <icfcldap:port>$(ldapPort)</icfcldap:port>
         <icfcldap:host>$(ldapHost)</icfcldap:host>
         <icfcldap:baseContext>$(ldapBaseContext)</icfcldap:baseContext>
         <icfcldap:bindDn>$(ldapAdmin)</icfcldap:bindDn>
         <icfcldap:bindPassword>
            <t:clearValue>$(ldapPassword)</t:clearValue>
         </icfcldap:bindPassword>
         <icfcldap:pagingStrategy>auto</icfcldap:pagingStrategy>
         <icfcldap:vlvSortAttribute>entryUUID</icfcldap:vlvSortAttribute>
         <icfcldap:operationalAttributes>ds-pwp-account-disabled</icfcldap:operationalAttributes>
         <icfcldap:operationalAttributes>isMemberOf</icfcldap:operationalAttributes>
      </icfc:configurationProperties>
  ...
</resource>
----

In the above example, the following properties are used:

* `ldapHost`
* `ldapPort`
* `ldapBaseContext`
* `ldapAdmin`
* `ldapPassword`

In Eclipse, there was a possibility to use a `properties` file which would
store the properties and their values.
The possibilities in IntelliJ IDEA are expanded.
You can use standard properties file, or keepass file, or both.

=== Using Properties File

You can use the properties files which are either environment-specific or project-specific.
It all depends on which property file is used in your specific environment configuration.

Properties file is more convenient for storing non-sensitive properties as the
properties file is not encrypted.
The properties file can be edited as an ordinary text file.
The format is very simple:

.Properties file example
----
[source]
ldapHost=server.example.com
ldapPort=389
ldapBaseContext=dc=example,dc=com
...
----

TODO spaces?
TODO comments?
TODO check double `=` in the DNs

NOTE: You can even use dots in properties names, e.g. `ldap.static.port`.

=== Using Keepass File

TODO True? The keepass file is used for all environments for the project.

This option is more convenient for storing sensitive properties such as
passwords.
The properties and their values are stored in an encrypted file (`keepass`
format).
This file is created when you create your project `credentials.kdbx`) when you have specified your master password.
The master password is *not* stored anywhere in IntelliJ IDEA nor the project;
it is rather stored in your operating system keystore database.
You can also access the encrypted file using `Keepass` program.

TODO example `ldapPassword` storage/usage from the above example

NOTE: The `credentials.kdbx` file is ignored from versioning using the project's `.gitignore` file. As it is encrypted, you might want to keep it under version control and share the password between your project team members using other channels.

NOTE: If you refer to a property which is stored both in the keepass file and
standard properties file, the keepass file takes priority.
