= Clustering demo
:page-wiki-name: Clustering demo
:page-wiki-id: 27820263
:page-wiki-metadata-create-user: lskublik
:page-wiki-metadata-create-date: 2019-02-25T10:02:21.793+01:00
:page-wiki-metadata-modify-user: lskublik
:page-wiki-metadata-modify-date: 2019-03-08T11:11:19.904+01:00
:page-upkeep-status: orange

This demo shows how to run two midPoint nodes working against common midPoint repository.
For more information you see link:https://wiki.evolveum.com/pages/viewpage.action?pageId=11075783[Clustering / high availability setup].

The image can be found in the link:https://github.com/Evolveum/midpoint-docker[Evolveum/midpoint-docker] GitHub project.

== Starting

[source,bash]
----
$ cd demo/clustering
$ docker-compose up
----

After docker-compose up command you will see more error logs from _midpoint_server_node_a_1 _or_ midpoint_server_node_b_1. Please you ignore errors, two Midpoint will try to inicialize same repository. You should see this errors only during first starting of the demo._

When docker-compose up command successfully finishes you should see something like this on the console:

[source]
----
midpoint_server_node_b_1  | 2019-02-25 10:15:36,855 [] [main] INFO (org.springframework.boot.web.embedded.tomcat.TomcatWebServer): Tomcat started on port(s): 8080 (http) with context path '/midpoint'
midpoint_server_node_b_1  | 2019-02-25 10:15:36,879 [] [main] INFO (com.evolveum.midpoint.web.boot.MidPointSpringApplication): Started MidPointSpringApplication in 85.847 seconds (JVM running for 87.726)
midpoint_server_node_a_1  | 2019-02-25 10:15:37,140 [] [main] INFO (org.springframework.boot.web.embedded.tomcat.TomcatWebServer): Tomcat started on port(s): 8080 (http) with context path '/midpoint'
midpoint_server_node_a_1  | 2019-02-25 10:15:37,160 [] [main] INFO (com.evolveum.midpoint.web.boot.MidPointSpringApplication): Started MidPointSpringApplication in 82.624 seconds (JVM running for 85.748)
----


Now you can log into midPoint using link:http://localhost:8080/midpoint[http://localhost:8080/midpoint] URL for node A and link:http://localhost:8081/midpoint[http://localhost:8081/midpoint] URL for node B, with an user of `administrator` and a password of `5ecr3t`.

You can safely ignore console messages like this:

[source]
----
clustering_midpoint_data_1  | ERROR:  could not serialize access due to read/write dependencies among transactions
clustering_midpoint_data_1  | DETAIL:  Reason code: Canceled on identification as a pivot, during write.
clustering_midpoint_data_1  | HINT:  The transaction might succeed if retried.
----


This is a part of standard midPoint conflict resolution process.
The mentioned transactions are really retried and they succeed eventually.


== Containers

The `demo/clustering` composition contains the following containers:


[%autowidth]
|===
| Container name | Description

| `midpoint_server_node_a_1  `
| This is the standard container providing midPoint functionality.
It contains standalone Tomcat running midPoint application node A.


| `midpoint_server_node_b_1  `
| This is the standard container providing midPoint functionality.
It contains standalone Tomcat running midPoint application node B.


| `clustering_midpoint_data_1`
| This container hosts midPoint repository; this time it is implemented on PostgreSQL 9.5 database.


|===


== Communication

The containers publish the following TCP ports.
(_Port mapped to localhost_ denotes the mapping of container port to the host port where it can be reached from the outside.)

[%autowidth]
|===
| Container | Port number | Port mapped to localhost | Description

| `clustering_midpoint_server_node_a_1  `
| 8080
| 8080
| HTTP port to be used to connect to midPoint application

| `clustering_midpoint_server_node_b_1  `
| 8080
| 8081
| HTTP port to be used to connect to midPoint application

| `clustering_midpoint_data_1`
| 5432
| 5432
| Port used to connect to the PostgreSQL database

|===


== Docker volumes

The following volumes are created to persist data and other relevant files.


[%autowidth]
|===
| Volume name | Description | Used by container

| `clustering_midpoint_home_node_a`
| The midPoint node A home directory.
Contains schema extensions, logs, custom libraries, custom ConnId connectors, and so on.
| `clustering_midpoint_home_node_a`

| `clustering_midpoint_home_node_b`
| The midPoint node B home directory.
Contains schema extensions, logs, custom libraries, custom ConnId connectors, and so on.
| `clustering_midpoint_home_node_b`

| `clustering_midpoint_data`
| Volume hosting PostgreSQL database used by midPoint.
| `clustering_midpoint_data`

|===


== Configuring the composition

The following configuration properties are supported.
Please refer to the xref:/midpoint/install/docker/dockerized-midpoint/#configuring-specific-container-features[main documentation page] for their explanation.


[%autowidth]
|===
| Property | Default value

| `REPO_DATABASE_TYPE`
| `postgresql`


| `REPO_JDBC_URL`
| `default`


| `REPO_HOST`
| `midpoint_data`


| `REPO_PORT`
| `default`


| `REPO_DATABASE`
| `midpoint`


| `REPO_USER`
| `midpoint`


| `REPO_PASSWORD_FILE`
| `/run/secrets/mp_database_password.txt`


| ``REPO_MISSING_SCHEMA_ACTION``
| `create`


| `REPO_UPGRADEABLE_SCHEMA_ACTION`
| `stop`


| `REPO_SCHEMA_VERSION_IF_MISSING`
|


| `REPO_SCHEMA_VARIANT`
|


| `MP_MEM_MAX`
| `2048m`


| `MP_MEM_INIT`
| `1024m`


| `MP_JAVA_OPTS`
| `-Dmidpoint.nodeId=NodeA  -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=20001 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.password.file=/run/secrets/jmxremote.password -Dcom.sun.management.jmxremote.access.file=/run/secrets/jmxremote.access -Dmidpoint.taskManager.clustered=true`


| `MP_KEYSTORE_PASSWORD_FILE`
| `/run/secrets/mp_keystore_password.txt`


| ``TIMEZONE``
| `UTC`


|===


Node B have only one properties diferent _-Dmidpoint.nodeId=NodeB_. You can tailor these to your needs.

The following Docker secrets are used:


[%autowidth]
|===
| Secret | Location

| `mp_database_password.txt`
| `configs-and-secrets/midpoint/application/database_password.txt`


| `mp_keystore_password.txt`
| `configs-and-secrets/midpoint/application/keystore_password.txt`


|===

You can modify or replace these files as needed.