= Installing MidPoint Using Docker Image
:page-nav-title: Using Docker Image
:page-wiki-name: MidPoint Easy Install
:page-wiki-id: 24675944
:page-wiki-metadata-create-user: ksuchanovsky
:page-wiki-metadata-create-date: 2017-11-23T15:56:38.155+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-09-08T15:29:13.027+02:00
:page-display-order: 40
:page-upkeep-status: orange
:page-upkeep-note: Restruct this to a real installation guide. Put docker details somewhere else.
:page-visibility: hidden

{% for v in site.data.midpoint-versions %}{% if v.status == null or v.status == "released" %}{% assign lastReleased = v %}{% endif %}{% endfor %}

You can deploy midPoint in Linux environment. All you need is to have installed Docker.

== Prerequisites

[TIP]
====
If you already have installed docker just continue to the section GUIDE
====

** Install Docker for your operating system. Please follow the instructions at official Docker Docs page: https://docs.docker.com/engine/installation/

== Guide

[TIP]
====
To run midPoint in Docker container please follow these 2 simple steps:
====

. Create container:

** Open your console and execute command below.
This command will create container from downloaded midPoint image and run that container.
If your docker does not contain a midpoint image yet, command will look for it on DockerHub and download it.
+
[source]
----
docker run -d -p 8080:8080 --name midpoint evolveum/midpoint:latest
----

** You can also delete midPoint container and create it again but please note that this will erase your configuration in midPoint.
For deleting midPoint container run command below (You have to stop container before removing it or use -f option for force removing):
+
[source]
----
docker rm midpoint
----
+
If it is not necessary do not remove midPoint container.

. Start and Stop container
+
Once you have your container created use start and stop commands for starting and stopping it.

** Start not running container:
+
[source]
----
docker start midpoint
----

** Stop running container:
+
[source]
----
docker stop midpoint
----
+
Stop command will save your configuration until you remove midPoint container.

** To enter the midPoint container bash use:
+
[source]
----
docker exec -it midpoint bash
----

== See Also

* xref:dockerized-midpoint.adoc[]