= Role Wizard User Stories
:page-nav-title: Role wizard user stories
:sectnums:
:sectnumlevels: 3

The main business reason for role wizard is to provide user interface to business users for self-service the role engineering where possible and enable cooperation with IGA administrators.

== Audience and usage

The role wizard should be used as standard interface for creation and management of roles (business roles or application roles). It should be used by business users, technical IT staff and by IGA administrators.

Business roles should be defined/modified mainly by business users - e.g. business managers/project managers or such positions - who manage people and their access.
The content of these roles can be easily explained in business language.

The application roles are more technical.
These roles should be defined by technical staff - e.g. application engineers with greater support of IGA administrators.


=== Role wizard

The role wizard should be used for *creation of new roles*, but the same screens should be used also for *modification of existing roles*.

The main difference is that while creation of new role the wizard navigates user step-by-step over the panels, and while modification, the user just select panel (tile) with the configuration part.

The role wizard must balance complexity of role definition options provided by midpoint with ease to use by expected audience.
If the interface is too complicated for business users, the wizard can omit specific elements that are not often used.
IGA administrator (or even the user) should have option to switch to advanced (our standard) interface for performing such modification.

Viewing and editing of existing role should be performed also using the wizard panels.
The existing screen with tiles (configure governance/configure members/go to role) that is displayed at the end of this wizard can be such starting point.
User can start on such screen with tiles and select option he needs to modify.

As an example, following tiles should be displayed:

* Role basics - attributes (maybe also owner here, approval policies)
* Access definitions - inducements
* Members
* Advanced role view - should display existing role user interface

The role wizard should be used in process of role engineering defined in guide.
// TODO - move role engineering process to docs.

== User-stories: Self-service, no approvals

In this set of user stories, there are no approvals defined for role engineering. Anybody with sufficient access rights can create/modify/delete roles.

=== Create new business role

User story::
AS a business user +
I WANT TO create new business role and set access to multiple applications there +
SO THAT I can start assigning this role for people in my organization (project) instantly.

Acceptance criteria::
GIVEN defined application roles that are needed for accessing applications, +
WHEN the business user creates the role in wizard (fills in basic details and configures access), +
THEN the role is created and the business user can start assigning the role to the users.

=== Create new business role and assign members

User story::
AS a business user +
I WANT TO create new business role, set access to multiple applications and assign the role to my users +
SO THAT the users get the access instantly.

Acceptance criteria::
. MidPoint provides interface for creation of business role
. Business role can be saved in draft state for later finalization
. When saved to production, the business role is created and applied to all its predefined members.

NOTE: This one-step configuration and also assignment of the role may be confusing users, as they may mix process for role creation and assignment, and they will be creating new roles instead of just assigning existing ones. But for smaller environments without approvals it may be ok.

=== Assign different types of inducements to business role

User story::
AS a business user or IGA administrator +
I WANT TO add different types of roles or even services with relations to the business role
SO THAT the business role can contain another business roles, or IT roles or any other type or role.

Acceptance criteria::
. Role wizard allows inducing any archetype of role into business role.
. Role wizard allows inducing services with default or specific relations into the business role.
    * The relations should be defined if the service allows it.
    * Each object can have different relation, so the relation is selected only after the application is selected
. As relations are quite complicated and not well understood by end-users, the relations should be displayed only when explicitly allowed by engineer. Not by default.

=== Cooperation of multiple users in role engineering
Definition of new role is seldom just work of one person. Midpoint should provide interface for cooperation of multiple users in preparing the role. The process is often iterative, as not all details are known each time.

User story::
AS an IGA administrator, +
I WANT TO review role prepared by business user and modify it when needed, +
SO THAT the role can be safely implemented.

Acceptance criteria::
. Midpoint should provide interface where multiple users can perform modification of role definition prior role is being applied to production life
. Midpoint should provide option for users to add notes what to be done in the role definition
. Midpoint should provide track of who and when modified which component of the role

=== Review of impact
Role assignments and inducements can be complex and modifications of the role definition can affect multiple users.
It is important if user knows what will be affected by the changes.

We need to display the changes according the knowledge of the audience. Business user can't read detail technical description as IGA administrator

User story::
AS a business user who created or modified role, +
I WANT TO know what will be affected by my changes of the role (e.g. when I added new app role to the business role), +
SO THAT I will know who will get more access and understand business impact of the change.

User story::
AS a IGA administrator who perform/review modification of a role, +
I WANT TO see all changes that will be induced by application of the change to the environment
SO THAT I can understand the technical impact of the change.

Acceptance criteria::
. Midpoint provides interface (simulation) for IGA administrator to review impact of role creation/modification
. Midpoint provides interface for business user to review business impact of the role creation/modification (who will get new access, where will be the access removed)

=== Create a copy of role

Roles are often similar. Especially application roles. It would be much easier if author of the application role could use copy-and-modify attitude while creating new role.

User story::
AS a business user or IT engineer who wants to create new role +
I WANT TO create a copy of existing role when I'm creating a similar role (e.g. multiple application roles for an application), +
SO THAT I don't need to perform full configuration of the role. This can save time and avoid errors.

Acceptance criteria::
. Midpoint allows creation copy of the role in "Draft" so the new role can be modified and created.
. New role is created without copying members.


=== Approval policy selection
Setting approver for role is complex. It is often not only 1 person. Existing user interface, where just approvers are selected is not useful for setting such approval policies by business users.

User story::
AS a business user creating a new role +
I WANT TO just select approval policy from predefined list, +
SO THAT I don't have to learn how to select multiple approvers.

User story::
AS a IGA engineer +
I WANT TO prepare set of approval policies (e.g.: 1, 2, 3-step approval), +
SO THAT I minimize possibility of errors while defining approvers by business users.

Acceptance criteria::
. Instead of just selecting approver midPoint enables selection of approval policy object from predefined approval policies.
. Midpoint should be delivered with some set of predefined default approval policies in initial objects.
. Midpoint can define also approval policy automatically while saving of the object - based on some attribute values (e.g. role risk level)

=== Application role: Define new group object in role wizard

Actual role wizard allows selection from existing resource entitlements (e.g. LDAP groups).
These groups must exist already while creating roles.
MidPoint can also create the group objects on resources, just wizard should allow this.
This increases application deployment speed if new group does not have to be created prior role definition.

User story::
AS an application engineer preparing new roles for my new application controlling access via LDAP groups, +
I WANT TO define new LDAP group name when granting entitlements in role wizard, +
SO THAT I don't have to request creation of the LDAP group by LDAP team.

Acceptance criteria::
. The application role wizard should allow definition of new resource object name while granting entitlements
. The new resource object should be created only when the role is switched to production


=== Application role: Access to multiple applications

Although it is not the pattern we would recommend, an application role can provide access to multiple applications.
E.g. read access to some internal applications can be provided via _internal_apps_ AD group.
Role wizard should support creation of application role accessing multiple applications.

It is easy - just allowing multiple inducements in the role wizard.

User story::
AS an application engineer preparing new application role, +
I WANT TO define application role that manages access to multiple applications, +
SO THAT I can define the application access the way how to it should be.

Acceptance criteria::
. Application role wizard should allow multiple inducements in the role wizard.
    * It would be better if there is some checkbox "manage access to multiple applications" provided and only then you can select more apps.

== Modification of roles
Midpoint should provide option also for controlled modification of the role.
The role being modified can be still in production and its members may change automatically.
The role modification may be instant (e.g. change of the description), or may take some time.

If the modification is not instant, midPoint should provide graphical information of what is being modified and identification of the role that is being modified.
Midpoint should provide option to graphically display what is being modified prior it is applied.

The modification should be performed via the same interface as new role creation.


== User-stories: Controlled self-service, approvals

In many environments, approvals by specific users are required when roles are created or modified.

=== Create new business role (with approval)

User story::
AS a business user +
I WANT TO create new business role and set access to multiple applications there +
SO THAT I start assigning this role for people in my organization (project) when the role is approved.

Acceptance criteria::
GIVEN defined application roles that are needed for accessing applications +
WHEN the business user creates the role in wizard (fill in basic details and configure access), sends the new role for approval and the creation of the role is approved, +
THEN the business user obtains notification of new role being created and can start assigning the role to his users.

=== Create new business role and assign members (with approval)

User story::
AS a business user +
I WANT TO create new business role, set access to multiple applications and assign the role to my users +
SO THAT the users get the access instantly when the role is approved.

Acceptance criteria::
GIVEN defined application roles that are needed for accessing applications, +
WHEN the business user creates the role in wizard (fills in basic details, configures access and configures members), sends the new role for approval and the creation of the role is approved, +
THEN the business user obtains notification of new role being created, and the access for assigned users is active since the role was approved.

NOTE: As written above, this one-step configuration and also assignment of the role may be confusing users, as they may mix process for role creation and assignment.

=== Rejection of request - business user

User story::
AS a business user who created role and sent it to approval +
I WANT TO *NOT* create new role when my request is rejected because of some errors, +
SO THAT I can just correct the errors and send the role for approval again.

=== Rejection of request - Approver

User story::
AS an approver of role creation, +
I WANT TO be able to approve the role, return the role back to requester to correct some details, or fully reject the role request creation (may be done in 2 steps) +
SO THAT I can handle the role creation request correctly.

== Additional user-stories: Visibility

=== See all roles to approve
User story::
AS a IGA administrator or Role manager +
I WANT TO see all roles that are in DRAFT (or similar state) +
SO THAT I can clearly see which roles have to be approved.

Acceptance criteria::
. MidPoint should provide specific view where IGA administrator can see all roles in DRAFT (or similar state).
. MidPoint should provide action buttons in that view that allows controlled and consistent operations over the objects in the view.

=== See all inactive roles
User story::
AS a IGA administrator +
I WANT TO see all roles that are invalidated (e.g. lifecycleState in (deprecated, archived, failed))+
SO THAT I can perform cleanup of old roles.

Acceptance criteria::
. MidPoint should provide specific view where IGA administrator can see all roles defined lifecycleState.
. MidPoint should provide action buttons in that view that allows controlled and consistent operations over the objects in the view.


== OPEN QUESTIONS

=== Assignment policies

We should handle somehow definition of autoassignment policies in GUI. Are users able to define such policies ? Are users able to read such policies ?
At least IGA admin should be able to do it via user interface.

Easy to use/easy to see policies can be defined by inducing the business role to the ORG. This would be easily readable and can be manageable by end users.
Can we include it in user interface ? Wouldn't it be too complicated ? Is "included in" panel enough ?

=== Easier selection of role owner

Creation of role owner is quite complicated now. For many users the owner is just attribute value.
Additionally - sometimes we would like to have "manager of the OU" be owner of the business role. The wizard should hadle this somehow.

=== Remove assign manager

For Roles - assignment of manager doesn't make sense.

=== Management of governance users

Management of governance users should not be asynchronous. We are managing small number of objects in this page. Asynchronous updates of page here is confusing.

=== Consistent design of selection of related objects

We should have same design for selecting related objects. We have multiple different patterns in one wizard:

. Application selection - tiles - just tile with applicationname is selected
. Governance - when empty
    * Assign manager/Owner/Approver - tiles - selection from list of users - assynchronous
. Governance - when anything filled in
    * Button "Assign users" - additional tile for selection of manager/owner/approver - and then selection from list - assynchronous.
. Configure members - Assign users button - selection from list of users in modal window
. Configure provisioning - resources - selection from list of resources - but not in modal window
. Configure provisioning - grant entitlements - selection from list of entitlements - not in modal window (but it could be the same as selection of members - and there is modal window there)

=== Application role: Name of the group instead of shadow OID

Some role definitions are part of project design and their configuration is stored in GIT.
When role is stored in GIT and relates to specific object, the association *should not* be created using shadowRef with OID like this:

----
<association>
    <ref>ri:group</ref>
    <outbound>
        <strength>strong</strength>
        <expression>
            <value xsi:type="c:ShadowAssociationType">
                <shadowRef oid="fb7a61ee-382e-44a3-bef2-a1e78b6cf39b" type="c:ShadowType"/>
            </value>
        </expression>
    </outbound>
</association>
----

Such group can't be moved between environments easily.

The question is, whether we should change configuration of the role generated by role wizard, or we should provide some notes for engineers.