= Kubernetes environment
:page-nav-title: Kubernetes
:toc:
:toclevels: 4
:page-visibility: hidden

[NOTE]
The yaml samples are available also on the link:https://github.com/Evolveum/midpoint-kubernetes/tree/master/base-environment[Github].
There are available also commands how to use the files with *kubectl* in readme.adoc file.

== What is it about

This page (or subtree of the documentation) will describe environment related to the clouds.
As there may be differences in configuration per specific environment, we will focus here on kubernetes.
The information is applicable for cloud environments in general but small configuration changes based on specific cloud environment might be required.

== Docker Images

As we are working in cloud environment the image is the most important part of the solution ( next to the configuration ).
All used images are available on public link:https://hub.docker.com/[Docker hub]:

* link:https://hub.docker.com/r/evolveum/midpoint[Midpoint] +
When we talk about the midpoint located in the cloud, the image of midpoint is a mandatory requirement.
* link:https://hub.docker.com/_/postgres[Postgres] +
The documentation will be mainly focused on native repository, which has postgres DB as a requirement, so we mention this image here.

The information related to the docker image mentioned in other parts of the documentation is also valid for our purposes.

== The structure of the information

* xref:/midpoint/install/kubernetes/single-node.adoc[Single node] deployment +
Deployment of single node midpoint where cluster specific settings are not handled.

* xref:/midpoint/install/kubernetes/cluster.adoc[Midpoint cluster] deployment +
Deployment in the cluster - how to handle cooperation between the nodes.

* xref:/midpoint/install/kubernetes/about.adoc[Used kubernetes objects] +
More common information about the used objects with the link to kubernetes documentation.

* xref:/midpoint/install/kubernetes/advanced-examples.adoc[Advanced examples] +
Specific midpoint configuration use cases and how to handle it in the kubernetes.

== References

* Evolveum docs links
** xref:/midpoint/install/docker/native-demo.adoc[Native repository demo]
** xref:/midpoint/install/midpoint-sh.adoc[Start script]
* External links
** link:https://kubernetes.io/docs/home/[Kubernetes documentation]