---
layout: connector-page
display-order: 300
functionality-status: stable
development-status: dormant
support-status: supportable
origin: ConnId
support-provided-by: Evolveum
target-systems: UNIX/Linux systems
connector-protocol: SSH
source-url-master: https://github.com/Tirasa/ConnIdUNIXBundle
description: Identity connector for UNIX/Linux systems based on SSH.
upkeep-status: orange
---
= UNIX Connector

== Versions

[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | Description

| 1.0
| Tirasa/Evolveum
| link:https://nexus.evolveum.com/nexus/repository/releases/org/connid/bundles/org.connid.bundles.unix/1.0/org.connid.bundles.unix-1.0.jar[download jar]
| link:https://github.com/Evolveum/ConnIdUNIXBundle[Evolveum git repository (fork)]
| Oct 21 2018 
| Stable version

| 1.1
| Tirasa/Evolveum
| link:https://nexus.evolveum.com/nexus/repository/releases/org/connid/bundles/org.connid.bundles.unix/1.1/org.connid.bundles.unix-1.1.jar[download jar]
| link:https://github.com/Evolveum/ConnIdUNIXBundle[Evolveum git repository (fork)]
| Nov 18 2021
| Stable version

| 1.1.1
| Tirasa/Evolveum
| link:https://nexus.evolveum.com/nexus/repository/releases/org/connid/bundles/org.connid.bundles.unix/1.1.1/org.connid.bundles.unix-1.1.1.jar[download jar]
| link:https://github.com/Evolveum/ConnIdUNIXBundle[Evolveum git repository (fork)]
| Nov 18 2021
| Patch/Stable version

|===

== Notes

In case of an non root user, where shell commands are prompted via the sudo password, make sure the PATH variables for commands located in "sbin" are also present for non-interactive sessions.
For this you might need to set the “Path” variable in the ssh "environment" file (might need to be created) in “~/.ssh/environment” or “/etc/ssh”. 
Also the “PermitUserEnvironment” parameter has to be set to true in “sshd_config”. For this please see “man sshd_config”.


== Resource Sample
xref:/connectors/resources/unix/[Unix Connector Samples]
