= ENISA Indispensable baseline security requirements for the procurement of secure ICT products and services
:page-nav-title: ENISA baseline security requirements
:page-upkeep-status: yellow
:page-toc: top

WARNING: Work in progress!

link:https://www.enisa.europa.eu/publications/indispensable-baseline-security-requirements-for-the-procurement-of-secure-ict-products-and-services[ENISA Indispensable baseline security requirements for the procurement of secure ICT products and services] is practical, technologically neutral document with clear, simple and sector-agnostic minimum necessary indispensable requirements for secure ICT products and services.
Any ICT product or service that *fails to be compliant* with one or more of the minimum security requirements *should be considered as insecure*, and therefore it should not be purchased or put in operation on the European digital single market.
It focuses on a few indispensable conditions, commonly agreed  among experts and based on standards and best practices.

ENISA baseline requirements are based on generally accepted principles for secure software development, such as glossref:secure-by-design[_secure by design_], glossref:secure-by-default[_secure by default_] and glossref:least-privilege[_least privilege_].

// TODO: it is not product certification, more like a self-assessment for software producers and service providers.

== MidPoint Compliance

*MidPoint is fully compliant* with ENISA indispensable baseline security requirements for the procurement of secure ICT products and services.
Following sections provide explanation and describe specific mechanisms.

=== Security by Design

MidPoint is a leading glossref:iga[identity governance and administration (IGA)] platform.
As such, midPoint is a foundation stone for cybersecurity practices in almost every organization.
Therefore, midPoint supports cybersecurity mechanisms of other applications, systems and services.

Naturally, midPoint itself is designed with security in mind since the very beginning.
xref:/midpoint/architecture/[MidPoint architecture] divides the system to subsystems and components with clearly defined responsibilities.
The architecture is reflected in midPoint xref:/midpoint/devel/source/[source code].

Following features demonstrate adherence to _security by design_ principle:

* feature:flexible-authentication[*Flexible authentication*] mechanism can be used to set up complex authentication schemes for access to midPoint, including multi-factor authentication.
Moreover, its primary purpose is to set up authentication schemes for special situations, such as registraion and password reset scenarios.

* feature:authorization[*Authorization* mechanism] can be used to control access to data and functionality on a very fine-grained level, using authorization statements that are naturally integrated with feature:rbac[role-based access control (RBAC)] framework.
Authorization framework is also used to support feature:delegated-administration[delegated administration] scenarios, allowing implementation of glossref:least-privilege[least privilege principle].

* feature:rbac[Role-based access control (RBAC)] framework is integrated deeply in the very fabric of midPoint code and data structures.
RBAC framework formed a foundation of midPoint code from its very beginning.
RBAC and its principles are supporting many midPoint functionalities, including advanced features.

* feature:policy-rule[Policy rules] can be used to enforce high-level governance policies over midPoint data and other low-level policies (such as feature:rbac[RBAC]), such as policies for feature:sod[segregation of duties] or feature:information-classification[information classification].

* feature:expression-profile[*Expression profiles*] can be used to limit the flexibility of expression languages, limiting them to secure operations.

* feature:audit-trail[Auditing] mechanisms record all operations in midPoint, including all actions of midPoint administrators and all configuration changes.
Audit trail data are stored in open, structured and documented format, available for integration with other system (such as SIEM).
Historic and provenance information are also recorded in feature:assignment-metadata[meta-data].

While midPoint is a comprehensive and very flexible platform, individual features can be activated or deactivated using feature:authorization[authorization mechanism], thus reducing the functionality to necessary minimum.

=== Least Privilege

glossref:least-privilege[Least privilege principle] is at the very core of midPoint, both internally as an application and externally, as an glossref:iga[identity governance and administration (IGA)] platform.

feature:authorization[*Authorization* mechanism] can be used to control access to data and functionality on a very fine-grained level, which allows to grant users access to the very minimal set of data and functionalities.
Authorization statements are naturally integrated with feature:rbac[role-based access control (RBAC)] framework, allowing design of roles that perfectly match responsibilities of every user.
Authorization framework, together with RBAC is used to support feature:delegated-administration[delegated administration] scenarios.
Dynamic, feature:pdrbac[policy-based RBAC] is used to automatically assign and unassign roles based on the organizational assignment of the user, user attributes, responsibilities and other characteristics, automatically reducing user privileges when not needed.

feature:access-certification[Access certification] mechanism can be used to systematically review user privileges, reducing them as necessary.

MidPoint feature:admin-gui[administration user interface] can be used to manage user accounts, as well as roles and privileges.
This functionality is also provided by feature:rest-api[RESTful application programming interface (API)].
The functionality also includes feature:nhi[management of technical and service accounts].
MidPoint provides feature:password-management[password management] features with support for feature:password-policy[password policies].

=== Strong Authentication

feature:flexible-authentication[*Flexible authentication*] mechanism can be used to set up complex authentication schemes for access to midPoint, including multi-factor authentication.
As the name suggests, authentication schemes can be flexibly adjusted for various scenarios to fit specific needs of each individual organization.

Privileges of every individual user can be controlled using feature:authorization[authorization mechanism], which includes feature:service-concept[service accounts].
As long as service accounts are not explicitly authorized to access user interface, they will not be allowed interactive log-on.

=== Asset Protection

feature:authorization[Authorization mechanism] is used to control access to data stored in feature:identity-repository[midPoint repository] on a very fine-grained level.
Authorizations are enforced independently on several levels, bound to midPoint xref:/midpoint/architecture/[architecture] and component structure.

feature:password-management[Passwords] are stored in midPoint in hashed or encrypted forms only.
Unique cryptographic key is generated for every deployment at the first start of the system.
Standard cryptographic libraries of Java platform are used for cryptographic operations.

=== Supply Chain Security

MidPoint is distributed from https://evolveum.com/download/[Evolveum web site], protected by standard HTTPS mechanism, providing transfer protection as well as assurance of origin.

MidPoint distribution files are signed using standard Java platform method (JAR signing).
Authenticity of the files is checked at the start of the system.

Moreover, complete xref:/midpoint/devel/source/[source code] of midPoint is publicly available, published on reputable platform (link:https://github.com/Evolveum/midpoint[github]), which can be used for independent checks of the code, as well as build artifacts.

=== Documentation Transparency

Complete documentation of midPoint is publicly accessible on https://docs.evolveum.com/[docs.evolveum.com], Evolveum documentation site.
This includes xref:/midpoint/install/[installation documentation], xref:/midpoint/reference/[reference documentation], xref:/midpoint/architecture/[architectural documentation], xref:/midpoint/devel/[developer documentation], even a publicly accessible xref:/book/[book] about use of midPoint.

The documentation is updated for each release of midPoint.
link:https://github.com/Evolveum/docs[Source code of midPoint documentation] is available too, providing access to full documentation change history.

Moreover, complete xref:/midpoint/devel/source/[source code] of midPoint is publicly available under an open source license, allowing unlimited access to knowledge about internal workings of midPoint.

=== Quality Management

Security of midPoint code is regularly monitored, including monitoring of security and vulnerability of midPoint dependencies (libraries and components used by midPoint).
This process is partially automated.
Regular upgrade and update of dependencies is a native part of midPoint development process.
MidPoint has well-established development and https://docs.evolveum.com/support/[support] mechanism, including public xref:/midpoint/roadmap/[roadmap] and predictable xref:/support/long-term-support/[schedule of releases] with matching support programs.
xref:/midpoint/security/advisories/[Security advisories] are published whenever security issue is discovered.
New maintenance version of midPoint is released when necessary.

Dedicated xref:/midpoint/security/security-guide/[security guide] is publicly available, describing security properties of midPoint. MidPoint was subject of several penetration tests and security scans, results of which were incorporated into midPoint development.
MidPoint was part of https://joinup.ec.europa.eu/collection/eu-fossa-2/about[European Union Free and Open Source Software Auditing (EU-FOSSA2) project].

=== Service Continuity

MidPoint has well-established development and https://docs.evolveum.com/support/[support] mechanism, including public xref:/midpoint/roadmap/[roadmap] and predictable xref:/support/long-term-support/[schedule of releases] with matching support programs.
Support lifetime of each release is xref:/midpoint/release/[clearly stated] for each release.
Maintenance versions are released as necessary, especially as a reaction to xref:/midpoint/security/advisories/[security issues].
Fixes for security issues are prioritized, and are immediately made available for all midPoint users regardless of their support program.
Responsible disclosure practices are documented in xref:/midpoint/security/security-guide/[midPoint security guide].


=== EU Jurisdiction

MidPoint is developed completely in European Union.
MidPoint development, distribution, support and all related activities are completely guided by EU law.

=== Data Usage Restriction

MidPoint is an on-premise software product.
All data stored in midPoint are maintained within the system, unless midPoint is explicitly configured by the operator to do otherwise.
MidPoint is not collecting or forwarding any data, except those channels that are explicitly configured by operator.

== Applicability

This description applies to midPoint 4.9 and later versions.

== See Also

* xref:../[MidPoint compliance overview]

* link:https://www.enisa.europa.eu/publications/indispensable-baseline-security-requirements-for-the-procurement-of-secure-ict-products-and-services[ENISA Indispensable baseline security requirements for the procurement of secure ICT products and services] (full text)
