---
layout: connector-page
display-order: 100
functionality-status: experimental
development-status: active
support-status: experimental
origin: Evolveum
support-provided-by: Evolveum
target-systems: Asynchronous message receivers
connector-protocol:
source-url-master: https://github.com/Evolveum/midpoint/tree/master/provisioning/ucf-impl-builtin/src/main/java/com/evolveum/midpoint/provisioning/ucf/impl/builtin/async/provisioning
description: Built-in identity connector for asynchronous (message-based) provisioning operations.
connid-bundle-name: com.evolveum.midpoint.provisioning.ucf.impl.builtin.async.provisioning
documentation-link: https://docs.evolveum.com/midpoint/reference/resources/asynchronous/outbound/
bundling: builtin
nav-title: Asynchronous Provisioning Connector
upkeep-status: orange
---
= Asynchronous Provisioning Connector (Built-In)

Asynchronous Provisioning Connector is a midPoint-specific built-in connector that implements provisioning operations mediated by an asynchronous (usually message-based) communication.
There are situations where a target resource is not accessible in a direct, synchronous, CRUD-like way. Such a resource can receive commands to add, modify, or delete accounts and other objects, but processes them asynchronously - in an unspecified time.

This connector implements the _outbound_ (provisioning) communication direction.
The xref:AsyncUpdateConnector/[Asynchronous Update Connector] implements the _inbound_ (synchronization) direction.

== See Also

* xref:/midpoint/reference/resources/asynchronous/outbound/[]

* xref:AsyncUpdateConnector/[]
