---
layout: connector-page
display-order: 200
functionality-status: stable
development-status: dormant
support-status: supportable
origin: Evolveum
support-provided-by: Evolveum
target-systems: SAP R/3
connector-protocol: SAP RFC
source-url-master: https://github.com/Evolveum/connector-sap
description: Identity connector for SAP R/3 systems.
connid-bundle-name: com.evolveum.polygon.connector-sap
upkeep-status: yellow
---
= SAP Connector
:page-wiki-name: SAP Connector
:page-wiki-id: 22282644
:page-wiki-metadata-create-user: oscar
:page-wiki-metadata-create-date: 2016-02-23T07:07:18.890+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-09-10T11:31:34.451+02:00

Connector for SAP R3, based on https://help.sap.com/saphelp_nwpi711/helpdata/en/48/70792c872c1b5ae10000000a42189c/content.htm[SAP Java Connector].
SAP JCo is proprietary, you need SAP login to download it.
SAP Connector is Apache-licensed.

[TIP]
====
SAP connector uses BAPI functions to manage accounts in SAP.
It supports all importing parameter types and table parameter types except UCLASSSYS, EXTIDHEAD, EXTIDPART a SYSTEMS to https://www.sapdatasheet.org/abap/func/BAPI_USER_CREATE1.html[create] and https://www.sapdatasheet.org/abap/func/BAPI_USER_CHANGE.html[change] account attributes, lock, unlock the account and change its password.
You can assign/unassign SAP accounts to activity groups (SAP roles), to groups (USERGROUP) and profiles managed in SAP.
It also supports reading arbitrary SAP tables using BAPI function https://www.sapdatasheet.org/abap/func/RFC_GET_TABLE_ENTRIES.html[RFC_GET_TABLE_ENTRIES], for example reading SAP activity groups (roles) from AGR_DEFINE table or reading SAP user groups from USGRP table.
====


== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| Provisioning
| YES
|

| Live Synchronization
| YES
| liveSync doesn't find deleted accounts

| Password
| YES
|

| Activation
| YES
| status, validFrom, validTo, lockoutStatus

| Filtering changes
|
| currently limited

| Paging support
| YES
| Simple Paged Results

| Native attribute names
| YES
| Use ri:USERNAME instead of icfs:nameand of icfs:uid if _useUsernameAsNativeName_ is enabled

|===

=== Interoperability

Tested on SAP System (R07)  Netweaver 7 EHP 2 (aka 7.31)

=== Limitations

* no support for Central User Administration in SAP (CUA landscape),

* liveSync doesn't see deleted accounts - you need sometimes to run full recompute, or use only disabling users in SAP,

* at the first time (getLatestSyncToken) liveSync returns current time as SyncToken - you need to synchronize midPoint server time with SAP server time or use full recompute after the first liveSync,

* rename account is not supported in SAP.


== History

[%autowidth]
|===
| Version | Origin | Sources | Build Date | Description

| 1.0.0.0
| Evolveum
| https://github.com/Evolveum/connector-sap/tree/v1.0.0.0[GitHub]
| October 2016
| Official release


| 1.0.1.0
| Evolveum
| https://github.com/Evolveum/connector-sap/tree/v1.0.1.0[GitHub]
| June 2017
| Official release


| 1.1
| Evolveum
| https://github.com/Evolveum/connector-sap/tree/v1.1[GitHub]
| September 2019
| Upgrade to Java SAP Connector 3.0.19 +
Support for load balancing (contributed) +
Allow setting of expired initial password (contributed) +
Parameter-related improvements (contributed)

| 1.2
| community
| https://github.com/Evolveum/connector-sap/tree/v1.2[GitHub]
| October 2025
| Upgrade to SAP JCo 3.1.12 +
Customized error handling +
Activity groups options +
Minor fixes and improvements

| 1.2.1
| community
| https://github.com/Evolveum/connector-sap/tree/v1.2.1[GitHub]
| November 2025
| Destination provider concurrency fix

|===


== Documentation


=== Building with Maven

. download SAP connector source code from https://github.com/Evolveum/connector-sap[github]

. download https://websmp102.sap-ag.de/connectors[sapjco] (SAP credentials needed) and find sapjco3.jar for your hardware processor (tested with sapjco3-NTAMD64-3.0.13)

. put it to your local maven repository, for example: mvn install:install-file -Dfile="\{pathToJCo}\sapjco3.jar" -DgroupId=com.sap.conn.jco -DartifactId=sapjco -Dversion=3.0.13 -Dpackaging=jar

. build SAP connector with maven:  +
mvn clean install -Dmaven.test.skip=true

. find `connector-sap-*.jar` in /target folder

=== Installation


. download https://websmp102.sap-ag.de/connectors[sapjco] (SAP credentials needed) and find javadoc/installation.html

. install JCo in your operating system

. put sapjco3.jar to \{midPoint_home}/lib/ directory

. put connector-sap-*.jar to \{midPoint_home}/connid-connectors/ directory

. run/restart midPoint


=== Object classes

SAP connector by default support these object classes:

* AccountObjectClass (`pass:[__ACCOUNT__]`) - read, create, update, delete users in SAP

* CustomPROFILEObjectClass (PROFILE) - read profile names

* CustomACTIVITYGROUPObjectClass (ACTIVITYGROUP) - read activity groups (roles) and his parent

* CustomGROUPObjectClass (GROUP) - read user group names

* any other SAP tables to read, see _tables_ parameter


=== Config

Please see https://raw.githubusercontent.com/Evolveum/connector-sap/master/src/main/resources/com/evolveum/polygon/connector/sap/Messages.properties[help] in connector.SAP have many user parameters, see https://www.sapdatasheet.org/abap/func/BAPI_USER_CREATE.html[here]. There are several types of parameters: "Importing" and "Tables" are relevant.
Importing parameter types are structures, for example, ADDRESS has some other single value attributes in it, for example, FIRSTNAME. This is represented as "ADDRESS.FIRSTNAME" in midPoint.Table parameter types and its rows are represented over SAP connector as XML, for example, connector attribute ACTIVITYGROUPS contains the value:

[source]
----
<?xml version="1.0" encoding="UTF-8"?><item><AGR_NAME>/CCM/CATALOG_APPROVER</AGR_NAME><FROM_DAT>2016-03-07</FROM_DAT><TO_DAT>9999-12-31</TO_DAT><AGR_TEXT>Role for Content Approver</AGR_TEXT><ORG_FLAG></ORG_FLAG></item>
----

You can use also attribute ACTIVITYGROUPS.AGR_NAME having the content of "/CCM/CATALOG_APPROVER".

Other available attributes: PROFILES.BAPIPROF, GROUPS.USERGROUP.

Other table parameter types are supported only in an XML way.
You can use XmlMatchingRule to compare them.

To speed up reading user details you can set to config _tableParameterNames_ only table type parameters, what you need, for example, _ACTIVITYGROUPS_, or ignore all as <sap:tableParameterNames/>.

=== Reading any SAP table data

==== Specify ObjectClass with _tables_ configuration

Over BAPI function RFC_GET_TABLE_ENTRIES you can read any SAP table.
To access a table, you have to include the table in the `S_TABU_NAM/TABLE` permission.
Each table row will be converted to a single projection in an object class.
You need only define table name and its structure in _tables_ parameter as follows:

[source]
----
{table name in SAP} as {alias in object class}={first field name:length{:IGNORE|KEY}},{next field what you need...}
----

If you don't need an attribute, you can ignore it using "IGNORE".
To set what column will be mapped to icfs:uid and icfs:name, please use "KEY" word.
For example activity groups are by default defined as:

[source]
----
AGR_DEFINE as ACTIVITYGROUP=MANDT:3:IGNORE,AGR_NAME:30:KEY,PARENT_AGR:30
----

You could find fields names and lengths for example https://www.sapdatasheet.org/abap/tabl/AGR_DEFINE.html[here] (for ARG_DEFINE).

Data are returned by SAP as fixed width with no delimiter, so you must define all field names and their length in order to parse them correctly.

If you update _tableParameterNames_ or _tables_ connector parameters via midpoint Configuration -> Repository objects, please delete <schema> section before saving it in order to generate new schema.

==== Specify additional columns with _subTables_ configuration

If a single SAP table is missing information that you need, you can specify additional tables, that can be fetched from SAP for each projection.
The BAPI function RFC_GET_TABLE_ENTRIES is also used here, so you can specify any table you need.
The sub-tables are queried with the "KEY" of the root table.
To access a table, you have to include the table in the `S_TABU_NAM/TABLE` permission.

If you update the _subTables_ configuration via midpoint, please delete <schema> section before saving it in order to generate the new schema.

You can specify additional tables in the following format in the _subTables_ configuration.
Each config value represents one table, that is queried according to the root projection and added as new multi-value attribute:

[source]
----
{table name} for {root table name}[ format {XML|TSV}][ as {attribute name}]={{column name}:{column size}[("{filter value}")]:{IGNORE|MATCH|OUTPUT}},{more columns...}
----

The table definition part consists of:

* `{table name}`: name of the table in SAP (e.g. "AGR_TEXTS")
* `for {root table name}`: name of the table inside the _tables_ configuration (e.g. "AGR_DEFINE")
* optional `format XML`: default format that represents every selected column as individual XML tag
* optional `format TSV`: Tab-separated values (SAP usually doesn't use TAB characters, so the values won't be escaped)
* optional `as {attribute name}`: name of the attribute inside the ObjectClass (default: table name)

Each column definition consists of:

* `{column name}`: name of the SAP column to structure the output (e.g. "AGR_NAME")
* `{column size}`: size of the SAP column in characters
* optional `("{filter value}")`: filter the sub-table result by this exact value (e.g. `("00000")`)
* optional `OUTPUT`: default behavior that includes the column in the result
* optional `IGNORE`: don't include the column in the result
* optional `MATCH`: the value of this has to match with an identically named column of the root table; otherwise the row is filtered (and don't include the column in the result)

====
This is an example to load the short description of an ActivityGroup.
This selects the row with language "E" (english) and line number "00000" of AGR_TEXTS, selects the TEXT column and returns it as ConnId attribute "ShortDescription" (by SAP convention, the line 0 represents the short description of a role, all following lines combined are the long description):
[source]
----
AGR_TEXTS for AGR_DEFINE format TSV as ShortDescription=MANDT:3:IGNORE,AGR_NAME:30:MATCH,SPRAS:1("E"):IGNORE,LINE:5("00000"):IGNORE,TEXT:80
----
====

====
This is an example to load the names of all single roles, that are referenced by a composite role:
[source]
----
AGR_AGRS for AGR_DEFINE format TSV=MANDT:3:IGNORE,AGR_NAME:30:MATCH,CHILD_AGR:30,ATTRIBUTES:10:IGNORE
----
====

====
This is an example to load all role flags as XML (role flags include for example the value COLL_AGR="X" for composite roles):
[source]
----
AGR_FLAGS for AGR_DEFINE format XML=MANDT:3:IGNORE,AGR_NAME:30:MATCH,FLAG_TYPE:10,MISC:52:IGNORE,FLAG_VALUE:32
----
or more precise for the composite flag:
----
AGR_FLAGS for AGR_DEFINE format TSV as COLL_AGR=MANDT:3:IGNORE,AGR_NAME:30:MATCH,FLAG_TYPE:10("COLL_AGR"):IGNORE,MISC:52:IGNORE,FLAG_VALUE:32
----
====

=== SAP permissions

The following table contains all SAP permissions required for all use cases.
Detailed permissions for each Use Case are shown in Use Cases section.

[%autowidth]
|===
| Authorization Object | Field | Value

.3+| S_RFC
| ACTVT
| 16

| RFC_NAME
| BAPT, BFHV, DDIF_FIELDINFO_GET, RFC1, SDIFRUNTIME, SUSE, SUSO, SU_USER, SYST

| RFC_TYPE
| FUGR


.3+| S_RFC
| ACTVT
| 16

| RFC_NAME
| PASSWORD_FORMAL_CHECK

| RFC_TYPE
| FUNC

| S_TCODE
| TCD
| SU01


.2+| S_TABU_NAM
| ACTVT
| 03

| TABLE
| AGR_DEFINE, USGRP


.2+| S_USER_AGR
| ACTVT
| 02

| ACT_GROUP
| * (may be restricted to specific values)


.2+| S_USER_GRP
| ACTVT
| 01, 02, 03, 05, 06, 22, 78

| CLASS
| * (may be restricted to specific values)


.2+| S_USER_PRO
| ACTVT
| 22

| PROFILE
| * (may be restricted to specific values)

|===


=== Use Cases

The following table contains typical use cases, a list of related BAPI functions, and SAP permissions needed for these use cases.
See also _testBapiFunctionPermission_.

Column RFC Name contains the RFC_NAME which must be permitted in Authorization object S_RFC for RFC_TYPE FUGR (see table above)

[%autowidth]
|===
| Use cases | Functions | RFC Authorisation | Additional Authorisations

| test connection
| `JCoDestination.ping()`
| SYST
|


| search and list SAP accounts
| BAPI_USER_GETLIST

BAPI_USER_GET_DETAIL

| SU_USER
a|

[%autowidth]
!===
3+h! S_USER_GRP

h! Field
h! Value
h! Comment

! ACTVT
! 03
! Display

! CLASS
! *
!  may be restricted to specific value

!===


| create, update, delete account +
assign/unassign group
| BAPI_USER_CREATE1

BAPI_USER_CHANGE

BAPI_USER_DELETE

| SU_USER
a|

[%autowidth]
!===
3+h! S_USER_GRP

h! Field
h! Value
h! Comment

! ACTVT
! 01 +
02 +
05 +
06 +
78
! Create or generate +
Change +
Lock +
Delete +
Assign

! CLASS
! *
!  may be restricted to specific value

!===

| use transaction to create and update account +
when config _useTransaction_=true
| BAPI_TRANSACTION_COMMIT

BAPI_TRANSACTION_ROLLBACK
| BAPT
|

| lock/unlock account
| BAPI_USER_LOCK

BAPI_USER_UNLOCK
| SU_USER
a|

[%autowidth]
!===
3+h! S_USER_GRP

h! Field
h! Value
h! Comment

! ACTVT
! 05
! Lock

! CLASS
! *
!  may be restricted to specific value

!===

| assign/unassign activity groups
| BAPI_USER_ACTGROUPS_ASSIGN
| SU_USER
a|

[%autowidth]
!===
3+h! S_USER_GRP

h! Field
h! Value
h! Comment

! ACTVT
! 22
! Enter, Include, Assign

! CLASS
! *
!  may be restricted to specific value

!===

[%autowidth]
!===
3+h! S_USER_AGR

h! Field
h! Value
h! Comment

! ACTVT
! 02
! Change

! ACT_GROUP
! *
! May be  restricted to specific values

!===


| assign/unassign profiles
| BAPI_USER_PROFILES_ASSIGN
| SU_USER
a|

[%autowidth]
!===
3+h! S_USER_GRP

h! Field
h! Value
h! Comment

! ACTVT
! 22
! Enter, Include, Assign

! CLASS
! *
!  may be restricted to specific value

!===

[%autowidth]
!===
3+h! S_USER_PRO

h! Field
h! Value
h! Comment

! ACTVT
! 22
! Enter, Include, Assign

! PROFILE
! *
! May be  restricted to specific values

!===


| change password

when config _changePasswordAtNextLogon_=false

check password

| SUSR_USER_CHANGE_PASSWORD_RFC

SUSR_GENERATE_PASSWORD

SUSR_LOGIN_CHECK_RFC, PASSWORD_FORMAL_CHECK

| SUSO

SUSE

SDIFRUNTIME

DDIF_FIELDINFO_GET

a|
[%autowidth]
!===
3+h! S_RFC

h! Field
h! Value
h! Comment

! RFC_NAME
! PASSWORD_FORMAL_CHECK
!

! RFC_TYPE
! FUNC
!

!===


| read any SAP table, see config _tables_ (activity groups, user groups)
| RFC_GET_TABLE_ENTRIES
| RFC1
a|
[%autowidth]
!===
3+h! S_TABU_NAME

h! Field
h! Value
h! Comment

! ACTVT
! 03
! Display

! TABLE
! AGR_DEFINE +
USGRP +
*
! Activity groups +
User groups +
any table (to be restricted as required)

!===


| read profile
| BAPI_HELPVALUES_GET
| BFHV
a|

| read additional account login info: +
LAST_LOGON_DATE, LOCK_STATUS, PASSWORD_STATUS

when config sap.config.alsoReadLoginInfo=true

| SUSR_GET_ADMIN_USER_LOGIN_INFO
| SUSO
a|
[%autowidth]
!===
3+h! S_TCODE

h! Field
h! Value
h! Comment

! TCD
! SU01
! Display

!===

|===


== Resource Examples

Please see samples in https://github.com/Evolveum/midpoint-samples/tree/master/samples/resources/sap[Github].

https://github.com/Evolveum/midpoint-samples/tree/master/samples/resources/sap/sap-medium.xml[sap-medium.xml] contains a sample to create/read account in/from SAP with roles (activity groups) as RoleType.
To use it, please also import https://github.com/Evolveum/midpoint-samples/tree/master/samples/resources/sap/role-activity-group-metarole.xml[role-activity-group-metarole.xml], https://github.com/Evolveum/midpoint-samples/tree/master/samples/resources/sap/object-template-role.xml[object-template-role.xml] (SAP ActivityGroup metarole assignment mapping is enough), enable it and import roles from sap over https://github.com/Evolveum/midpoint-samples/tree/master/samples/resources/sap/task-import-activity-groups.xml[task-import-activity-groups.xml].

https://github.com/Evolveum/midpoint-samples/tree/master/samples/resources/sap/sap-advanced.xml[sap-advanced.xml]contains a sample to create/read the account in/from SAP with roles (activity groups) and also with profiles and groups as OrgType. In this sample uniqueness of names are solved with name prefixes 'r:' (role), 'p:' (profile) and 'g:' (group). Please import all files from the appropriate folder and run all import tasks.

In subdirectory assignment, you see a similar sample as in sap-advanced, but when you import account from SAP, you also import assigned SAP roles, profiles and groups to extension attributes what you see in extension-sap.xsd. From this new attributes over enabled object-template-org.xml is created assignment to appropirate OrgType (roles, profiles and groups).


== Using Encryption / SAP SNC

This Section is under "heavy" work in progress.

If you deploy the connector without SNC the communication between SAP and Midpoint is not encrypted.
To use a Secure High encrypted Connection you have to use SAP SNC.
Here is a short list what you have to do:

[source]
----
The tomcat must use same user as we create the pse file.pse file is generated as follows. to get the tools you have to downlaod them from SAP.

extract sapcrypto file on midpoint system under a common directory we use /staging/

[root@midpoint sapryptolib]# ls -ltr /staging/sapcryptolib
total 3876
-rwxrwxrwx 1 root root 2361998 Apr  7 16:11 libsapcrypto.so
-rwxrwxrwx 1 root root      26 Apr  7 16:11 sapcrypto.lst
-rwxrwxrwx 1 root root   20720 Apr  7 16:11 sapgenpse
drwxr-xr-x 2 root root    4096 Jul  6 11:23 sec
-rwxr-xr-x 1 root root 1436445 Jul 19 15:25 sapjco3.jar

generate the snc pse/certs for the user which you use to connect to the sap system

sapgenpse get_pse -p MIDPOINTSNC -x <PW> "<DN>"
sapgenpse seclogin -p MIDPOINTSNC -x <PW>

It´s important to execute the following command as the same user that runs Midpoint:

sapgenpse export_own_cert -o <filename> -p SAPSNCS -x <PW>

On your SAP System, export the own cert of the SAP System and import it into the PSE on the MIDPOINT Server.
You can do this via SAP GUI (Transaction STRUST) or like above:

sapgenpse export_own_cert -o <Filename> -p SAPSNCS -x <PW>

Import the MIDPOINT Cert into SAP and vice versa

sapgenpse maintain_pk -a <certfile> -x <PW>


Tomcat need to find the right libs , put this also in the startupscript of tomcat

export LD_LIBRARY_PATH=/staging/sapryptolib/:$LD_LIBRARY_PATH
export SNC_LIB=/staging/sapryptolib
export SECUDIR=/staging/sapryptolib/sec
----
