---
layout: connector-page
display-order: 500
functionality-status: unknown
development-status: community
support-status: community
origin: Openstandia
support-provided-by: Openstandia
target-systems: Keycloak
source-url-master: https://github.com/openstandia/connector-keycloak
description: Identity connector for Keycloak.
documentation-link: https://github.com/openstandia/connector-keycloak
upkeep-status: green
---
= Keycloak connector

This connector integrates midPoint with Keycloak through the Keycloak Admin REST API and uses OpenID Connect (OIDC) for authentication.

Each midPoint resource is associated with a specific Keycloak realm.
The configuration specifies the authentication realm and the realm containing the managed objects.

== Capabilities and features

[%autowidth,cols="h,1,1"]
|===
| Capability | Supported | Description

| Schema
| Yes
| Static, with the option to define additional attributes through the resource configuration.

| Test connection
| Yes
|

| Provisioning
| Yes
|

| Live synchronization
| No
|

| Password
| Yes
| Client secret handling is also supported.

| Activation
| Yes
|

| Paging support
| Yes
|

| Filtering
| Yes
| Exact matching by the `UID` or `Name` attributes.

| Script execution
| No
|

| Connector pooling
| Yes
|

|===

== Managed entities

|===
| Entity | Description

| Users
| Associations with client roles, realm roles, and groups are configured as subject-to-object simulated references.

| Clients
|

| Client roles
| The name combines the `clientUUID` and the role `name`, separated by `/`, to define the role's association with the client.

| Realm roles
|

| Groups
|

|===


== See also

* https://github.com/openstandia/connector-keycloak
