= Supported task types
:page-wiki-name: Supported task types
:page-wiki-id: 24676737
:page-wiki-metadata-create-user: mederly
:page-wiki-metadata-create-date: 2018-03-28T14:01:14.559+02:00
:page-wiki-metadata-modify-user: mederly
:page-wiki-metadata-modify-date: 2018-03-28T14:01:46.345+02:00

Currently the following task types are segmentable - and thus able to be distributed to multiple nodes as well as to be resumed at (approximate) point of suspension.


== All iterative tasks

Segmentation awareness is built into `AbstractSearchIterativeTaskHandler` thus the following tasks are segmentable out of the box:

. Importing accounts from resource

. Recomputation

. Iterative scripting

. Reindexing

. Executing changes

. Shadow integrity check

. Object integrity check

. Propagation and multi-propagation

(Note that the segmentation was not tested with all of them yet; for some of them it might not be useful at all.
The first three - namely import, recomputation and iterative scripting - were tested.)


== Reconciliation task

Although this is not traditional iterative task, it can be partitioned into three segments (operation completion, resource reconciliation, shadow reconciliation), out of which the second and the third can be meaningfully segmented.
Some examples are xref:/midpoint/devel/design/multi-node-partitioned-and-stateful-tasks/task-partitioning/[here].


== No-op (demo) task

This task does not do anything useful; but it was made segmentable just to illustrate this concept.
Please see the link:https://github.com/Evolveum/midpoint/blob/master/samples/tasks/multinode-task-1.xml[sample task].