= Workers management
:page-wiki-name: Workers management
:page-wiki-metadata-create-user: mederly
:page-wiki-metadata-create-date: 2018-03-20T14:57:11.435+01:00
:page-wiki-metadata-modify-user: mederly
:page-wiki-metadata-modify-date: 2018-03-20T14:58:28.047+01:00

In coordinator/workers setup one can create workers manually.
However, it is more convenient to have them created automatically, according to some definition.
The `WorkersCreationTaskHandler` does just that.
Here's a short description how to configure it.


== An example

[source,xml]
----
<task oid="0ce0ce48-ff0b-48db-aefe-a3adec0ed25b"
      xmlns="http://midpoint.evolveum.com/xml/ns/public/common/common-3"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:xsd="http://www.w3.org/2001/XMLSchema"
      xmlns:noop="http://midpoint.evolveum.com/xml/ns/public/task/noop/handler-3">
    <!-- Simulates importing 1000 accounts divided into 20 buckets. Processing of each account takes 1 second.
         Execution is carried out by 4 workers per node. -->
    <name>Multinode import simulation</name>
    <extension>
        <!-- 1 second per object -->
        <noop:delay xsi:type="xsd:int">1000</noop:delay>
        <noop:steps xsi:type="xsd:int">1</noop:steps>
    </extension>
    <ownerRef oid="00000000-0000-0000-0000-000000000002"/>
    <executionStatus>runnable</executionStatus>
    <category>Demo</category>
    <handlerUri>http://midpoint.evolveum.com/xml/ns/public/task/workers-creation/handler-3</handlerUri>
    <workManagement>
        <taskKind>coordinator</taskKind>
        <buckets>
            <numericSegmentation>
                <to>1000</to>
                <numberOfBuckets>20</numberOfBuckets>
            </numericSegmentation>
        </buckets>
        <workers>
            <handlerUri>http://midpoint.evolveum.com/xml/ns/public/task/noop/handler-3</handlerUri>
            <workersPerNode>
                <count>4</count>
            </workersPerNode>
        </workers>
    </workManagement>
    <recurrence>recurring</recurrence>
    <binding>loose</binding>
    <schedule>
        <interval>600</interval>
    </schedule>
</task>
----

The `workManagement` section defines here two important things:

. Segmentation of work into buckets:

.. We create 20 buckets, each having 50 items.
(So the first one is 0..49, then 50..99, 100..149, up to 950..999.)



. What workers are used to process the work:

.. There will be four workers on each cluster node.

.. Each worker will execute NoOpTaskHandler.
(It does nothing in particular; just iterates through fictitious objects.)




== Definition options

Here we describe `workers` configuration section.
(The `buckets` section is explained wiki:Multi-node,+partitioned+and+stateful+tasks[elsewhere].)

[%autowidth]
|===
| Item | Description 1+| Default value 

| taskName
| How to derive names for worker tasks.
It is possible to use substitution strings of `{coordinatorTaskName}`,` {node}` and `{index}` here.
In `coordinatorTaskName` there is the name of the coordinator task, `node` is the nodeidentifier and `index` numbers workers created for particular node, starting at 1.
1+| {coordinatorTaskName} ({node}:{index})


| handlerUri
| Worker tasks handler URI.
1+| Might be known from the context; otherwise there is no default and the URI has to be specified.


| otherDeltas
| Other deltas to be applied to newly created worker task.
1+| -


| workersPerNode
| Configuration of how many and what workers to be created for given cluster node(s).
1+| Single worker per node.


|===

Workers per node are configured using the following items:

[%autowidth]
|===
| Item | Description 1+| Default value 

| nodeIdentifier (multivalued)
| Node identifier(s) for which we are going to generate the tasks.
1+| All nodes currently defined in the repository.


| count
| How many workers to create for given node(s).
1+| 1


| taskName
| How to derive names for the tasks.
1+| taskName defined in the parent element


| executionGroup
| Execution group for created workers.
It is possible to use substitution strings here.
1+| `{node}` (i.e. the task will execute on the specified node only  assuming that the default setting for execution capabilities is present)


| otherDeltas
| Other deltas to be applied to newly created worker task in this group.
Applied in addition to the deltas defined in parent element.
1+| -


|===