= OIDC client authentication setup
:page-wiki-metadata-create-user: jkadera
:page-toc: top

This article describes Midpoint configuration, necessary to accept REST API requests (e.g. from a custom application) that are authenticated using OIDC client authentication.

NOTE: It is recommended visiting link:https://docs.evolveum.com/midpoint/reference/master/security/authentication/flexible-authentication/modules/oidc/[Module oidc documentation article] for detailed information about Midpoint OIDC configuration options and parameter specifics.

== Prerequisites

* Running instance of Midpoint
* Running instance of OIDC authentication server

== REST communication with Midpoint
REST requests has to contain WWW-Authentication header with syntax `Authorization: Bearer {token}`

Where `{token}` is obtained from OIDC authentication server and can be either a JWT token or an opaque token.

== Validating JWT in Midpoint
The following methods can be used:

* issuerUri
* JWKSetUri
* singleSymmetricKey
* public key with trustingAsymmetricCertificate
* public key with keyStoreTrustingAsymmetricKey

NOTE: The method of your choice has implications on how you configure both Midpoint and OIDC authentication server.

== Configure OIDC authentication server

Based on your choices regarding token type and validation method, you need to configure your OIDC authentication server accordingly.

=== Configure Midpoint Security settings

* In Midpoint, navigate to *Repository objects* / *All objects*.
* Locate and edit your *secutiry policy* xml file.
* Locate the `modules` element and as its child, insert a new module.
** Populate this new module with relevant values, desribed in link:https://docs.evolveum.com/midpoint/reference/master/security/authentication/flexible-authentication/modules/oidc/[Module oidc documentation article] 
** Note the identifier you used.

=== Point Midpoint REST API to the OIDC module

* Locate the `sequence` element containing child element `identifier` with the value `rest-default`.
* In this `sequence`, update the value of the `module` / `identifier` element to the identifier of the OIDC module you created in the previous step.
* Save your security policy

== Send a REST request to Midpoint

The following example assumes that:

* A token is:
** Obtained from OIDC authentication server (e.g. using OIDC library, curl, Postman, etc.)
** Stored in a variable called `TOKEN`.
* Midpoint is running on `http://localhost:8080/midpoint`.

And uses `/ws/rest/self` as an example Midpoint REST API endpoint.

[source,bash]
----
curl "http://localhost:8080/midpoint/ws/rest/self" -s\
    -H "Authorization: Bearer $TOKEN"\
    -H "Accept: application/json"
----