= DatabaseTable
:page-wiki-name: DatabaseTable
:page-wiki-id: 3145736
:page-wiki-metadata-create-user: vix
:page-wiki-metadata-create-date: 2011-09-23T15:38:16.602+02:00
:page-wiki-metadata-modify-user: mmacik
:page-wiki-metadata-modify-date: 2019-11-25T15:44:33.673+01:00
:page-toc: top
:page-upkeep-status: yellow

[%autowidth,cols="h,1"]
|===
| Status
| Provisioning works well. +
Synchronization works well.

| Recommended connector
| xref:../connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[]
|===

The xref:../connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable connector] can be used for any table in JDBC-supported database.
The following steps describe setup for MySQL database table.

== Resource Configuration

=== MySQL Installation

Standard MySQL installation is expected.


=== Example Table Definition

The database needs to be created and populated.
The following example is available in `samples/resources/databasetable/create-simple-idm-table.mysql`.

.SQL Simple Table Definition
[source,sql]
----
/*!40101 SET NAMES utf8 */; +
/*!40101 SET character_set_client = utf8 */;

CREATE DATABASE IF NOT EXISTS midpoint_tests CHARACTER SET utf8 COLLATE utf8_bin;

CREATE TABLE midpoint_tests.idrepo ( +
userId VARCHAR(16) NOT NULL, +
password VARCHAR(16) NOT NULL, +
firstName VARCHAR(16), +
lastName VARCHAR(16), +
fullName VARCHAR(32), +
PRIMARY KEY (userId) +
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

GRANT ALL PRIVILEGES on midpoint_tests.* TO midpoint_tests@'%' IDENTIFIED BY 'secret'; +
GRANT ALL PRIVILEGES on midpoint_tests.* TO midpoint_tests@localhost IDENTIFIED BY 'secret';
----

Sample resource can be imported from `samples/resources/databasetable/*.xml`.


== Connector Configuration

link:http://openicf.forgerock.org/connectors/databasetable/configuration.html[See DatabaseTable Connector documentation.] (currently, no published documentation).


=== JDBC Driver

The connector requires appropriate JDBC driver.
The driver needs to be available to the web server.
It usually has to be placed on on web server classpath.
E.g. this means copying the driver to `$TOMCAT_HOME/lib` directory if tomcat server is used and restarting the server.


=== Connector Configuration Example

[source,xml]
----
<c:connectorConfiguration>

    <!-- Configuration specific for the DBTable connector -->
    <icfc:configurationProperties
                        xmlns:icscdbtable="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/org.forgerock.openicf.connectors.databasetable-connector/org.identityconnectors.databasetable.DatabaseTableConnector">

        <icscdbtable:port>3306</icscdbtable:port>
        <icscdbtable:quoting></icscdbtable:quoting>
        <icscdbtable:host>localhost</icscdbtable:host>
        <icscdbtable:user>midpoint_tests</icscdbtable:user>
        <icscdbtable:password>
            <clearValue>secret</clearValue>
        </icscdbtable:password>
        <icscdbtable:database>midpoint_tests</icscdbtable:database>
        <icscdbtable:table>idrepo</icscdbtable:table>
        <icscdbtable:keyColumn>userId</icscdbtable:keyColumn>
        <icscdbtable:passwordColumn>password</icscdbtable:passwordColumn>
        <icscdbtable:jdbcDriver>com.mysql.jdbc.Driver</icscdbtable:jdbcDriver>
        <icscdbtable:jdbcUrlTemplate>jdbc:mysql://%h:%p/%d</icscdbtable:jdbcUrlTemplate>
        <icscdbtable:enableEmptyString>false</icscdbtable:enableEmptyString>
        <icscdbtable:rethrowAllSQLExceptions>true</icscdbtable:rethrowAllSQLExceptions>
        <icscdbtable:nativeTimestamps>false</icscdbtable:nativeTimestamps>
        <icscdbtable:allNative>false</icscdbtable:allNative>
        <icscdbtable:changeLogColumn></icscdbtable:changeLogColumn>
        <icscdbtable:datasource></icscdbtable:datasource>
    </icfc:configurationProperties>
</c:connectorConfiguration>

----


=== Configuration with Datasource

To avoid using JDBC connection properties such as host, port, username, password and database name, you can also use datasource.

To wiki:Repository+Configuration#RepositoryConfiguration-Datasourceconfiguration[configure datasource in Tomcat], you can use the step 1 as when configuring midPoint repository (modification of server.xml and context.xml).

After Tomcat restart, change your resource configurationProperties (`jdbc/testds1` is used as an example datasource):

[source,xml]
----
. . .
<c:connectorConfiguration>

    <!-- Configuration specific for the DBTable connector -->
    <icfc:configurationProperties
                        xmlns:icscdbtable="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/org.forgerock.openicf.connectors.databasetable-connector/org.identityconnectors.databasetable.DatabaseTableConnector">
        <icscdbtable:table>idrepo</icscdbtable:table>
        <icscdbtable:keyColumn>userId</icscdbtable:keyColumn>
        <icscdbtable:passwordColumn>password</icscdbtable:passwordColumn>
        <icscdbtable:jdbcDriver>com.mysql.jdbc.Driver</icscdbtable:jdbcDriver>
        <icscdbtable:jdbcUrlTemplate>jdbc:mysql://%h:%p/%d?useUnicode=true&amp;characterEncoding=utf8&amp;connectionCollation=utf8_bin</icscdbtable:jdbcUrlTemplate>
        <icscdbtable:enableEmptyString>false</icscdbtable:enableEmptyString>
        <icscdbtable:rethrowAllSQLExceptions>true</icscdbtable:rethrowAllSQLExceptions>
        <icscdbtable:nativeTimestamps>false</icscdbtable:nativeTimestamps>
        <icscdbtable:allNative>false</icscdbtable:allNative>
        <icscdbtable:changeLogColumn></icscdbtable:changeLogColumn>
        <icscdbtable:datasource>java:comp/env/jdbc/testds1</icscdbtable:datasource>
    </icfc:configurationProperties>
</c:connectorConfiguration>
. . .
----

=== Exception Handling Configuration

Midpoint needs some of the exceptions produced by the connector to react to some of the situations which can emerge while executing operations on the target resource. For example if we have some kind of conflict in a unique constraint, i.e. creating a user with duplicate unique ID, the connector has to translate this exception to a form understandable by midpoint. There are two properties which can be used for this action,
the first one 'alreadyExistMessages' where you are capable to specify the concrete message which is a part of an SQL exception describing a conflict in a unique constraint. Additionally there is an option to react to the sqlState codes produced by the resource. These codes are used as a standard and for most of the resources the interpretation will be successful. The sqlState option is by default turned off and exception handling via sql messages is used. 

The 'SQLStateExceptionHandling' property is present in the databasetable connector version 1.4.8.1 and higher. 

See below example with both the 'alreadyExistMessages' and 'SQLStateExceptionHandling' properties.


[source,xml]
----
. . .
    <connectorConfiguration>
        <icfc:configurationProperties xmlns:gen121="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/com.evolveum.polygon.connector-databasetable/org.identityconnectors.databasetable.DatabaseTableConnector">
            <gen121:alreadyExistMessages>duplicate key value violates unique constraint, already exists</gen121:alreadyExistMessages>
            <gen121:SQLStateExceptionHandling>false</gen121:SQLStateExceptionHandling>
            <gen121:host>localhost</gen121:host>
            <gen121:port>5433</gen121:port>
            <gen121:user>midpoint_tests</gen121:user>
            <gen121:password>
				 <clearValue>secret</clearValue>
            </gen121:password>
            <gen121:database>midpoint_tests</gen121:database>
            <gen121:table>accounts</gen121:table>
            <gen121:keyColumn>ACCOUNTID</gen121:keyColumn>
            <gen121:passwordColumn>PASSWORD</gen121:passwordColumn>
            <gen121:jdbcDriver>org.postgresql.jdbc.Driver</gen121:jdbcDriver>
            <gen121:jdbcUrlTemplate>jdbc:postgresql://%h:%p/%d</gen121:jdbcUrlTemplate>
        </icfc:configurationProperties>
    </connectorConfiguration>
. . .
----

=== Resource Sample

See resource samples in link:https://github.com/Evolveum/midpoint-samples/tree/master/samples/resources/databasetable[Git samples directory for DBTable connector (master)].