= Flexible Authentication Improvements
:page-wiki-name: Flexible Authentication Improvements
:page-planned: true
:page-upkeep-status: orange
:page-upkeep-note: Reflect recent development, maybe mention OIDC?

== Motivation

Since midPoint 4.1 there is wiki:Flexible+Authentication[Flexible Authentication] mechanism.
This was a huge step forward.
But there are still some missing pieces.


== Requirements

What we need:

* Support for OpenID Connect protocol (interactive login, e.g. GUI).

* Support for OpenID Connect protocol (non-interactive, e.g. REST).

* Authentication that can take advantage of account linking.
MidPoint knows that Active Directory account "foo" actually belongs to user X12345.
Therefore the user can log in with his Active Directory account foo, but midPoint will display self service for user X12345.

* Make sure that the old password provided in self-service password reset is checked on the particular resource where authentication is delegated.

* Authentication module chaining improvements, e.g. better support for module `necessity` setting.

* (Optional) There is an authentication function in ConnId connectors.
This function might be used.
This will avoid duplication of connectors and authentication modules.
E.g. Active Directory connector may take care of both identity management and authentication.
The same configuration can be reused.


=== Multi-Factor Authentication Credential Management

Note that that is not strictly a matter of _authentication_  mechanisms, as we will not be using those credentials to authenticate users.
This is all a question of credential management.
But for the lack of better place we are listing the requirements here.

* Native support for SSH keys

* Native support for X.509 certificates/keypairs

* Native support for other authentication types (HOTP, TOTP, FIDO, yubikeys,...)


== See Also

* wiki:Flexible+Authentication[Flexible Authentication]

