= Localization Improvements
:page-wiki-name: Localization Improvements
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2019-07-22T09:50:41.871+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-07-22T10:06:52.640+02:00
:page-planned: true
:page-upkeep-status: orange
:page-upkeep-note: Reflect recent development

== Motivation

As MidPoint was born in the Europe, it naturally supports localization.
Otherwise midPoint wouldn't be able to survive in the European melting pot of languages and cultures.
However, complete localization of any software package is a surprisingly complex task.

MidPoint versions 3.x and 4.0 are well suited for a single-language environments.
Which means you can choose any supported language that you want and midPoint will talk to you in that language.
But when it comes to supporting several languages at the same time, there are still limitations.
Those limitations are given by the localization of the _content_ of midPoint.

Localization of midPoint user interface is quite easy.
There are well-known and proved techniques, such as using localization catalogs.
This requires a huge amount of work to maintain the localizations - big thanks to all midPoint translators is in order here.
But otherwise this localization approach works like a charm.
The problem is a localization of data.
Firstly the data are created during deployment.
Therefore the translator cannot translate them as they simply do not know them.
Secondly, the data may be presented in many languages at once.
Which makes operations such as searching and sorting very difficult.


== Planed Improvements

MidPoint 4.0 have some mechanism to deal with data localization, such as wiki:PolyString[PolyString]. PolyString was part of midPoint design almost from the beginning.
The developers are based in Europe and speaks an obscure native language, therefore it is quite natural that the thoughts about localization played a part in midPoint design.
The PolyString was quite simple at the beginning and it got improved in midPoint 4.0. But there is still wiki:PolyString+Improvements[a long way to go].

But even if PolyString supports full localization, there is still a question how to store (or index) the data in the database.
There are wiki:PolyString+Design+Notes[some ideas], however those needs to be explored and prototyped to make sure that functionality and performance is acceptable.

== See Also

* wiki:PolyString[PolyString]

* wiki:PolyString+Improvements[PolyString Improvements]

* wiki:PolyString+Design+Notes[PolyString Design Notes]

* wiki:UX+Design+notes[UX Design notes]