= Script Expression Sandboxing
:page-wiki-name: Script Expression Sandboxing
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2019-03-11T15:02:21.149+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-04-08T16:42:26.766+02:00
:page-planned: true
:page-upkeep-status: orange
:page-upkeep-note: Java Security Manager is retired? Do we still want this?
:page-toc: top

== Introduction

Script expressions are a code that runs inside midPoint servers.
As such, script expressions are incredibly powerful.
But with great powers comes great responsibility.
Script expressions can do a lot of useful things, but they can also do a lot of harm.
There are just a few simple internal safeguards when it comes to expression evaluation.
E.g. midPoint script libraries will properly enforce authorization when executing the functions.
However, script languages are powerful and a clever expression can find a way around this safeguards.
MidPoint is *not* placing expressions in a sandbox, therefore expressions are free to do almost anything.


== Sandboxing

The sandbox is not enforced yet from complexity and performance reasons.
However we want to apply sandboxing or an equivalent strategy to limit the capabilities of script expressions.
Yet, this is not easy.
Sandbox privileges need to be chosen carefully and maintained.
And then, some expressions may need to do stronger things than others.
E.g. reporting expression should be tightly restricted, while scripting hooks should remain very powerful.
This is introducing additional complexity.


== Expression Profiles

This feature is a part of a much bigger feature set.
See wiki:Expression+Profiles:+Full+Implementation[Expression Profiles: Full Implementation] for more details.


== See Also

* bug:MID-5193[]

* wiki:Expression[Expression]

* wiki:Script+Expression[Script Expression]

* wiki:Expression+Profiles[Expression Profiles]

* wiki:Expression+Profiles:+Full+Implementation[Expression Profiles: Full Implementation]