= midPoint Accessibility Conformance Report (VPAT)
:page-nav-title: midPoint VPAT
:keywords: WCAG, VPAT, ACR

Evolveum Accessibility conformance report for WCAG 2.2 AA level for midPoint end-user interface in the form of VPAT report.

== Report Date

This report was last updated on 2026-02-17.

== Product

midPoint, version 4.10.1

=== Product Description

midPoint is an identity governance and administration (IGA) platform used to manage digital identities, their attributes and access rights across connected systems.
It provides web-based administrative and end-user self-service interfaces that support user lifecycle management, access requests, approvals and access governance workflows.

The scope of this VPAT and the WCAG 2.2 Level AA evaluation is limited to the end-user self-service interface in English and Czech languages.

=== Scope

This VPAT describes WCAG 2.2 Level AA conformance for the midPoint end-user self-service interface only.
The evaluation scope includes a defined set of self-service functions provided to end users, as identified in the table below.


[cols="25h,~"]
|===
|Self-service item |Definition

|Dashboard (Home)
a|Dashboard is a configurable object in midPoint that provides basic information about the state of the system and the user. +
The dashboard displays the most important data needed to present information about the user’s status as quickly as possible. +
This mainly includes information about the user’s access rights, requests, and other miscellaneous information whose relevance is determined by the client.
Dashboard elements can be presented in the form of tiles, tables, or widgets.

|Profile
|This section is used to manage basic user information in midPoint. +
It consists of various attributes whose values can be managed by the user, if permitted by internal policy. These attributes are typically provisioned automatically to the user’s assigned accounts in associated applications and systems. From this section, the user can manage access rights, view linked accounts, and review history information.

|Credential management
|This functionality is used to reset or change passwords for user accounts.

|Access request
|The functionality is used to request access on demand. +
The process is similar to shopping in an e-shop, where the user selects access items from a catalog, adds them to a basket, specifies the activation period, and submits the request for processing.

|Approval process
|The functionality extends processes such as access requests. Authorized users are able to review access requests and make approval or rejection decisions.

|Self-Registration
|Registration of new account.

|Log-in
|The log-in functionality supports two methods: authentication using a standard log-in form with a username and password, and authentication using OpenID Connect (OIDC) via an external identity provider.

|Post-authentication form
|This functionality allows users to provide required information after logging in for the first time.

|Reset password
|This functionality supports password recovery when a user forgets their password.

|Identity recovery
|The functionality supporting identification of a username based on correlation information provided by the user.

|===


== Feedback and Contact Information

We welcome your feedback on the accessibility of our services.
If you encounter any accessibility barriers or require more information, please contact us at compliance@evolveum.com .

We aim to respond to accessibility-related inquiries within 15 business days.

== Evaluation Methods Used

midPoint has undergone an initial accessibility evaluation using a combination of automated tools and manual testing techniques.
The evaluation focused on identifying major accessibility barriers and areas of non-conformance with WCAG 2.2 Level AA.
Manual testing included keyboard navigation checks, visual inspection, and limited assistive technology testing.
Accessibility improvements are ongoing.

== Applicable Standards/Guidelines

This report reflects outstanding issues found by techical review based on the level A and AA criteria of the
*Web Content Accessibility Guidelines version 2.2 (WCAG 2.2 AA)*.

=== Conformance level

Partially supports

=== Remarks and Explanations

The end-user self-service interface generally supports this success criteria.
However, some self-service functions currently exhibit accessibility limitations.
Remediation is in progress as part of our ongoing WCAG compliance improvements.

== Terms

* *Supports:* The functionality of the product has at least one method that meets the criterion without known defects or meets with equivalent facilitation.
* *Partially Supports:* Some functionality of the product does not meet the criterion.
* *Does Not Support:* The majority of product functionality does not meet the criterion.
* *Not Applicable:* The criterion is not relevant to the product.
* *Not Evaluated:* The product has not been evaluated against the criterion.


== WCAG 2.2. Report

=== Level A Success Criteria

[cols="20,10,20", options="header"]
|===
|Success Criteria |Conformance Level |Remarks and Explanations

|1.1.1 Non-text Content
|Partially Supports
a|
* Some images have incorrect alternative text
* Decorative images don’t have empty alt description

|1.2.1 Audio-only and Video-only (Prerecorded)
|Not Applicable
|

|1.2.2 Captions (Prerecorded)
|Not Applicable
|

|1.2.3 Audio Description or Media Alternative
|Not Applicable
|

|1.3.1 Info and Relationships
|Partially Supports
a|
* Incorrect announcement of navigation items

|1.3.2 Meaningful Sequence
|Supports
|

|1.3.3 Sensory Characteristics
|Supports
|

|1.4.1 Use of Color
|Supports
|

|1.4.2 Audio Control
|Not Applicable
|

|2.1.1 Keyboard
|Supports
|

|2.1.2 No Keyboard Trap
|Supports
|

|2.1.4 Character Key Shortcuts
|Supports
|

|2.2.1 Timing Adjustable
|Not Applicable
|

|2.2.2 Pause Stop Hide
|Supports
|

|2.3.1 Three Flashes or Below Threshold
|Supports
|

|2.4.1 Bypass Blocks
|Supports
|

|2.4.2 Page Titled
|Supports
|

|2.4.3 Focus Order
|Partially Supports
a|
* Some elements on the website have an incorrect focus order

|2.4.4 Link Purpose (In Context)
|Supports
|

|2.5.1 Pointer Gestures
|Not Applicable
|

|2.5.2 Pointer Cancellation
|Not Applicable
|

|2.5.3 Label in Name
|Supports
|

|2.5.4 Motion Actuation
|Not Applicable
|

|3.1.1 Language of Page
|Supports
|

|3.2.1 On Focus
|Supports
|

|3.2.2 On Input
|Supports
|

|3.2.6 Consistent Help
|Supports
|

|3.3.1 Error Identification
|Supports
|

|3.3.2 Labels or Instructions
|Supports
|

|3.3.7 Redundant Entry
|Supports
|

|4.1.2 Name Role Value
|Supports
|
|===

=== Level AA Success Criteria

[cols="20,10,20", options="header"]
|===
|Success Criteria |Conformance Level |Remarks and Explanations

|1.2.4 Captions (Live)
|Not Applicable
|

|1.2.5 Audio Description (Prerecorded)
|Not Applicable
|

|1.3.4 Orientation
|Supports
|

|1.3.5 Identify Input Purpose
|Supports
|

|1.4.3 Contrast (Minimum)
|Supports
|

|1.4.4 Resize text
|Supports
|

|1.4.5 Images of Text
|Supports
|

|1.4.10 Reflow
|Supports
|

|1.4.11 Non-text Contrast
|Supports
|

|1.4.12 Text-spacing
|Supports
|

|1.4.13 Content on Hover or Focus
|Supports
|

|2.4.5 Multiple Ways
|Supports
|

|2.4.6 Headings and Labels
|Partially Supports
a|
* Some labels are not sufficiently descriptive

|2.4.7 Focus Visible
|Supports
|

|2.4.11 Focus Not Obscured (Minimum)
|Supports
|

|2.5.7 Dragging Movements
|Not Applicable
|

|2.5.8 Target Size (Minimum)
|Supports
|

|3.1.2 Language of Parts
|Supports
|

|3.2.3 Consistent Navigation
|Supports
|

|3.2.4 Consistent Identification
|Supports
|

|3.3.3 Error Suggestion
|Supports
|

|3.3.4 Error Prevention (LFD)
|Supports
|

|3.3.8 Accessible Authentication (Minimum)
|Supports
|

|4.1.3 Status Messages
|Supports
|

|===