= Axiom Background

Axiom is a language originally designed to model data in midPoint project.
MidPoint was originally designed with XML and XML Schema Definition (XSD), however those mechanisms were never a perfect fit for project needs.
Finally in 2020 it was decided to replace XSD with a new data modeling language that would be a better fit.
First step was to use Axiom to represent meta-data schema (meta-schema) for data provenance purposes needed by MidPrivacy initiative.

Axiom was used to model _Prism_ data structures in midPoint.
Prism is a Java framework that can be used to maintain object-based data models.
Prism specifies basic properties of a data object, it defines data structures that describe object changes (_deltas_), it specifies query language for objects and so on.
Prism evolved in midPoint project where it was used as a basic data framework.

Axiom sytnax was heavily inspired by Statement concepts were inspired by link:https://tools.ietf.org/html/rfc7950[YANG modeling language].
Some of Axiom concepts were also inspired by YANG.

== Axiom in MidPoint

Axiom is data modeling language used to model data and metadata for Prism and midPrivacy project, with intention to replace XSD as go-to modeling language for Prism.

Axiom is designed with migration path from XSD to Axiom in mind, which is possible
thanks to common mapping of concepts via Prism.
Axiom maps more directly to Prism concepts and it is intended to be less verbose
than same model written in XSD.
