= Axiom Implementation Notes

== Namespace Resolution

Models are identified by using namespace.
That's what import statement specifies.
We need to get from the namespece (URI) to file that contains model definition.
There are two options:

* *Offline: catalog*: Use catalog file that maps namespace URIs to filenames.

* *Online: web resolution*: Use HTTP get on namespace to get model spec.
This needs to be a bit more complex as we need to specify model verion (or version range).

== Item Namespace resolution

In `Axiom`, `JSON`, `YAML` and `XML`, item names are serialized using prefixed
name syntax.

Prefixed name consists of optional prefix and localName.

1. If prefix is specified, namespace is namespace associated with specified prefix.

If prefix is not specified:

1. Search for non-augmentation item with same localName in current value type.
  a) If item exists, use qualified name of the item.
2. Search for item in current value type with namespace of enclosing value type.
   a) If item exists, use qualified name of the item.
   b) If item does not exists, repeat step 2, till root value is reached.
3. Search for item in current value type with document default namespace
   if specified.
4. If no item was found, fail namespace resolution.

// FIXME: Or do we want to guess in augmentation items? Possible to have inconsistent
// behaviour if two augmentations targeting same type uses same item local name.
