= Axiom Implementation Notes

== Namespace Resolution

Models are identified by using namespace.
That's what import statement specifies.
We need to get from the namespece (URI) to file that contains model definition.
There are two options:

* *Offline: catalog*: Use catalog file that maps namespace URIs to filenames.

* *Online: web resolution*: Use HTTP get on namespace to get model spec.
This needs to be a bit more complex as we need to specify model verion (or version range).

== Item Namespace resolution

In `Axiom`, `JSON`, `YAML` and `XML`, item names are serialized using prefixed
name syntax.

Prefixed name consists of optional prefix and localName.

1. If prefix is specified, namespace is namespace associated with specified prefix.

If prefix is not specified:

1. Search for non-augmentation item with same localName in current value type.
  a) If item exists, use qualified name of the item.
2. Search for item in current value type with namespace of enclosing value type.
   a) If item exists, use qualified name of the item.
   b) If item does not exists, repeat step 2, till root value is reached.
3. Search for item in current value type with document default namespace
   if specified.
4. If no item was found, fail namespace resolution.

// FIXME: Or do we want to guess in augmentation items? Possible to have inconsistent
// behaviour if two augmentations targeting same type uses same item local name.

== Metadata Authorizations

If no `scope` and no `item` is present, then scope of data=all,metadata=unspecified is assumed.
This is a short-cut to common case "allow access to all data".
It is also compatible with old midPoint versions.

If no `scope` is present, but there are ``item``s, then scope of data=enumerated,metadata=unspecified is assumed.
It is compatible with old midPoint versions.

If empty `scope` is present, then scope of data=unspecified,metadata=unspecified is assumed.

---

Allow read access to all data items and all metadata items:

[source,xml]
----
  <authorization>
    <action>http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#read</action>
    <scope>
        <data>
            <selection>all</selection>
        </data>
        <metadata>
            <selection>all</selection>
        </metadata>
    </scope>
  </authorization>
----

---

Allow read access to all data items, but no metadata items:

[source,xml]
----
  <authorization>
    <action>http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#read</action>
    <scope>
        <data>
            <selection>all</selection>
        </data>
        <metadata>
            <selection>unspecified</selection>
        </metadata>
    </scope>
  </authorization>
----

Shorter way to express the same thing:

[source,xml]
----
  <authorization>
    <action>http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#read</action>
    <scope>
        <data>
            <selection>all</selection>
        </data>
    </scope>
  </authorization>
----

Old way:

[source,xml]
----
  <authorization>
    <action>http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#read</action>
  </authorization>
----

---

Allow read access to provenance metadata in all items that the user can already read:

[source,xml]
----
  <authorization>
    <action>http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#read</action>
    <scope>
        <data>
            <selection>unspecified</selection>
        </data>
        <metadata>
            <selection>enumerated</selection> <!-- optional -->
            <item>provenance</item>
        </metadata>
    </scope>
  </authorization>
----

Or shorter:

[source,xml]
----
  <authorization>
    <action>http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#read</action>
    <scope>
        <metadata>
            <item>provenance</item>
        </metadata>
    </scope>
  </authorization>
----


---

Allow read access to metadata items, but give no access to any metadata

[source,xml]
----
  <authorization>
    <action>http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#read</action>
    <scope>
        <data>
            <item>name</item>
            <item>fullName</item>
        </data>
        <metadata>
            <selection>unspecified</selection>
        </metadata>
    </scope>
  </authorization>
----

Or the same thing shortened:

[source,xml]
----
  <authorization>
    <action>http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#read</action>
    <scope>
        <data>
            <item>name</item>
            <item>fullName</item>
        </data>
    </scope>
  </authorization>
----

Old way to specify it:

[source,xml]
----
  <authorization>
    <action>http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#read</action>
    <item>name</item>
    <item>fullName</item>
  </authorization>
----

---

Full specification, allow certain data items and certain metadata for them
(not supported in midPoint 4.2)

[source,xml]
----
  <authorization>
    <action>http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#read</action>
    <scope>
        <data>
            <selection>enumerated</selection> <!-- optional -->
            <item>name</item>
            <item>fullName</item>
        </data>
        <metadata>
            <selection>enumerated</selection> <!-- optional -->
            <item>provenance</item>
            <item>storage</item>
        </metadata>
    </scope>
  </authorization>
----
