= Axiom: Draft v0.1
:version: 0.1

WARNING: This is draft of feature, currently none of described functionality is available.
The language design and concepts are still subject to change.

Axiom is data modeling language used to model data and metadata for Prism and midPrivacy project, with intention to replace XSD as go-to modeling language for Prism.

This document describes the syntax and semantics of version {version} of Axiom language.
This document will also describe how a data model defined in Axiom model is
encoded in XML, JSON, YAML and Axiom language.

:toc:

== Introduction

Axiom is data modeling language used to model data and metadata for Prism and midPrivacy project, with intention to replace XSD as go-to modeling language for Prism.

Axiom is designed with migration path from XSD to Axiom in mind, which is possible
thanks to common mapping of concepts via Prism.
Axiom maps more directly to Prism concepts and it is intended to be less verbose
than same model written in XSD.

include::terminology.adoc[]

include::overview.adoc[]

include::semantics.adoc[]

include::syntax.adoc[]
