= Axiom Namespaces

How are namespaces used in Axiom?

TODO: what is a namespace (URI)

== Model Identification

Model namespace is a globally-unique identifier of a model.
Whenever a data file needs to specify the data model that was used to create it, namespace is used to identify that model.
Whenever a data model refers to a concepts of another model, namespace of the model is used.
Whenever there is may be an ambiguity about appropriate interpretation of an item, namespace is used to resolve the ambiguity by pointing to the correct model.

== Isolation of Models to Support Evolution

All data models evolve.
They change to implement new features, adapt to changes environment or fix mistakes of the past.
Axiom is designed to combine, reuse and extend data models.
Each model has its own namespace, therefore it may look like each model can evolve independently.
However, there are practical limitations.


TODO: import

TODO: tight coupling (inheritance) and loose coupling (extension)

See also link:../cross-model-usecases/[Cross-model use cases]

== QNames and URIs

TODO

== Recommendations

TODO: how to create good namespace URI, conventions
TODO: URIs, no requirement for resolvability. But it is recommended to choose URIs that could be resolvable in the future.

== Related Concepts

TODO: XML namespaces, JSON-LD context

== Notes

TODO: Namespace and versioning.
