= Axiom Namespaces

TODO: what is a namespace (URI)

== Model Identification

Namespace is a globally-unique identifier of a model.
Each namespace specifies exactly one model.
Whenever a data file needs to specify the data model that was used to create it, namespace is used to identify that model.
Whenever a data model refers to a concepts of another model, namespace of the model is used.
Whenever there is may be an ambiguity about appropriate interpretation of an item, namespace is used to resolve the ambiguity by pointing to the correct model.

== Isolation of Models to Support Evolution

All data models evolve.
They change to implement new features, adapt to changes environment or fix mistakes of the past.
Axiom is designed to combine, reuse and extend data models.
Each model has its own namespace, therefore it may look like each model can evolve independently.
However, there are practical limitations.

Some models are tightly interweaved.
They depend on one another and if one of them changes the other has to adapt.
This is usually caused by type inheritance.
The problem is, that even if the "parent" model evolves in an compatible way, the "child" (dependent) model may still be affected and it may be forced to change in non-compatible way.
The bad news is that there is not much that we can about this unless we want to make data structures quite complicated, big and difficult to use.
But the good news is that we usually do not need to do anything.
Development of models that are such a tight relationship are usually well coordinated.
Therefore such conflicts can usually be avoided or resolved by "out of band" means.

Then there are models that need to evolve independently and they are prepared to pay the cost.
There are two "safe" methods to use: _composition_ and _augmentation_.
Composition is a mechanism to use data type from a foreign schema in my own data structures.
Composition easy to use, it does not complicate the data and it is overall a recommended mechanism.
Augmentation is a mechanism to extend data type from foreign schema with custom items.
Augmentation ensures safe evolution of the models.
But it is using explicit specification of namespaces in the data, therefore it makes the data larger and more complex.

See link:../cross-model-usecases/[Cross-model use cases] for more details.

== QNames and URIs

TODO

== Recommendations

TODO: how to create good namespace URI, conventions
TODO: URIs, no requirement for resolvability. But it is recommended to choose URIs that could be resolvable in the future.

TODO: https URIs
TODO: do *not* end with slash (so QNames can be composed with #)
TODO: do *not* include version

== Related Concepts

TODO: XML namespaces, JSON-LD context

== Notes

TODO: Namespace and versioning.
