= Axiom Overview

A Axiom model defines data objects and their nested data item hierarchies.
This allows a complete human and machine-readable description of the data.

Axiom models data structures using _items_ and _values_ that are combined to specify _data types_.
Axiom provides clear and concise descriptions of the items, as well as relations between those items and their composition in data types.

Axiom definitions are grouped into models.
A model can import definitions from other external models.
Models can be extended, allowing one model to add items to the extension point defined in another model.

Axiom data models can describe constraints to be applied to the data.

Axiom defines a set of built-in types and has a type mechanism through which additional types may be defined.
Derived types can restrict their base type's set of valid values using mechanisms like range or pattern restrictions and extend their base type by addition of additional items in case of complex types.

Axiom is a self-descriptive language.
Axiom modeling language could be also modeled using Axiom.

== Models

Axiom definitions are grouped into models.
A model contains collection of related definitions that form a consistent group of data types for a specific use.

A model contains three types of statements: model header statements, versioning statements and definition statements.

TODO: model imports

== Types, Items and Values

Axiom defines basic concepts for data modeling - items, values and data types.

TODO: further explain items and values


== Built-in Types

Axiom provides following built-in simple types:

.Built-in types from XSD
boolean,
base64,
byte,
date,
dateTime,
dateTimeStamp,
decimal,
double,
duration,
float,
int,
integer,
language,
long,
negativeInteger,
nonNegativeInteger,
nonPositiveInteger,
normalizedString,
positiveInteger,
precisionDecimal,
QName,
short,
string,
time,
token,
unsignedByte,
unsignedInt,
unsignedLong,
unignedShort,
yearMonthDuration,

Axiom-specific built-in types:

AxiomIdentifier:: Represent item or type identifier

== Subtyping

Axiom allows subtyping (type derivation) for both simple and complex types.
Derived simple type may limit possible value set by imposing restrictions.
Derived complex type may introduce additional items (properties, container, object references).

[source, axiom]
----
type IdentifiableObject {
  item oid {
    type uuid;
  }
}

type User {
  supertype IdentifiableObject;
  item username {
    type string;
  }
}
----

== Metadata, Completeness And Other Underlying Concepts

// TODO: metadata overview

// TODO: completeness overview

// TODO: Simplified description of inframodel
