== Axiom Syntax

Axiom will uses syntax which will consists of statements (with arguments),
substatements and concepts.

NOTE: Statement concepts were inspired by YANG modeling language from IETF,
which tries to strike balance between readability and authoring.
(https://tools.ietf.org/html/rfc7950#section-6.3[YANG 1.1: 6.3 Statements])

.Basic ABNF
----
statement = keyword [argument] (";" / "{" *statement "}")
----

This provides basic simple structure for language and allows for simpler parser (See ANTLR4 syntax bellow.)

The *omission of actual keywords* from grammar allows for addition of keywords
and language extensions without need to change grammar definition (and lexer code).

NOTE: Experience during development and refactor of YANG Parser in OpenDaylight showed
that this simplified form is more flexible and allows for cleaner parsing code
and more user-friendly error reporting.

.Simple syntax example
[source,axiom]
----
complexType Address { // <1>
  description """
    Simple Address Type

    Represents physical address.
    Address should be normalized.
    """; // <2>
  property street {  // <3>
    type PolyString; // <4>
    required; // <5>
    storage:indexed fulltext; // <6>
  }
  // ...
}
----
<1> Complex statement `complexType` with argument `Address`
<2> Statement `description` with multi-line string argument
<3> Another complex `statement`
<4> Complex statement
<5> Simple statement without argument
<6> Statement `indexed` from extension `storage`



### Examples

[source,axiom]
----
include::examples/polystring.axiom[]
----
