== Terminology

The following terms are used within this document:


model:: Axiom model defines set of objects, items, types and value metadata definitions. With it definitions and definitions in its imports model is self-contained and "compilable"
object:: An identifiable entity.
item:: Item is attribute of object which can have value. There are 3 item types: *property*, *container* or *object reference*.
property:: An item, which can contain values of simple types, does not contain nested items. The type of value must be *simple type*.
container:: An item, whose values can contain multiple nested items, which are addressable. The type of value must be *complex type*.

type:: Represents a type of value. It can be *simple type* or *complex type*, and may its instance (value) may have *value metadata* attached.
simple type:: A type, which has simple value. The value may have nested items in case of some specific types.
complex type:: A type, which has complex value consisting of multiple items.

value:: Represents concrete instance of type. The value is instance of *type*
  and may have *value metadata* attached.

value metadata:: Represents metadata attached to value. The value metadata could be *property*, *container* or *object reference*.
extension:: Mechanism for declaring additional items to already defined objects. 
