== Terminology

The following terms are used within this document:


model:: Axiom model defines set of types, items and value metadata definitions.
With it definitions and definitions in its imports model is self-contained and "compilable"

schema:: Set of one or several models that are used together.
Schema is usually set of models that are loaded and active in an application.
Schema is a "soft" concept, it is not formally defined anywhere in Axiom definitions.

object:: An identifiable entity.
TODO: better explanation

item:: Item is attribute of object which can have value.
There are 3 item types: *property*, *container* or *object reference*.

property:: An item, which can contain values of simple types, does not contain nested items.
The type of value must be *simple type*.

container:: An item, whose values can contain multiple nested items, which are addressable.
The type of value must be *complex type*.


type:: Represents a type of value. It can be *simple type* or *complex type*, and may its instance (value) may have *value metadata* attached.

simple type:: A type, which has simple value. The value may have nested items in case of some specific types.

complex type:: A type, which has complex value consisting of multiple items.


value:: Represents concrete instance of type. The value is instance of *type* and may have *value metadata* attached.

value metadata:: Represents metadata attached to value.
The value metadata could be *property*, *container* or *object reference*.

extension:: Mechanism for declaring additional items to already defined objects.

representation format:: (also _serialization format_)
Specific data format used to store the data.
JSON, XML and YAML are examples of representation formats.
