= Model Versioning

Axiom is using https://semver.org/[semantic versioning] principles.
As Axiom deals with data and not the code, the semantic versioning is slightly modified to suit the needs of data compatibility.

Each axiom data model has a version:

[source,axiom]
----
model example {
    namespace "https://schema.example.com/ns/example";
    version "3.5";
}
----

== Semantic Version Numbers

Recommended format for version number is:

----
MAJOR.MINOR.PATCH
----

All three parts are usually numeric, e.g. `4.2.1`. The parts of version number have specific meaning:

* *Major* version number indicates compatibility.
Data models with the same major number must be compatible (with the exceptions specified below).
Changing major version number indicates that the data model may no longer be compatible with its previous versions.
Data created for a model with lower major version number may require significant modification or ever complete rewrite to fit the model with higher major version number.

* *Minor* version number indicate (compatible) revisions of the model.
Axiom assumes _backward_ compatibility (see below).
Changing minor version number indicates that the data model has evolved in a compatible way.
E.g. the model may be extended with new optional items.
Data created for a model with lower minor version number should be directly usable in processors built for model with higher minor version number.
However, the data may still need some modifications, e.g. removal or rewrite of deprecated or experimental items.

* *Patch* version number indicate corrections.
Changing patch version number indicates that the data model was updated, but there was no significant change in structure or meaning of the data.
Data created for a model with lower patch version number must be directly usable in processors built for model with higher patch version number.
The data must not require any modifications, with the exception of experimental items and corrections of previous incorrect behavior.

Version number that are zeros are optional. Therefore version `1.2` is to be considered the same as version `1.2.0`.
Minor and major version numbers must be numeric.
It is strongly recommended for patch version number to be numeric too.
However, it is allowed for it not to be numeric to account for hotfixes and other out-of-sequence patches.

In addition to that, version number may have optional suffix:

----
MAJOR.MINOR.PATCH-SUFFIX
----

The suffix indicates that the model version is _before_ or _lower_ than the specified version.
E.g. `1.2-SNAPSHOT` means that this is a model that is just before version `1.2`.
Therefore it is considered to be _after_ any `1.1` version, including `1.1.2` and `1.1.98761`, but not yet reaching version `1.2`.
The suffix is usually used for development, milestone or pre-release versions.
Ordering of the suffixes is not specified.
Therefore it is not specified whether `1.2-M3` is _before_ or _after_ `1.2-RC2`.

== Backward Compatibility


TODO: No 'compatible bugs' policy

== Data Model Evolution

TODO: since

TODO: Guidelines for compatible changes

== Deprecation and Removal

TODO: removal of deprecated elements


== Experimental Elements

TODO: experimental elements

TODO: 0.x is always experimental


// TODO: data model evolution: documentation, versioning (model version declaration, import specific version), compatibility, deprecated, experimental, etc.
