---
layout: connector-page
display-order: 200
functionality-status: limited
development-status: dormant
support-status: supportable
origin: Evolveum
support-provided-by: Evolveum
target-systems: SmartRecruiters cloud service
connector-protocol: REST
source-url-master: https://github.com/Evolveum/connector-smartrecruiters
description: Identity connector for SmartRecruiters cloud service over REST User API.
connid-bundle-name: com.evolveum.polygon.connector.smartrecruiters
upkeep-status: yellow
---
= SmartRecruiters Connector
:page-wiki-name: SmartRecruiters Connector
:page-wiki-id: 24085692
:page-wiki-metadata-create-user: oscar
:page-wiki-metadata-create-date: 2017-04-05T07:20:47.381+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-07-09T14:31:03.653+02:00

== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| Provisioning
| YES
|

| Live Synchronization
| NO
| Can be done over workaround: read all users and compare token with updatedOn user attribute.

| Password
| YES
|

| Activation
| YES
| Activation via the active attribute.

| Paging support
| YES
|

|===


== History

[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | Framework version | Description

| 1.0.0.0
| Polygon
| https://nexus.evolveum.com/nexus/repository/releases/com/evolveum/polygon/connector-smartrecruiters/1.0.0.0/connector-smartrecruiters-1.0.0.0.jar[download jar]
| link:https://github.com/Evolveum/connector-smartrecruiters[GitHub]
| December 2016
| 1.4.2.14
| Stable.

|===


== Licensing

The connector itself is available under the terms of Apache License 2.0. To our best knowledge, there is no extra license needed to use this connector.

== Documentation

To generate Your SmartRecruiters API key please log in, go to Settings / Admin, find in Configuration section API / Integrations.

Smart recruiters use Email globally, so if one e-mail address is registered and active, you can't create the new user with same e-mail address over API.
If you need to have test and also production environment, please use some e-mail address obfuscation like:

----
email = emailAddress.replace('@', '_');
return 'yourGmailAccount+' + email + '@gmail.com';
----

At the same time, in SmartRecruiters one user has exactly one role assigned.
Connector solve this restriction automatically - find the strongest role from list of all roles what midPoint sent and set only this.