---
layout: connector-page
display-order: 990
functionality-status: stable
development-status: abandoned
support-status: unsupported
origin: ICF
target-systems: LDAP servers
connector-protocol: LDAP/LDAPS
description: Legacy connector for LDAP servers based on JNDI.
upkeep-status: green
wiki-name: Legacy JNDI LDAP Connector
---
= Legacy LDAP Connector

Connector for LDAP-based directory servers.
Also works for LDAP access to Active Directory.
Evolution of original Sun LDAP connector.
CDDL-licensed and JNDI-based.

[WARNING]
.Legacy
====
*This connector is a development dead-end.*
It is JNDI-based connector.
JNDI is a very bad API for LDAP and it has severe limitations.
This connector is *not maintained* any more.
It is not supported.
It is no longer actively developed.
Use the new xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] instead whenever possible.
====

This connector originated from Sun ICF, taken over by OpenICF and then taken over by Polygon.
We do *not* recommend use of the original or OpenICF version.
The Polygon version has significant improvements over all other versions.
However, even the Polygon version is considered to be a legacy and it is not recommended.

== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| Schema | YES |

| Provisioning
| YES
|

| Live Synchronization
| YES
| For LDAP servers that support Sun-style changelog (Retro ChangeLog) or modifyTimestamp

| Password
| YES
|

| Activation
| NO
| Can be simulated in midPoint

| Filtering changes
| YES
| by modiffiersName

| Paging support
| YES
| Simple Paged Results and VLV.
But no support for partial search results (JNDI limitation)


| Native attribute names
| NO
|

|===


== History

This is mostly the original version from Sun ICF with some enhancements done by Evolveum, ForgeRock and others.

[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | Description

| 1.4.1.23
| Polygon
| https://nexus.evolveum.com/nexus/repository/releases/com/evolveum/polygon/connector-ldap-legacy/1.4.1.23/connector-ldap-legacy-1.4.1.23.jar[download jar]
| link:https://github.com/Evolveum/openicf/tree/connector-ldap-v1.4.1.23/connectors/java/ldap[GitHub]
| Aug 2015
| Official release


| 1.4.0.50
| Polygon
| https://nexus.evolveum.com/nexus/repository/releases/com/evolveum/polygon/connector-ldap-legacy/1.4.0.50/connector-ldap-legacy-1.4.0.50.jar[download jar]
| link:https://github.com/Evolveum/openicf/tree/connector-ldap-v1.4.0.50/connectors/java/ldap[GitHub]
| Jun 2015
| Official release


| 1.1.0.e6320d
| OpenICF development version, built and tested by Evolveum
| https://nexus.evolveum.com/nexus/repository/openicf-releases/org/forgerock/openicf/connectors/ldap-connector/1.1.0.e6320d/ldap-connector-1.1.0.e6320d.jar[download jar]
| OpenICF: ldap-connector-1.1.1.x-dev branch, revision 6320
| Jan 2013
| Build from the development branch, but well tested.
Includes all the necessary features.
Trunk version *does not* contain fixes e.g. to correctly support activation on OpenDJ


| 1.1.0.em2
| Evolveum OpenICF flavour
| https://nexus.evolveum.com/nexus/repository/openicf-releases/org/forgerock/openicf/connectors/ldap-connector/1.1.0.em2/ldap-connector-1.1.0.em2.jar[download jar]
| Evolveum OpenICF git repository (2c651a45b26960a017722a104c84fba4f9738c20)
| 5 Aug 2013
| Evolveum build.
Includes all the necessary features.
Original OpenICF version *does not* contain these fixes yet e.g. to correctly support activation on OpenDJ

|===

== Resource Examples

* xref:/connectors/resources/ldap/opendj/[OpenDJ]

* xref:/connectors/resources/ldap/dsee/[Directory Server Enterprise Edition]


== See Also

* xref:/midpoint/reference/upgrade/connectors/ldap-connector-migration/[LDAP Connector Migration]

* xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector]