= Describe user schema
:page-nav-title: User schema
:page-display-order: 1310
:page-upkeep-status: orange
:page-moved-from: /connectors/scimrest-framework/develop/25-user-schema/
:page-description: How to define a user object class schema in a SCIMREST connector using a Groovy builder script, including attribute types, formats, and access flags.
:page-keywords: user schema, object class, Groovy script, attribute definition, SCIMREST connector

How to define a user object class schema in a SCIMREST connector using a Groovy builder script, including attribute types, formats, and access flags.

Write a Groovy script describing the model in JSON using Groovy builder
like following:

[source,groovy]
----
objectClass("User") {
     attribute("created") {
         description "Time when user was created.";
         json {
            type  "string";
            openApiFormat "date-time";
         }
     }
    attribute("id") {
        description "ID of user";
        json {
            type "number";
            openApiFormat "int64";
        }

    }
}
----

The available attributes properties are:

 *  `json.type` - JSON Type
which is used to represent data in JSON
 *  `openApiFormat` - OpenAPI
Format (from https://spec.openapis.org/registry/format/), which
describes formatting of data, allowed values
 *  `description` -
Description of attribute as obtained from documentation
 *  `required`
- Is attribute required?
 *  `creatable` - Can attribute be used
during create operation, default is true, can be omitted.
 *
`readable` - Can attribute be read, default is true, can be omitted.

 *  `updatable` - Can attribute be modified default is true, can be
omitted.
 *  `returnedByDefault` - Is attribute returned by default