= Identity Matching

This page describes implementation of identity matching in midPoint, involving the use of Internet2 ID MATCH API.

== Pointers

* https://github.internet2.edu/internet2/id-match-api[Internet2 Github id-match-api Repository]
* http://aktis.org/docs/id-match-api-1.2.2.html[ID Match API V1.2.2 documentation web page]
* https://app.swaggerhub.com/apis/TIER_API_and_Schema/ID_Match/1.2.2[ID Match API V1.2.2 online live documentation on]

== CoManage Match

* https://spaces.at.internet2.edu/display/COmanage/COmanage+Match+Technical+Manual[COmanage Match Technical Manual]

* https://github.internet2.edu/COmanage/match/tree/develop[COmanage Match source code (develop branch)]

* https://hub.docker.com/r/tier/comanage-match-base[tier/comanage-match-base docker image]

Obviously, there is a need to create a new docker image based on `tier/comanage-match-base` image.
This is needed to set up the environment, e.g. database access.

Example docker file:

[source]
----
FROM tier/comanage-match-base:develop1
ARG COMANAGE_MATCH_VERSION=develop
ARG COMANAGE_MATCH_BASE_IMAGE_VERSION=1
ENV ENV=$SHORTENV
ARG COMANAGE_MATCH_BASE_IMAGE_VERSION
ENV COMANAGE_MATCH_BASE_IMAGE_VERSION ${COMANAGE_MATCH_BASE_IMAGE_VERSION}
LABEL comanage_match_base_image_version=${COMANAGE_MATCH_BASE_IMAGE_VERSION}
#COPY basic-auth /etc/apache2/
#COPY 000-comanage.conf /etc/apache2/sites-available/
ENV COMANAGE_MATCH_DATASOURCE Database/Postgres
ENV COMANAGE_MATCH_DATABASE comatch
ENV COMANAGE_MATCH_DATABASE_HOST comatchdb.example.com
ENV COMANAGE_MATCH_DATABASE_USER comatch
ENV COMANAGE_MATCH_DATABASE_USER_PASSWORD xxxxxxxx
----

Empty postgres database needs to be created, with `fuzzystrmatch` extension.
Comanage Match will create the database tables.
The instructions are on link:https://spaces.at.internet2.edu/display/COmanage/Match+Installation+-+Database[Match Installation - Database (Internet2 wiki)].

== See Also

* wiki:Manual+Correlation[]
