= MidPrivacy Bibliography
:page-nav-title: Bibliography

== Papers

https://riojournal.com/article/53916/[Methods & Proposal for Metadata Guiding Principles for Scholarly Communications]::
Paper about http://www.metadata2020.org/[Metadata 2020] - interoperable academic metadata.
Very general paper, mostly about principles, e.g.:
metadata 2020 principles:

* COMPATIBLE: provide a guide to content for machines and people.
So, metadata must be as open, interoperable, parsable, machine actionable, and human readable as possible.

* COMPLETE: reflect the content, components and relationships as published.
So, metadata must be as complete and comprehensive as possible.

* CREDIBLE: enable content discoverability and longevity.
So, metadata must be of clear provenance, trustworthy and accurate.

* CURATED: reflect updates and new elements.
So, metadata must be maintained over time.

== Specifications

https://protocol.jlinc.org/[JLINC Protocol] (Data portability)::
Simple protocol to establish a data-sharing agreement based on Standard Information Sharing Agreement (SISA).

== Sites

http://www.metadata2020.org/[Metadata 2020]::
Interesting initiative for interoperable metadata.
For now there is mostly guidance, principles and http://www.metadata2020.org/resources/metadata-use-cases/[usecases].
It is worth watching.
