---
layout: release
release-version: '4.6'
visibility: hidden
---
= MidPoint 4.6 "Baumgarten"
:release-version: 4.6
:page-liquid:
:page-toc: top

// TODO 4.4.3 was #42, if nothing is released 43 is good, otherwise fix:
Release {release-version} is a forty-third midPoint release code-named _Baumgarten_.
The {release-version} release brings ... TODO

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
Alexander Gottlieb Baumgarten (1714 – 1762) was a German philosopher.
Baumgarten appropriated the word <i>aesthetics</i>, which had previously meant "sensation", to mean taste or "sense" of beauty.
In so doing, he gave the word a different significance, thereby inventing its modern usage.
For Baumgarten, a science of aesthetics would be a deduction of the rules or principles of artistic or natural beauty from individual "taste".
</p>
<p>
TODO: There fore midPoint ...
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

== Changes With Respect To Version 4.5

=== New Features and Improvements

* Major features

** xref:/midpoint/devel/design/resource-schema-improvements-4.6/templates/[Resource and object type inheritance was implemented].
Resource inheritance in other words means Resource templates. Resource templates can be used in new resource wizard.

** xref:/midpoint/reference/correlation/[Smart correlation]

* User interface improvements

** AdminLTE upgraded to 3.2, Bootstrap to 4.6, Font-Awesome to 6.1. There has been changes in css class names.

** New resource wizard with the emphasis of simplification and better UX was implemented.

** xref:/midpoint/reference/admin-gui/self-service/#home-page[Home dashboard] was reworked.

** Configuration for Sel-service Profile page was separated from administration object's (logged in entity, so user, service,...) details page configuration.

** New xref:/midpoint/reference/admin-gui/request-access/[request access] GUI was implemented with the emphasis of better UX.
Also, xref:/midpoint/reference/admin-gui/request-access/configuration/[more configuration options] were added.

** Small improvements on credentials page.

** Possibility to xref:/midpoint/guides/gui-user-profile/[save filters] to GUI User profile was introduces.

** Assignment panels can be configured to xref:/midpoint/guides/assignment-repository-search/[use the repository for searching].
This setup provides more flexible search, especially by the target objects attributes, including full-text search on the target objects.
It can also help performance on the assignment panel for deployments with many assignments per object.

* Miscellaneous improvements

** xref:/midpoint/reference/concepts/query/query-api/[Query API] provides new filters `referencedBy`
and `ownedBy`, as well as support for nested filter for reference targets (AKA "target filter").

** ConnID Connector Server (Java) improvements and xref:/connectors/connid/1.x/connector-server/java/[documentation updates]

* Internal improvements

** Resource schema cleanup (include better hadling for kind/intent, moving synchronization definition to the objectType)

** Springboot upgraded


=== Deprecation, Feature Removal And Incompatible Changes

* WAR packaging for midPoint binary was changed to JAR packaging (`midpoint.jar`).
No change is required if provided scripts (in `bin` directory) are used for start/stop.
Replace `midpoint.war` with `midpoint.jar` in you service definitions - or recreate the service with
version 4.6 if you have no custom options in the service.
Explicit deployment of midPoint WAR to Tomcat became unsupported in the previous version 4.5.

** This change affects how midPoint overlays are developed - for more see
xref:/midpoint/reference/deployment/maven-overlay-project.adoc[this document].

* Older versions of `commons-lang` and `commons-collections` libraries were removed and are now
fully replaced by newer versions from group `org.apache.commons`, that is `commons-lang3` and
`commons-collections4`.
This may affect existing Groovy scripts.
Any imports from packages `org.apache.commons.lang` must be replaced with respective imports
from `org.apache.commons.lang3` (rarely `org.apache.commons.text`, e.g. `WordUtils`) and
package `org.apache.commons.collections` must be replaced with `org.apache.commons.collections4`.
Alternatively, provide the older JARs in the runtime by putting them in `${midpoint.home}/lib`.

=== API changes

==== midpoint.getFocusesByCorrelationRule

This method was not quite compatible with correlators changes introduced in 4.5,
and is definitely not compatible with synchronization schema changes done in this release.
So, it was rewritten from scratch, and renamed to `findCandidateOwners`.
(The old signature is still available but marked as deprecated.)
There may be minor differences in the behavior, so please review javadoc and adapt your code, if necessary.

=== Releases Of Other Components

TODO

++++
{% include release-quality.html %}
++++

=== Limitations

Following list provides summary of limitation of this midPoint release.

* Functionality that is marked as xref:/midpoint/versioning/experimental/[Experimental Functionality] is not supported for general use (yet).
Such features are not covered by midPoint support.
They are supported only for those subscribers that funded the development of this feature by the means of
xref:/support/subscription-sponsoring/[subscriptions and sponsoring] or for those that explicitly negotiated such support in their support contracts.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector].
Support for LDAP connector is included in standard midPoint support service, but there are limitations.
This "bundled" support only includes operations of LDAP connector that 100% compliant with LDAP standards.
Any non-standard functionality is explicitly excluded from the bundled support.
We strongly recommend to explicitly negotiate support for a specific LDAP server in your midPoint support contract.
Otherwise, only standard LDAP functionality is covered by the support.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] page for more details.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)].
Support for AD connector is included in standard midPoint support service, but there are limitations.
Only some versions of Active Directory deployments are supported.
Basic AD operations are supported, but advanced operations may not be supported at all.
The connector does not claim to be feature-complete.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)] page for more details.

* MidPoint user interface has flexible (responsive) design, it is able to adapt to various screen sizes, including screen sizes used by some mobile devices.
However, midPoint administration interface is also quite complex and it would be very difficult to correctly support all midPoint functionality on very small screens.
Therefore, midPoint often works well on larger mobile devices (tablets) it is very likely to be problematic on small screens (mobile phones).
Even though midPoint may work well on mobile devices, the support for small screens is not included in standard midPoint subscription.
Partial support for small screens (e.g. only for self-service purposes) may be provided, but it has to be explicitly negotiated in a subscription contract.

* There are several add-ons and extensions for midPoint that are not explicitly distributed with midPoint.
This includes xref:/midpoint/reference/interfaces/midpoint-client-java/[Java client library],
various https://github.com/Evolveum/midpoint-samples[samples], scripts, connectors and other non-bundled items.
Support for these non-bundled items is limited.
Generally speaking those non-bundled items are supported only for platform subscribers and those that explicitly negotiated the support in their contract.

* MidPoint contains a basic case management user interface.
This part of midPoint user interface is not finished.
The only supported part of this user interface is the part that is used to process requests and approvals.
Other parts of case management user interface are considered to be experimental, especially the parts dealing with manual provisioning cases.

* Production deployments of midPoint in Microsoft Windows environment are not supported.
Microsoft Windows is supported only for evaluation, demo, development and similar non-production purposes.

This list is just an overview, it may not be complete.
Please see the documentation regarding detailed limitations of individual features.

== Platforms

MidPoint is known to work well in the following deployment environment.
The following list is list of *tested* platforms, i.e. platforms that midPoint team or reliable partners personally tested with this release.
The version numbers in parentheses are the actual version numbers used for the tests.

It is very likely that midPoint will also work in similar environments.
But only the versions specified below are supported as part of midPoint subscription and support programs - unless a different version is explicitly agreed in the contract.

=== Operating System

MidPoint is likely to work on any operating system that supports the Java platform.
However, for *production deployment*, only some operating systems are supported:

* Linux (x86_64)

We are positive that MidPoint can be successfully installed on other operating systems, especially macOS and Microsoft Windows desktop.
Such installations can be used to for evaluation, demonstration or development purposes.
However, we do not support these operating systems for production environments.
The tooling for production use is not maintained, such as various run control (start/stop) script, low-administration and migration tools, backup and recovery support and so on.

=== Java

* OpenJDK 11 (11.0.16).

* OpenJDK 17.
This is a *recommended* platform.

OpenJDK 17 is the recommended Java platform to run midPoint.

Support for Oracle builds of JDK is provided only for the period in which Oracle provides public support (free updates) for their builds.
As far as we are aware, free updates for Oracle JDK 11 are no longer available.
Which means that Oracle JDK 11 is not supported for MidPoint anymore.
MidPoint is an open source project, and as such it relies on open source components.
We cannot provide support for platform that do not have public updates as we would not have access to those updates, and therefore we cannot reproduce and fix issues.
Use of open source OpenJDK builds with public support is recommended instead of proprietary builds.

=== Databases

Since midPoint 4.4, midPoint comes with two repository implementations: _native_ and _generic_.
Native PostgreSQL repository implementation is strongly recommended for all production deployments.

See xref:/midpoint/reference/repository/repository-database-support/[] for more details.

Since midPoint 4.0, *PostgreSQL is the recommended database* for midPoint deployments.
Our strategy is to officially support the latest stable version of PostgreSQL database (to the practically possible extent).
PostgreSQL database is the only database with clear long-term support plan in midPoint.
We make no commitments for future support of any other database engines.
See xref:/midpoint/reference/repository/repository-database-support/[] page for the details.
Only a direct connection from midPoint to the database engine is supported.
Database and/or SQL proxies, database load balancers or any other devices (e.g. firewalls) that alter the communication are not supported.

==== Native Database Support

xref:/midpoint/reference/repository/native-postgresql/[Native PostgreSQL repository implementation] is developed and tuned
specially for PostgreSQL database, taking advantage of native database features, providing improved performance and scalability.

This is now the *primary and recommended repository* for midPoint deployments.
Following database engines are supported:

* PostgreSQL 14 or 13

==== Generic Database Support (deprecated)

xref:/midpoint/reference/repository/generic/[Generic repository implementation] is based on object-relational
mapping abstraction (Hibernate), supporting several database engines with the same code.
Following database engines are supported with this implementation:

* H2 (embedded).
Supported only in embedded mode.
Not supported for production deployments.
Only the version specifically bundled with midPoint is supported. +
H2 is intended only for development, demo and similar use cases.
It is *not* supported for any production use.
Also, upgrade of deployments based on H2 database are not supported.

* PostgreSQL 14, 13, 12, 11.

* Oracle 12c

* Microsoft SQL Server 2019, 2016 SP1

Support for xref:/midpoint/reference/repository/generic/[generic repository implementation] together with all the database engines supported by this implementation is *deprecated*.
It is *strongly recommended* to migrate to xref:/midpoint/reference/repository/native-postgresql/[native PostgreSQL repository implementation] as soon as possible.
See xref:/midpoint/reference/repository/repository-database-support/[] for more details.

=== Supported Browsers

* Firefox
* Safari
* Chrome
* Edge
* Opera

Any recent version of the browsers is supported.
That means any stable stock version of the browser released in the last two years.
We formally support only stock, non-customized versions of the browsers without any extensions or other add-ons.
According to the experience most extensions should work fine with midPoint.
However, it is not possible to test midPoint with all of them and support all of them.
Therefore, if you chose to use extensions or customize the browser in any non-standard way you are doing that on your own risk.
We reserve the right not to support customized web browsers.

== Important Bundled Components

[%autowidth]
|===
| Component | Version | Description

| Tomcat
| 9.0.65
| Web container

| ConnId
| 1.5.1.7
// TODO double-check
| ConnId Connector Framework

| xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP connector bundle]
| 3.5
// TODO release non-M version
| LDAP and Active Directory

| xref:/connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/[CSV connector]
| 2.5
// TODO release non-M version
| Connector for CSV files

| xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable connector]
| 1.5.0.0
// TODO release non-M version
| Connector for simple database tables

|===

++++
{% include release-download.html %}
++++

== Upgrade

MidPoint is a software designed with easy upgradeability in mind.
We do our best to maintain strong backward compatibility of midPoint data model, configuration and system behavior.
However, midPoint is also very flexible and comprehensive software system with a very rich data model.
It is not humanly possible to test all the potential upgrade paths and scenarios.
Also, some changes in midPoint behavior are inevitable to maintain midPoint development pace.
Therefore, there may be some manual actions and configuration changes that need to be done during upgrades,
mostly related to xref:/midpoint/versioning/feature-lifecycle/[feature lifecycle].

This section provides overall overview of the changes and upgrade procedures.
Although we try to our best, it is not possible to foresee all possible uses of midPoint.
Therefore, the information provided in this section are for information purposes only without any guarantees of completeness.
In case of any doubts about upgrade or behavior changes please use services associated with xref:/support/subscription-sponsoring/[midPoint subscription programs].

Please refer to the xref:/midpoint/reference/upgrade/upgrade-guide/[] for general instructions and description of the upgrade process.
The guide describes the steps applicable for upgrades of all midPoint releases.
Following sections provide details regarding release {release-version}.

=== Upgrade From MidPoint 4.5.x

MidPoint {release-version} data model is backwards compatible with previous midPoint version.
Please follow our xref:/midpoint/reference/upgrade/upgrade-guide/[Upgrade guide] carefully.

Note that:

* There are database schema changes (see xref:/midpoint/reference/upgrade/database-schema-upgrade/[Database schema upgrade]).

* Version numbers of some bundled connectors have changed.
Connector references from the resource definitions that are using the bundled connectors need to be updated.

* TODO WAR->JAR change affects `systemd` configuration (`ExecStart` should refer to JAR now)

It is strongly recommended migrating to the xref:/midpoint/reference/repository/native-postgresql/[new native PostgreSQL repository implementation]
for all deployments that have not migrated yet.
However, it is *not* recommended upgrading the system and migrating the repositories in one step.
It is recommended doing it in two separate steps.
Please see xref:/midpoint/reference/repository/native-postgresql/migration/[] for the details.

=== Upgrade From MidPoint Versions Older Than 4.5

Upgrade from midPoint versions older than 4.5 to midPoint {release-version} is not supported directly.
Please xref:/midpoint/release/4.5/#upgrade[upgrade to midPoint 4.5.x] first.

=== Changes In Initial Objects Since 4.5

// TODO

=== Schema Changes Since 4.5

// TODO

=== Behavior Changes Since 4.5

* The meaning of `requireAssignmentTarget` configuration item in xref:/midpoint/reference/security/authentication/flexible-authentication/configuration/[Flexible Authentication Configuration] has been changed.
Previously, the values were checked against target (and resource) references in _assignments_.
Therefore, only directly assigned roles were taken into account.
(Moreover, the validity of the assignments was not checked.)
This was changed, and now the _effectively assigned_ roles are considered.
The check is based on `roleMembershipRef` values.
Resources are no longer taken into account.
Please see bug:MID-8123[] and link:https://github.com/Evolveum/midpoint/commit/c55b06e9[commit c55b06e9] for more information.

// TODO === Important Internal Changes Since 4.5

++++
{% include release-issues.html %}
++++
