---
layout: release
release-version: '4.6'
visibility: hidden
---
= MidPoint 4.6 "Baumgarten"
:release-version: 4.6
:page-liquid:
:page-toc: top

Release {release-version} is a forty-third midPoint release code-named _Baumgarten_.
The {release-version} release brings substantial GUI improvements, smart correlation, resource inheritance, and many smaller enhancements.

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
Alexander Gottlieb Baumgarten (1714 – 1762) was a German philosopher.
Baumgarten appropriated the word <i>aesthetics</i>, which had previously meant "sensation", to mean taste or "sense" of beauty.
In so doing, he gave the word a different significance, thereby inventing its modern usage.
For Baumgarten, a science of aesthetics would be a deduction of the rules or principles of artistic or natural beauty from individual "taste".
</p>
<p>Just as Alexander Baumgarten turned his mind to the beauty, midPoint is much nicer in this release.
MidPoint looks much better due to major GUI style improvements.
System administration is easier, supported by a brand-new resource wizard and resource templates.
There are significant improvements to end-user part of the user interface, contributing to ease-of-use.
New smart correlation mechanism aids in faster deployments and smoother system operation.
Overall, midPoint 4.6 looks better, and it is easier to use.
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

== Changes With Respect To Version 4.5

=== New Features and Improvements

==== Major New Features and Improvements in the User Interface

* The whole look-and-feel was greatly improved along with upgrading AdminLTE from 2.4 to 3.2, Bootstrap from 3.4 to 4.6, Font-Awesome from 5.15 to 6.1.

* New resource definition wizard with the emphasis on ease of use and better overall user experience (UX) was implemented. Wizard contains new panels, you can see their identifiers and configuration on xref:/midpoint/reference/admin-gui/admin-gui-config/#object-details-for-resource[Object details for resource].

* New xref:/midpoint/reference/admin-gui/request-access/[request access] wizard was implemented with the emphasis of better UX.
Also, xref:/midpoint/reference/admin-gui/request-access/configuration/[more configuration options] were added.

* The xref:/midpoint/reference/admin-gui/self-service/#home-page[home dashboard] was reworked.

* The possibility to xref:/midpoint/guides/gui-user-profile/[save search filters] to the user profile was introduced.


==== Major New Features Outside the User Interface

** *xref:/midpoint/reference/correlation/[Smart correlation]*.
MidPoint now supports very flexible correlation of resource objects (accounts, groups, and so on) to respective focus objects (users, roles, orgs, ...).
Multiple weighted correlation rules can be used.
Matching based on fuzzy logic (Levenshtein distance, trigram similarity) is supported.
As experimental features, custom normalization and matching data from multiple sources are available.

** *Resource templates.*
No more copying-and-pasting of resource configuration fragments!
MidPoint now supports the inheritance between resources and resource object types.
This means the administrator can define features common to multiple resources, and put them in the "super-resource" (or resource template) definition.
The same is true at the level of resource object types.
See xref:/midpoint/devel/design/resource-schema-improvements-4.6/templates/[Resource and object type inheritance] for more information.
This feature is used in the new resource definition wizard.

==== Other User Interface Improvements

** Assignment panels can be configured to xref:/midpoint/guides/assignment-repository-search/[use the repository for searching].
This setup provides more flexible search, especially by the target objects attributes, including full-text search on the target objects.
It can also help performance on the assignment panel for deployments with many assignments per object.

** Archetype, role, and GUI customization changes are applied almost immediately.
They do not require logout and re-login to take effect.
Users are logged out automatically when their administrative status is set to `disabled`.
When user permissions are changed, e.g. a role is assigned or unassigned, this takes immediate effect.
(See xref:/midpoint/reference/admin-gui/change-application.adoc[the detailed description].)

** The configuration for xref:/midpoint/reference/admin-gui/self-service/#profile-page[Self-service Profile page] was separated from the configuration of the editing of respective objects (typically the user or service) in the standard user interface used by the administrator.
Hence, it is now possible to provide a custom configuration for the self-service use.

** Small improvements on the credentials page.

==== Miscellaneous Improvements

* xref:/midpoint/reference/concepts/query/query-api/[Query API] provides new filters `referencedBy`
and `ownedBy`, as well as support for nested filter for reference targets (a.k.a. "target filter").

* There are ConnID Connector Server (Java) improvements and xref:/connectors/connid/1.x/connector-server/java/[documentation updates].

==== Internal Improvements

** The resource definition schema was cleaned up.
This includes better handling of `kind` and `intent` values, the possibility to globally override object class definitions, and moving synchronization-related configuration right into the `objectType` definition.

** Spring Boot was upgraded from 2.5 to 2.7.

=== Deprecation, Feature Removal And Incompatible Changes

* WAR packaging for midPoint binary was changed to JAR packaging (`midpoint.jar`).
No change is required if provided scripts (in `bin` directory) are used for start/stop.
Replace `midpoint.war` with `midpoint.jar` in you service definitions - or recreate the service with
version 4.6 if you have no custom options in the service.
Explicit deployment of midPoint WAR to Tomcat became unsupported in the previous version 4.5.

** This change affects how midPoint overlays are developed - for more see
xref:/midpoint/reference/deployment/maven-overlay-project.adoc[this document].

* Older versions of `commons-lang` and `commons-collections` libraries were removed and are now
fully replaced by newer versions from group `org.apache.commons`, that is `commons-lang3` and
`commons-collections4`.
This may affect existing Groovy scripts.
Any imports from packages `org.apache.commons.lang` must be replaced with respective imports
from `org.apache.commons.lang3` (rarely `org.apache.commons.text`, e.g. `WordUtils`) and
package `org.apache.commons.collections` must be replaced with `org.apache.commons.collections4`.
Alternatively, provide the older JARs in the runtime by putting them in `${midpoint.home}/lib`.

* As part of GUI upgrade, there are changes in CSS class names (watch out for Font-Awesome icons and standard Bootstrap CSS classes).

=== API changes

==== midpoint.getFocusesByCorrelationRule

This method was not quite compatible with correlators changes introduced in 4.5,
and is definitely not compatible with synchronization schema changes done in this release.
So, it was rewritten from scratch, and renamed to `findCandidateOwners`.
(The old signature is still available but marked as deprecated.)
There may be minor differences in the behavior, so please review javadoc and adapt your code, if necessary.

=== Releases Of Other Components

* New version (3.5) of LDAP connector bundle (including xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] and xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector]) was released and bundled with midPoint.

* New version (2.5) of xref:/connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/[CSV Connector] was released and bundled with midPoint.

* New version (1.5.0.0) of xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable Connector] was released and bundled with midPoint.

** New versions of these connectors (LDAP, CSV, database table) support the configuration discovery and contain several bugfixes, many of which were contributed by the community.

* Docker images will be released in Docker Hub soon after midPoint {release-version} release.

* Overlay project examples will be released soon after midPoint {release-version} release.

* xref:/midpoint/tools/studio/[MidPoint Studio] version {release-version} will be released soon after midPoint {release-version} release.

* xref:/midpoint/devel/prism/[Prism] data representation library {release-version} was released together with midPoint {release-version}.

* xref:/midpoint/reference/interfaces/midpoint-client-java/[Midpoint client Java library] will be released soon after midPoint {release-version} release.

++++
{% include release-quality.html %}
++++

=== Limitations

Following list provides summary of limitation of this midPoint release.

* Functionality that is marked as xref:/midpoint/versioning/experimental/[Experimental Functionality] is not supported for general use (yet).
Such features are not covered by midPoint support.
They are supported only for those subscribers that funded the development of this feature by the means of
xref:/support/subscription-sponsoring/[subscriptions and sponsoring] or for those that explicitly negotiated such support in their support contracts.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector].
Support for LDAP connector is included in standard midPoint support service, but there are limitations.
This "bundled" support only includes operations of LDAP connector that 100% compliant with LDAP standards.
Any non-standard functionality is explicitly excluded from the bundled support.
We strongly recommend to explicitly negotiate support for a specific LDAP server in your midPoint support contract.
Otherwise, only standard LDAP functionality is covered by the support.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] page for more details.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)].
Support for AD connector is included in standard midPoint support service, but there are limitations.
Only some versions of Active Directory deployments are supported.
Basic AD operations are supported, but advanced operations may not be supported at all.
The connector does not claim to be feature-complete.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)] page for more details.

* MidPoint user interface has flexible (responsive) design, it is able to adapt to various screen sizes, including screen sizes used by some mobile devices.
However, midPoint administration interface is also quite complex, and it would be very difficult to correctly support all midPoint functionality on very small screens.
Therefore, midPoint often works well on larger mobile devices (tablets), but it is very likely to be problematic on small screens (mobile phones).
Even though midPoint may work well on mobile devices, the support for small screens is not included in standard midPoint subscription.
Partial support for small screens (e.g. only for self-service purposes) may be provided, but it has to be explicitly negotiated in a subscription contract.

* There are several add-ons and extensions for midPoint that are not explicitly distributed with midPoint.
This includes xref:/midpoint/reference/interfaces/midpoint-client-java/[Java client library],
various https://github.com/Evolveum/midpoint-samples[samples], scripts, connectors and other non-bundled items.
Support for these non-bundled items is limited.
Generally speaking, those non-bundled items are supported only for platform subscribers and those that explicitly negotiated the support in their contract.

* MidPoint contains a basic case management user interface.
This part of midPoint user interface is not finished.
The only supported parts of this user interface are those that are used to process requests, approvals, and manual correlation.
Other parts of case management user interface are considered to be experimental, especially the parts dealing with manual provisioning cases.

* Production deployments of midPoint in Microsoft Windows environment are not supported.
Microsoft Windows is supported only for evaluation, demo, development and similar non-production purposes.

This list is just an overview, it may not be complete.
Please see the documentation regarding detailed limitations of individual features.

== Platforms

MidPoint is known to work well in the following deployment environment.
The following list is list of *tested* platforms, i.e. platforms that midPoint team or reliable partners personally tested with this release.
The version numbers in parentheses are the actual version numbers used for the tests.

It is very likely that midPoint will also work in similar environments.
But only the versions specified below are supported as part of midPoint subscription and support programs - unless a different version is explicitly agreed in the contract.

=== Operating System

MidPoint is likely to work on any operating system that supports the Java platform.
However, for *production deployment*, only some operating systems are supported:

* Linux (x86_64)

We are positive that midPoint can be successfully installed on other operating systems, especially macOS and Microsoft Windows desktop.
Such installations can be used to for evaluation, demonstration or development purposes.
However, we do not support these operating systems for production environments.
The tooling for production use is not maintained, such as various run control (start/stop) scripts, low-level administration and migration tools, backup and recovery support and so on.

=== Java

* OpenJDK 11 (11.0.16).

* OpenJDK 17.
This is a *recommended* platform.

OpenJDK 17 is the recommended Java platform to run midPoint.

Support for Oracle builds of JDK is provided only for the period in which Oracle provides public support (free updates) for their builds.
As far as we are aware, free updates for Oracle JDK 11 are no longer available.
Which means that Oracle JDK 11 is not supported for MidPoint anymore.
MidPoint is an open source project, and as such it relies on open source components.
We cannot provide support for platform that do not have public updates as we would not have access to those updates, and therefore we cannot reproduce and fix issues.
Use of open source OpenJDK builds with public support is recommended instead of proprietary builds.

=== Databases

Since midPoint 4.4, midPoint comes with two repository implementations: _native_ and _generic_.
Native PostgreSQL repository implementation is strongly recommended for all production deployments.

See xref:/midpoint/reference/repository/repository-database-support/[] for more details.

Since midPoint 4.0, *PostgreSQL is the recommended database* for midPoint deployments.
Our strategy is to officially support the latest stable version of PostgreSQL database (to the practically possible extent).
PostgreSQL database is the only database with clear long-term support plan in midPoint.
We make no commitments for future support of any other database engines.
See xref:/midpoint/reference/repository/repository-database-support/[] page for the details.
Only a direct connection from midPoint to the database engine is supported.
Database and/or SQL proxies, database load balancers or any other devices (e.g. firewalls) that alter the communication are not supported.

==== Native Database Support

xref:/midpoint/reference/repository/native-postgresql/[Native PostgreSQL repository implementation] is developed and tuned
specially for PostgreSQL database, taking advantage of native database features, providing improved performance and scalability.

This is now the *primary and recommended repository* for midPoint deployments.
Following database engines are supported:

* PostgreSQL 15, 14, and 13

==== Generic Database Support (deprecated)

xref:/midpoint/reference/repository/generic/[Generic repository implementation] is based on object-relational
mapping abstraction (Hibernate), supporting several database engines with the same code.
Following database engines are supported with this implementation:

* H2 (embedded).
Supported only in embedded mode.
Not supported for production deployments.
Only the version specifically bundled with midPoint is supported. +
H2 is intended only for development, demo and similar use cases.
It is *not* supported for any production use.
Also, upgrade of deployments based on H2 database are not supported.

* PostgreSQL 15, 14, 13, 12, and 11

* Oracle 21c

* Microsoft SQL Server 2019

Support for xref:/midpoint/reference/repository/generic/[generic repository implementation] together with all the database engines supported by this implementation is *deprecated*.
It is *strongly recommended* to migrate to xref:/midpoint/reference/repository/native-postgresql/[native PostgreSQL repository implementation] as soon as possible.
See xref:/midpoint/reference/repository/repository-database-support/[] for more details.

=== Supported Browsers

* Firefox
* Safari
* Chrome
* Edge
* Opera

Any recent version of the browsers is supported.
That means any stable stock version of the browser released in the last two years.
We formally support only stock, non-customized versions of the browsers without any extensions or other add-ons.
According to the experience most extensions should work fine with midPoint.
However, it is not possible to test midPoint with all of them and support all of them.
Therefore, if you chose to use extensions or customize the browser in any non-standard way you are doing that on your own risk.
We reserve the right not to support customized web browsers.

== Important Bundled Components

[%autowidth]
|===
| Component | Version | Description

| Tomcat
| 9.0.65
| Web container

| ConnId
| 1.5.1.10
| ConnId Connector Framework

| xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP connector bundle]
| 3.5
| LDAP and Active Directory

| xref:/connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/[CSV connector]
| 2.5
| Connector for CSV files

| xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable connector]
| 1.5.0.0
| Connector for simple database tables

|===

++++
{% include release-download.html %}
++++

== Upgrade

MidPoint is a software designed with easy upgradeability in mind.
We do our best to maintain strong backward compatibility of midPoint data model, configuration and system behavior.
However, midPoint is also very flexible and comprehensive software system with a very rich data model.
It is not humanly possible to test all the potential upgrade paths and scenarios.
Also, some changes in midPoint behavior are inevitable to maintain midPoint development pace.
Therefore, there may be some manual actions and configuration changes that need to be done during upgrades,
mostly related to xref:/midpoint/versioning/feature-lifecycle/[feature lifecycle].

This section provides overall overview of the changes and upgrade procedures.
Although we try to our best, it is not possible to foresee all possible uses of midPoint.
Therefore, the information provided in this section are for information purposes only without any guarantees of completeness.
In case of any doubts about upgrade or behavior changes please use services associated with xref:/support/subscription-sponsoring/[midPoint subscription programs].

Please refer to the xref:/midpoint/reference/upgrade/upgrade-guide/[] for general instructions and description of the upgrade process.
The guide describes the steps applicable for upgrades of all midPoint releases.
Following sections provide details regarding release {release-version}.

=== Upgrade From MidPoint 4.5.x

MidPoint {release-version} data model is backwards compatible with previous midPoint version.
Please follow our xref:/midpoint/reference/upgrade/upgrade-guide/[Upgrade guide] carefully.

Note that:

* There are database schema changes (see xref:/midpoint/reference/upgrade/database-schema-upgrade/[Database schema upgrade]).

* Version numbers of some bundled connectors have changed.
Connector references from the resource definitions that are using the bundled connectors need to be updated.

* Replace `midpoint.war` with `midpoint.jar` in you service definitions - or recreate the service with version 4.6 if you have no custom options in the service.

It is strongly recommended migrating to the xref:/midpoint/reference/repository/native-postgresql/[new native PostgreSQL repository implementation]
for all deployments that have not migrated yet.
However, it is *not* recommended upgrading the system and migrating the repositories in one step.
It is recommended doing it in two separate steps.
Please see xref:/midpoint/reference/repository/native-postgresql/migration/[] for the details.

=== Upgrade From MidPoint Versions Older Than 4.5

Upgrade from midPoint versions older than 4.5 to midPoint {release-version} is not supported directly.
Please xref:/midpoint/release/4.5/#upgrade[upgrade to midPoint 4.5.x] first.

=== Changes In Initial Objects Since 4.5

MidPoint has a built-in set of "initial objects" that it will automatically create in the database if they are not present.
This includes vital objects for the system to be configured (e.g. role `Superuser` and user `administrator`).
These objects may change in some midPoint releases.
However, midPoint is conservative and avoids overwrite of customized configuration objects.
Therefore, midPoint does not overwrite existing objects when they are already in the database.
This may result in upgrade problems if the existing object contains configuration that is no longer supported in a new version.

The following list contains a summary of changes to the initial objects in this midPoint release.
The complete new set of initial objects is in the `config/initial-objects` directory in both the source and binary distributions.
Although (in general) any problems caused by the changes in initial objects are unlikely to occur, the implementors are advised to review the changes and assess the impact on case-by-case basis.
In particular, the GUI changes between 4.5 and 4.6 require the `adminGuiConfiguration` changes be applied thoroughly.
Also, the application of default configuration for flexible authentication is needed for successful non-GUI login.

* `000-system-configuration.xml`:
Added default configuration for Request access GUI.
Self-service Home page configuration was reworked to use new schema for widgets.
Added configuration for different parts of Resource details page (e.g. virtual containers' configuration, connector properties panel configuration, and so on).
StringUtils package name was upgraded in the expression profile.

* `015-security-policy.xml`: Added default configuration for flexible authentication.

* `027-archetype-correlation-case.xml`: Added panels ordering.

* `040-role-enduser.xml`:
It was updated with Self service Home and Profile pages configuration.
The (unneeded) "self-owned-task-add-execute-changes" authorization was removed.

* `042-role-reviewer.xml`: The `orgs-read` authorization was fixed to read basic organization properties.

* `043-role-delegator.xml`: Delegator role was updated with Self service Home page configuration.

* `240-lookup-state.xml`: It was updated with new values.

* `516-archetype-task-shadows-delete-long-time-not-updated.xml`: The name computation script was changed to show referenced resource objects information.

* `518-archetype-task-execute-deltas.xml`: The order of elements was fixed to comply with the XSD definition.

* `000-system-configuration.xml`, `023-archetype-manual-provisioning-case.xml`, `027-archetype-correlation-case.xml`, `059-archetype-report.xml`, `060-archetype-report-dashboard.xml`, `501-archetype-task-reconciliation.xml`, `504-archetype-task-live-sync.xml`, `506-archetype-task-cleanup.xml`, `507-archetype-task-report.xml`, `511-archetype-task-report-export-classic.xml`: Some changes related to AdminLTE upgrade were made in these files (e.g. icon css class changes).

Please review link:https://github.com/Evolveum/midpoint/commits/master/gui/admin-gui/src/main/resources/initial-objects[source code history] for detailed list of changes.

TIP: Copies of initial object files are located in `config/initial-objects` directory of midPoint distribution packages. These files can be used as a reference during upgrades. On-line version can be found in https://github.com/Evolveum/midpoint/tree/v{release-version}/config/initial-objects[midPoint source code].

=== Schema Changes Since 4.5

// TODO

=== Behavior Changes Since 4.5

* The meaning of `requireAssignmentTarget` configuration item in xref:/midpoint/reference/security/authentication/flexible-authentication/configuration/[Flexible Authentication Configuration] has been changed.
Previously, the values were checked against target (and resource) references in _assignments_.
Therefore, only directly assigned roles were taken into account.
(Moreover, the validity of the assignments was not checked.)
This was changed, and now the _effectively assigned_ roles are considered.
The check is based on `roleMembershipRef` values.
Resources are no longer taken into account.
Please see bug:MID-8123[] and link:https://github.com/Evolveum/midpoint/commit/c55b06e9[commit c55b06e9] for more information.

// TODO === Important Internal Changes Since 4.5

++++
{% include release-issues.html %}
++++
