---
layout: release
release-version: '4.6'
visibility: hidden
---
= MidPoint 4.6 "TODO"
:release-version: 4.6
:page-liquid:
:page-toc: top

Release {release-version} is a TODO midPoint release code-named _TODO_. The {release-version} release brings ...

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
    Whatever J. Random (xxxx-yyyy) was nobody, really ...
</p>
<p>
    There fore midPoint ...
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

== Changes With Respect To Version 4.5

=== New Features and Improvements

TODO

=== Deprecation, Feature Removal And Incompatible Changes

* WAR packaging for midPoint binary was changed to JAR packaging (`midpoint.jar`).
No change is required if provided scripts (in `bin` directory) are used for start/stop.
Replace `midpoint.war` with `midpoint.jar` in you service definitions - or recreate the service with
version 4.6 if you have no custom options in the service.
Explicit deployment of midPoint WAR to Tomcat became unsupported in previous version 4.5.

** This change affects how midPoint overlays are developed - for more see
xref:/midpoint/reference/deployment/maven-overlay-project.adoc[this document].

* Older versions of `commons-lang` and `commons-collections` libraries were removed and are now
fully replaced by newer versions from group `org.apache.commons`, that is `commons-lang3` and
`commons-collections4`.
This may affect existing Groovy scripts.
Any imports from packages `org.apache.commons.lang` must be replaced with respective imports
from `org.apache.commons.lang3` (rarely `org.apache.commons.text`, e.g. `WordUtils`) and
package `org.apache.commons.collections` must be replaced with `org.apache.commons.collections4`.
Alternatively, provide the older JARs in the runtime by putting them in `${midpoint.home}/lib`.

=== API changes (good term?)

==== midpoint.getFocusesByCorrelationRule

This method was not quite compatible with correlators changes introduced in 4.5, and is definitely not compatible
with synchronization schema changes done in this release. So, it was rewritten from scratch, and renamed to
`findCandidateOwners`. (The old signature is still available but marked as deprecated.) There may be minor
differences in the behavior, so please review javadoc and adapt your code, if necessary.
