---
layout: release
release-version: '4.6'
visibility: hidden
---
= MidPoint 4.6 "TODO"
:release-version: 4.6
:page-liquid:
:page-toc: top

Release {release-version} is a TODO midPoint release code-named _TODO_. The {release-version} release brings ...

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
    Whatever J. Random (xxxx-yyyy) was nobody, really ...
</p>
<p>
    There fore midPoint ...
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

== Bla bla bla

=== API changes (good term?)

==== midpoint.getFocusesByCorrelationRule

This method was not quite compatible with correlators changes introduced in 4.5, and is definitely not compatible
with synchronization schema changes done in this release. So, it was rewritten from scratch, and renamed to
`findCandidateOwners`. (The old signature is still available but marked as deprecated.) There may be minor
differences in the behavior, so please review javadoc and adapt your code, if necessary.
