= Outline of the first steps guide
:page-nav-title: Outline
:page-display-order: 54
:experimental:
:icons: font
:page-moved-from: /midpoint/methodology/first-steps/outline-and-concept/

To go from greenfield to a functional midPoint deployment, you will go through the following steps:

. Decide what is it exactly that you need.
	** Which systems do you need to connect to identity management (IDM)?
	** What level of security do you need?
	** Consider your budget for long-term IDM expenses.
. Connect and integrate your first source and target systems using smart correlation.
. Map account attributes.
. Clean up the data by fixing inconsistencies and handling orphaned accounts.
. Automate some processes, such as the joiner-mover-leaver (JML) process.

Obviously, while midPoint makes administrator's life very safe thanks to simulations, it is never a good idea to learn by trial and error on production data.
The easiest course of action for you is to use the sample data we have prepared for you.
Alternatively, you can create your own test environment and work with that.
This First steps guide works for either of the approaches.

== Next steps

Before you get into the action, one important module remains:
Get acquainted with the iterative approach on which this guide builds.

[.nowrap]#icon:arrow-right[] *xref:/midpoint/methodology/first-steps/outline-and-concept/iterative-concept/[]*#