---
layout: connector-page
origin: Evolveum
sourceUrlMaster: https://github.com/Evolveum/connector-ldap
visibility: hidden
---
= LDAP Connector
:page-liquid:

include::description.adoc[]

== Interoperability

In theory the connector should work with any LDAPv3 compliant LDAP server.
However, many servers claim LDAPv3 compliance while the reality is far from ideal.
The connector supports "quirks" of several popular LDAP servers and it tolerates some violations of LDAPv3 standards.

The connector was successfully tested with the following LDAP servers (assuming reasonably recent versions of the servers):

* OpenLDAP
* ForgeRock OpenDJ / wren:DS
* 389 directory server / Red Hat Directory Server / Fedora Directory Server
* Oracle Directory Server Enterprise Edition (DSEE) / Sun One / Sun Java System / iPlanet Directory Server
* ViewDS

We know that at least some operations of the connector works with these servers and they are supported in some midPoint deployments.
However, support for any specific server is not part of standard midPoint subscription and it has to be negotiated separately (see below).

If you are using this connector with a different directory server please let us know.
We would like to know both about the positive and negative experiences.

== History

Click on a version number to get the details about a particular connector version.

++++
{% include connector-history.html %}
++++

This is an LDAP connector completely rewritten from scratch in 2015.
It is using Apache Directory API and it is designed and built to work with recent ConnId versions and to take all the advantages of that.
This is the supported and recommended LDAP and AD connector for midPoint.
The old LDAP and AD connectors are now deprecated and they are no longer supported.

== Support

LDAP connector is bundled with midPoint distribution.
Support for LDAP connector is included in standard midPoint support service (a.k.a. link:https://wiki.evolveum.com/display/midPoint/Bundled+Support[bundled support]) - however, there are limitations.
This "bundled" support only includes operations of LDAP connector that 100% compliant with LDAP standards.
Any non-standard functionality is explicitly excluded from the bundled support.

It is a sad fact that so far we haven't seen any LDAP server that would be 100% standard-compliant or that would not require any non-standard extensions to work.
Therefore if you want to be sure that this LDAP connector will work with your LDAP server, we strongly recommend to negotiate support for that specific server in your midPoint support contract.

For the purposes of this definition "standard" means RFC specifications that reach at least a "proposed standard" status.
Drafts, informational documents, vendor specifications or any other documents are not considered to be part of LDAP standards.

This means that the bundled support does not include support for any specific LDAP server.
Support for specific servers needs to be explicitly negotiated in the support contract.

NOTE: There may be exception to this rule for the customers that purchased support before the release of midPoint 4.0.
In case of any doubts please contact Evolveum sales representatives.

== Notes

The LDAP connector bundle also contains connector for Active Directory.
These connectors are specializations of the LDAP connector and support the LDAP quirks needed to work with AD.
