---
midpoint-feature: midScribe
doc-type: intro
---
= midScribe
:page-toc: top

The midscribe is a command-line utility used to generate documentation from midPoint objects.
It reads the XML files, extracts relevant information about objects and their relationships, and uses this data to create documentation in various formats.

== Studio integration

Midscribe is also integrated within Intellij IDEA MidPoint Studio plugin.
Documentation can be generated directly from the Studio by using action `Generate documentation`.
For more information see Studio xref:/midpoint/tools/studio/usage/index.adoc[documentation].

== Examples

.Generate documentation in Asciidoc format
[source, bash]
----
java -jar midscribe.jar generate -s /path/to/objects/directory -o output.adoc
----

.Generate documentation in PDF format
[source, bash]
----
java -jar midscribe.jar generate -s /path/to/objects/directory -o output.pdf -of PDF
----

.Generate documentation in HTML format, but only including xml files from the `users` directory
[source, bash]
----
java -jar midscribe.jar generate -s /path/to/objects/directory -i "users/*.xml" -o output.html -of HTML
----