= MidScribe
:toc:

The midscribe is a command-line utility used to generate documentation from midPoint objects.
It reads the XML files, extracts relevant information about objects and their relationships, and uses this data to create documentation in various formats.

Xml files can be sourced using the `-s, --source` option.
This option can be used multiple times to specify multiple source directories or files.

Second set of xml files can be specified using the `-as, --additional-source` option.
These objects won't be directly used to create documentation, but they can be used to read additional data like reference names or descriptions.
For example when documenting resource, description of connector configuration properties can be read from the connector schema.

Command also supports include `-i, --include` and exclude `-e, --exclude` patterns to filter files.

If files contains parameters that should be expanded before documentation is generated, then `-p, --properties` option can be used to specify properties file with parameters for expansion.

Currently supported formats are Asciidoc, PDF and HTML.

.Full usage
[source, bash]
----
Usage: java [-Dlogback.configurationFile=logback.xml] -jar midscribe.jar [options] [command] [command options]
  Options:
    -h, --help
      Print this help
    -s, --silent
      No output at all
      Default: false
    -v, --verbose
      Verbose output
      Default: false
    -V, --version
      Version and build description
      Default: false
  Commands:
    generate      Generate documentation
      Usage: generate [options]
        Options:
          -as, --additional-source
            Additional source directories/files, not directly used to create documentation. E.g. objects referenced in source files.
          -e, --exclude
            Exclude pattern to be used on source directories/files.
          -i, --include
            Include pattern to be used on source directories/files
          -o, --output
            Output file name (path).
          -of, --output-format
            Output format.
            Default: ADOC
            Possible Values: [ADOC, PDF, HTML]
          -p, --properties
            Properties file with parameters for report.
        * -s, --source
            Source directories/files.
          -t, --template
            Template file. File should be ZIP archive containing "template" directory with Velocity templates. Main template is "documentation.vm".

----

== Studio integration

Midscribe is also integrated within Intellij IDEA MidPoint Studio plugin.
Documentation can be generated directly from the Studio by using action `Generate documentation`.
For more information see Studio xref:/midpoint/tools/studio/usage/index.adoc[documentation].

== Examples

.Generate documentation in Asciidoc format
[source, bash]
----
java -jar midscribe.jar generate -s /path/to/objects/directory -o output.adoc
----

.Generate documentation in PDF format
[source, bash]
----
java -jar midscribe.jar generate -s /path/to/objects/directory -o output.pdf -of PDF
----

.Generate documentation in HTML format, but only including xml files from the `users` directory
[source, bash]
----
java -jar midscribe.jar generate -s /path/to/objects/directory -i "users/*.xml" -o output.html -of HTML
----