= Evolveum Maven Repository
:page-nav-title: Maven Repository
:page-wiki-name: Evolveum Maven Repository
:page-upkeep-status: yellow

Evolveum maintains maven repository at link:http://nexus.evolveum.com[nexus.evolveum.com]. The goal of this repository is to for the internal development purposes for midPoint project.
The repository is publicly available as we are trying to be open in everything that we do.
Despite that, there are *no guarantees* about the content, availability or integrity of the repository.

If you depend on this repository *you are doing that on your own risk*. Especially when using snapshot artifacts.
Those artifacts are published to our repository by our wiki:Continuous+Integration[continuous integration] (CI) system.
This system is undergoing evolution as any other development system.
Therefore there may be times when the artifacts are not available.
And even the fundamental principle of the development snapshot does not provide much guarantee.
CI system is in its nature a testing system.
It may publish artifacts that are broken, incomplete or corrupt.
This is likely to get fixed later on.
But we make no guarantees when that actually happens.
The tasks of the CI system may be re-prioritized any time without a warning to reflect current development activities.
CI tasks may be suspended, migrated or they may simply get broken due to unforeseen circumstances.
Hic sunt leones.
Snapshot artifacts may make the life somewhat easier.
But we usually do not depend on these artifacts ourselves during our development cycle.
And neither should you.

There are also release artifacts published in our maven repository.
Those are somewhat more reliable as they are published by a manual process during product releases.
However, we do not make any guarantees about those artifacts either.
Official midPoint releases are available in binary form from our link:https://evolveum.com/download/[download page] or in wiki:Source+Code[source code] form from our wiki:Git[git repository]. Artifacts in our maven repository are *not* considered official release images.

If you need a dependable environment then we recommend to set up your own CI system that will create your own snapshot images directly from the source code.


== See Also

* wiki:Continuous+Integration[Continuous Integration]

* wiki:Git[Git]

* wiki:Source+Code[Source Code]

