= Additional Notes
:page-nav-title: Additional Notes
:page-display-order: 300
:sectnums:
:sectnumlevels: 3

== Additional notes

=== Reporting

#TODO#
////
Sem, ze ake zakladne reporty by sa mali robit - alebo pripadne to dame ako linku na use-cases

	- Zakladne reporty:
		○ Kto ma pristup kam a preco
		○ Role model
	- Priebezne vytvarat reporty, ktore budu popisovat jednotlive stavy, procesy. Zlepsovat, optimalizovat.

a este info, ze reporty umoznuju merat procesy a kvalitu dat - cize umoznuju predavat vysledky v IGA
////


=== Integration with manual provisioning

#TODO#
////
	- Existujuce ITSM systemy su dizajnovane na sprocesovanie poziadavky, nie vsak na popisanie accessu -> to musime zabezpecit v IGA.
	- Mozeme zaintegrovat tak, ze vytvorenie poziadavky, ktora prebiehala cez ITSM vykona IGA a zaroven po uzavreti ulohy oznaci pristup ako prideleny.
Integracia manualneho provisioningu zabezpeci prepojenie manualnej ulohy s danym assignmentom, takze bude zabezpecena evidencia, kto ma aky pristup (samozrejme nie na 100%, toto budu musiet zabezpecit dalsie kontrolne mechanizmy).

////

=== Naming convention of roles
#TODO#

////
Tu popisat naming convention spolu s prikladmi a dovodom preco.
////