= IGA Operation
:page-nav-title: IGA Operation
:page-display-order: 200
:sectnums:
:sectnumlevels: 3


== IGA operation

#TODO#

////
mapovanie na Gartnera - 3 az 4 - Defined and quantitatively managed

Now - IGA is up and running - not only as a technology (toto bezalo uz na zaciatku) ale je integrovana do procesov organizacie. Kazde pridelenie pristupu (v ramci manazovaneho scopu a hlbky) je viditelne v IGA. Je mozne odoberat pristupy.

.Business drivers:
	Business driver 1:
		Zvysuje sa rychlost pridelenia pristupu. Zlepsuje sa kvalita - pristup je skutocne prideleny a je to to, co uzivatel chcel.
	Business driver 2:
		Zlepsuje sa viditelnost a pokrytie - narasta scope pokrytia a viditelnost jednotlivych pristupov. Zaroven sa odoberaju pristupy.

- tentokrat to uz je kontinualne zlepsovanie. Kedy si bude moct povedat IGA owner, ze sa tie business drivery naplnili - to zavisi na jeho nastaveni cielov.


Tento krok uz nema koncovy datum. Jeho cielom je iterativne zlepsovanie fungovania IGA (technologie, procesov, zlepsovanie kvality dat). Ake presne ciele bude davat vlastnik IGA zavisi uz na nom.

V tomto kroku je mozne dalej:
- definovanie rules: Assignment of rules to organization units or autoassignments on specific roles.
- increase scope and depth. E.g.:
    * integration of new application
    * integration of new resources (TODO: linka)
    * adding new levels of access (roles for administrators/ operators)
- increasing data quality: synchronizations and reconciliations
-

----
- 		○ toto je uz nekonecny pribeh - zlepsovanie - access request, increasing scope (or even depth), upratovanie, reporting, self service
		○ Modifikacia Role modelu podla vyvoja organizacie alebo infrastruktury a pod…
			§ Upravy business roli
		○ Definovanie pravidiel: Assignment roli na organizacnu strukturu
		○ Priklady rozsirovania a prehlbovania pokrytia:
			§ integracia novych ale aj existujucich aplikacii
			§ integracia novych resourcov
			§ integracia roznych urovni pristupu (vytvorenie roli pre adminov / operatorov, …)
		○ Udrzba dat: rekonciliacia
		○ Zlepsovanie v procese Role engineeringu:
			§ zrychlovanie spracovania a zavadzanie prvkov automatizacie (pokial je to mozne).
			§ Decommisioning roli a aplikacii.
			§ Aktualizacia business roli
			§ Nahradzanie manualne provisionovanych pristupov automatickym
		○ Zlepsovanie v procese Access requestu:
			§ Zrychlovanie schvalovania a spracovania, osetrovanie chyb
			§ Analyza requestov a definovanie pravidiel alebo vytvaranie business roli
			§ Integrovanie inych bodov pre access request v organizacii do centralneho.
		○ Zlepsovanie v procese Access certification:
			§ Ad-hoc certifikacne kampane
			§ Schedulovane certifikacne kampane

// Now - process optimization, increase of scope, adding other IGA capabilities, ...

////
