= IGA Deployment Methodology
:page-nav-title: Deployment Methodology
:page-display-order: 500
:toc:
:toclevels: 3
:sectnums:
:sectnumlevels: 3
:page-visibility: hidden

WARNING: This page is a work in progress.

This IGA deployment methodology is rather high level description how to go forward than detail explanation of each step.

== How

Typical IGA deployment will not start on green field. There are already some provisioning processes, some user lifecycle or even whole IDM system is running.

//This methodology expects such state and #TODO# - doplnit + odkazat sa na prerequisites

////
NOTE: Toto je odporucana metodika, ale v kazdej organziacii sa moze zmenit. Dokonca v ramci implementacie mozete vykonat male casti krokov skor ako ine (napr. update business roli pred self servicom a pod.).

NOTE: Assignment roly sa chapeme tak, ze clovek ma tento pristup prideleny. To, ci ho ma aj v skutocnosti, je vec synchronizacie a rekonciliacie.
TODO - toto mozno na ine miesto.
////

=== Business drivers

IGA deployment and implementation requires significant amount of communication and manual work. It will modify the daily life of organization and results will not come the next day.
Such large task needs some good business reason to be performed. And there are at least two of them.

*Business performance: Easier and faster provisioning of access.* People in organizations often struggle to get access to an application. It can take even weeks in some applications which directly affects delivery of new projects and organization performance.

Good IGA implementation may decrease this lead time from weeks to hours or even minutes.

*Security & Compliance: Good control over user access.* Having good control over user access is one of main goals in information security. And real organizations are quite away from achieving this goal.
Security managers struggle to get user access under control and know who has access where and why.

Furthermore, good technical description of application roles enables easy deprovisioning of user access. The word easy means that the unexpected errors caused by removal of entitlement can be minimized.
When such errors are minimized, security managers have easier life pushing people to remove unnecessary access. Especially when people know that creating access is easy and fast.


=== Responsibilities

IGA should not be responsible for registration of application or users. It may be case for some specific sets, but normally, the lifecycle of these objects should be managed by other systems and read to IGA. Users are typically managed in HR systems, application in an application inventory.

*IGA is responsible for definition and management of relations between users and applications - in the form of roles and their assignments.* But, as IGA is seldom build on green field, even the roles may be read from external systems for some sets of applications.



////
	- Externe zodpovednosti / zdroje (external data sources & external responsibilities)
		○ Identities
		○ Applications

	- Zodpovednost IGA:
		○ Vytvorit a manazovat roly
			(trochu definicie, co to znamena  <sposob pristupu do aplikacie - nejaka abstrakcia pristupoveho prava> - tuto spomenut co je rola.)
			§ co sa priraduje
			§ napojit roly na aplikacie (role model)
		○ Nacitat/Vytvorit a manazovat assignmenty
			§ vysledok - kto, co ma (user-> rola -> aplikacia) = kto ma kam pristup
////

== The IGA Deployment

#TODO#
// iterativny pristup s postupnym zlepsovanim.
// Ale niektore veci je potrebne urobit na zaciatku. Nasledne sa inicializuju procesy a potom uz bezime iterativne s postupnym zlepsovanim.
// midPoint musi byt integrovany do vnutrofiremnych procesov. - toto je klucom. Nie len technologia, ale aj procesy. A prepojenie business vrstvy s technologickou. Toto je treba mat stale na pamati.

=== Prerequisites

#TODO#
////
	<tuto sa odkazat na ukoncenie first steps - mame uz resources, mame userov, ale nemame roly>
	Upozornenie: aplikacia nie je resource -> odkaz na koncept aplikacie.

    Technology is runing: Ze mame nainstalovany midPoint ako IGA platformu - a vykonava provisioning.

???Prior deployment, the engineer should identify and describe the authoritative sources of each set of users and how these users will be loaded to IGA.

////

=== Initial steps

#TODO#
////
 na co budu tieto kroky dobre

 co bude po vykonani prac:
	V tomto bode mame vytvoreny zakladny role model, cast aplikacii je v IGA a ma vytvorene roly, ktore su assignovane ludom. Uz to nie je len teoreticke cvicenie, ale ma realne priklady, na ktorych sa daju ludom ukazat pristupy a je mozne zapojit sa do vnutrofiremnych procesov. Stale staticky stav z pohladu aplikacii (nepridavame nove aplikacie, nereagujeme na ich updaty).

	Business driver: Vieme povedat informaciu: kto ma kam pristup.
		Avsak iba na velmi obmedzenom scope aplikacii (iba na tom, co bolo doteraz pripojene a spracovane).


////

==== Initial Role model design

#TODO#
////
		○ Tuto len, ze potrebujem si definovat scope and depth (ake aplikacie chcem manazovat a aku uroven opravneni v nich. Ten scope sa moze vyvijat v case)
			§ Scope: na uvod idem manazovat iba interne aplikacie z vyvoja oddelenia XYZ, ktore prostredia (PROD/DEVEL/ACCEPTANCE)
			§ Depth: Urcit, co vsetko ma byt na uvod viditelne v IGA a co napriklad bude viditelne inde (e.g. administrators access - in PAM system) alebo vobec
		○ Scope alebo depth mozu prebiehat vyvojom v case - postupne sa moze rozsirovat

----
uto lepsie popisat, aka je prerequisita (ze maju nacitane entitlementy v MP). Ak nie su nacitane entitlementy v MP
	- ze musime nacitat grupy ako aplikacne roly (nejako ich vytvorit).

Role model priklad - co by teraz malo byt spravene.
	- na priklade ukazat co a ako (trochu aj v MP).


tuto aj info, ze su to len aplikacne roly. Zatial by sme neriesili business roly

load entilementov ako <technickych roli> - a tie sa budu postupne transformovat na aplikacne roly.

	- toto poskytne info: USer ma pristup do <tychto aplikacii> a este ma tychto N <technickych roli>

naliatie noveho resourcu:
	- natiahneme entitlementy ako technicke roly a potom ich transformujeme na aplikacne roly.

////

==== Integrate applications

#TODO#
////
		○ What is application (a ako ju napojit na objekty v organizacii)
		○ Vytvorenie roli pre malu/zakladnu cast aplikacii (pokryt rolami cast/vsetky existujuce entitlementy v IAM systeme) - alebo napojit existujuce app roly s aplikaciami

////

==== Initial update of assignments

#TODO#
////
		○ transformacia existujucich technickych roli na aplikacne roly, ktore boli vytvorene v predchadzajucom kroku. Vytvorenie (a zobrazenie) userovho accessu (user -> app rola -> aplikacia). Na existujucej mnozine entitlementov.
		○ identification rules for automatic assignments - transformation to role assignments.

////

=== Start of processes

#TODO#
////

PO dokonceni budeme mat:
	V tomto bode uz v organizacii bezi pridelovanie pristupu cez IGA, kazdy takto prideleny pristup je viditelny v IGA a je reportovatelny. Self service bezi, bezi aj vytvaranie roli. Stavy dat aj procesov sa daju merat.

	Teraz mozeme Nastavit/ziadat, aby vsetky nove aplikacie boli v ALM procese integovane s IGA solution (aby boli zaradene a vytvorene pre ne roly).

	Toto obdobie moze trvat par tyzdnov az par mesiacov. Do 1 roka max.

	Business driver 1:
		Existuje priestor pre pridelovanie pristupov a spracovanie a evidenciu.
	Business driver 2:
		Vieme zobrazit kto ma kam pristup - postupne pokryvanie.

////

==== Start Access Request process

#TODO#
////
		○ Klucovy business driver - ludia budu mat bod, ktory umoznuje rychle a prehladne pridelenie pristupu.
		○ Dobry manazment procesu - rychle pridelenie pristupov.
			§ Efektivne schvalovanie - nie vela schvalivatelov

////

==== Start Role Engineering process

#TODO#
////
		○ Dizajn a rozbehnutie procesu  (zaciatok papierovo)
			§ Aplikacne roly
			§ business roly
		○ Integracia provisioningu s ITSM (pre manualny provisioning).

////

==== Initial tuning of processes

#TODO#
////
		○ zrychlovanie access requestu
		○ zrychlovanie role engineeringu & zlepsovanie kvality roli (konzistencia across apps)
		○ zlepsit pokrytie rolami (bulk vytvorenie roli z dat, ktore ma MP).
		○ reporty

////

==== Start Access Certification process

#TODO#
////
a. po kratkom case optimalizacie (mozno by som to mohol dat este vyssie) spustit UI pre tento proces - umoznit na business vrstve prehliadanie roli a ich certifikaciu.
b. na zaciatku len umoznit ad hoc vidiet roly podriadenych jednotlivcov a odoberat ich.
c. az neskor kampane
////

=== IGA operation

#TODO#

////
mapovanie na Gartnera - 3 az 4 - Defined and quantitatively managed

Now - IGA is up and running - not only as a technology (toto bezalo uz na zaciatku) ale je integrovana do procesov organizacie. Kazde pridelenie pristupu (v ramci manazovaneho scopu a hlbky) je viditelne v IGA. Je mozne odoberat pristupy.

.Business drivers:
	Business driver 1:
		Zvysuje sa rychlost pridelenia pristupu. Zlepsuje sa kvalita - pristup je skutocne prideleny a je to to, co uzivatel chcel.
	Business driver 2:
		Zlepsuje sa viditelnost a pokrytie - narasta scope pokrytia a viditelnost jednotlivych pristupov. Zaroven sa odoberaju pristupy.

- tentokrat to uz je kontinualne zlepsovanie. Kedy si bude moct povedat IGA owner, ze sa tie business drivery naplnili - to zavisi na jeho nastaveni cielov.


Tento krok uz nema koncovy datum. Jeho cielom je iterativne zlepsovanie fungovania IGA (technologie, procesov, zlepsovanie kvality dat). Ake presne ciele bude davat vlastnik IGA zavisi uz na nom.

V tomto kroku je mozne dalej:
- definovanie rules: Assignment of rules to organization units or autoassignments on specific roles.
- increase scope and depth. E.g.:
    * integration of new application
    * integration of new resources (TODO: linka)
    * adding new levels of access (roles for administrators/ operators)
- increasing data quality: synchronizations and reconciliations
-

----
- 		○ toto je uz nekonecny pribeh - zlepsovanie - access request, increasing scope (or even depth), upratovanie, reporting, self service
		○ Modifikacia Role modelu podla vyvoja organizacie alebo infrastruktury a pod…
			§ Upravy business roli
		○ Definovanie pravidiel: Assignment roli na organizacnu strukturu
		○ Priklady rozsirovania a prehlbovania pokrytia:
			§ integracia novych ale aj existujucich aplikacii
			§ integracia novych resourcov
			§ integracia roznych urovni pristupu (vytvorenie roli pre adminov / operatorov, …)
		○ Udrzba dat: rekonciliacia
		○ Zlepsovanie v procese Role engineeringu:
			§ zrychlovanie spracovania a zavadzanie prvkov automatizacie (pokial je to mozne).
			§ Decommisioning roli a aplikacii.
			§ Aktualizacia business roli
			§ Nahradzanie manualne provisionovanych pristupov automatickym
		○ Zlepsovanie v procese Access requestu:
			§ Zrychlovanie schvalovania a spracovania, osetrovanie chyb
			§ Analyza requestov a definovanie pravidiel alebo vytvaranie business roli
			§ Integrovanie inych bodov pre access request v organizacii do centralneho.
		○ Zlepsovanie v procese Access certification:
			§ Ad-hoc certifikacne kampane
			§ Schedulovane certifikacne kampane

// Now - process optimization, increase of scope, adding other IGA capabilities, ...

////

== Additional notes

=== Reporting

#TODO#
////
Sem, ze ake zakladne reporty by sa mali robit - alebo pripadne to dame ako linku na use-cases

	- Zakladne reporty:
		○ Kto ma pristup kam a preco
		○ Role model
	- Priebezne vytvarat reporty, ktore budu popisovat jednotlive stavy, procesy. Zlepsovat, optimalizovat.

a este info, ze reporty umoznuju merat procesy a kvalitu dat - cize umoznuju predavat vysledky v IGA
////


=== Integration with manual provisioning

#TODO#
////
	- Existujuce ITSM systemy su dizajnovane na sprocesovanie poziadavky, nie vsak na popisanie accessu -> to musime zabezpecit v IGA.
	- Mozeme zaintegrovat tak, ze vytvorenie poziadavky, ktora prebiehala cez ITSM vykona IGA a zaroven po uzavreti ulohy oznaci pristup ako prideleny.
Integracia manualneho provisioningu zabezpeci prepojenie manualnej ulohy s danym assignmentom, takze bude zabezpecena evidencia, kto ma aky pristup (samozrejme nie na 100%, toto budu musiet zabezpecit dalsie kontrolne mechanizmy).

////