= IGA Deployment - technical description
:page-nav-title: Deployment - technical concepts
:page-display-order: 100
:sectnums:
:sectnumlevels: 3
:page-visibility: hidden

WARNING: This page is a work in progress.

////
< povedat o com je dokument: ze popisuje zhruba, ako technicky vykonat niektore operacie pri deploymente a implementacii IGA v organizacii..

Tu popisat technicke koncepty, ktore sa pouziju v jednotlivych krokoch v metodologii
////

== Technical roles

////
tuto aj technicke roly a aplikacne roly -> co rozumieme pod technickou rolou.
- ze to bude rola so specifickym archetypom. Znamena, ze bola nacitana, avsak nevieme este jej business interpretaciu. Minimalne nevieme jej naviazanie na aplikaciu.

////


== Role model - example

#TODO#

////
////

== Naming conventions

#TODO#

////
prevziat z dokumentu
////

== Load of entitlements

#TODO#

////
- ze natiahneme <rekonciliaciou> z resourcu
TODO: co si nastavim a zhruba ako - jednou/dvomi vetami.
////

== Integration of new resource

#TODO#
////
- priklad - napr. LDAP system s dalsim setom manazovanych roli.
- ze to prinasa pridelenie systemu
- vytvorenie business roli - alebo len technickych roli
////

== How to build application role out of technical role

#TODO#
////
- ked ziska role manager alebo IGA admin informacie potrebne pre postavenie roly, tak vie nacitat tieto roly z
- ze prepnem archetypu technickej roly na aplikacnu rolu - to bude znamenat, ze uzivatel ma dane pristupy
////
