= Try AI in midPoint: midPilot connector generator
:page-nav-title: Try AI in midPoint
:page-display-order: 400
:page-liquid:
:toclevels: 2
:page-upkeep-status: green
:page-keywords: connector generator, generator, identity connectors, connectors, ai, midpilot, llm
:page-experimental: true

== Introduction

Identity projects often stall not on business logic, but on the tedious work of building and maintaining custom connectors for every target system.
MidPoint's midPilot connector generator tackles this by using API documentation and AI‑assisted analysis to produce ready‑to‑use identity connectors with far less manual effort.

This section walks you through setting up the midPilot connector generator microservice using Docker Compose and running it alongside a local midPoint instance on your workstation.

By the end, you will have a working development environment with midPilot’s connector generator accessible on a local URL and midPoint running in a separate container.
This guide assumes you are comfortable with Docker and Docker Compose, have basic familiarity with midPoint, and can run commands from a terminal on Linux, macOS, or WSL.

++++
{% children style: table %}
++++

IMPORTANT: This functionality is experimental, the midPilot connector generator and its components are still under development, some concepts may change. Note that you may encounter bugs.


== Additional Links

* link:https://github.com/Evolveum/midpoint-samples/tree/master/samples[Midpoint samples]
* link:https://github.com/Evolveum/midpilot-connector-gen/tree/main[Connector generator]
* link:https://github.com/Evolveum/connector-scimrest[Scimrest framework]