= Related Projects
:page-wiki-name: MidPoint-Related Projects

MidPoint is a comprehensive identity management and governance system.
It is also a platform that can be customized, build on and integrated with surrounding world.
Therefore, it is no big surprise that there are midPoint-related projects that are not directly affiliated with midPoint project (or Evolveum).
This page is an attempt to list all such projects that can be interesting for midPoint community:

|====
| Name | URL | Description

| MidPoint Active Directory live password agent
| https://github.com/Identicum/midPointADPasswordAgent[midPointADPasswordAgent (github)]
| Password agent for Active Directory.
The agent will capture password changes in Active Directory and send them to midPoint for processing.

| MidPoint CLI (Python)
| https://gitlab.com/alcibiade/midpoint-cli[midpoint-cli (gitlab)]
| Command-line interface (CLI) for midPoint written in Python.
See link:midpoint-cli-python/[Midpoint-CLI in Python]
|====

These are independent projects that are not maintained or governed by Evolveum. Their have their own maintainer and their own governance. In case of any questions please contact the original authors.

There are also third-party connectors that work with midPoint.
Please see the https://wiki.evolveum.com/display/midPoint/Identity+Connectors[list of identity connectors] for details.

== See Also

* link:/community/[MidPoint community]
* https://wiki.evolveum.com/display/midPoint/Participation[Participation (wiki)]
* https://wiki.evolveum.com/display/midPoint/Identity+Connectors[Identity Connectors (wiki)]
