= MidPoint CLI in Python
:page-nav-title: Python CLI
:page-wiki-name: Midpoint-CLI in Python
:page-alias: { "parent" : "/midpoint/tools/", "display-order" : 900 }

.Independent project
NOTE: MidPoint CLI in Python is an independent (third-party) project.
The project was independently started by Yannick Kirschhoffer.
This project is not maintained by the Evolveum team.
However, we find this project very useful and we are very grateful for its existence.
It is almost certain we will help to maintain the project by contributing code if needed.

== Introduction

A command line client to Midpoint Identity Management system.
Source code is located on https://gitlab.com/alcibiade/midpoint-cli.

== Installation

TIP: Steps below were tested on ubuntu 18.04.

. As the first step, install python3-pip.

    sudo apt install -y python3-pip

. Next, clone the git project from GitLab.

    git clone https://gitlab.com/alcibiade/midpoint-cli.git

. Use pip3 to install package.

    cd midpoint-cli/midpoint_cli/
    pip3 install midpoint-cli

. Final step is starting package midpoint-cli.

    python3 midpoint-cli

== Arguments

The following arguments can be used during startup, for example `python3 midpoint-cli -U http://localhost:8080/`.

|====
| Tag | Description | Default value


|`-v`, `--version`
|Show version information
|

|`-u`, `--username`
|Set the username to authenticate this session.
|`administrator`

|`-p`, `--password`
|Set the password to authenticate this session.
|`5ecr3t`

|`-U`, `--url`
|Midpoint base URL.
|`http://localhost/`

|_command_
|Optional command to be executed immediately.
|

|_arg_
|Optional command arguments.
|
|====

Available commands:

`get`::
Get an XML definition from the server from an existing OID reference.

`put`::
Create/Update a server object based on an XML structure.

`delete`::
Delete a server object based on its type and OID.

`task`::
Manage server tasks.

`resource`::
Manage resources on the server.

`org`::
Manage organizations.

`user`::
Manage users.

If you don't know how to use command, you can use help.
We can also use help in conjunction with the command, for example help user.

== See Also

* link:../[MidPoint-related projects]
