---
layout: connector-page
display-order: 200
functionality-status: limited
development-status: dormant
support-status: supportable
origin: Evolveum
support-provided-by: Evolveum
target-systems: Oracle PeopleSoft Human Capital Management (HCM)
connector-protocol: Local file I/O
source-url-master: https://github.com/Evolveum/connector-smartrecruiters
description: Identity connector for Oracle PeopleSoft Human Capital Management (HCM).
connid-bundle-name: com.evolveum.polygon.hcm
upkeep-status: yellow
---
= PeopleSoft HCM connector
:page-wiki-name: PeopleSoft HCM connector
:page-wiki-metadata-create-user: mmacik
:page-wiki-metadata-create-date: 2017-04-24T10:45:51.942+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-07-09T14:32:12.678+02:00

A connector which is meant to provide identity information by reading the XML files exported from the Oracle PeopleSoft Human Capital Management (HCM) software. These files are viewed as individual resources which are connected to midpoint.

== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| *Provisioning*
| YES
|

| *Live Synchronization*
| NO
|

| *Password*
| NO
|

| *Activation*
| NO
|

| *Paging support*
| NO
|

| *Native attribute names*
| YES
|

| *Scripting*
| NO
|

|===


== History

[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | ConnId Framework | Description

| *1.4.2.2*
| *Polygon*
| http://nexus.evolveum.com/nexus/content/repositories/releases/com/evolveum/polygon/hcm/connector-hcm/1.4.2.2/connector-hcm-1.4.2.2.jar[download jar]
| https://github.com/Evolveum/connector-peoplesoft-hcm[GitHub]
| *April 2017*
| *1.4.2.18*
| *Official release*

|===

== Licensing

The connector itself is available under the terms of Apache License 2.0. To our best knowledge there is no extra license needed to use this connector. (Additional  licensing terms and conditions may apply with services on which the connector is used).

== Configuration

The basic parameters which are present in the configuration dialogue window are the following:

* File path: The path to a XML resource file from the HCM resource. (e.g. ../hcm.xml)

* Parser iterations: The number of employee records the parser iterates trough. This action is needed to generate the resource schema. The higher the number of iterations the higher the possibility that the schema will be complete.

* Unique identifier name: The UID name of the user account attribute. Please select an identifier which is unique for each employee.

* Name attribute: The secondary identifier attribute.


== Setting up tests

A predefined set of test resources is present in the source bundle which can be found at our git repository. Additionally the tests can be modified via the test.properties file which contains the basic test properties which are the following:

* filepath_xmlconsistent: Contains the path to a (valid) consistent xml resource which simulates the provided xml containing no flaws.

* uid: The name of the unique identificator attribute.

* secondaryid: The name of the Name attribute.

* iterationcount: Number of iterations which the parser is permitted to execute for successful schema generation. If the number is higher than the actual number of identities present in the xml file than the number of iteration will be equal to the number of identities.

* secondaryid_missing: Name of a secondary attribute which can be potentially non mandatory in the source system but which will be marked mandatory in midpoint. This will end up in an exception.

* filepath_xmlinconsistent: A path to an XML resource file containing indentities but which is (non valid) inconsistent.

* filepath_filenotfound: A non valid path to an XML resource file.

* filter_equals_attr: Name of the attribute which will be used for an equals filter test.

* filter_equals_value: The value used in the equals filter test.

* filter_contains_attr:  Name of the attribute which will be used for an contains filter test.

* filter_contains_value:  The value used in the equals filter test.

* query_options_option: Name of the query option which will be used in a query.

*  query_options_value: Value which will be used in the query option.