---
release-version: '3.C'
---
= MidPoint 3.C "Cimrman"
:page-layout: release-skeleton
:release-version: 3.C
:page-wiki-name: Release 3.C
:page-wiki-id: 24085679
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2017-03-31T21:34:40.116+02:00
:page-wiki-metadata-modify-user: vera
:page-wiki-metadata-modify-date: 2018-01-29T16:15:23.634+01:00
:page-liquid:

Release {release-version} is a nineteenth midPoint release code-named _Cimrman_.
The {release-version} release brings revolutionary features that support the Internet of People (IoP) concepts in the home environment.

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
    <a href="https://en.wikipedia.org/wiki/J%C3%A1ra_Cimrman">Jára Cimrman</a> was a Czech universal genius.
    He was the greatest Czech that ever lived.
    Cimrman contributions to science, technology, culture, sport and almost any other field cannot be overstated.
    Cimrman <a href="https://www.youtube.com/watch?v=eNDEEEy7Qzo">inspired</a> many of his contemporaries including Guglielmo Marconi, Gustave Eiffel, Johann Strauss, A.P. Checkov, Marie Currie, Dmitri Mendeleev and many others.
    The world would be a very different place without Cimrman.
    Cimrman was <a href="https://www.youtube.com/watch?v=YXuWSH-U_-o">almost successful inventor</a>.
    He almost invented telephone, kinematograph, electric fuse, light bulb, battery, dynamo, electric meter, dynamite and many other inventions.
    He has pioneered the <a href="https://en.wikipedia.org/wiki/J%C3%A1ra_Cimrman#Contributions">principles of the Internet</a>, introduced concept of magnetic monopole and invented bikini swimsuit.
    He was almost the first human that reached the north pole, missing it only by seven meters.
    As a recognition of his lifetime of achievement he won the voting in the 2005 Greatest Czech contest.
</p>
<p>
    The genius of Cimrman inspired the development of midPoint 3.C.
    Especially the Cimrman's invention of the Internet was a direct inspiration for the revolutionary features of midPoint 3.C which is entirely based on the Internet of People idea.
    Internet of People (IoP) concept is based on observation that too many people are almost inseparable from their on-line devices.
    Therefore these people can be considered to be efficiently Internet-connected and they can managed using methods that are very similar to methods used for management of "things".
    The IoP concept has a very broad area of application ranging from small-scale family environments to a large-scale automated provisioning of political ideologies.
    We believe that Cimrman himself would embrace this idea. And it is possible that the IoP concept may in fact be invented by Cimrman - a fact that the leading Cimrmanologists will surely explore in depth.
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

== Credits

Majority of the work on the _Cimrman_ release was done by the https://www.evolveum.com/[Evolveum] team.
However, this release would not be possible without the help of our partners, customers, contributors, friends and families.
We would like to express a great gratitude to all the people that contributed to the midPoint project.

We would also like to thank all the Cimrmanologists of all nations.
Without them we would lack a great deal of inspiration that made this release possible.


== Features

MidPoint 3.C supports all imaginary, fictional and unreal features imaginable.
There are too many features to list.


== Changes With Respect to Version 3.5

* Change of versioning scheme.
The version numbers are too dull for expressing the excellence of this midPoint version.

* Change of color scheme to mark the importance of midPoint 3.C.

* Pre-configured objects and roles to support the IoP concept in home environment.
MidPoint 3.C is ready for IoP deployments out-of-the-box.

All serious, sober, real and down-to-the-earth features are deprecated and they are no longer supported.

== Quality

The quality of midPoint 3.C is as real as Jra Cimrman himself.
As master Cimrman excelled in so many fields, we have no doubt that we was also great quality assurance engineer.
Therefore we have relied on the fact that the spirit of Cimrman made all the product defects just disappear.
No explicit testing has been done because we feel that testing may be seen as disregard for the power of master's spirit.


=== Limitations

MidPoint 3.C is limited only by user's imagination.


== Platforms

MidPoint works in the following environments:

* Java 8

* Old circus tent with a telephone


++++
{% include release-download.html %}
++++


== Upgrade

No need to upgrade.
MidPoint 3.C is so revolutionary that it will overthrow any previous installation of any software, hardware, firmware or anything else.


== Known Issues

MidPoint 3.C does not have any known issues - except for all the issues that it already has.


== See Also

* xref:/midpoint/history/[midPoint History]

* xref:index.adoc[]
