= Missing IGA Features
:page-nav-title: Missing Features
:page-display-order: 900
:page-toc: top

This is somehow unstructured, unprioritized and very unofficial list of IGA features that are missing in midPoint.
It is more in a form of design notes.
There is no promise that any of these features will be developed.
That has to be decided yet.

== Expression Profiles

*Problem*: Expressions are foundation of midPoint flexibility.
It is pretty much certain that role engineers will need to use expressions in roles.
However, allowing use of expressions in current midPoint means quite literally to give up the keys to the kingdom.
In IGA, role engineers will *not* be almighty system administrator.
This task will be delegated.
Expressions need to be safe.

*Solution*: finish expression profiles, apply them consistently to all types and kinds of expressions in the system.
Pre-configure reasonable expression profiles to choose from (initial objects).

== Concept of Application

TODO

== Differential Resources

*Problem*: Indirect provisioning.
We are provisioning to resource `X`.
However, the accounts end up in resources `A` and `B` in the end, mostly due to complicated legacy stuff.
We have read-write access to `X`, we have read-only access to `A` and `B`.
We want to make sure that all accounts were correctly provisioned to `A` and `B`.
More importantly, we want to check for orphaned accounts in `A` and `B`.
We want to make all kinds of reports about differences between `X` and `A`/`B`.

*Solution ideas*:

* Create "dual-legged" roles.
One leg will provision in `X`, the other leg will _check_ accounts in `A`/`B`.
We will need to create a completely new _comparison_ mechanism or mode for assignments/inducements.

* Should we create "dual resources", resources that are somehow bound together?

* Could be use (provisioning) dependencies?
We will need to extend the dependencies to support comparison, and extend reporting.

* Could we use policy rules?
E.g. a rule specifying that if an account exists in `A`, then related account should also exist in `X` (or vice versa).

*Thoughts*: There will be a time delay problem.
The account will appear in `A`/`B` some time aftet it was created in `X`.
This may be quite a long delays (hours/days).
Could we re-use the mechanism that we have developed for semi-manual resources?

== Relation As Role Parameter

See xref:role-engineering/parametric-access/[]

== Relation Display Name In assignmentRelation

*Problem*: The term _relation_ is very generic, it does not tell people much about its meaning.

*Solution*: We can specify "display name" for the relation in `assignmentRelation` part of archetype definition.
E.g. we can change "relation" to "membership class" for project orgs.
We can change "relation" to "access level" for parametric access to application resources (see xref:role-engineering/parametric-access/[]).

This would be step towards midPoint speaking more business-like language.

*Thoughts*: Do we need also to change display names of relation values?
E.g. do we want to display something else than "Owner" for `owner` relation?

== Shadow Marking

TODO

Marks for protected, decomissioning and remediation.

See also xref:/midpoint/methodology/first-steps/solution/[]

== Role Mining

TODO

== Risk Modelling

TODO

== Risk-Based Triggers

TODO

== Collaborative Role Engineering

TODO

== Role "Refactoring" Tools

TODO: e.g. a tool to create business role from application roles,
replacing existing assignments of application roles to assignment of business role.

== Remediation

TODO

== Improved Access Request User Experience

TODO

== Improved Case Management (Approvals) User Experience

TODO

== Access Request: End-to-End Process

TODO: manage/track/record the process from selection of access, through approvals, clockwork, provisioning, all the way to the last manual ticket being closed.

== Manual Provisioning Instructions

TODO: There should be way to specify additional instructions for manual provisioning,
such as reference to a process, guide, exact sequence of steps, etc.
Such instructions should be added to the ticket for manual provisioning in ITSM.

The `objectType` definition in resource seems to be the right place to place the instructions.
Do we need instructions in role definition?
There may be additional manual steps to be done for each role (e.g. manually assign to a specific group, or add a privilege).

Maybe we need "virtual" entitlements for manual resource, that the role engineer can choose from when constructing roles?

== Entitlement (Application Role) Ownership Management

*Problem*: Who is responsible for AD group `foobar`?

TODO: Pre-configured policies


== Expression Profiles Finished

TODO: roles will be specified by non-administrator users.
Expressions in roles have to be safe.

Also: expressions in queries in GUI


== Access Request Recommenders

Recommend better roles that the user has selected.
E.g. user has selected application roles `A`, `B` and `C`.
The recmmender should (very strongly) suggest to request business role `X` instead,
as `X` is an exact combination of `A`, `B` and `C`.

The recommended could also suggest role `Y`, even though it contains `A`, `B`, `C` and `D` - as long as the additional risk introduced by `D` is low.

We need this to "motivate" (read: more-or-less _force_) users to select business roles instead of application roles.


== Risk-Based Approval Assistance

Approver should see the risk introduced by the roles that he is approving.
Also, there should be a warning in case that the overall risk posed by the user _after approval_ is above reasonable level.

Also, there should be an option to add additional approval step based on risk (in case of new roles are too risky, or cummulative risk of the user is too high).


== New Pre-Defined Objects

We need to add following new pre-defined objects (initial objects):

* System configuration:

** Reasonable set of expression profiles to choose from.
We do not want IDM admin to manually list all safe Groovy packages to use.
We have to do it.
