= IGA Reporting
:page-nav-title: IGA Reporting
:page-display-order: 500

WARNING: This page is a stub, it is a work in progress.

// Sem vsetky reporty ake by sme potrebovali

To be able to perform Identity Governance, the system must provide answers to following questions.

To provide the best form of data interpretation, the answers may be in form of reports, dashboards or object details.

.Following kinds of reports are needed:

* Big picture & Assignments reports
* Process monitoring reports

Additionally, system shall provide following information:

* business description of assignment policies
** list of the policies
** assignment counts

== Big picture & Assignments reports

.Big picture over assignments
* **Who has access where** - main IGA report - report of user assignments (roles or applications) for defined scope of users
* assignments of roles - how many assignments has each role (scope may be limited)
* assignments of applications - how many assignments has each application
* role assignments per users -  how many assignments each user has

.Per object assignments reports
* who has this role assigned
* who has access to this application
* what roles has the user assigned (directly or indirectly)
* what applications have the user access to
* user's assignment history
* reasons for the assignment - information **why** the user has the access - identification of request or policy providing the access

.What has happened in the system
For defined time period or scope, the system should provide information:

* how many users were created / modified / disabled / removed
* create / modify / delete operations per resource
* new / removed assignments

.Risk based reports
* Who are privileged users
* Users with the highest risk profile


== Role Engineering process monitoring

All the reports mentioned here should be designed for specified time period:

* New requests - how many role creation/update/decommissioning requests was created
* Process throughput - how many requests (of all requests created within the time period) were closed within e.g. 21 days.
* Process speed - how fast was e.g. 95% of the requests closed (of all requests created within specified time period)
* Closure rate - percentage of requests already closed
* Success rate - percentage of already closed requests that are closed successfully
* Requests with excessive processing times - all opened requests not closed within e.g. 60 days.

== Access request process monitoring

All the reports mentioned here should be designed for specified time period:

* New requests - how many role creation/update/decommissioning requests was created
* Process throughput - how many requests (of all requests created within the time period) were closed within e.g. 7 days.
* Process speed - how fast was e.g. 95% of the requests closed (of all requests created within specified time period)
* Closure rate - percentage of requests already closed
* Success rate - percentage of already closed requests that are closed successfully
* Requests with excessive processing times - all opened requests not closed within e.g. 21 days.
* Requests per applications - to identify users / organization units utilizing the system - hints for including application roles to business role
* Requests per users / organizations - to identify users / organization units utilizing the system - hints for business role preparation