= FAQ, issues during upgrade

WARNING: THIS PAGE IS WORK IN PROGRESS

This document is a collection of frequently asked questions and answers about the upgrade process.
It is intended to help you to solve problems that may occur during the upgrade process.

== Known issue's and solution



. midPoint failed to start after upgrade
    .. error message in log:

    2023-09-27 10:13:49,234 [] [main] ERROR (org.springframework.boot.SpringApplication): Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server
...
ERROR initializing midPoint: org.springframework.context.ApplicationContextException: Unable to start web server
ROOT cause: com.evolveum.midpoint.util.exception.SystemException: Can't initialize sqale repository context, database schema version (23) doesn't match expected value (24) for label 'schemaChangeNumber'. Seems like mismatch between midPoint executable version and DB schema version. Maybe DB schema was not up...
See midpoint.log for more details.

    .. explain

    Upgrade process was incomplete, or repository tables was not correctly upgraded.

    .. solution

     Run sql upgrade scripts from distribution package, please use related documentation to do it.

* xref:* xref:/midpoint/reference/deployment/ninja/upgrade-with-ninja/[Upgrade DB schema]
[Database Schema Upgrade]

