= Deprecated items
:page-since: 4.8
:page-toc: top

Following table lists deprecated elements and types that currently exist in midPoint XSD schemas.
Table data from upgrade fields will be used as input for xref:/midpoint/devel/design/upgrade-process-4.8/design.adoc[upgrade process].

.Deprecated items
[%header,cols=13]
|===
| File
| Element owner
| Element name
| Element type
| Planned removal
| Notes
| Automatic migration ideas
| Responsible
| Schema change identifier
| Upgrade phase
| Upgrade type
| Upgrade priority
| Analysis done (Prepared for implementation. Yes/No)

| capabilities-3.xsd
| CapabilityCollectionType
| addRemoveAttributeValues
| AddRemoveAttributeValuesCapabilityType
|
| Removed.

Deprecated in 4.0 by https://github.com/Evolveum/midpoint/commit/fab755d8[fab755d8].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/8038b70f[8038b70f].

The element was replaced by `addRemoveAttributeValues` property of `update` capability.

|
For configured capabilities, the `update` capability has to be modified according to the `addRemoveAttributeValues` content.

For native capabilities, the situation is most probably OK (as the old-style capability stopped to be produced in 4.0), but for sure, one should refresh the capabilities.
Or, the migration tool can do the same operation as for configured capabilities.

| Pavol
|
| Before upgrade
| Automatic if implemented.
| Critical
| Analyzed and removed from the schema. Done.

| common-case-management-3.xsd
| CaseType
| taskRef
| tns:ObjectReferenceType
|
| Removed (not used anymore).

This item was used to bind approval cases and their execution tasks.
It was maintained by midPoint only, never set manually.
It is no longer used.
So, it was now simply dropped from the schema, without any replacement.

Introduced in 4.0.
Marked as deprecated in 4.0.3/4.1.
See https://github.com/Evolveum/midpoint/commit/e1b6fb81c18dec045605cc2a511c6d8e47f9cb33[e1b6fb81].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/861b6d9a[861b6d9a].

| Any data in that item can be safely discarded.
| Pavol
|
| N/A
| Automatic.
| N/A
| Analyzed and removed from the schema. Done.

| common-core-3.xsd
| OtherPrivilegesLimitationType
| approvalWorkItems
| c:WorkItemSelectorType
|
| #TODO resolve#

Used to limit delegated privileges related to approval work items.
In both 4.4 and 4.7, it is incorrectly used in the code:
Although only `caseManagementWorkItems` should be used, both `caseManagementWorkItems` and `approvalWorkItems` are used by mistake.
This needs to be resolved somehow.

Introduced in 3.6.
Marked as deprecated in 4.0 by https://github.com/Evolveum/midpoint/commit/6326a7cbb6014835680e6c01c599c28810cb0c88[6326a7cb].
| #To be analyzed.#
| Pavol
|
| #To be analyzed.#
| #To be analyzed.#
| #To be analyzed.#
|

| common-core-3.xsd
| ReportDataType
| data
| xsd:string
|
| Full data of the report.

Still needed, so I un-deprecated it.
| N/A
| Pavol
|
| N/A
| N/A
| N/A
|

| common-core-3.xsd
|
| defaultAssignmentConstraints
| tns:AssignmentConstraintsType
| 4.8
| It was deprecated with new request access UI. #Is this still needed?# There's currently no replacement for this?
|
| Vilo
|
|
|
|
|

| common-core-3.xsd
|
| defaultCollection
| tns:ObjectCollectionUseType
| 4.8
| Configuration was moved to adminGuiConfiguration/accessRequest/roleCatalog. Eg. `systemConfiguration/roleManagement/defaultCollection/collectionUri` ->
`systemConfiguration/adminGuiConfiguration/accessRequest/roleCatalog/collection/identifier`
|
| Vilo
|
|
|
|
|

| common-core-3.xsd
| CleanupPoliciesType
| objectResults
| tns:CleanupPolicyType
|
| Removed.

Deprecated in 4.3 by https://github.com/Evolveum/midpoint/commit/26044356[26044356].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/df9d41d4[df9d41d4].

The value of `objectResults` served as a default for both `simpleOperationExecutions` and `complexOperationExecutions`.
See https://github.com/Evolveum/midpoint/blob/master/repo/repo-common/src/main/java/com/evolveum/midpoint/repo/common/util/OperationExecutionWriter.java#L289-L304[the code].

|
Take the value.
If `simpleOperationExecutions` is not specified, set it to the value.
If `complexOperationExecutions` is not specified, set it to the value.
| Pavol
|
| Before upgrade
| Automatic if implemented.
| Not critical.

If not done, the information will disappear and system-wide default value of keeping 5 records is applied.
See https://github.com/Evolveum/midpoint/blob/master/repo/repo-common/src/main/java/com/evolveum/midpoint/repo/common/util/OperationExecutionWriter.java#L325-L334[the code].
| Yes

| common-core-3.xsd
|
| oidBound
| xsd:boolean
|
| This property was introduced in 2014 by https://github.com/Evolveum/midpoint/commit/2d71af12[2d71af12].
It was marked as deprecated in that very commit.
The discussion with Radovan revealed that this is just a workaround for not knowing focus OID when mappings are evaluated.
(For new objects, i.e. `ADD` operations.)
The serious solution would be to generate OID before the operation, so that it could be used in the mappings.

See bug:MID-8867[].
#Will we do this in 4.8?#
| No automation possible.
| Pavol
|
| N/A
| N/A
| N/A
| Probably will not be removed now.

| common-core-3.xsd
| ArchetypePolicyType
| propertyConstraint
| tns:ItemConstraintType
|
| Removed.

Deprecated in 4.1 by https://github.com/Evolveum/midpoint/commit/940c62e6[940c62e6].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/551ab3fd[551ab3fd].

| Take all values of `propertyConstraint` and add them to (multivalued) `itemConstraint`.
| Pavol
|
| Before upgrade
| Automatic if implemented.
| May be critical.
If not done, that part of configuration will disappear.
|

| common-core-3.xsd
| ModelExecuteOptionsType
| reconcileAffected
| xsd:boolean
|
| Removed (not used anymore).

Deprecated in 4.2 by https://github.com/Evolveum/midpoint/commit/9c6a5ba5[9c6a5ba5].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/5e83b64e[5e83b64e].

The functionality controlled by this option was removed somewhere between 4.2 and 4.4.
(It is not present in 4.4 for sure.)
Hence, the option can be safely removed from the schema.
| Not needed.
| Pavol
|
| N/A
| Automatic.
| N/A
| Analyzed and removed from the schema. Done.

| common-core-3.xsd
|
| roleCatalogCollections
| tns:ObjectCollectionsUseType
| 4.8
| Configuration was moved to adminGuiConfiguration/accessRequest/roleCatalog
|
| Kate
|
|
|
|
|

| common-core-3.xsd
|
| roleCatalogRef
| c:ObjectReferenceType
| 4.8
| Configuration was moved to adminGuiConfiguration/accessRequest/roleCatalog
|
| Kate
|
|
|
|
|

| common-core-3.xsd
|
| subtype
| xsd:string
|
| #TODO#
|
| Vilo
|
|
|
|
|

| common-core-3.xsd
| PersonaConstructionType
| targetSubtype
| xsd:string
|
| Removed.

Deprecated in 4.4 by https://github.com/Evolveum/midpoint/commit/f423dc30[f423dc30].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/9e02d004[9e02d004].

Matching of personas by `subtype` values is not supported anymore.
Any such use should be migrated to the use of archetypes.
An example of doing this (for tests) is presented in https://github.com/Evolveum/midpoint/commit/9e02d004[9e02d004].
| Not possible.
| Pavol
|
| Before upgrade
| Manual
| Critical (if the feature is used)
| Analyzed and removed from the schema. Done.

| common-correlation-3.xsd
| IdMatchCorrelatorType
| followOn
| tns:CompositeCorrelatorType
|
| Removed.

Introduced in 4.5 by https://github.com/Evolveum/midpoint/commit/107d6bbe[107d6bbe].
Deprecated in 4.6 by https://github.com/Evolveum/midpoint/commit/eb3e8dbb[eb3e8dbb].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/df69d0cb[df69d0cb].

Related to ID Match correlator.
Instead of `followOn` item, the `referenceIdProperty` should be used.
An example of doing this (for a test) is presented in https://github.com/Evolveum/midpoint/commit/df69d0cb[df69d0cb].
| Not possible.
| Pavol
|
| Before upgrade
| Manual
| Critical (if ID Match correlator is used)
| Analyzed and removed from the schema. Done.

| common-gui-3.xsd
|
| additionalPanels
| tns:GuiObjectListViewAdditionalPanelsType
|
| 4.8 - copying between classes, 4.4 - used only for member panel additionalPanels.memberPanel and we can use ContainerPanelConfigurationType.listView instead
|
| Lukas
| ContainerPanelConfigurationType.listView
|
| should be removed from the schema
|
|

| common-gui-3.xsd
|
| container
| tns:VirtualContainersSpecificationType
|
| use panel.container instead
|
| Lukas
| panel.container
|
| should be removed from the schema
|
|

| common-gui-3.xsd
|
| defaultObjectType
| xsd:QName
|
| #TODO#
|
| Kate
|
|
|
|
|

| common-gui-3.xsd
|
| defaultScope
| tns:SearchBoxScopeType
|
| #TODO#
|
| Kate
|
|
|
|
|

| common-gui-3.xsd
|
| displayName
| t:PolyStringType
|
| Located in SearchItemType. #Probably display/label should be used?#
|
| Kate
|
|
|
|
|

| common-gui-3.xsd
|
| forms
| tns:ObjectFormType
|
| Just remove this? XML update probably needed (admin gui configuration objects), copying between classes
|
| Lukas
|
|
| should be removed from the schema
|
|

| common-gui-3.xsd
|
| name
| xsd:string
| 4.8
| Used in GuiActionType, probably identifier should be used.
|
| Lukas
| identifier
|
| should be removed from the schema
|
|

| common-gui-3.xsd
|
| objectForms
| tns:ObjectFormsType
| 4.8
| This has to be moved to  objectDetails/objectDetailsPage/forms.
Located in AdminGuiConfigurationType, meaning AbstractRoleType and SystemConfigurationType has to be updated if necessary. used only for copying between classes.
|
| Lukas
| used configuration for panels
|
| should be removed from the schema
|
|

| common-gui-3.xsd
|
| userDashboard
| tns:DashboardLayoutType
| 4.8
| Use homePage configuration instead. #Can this be translated 1:1?#
|
| Kate
|
|
|
|
|

| common-gui-3.xsd
|
| userDashboardLink
| tns:RichHyperlinkType
| 4.8
| Use homePage instead. #Can this be translated 1:1?#
|
| Kate
|
|
|
|
|

| common-model-context-3.xsd
| LensProjectionContextType
| accountPasswordPolicy
| c:ValuePolicyType
|
| Removed (not used anymore).

Deprecated in 4.0 by https://github.com/Evolveum/midpoint/commit/c1088e0a[c1088e0a].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/1adf09dc[1adf09dc].

This property was maintained by midPoint and is not used for a long time.
It can be safely dropped from the schema.
| Not needed.
| Pavol
|
| N/A
| Automatic.
| N/A
| Analyzed and removed from the schema. Done.

| common-model-context-3.xsd
|
| accountPasswordPolicyRef
| c:ObjectReferenceType
|
| Removed (not used anymore).

Deprecated in 4.0 by https://github.com/Evolveum/midpoint/commit/c1088e0a[c1088e0a].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/1adf09dc[1adf09dc].

This property was maintained by midPoint and is not used for a long time.
It can be safely dropped from the schema.
| Not needed.
| Pavol
|
| N/A
| Automatic.
| N/A
| Analyzed and removed from the schema. Done.

| common-notifications-3.xsd
|
| FileConfigurationType
|
| 4.7
| MessageTransportConfigurationType/file should be used.
|
| Tony
|
|
|
|
|

| common-notifications-3.xsd
|
| LegacyCustomTransportConfigurationType
|
| 4.7
| #TODO#
|
| Tony
|
|
|
|
|

| common-notifications-3.xsd
|
| MailConfigurationType
|
| 4.7
| MessageTransportConfigurationType/mail should be used.
|
| Tony
|
|
|
|
|

| common-notifications-3.xsd
|
| NotificationTransportConfigurationType
|
| 4.7
| Use new messageTransportConfiguration instead.
|
| Tony
|
|
|
|
|

| common-notifications-3.xsd
|
| SmsConfigurationType
|
| 4.7
| MessageTransportConfigurationType/sms should be used.
|
| Tony
|
|
|
|
|

| common-notifications-3.xsd
|
| customTransport
| tns:LegacyCustomTransportConfigurationType
| 4.7
| MessageTransportConfigurationType/customTransport should be used.
|
| Tony
|
|
|
|
|

| common-notifications-3.xsd
|
| sms
| tns:SmsConfigurationType
| 4.7
| MessageTransportConfigurationType/sms should be used.
|
| Tony
|
|
|
|
|

| common-provisioning-3.xsd
| SynchronizationType
| objectSynchronization
| ObjectSynchronizationType

// NOTE: both `objectSynchronization` and `ObjectSynchronizationType` are marked as deprecated.
// This entry applies to both.

|
| In 4.6, we improved the style of configuration of the resource objects synchronization.
It was moved into `schemaHandling/objectType` definitions and modernized.
The legacy style (`synchronization/objectSynchronization`) was marked as deprecated in the same midPoint version by https://github.com/Evolveum/midpoint/commit/0a58e992[0a58e992].

To migrate, use the new format.
See https://docs.evolveum.com/midpoint/reference/resources/resource-configuration/schema-handling/changes-in-4.6/[the documentation] for more information.

// On 2023-05-25 we (Vilo, Rado, Pavol) decided to keep the legacy style available in 4.8, because otherwise there would be no migration path from 4.4.
// (The functionality was not available at that time; and the change is substantial.)
| To be analyzed (most probably quite complex).
| Pavol
|
| Before or after
| #To be analyzed#
| Optional but strongly recommended.
|

| common-provisioning-3.xsd
| ObjectSynchronizationType
| `reaction`
| LegacySynchronizationReactionType
|
2+| This is a part of deprecated `objectSynchronization` item (of `ObjectSynchronizationType`).
| Pavol
|
3+| see `objectSynchronization` above
|

| common-provisioning-3.xsd
| ResourceObjectTypeDefinitionType
| auxiliaryObjectClass
| xsd:QName
|
|
This property was moved to newly-introduced `delineation` item and deprecated (in its original place) in 4.6 by https://github.com/Evolveum/midpoint/commit/1f3cb147[1f3cb147].

Just like `objectSynchronization` item above, we decided not to remove it in 4.8.

| Move (or merge?) the values if they do not exist in `delineation`.
| Pavol
|
| Before or after
| #TBD#
| Optional but strongly recommended.
|

| common-provisioning-3.xsd
| ResourceObjectTypeDefinitionType
| baseContext
| tns:ResourceObjectReferenceType
|
|
Just like `auxiliaryObjectClass` property above, this item was moved to newly-introduced `delineation` item and deprecated (in its original place) in 4.6 by https://github.com/Evolveum/midpoint/commit/29c0a6ee[29c0a6ee].
We decided not to remove it in 4.8.

| Move the value to `delineation` (what about conflicts?)
| Pavol
|
| Before or after
| #TBD#
| Optional but strongly recommended.
|


| common-provisioning-3.xsd
|
| searchHierarchyScope
| tns:SearchHierarchyScopeType
|
|
Just like `baseContext` property above, this item was moved to newly-introduced `delineation` item and deprecated (in its original place) in 4.6 by https://github.com/Evolveum/midpoint/commit/29c0a6ee[29c0a6ee].
We decided not to remove it in 4.8.

| Move the value to `delineation` (what about conflicts?)
| Pavol
|
| Before or after
| #TBD#
| Optional but strongly recommended.
|

| common-security-3.xsd
|
| name
| xsd:string
|
| Use identifier instead.

The element of the AbstractAuthenticationModuleType.
The code was reviewed, all usages of this element were removed.

4.4 -> 4.8 : AbstractAuthenticationModuleType.identifier element should be added. The value of the name attribute is to be copied to the identifier. Then name can be removed.

4.7 -> 4.8 : In case name value exists but identifier doesn't, the same steps as for 4.4. If both values exist, just remove name value (starting from 4.7 identifier appeared and was used with a higher priority than name).
If no of these 2 elements values present, it's considered to be a wrong configuration. Identifier element is set to be mandatory.

code cleanup commit c36ef0f0
|
| Kate
|
| old mp version running (described steps should be produced)
| should be removed from schema
|
|

| common-security-3.xsd
|
| name
| xsd:string
|
| Use identifier instead.

The element of the AuthenticationSequenceType.
The code was reviewed, all usages of this element were removed.

4.4 -> 4.8 : AuthenticationSequenceType.identifier element should be added. The value of the name attribute is to be copied to the identifier. Then name can be removed.

4.7 -> 4.8 : In case name value exists but identifier doesn't, the same steps as for 4.4. If both values exist, just remove name value (starting from 4.7 identifier appeared and was used with a higher priority than name).
If no of these 2 elements values present, it's considered to be a wrong configuration. Identifier element is set to be mandatory.

code cleanup commit 8a888a0a
|
| Kate
|
| old mp version running (described steps should be produced)
| should be removed from schema
|
|

| common-security-3.xsd
|
| name
| xsd:string
|
| Use identifier instead.
|
| Kate
|
|
|
|
|

| common-security-3.xsd
|
| name
| xsd:string
| 4.8
| Use identifier instead.
|
| Kate
|
|
|
|
|

| common-tasks-3.xsd
| ActivityStateType
| workState (not deprecated)
| PureCompositeWorkStateType (deprecated)
|
| This is the work state created by custom composite activities.
It is not a configuration, but a state maintained by the activity itself.

Most of the time, it is empty, like `<workState xsi:type="c:CustomCompositeWorkStateType"/>`.

In 4.4, the type was called `PureCompositeWorkStateType`, but since 4.4.4 and 4.7, it is deprecated and replaced by `CustomCompositeWorkStateType` (see https://github.com/Evolveum/midpoint/commit/bd840722[bd840722] and https://github.com/Evolveum/midpoint/commit/6a611801[6a611801]).

If we removed the type definition, the task objects of this type will be no longer readable.
(AFAIK there is no schema migration mechanism for types.)

We could write a migration code that would swap the types, but is it worth the effort?

Note that these activities are marked experimental in the schema in `ActivityCompositionType` (but not in the docs).
Moreover, there is no code bound to this type except for its definition.
So, maybe the most reasonable is to postpone removal of this type to (e.g.) 5.0.
| #TBD#
| Pavol
|
| #TBD#
| #TBD#
| #TBD#
|

| common-tasks-3.xsd
| StringWorkSegmentationType
| boundaryCharacters
| xsd:string
|
| This is a configuration property for bucketing, used primarily for multi-node tasks.
It had problems with unordered nature of prism items, so it was replaced by sound `boundary` item and deprecated in 4.3 by https://github.com/Evolveum/midpoint/commit/0d0a9dff[0d0a9dff].

Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/996326c9[996326c9].
a|
The migration consists of converting each `boundaryCharacters` value to `boundary` item with:

- the `position` property, starting at 1 and increasing,
- the `characters` property, containing original `boundaryCharacters` value.

For example, from

[source,xml]
----
<boundaryCharacters>a</boundaryCharacters>
<boundaryCharacters>\0-\1\a-\c</boundaryCharacters>
<boundaryCharacters>01abc</boundaryCharacters>
----

to

[source,xml]
----
<boundary>
    <position>1</position>
    <characters>a</characters>
</boundary>
<boundary>
    <position>2</position>
    <characters>\0-\1\a-\c</characters>
</boundary>
<boundary>
    <position>3</position>
    <characters>01abc</characters>
</boundary>
----

| Pavol
|
| Before upgrade
| Automatic if implemented.
| Critical
| Analyzed and removed from the schema. Done.

| common-tasks-3.xsd
| TaskType
| category
| xsd:string
|
| Deprecated in 4.4 by https://github.com/Evolveum/midpoint/commit/5a9684d4[5a9684d4].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/a5754af1[a5754af1].

The removal is safe, as this property was practically not used.
| Not needed.
| Pavol
|
| N/A
| Automatic.
| N/A
| Analyzed and removed from the schema. Done.

| common-tasks-3.xsd
| TaskType
| errorHandlingStrategy
| tns:ActivityErrorHandlingStrategyType
|
| Removed.

Introduced in 4.3 by https://github.com/Evolveum/midpoint/commit/ab4ba1b7[ab4ba1b7] as experimental feature.
Deprecated in 4.4 by https://github.com/Evolveum/midpoint/commit/c2a17184[c2a17184].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/c0508aaf[c0508aaf].

This feature was superseded by the activity definition format, which is the only one to be used in 4.8 and beyond.
| Using existing XSLT convertor?
| Pavol
|
| Before upgrade
| Automatic (#TODO check the XSLT convertor if it does it correctly#).
| #Critical?#
| Analyzed and removed from the schema. Done.

| common-tasks-3.xsd
| ActivityDefinitionType
| executionMode
| tns:ExecutionModeType
| 5.0
| The `executionMode` property was generalized into `execution` container in 4.7 and marked as deprecated by https://github.com/Evolveum/midpoint/commit/2e574125[2e574125].

However, as the new item does not exist in 4.4, we will not remove the old property now.
Marked with planned removal in 5.0 by https://github.com/Evolveum/midpoint/commit/da905f39[da905f39].

| The value can be stored as `execution/mode`.
| Pavol
|
| Before or after upgrade
| Automatic if implemented
| Optional
| Done.

| common-tasks-3.xsd
| TaskType
| expectedTotal
| xsd:long
|
| This property is managed by midPoint.
It contains the expected number of items to be processed by given task.

It is not used by standard (activity-based) tasks.
But we must keep it for now, because not all tasks were migrated to activities yet.
| N/A
| Pavol
|
| N/A
| N/A
| N/A
| Done.

| common-tasks-3.xsd
| ActivityTracingDefinitionType
| interval
| xsd:int
| 5.0
| The simple `interval` specification was replaced by more complex `beforeItemCondition` structure (containing `interval` itself).
The whole tracing feature is experimental.

However, we are not ready to remove this property yet.
First, it is still the only possibility how to specify tracing for asynchronous update tasks.
Second, the profiling interval should be removed with it; and it was not deprecated until now.

Removal postponed to 5.0 by https://github.com/Evolveum/midpoint/commit/bb3a264f[bb3a264f].
| N/A
| Pavol
|
| Before or after upgrade
| Manual
| Optional. The property stays in the schema.
| Done.

| common-tasks-3.xsd
| ActivityProfilingDefinitionType
| interval
| xsd:int
| 5.0
| Some time ago, the simple `interval` specification was replaced by more complex `beforeItemCondition` structure (containing `interval` itself).
However, the original place was not marked as deprecated.

So, it was marked as deprecated right now (4.8), with planned removal set to 5.0 by https://github.com/Evolveum/midpoint/commit/bb3a264f[bb3a264f].

The whole feature is experimental.
| N/A
| Pavol
|
| Before or after upgrade
| Manual
| Optional. The property stays in the schema.
| Done.

| common-tasks-3.xsd
| TaskType
| modelOperationContext
| tns:LensContextType
|
| In the days of old, this item was used to keep the information about changes that are to be executed.
It is no longer used, though.

Deprecated in 4.4 by https://github.com/Evolveum/midpoint/commit/0faab13f[0faab13f].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/be10eb77[be10eb77].
| Not needed.
| Pavol
|
| N/A
| Automatic.
| N/A
| Analyzed and removed from the schema. Done.

| common-tasks-3.xsd
| WorkDefinitionsType
| nonIterativeChangeExecution
| tns:ExplicitChangeExecutionWorkDefinitionType
| 5.0
| The `nonIterativeChangeExecution` was improved and renamed to `explicitChangeExecution` in 4.6 by https://github.com/Evolveum/midpoint/commit/0c85b470[0c85b470].
However, as the new item does not exist in 4.4, we will not remove the old one now.
Marked with planned removal in 5.0 by https://github.com/Evolveum/midpoint/commit/4da1a29d[4da1a29d].

| Simple rename will do the trick.
| Pavol
|
| Before or after upgrade
| Automatic if implemented
| Optional
| Done.

| common-tasks-3.xsd
| TaskType
| policyRule
| tns:PolicyRuleType
|
a| This was a part of an undocumented, untested, and experimental mechanism of providing custom timed notifications.
There is a migration to the use of `focusValidityScan.validityConstraint` item, although not a complete one:
even if the ability to recompute objects is retained, custom policy actions can no longer be defined.

However:

1. this functionality was undocumented and experimental;
2. since approx. 4.4 it didn't work at all, due to an unrelated bug.

The replacement mechanism is still experimental, but at least the bug was fixed and a test was written.
| Not needed due to experimental nature of the feature.
| Pavol
|
| Before update
| Manual
| Mandatory if the feature is to be used.
| Analyzed and removed from the schema. Done.

| common-tasks-3.xsd
| TaskType
| recurrence
| tns:TaskRecurrenceType
|
|
This property was moved from the task root to `schedule` container (and deprecated in the original place) in 4.4 by https://github.com/Evolveum/midpoint/commit/74280c5f[74280c5f].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/15e18c2f[15e18c2f].

Note that the property is no longer required.
The default value is `recurring` for tasks that have `interval` or `cronLikePattern` set, and `single` otherwise.

| The migration code can simply take the value of this property and put it into the `schedule` container.
| Pavol
|
| Before upgrade
| Automatic if implemented.
| Critical
| Analyzed and removed from the schema. Done.

| common-workflows-3.xsd
| ApprovalStageExecutionInformationType
| executionRecord
| ApprovalStageExecutionRecordType
|
|
This structure is used as a return value by (internal) midPoint APIs when
xref:/midpoint/devel/design/how-to-display-approval-case-planned-or-real-execution/[asking for information about planned or real execution of an approval case].

It was deprecated in 4.1 by https://github.com/Evolveum/midpoint/commit/80a957c2[80a957c2] and is not filled-in since then.

Hence, no migration is needed.
We simply removed this item from the schema in 4.8 by https://github.com/Evolveum/midpoint/commit/b0b4a379[b0b4a379].
| Not needed.
| Pavol
|
| N/A
| Automatic.
| N/A
| Analyzed and removed from the schema. Done.

| common-workflows-3.xsd
| InformationType
| title
| xsd:string
|
|
Deprecated in 3.7 by https://github.com/Evolveum/midpoint/commit/cc5e5dc9[cc5e5dc9], when `localizableTitle` was added.

This object is part of the information passed by (customer-defined) `ApprovalStageDefinitionType.additionalInformation` expression.
That information is to be displayed to the approver in addition to the standard approval information provided by midPoint.
The `title` can be a useful shortcut for the engineer to avoid the complexity of creating a localizable message structure.

Un-deprecated in 4.8 by https://github.com/Evolveum/midpoint/commit/afbe82e5[afbe82e5].
| N/A
| Pavol
|
| N/A
| N/A
| N/A
|

| common-workflows-3.xsd
| InformationPartType
| text
| xsd:string
|
|
Deprecated in 3.7 by https://github.com/Evolveum/midpoint/commit/cc5e5dc9[cc5e5dc9], when `localizableText` was added.

This object is part of the information passed by (customer-defined) `ApprovalStageDefinitionType.additionalInformation` expression.
That information is to be displayed to the approver in addition to the standard approval information provided by midPoint.
The `text` can be a useful shortcut for the engineer to avoid the complexity of creating a localizable message structure.

Un-deprecated in 4.8 by https://github.com/Evolveum/midpoint/commit/afbe82e5[afbe82e5].
| N/A
| Pavol
|
| N/A
| N/A
| N/A
|

| common-workflows-3.xsd
| WfConfigurationType
| useLegacyApproversSpecification
| tns:LegacyApproversSpecificationUsageType
| 4.8
| Removed (not used anymore).

Legacy approvers specification were removed back in 4.0.

The `useLegacyApproversSpecification` was removed in 4.8 by https://github.com/Evolveum/midpoint/commit/f1fcfce0[f1fcfce0].

There is nothing to migrate, it can be safely removed from the configuration.
| Not needed.
| Pavol
|
| N/A
| Automatic.
| N/A
| Analyzed and removed from the schema. Done.

| extension-3.xsd
| task extension
| liveSyncErrorHandlingStrategy
| c:ActivityErrorHandlingStrategyType
|
| Removed.

Introduced in 4.3 by https://github.com/Evolveum/midpoint/commit/7af6125a[7af6125a] as experimental feature.
Deprecated in 4.3 by https://github.com/Evolveum/midpoint/commit/ab4ba1b7[ab4ba1b7].
Removed in 4.8 by https://github.com/Evolveum/midpoint/commit/c0508aaf[c0508aaf].

This feature was superseded by the activity definition format, which is the only one to be used in 4.8 and beyond.
| XSLT convertor?
| Pavol
|
| Before upgrade
| Automatic (#TODO check the XSLT convertor if it does it correctly#).
| #Critical?#
| Analyzed and removed from the schema. Done.

| extension-3.xsd
|
| reportOutputOid
| xsd:string
| 4.3
| Still used at least in archetype for report task.
|
| Lukas
| reportDataParam.oid
|
| should be removed from schema
|
|
|===
