= Schema cleanup
:page-since: 4.8
:page-toc: top

== Introduction

// TODO

== List of currently deprecated items in XSD

[%header,format=csv,separator=,]
|===
File, Element name, Element type
capabilities-3.xsd,AddRemoveAttributeValuesCapabilityType,
common-case-management-3.xsd,taskRef,tns:ObjectReferenceType
common-core-3.xsd,approvalWorkItems,c:WorkItemSelectorType
common-core-3.xsd,data,xsd:string
common-core-3.xsd,defaultAssignmentConstraints,tns:AssignmentConstraintsType
common-core-3.xsd,defaultCollection,tns:ObjectCollectionUseType
common-core-3.xsd,objectResults,tns:CleanupPolicyType
common-core-3.xsd,oidBound,xsd:boolean
common-core-3.xsd,propertyConstraint,tns:ItemConstraintType
common-core-3.xsd,reconcileAffected,xsd:boolean
common-core-3.xsd,roleCatalogCollections,tns:ObjectCollectionsUseType
common-core-3.xsd,roleCatalogRef,c:ObjectReferenceType
common-core-3.xsd,subtype,xsd:string
common-core-3.xsd,targetSubtype,xsd:string
common-correlation-3.xsd,followOn,tns:CompositeCorrelatorType
common-gui-3.xsd,additionalPanels,tns:GuiObjectListViewAdditionalPanelsType
common-gui-3.xsd,container,tns:VirtualContainersSpecificationType
common-gui-3.xsd,defaultObjectType,xsd:QName
common-gui-3.xsd,defaultScope,tns:SearchBoxScopeType
common-gui-3.xsd,displayName,t:PolyStringType
common-gui-3.xsd,forms,tns:ObjectFormType
common-gui-3.xsd,name,xsd:string
common-gui-3.xsd,objectForms,tns:ObjectFormsType
common-gui-3.xsd,userDashboard,tns:DashboardLayoutType
common-gui-3.xsd,userDashboardLink,tns:RichHyperlinkType
common-model-context-3.xsd,accountPasswordPolicy,c:ValuePolicyType
common-model-context-3.xsd,accountPasswordPolicyRef,c:ObjectReferenceType
common-notifications-3.xsd,FileConfigurationType,
common-notifications-3.xsd,LegacyCustomTransportConfigurationType,
common-notifications-3.xsd,MailConfigurationType,
common-notifications-3.xsd,NotificationTransportConfigurationType,
common-notifications-3.xsd,SmsConfigurationType,
common-notifications-3.xsd,customTransport,tns:LegacyCustomTransportConfigurationType
common-notifications-3.xsd,sms,tns:SmsConfigurationType
common-provisioning-3.xsd,LegacySynchronizationReactionType,
common-provisioning-3.xsd,ObjectSynchronizationType,
common-provisioning-3.xsd,auxiliaryObjectClass,xsd:QName
common-provisioning-3.xsd,baseContext,tns:ResourceObjectReferenceType
common-provisioning-3.xsd,objectSynchronization,tns:ObjectSynchronizationType
common-provisioning-3.xsd,searchHierarchyScope,tns:SearchHierarchyScopeType
common-security-3.xsd,name,xsd:string
common-security-3.xsd,name,xsd:string
common-security-3.xsd,name,xsd:string
common-security-3.xsd,name,xsd:string
common-tasks-3.xsd,PureCompositeWorkStateType,
common-tasks-3.xsd,boundaryCharacters,xsd:string
common-tasks-3.xsd,category,xsd:string
common-tasks-3.xsd,errorHandlingStrategy,tns:ActivityErrorHandlingStrategyType
common-tasks-3.xsd,executionMode,tns:ExecutionModeType
common-tasks-3.xsd,expectedTotal,xsd:long
common-tasks-3.xsd,interval,xsd:int
common-tasks-3.xsd,modelOperationContext,tns:LensContextType
common-tasks-3.xsd,nonIterativeChangeExecution,tns:ExplicitChangeExecutionWorkDefinitionType
common-tasks-3.xsd,policyRule,tns:PolicyRuleType
common-tasks-3.xsd,recurrence,tns:TaskRecurrenceType
common-workflows-3.xsd,ApprovalStageExecutionRecordType,
common-workflows-3.xsd,text,xsd:string
common-workflows-3.xsd,title,xsd:string
common-workflows-3.xsd,useLegacyApproversSpecification,tns:LegacyApproversSpecificationUsageType
extension-3.xsd,liveSyncErrorHandlingStrategy,c:ActivityErrorHandlingStrategyType
extension-3.xsd,reportOutputOid,xsd:string
|===