---
layout: personal
job-title: Senior Identity Engineer
photo: slavek.jpg
academic-titles: Mgr
profile-github: licehammer
evolveum-blog: https://evolveum.com/author/slavek/
---

= Slávek Licehammer

== Short Bio

Slavek graduated from Faculty of Informatics, Masaryk University in Brno, Czech Republic with Master's degree.
He works at Evolveum as senior identity engineer where he is specializing in identity management for higher-education.
He also works at Masaryk University and CESNET where his primary focus is building AAI infrastructures in research and education domain.
For over ten years, he has been engaged in the Trust and Identity area with a focus on Authentication and Authorization Infrastructures (AAI) in academic and research environment.
He has experience with distributed AAI solutions.


== Education

* Master's degree from https://www.muni.cz/[Masaryk university]

== Publications and Talks (selection)

link:/talks/files/2020-11-vision-for-IdM-in-higher-edutcation.pdf[Vision for Identity Management in Higher Education]::
Presentation at InCommon and GÉANT CAMP & Advance CAMP 2020

link:/media/2020-09-10-data-provenance-workshop.mp4[Data Provenance and Metadata Management in IdM (video)]::
Evolveum webinar 2020 (with Radovan Semančík)

https://arxiv.org/abs/1611.07832[AARC: First draft of the Blueprint Architecture for Authentication and Authorisation Infrastructures]::
AARC Blueprint Architecture, a design pattern that has emerged as a best practice for implementing inter-operable authentication and authorization solutions for international research collaborations and infrastructures.

https://doi.org/10.22323/1.270.0016[Importance of User Deprovisioning from Services]::
Published in Proceedings of Science ISGC 2016

https://ieeexplore.ieee.org/document/7431466[Public-private cloud federation challenges]::
Published in Proceedings of the 8th International Conference on Utility and Cloud Computing (UCC '15)

http://dx.doi.org/10.1109/ISTAFRICA.2014.6880654[Perun — Modern approach for user and service management]::
Published in 2014 IST-Africa Conference Proceedings


== Project Participation (selection)

xref:/midpoint/midprivacy/[Midprivacy]::
2020, Analysing requirements for Metadata management in IdM

https://aarc-project.eu/[AARC and AARC2]::
2016 - 2019, designing recommendations for AAI for research collaborations

https://www.geant.org/Projects/GEANT_Project_GN4-3[GÉANT GN4-3]::
since 2019, building AAI solution for research collaborations

https://www.eosc-life.eu/[EOSC-Life]::
since 2019, task leader of Complex Life-science AAI implementation task

https://www.e-infra.cz/[e-INFRA CZ]::
since 2020, building AAI solution for Czech national e-infrasctructure
