= Unified Connector Framework Interfaces
:page-wiki-name: Unified Connector Framework Interfaces
:page-wiki-id: 24085734
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2017-04-07T16:03:57.150+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2017-04-07T16:19:18.398+02:00
:page-archived: true
:page-obsolete: true
:page-toc: top

== UCF API

Component: provisioniong/ucf-api

GitHub link: https://github.com/Evolveum/midpoint/tree/master/provisioning/ucf-api[]

Primary interfaces are ConnectorFactory and ConnectorInstance.
The UCF implementation is supposed to provide at least one implementation of ConnectorFactory.
The ConnectorFactory implementation will produce instances of ConnectorInstance interface.

== UCF Implementation

Currently there are two UCF implementations:

* ucf-impl-connid: Implementation using the wiki:ConnId[ConnId] framework.
This is used for almost all midPoint connectors.

* ucf-impl-builtin: Implementation for specialized built-in connectors.
This is used mostly for manual connectors.


=== UCF ConnId Implementation

Component: provisioniong/ucf-impl-connid

GitHub link: https://github.com/Evolveum/midpoint/tree/master/provisioning/ucf-impl-connid[]

TODO: documentation

=== UCF Builtin Implementation

Component: provisioniong/ucf-impl-builtin

GitHub link: https://github.com/Evolveum/midpoint/tree/master/provisioning/ucf-impl-builtin[]

UCF implementation for built-in and specialized connectors.
This a very thin implementation, heavily based on midPoint internals (e.g. wiki:Prism+Objects[Prism Objects]) and Spring framework.

This implementation is looking for connector classes that have @ManagedConnector annotation and it tries to use them automatically.
All "connectors" used by this implementation must be built together with midPoint.
Therefore they either need to be part of midPoint itself, they need to be midPoint dependencies or they need to be glued to midPoint classpath by using maven overlay or a similar mechanism.

== Manual Connectors

The UCF API has s specialized abstract class `AbstractManualConnectorInstance` that can be used to create manual connectors.
Built-in manual connectors simply need to extend this class and implement the abstract methods.
The responsibility of a manual connector implementation is to create tickets (work orders) and to provide information about their state.

The default built-in manual connector implementation can be used as an example:

link:https://github.com/Evolveum/midpoint/blob/master/provisioning/ucf-impl-builtin/src/main/java/com/evolveum/midpoint/provisioning/ucf/impl/builtin/ManualConnectorInstance.java[]


=== How To Create Manual Connector

. Coordinate your effort with midPoint development team.
See wiki:Development+Participation[Development Participation].

. Create a subclass of `AbstractManualConnectorInstance`:

.. Implement the abstract methods

.. Use `@ManagedConnector` annotation



. The implementation must be in `com.evolveum.midpoint package. Following root package is recommended:` +
`com.evolveum.midpoint.provisioning.ucf.impl.builtin.connector.<yourBundleName>`

. Make sure that this implementation is on a class path when midPoint runs.

[NOTE]
====
This method is only supported for connectors that are supposed to become (optional) part of midPoint.
It is expected that the connectors will be available under open source license, preferably Apache License and that they will be contributed to the midPoint project.
This method is *not* supported for commercial or per-project connectors.
====

== See Also

* wiki:Unified+Connector+Framework[Unified Connector Framework]
* wiki:Prism+Objects[Prism Objects]
