= Sample ID Match Service

The sample ID Match service is configured with two matchgrids:

1. `test`
2. `demo`

Both contain the same sample configuration, described below.

== Attributes

[%autowidth]
[%header]
|===
| Name | Meaning
| givenName | Given name
| familyName | Family name
| dateOfBirth | Date of birth (yyyy-mm-dd)
| nationalId | A national-wide identifier
|===

== Matching Rules

Having a new record that is being matched (`new`), and an existing record in the matching database
that we are considering as a candidate match (`candidate`).

1. If all attributes match between `new` and `candidate`, the `candidate` record is automatically taken as a match for `new`. This is
a built-in rule in ID Match service.
2. If national ID, date of birth and family name matches between `new` and `candidate`, the `candidate` record is automatically taken
as a match for `new`.
3. Otherwise, if national ID matches between `new` and `candidate`, the `candidate` record is added to the list of candidates that will
be presented to the human operator.
4. Otherwise, if date of birth, given name and family name match between `new` and `candidate`, the `candidate` record is added to the list of candidates that will
be presented to the human operator.
5. Otherwise, the `candidate` record is ignored, and next one is considered. If no candidate matches, the `new` is said to be a unique identity.

Summarizing the rules:

[%autowidth]
[%header]
|===
| Given name | Family name | Date of birth | National ID | Result | Note
| Matches | Matches | Matches | Matches | Automatic match | Built-in rule
| May or may not match | Matches | Matches | Matches | Automatic match | Custom rule 1
3+| Any of these does not match | Matches | Manual consideration | Custom rule 2
| Matches | Matches | Matches | Does not match | Manual consideration | Custom rule 3
4+| None of the above matches for no candidate | Automatic result: new identity | Built-in rule
|===

== How to Use

1. Unzip #TODO# file.
2. Start the composition by issuing the command

----
docker compose up
----

The following text on the console indicates that the service is ready to use:

----
...
php  | INSERT 0 2
php  | INSERT 0 1
php  | INSERT 0 9
php  | INSERT 0 2
php  | INSERT 0 6
php  | INSERT 0 14
php  | --COMANAGE_MATCH READY FOR USE --
----

The administration console can be reached at http://localhost:9090/match/, with the username of `admin` and password of `5ecr3t`.
