= LDAP Servers Summary
:page-wiki-name: LDAP Servers Summary
:page-wiki-id: 24084654
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2016-12-05T10:52:28.007+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2018-05-24T15:15:40.395+02:00
:page-upkeep-status: yellow

[%autowidth,cols="h,1,1,1,1,1"]
|===
|   | OpenLDAP | OpenDJ / Wren:DS | 389ds | Active Directory | eDirectory

| Connector
| xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP]
| xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP]
| xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP]
| xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[AD (LDAP)]
| xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.edirectory.EDirectoryLdapConnector/[eDirectory]


| midPoint support
| [.green]#Works.# +
Supported out-of-box.
Included in all midPoint subscriptions.
| [.green]#Works.# +
But due to the change in ForgeRock open source strategy it supported only for midPoint subscribers that got their subscription before December 2016. +
(see note 1 below)
| [.green]#Works.# +
But only partially tested.
Extra subscription is needed to support this resource.
| [.green]#Works.# +
Supported out-of-box.
Included in all midPoint subscriptions.
| Works with limitations. Extra subscription is needed to support this resource.


| Details page
| xref:/connectors/resources/ldap/openldap/[OpenLDAP]
| xref:/connectors/resources/ldap/opendj/[OpenDJ]
| xref:/connectors/resources/ldap/389ds/[389 Directory Server]
| xref:/connectors/resources/active-directory/[Active Directory]
| xref:/connectors/legacy/edirectory/[eDirectory]


| LDAP standard compliance
| [.green]#good compliance +
#
| [.green]#good [.green]#compliance# +
#
| some compliance issues
| really BAD standard compliance
| bad standard compliance


| Entry ID Attribute
| entryUuid
| entryUuid
| nsUniqueId
| objectGUID
| GUID


| Account activation
| _none_ +
(see note 3 below)
| `ds-pwp-account-disabled`
| `nsAccountLock`
| `userAccountControl`
|


| Group membership shortcut
| `memberOf` (with overlay)
| `isMemberOf`
|
| memberOf
| _several_


| Livesync support
| modifyTimestamp +
(see note 4 below)
| [.green]#Retro changelog#
| Retro changelog - with limitations +
(see note 5 below)
| [.green]#Active Directory DirSync control#
| none


| referential integrity
| yes (with overlay)
|
| yes (with plugin)
| yes
| yes


| License
| [.green]#OpenLDAP Public License#
| OpenDJ: Formally CDDL, but otherwise commercial. +
Wren:DS: CDDL
| [.green]#GPL#
| Commercial
| Commercial


| Issues
| Cannot disable accounts. +
Difficult to manage.
| OpenDJ: Licensing (fauxpen source) +
Wren:DS: Small community, maintenance may be problematic.(see notes 1 and 2 below)
| Very old technology (fork from iPlanet Alliance). +
(see note 6 below)
| Way too many issues to list
| Many


|===


== Notes

. OpenDJ server was fully supported in the past.
However, OpenDJ maintainer (ForgeRock) has changed its open source strategy.
Therefore we are no longer allowed to get recent versions of OpenDJ for testing.
Therefore we cannot make sure that recent OpenDJ versions work with midPoint.
So, even though OpenDJ server is likely to work well with midPoint, it is no longer officially supported.

. Wren:DS is a fork of OpenDJ.
Wren:DS is freely available under the terms of CDDL license.
However, the Wren:DS development community is very small.
There is almost no new development.
However, Wren:DS may be supported with midPoint, if this is negotiated in the subscription contract.

. OpenLDAP has no easy way to disable an account.
There are some workarounds that are using the ACI mechanism.
But as far as we know there is no really good solution for this.

. OpenLDAP livesync support is currently available only by using the modifyTimestamp attribute.
The approach generally works, but this is the minimal support possible.
This method cannot detect deleted accounts.
There is an option to implement livesync by using OpenLDAP syncrepl mechanism (link:https://tools.ietf.org/html/rfc4533[RFC4533]). However, this is not implemented yet.

. Livesync with 389 Directory Server (389ds) is using retro changelog method that is similar to Sun/Oracle DSEE servers and OpenDJ/Wren:DS servers.
However, 389ds server is using very old version of the retro changelog.
Some crucial data are missing.
E.g. there is no entry unique identifier (nsUniqueId) of the deleted entry.
Therefore the 389ds changelog does *not* work reliably in case that nsUniqueId is used as entry identifier.
The changelog work reasonably well in case that DN is used as primary identifier.
But in that case midPoint cannot reliably detect object renames.

. Overall, the 389ds is based on very old technology going back to early 2000s and it was only partially (but insufficiently) updated to recent LDAP standards.
E.g. 389ds is still using nsUniqueId, while link:https://www.ietf.org/rfc/rfc4530.txt[RFC4530] is specifying entryUUID attribute for that purpose.
Almost all other LDAP servers have adopted entryUUID.
But not 389ds server - albeit the fact that RFC4530 was published more than a decade ago.


== Conclusion

This is a very difficult choice.
It almost looks like there is no good LDAP server at all.
All the servers have serious issues.


== See Also

* xref:/iam/ldap/ldap-survival-guide/[]