= ISO/IEC 27001 Compliance
:page-nav-title: ISO 27001
:page-upkeep-status: green

link:https://www.iso.org/standard/iso-iec-27000-family[ISO/IEC 27000 Series] of standards deal with information security management systems (ISMS), an essential building block of cybersecurity.
The standard series describes _best practice_ in the field, providing recommendations and guidance.

* *ISO/IEC 27000* specification provides an introduction and a vocabulary.
+
xref:/glossary/iso27000/[ISO 27000 vocabulary] was xref:/glossary/iso27000/[mapped] to xref:/glossary/[midPoint vocabulary] to improve understanding.
Moreover, some terms of midPoint vocabulary were adapted to standard ISO27000 vocabulary.

* *ISO/IEC 27001* specification is the normative core of 27000 series.
It specifies requirements for establishing, implementing, maintaining and continually improving an information security management system (ISMS).
Annex A of the specification provides list of concrete information security controls.

* *ISO/IEC 27002* specification provides additional information on best practice and further guidance for implementation and maintenance of information security management system (ISMS).
Controls listed in ISO 27001 Annex A are further explained in ISO 27002 document.

// TODO: Applicability: we assume mid-sized or large organizations. Necessity of midPoint may be different for very small organizations.

== Mapping of MidPoint Features

// TODO: mapping intro

NOTE: This list applies to the latest stable release of midPoint starting with midPoint 4.9.1.


++++
<table class="tableblock frame-all grid-all fit-content">

    <thead>
        <tr>
            <th class="tableblock halign-left valign-top">Control ID</th>
            <th class="tableblock halign-left valign-top">Control Name</th>
            <th class="tableblock halign-left valign-top">Necessity</th>
            <th class="tableblock halign-left valign-top">Implementation Overview</th>
            <th class="tableblock halign-left valign-top">Number of Features</th>
        </tr>
    </thead>

    <tbody>
    {% for c in site.data.compliance-iso27001 %}
        <tr>
            <td class="tableblock halign-left valign-top"><a href="{{ c.url }}">{{ c.id }}</a></td>
            <td class="tableblock halign-left valign-top"><a href="{{ c.url }}">{{ c.title }}</a></td>
            <td class="tableblock halign-left valign-top">{{ c.necessity }}</td>
            <td class="tableblock halign-left valign-top">{{ c.implementation.overview }}</td>
            <td class="tableblock halign-left valign-top">{% if c.features %}{{ c.features.size }}{% else %}-{% endif %}</td>
        </tr>
    {% endfor %}
    </tbody>

</table>
++++
