= MidPilot demo: AI-assisted connector generator
:page-moved-from: /midpoint/guides/trying-out-the-connector-generator/
:page-nav-title: Try AI in midPoint
:page-display-order: 400
:page-liquid:
:toclevels: 2
:page-upkeep-status: green
:page-keywords: connector generator, generator, identity connectors, connectors, ai, midpilot, llm, mcm, mcm26, midpoint community meetup
:page-description: This section walks you through setting up the midPilot so that you can try AI-assisted connector generation.
:page-experimental: true

== Introduction

Identity projects often stall not on business logic, but on the tedious work of building and maintaining custom connectors for every target system.
MidPilot connector generator in midPoint tackles this by using API documentation and AI‑assisted analysis to produce ready‑to‑use identity connectors with far less manual effort.

This section walks you through a demo version of the midPilot demo presented during the link:https://evolveum.com/events/mcm2026/[MidPoint community meetup 2026] (MCM26), helping you set up the midPilot connector generator microservice using Docker Compose and running it alongside a local midPoint instance on your workstation.
This demo uses OpenProject as a target application for which you will generate a connector.

By the end of the guide, you will have deployed a working development environment with midPilot’s connector generator accessible on a local URL and midPoint running in a separate container.
This guide assumes you are comfortable with Docker and Docker Compose, have basic familiarity with midPoint, and can run commands from a terminal on Linux, macOS, or WSL.

.You need an LLM
[NOTE]
====
The connector generator microservice needs a large language model (LLM) to function.
Evolveum does not provide an LLM service.
You need to deploy or rent one on your own.
Refer to xref:/midpoint/get-started/install/midpilot-setup/[] for details on midPilot microservices configuration.
====

++++
{% children style: table %}
++++


== Additional Links

* xref:/midpoint/get-started/install/midpilot-setup/[]
* link:https://github.com/Evolveum/midpoint-samples/tree/master/samples[Midpoint samples]
* link:https://github.com/Evolveum/midpilot-connector-gen/tree/main[Connector generator]
* link:https://github.com/Evolveum/connector-scimrest[Scimrest framework]