= Expression evaluation model

Let us define the expression evaluation more formally.

== Sources

1. Let we have n sources numbered 1, 2, ..., n.
2. Each source can provide values of a given type. Let D~1~, D~2~, ..., D~n~ be domains for individual
values for sources 1, 2, ..., n, respectively.
3. Because each source can have multiple values of given type, the domains for sources 1, 2, ..., n are
power sets (sets of sets) of D~1~, D~2~, ..., D~n~, respectively, denoted as P(D~1~), P(D~2~), ..., P(D~n~).
4. And because each source has two states: old and new, the complete specification of input states
can be denoted as P(D~1~) x P(D~1~), P(D~2~) x P(D~2~), ..., P(D~n~) x P(D~n~).

== Output

1. Let R be the domain for individual values of the target (output) item, i.e. _evaluator range_.
2. P\(R) is the power set of the evaluator range: all sets of individual values of the target item.
3. P\(R) x P\(R) x P\(R) is the set of all possible delta set triples (plus, minus, zero sets of values).

== Transformation function (no deltas)

|===
|
T: P(D~1~) x P(D~2~) x ... x P(D~n~) -> P\(R)
|===

is the transformation function that maps sets of source values to a set of output values (no deltas yet).

== Transformation function (with deltas)

Then the "delta-aware" transformation T~rel~ i.e.:

|===
|
T~rel~ : P(D~1~) x P(D~1~) x P(D~2~) x P(D~2~) x ... x P(D~n~) x P(D~n~) -> P\(R) x P\(R) x P\(R)
|===
(in human words, a transformation function that maps couples (old, new) of sets of source values
to the output delta set triple)

can be defined in this way:

* let S~1~ &#x2286; D~1~, S~2~ &#x2286; D~2~, ..., S~n~ &#x2286; D~n~ be sets of old values
of sources 1, 2, ..., n, respectively;
* let S~1~' &#x2286; D~1~, S~2~' &#x2286; D~2~, ..., S~n~' &#x2286; D~n~ be sets of new values
of sources 1, 2, ..., n, respectively;
* let O &#x2286; R is the set of output values for the "old" state, i.e. O = T(S~1~, S~2~, ..., S~n~);
* let O' &#x2286; R is the set of output values for the "new" state, i.e. O' = T(S~1~', S~2~', ..., S~n~');
* let (O~plus~ &#x2286; R, O~minus~ &#x2286; R, O~zero~ &#x2286; R) be resulting delta set triple.

Then

|===
|
T~rel~ (S~1~, S~1~', S~2~, S~2~', ..., S~n~, S~n~') = (O~plus~, O~minus~, O~zero~)
|===

if and only if:

* O~plus~ = O' - O
* O~minus~ = O - O'
* O~zero~ = O &#x2229; O'

Note that this description ignores the existence of variables. It is rather complicated even without them.
If you're interested how variables are treated, please see the description of the implementation.
