= Active Directory with LDAP connector
:page-wiki-name: Active Directory with LDAP connector
:page-wiki-id: 21528769
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2015-11-23T14:02:25.046+01:00
:page-wiki-metadata-modify-user: vix
:page-wiki-metadata-modify-date: 2021-03-08T09:04:37.997+01:00
:page-toc: top
:page-upkeep-status: orange
:page-upkeep-note: merge with "Active Directory HOWTO"?

// TODO: merge with "Active Directory HOWTO"?

[%autowidth,cols="h,1"]
|===
| Status
| Provisioning works well. Synchronization works well.

| Recommended connector
| xref:../../connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[]
|===


== Resource Configuration

(Remote connector server is not needed for this connector)


=== Administrative Account for Provisioning/Synchronization

We have successfully tested both provisioning and synchronization of users with the following access privileges using Active Directory domain "Delegate Control" mechanism:

* Create, delete and manage user accounts

* Reset user passwords and force password change at next logon

* Read all user information

* Create, delete and manage groups

* Modify the membership of a group

* Create, delete and manage inetOrgPerson accounts (TODO: is this needed?)

* Reset inetOrgPerson accounts and force password change at next logon (TODO: is this needed?)

* Read all inetOrgPerson information

* Create, delete and manage managed service accounts (MSA)

[NOTE]
In the new versions of windows the option *Create, delete and manage groups* disappear from the list to select.
Without this permission the proper provision is not possible.
The successful tests has been reached with the *Domain admin* membership for the account used by the midpoint to access the AD.

.Powershell command to add the account *midpoint* to Domain admin group
[source,powershell]
----
Add-ADGroupMember -Identity 'CN=Domain Admins,CN=Users,DC=ad2019,DC=lab,DC=evolveum,DC=com' -Members 'CN=MidPoint,CN=Users,DC=ad2019,DC=lab,DC=evolveum,DC=com'
----

For LiveSync, you also need "Replicating Directory Changes" (DS-Replication-Get-Changes) permission (please refer to link:https://support.microsoft.com/en-us/help/303972[https://support.microsoft.com/en-us/help/303972] and link:https://support.microsoft.com/en-ae/help/891995/how-to-poll-for-object-attribute-changes-in-active-directory-on-window[https://support.microsoft.com/en-ae/help/891995/how-to-poll-for-object-attribute-changes-in-active-directory-on-window]).

[NOTE]
All the permissions in AD have own GUID which is unique ID used for the assignment.
In case of DS-Replication-Get-Changes permission it is 1131f6aa-9c07-11d1-f79f-00c04fc2dcd2 (https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/1522b774-6464-41a3-87a5-1e5633c3fbbb).

.Powershell command to assign *DS-Replication-Get-Changes* permission
[source,powershell]
----
#############
# Module ActiveDirectory is needed to be loaded just once.
# In case of AD: "prefix" the module is not loaded automatically.
#############
Import-Module ActiveDirectory

$path = "AD:DC=ad2019,DC=lab,DC=evolveum,DC=com"
$acl = Get-Acl -Path $path
$ace = New-Object System.DirectoryServices.ActiveDirectoryAccessRule(
	[System.Security.Principal.IdentityReference] (get-aduser -identity midpoint).SID,
	[System.DirectoryServices.ActiveDirectoryRights] 'ExtendedRight',
	[System.Security.AccessControl.AccessControlType] 'Allow',
	(new-object Guid '1131f6aa-9c07-11d1-f79f-00c04fc2dcd2')
)
$acl.AddAccessRule($ace)
Set-Acl -Path $path -AclObject $acl
----


== Recommended Connector

*Framework:* ConnId +
*Bundle:* com.evolveum.polygon.connector-ldap +
*Version:* most recent stable version +
*Connector:* com.evolveum.polygon.connector.ldap.ad.AdLdapConnector


== Connector Configuration

(currently, no published documentation)

[NOTE]
.Active Directory LDAP Strangeness
====
Active Directory in the default configuration is not really LDAPv3-compliant server.
It has many quirks, extensions, modification and twists the LDAP standard almost beyond recognition.
The LDAP connector was modified to survive this brutal "intepretation" of the LDAP specifications.
However, there are many things that needs to be taken into account when configuring AD resource:

* `instanceType`, `nTSecurityDescriptor` and `objectCategory` are formally defined as mandatory attributes in the `top` object class (!!!). This means they are (formally) mandatory for all objects accessed using LDAP connection.
But the reality is different.
It seems to be OK to create an object without these attributes.
Therefore for a proper operation of midPoint we recommend to modify the schema using the `limitations` mechanism in midPoint xref:/midpoint/reference/resources/resource-configuration/schema-handling/[Resource Schema Handling] by setting `minOccurs=0`. (This is already done in the sample referenced below.)

* The objects can easily have attributes that are not defined in any object classes that they have.
E.g. a normal user (the `user` object class) may have attribute `info`. If such extra attributes are used in your AD instance then the best way is to configure them as operational attributes in the connector configuration and define them explicitly in xref:/midpoint/reference/resources/resource-configuration/schema-handling/[Resource Schema Handling] (see bug:MID-3379[]).
====

=== Resource Configuration Example

[source,MidPoint 4.8 and lower]
----
<connectorConfiguration xmlns:icfc="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/connector-schema-3">
        <icfc:configurationProperties xmlns:icfcldap="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/com.evolveum.polygon.connector-ldap/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector">
            <icfcldap:host>ad.example.com</icfcldap:host>
            <icfcldap:port>636</icfcldap:port>
            <icfcldap:baseContext>DC=evolveum,DC=com</icfcldap:baseContext>
            <icfcldap:bindDn>CN=midpoint,CN=Users,DC=evolveum,DC=com</icfcldap:bindDn>
            <icfcldap:connectionSecurity>ssl</icfcldap:connectionSecurity>
            <icfcldap:bindPassword>
                <t:clearValue>secret</t:clearValue>
            </icfcldap:bindPassword>
        </icfc:configurationProperties>
        <icfc:resultsHandlerConfiguration>
            <icfc:enableNormalizingResultsHandler>false</icfc:enableNormalizingResultsHandler>
            <icfc:enableFilteredResultsHandler>false</icfc:enableFilteredResultsHandler>
            <icfc:enableAttributesToGetSearchResultsHandler>false</icfc:enableAttributesToGetSearchResultsHandler>
        </icfc:resultsHandlerConfiguration>
    </connectorConfiguration>

----

[source,MidPoint 4.9 and higher]
----
    <connectorConfiguration xmlns:icfc="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/connector-schema-3">
        <icfc:configurationProperties xmlns:icfcldap="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/com.evolveum.polygon.connector-ldap/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector">
            <icfcldap:host>medusa.lab.evolveum.com</icfcldap:host>
            <icfcldap:port>636</icfcldap:port>
            <icfcldap:baseContext>DC=win,DC=evolveum,DC=com</icfcldap:baseContext>
            <icfcldap:bindDn>CN=midpoint admin1,CN=Users,DC=win,DC=evolveum,DC=com</icfcldap:bindDn>
            <icfcldap:connectionSecurity>ssl</icfcldap:connectionSecurity>
            <icfcldap:bindPassword>
                <t:clearValue>secret</t:clearValue>
            </icfcldap:bindPassword>
            <icfcldap:pagingBlockSize>5</icfcldap:pagingBlockSize> <!-- ridiculously small, just to test paging -->
            <icfcldap:managedAssociationPairs>"user"+memberOf -# "group"+member</icfcldap:managedAssociationPairs>
            <icfcldap:managedAssociationPairs>"group"+ memberOf -# "group"+ member</icfcldap:managedAssociationPairs>
        </icfc:configurationProperties>
    </connectorConfiguration>
----

=== Resource Sample

link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/resources/ad-ldap/ad-ldap-medusa-medium.xml[See resource sample],
link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/resources/ad-ldap/AD%20advanced/resources/ADfirststep.xml[advanced example], or
link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/resources/ad-ldap/ad-ldap-medusa-native-references.xml[sample with native references].

=== Limitations

* Active Directory LDAP schema is violating LDAP standards and best practices in numerous ways.
The connector is build to tolerate these "quirks" in the AD schema.
However the underlying LDAP library may complain about the schema issues.
It is usually safe to ignore these warnings.


== Recommendation and Notes

=== Passwords

To avoid clear-text password visible in the repository, please refer to xref:/midpoint/reference/resources/resource-configuration/string-to-protectedstring-connector-configuration/[String to ProtectedString Connector Configuration].

=== Full Active Directory Schema

Active Directory has huge schema.
The schema when encoded in XSD has several megabytes.
This might take several hundreds of megabytes of memory when processed.
Make sure that your midpoint instance has enough memory (heap) to handle that.
The impact of AD schema can be limited by reducing the number of object classes that are processed by midPoint:

[source]
----
    <schema>
       <generationConstraints>
            <generateObjectClass>ri:user</generateObjectClass>
            <generateObjectClass>ri:group</generateObjectClass>
            <generateObjectClass>ri:msDS-ManagedServiceAccount</generateObjectClass>
        </generationConstraints>
    </schema>
----

See also bug:MID-2716[]

=== Explicit Referential Integrity

We recommend turning off explicitReferentialIntegrity for associations with groups.
Active Directory will maintain the group membership after account rename automatically.

Example:

[source,MidPoint 4.8 and lower]
----
...
<association>
    <ref>ri:group</ref>
    <displayName>AD Group Membership</displayName>
    <kind>entitlement</kind>
    <intent>group</intent>
    <direction>objectToSubject</direction>
    <associationAttribute>ri:member</associationAttribute>
    <valueAttribute>ri:dn</valueAttribute>
    <shortcutAssociationAttribute>ri:memberOf</shortcutAssociationAttribute>
    <shortcutValueAttribute>ri:dn</shortcutValueAttribute>
    <explicitReferentialIntegrity>false</explicitReferentialIntegrity>
</association>
...
----

[source,MidPoint 4.9 and higher]
----
        <associationType>
            <name>membership</name>
            <subject>
                <objectType>
                    <kind>account</kind>
                    <intent>default</intent>
                </objectType>
                <association>
                    <ref>ri:group</ref>
                    <sourceAttributeRef>ri:group</sourceAttributeRef> <!-- this is the default (the same as "ref") -->
                    <outbound>
                        <name>group-outbound</name>
                        <documentation>
                            Creates an association value from each role that has appropriate projection (to entitlement/group).
                        </documentation>
                        <expression>
                            <associationConstruction>
                                <objectRef>
                                    <mapping>
                                        <expression>
                                            <associationFromLink/>
                                        </expression>
                                    </mapping>
                                </objectRef>
                            </associationConstruction>
                        </expression>
                    </outbound>
                    <inbound>
                        <name>group-inbound</name>
                        <documentation>
                            Creates an assignment from each association value (a group) that has appropriate owner (a role);
                            except for situations where related assignment exists, or where an indirect assignment of the group
                            exists.

                            When the association value is removed, this mapping removes only those assignments that were created
                            by it (in the past).
                        </documentation>
                        <expression>
                            <associationSynchronization>
                                <objectRef>
                                    <correlator/>
                                    <mapping>
                                        <expression>
                                            <shadowOwnerReferenceSearch/>
                                        </expression>
                                        <target>
                                            <path>targetRef</path>
                                        </target>
                                    </mapping>
                                </objectRef>
                                <synchronization>
                                    <reaction>
                                        <situation>unmatched</situation>
                                        <actions>
                                            <addFocusValue/>
                                        </actions>
                                    </reaction>
                                    <reaction>
                                        <situation>matched</situation>
                                        <actions>
                                            <synchronize/>
                                        </actions>
                                    </reaction>
                                    <reaction>
                                        <situation>matchedIndirectly</situation>
                                        <!-- no actions here -->
                                    </reaction>
                                </synchronization>
                            </associationSynchronization>
                        </expression>
                    </inbound>
                    <tolerant>true</tolerant>
                </association>
            </subject>
            <object>
                <objectType>
                    <kind>entitlement</kind>
                    <intent>group</intent>
                </objectType>
            </object>
        </associationType>
----

=== National Characters

Although LDAP protocol and data structures are designed to be safe for use with national characters,
Active Directory obviously leaves a large room for improvement in this area.
For example, although LDAP specification states that DNs using different national characters should be considered different identifiers, Active Directory might consider them to be the same (see bug:MID-7355[]).

Therefore, we *strongly recommend* to avoid use of national characters in Active Directory, especially in the identifiers (`dn` and hence also `cn`).
MidPoint xref:/midpoint/reference/concepts/polystring/[polystring] functionality is designed especially for this purpose.
Following mapping may help create identifier without national characters:

[source,xml]
----
<attribute>
    <ref>ri:dn</ref>
    <outbound>
        <source>
            <path>givenName</path>
        </source>
        <source>
            <path>familyName</path>
        </source>
        <expression>
            <script>
                <code>
                    'CN=' + basic.concatName(familyName.getNorm(), givenName.getNorm()) + iterationToken + ',OU=Users,DC=example,DC=com'
                </code>
            </script>
        </expression>
    </outbound>
</attribute>
----

An equivalent mapping would be probably needed for `cn` attribute as well.

=== Increase maxObjects limit
By default, connector configuration maxObjects has preconfigured value of 10.
We recommend to increase this value for production deployment where heavy loads are expected to ensure that all objects will be correctly processed by midPoint, otherwise you could exceed limitation.
Also, this configuration can be useful in case that there are big groups, such asActive directory Domain users group contain all domain users.
In such a case operations with such groups can take a long time.
Increasing number of connectors in pool makes more connector instances available for other operations.

[source,xml]
----
    <connectorConfiguration xmlns:icfc="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/connector-schema-3">
        <icfc:connectorPoolConfiguration>
            <icfc:maxObjects>100</icfc:maxObjects>
        </icfc:connectorPoolConfiguration>
          ...
    </connectorConfiguration>
----

== See Also

* xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)]

* xref:/connectors/resources/active-directory/tips-tricks/[Active Directory Tips&Tricks]

* xref:/connectors/resources/active-directory/multidomain/[Active Directory Multi-Domain]

* xref:/connectors/resources/active-directory/legacy-net-connector/[Active Directory with the legacy .NET connector]

* xref:/midpoint/devel/design/ad-connector-design-notes/[AD Connector Design Notes]


== External links

* What is link:https://evolveum.com/midpoint/[midPoint Open Source Identity & Access Management]

* link:https://evolveum.com/[Evolveum] - Team of IAM professionals who developed midPoint

* link:http://ldapwiki.com/wiki/WILL_NOT_PERFORM[WILL_NOT_PERFORM] - wiki page explaining a lot of error messages returned by Active Directory