= Active Directory HOWTO
:page-wiki-name: Active Directory HOWTO
:page-wiki-id: 7307614
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2013-01-31T14:28:39.875+01:00
:page-wiki-metadata-modify-user: peterkortvel@gmail.com
:page-wiki-metadata-modify-date: 2016-02-20T16:12:21.951+01:00
:page-alias: { "parent" : "/midpoint/guides/" }
:page-upkeep-status: red

// TODO: merge with "Active Directory with LDAP connector"?

== Install .NET Connector Server

Install .NET Connector Server on a "gateway" machine.
This can be almost any Windows machine that will be used as an intermediary between link:https://evolveum.com/midpoint[midPoint] and Active Directory.

Installation instructions are on wiki:.NET+Connector+Server[.NET Connector Server] page.


== Deploy Active Directory Connector

Deploy Active Directory to the .NET Connector Server.

Active Directory connector information and download links are on wiki:Legacy+Active+Directory+Connector+(.NET)[Legacy Active Directory Connector (.NET)] page.

Deploy the connector by copying files to the .NET Connector Server directory.
The details are here: wiki:.NET+Connector+Server[.NET Connector Server].


== Configure Connector Host in midPoint

Create a connector host definition and import it in midPoint.
See here: wiki:Connector+Server[Connector Server].

You can import the sample XML configuration mentioned above by clicking the _Configuration_ tab, then _Import object_ tab.
Select "_Get objects from ... Embedded editor_" and paste the content of the connector host sample mentioned above.
Please modify the following attributes before clicking _Import Object_:

* *name*: rename it to contain your connector server name instead of "foobar.example.com", e.g. "ICF Connector server on server:8759"

* *hostname*: enter your connector server hostname, e.g. server.example.com

* *port*: enter your connector server port if you have changed it, or keep default "8759"

* *sharedSecret*: enter your [.underline]#connector server key# into the "sharedSecret" element instead of "secret"

Then click _Import Object_ button.

Detailed description of connector object is here: xref:/midpoint/architecture/archive/data-model/midpoint-common-schema/connectorhosttype/[ConnectorHostType].

If you have configured SSL on the connector server you should also install the appropriate CA certificate to a midPoint wiki:Keystore+Configuration[keystore] as described on wiki:Connector+Server[Connector Server] page.


== Discover the Connectors

The connector host should appear in midPoint GUI under a _Resources_ tab.
Check the checkbox next to it and click _Discovery_ button.
Green success message should appear.

Look at the Connector objects in the repository (in the GUI _Configuration_ tab, _Repository objects_, object type _Connector_). A new connector should appear there.
Look for a name similar to `ICF Org.IdentityConnectors.ActiveDirectory.ActiveDirectoryConnector @ICF Connector server on medusa:8759`.


== Configure Active Directory

To actually use Active Directory connector, you need to create an administrative account in Active Directory.
Do not use "administrator" account as it has unrestricted rights!

To create the administrative account for provisioning:

. Open "Server Manager" on the Active Directory machine.

. Select _Roles_, then _Active Directory Domain Services_. Alternatively, open "Active Directory Users and Computers".

. Unexpand your domain (e.g. _domain.example.com_) and right click on the _Users_ container.

. Select _New User_.

. Enter required information to create your administrative user for midPoint.
Do not forget to fill in _sAMAccountName_ (e.g. "midpoint") and _userPrincipalName_ (e.g. "midpoint@domain.example.com") attributes, and user's _password_. We recommend to uncheck "User must change password at next logon" and check "Password never expires".

To assign the administrative privileges in Active Directory to the administrative account:

. Open "Server Manager" on the Active Directory machine.

. Select _Roles_, then _Active Directory Domain Services_. Alternatively, open "Active Directory Users and Computers".

. Select your domain (e.g. _domain.example.com_) or a part of it where you will manage accounts with midPoint.
Select _Actions_ from menu.
Alternatively, right click on your domain (e.g._ domain.example.com_).

. Select _Delegate Control.._.

. Click _Next_.

. Click _Add_ to search for your administrative user, e.g. "midpoint".

. Click _Next_.

. Check the following checkboxes in "Delegate the following common tasks" area (default):

.. Create, delete, and manage user accounts

.. Reset user passwords and force password change at next logon

.. Read all user information

.. Create, delete and manage groups

.. Modify the membership of a group



. Click _Next_.

. Click _Finish_.



[TIP]
====
Please note that the Delegate control wizard cannot be used to modify existing delegated tasks.

====


=== Import Resource Definition

After you have installed all the required components and created your administrative account in Active Directory, you can create Active Directory resource definition.

There are three sample resource definitions that can be used to connect to a Active Directory server.
They can be found in our `samples/ad` directory accessible here:

[%autowidth,cols="h,1"]
|===
| Current Development Snapshot (master) | https://github.com/Evolveum/midpoint/tree/master/samples/resources/ad

| Latest Release (3.1.1)
| link:https://github.com/Evolveum/midpoint/tree/v3.1.1/samples/resources/ad[https://github.com/Evolveum/midpoint/tree/v3.1.1/samples/resources/ad]


|===

[TIP]
====
The resource definition XML file is full of in-line comments that explain individual configuration items used in the file.
The `ad-resource-simple.xml` file in the samples directory is a basic, readable and understandable definition of an AD resource.
The `ad-resource-advanced-nosync.xml` file in the samples directory contains provisioning-only configuration of the resource.
And` ad-resource-advanced-sync.xml` file contains provisioning and synchronization configuration of the resource.

====

[TIP]
====
The resource definition must be updated for your environment.
Especially:

* *DirectoryAdminName*: the name of the administrative account (e.g. "midpoint@domain.example.com", this is an example of using userPrincipalName format)

* *DirectoryAdminPassword*: the administrative account password (do not confuse this with the Connector Server key)

* *Container*: the container where the connector will "see" accounts in Active Directory

* *DomainName*: the Active Directory domain name (e.g. "domain", it seems that you can also use the "long" name as in "domain.example.com")

* *SyncGlobalCatalogServer*: null (if you are synchronizing, use "localhost"!)

* *SyncDomainController*: null (if you are synchronizing, use "localhost"!)

* *SearchChildDomains*: false (if you are synchronizing, use "true"!)

====

Import the resource definition by clicking the _Configuration_ tab, then _Import object_ tab.
Select _Use embedded editor_ and Copy&paste the content of `ad-resource-advanced-nosync.xml` file into the text area.
Press the "_Import object_" button.
You should see green message "Operation successful".


== See Also

* wiki:.NET+Connector+Server[.NET Connector Server]

* wiki:Connector+Server[Connector Server]

* wiki:Legacy+Active+Directory+Connector+(.NET)[Legacy Active Directory Connector (.NET)]

* wiki:Active+Directory[Active Directory]

* wiki:Keystore+Configuration[Keystore Configuration]


== External links

* What is link:https://evolveum.com/midpoint/[midPoint Open Source Identity & Access Management]

* link:https://evolveum.com/[Evolveum] - Team of IAM professionals who developed midPoint