= Active Directory with LDAP connector
:page-wiki-name: Active Directory with LDAP connector
:page-wiki-id: 21528769
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2015-11-23T14:02:25.046+01:00
:page-wiki-metadata-modify-user: vix
:page-wiki-metadata-modify-date: 2021-03-08T09:04:37.997+01:00
:page-toc: top
:page-upkeep-status: orange
:page-upkeep-note: merge with "Active Directory HOWTO"?

// TODO: merge with "Active Directory HOWTO"?

[%autowidth,cols="h,1"]
|===
| Status
| Provisioning works well. Synchronization works well.

| Recommended connector
| xref:../../connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[]
|===


== Resource Configuration

(Remote connector server is not needed for this connector)


=== Administrative Account for Provisioning/Synchronization

We have successfully tested both provisioning and synchronization of users with the following access privileges using Active Directory domain "Delegate Control" mechanism:

* Create, delete and manage user accounts

* Reset user passwords and force password change at next logon

* Read all user information

* Create, delete and manage groups

* Modify the membership of a group

* Create, delete and manage inetOrgPerson accounts (TODO: is this needed?)

* Reset inetOrgPerson accounts and force password change at next logon (TODO: is this needed?)

* Read all inetOrgPerson information

For LiveSync, you also need "Replicating Directory Changes" permission (please refer to link:https://support.microsoft.com/en-us/help/303972[https://support.microsoft.com/en-us/help/303972] and link:https://support.microsoft.com/en-ae/help/891995/how-to-poll-for-object-attribute-changes-in-active-directory-on-window[https://support.microsoft.com/en-ae/help/891995/how-to-poll-for-object-attribute-changes-in-active-directory-on-window]).


== Recommended Connector

*Framework:* ConnId +
*Bundle:* com.evolveum.polygon.connector-ldap +
*Version:* most recent stable version +
*Connector:* com.evolveum.polygon.connector.ldap.ad.AdLdapConnector


== Connector Configuration

(currently, no published documentation)

[NOTE]
.Active Directory LDAP Strangeness
====
Active Directory in the default configuration is not really LDAPv3-compliant server.
It has many quirks, extensions, modification and twists the LDAP standard almost beyond recognition.
The LDAP connector was modified to survive this brutal "intepretation" of the LDAP specifications.
However, there are many things that needs to be taken into account when configuring AD resource:

* `instanceType`, `nTSecurityDescriptor` and `objectCategory` are formally defined as mandatory attributes in the `top` object class (!!!). This means they are (formally) mandatory for all objects accessed using LDAP connection.
But the reality is different.
It seems to be OK to create an object without these attributes.
Therefore for a proper operation of midPoint we recommend to modify the schema using the `limitations` mechanism in midPoint xref:/midpoint/reference/resources/resource-configuration/schema-handling/[Resource Schema Handling] by setting `minOccurs=0`. (This is already done in the sample referenced below.)

* The objects can easily have attributes that are not defined in any object classes that they have.
E.g. a normal user (the `user` object class) may have attribute `info`. If such extra attributes are used in your AD instance then the best way is to configure them as operational attributes in the connector configuration and define them explicitly in xref:/midpoint/reference/resources/resource-configuration/schema-handling/[Resource Schema Handling] (see bug:MID-3379[]).
====

=== Resource Configuration Example

[source,xml]
----
<connectorConfiguration xmlns:icfc="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/connector-schema-3">
        <icfc:configurationProperties xmlns:icfcldap="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/com.evolveum.polygon.connector-ldap/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector">
            <icfcldap:host>ad.example.com</icfcldap:host>
            <icfcldap:port>636</icfcldap:port>
            <icfcldap:baseContext>DC=evolveum,DC=com</icfcldap:baseContext>
            <icfcldap:bindDn>CN=midpoint,CN=Users,DC=evolveum,DC=com</icfcldap:bindDn>
            <icfcldap:connectionSecurity>ssl</icfcldap:connectionSecurity>
            <icfcldap:bindPassword>
                <t:clearValue>secret</t:clearValue>
            </icfcldap:bindPassword>
        </icfc:configurationProperties>
        <icfc:resultsHandlerConfiguration>
            <icfc:enableNormalizingResultsHandler>false</icfc:enableNormalizingResultsHandler>
            <icfc:enableFilteredResultsHandler>false</icfc:enableFilteredResultsHandler>
            <icfc:enableAttributesToGetSearchResultsHandler>false</icfc:enableAttributesToGetSearchResultsHandler>
        </icfc:resultsHandlerConfiguration>
    </connectorConfiguration>

----


=== Resource Sample

link:https://github.com/Evolveum/midpoint-samples/blob/master/samples/resources/ad-ldap/ad-ldap-medusa-medium.xml[See resource sample].


=== Limitations

* Active Directory LDAP schema is violating LDAP standards and best practices in numerous ways.
The connector is build to tolerate these "quirks" in the AD schema.
However the underlying LDAP library may complain about the schema issues.
It is usually safe to ignore these warnings.


== Notes

[TIP]
====
Note: to avoid clear-text password visible in the repository, please refer to xref:/midpoint/reference/resources/resource-configuration/string-to-protectedstring-connector-configuration/[String to ProtectedString Connector Configuration].
====


[NOTE]
.Full Active Directory Schema
====
Active Directory has huge schema.
The schema when encoded in XSD has several megabytes.
This might take several hundreds of megabytes of memory when processed.
Make sure that your midpoint instance has enough memory (heap) to handle that.
The impact of AD schema can be limited by reducing the number of object classes that are processed by midPoint:

[source]
----
    <schema>
       <generationConstraints>
            <generateObjectClass>ri:user</generateObjectClass>
            <generateObjectClass>ri:group</generateObjectClass>
        </generationConstraints>
    </schema>
----

See also bug:MID-2716[]

====


[NOTE]
.Explicit Referential Inrtegrity
====
We recommend to turn off explicitReferentialIntegrity for associations with groups.
Active Directory will maintain the group membership after account rename automatically.

Example:

[source,xml]
----
...
<association>
    <ref>ri:group</ref>
    <displayName>AD Group Membership</displayName>
    <kind>entitlement</kind>
    <intent>group</intent>
    <direction>objectToSubject</direction>
    <associationAttribute>ri:member</associationAttribute>
    <valueAttribute>ri:dn</valueAttribute>
    <shortcutAssociationAttribute>ri:memberOf</shortcutAssociationAttribute>
    <shortcutValueAttribute>ri:dn</shortcutValueAttribute>
    <explicitReferentialIntegrity>false</explicitReferentialIntegrity>
</association>
...
----

====



== See Also

* xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)]

* wiki:Active+Directory+Tips&Tricks[Active Directory Tips&Tricks]

* wiki:Active+Directory+Multi-Domain[Active Directory Multi-Domain]

* wiki:Active+Directory+with+the+legacy+.NET+connector[Active Directory with the legacy .NET connector]

* wiki:AD+Connector+Design+Notes[AD Connector Design Notes]


== External links

* What is link:https://evolveum.com/midpoint/[midPoint Open Source Identity & Access Management]

* link:https://evolveum.com/[Evolveum] - Team of IAM professionals who developed midPoint

* link:http://ldapwiki.com/wiki/WILL_NOT_PERFORM[WILL_NOT_PERFORM] - wiki page explaining a lot of error messages returned by Active Directory