---
layout: connector-page
display-order: 500
functionality-status: stable
development-status: active
support-status: active
origin: Provision IAM
support-provided-by: Evolveum
target-systems: Box
connector-protocol: Box cloud services
source-url-master: https://github.com/Evolveum/connector-box
description: Identity connector for Box cloud services using the official SDK.
documentation-link: https://github.com/Evolveum/connector-box[https://github.com/ExclamationLabs/connector-box]
---
= Box Connector (SDK)

This is a fork of the original repository which can be found link:https://github.com/ExclamationLabs/connector-box[here].
The development status of the parent project seems to be dormant so this fork will continue independently of the parent project.
This connector supports box.com using the official SDK.

[%autowidth,cols="h,1,1"]
|===
| Schema
| YES
|

| Provisioning
| YES
|

| Live Synchronization
| NO
|

| Password
| NO
|

| Activation
| YES
| Can be simulated via the "status" attribute

| Filtering changes
|
| currently limited

| Paging support
| NO
|

| Native attribute names
| YES
|

| Scripting
| NO
|

| Native references
| NO
|

| Last login date
| NO
|

|===

== Setup

- In the box link:https://developer.box.com[developer portal]
- Turn on Enterprise in Application Access section in Developer Console for the app
- Turn on Generate User Access Tokens in Advanced Features section in Developer Console for the app
- Enable JWT https://developer.box.com/docs/authentication-with-jwt
- Generate a keypair and download the file

[source,json]
----
{
  "boxAppSettings": {
    "clientID": "thisisaclientidthatwouldbepresentinthisfileifyoudiditright",
    "clientSecret": "thisisaclientsecretthatwouldbepresentinthisfileifyoudiditright",
    "appAuth": {
      "publicKeyID": "yourpublickeyid",
      "privateKey": "-----BEGIN ENCRYPTED PRIVATE KEY-----\nTHISISNTAREALPRIVATEKEYBUTIFITWEREITWOULDBEAWESOME\n-----END ENCRYPTED PRIVATE KEY-----\n",
      "passphrase": "haveyouthepassphras"
    }
  },
  "enterpriseID": "88888888"
}
----

== Configuration Properties

[cols="1,1,3", options="header"]
|===
| Item | Required | Description

| JWT Config File Path
| NO
| File path for the JWT Config File

| JWT Config JSON
| NO
| JSON String of the JWT Config File

| HTTP Proxy Host
| NO
| Hostname for the HTTP Proxy

| HTTP Proxy Port
| NO
| Port for the HTTP Proxy

| HTTP Proxy User
| NO
| Username for the HTTP Proxy Authentication

| HTTP Proxy Password
| NO
| Password for the HTTP Proxy Authentication

| Group Admin Default Permission - can_create_accounts
| NO
| If true, when assigned to a group as group admin, the user has "can_create_accounts" permission by default

| Group Admin Default Permission - can_edit_accounts
| NO
| If true, when assigned to a group as group admin, the user has "can_edit_accounts" permission by default

| Group Admin Default Permission - can_instant_login
| NO
| If true, when assigned to a group as group admin, the user has "can_instant_login" permission by default

| Group Admin Default Permission - can_run_reports
| NO
| If true, when assigned to a group as group admin, the user has "can_run_reports" permission by default

| Maximum retries
| NO
| Configure how many times API will retry calls (Default: 5)

| Connection Timeout (in milliseconds)
| NO
| Set up how log (in milliseconds) API waits to establish connection (Default: 10000)

| Read Timeout (in milliseconds)
| NO
| Set up how log (in milliseconds) API waits to read data from connection (Default: 10000)

|===

== See Also

* https://github.com/ExclamationLabs/connector-box
