= Query Language Design
:page-nav-title: Query Language

NOTE: All examples are only for discussion and does not represent any current
functionality

== Work Items

.Query Language Support
1. Design grammar and parser for Query Language
2. Implement transformation from Query language to Java Query API
3. Extends Prism, Query API and in-memory implementation for missing concepts
  * ExistsFilter for:
    ** <<Exists>> support (no nested filter)
    ** <<Matches Empty>> support
    ** <<Matches>> support for Object Reference and PolyString. Two possible options:
    *** Short term - Matches delegates to special code for Object Reference and PolyString
    *** Long term (Prism 5) - Allow item path to reference nested "structured simple" value
        elements
4. Implement repository support for new Query API concepts
  * Extends 'repo-sql-impl' to support new Query API concepts
  * Implement Query / language Query API support in new repository

.Custom Dashboard Support
 * Design simple "grouping" dashboard model and APIs for it
 * Design experimental dashboard model with SQL query support

== Basic Concepts


Filter:: A set of conditions / predicates used to select subset of data
Query:: Combination of filter and transformation / ranking / ordering specification to retrieve set of data

== Filters

=== Logic Filters

Logic filters are use to compose / modify multiple filters together, currently
there are 3 logic filters present:

<<And>>::
  Object / item must match all of specified filters.
<<Or>>::
  Object / item matches any of specified filters.
<<Not>>::
  Negates subfilter, object / item must not match filter.


==== And
Matches if all subfilters matches.

.Grammar
[source]
----
AndFilter: Filter "AND" Filter ("AND" Filter)*
----

.Examples
[source]
----
fName="Foo" AND lName="Bar" <1>
fName="Foo" AND lName="Bar" AND birthDate="31-12-1970" <2>
fName="Foo" AND ( lName="Bar" OR lName="Baz" ) <3>
----
<1> Matches objects with fName "Foo" and lName "Bar"
<2> Multiple AND conditions
<3> Combination of AND and OR filter

Java Query API: `AndFilter`

==== Or
Matches if any subfilter matches.

.Grammar
[source]
----
OrFilter: Filter "OR" Filter ("OR" Filter)*
----

.Examples
[source]

----
fName="John" OR fName="Bar" <1>
fName="Foo" OR fName="Bar" OR fName="Baz" <2>
fName="Foo" OR ( fName="John" AND lName="Baz" ) <3>
----
<1> fName is John or Bar
<2> fName is John or Bar or Baz
<3> Combination of OR filter and AND filter

Java Query API: `OrFilter`

==== Not

Negates specified filter - matches items, which do not conform to specified nested filter.

`NOT` keyword can be used also between `path` and filter keyword to
improve readability (eg. `path NOT EXISTS` instead of `NOT path EXISTS`).

.Grammar
[source]
----
Negation: "NOT"
NotFilter: Negation Filter
----


.Examples
[source]
----
NOT fName="John" <1>
fName NOT STARTS WITH "John" <2>
assigment NOT EXITS <3>
assigment NOT MATCHES (relationship = "default") <4>
----

Java Query API: `NotFilter`

=== Item Filters

Item filters performs check on item values (reference, property, container) specified by path.

.<<Generic Item Filters>>
  <<Exists>>::
    Matches if specified item has any values.

.<<Property Specific Filters>>
  <<Equals>>::
    Matches if any value equals to any of specified values.
  <<Comparison>>::
    Matches if any value is greater/smaller than specified value.

  <<Starts With>>::
    Matches if any value starts with specified string.
  <<Ends With>>::
    Matches if any value ends with specified string.
  <<Contains>>::
    Matches if any value contains specified substring.

.<<Container Specific Filters>>
  <<Matches>>::
    Matches if specified item has value (container, PolyString or reference) matching subfilter.
  <<Matches Empty>>::
    Matches if specified container has empty value (value with no nested properties or containers).
  <<In Oid>>::
    Matches if container is nested inside object with specified `oid`.

.<<Object Specific Filters>>
  <<Type>>::
    Matches if object is of specified type
  <<In Org>>::
    Matches if object is member of specified organization
  <<Fulltext>>::
    Matches if fulltext search finds specified value


//.Grammar
//[source]
//----
//ItemFilter: Path ItemFilterSpec
//ItemFilterSpec: (FilterNegation)? (  PropertyValueFilter | ExistsFilter | MatchesFilter)
//
//----



==== Exists

Matches is specified item has any value (even empty).

[WARNING]
`NOT EXISTS` also matches, when item does exists (because of non-empty item metadata), but does have any values.


.Grammar
[source]
----
ExistsFilter: path (Negation)? "EXISTS"
----

.Examples
[source]
----
linkRef EXISTS <1>
linkRef NOT EXISTS <2>
assignment NOT EXISTS <3>
assignment NOT EXISTS AND assignment/@assurance > 4 <4>
----
<1> Matches if object reference `linkRef` has any value
<2> Matches if object reference `linkRef` does not have value, or does not exists
<3> Matches if container `assigment` does not have any value, or does not exists
<4> Matches if path `assigment` does not contain any values, but item metadata
for `assigment` are present and ``@assurance` is higher than 4.

Java Query API: `ExistsFilter`, probably some modification needed

=== Property Specific filters

Property-specific filters allows to specify <<Matching Rules,Matching Rule>> for strings, which specifies rules how strings are compared.

.Grammar
[source]
----
PropertyFilterOperand: Comparison
MatchingRule: "[" MatchingRuleName "]"
PropertyValueFilter: PropertyFilterOperand (MatchingRule)? ValueSpecification
----

==== Equals

Matches if any value of specified property is equal to any of right-hand side values

.Not Equals
`!=` is negation - NOT EQUALS - matches if all values of specified property does not equal
to any of right-hand sided values.

.Grammar
----
ComparisionFilter: Path ("!")? "=" (MatchingRule)? MultiValueSpecification
----

.Examples
[source]
----
name =  "jsmith" <1>
fName = lName <2>
primaryIdentifier =[distinguishedName] "UID=jsmith,DC=example,DC=net" <3>
----
<1> Matches if name has value jsmith
<2> Matches if fName has same value as lName
<3> Matches if primaryIdentifier (interpreted as Ldap DN) equals to `UID=jsmith,DC=example,DC=net` LDAP DN

==== Comparison

Filter matches if any values of specified property is smaller/greater then right side value.

.Grammar
[source]
----
Greater: "<"
GreaterOrEqual: ">="
Less: "<"
LessOrEqual: "<="
ComparisisonOperand: Greater | GreaterOrEqual | Less | LessOrEqual
ComparisionFilter: Path ComparisonOperand (MatchingRule)? SingleValueSpecification
----

.Examples
[source]
----

----


==== Starts With

.Grammar
[source]
----
StartsWithFilter: Path "STARTS WITH" (MatchingRule)? ValueSpecification
----

.Examples
[source]
----
lName STARTS WITH "foo"
lNaME STARTS WITH "bar"
----


Java Query API: `SubstringFilter` with `anchorStart=true`

==== Ends With

Grammar
[source]
----
EndsWithFilter: Path "ENDS WITH" (MatchingRule)? ValueSpecification
----

.Examples
[source]
----
----

Java Query API: `SubstringFilter` with `anchorEnd=true`

==== Contains
Matches if any String/PolyString value contains specified substring.

.Grammar
[source]
----
ContainsFilter: Path "CONTAINS" (MatchingRule)? ValueSpecification
----

.Examples
[source]
----
----

Java Query API: `SubstringFilter`

==== Matching Rules

Matching rule allows to further specify how to interpret strings during matching
(comparison, substring or equality).

|===
| Matching Rule | Description

| *default* | Fallback to default matching strategy
| *polyStringOrig* | Tests only original form of PolyString
| *polyStringNorm* | Tests only normalized form of PolyString
| *polyStringStrict* | Compares both forms of PolyString
| *stringIgnoreCase* | Compares strings with ignore case
| *uuid* | Matches strings as UUIDs
| *xml* | Matches strings as XML
| *exchangeEmailAddresses* | Microsoft Exchange EmailAddresses attribute consisting of SMTP:/smtp: prefix and email address. Prefix case is preserved, email address is matched case insensitive.
| *distinguishedName* | Matches strings as LDAP distinguish name

|===

=== Container Specific Filters

==== In Oid

Filter matches if container value is nested in specified object.


.Grammar
[source]
----
filter: IN OID ValueSpecification
----

.Examples
[source]
----
IN OID "eb33bf4e-b093-42ff-9400-6f87c1b9ab2b"
----

Java Query API: InOidFilter


==== Matches

Filter matches if path contains any value which matches specified subfilter
(subfilter criteria are matched against contents of value).

Matches filter can be used also on PolyString and object reference, with following virtual properties:

|===
| Property | Description

2+| *PolyString*
| orig | Original form
| norm | Normalized form

2+| *Object Reference*
| targetOid | Target OID
| targetType | Type of target
| relationship | Relationship
|===




.Grammar
[source]
----
MatchesFilter: path (Negation)? "MATCHES" "(" Filter ")"
----

.Examples
[source]
----
lName MATCHES (norm="smith") <1>
linkRef MATCHES (targetOid="eb33bf4e-b093-42ff-9400-6f87c1b9ab2b") <2>

assignment MATCHES ( relationship="manager") <3>
assignment MATCHES (relationship="manager" AND targetRef/targetOid="eb33bf4e-b093-42ff-9400-6f87c1b9ab2b") <4>


----
<1> lName property matches if PolyString value has norm "smith"
<2> linkRef matches only if targetOid is specified UUID
<3> Matches only if assigment container has value, which has property relationship with manager value. This is same as `assigment/relationship="manager"`
<4>  Matches only if assigment has value, whose properties relatioship and targetRef meet specified criteria


Java Query API: `ExistsFilter`, probably modification needed for PolyString / Object Reference

==== Matches Empty
A special case of <<Matches>> filter which matches empty container value (value which does not have any nested items).

.Grammar
[source]
----
MatchesEmptyFilter: path "MATCHES EMPTY"
----

.Examples
[source]
----
mapping MATCHES EMPTY <1>
----
<1> Matches object, which has empty mapping (mapping containe exists, but one of its value does not have any nested items).

Java Query API: New Filter


=== Object Specific Filters

==== Type


.Grammar
[source]
----
TypeFilter: "TYPE" ValueSpecification "AND" Filter
----

.Examples
[source]
----
TYPE UserType AND fName = "John" <1>
----
<1> Matches user with first name John

==== In Org
Matches if object is member of specified organization or root.

.Grammar
[source]
----
InOrgFilter: "IN ORG" ( ValueSpecification | "ROOT" );
----


==== Fulltext
Filters objects based on fulltext search.

.Examples
[source]
----
FULLTEXT "john"
----







== Java Query API

|===
| Java Filter | Query Language Filters | Description
| AllFilter | N/A | Explicitly match everything
| AndFilter | <<And>> | All subfilters must be true
| EqualFilter | <<Equals>> | True if both sides are equal based on matching rule
| OrFilter | <<Or>> | True if any subfilter is true
| ExistsFilter | <<Matches>> | True if container matching subfilter exists
| FullTextFilter | <<Fulltext>> | True if fulltext database search contains value
| GreaterFilter | <<Comparison>> | True if left side is greater then right side
| InOidFilter | <<In Oid>> | True if container is part of object with specified oid
| LessFilter | <<Comparison>> | True if left side is smaller then right side
| SubstringFilter | <<Starts With>>, <<Contains>>, <<Ends With>> | True if left side contains specified substring
| TypeFilter | <<Type>> and <<And>> | True if object matches type and subfilter
| RefFilter | <<Matches>> | True, if reference matches specification
| NoneFilter | N/A | Always false
| UndefinedFilter | N/A | Special marker filter, always true
| NotFilter | <<Not>> | Logic filter, negates value of subfilter
| OrgFilter | <<In Org>> | True if object is part of organization
|===

== Notes

.Existing Filters to Query Language
|===
| Existing | Right Side | Modifiers | Proposed Name | True State

.3+| Equals
| Value .3+| matchingStrategy | <<Equals>> |Any value of left property matches value on right
| Multiple Values, Path | <<Equals>> | Any value of left property matches any value on right
| Null | NOT <<Exists, EXISTS>> | Property does not have value


| Comparison  | Value | matchingStrategy | <<Comparison>> | Any value of property is smaller / larger / equals then right value.


.4+| Substring .4+| Value, Property

| matchingStrategy, anchorLeft=false, anchorRight=false | <<Contains>> | Any value of property contains any substring from right
| matchingStrategy, anchorLeft=true, anchorRight=false | <<Starts With>> | Any value of property starts with any substring from right
| matchingStrategy, anchorLeft=false, anchorRight=true | <<Ends With>> | Any value of property ends with any substring from right
| matchingStrategy, anchorLeft=true, anchorRight=true | <<Equals>> | Any value of property equals to any string from right

| Ref filter | Value, Property | oidNullAsAny, targetTypeAsAny, relationTypeAsAny | <<Matches>> | Any value of reference matches any value from right side

| Org filter | Value, Property || <<In Org>> | Object is member of organization

| InOid filter | Value, Property ||||

|===


== Discussions

* Assignment as (almost) first-class object? Or make it possible to query any container?
** Still treated as containers, option to query specific containers only

* Ad-hoc joins (joins that do not follow prism reference): do we need them?
** Do not support them, at least for now. But this may change in the future. `Joins` are supported only via object references in <<Path,paths>>
** We would need aliases for objects in order to distuinguish path

* Syntax for "reference match", "polystring match" and similar. Construct is <<Matches>>.

* Are matching rules for polystring a good idea? Maybe we need patterns instead of matching rules.

* Should matching rules be in fact _string_ matching rules?
Do we need other cases, e.g. matching of IP address and netmask?
** Tony: Similar special case is _DistuinguishName_, this feels more like
   separate value types for DN, IP Address with their own matching rules
   (eg. in DB serialized like `dn_orig` and `dn_norm`, where `dn_norm` is used for filters).

* Make sure that NOT queries are supported. E.g. "find users that do not have any linked account".
** Examples
+
[source]
----
TYPE UserType AND linkRef NOT EXISTS

// Users which do not have manager relationship
TYPE UserType AND assigment/targetRef NOT MATCHES (relationship="manager")

TYPE UserType AND assigment/targetRef/relationship != "manager"
----

* How to do "group by" queries?
** Does group by creates ad-hoc schema? *Yes*

** Discussed solution was to provide 2 concepts:
 *** Simple "dashboard"-like model which allows to specify item paths to fetch,
    and apply aggregate operations on these paths (grouping, min, avg, count)
    and filter (this model does not allows for complex grouping / queries - easier to map to database)
 *** Experimental dashboard - Custom schema + query which retrieves data


.Report Syntax proposal
----
statusReport {
  from ShadowType;

  collumn name {
    displayName "Resource";
    source resourceRef/@/name {
      type grouping;
    }
  }
  collumn kind {
    source kind {
      type grouping;
    }
  }
  collumn intent {
    source intent {
      type grouping;
    }
  }
  collumn status {
    source status {
      type grouping;
    }
  }
  collumn count {
    displayName "Count";
    source  {
      count;
    }
  }

}

statusReport {
  from UserType;
  collumn directorate {
    displayName "Name";
    source extension/directorateRef/@/name {
      grouping;
    }
  }
  collumn count {
    source {
      count;
    }
  }
  filter """
    activation/efectiveStatus = disabled
  """;

}
----


.Sample SQL query used for custom overview
----
select

    count(*) AS (prism definiciu),
    r.name_orig,
    s.kind,
    s.intent,
    case s.SYNCHRONIZATIONSITUATION
        when 0 then 'DELETED'
        when 1 then 'UNMATCHED'
        when 2 then 'DISPUTED'
        when 3 then 'LINKED'
        when 4 then 'UNLINKED'
        end as SITUATION,
    s.resourceref_targetoid
from m_shadow s
left join m_resource r on s.resourceref_targetoid=r.oid
group by
    r.name_orig,
    s.kind,
    s.intent,
    s.SYNCHRONIZATIONSITUATION,
    s.resourceref_t
----
