= How to attach metadata mappings to data mappings?

It would be awkward to specify metadata mappings for every data mapping where they should be applied.

Many of the metadata mappings have global applicability. For example, we want to propagate level of assurance
or confidentiality level across mappings without an explicit notion. Or we want to provide value origin
(source/transformation) mapping to values of all or selected items.

Metadata mappings for any given data mapping (DM) are selected from the following pools:

1. Mappings directly attached to the DM.
2. Mappings provided by focus archetype (or archetypes).
3. Mappings provided by object policy configuration.
4. Global metadata mappings.
5. Built-in metadata mappings.

We have to be able to enable/disable processing of metadata mappings for given place:

1. When declaring mapping (at levels 2-5 above) we need to specify which data items it should or should not be applied to.
2. When declaring metadata handling for given mapping (level 1) we need to specify which "inherited" metadata mappings
should or should not be applied.

== Directly attached metadata handling instructions

----
<mapping>
    <source> ... (e.g. givenName, familyName) ... </source>
    <expression> ... </expression>
    <target> ... (e.g. fullName) ... </target>
    <metadataHandling>
       ... either defining mappings directly ...
       ... or select existing mappings to be applied ...
    </metadataHandling>
</mapping>
----

=== Examples of directly attached metadata mapping specification

Specific metadata mapping:

----
<mapping>
    ... source, expresison, target ...
    <metadataHandling>
        <mapping>
            <source>
                <path>extension/loa</path>
            </source>
            <expression>
                <script>
                    <code>custom.getMinLoa(loa)</code>
                </script>
            </expression>
            <target>
                <path>extension/loa</path>
            </target>
        </mapping>
    </metadataHandling>
</mapping>
----

Specific metadata mapping(s) reference - includes the most specific mapping having `extension/loa` as their target.

----
<mapping>
    ... source, expresison, target ...
    <metadataHandling>
        <includeMapping>
            <selection>single</selection>
            <target>
                <path>extension/loa</path>
            </target>
        </includeMapping>
    </metadataHandling>
</mapping>
----

Specific metadata mapping(s) reference - includes mapping(s) by name:

----
<mapping>
    ... source, expresison, target ...
    <metadata>
        <includeMapping>
            <name>loa-mapping</name>
        </includeMapping>
    </metadata>
</mapping>
----

=== Examples of globally defined mappings

This is how we can specify applicability of a metadata mapping specified e.g. in archetype:

----
<archetype ...>
    <archetypePolicy>
        <metadataHandling>
            <mapping>
                ...
                <applicability>
                    <include>
                        <path>fullName</path>
                    </include>
                    <include>
                        <path>extension</path>
                    </include>
                    <exclude>
                        <path>extension/trash</path>
                    /exclude>
                <applicability>
            </mapping>
        </metadataHandling>
    </archetypePolicy>
</archetype>
----

The same can be specified in object policy configuration:

----
<systemConfiguration>
    ...
    <defaultObjectPolicyConfiguration>
        <type>UserType</type>
        ...
        <metadataHandling> ... </metadataHandling>
    </defaultObjectPolicyConfiguration>
    ...
</systemConfiguration>
----

Or even globally:

----
<systemConfiguration>
    ...
    <metadataHandling> ... </metadataHandling>
    ...
</systemConfiguration>
----
