---
layout: personal
job-title: Software Architect
photo: mederly.jpg
academic-titles: Mgr. (MSc), PhD.
profile-github: mederly
profile-linkedin-url: https://www.linkedin.com/in/pavol-mederly-4570859/
evolveum-blog: https://evolveum.com/author/mederly/
---

= Pavol Mederly

== Short Bio

He graduated from the Comenius University with a master degree in computer science and PhD degree from Slovak University of Technology.
He participated in several roles in higher education organizations.
At the time he works as a software architect at Evolveum, being one of the first team members.
He is one of the leading figures in development of midPoint, open source identity management and governance platform.


== Education

* Magister (Mgr., master) degree from https://uniba.sk/[Comenius University]
* Philosophiae Doctor (PhD.) degree from https://www.stuba.sk/[Slovak University of Technology]

== Publications and Talks (selection)

Smart Correlation::
2024, MidPoint Working Group at https://tiime-unconference.eu/[TIIME Unconference]

xref:/talks/files/2023-12-simulations.pdf[Simulations]::
2023, Evolveum Webinar

xref:/talks/files/2022-02-tasks.pdf[Tasks in MidPoint 4.4]::
2022, Evolveum Webinar

xref:/talks/files/2021-05-asynchronous-resources-with-activemq.pdf[Asynchronous resources with ActiveMQ]::
2021, Evolveum Webinar

link:2011-mederly-dissertation.pdf[Semi-automated Construction of Messaging-Based Enterprise Application Integration Solutions]::
2011, dissertation

Construction of messaging-based integration solutions using constraint programming::
2010, Advances in Databases and Information Systems: 14th East European Conference, ADBIS 2010 Novi Sad, Serbia, September 20-24, 2010. With P. Návrat.

Construction of messaging-based enterprise integration solutions using AI planning::
2009, 4th IFIP TC2 Central and East European Conference on Software Engineering Techniques, CEE-SET 2009, Krakow, Poland, October 12-14, 2009. With M. Lekavý, M. Závodský, and P. Návrat.

Service adaptation using AI planning techniques::
2009, Fifth International Conference on Next Generation Web Services Practices, NWeSP 2009 Prague, Czech Republic, September 9-11, 2009. With M. Lekavý and P. Návrat.

link:https://www.eunis.org/eunis2008/papers/p98.pdf[Enterprise service bus at Comenius University in Bratislava]::
2008, EUNIS 2008 VISION IT - Vision for IT in higher education. University of Aarhus. With G. Pálos.


== Project Participation (selection)

xref:/midpoint/[MidPoint]::
since 2011, software architect and key developer

https://github.com/Evolveum/midpoint-studio[MidPoint Studio]::
since 2020, contributor

http://connid.tirasa.net/[ConnId]::
since 2024, contributor
