---
layout: personal
job-title: Software Architect
photo: mederly.jpg
academic-titles: Mgr. (MSc), PhD.
profile-github: mederly
profile-linkedin-url: https://www.linkedin.com/in/pavol-mederly-4570859/
evolveum-blog: https://evolveum.com/author/mederly/
---

= Pavol Mederly

== Short Bio

He graduated from the Comenius University with a master degree in computer science and PhD degree from Slovak University of Technology.
He participated in several roles in higher education organizations.
At the time he works as a software architect at Evolveum, being one of the first team members.
He is one of the leading figures in development of midPoint, open source identity management and governance platform.


== Education

* Magister (Mgr., master) degree from https://uniba.sk/[Comenius University]
* Philosophiae Doctor (PhD.) degree from https://www.stuba.sk/[Slovak University of Technology]

== Publications and Talks (selection)

Smart Correlation::
2024, MidPoint Working Group at https://tiime-unconference.eu/[TIIME Unconference]

xref:/talks/files/2023-12-simulations.pdf[Simulations]::
2023, Evolveum Webinar

xref:/talks/files/2022-02-tasks.pdf[Tasks in MidPoint 4.4]::
2022, Evolveum Webinar

xref:/talks/files/2021-05-asynchronous-resources-with-activemq.pdf[Asynchronous resources with ActiveMQ]::
2021, Evolveum Webinar

== Project Participation (selection)

xref:/midpoint/[MidPoint]::
since 2011, software architect and key developer

https://github.com/Evolveum/midpoint-studio[MidPoint Studio]::
since 2020, contributor

http://connid.tirasa.net/[ConnId]::
since 2024, contributor
