= AsciiDoc Fairy Tale
:page-display-order: 91
This is a nice short fairy tale.

== Introduction

Once upon a time there was a small kingdom.
The king was old and *very wise*.

== Getting to the Point

The king decreed that everybody in the kingdom should use `AsciiDoc`.
`AsciiDoc` looked very strange to the people of the kingdom, because they haven't seen anything but Microsoft _Word_ in their entire life.
That `AsciiDoc` thing looked difficult and ugly.
The people were not happy.
They complained.

But the king was wise and persistent.
He persuaded people to try `AsciiDoc`.
One by one the people started to understand the benefits of long-term maintainability and increased productivity, such as:

* Easy maintenance of the files in a _version control system_ (`gitlab`).

* Easy conversion of the documents to different formats (HTML, PDF, EPUB).

* No need to care about the styling details (font sizes, spacing, text flow) that break *all the time* in office text processors.

== Conclusion

Finally, the people understood.
And they lived happily ever after.
