= About
:page-display-order: 999

Site for Evolveum public documentation and other files.
This site contains majority of xref:/midpoint/[midPoint documentation].

== Writing Documentation

Most of the documents on this site are written in https://asciidoc.org/[AsciiDoc] format, maintained in https://github.com/Evolveum/docs[Evolveum docs repository at GitHub].

Please see xref:writing-documentation/[] for the details.

== Documentation Dynamics

We will try to keep the documentation updated as we progress with the development of midPoint and related projects.
However, please expect some degree of "motion blur" all the time, as the system is evolving continually.
The architecture and design are always a bit ahead of the development, and these pages provide both description of what _is_ and what is _planned_ to be.
The documentation usually lacks behind the development slightly, especially for experimental features.
This is quite normal for an open source product documentation.
In case that we are missing something, you can contact us.
However, the best way to make sure there is a quality documentation is to purchase a xref:/support/subscription-sponsoring/[midPoint subscription].

== Copyright and Licensing

Please note that the content of docs site is licensed under the terms of *https://creativecommons.org/licenses/by-nc-nd/4.0/[Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0) license]*.
There are limitations to the use of both the content of the site, and its source code.
Please also note, that the license does not cover use of trademarks, which may be used on this site.

Generally speaking, Contributor License Agreement (CLA) is needed to contribute to the content of this site.

Please see xref:/copyright/[] for details.

== Under The Hood

Powered by:

* https://jekyllrb.com/[Jekyll] generates the site and provides site structure

* https://asciidoctor.org/[Asciidoctor] renders Asciidoc files, integrated with Jekyll by https://github.com/asciidoctor/jekyll-asciidoc[jekyll-asciidoc]

* https://getbootstrap.com/[Bootstrap] set the style

* A bunch of custom https://www.ruby-lang.org/[Ruby] code glues it all together.
