= IGA Use Cases: Access certification
:page-nav-title: Access certification use-cases
:page-display-order: 400
:page-toc: top
:toclevels: 3
:sectnums:
:sectnumlevels: 3

[#_all_user_assignments_should_be_displayed_in_certification]
== All user assignments should be displayed in certification.

Only the roles that are directly assigned are displayed in the certification campaign. But business roles are providing access to multiple applications that is not explicitly displayed.

To make better decision during the access review, the person who certifies user's access needs to see all assigned roles together with application these roles provide access to.
He should obtain the same information that is described in the use-case xref:visibility-uc.adoc#_what_is_the_access_of_the_user[What is the access of the user].

Of course, indirectly assigned attributed can't be removed individually. But it must be visible in UI what is "the source" of the indirect assignment.
E.g. the person who certifies user's access shall see that the role _AppRoleXY_ providing access to _application XY_ is indirectly assigned because of assignment of role _BusinessABC_

Sometimes the amount of indirect assignments may be overwhelming - especially when person already knows the business role details. Functionality, that hides/displays indirect assignments on demand would be helpful.