---
layout: personal
job-title: Backend technical leader and developer
#photo: tkacik.jpg
academic-titles: Bc.
profile-github: tonydamage
profile-linkedin-url: https://www.linkedin.com/in/antontkacik/
evolveum-blog: https://evolveum.com/author/tony/
---

= Anton Tkáčik

== Short Bio

He graduated from Pan-European University with bachelor degree in computer science.
He participated in several development and leading roles at OpenDaylight projects, creating and driving high performance model driven architecture in several computer networking use-cases.   
At the time he works as a Backend technical leader and developer at Evolveum and is responsible for performance and model-driven efforts at MidPoint.
His main areas of interest are model-driven platforms and domain specific languages. 


== Education

* Bachelor (Bc.) degree from https://www.paneurouni.com/[Pan-European University]


== Publications and Talks (selection)

link:https://docs.evolveum.com/talks/files/2024-04-securing-midpoint-deployments.pdf[Securing MidPoint Deployments]::
2024, Evolveum Webinar

Securing MidPoint Deployments::
2024, MidPoint Working Group at https://tiime-unconference.eu/[TIIME Unconference]


link:https://docs.evolveum.com/talks/files/2022-01-upgrade-guide.pdf[Upgrade Guide]:: 
2022, Evolveum Webinar

link:https://docs.evolveum.com/talks/files/2021-05-query-language.pdf[Axiom Query]::
2021, Evolveum Webinar


link:https://www.youtube.com/watch?v=CsJZCLWy05g[How to Design OpenDaylight Applications for Best Scale and Performance]::
2015, Presentation at OpenDaylight Summit 2015 (with Jan Medved and Robert Varga)

link:https://www.youtube.com/watch?v=uBnDJNsd6Qo[Developing OpenDaylight Apps with MD-SAL]::
2014, Presentation at OpenDaylight Summit 2014 (with Jan Medved, Ed Warnicke)

// Here I am not listed in main authors (due to size limit), but mentioned in cotributors section, was co-author of original draft (below and original model)
link:https://datatracker.ietf.org/doc/html/rfc8345[RFC 8345: A YANG Data Model for Network Topologies]::
2018, Internet Requests for Comments, RFC Editor

// Here I am not listed in main authors (due to size limit), but mentioned in cotributors section, was co-author of original draft (below and original model)
link:https://datatracker.ietf.org/doc/html/rfc8346[RFC 8346: A YANG Data Model for Layer 3 Topologies]::
2018, Internet Requests for Comments, RFC Editor


link:https://datatracker.ietf.org/doc/draft-ietf-i2rs-yang-network-topo/02/[Clemm A., Medved J., Varga R.,  Tkacik A, et. al.: A Data Model for Network Topologies]::
2015, Internet Requests for Comments, RFC Editor

link:https://ieeexplore.ieee.org/document/6918985[OpenDaylight: Towards a Model-Driven SDN Controller architecture]::
2014, Proceeding of IEEE International Symposium on a World of Wireless, Mobile and Multimedia Networks 2014


== Project Participation (selection)

xref:/midpoint/[MidPoint]::
since 2019, software architect, developer

link:https://www.opendaylight.org/[OpenDaylight]::
2013-2016, project leader, commiter, contributor 
