---
layout: release
release-version: '4.5'
visibility: hidden
---
= MidPoint 4.5 "Nightingale"
:release-version: 4.5
:page-liquid:
:page-toc: top

Release {release-version} is a TODO midPoint release code-named _Nightingale_. The {release-version} release brings ...

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
    Florence Nightingale (1820 – 1910) was ...
</p>
<p>
    Therefore midPoint ...
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

== Changes With Respect To Version 4.4

=== New Features and Improvements

* Major features

** Identity matching, supporting InCommon ID Match integration

** Notification improvements

** OpenID Connect support


* User interface improvements

** Improved system configuration pages

** Miscellaneous GUI usability and user experience updates

** User interface for editing notification message templates


* Miscellaneous improvements

** Axiom query language expressions

** New xref:/midpoint/reference/security/authentication/flexible-authentication/configuration/#sequence-configuration[`focusBehaviorUpdate` option] to avoid update of last login timestamp in user object.

** Native fail-over support in xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP connector]

** Significantly improved xref:/midpoint/reference/expressions/mappings/[reference documentation of mappings]


* Internal improvements

** New code generator, replacing legacy JAXB/JAXWS generator

=== Deprecation, Feature Removal And Incompatible Changes

* Explicit deployment of midPoint (in a form of WAR file) to Tomcat web container is no longer supported.
This mechanism was deprecated since midPoint 4.1.
Deploying midPoint as a xref:/midpoint/reference/deployment/stand-alone-deployment/[stand-alone application] is the only supported method now.

* PostgreSQL 10 is no longer supported.

* xref:/midpoint/reference/repository/generic/[Generic repository implementation] (which was the only available repository implementation in midPoint 4.2 and earlier) was deprecated in midPoint 4.4.
It was replaced by xref:/midpoint/reference/repository/native-postgresql/[native PostgreSQL repository].
It is *strongly* recommended for all new deployments to use xref:/midpoint/reference/repository/native-postgresql/[native PostgreSQL repository].
Moreover, it is recommended that all existing deployments migrate to the xref:/midpoint/reference/repository/native-postgresql/[native PostgreSQL repository] as soon as possible.

=== Releases Of Other Components

* New version of LDAP connector bundle (including xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] and xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector]) was released during the course of midPoint {release-version} development.
  New version of LDAP connector includes native fail-over functionality.

* New version of xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable Connector] was released and bundled with midPoint.

* TODO Docker images were released in Docker Hub: https://hub.docker.com/layers/evolveum/midpoint/4.4/images/sha256-015e67f440c44e2cf10a01cef0c324f43e9fbaae64fb0fa09c5696957533825c?context=explore[4.4] and https://hub.docker.com/layers/evolveum/midpoint/4.4-alpine/images/sha256-60ffb2db37860dd09c66cafcb88e86ab1e8aa2c096aacaa18450d5098b3a8922?context=explore[4.4-alpine].

* Overlay project examples will be released soon after released together with midPoint {release-version} release.

* xref:/midpoint/tools/studio/[MidPoint Studio] version {release-version} will be released soon after midPoint {release-version} release.

* xref:/midpoint/devel/prism/[Prism] data representation library was separated from midPoint code into ist own project.
It was released together with midPoint {release-version}.

* TODO xref:/midpoint/reference/interfaces/midpoint-client-java/[Midpoint client Java library] will be released soon after released together with midPoint {release-version} release.


++++
{% include release-quality.html %}
++++

=== Limitations

Following list provides summary of limitation of this midPoint release.

* Functionality that is marked as xref:/midpoint/versioning/experimental/[Experimental Functionality] is not supported for general use (yet).
Such features are not covered by midPoint support.
They are supported only for those subscribers that funded the development of this feature by the means of xref:/support/subscription-sponsoring/[subscriptions and sponsoring] or for those that explicitly negotiated such support in their support contracts.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector].
Support for LDAP connector is included in standard midPoint support service, but there are limitations.
This "bundled" support only includes operations of LDAP connector that 100% compliant with LDAP standards.
Any non-standard functionality is explicitly excluded from the bundled support.
We strongly recommend to explicitly negotiate support for a specific LDAP server in your midPoint support contract.
Otherwise only standard LDAP functionality is covered by the support.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] page for more details.

* MidPoint comes with bundled xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)].
Support for AD connector is included in standard midPoint support service, but there are limitations.
Only some versions of Active Directory deployments are supported.
Basic AD operations are supported, but advanced operations may not be supported at all.
The connector does not claim to be feature-complete.
See xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)] page for more details.

* MidPoint user interface has flexible (fluid) design, it is able to adapt to various screen sizes, including screen sizes used by some mobile devices.
However, midPoint administration interface is also quite complex and it would be very difficult to correctly support all midPoint functionality on very small screens.
Therefore, midPoint often works well on larger mobile devices (tablets) it is very likely to be problematic on small screens (mobile phones).
Even though midPoint may work well on mobile devices, the support for small screens is not included in standard midPoint subscription.
Partial support for small screens (e.g. only for self-service purposes) may be provided, but it has to be explicitly negotiated in a subscription contract.

* There are several add-ons and extensions for midPoint that are not explicitly distributed with midPoint.
This includes Java client library, various samples, scripts, connectors and other non-bundled items.
Support for these non-bundled items is limited.
Generally speaking those non-bundled items are supported only for platform subscribers and those that explicitly negotiated the support in their contract.

* MidPoint contains a basic case management user interface.
This part of midPoint user interface is not finished.
The only supported part of this user interface is the part that is used to process requests and approvals.
Other parts of case management user interface are considered to be experimental, especially the parts dealing with manual provisioning cases.

* Production deployments of midPoint in Microsoft Windows environment are not supported.
Microsoft Windows is supported only for evaluation, demo, development and similar non-production purposes.

* Identity matching developed in midPoint 4.5 is supported only for integration with ID Match API.
Newly-developed internal correlators and all other correlation functionality developed in midPoint 4.5 is considered _experimental_.
The correlation functionality present in midPoint 4.4 (and older) is still fully functional and supported.

This list is just an overview, it may not be complete.
Please see the documentation regarding detailed limitations of individual features.

== Platforms

MidPoint is known to work well in the following deployment environment.
The following list is list of *tested* platforms, i.e. platforms that midPoint team or reliable partners personally tested with this release.
The version numbers in parentheses are the actual version numbers used for the tests.

It is very likely that midPoint will also work in similar environments.
But only the versions specified below are supported as part of midPoint subscription and support programs - unless a different version is explicitly agreed in the contract.

=== Operating System

MidPoint is likely to work on any operating system that supports the Java platform.
However, for *production deployment*, only some operating systems are supported:

* Linux (x86_64)

We are positive that MidPoint can be successfully installed on other operating systems, especially macOS and Microsoft Windows desktop.
Such installations can be used to for evaluation, demonstration or development purposes.
However, we do not support these operating systems for production environments.
The tooling for production use is not maintained, such as various run control (start/stop) script, low-administration and migration tools, backup and recovery support and so on.

=== Java

* OpenJDK 11 (11.0.14).

* OpenJDK 17.
This is a *recommended* platform.

OpenJDK 17 is a recommended Java platform to run midPoint.

Support for Oracle builds of JDK is provided only for the period in which Oracle provides public support (free updates) for their builds.
As far as we are aware, free updates for Oracle JDK 11 are no longer available.
Which means that Oracle JDK 11 is not supported for MidPoint anymore.
MidPoint is an open source project, and as such it relies on open source components.
We cannot provide support for platform that do not have public updates as we would not have access to those updates, and therefore we cannot reproduce and fix issues.
Use of open source OpenJDK builds with public support is recommended instead of proprietary builds.


=== Databases

Since midPoint 4.4, midPoint comes with two repository implementations: _native_ and _generic_.
Native PostgreSQL repository implementation is strongly recommended for all production deployments.

See xref:/midpoint/reference/repository/repository-database-support/[] for more details.

Since midPoint 4.0, *PostgreSQL is the recommended database* for midPoint deployments.
Our strategy is to officially support the latest stable version of PostgreSQL database (to the practically possible extent).
PostgreSQL database is the only database with clear long-term support plan in midPoint.
We make no commitments for future support of any other database engines.
See xref:/midpoint/reference/repository/repository-database-support/[] page for the details.
Only a direct connection from midPoint to the database engine is supported.
Database and/or SQL proxies, database load balancers or any other devices (e.g. firewalls) that alter the communication are not supported.

==== Native Database Support

xref:/midpoint/reference/repository/native-postgresql/[Native PostgreSQL repository implementation] is developed and tuned specially for PostgreSQL database, taking advantage of native database features, providing improved performance and scalability.

This is now the *primary and recommended repository* for midPoint deployments.
Following database engines are supported:

* PostgreSQL 14 or 13

==== Generic Database Support (deprecated)

xref:/midpoint/reference/repository/generic/[Generic repository implementation] is based on object-relational mapping abstraction (Hibernate), supporting several database engines with the same code.
Following database engines are supported with this implementation:

* H2 (embedded).
Supported only in embedded mode.
Not supported for production deployments.
Only the version specifically bundled with midPoint is supported. +
H2 is intended only for development, demo and similar use cases.
It is *not* supported for any production use.
Also, upgrade of deployments based on H2 database are not supported.

* PostgreSQL 14, 13, 12, 11.

* Oracle 12c

* Microsoft SQL Server 2019, 2016 SP1

Support for xref:/midpoint/reference/repository/generic/[generic repository implementation] together with all the database engines supported by this implementation is *deprecated*.
It is *strongly recommended* to migrate to xref:/midpoint/reference/repository/native-postgresql/[native PostgreSQL repository implementation] as soon as possible.
See xref:/midpoint/reference/repository/repository-database-support/[] for more details.

=== Supported Browsers

* Firefox
* Safari
* Chrome
* Edge
* Opera

Any recent version of the browsers is supported.
That means any stable stock version of the browser released in the last two years.
We formally support only stock, non-customized versions of the browsers without any extensions or other add-ons.
According to the experience most extensions should work fine with midPoint.
However, it is not possible to test midPoint with all of them and support all of them.
Therefore, if you chose to use extensions or customize the browser in any non-standard way you are doing that on your own risk.
We reserve the right not to support customized web browsers.

== Important Bundled Components

[%autowidth]
|===
| Component | Version | Description

| Tomcat
| 9.0.48
| Web container

| ConnId
| 1.5.0.18
| ConnId Connector Framework

| xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP connector bundle]
| 3.4
| LDAP and Active Directory

| xref:/connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/[CSV connector]
| 2.4
| Connector for CSV files

| xref:/connectors/connectors/org.identityconnectors.databasetable.DatabaseTableConnector/[DatabaseTable connector]
| 1.4.9.1
| Connector for simple database tables

|===

++++
{% include release-download.html %}
++++

== Upgrade


TODO


Upgrade/changes:

Notifications:

* Previously, if no transport was specified for `customNotifier`, `customTransport` was quietly implied.
This is no longer the case and the transport must be explicitly mentioned just like in any other notifier.
Custom notifier is actually in no way tied to the custom transport only - any transport can be used.

* Previously, schema allowed nesting notifiers, e.g. putting `simpleFocalObjectNotifier` inside `timeValidityNotifier` or any other notifier.
This is no longer possible, if there is any nesting of concrete notifiers in your System configuration object it must be removed.
Nesting inside `handler` element and inside `chained`/`forked` blocks is fine, although the latter is deprecated now.
This nested notifiers didn't do anything anyway, so it is unlikely anyone used them.

Plugins/overlays:

* For performance reasons, user interface code is scanning only `com.evolveum` packages on classpath.
This can be changed using settings in `application.yml` file.