---
layout: release
release-version: '4.5'
visibility: hidden
---
= MidPoint 4.5 "Nightingale"
:release-version: 4.5
:page-liquid:
:page-toc: top

Release {release-version} is a TODO midPoint release code-named _Nightingale_. The {release-version} release brings ...

++++
{% include release-data.html %}
++++

++++
{% capture dedicationContent %}
<p>
    Florence Nightingale (1820 – 1910) was ...
</p>
<p>
    Therefore midPoint ...
</p>
{% endcapture %}
{% include release-dedication.html content=dedicationContent %}
++++

TODO

Notifications:

* Previously, if no transport was specified for `customNotifier`, `customTransport` was quietly implied.
This is no longer the case and the transport must be explicitly mentioned just like in any other notifier.
Custom notifier is actually in no way tied to the custom transport only - any transport can be used.

* Previously, schema allowed nesting notifiers, e.g. putting `simpleFocalObjectNotifier` inside `timeValidityNotifier` or any other notifier.
This is no longer possible, if there is any nesting of concrete notifiers in your System configuration object it must be removed.
Nesting inside `handler` element and inside `chained`/`forked` blocks is fine, although the latter is deprecated now.
This nested notifiers didn't do anything anyway, so it is unlikely anyone used them.
