= ConnectorHostType
:page-archived: true
:page-outdated: true
:page-wiki-name: ConnectorHostType
:page-wiki-id: 4424215
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2012-06-27T19:45:16.031+02:00
:page-wiki-metadata-modify-user: katkav
:page-wiki-metadata-modify-date: 2015-05-19T10:36:31.187+02:00

`ConnectorHost` defines a host where a connector is running.
It may be a definition for remote connector host, remote connector framework or a remote "gateway".
It is not a definition of a single connector but rather a definition of host that can host several connectors.

This is a generic concept of a connector host, not specific to any connector framework.
It can be extended with a framework-specific configuration using the usual "extension" element if needed.

[%autowidth,cols="h,1,1"]
|===
| Property | Type | Description

| hostname
| string
| Hostname or IP address of the connector host.


| port
| string +
 optional
| Port number of the remote service.
If not present, default port number is assumed by the implementation (may depend of connector framework).


| sharedSecret
| ProtectedStringType +
 optional
| Shared secret used to authenticate client (midPoint) to the host.


| protectConnection
| boolean +
 optional
| If set to true then a protected connection will be established (usually SSL).
(default: false)


| timeout
| int +
 optional
| Timeout (in milliseconds) used when initially connecting to the host or during other connections when timeout is not otherwise specified.


|===


== Samples

.ICF Remote Connector Server Host Example
[source,xml]
----
<connectorHost xmlns="http://midpoint.evolveum.com/xml/ns/public/common/common-3" xmlns:t="http://prism.evolveum.com/xml/ns/public/types-3">
	<name>ICF Connector server on localhost:8759</name>
	<hostname>localhost</hostname>
	<port>8759</port>
	<sharedSecret>
		<t:clearValue>secret</t:clearValue>
	</sharedSecret>
</connectorHost>

----