= ObjectType
:page-archived: true
:page-outdated: true:page-wiki-name: ObjectType
:page-wiki-id: 17761024
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2015-03-24T11:10:37.995+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2015-03-24T11:10:37.995+01:00


== Description

ObjectType is a common superclass of all midPoint objects.
It defines the basic properties that all the objects have.

All objects are identified by xref:/midpoint/devel/prism/concepts/object-identifier/[OID]. The OID is an immutable identifier (usually UUID).
Except the OID all the objects have human-readable name.
The name is usually unique for each object type, but this is not a strict requirement.

Note: object type is fixed, it cannot be changed.
The object retains its type from the time it was created to the end of its life.

TODO: extensible

TODO: polystring


== SchemaDoc

Following links can be used to get full an authoritative description of the object schema:

[%autowidth]
|===
| Relase | SchemDoc link

| Latest stable
| link:https://www.evolveum.com/downloads/midpoint/latest/schemadoc/http---midpoint-evolveum-com-xml-ns-public-common-common-3/object/ObjectType.html[ObjectType]


| Development
| link:http://athena.evolveum.com/builds/master/latest/schemadoc/http---midpoint-evolveum-com-xml-ns-public-common-common-3/object/ObjectType.html[ObjectType]


|===


== Important Items

User object contains following frequently used items:

[%autowidth,cols="h,1,1"]
|===
| Property | Type | Description

| name
| PolyString
| Human-readable, mutable name of the object.
It may also be an identifier (login name, group name).
It is usually unique in the respective context of interpretation.
E.g. the name of the UserType subtype is usually unique in the whole system.
The name of the ShadowType subtype is usually unique in the scope of resource (target system) that it belongs to. +
The name may not be human-readable in a sense to display to a common end-user.
It is intended to be displayed to IDM system administrator.
Therefore it may contain quite a "ugly" structures such as LDAP DN or URL. +
Name is mutable.
It is considered to be ordinary property of the object.
Therefore it can be changed by invoking usual modifyObject operations.
However, change of the name may have side effects (rename process).


| description
| string +
optional
| Free-form textual description of the object.
This is meant to be displayed in the user interface.


| extension
| any +
optional
| Extension container that provides generic extensibility mechanism.
Almost any extension property can be placed in this container.
This mechanism is used to extend objects with new properties.


| parentOrgRef
| ObjectReferenceType +
optional, multi
| Set of the orgs (organizational units, projects, teams) that the object relates to.
This usually means that the object belongs to them but it may have other meanings as well (e.g. user manages an organizational unit).
See xref:/midpoint/architecture/archive/data-model/midpoint-common-schema/orgtype/[OrgType].


|===

Full list of items can be found by using the SchemaDoc links above.


== See Also

* xref:/midpoint/devel/prism/concepts/object-identifier/[Object ID]