= Create a task of any kind
:page-nav-title: 'General task creation'
:page-display-order: 1
:page-toc: top
:experimental:
:icons: font

There are many tasks you can use in midPoint.
This guide provides general direction on where to start with any task creation.

You may know creating a resource-specific task from the respective resource the task is related to.
This guide describes the general way to create tasks which gives you full control over the settings of the task.

// TODO: rewrite so that it's general; originally taken from import tasks

== Create a task

. In icon:tasks[] *Server tasks* > icon:upload[] *Import tasks*, click icon:upload[role="green"] btn:[New import task].
. In the form that appears, specify the basic parameters of the imported objects on the icon:briefcase[] *Work* screen:
	** *Resource*: Click btn:[Edit] to select the resource from which you want to import.
	** *Kind*: Select the appropriate kind based on what you've used for the objects in the resource.
	** *Intent*: Set to *default* unless you use multiple intents on the same resource and need to select a non-default intent.
. Switch to the icon:gears[] *Execution* screen using the left-side menu:
	** *Execution*: Set *Mode* to *Preview* if you want to simulate. Leave *Undefined* or select *Full* for real production import.
	** *Configuration to use*: Set *Predefined* to *Development* to simulate. Select *Production* or leave undefined for real production import.
* Switch to the icon:circle[] btn:[Basic] screen and name the task there.
. Click icon:check[] btn:[Save & Run] to run the task immediately.
	If need be, save it for later without running it yet.
	Until you run it for the first time, you won't see it in the defined tasks of the resource.

As opposed to preview development simulation, the full mode with production configuration runs the actual data import modifying your midPoint database.

// TODO: Mention simulation and link reading simulation results article.
