= Import Objects to midPoint
:page-nav-title: 'Import tasks'
:page-display-order: 1
:page-toc: top
:experimental:
:icons: font
:icon-set: fas

Import tasks in midPoint are essential for synchronizing data from external resources into the midPoint system.
This article is here to guide you through creating import tasks, simulating their execution, and deploying them in a production environment.

Import tasks are mostly useful when you connect a new resource to midPoint.
Especially if it's the first resource, you want to import the resource objects to create their respective focal objects and set the stage for later when you eventually reconcile data from various other resources.

This guide shows you how to create an import task for one specific combination of resource, object kind, and its intent.
For a more general guide, refer to xref:./create-task-of-any-kind[].

[NOTE]
====
See xref:/midpoint/reference/tasks/[] for advanced configuration options and explanations outside the realm of GUI.
====

== Create an Import Task

To create the simplest import task, you only need to:

* Pick a resource from which to import object.
* Specify the kind and intent of the imported objects.
* Select the execution mode and configuration preset.
* _Everything beyond these essential settings is optional in import tasks._

To create an import task:

. Open the resource from which you want to import via icon:database[] *Resources* > icon:database[] *All resources*.
. Select the icon:male[] btn:[Accounts] screen.
. Click icon:tasks[] btn:[Tasks] dropdown menu and select icon:plus-circle[] btn:[Create task].
. If you want to first simulate the import, toggle the *Simulate task* switch to *on*.
. Select *Import task* and click icon:plus-circle[] btn:[Create task].
. Name the task and go through the wizard keeping the Resource, Kind, and Intent to defaults.
. Click icon:check[] btn:[Save & Run] or icon:save[] btn:[Save settings] based on whether you want to run the task immediately or save it for later.

// TOOD: link reading simulation results
