= Identity Provisioning
:page-wiki-name: Identity Provisioning
:page-wiki-id: 14745784
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2014-04-06T20:01:41.604+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2020-02-14T19:58:34.994+01:00
:page-moved-from: /iam/identity-provisioning/
:page-upkeep-status: yellow

In broad sense, glossref:identity-provisioning[identity provisioning] is a subfield of xref:/iam/iga/[identity governance and administration (IGA)], concerned with technical aspects of creating user glossref:account[accounts], groups and other objects in target systems.
It is a technology thanks to which many identity stores are synchronized, merged and maintained.
Identity provisioning takes care of technical tasks during the whole user lifecycle - when new employee is hired, when their responsibilities change, or when they leave the company (deprovisioning).
It helps the organization to work more effectively as the goal of identity provisioning goal is to automate as much as possible.

In the enterprise environment, the provisioning system usually takes information about employees from the Human Resource (HR) system.
When new employee is recorded into HR system, this information is detected and pulled by the provisioning system.
After that, it is processed to determine set of roles each user should have.
These roles determine and create accounts users should have, so everything is ready for new users on the very first day.
If a user is transferred to another department or his privileges change, similar processes happen again.
If an employee leaves the company, identity provisioning systems makes sure all his accounts are closed.

In a specific sense, identity provisioning means a process of creating accounts, assigning entitlements and similar actions, making sure a user has appropriate access to information systems.
Identity provisioning together with deprovisioning and associated activities is known as "fulfillment".

