= Import objects to midPoint with import tasks
:page-nav-title: 'Import tasks'
:page-display-order: 1
:page-toc: top
:experimental:
:icons: font
:icon-set: fas

Import tasks in midPoint are essential for synchronizing data from external resources into the midPoint system.
This article is here to guide you through creating import tasks, simulating their execution, and deploying them in a production environment.

Import tasks are mostly useful when you connect a new resource to midPoint.
Especially if it's the first resource, you want to import the resource objects to create their respective focal objects and set the stage for later when you eventually reconcile data from various other resources.

[NOTE]
====
See xref:/midpoint/reference/tasks/[] for advanced configuration options and explanations outside the realm of GUI.
====

== Create an Import Task

To create the simplest import task, you only need to:

* Pick a resource from which to import object.
* Specify the kind and intent of the imported objects.
* Select the execution mode and configuration preset.

Everything beyond that is optional.

*You have two ways to create tasks:*

* Create the task directly in the corresponding resource from which you want to import.
* Use the main task configuration in icon:tasks[] *Server tasks*.

=== From the Corresponding Resource

This is the most straighforward way to create tasks in general.

. Open the resource from which you want to import via icon:database[] *Resources* > icon:database[] *All resources*.
. Select the icon:male[] btn:[Accounts] screen.
. Click icon:tasks[] btn:[Tasks] dropdown menu and select icon:plus-circle[] btn:[Create task].
. Toggle the *Simulate task* switch to *on* and select *Import task*.
. Name the task and go through the wizard keeping the Resource, Kind, and Intent to defaults.
. Click icon:check[] btn:[Save & Run] or icon:save[] btn:[Save settings] based on whether you want to run the task immediately or save it for later.

=== Using the Main Task Configuration Section

This way gives you full control over the settings of the task.

. In icon:tasks[] *Server tasks* > icon:upload[] *Import tasks*, click icon:upload[role="green"] btn:[New import task].
. In the form that appears, specify the basic parameters of the imported objects on the icon:briefcase[] *Work* screen:
	** *Resource*: Click btn:[Edit] to select the resource from which you want to import.
	** *Kind*: Select the appropriate kind based on what you've used for the objects in the resource.
	** *Intent*: Set to *default* unless you use multiple intents on the same resource and need to select a non-default intent.
. Switch to the icon:gears[] *Execution* screen using the left-side menu:
	** *Execution*: Set *Mode* to *Preview* if you want to simulate. Leave *Undefined* or select *Full* for real production import.
	** *Configuration to use*: Set *Predefined* to *Development* to simulate. Select *Production* or leave undefined for real production import.
* Switch to the icon:circle[] btn:[Basic] screen and name the task there.
. Click icon:check[] btn:[Save & Run] to run the task immediately.
	If need be, save it for later without running it yet.
	Until you run it for the first time, you won't see it in the defined tasks of the resource.

As opposed to preview development simulation, the full mode with production configuration runs the actual data import modifying your midPoint database.

== Simulation Results

// This needs to go to its dedciated section once it exists

You run simulated tasks to confirm your configuration behaves as expected.
To see the results of the simulated task:

. Open the corresponding resource via icon:database[] *Resources* > icon:database[] *All resources*.
. In icon:tasks[] Defined Tasks, click the task the results of which you want to inspect.
. Click btn:[Show simulation results] at the top.

Here, you can see tiles with an overview of what would have happened.
Click the btn:[More info] buttons to view the affected objects.
The left sidebar shows an overview of object counts.
Click the numbers to list the objects and see more details.
