= Abstract Role
:page-wiki-name: Abstract Role
:page-wiki-id: 27361707
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2019-01-31T12:10:27.587+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-01-31T12:10:27.587+01:00

In midPoint parlance, _abstract role_ means any type of object that acts as a role.
This means that abstract tole can be used to give privileges to other objects.
Following object types are abstract roles in midPoint:

* Role (`RoleType`)

* Org (`OrgType`)

* Service (`ServiceType`)

* Archetype (`ArchetypeType`) - since midPoint 4.0

All those object types may act as roles.
Which means they can cause provisioning of accounts or other resource objects, they may contain other abstract roles, they can form a platform for wiki:Policy+Rules[Policy Rules] and so on.

In simple technical terms _abstract role_ means that the object may contain wiki:Assignment+vs+Inducement[inducement].


== See Also

* wiki:Advanced+Hybrid+RBAC[Advanced Hybrid RBAC]

* wiki:Organizational+Structure[Organizational Structure]