= Development Chat
:page-wiki-name: Development Chat
:page-wiki-id: 21201035
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2015-10-09T20:06:23.571+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2020-03-11T17:22:22.648+01:00

There is gitter chat that can be used to discuss midPoint development topics on-line.
The chat can be access by following the link below.

link:https://gitter.im/Evolveum/midpoint[MidPoint Development Chat]

The chat is intended for developers and engineers that intend to contribute to midPoint.
The chat is open to everybody and anyone is welcome to join the conversation.
However, the chat is limited to the topics concerning midPoint development, localization, examples, documentation updates and similar topics.
The chat is *not* intended for midPoint deployment support.
The support questions should be addressed to Evolveum or link:https://evolveum.com/about-us/partners/[Evolveum partners] for a commercial support or to the link:http://lists.evolveum.com/[midPoint mailing lists] for community discussions.

*Support questions will not be answered in this chat.*

The primary purpose of the chat is to support people that want actively *participate* and to *contribute* to midPoint project.
The chat will also be used for announcement that are of interest for a wider development community, such as announcements of development cycle milestones (feature freeze, localization freeze, testing phases, beginning of release process, etc.), coordination of people that want to help with testing of new midPoint releases, major source code changes, feature development milestones and so on.

[TIP]
.Public community communication
====
As a matter of Evolveum policy, all community communication must be public.
There are public mailing lists, development chat room, public wiki and bug tracking system - all completely open to community.
Evolveum is fully participating in all those public community communication channels.
We are fully committed to open development practices.
Information sharing is a crucial part of our openness policy.
Therefore no support or consultations will be provided by using any private communication channels.
That includes private mail communication, private chat conversation and so on.
Private communication channels are available only to midPoint wiki:Subscriptions+and+Sponsoring[subscribers]. Subscribers are funding midPoint development and therefore they are entitled for exceptions to this policy in case that such exception is needed.
Except for such cases we are fully committed to complete openness of midPoint development process.
Therefore we have decided to enforce the open communication policy.

====


==  See Also

* xref:../community-guidelines.adoc[]

* xref:/community/development/[Development Participation]