= Installing MidPoint Server From Distribution Package
:page-nav-title: From Distribution Package
:page-wiki-name: Installing MidPoint Server
:page-wiki-id: 24676039
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2017-12-08T12:43:45.697+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-09-08T15:26:16.271+02:00
:page-display-order: 30
:page-upkeep-status: orange
:page-upkeep-note: Missing information about generated password. Also, point to instruction to set up PostgreSQL database.
:page-toc: top
:page-moved-from: /midpoint/install/distribution/

{% for v in site.data.midpoint-versions %}{% if v.status == null or v.status == "released" %}{% assign lastReleased = v %}{% endif %}{% endfor %}


This guide describes how to install midPoint as a server from Evolveum distribution packages.

This procedure is intended for pre-production and production environments, and it is suitable for installing on virtual machines or physical hardware.
The guide assumes an ordinary server environment, running a server operating system, such as Linux.

If you only want to try midPoint, see xref:/midpoint/quickstart[Quickstart guide].

There are also alternative installation methods, such as xref:../containers/[Containers] or installing from a xref:../source/[building from the source code].

[TIP]
.MidPoint 4.0 and later
====
This guide applies to midPoint 4.0 and later.
For older releases, see xref:/midpoint/release[Release Notes].
====

== Before You Start

There are few things to check before you start the installation:

* Make sure to see the xref:/midpoint/release/[Release Notes] for the list of environments that are known to work and for the list of known issues in the current release.

* Make sure the xref:/midpoint/install/system-requirements/[System Requirements] are met.

* Make sure you are using a supported version of midPoint.
When in doubt, use the latest midPoint release ({{lastReleased.version}})

* See xref:platform-support.adoc[]

++++
{% include release-install-prereq-j17-j21.html release-version=lastReleased.version %}
++++

++++
{% include release-install-download.html this=lastReleased %}
++++

== Installation

=== Installing the Files

Copy the files to the installation directory.
The following directory locations are recommended:

[%autowidth]
|===
| Operating system | Installation directory

| Linux and other UNIX systems
| `/opt/midpoint`

| Windows
| `C:\Program Files\midpoint`

|===

The following instructions refer to relative paths inside the installation directory.

=== MidPoint Home Directory

xref:/midpoint/reference/deployment/midpoint-home-directory/[MidPoint Home Directory] is a filesystem directory that midPoint uses to store the initial configuration, cryptographic keys, log files and similar "variable" content.
MidPoint home directory is located in the `var` subdirectory by default (e.g. `/opt/midpoint/var`).
This location is acceptable for many installations.

However, some installations may want to separate the static (read-only) parts from the dynamic (read-write) parts of the installation.
To do that, move the midPoint home directory to a suitable location by setting the `MIDPOINT_HOME` environment variable (on UNIX systems) or by configuring the JVM options.
You can move the midPoint home directory even after installing midPoint.
However, it is recommended to set the directory correctly during installation to save time.

For details, refer to:

* xref:/midpoint/reference/deployment/midpoint-home-directory/[MidPoint Home Directory]
* xref:/midpoint/reference/deployment/stand-alone-deployment/[Stand-Alone Deployment]

=== MidPoint Repository

MidPoint comes with two repository implementations:

* Native PostgreSQL repository (preferred)
* Generic repository that supports multiple DB vendors (Oracle, SQL Server, PostgreSQL)

The generic repository is deprecated and not recommended.

A PostgreSQL database with a native repository has to be used for any production midPoint deployment.

For installation details, see xref:/midpoint/reference/repository/native-postgresql/usage/[].

== Post-Installation

=== Manual Run Control

MidPoint distribution packages provide convenient scripts that allow you to start and stop the midPoint service manually.
Those scripts are located in the `bin` directory.
Those scripts are *not* interacting with any service control facility on operating systems, such as `systemd`.
Those scripts only start and stop the midPoint process.

==== Linux (UNIX)

.Starting midPoint (Linux)
[source,bash]
----
./bin/start.sh
----

.Stopping midPoint (Linux)
[source,bash]
----
./bin/stop.sh
----

The `start.sh` and `stop.sh` scripts are simple wrappers for the `midpoint.sh` script.
The `midpoint.sh` script is where all the action happens.
You can also invoke this script directly:

.Using midpoint.sh script (Linux)
[source,bash]
----
./bin/midpoint.sh start
./bin/midpoint.sh stop
----

The `midpoint.sh` script will process the `setenv.sh` script if it exists in the same directory
(`bin`), or in the xref:/midpoint/reference/deployment/midpoint-home-directory/[midPoint home directory].
In this script, you can conveniently customize JVM properties, for example:

[source,bash]
----
#!/bin/sh
export JAVA_OPTS="$JAVA_OPTS -Dmidpoint.nodeId=My_Node1"
----

TIP: For more information on `midpoint.sh`, refer to xref:midpoint-sh.adoc[].

==== Windows

.Starting midPoint (Windows)
[source]
----
bin\start.bat
----

.Stopping midPoint (Windows)
[source]
----
bin\stop.bat
----

The `start.bat` and `stop.bat` scripts are simple wrappers for the `midpoint.bat` script.
The `midpoint.bat` script is where all the action happens.

The `midpoint.bat` script will process the `setenv.bat` script if it exists in the same directory `(bin`).
In this script, you can conveniently customize JVM properties.

=== Changing Keystore Password

Do not forget to *change the initial keystore password!*

It is strongly recommended to perform this step right after the initial startup of midPoint for all non-test environments.

To see how to change the initial keystore password, refer to xref:/midpoint/reference/security/crypto/keystore-configuration.adoc#_change_keystore_password[Change Keystore Password].


=== Setting Up a Service

The proper way to run midPoint on a server is to register it to the operating system service control facility.
This procedure is inherently dependent on the operating system.
The following pages provide specific instructions for the individual operating systems:

* Linux: xref:../systemd/[Running midPoint with systemd]

* Windows: xref:../windows-service/[Installing midPoint as a Windows Service]

== See Also

* xref:/midpoint/reference/deployment/midpoint-home-directory/[MidPoint Home Directory]

* xref:/midpoint/reference/repository/configuration/[]

* xref:/midpoint/reference/deployment/stand-alone-deployment/[Stand-Alone Deployment]
