= Supported Platforms for MidPoint Deployment
:page-nav-title: Platform Support
:page-upkeep-status: green
:page-moved-from: /midpoint/install/platform-support/
:page-toc: top
:icons: font

MidPoint can be deployed on a variety of operating systems, environments and platforms.
From a technical point of view, midPoint is a Java application, therefore it can run on any platform where Java Runtime Environment is available.
However, only some platforms are recommended and supported for production use.
This document summarizes support for midPoint deployment platforms.

== Supported Platforms

It is recommended to run midPoint on <<linux,Linux>> for which it is designed, although other platforms are also supported:

[%autowidth,options="header"]
|===
| OS | Non-production (demo, testing) | Production – LTS | Production – Feature version

| Linux (recommended)
| icon:check[]
| icon:check[]
| icon:check[]

| Windows
| icon:check[]
| icon:check[]
| icon:times[]

| macOS
| icon:check[]
| icon:times[]
| icon:times[]
|===

[[linux]]
== Linux - Recommended Platform

Linux is the *recommended platform* for midPoint deployment.
MidPoint is designed for Linux environments, development testing of midPoint is done in Linux environments, performance and any other special testing is focused on Linux environments - midPoint is living and breathing in Linux environments.
All performance testing, security evaluations and any special-purpose testing is done only in Linux environments.

MidPoint is fully supported in Linux environments for any use: development, demo, testing, and production.
No particular Linux distribution is required.
Any modern distribution should work well, as long as requirements for the Java platform are met (see the respective xref:/midpoint/release/[Release Notes]).
However, most development and testing of midPoint is done in Ubuntu LTS environment, therefore users of Ubuntu LTS versions are probably least likely to run into issues related to the operating system and platform.

MidPoint is also supported in xref:../containers/docker/[Docker] and xref:../containers/kubernetes.adoc[Kubernetes].
Kubernetes are recommended, if you are running them on top of your Linux operating system.

// TODO: docker, kubernetes, more details?

== Microsoft Windows

MidPoint runs on Windows, and it is supported for production use in xref:/support/long-term-support/[long-term support (LTS)] releases.
However, production deployments on Windows platform are *not recommended*.

Theoretically, Java platform should isolate midPoint from the underlying operating system.
However, practice is much more complex than that.
There are various details and peculiarities of the operating system platform that leak through the Java abstraction layers.
Then there are auxiliary details, such as the start/stop scripts, monitoring, logging, and other details that make midPoint quite an uncomfortable guest in the Windows environment.
MidPoint will run on Windows.
However, it is likely to require more attention from system administrators and engineers as compared to the Linux platform.

The vast majority of midPoint testing is done on Linux.
Therefore, we do not guarantee that midPoint will have satisfactory performance in Windows environments.
Similarly, if security is your primary concern, we strongly recommend to use a Linux environment instead.
All security testing and evaluation of midPoint is done only in Linux environments.
MidPoint bugs that are specific to Windows will usually take longer to fix.
Such bugs are much more difficult to reproduce for our development team, as the majority of the team does not use Windows at all.
It is perhaps perfectly understandable that Windows support is not our priority, especially given that the number of production deployments of midPoint in Windows environment is very low.

Windows is supported for production use only in xref:/support/long-term-support/[long-term support (LTS)] releases of midPoint.
As we do not test midPoint on Windows during the feature release cycle, we cannot guarantee that feature releases of midPoint will run smoothly on Windows.
We are doing proper Windows testing only for LTS releases.

It is perfectly acceptable to use Windows for presentations, demos, even for development of midPoint configurations.
However, we do not recommend to use Windows as a production environment for midPoint.

We recommend choosing Windows only in case you have no other option.

== Apple macOS

MidPoint runs quite well in the Apple macOS environment.
However, *macOS is not supported for production use*.

Many midPoint developers and engineers work in macOS environments.
Hence, we are quite sure that midPoint runs in this environment quite well.
In fact, it is a good environment for presentations, demos, and similar purposes.
Feel free to install midPoint on your Mac and give it a spin.

== General Notes

Only platforms that are within the standard support period provided by their vendor are supported.
Platform versions that are _end of life_ (EOL), are available only under extended support, or any other special support arrangements, are *not* supported for running midPoint.
As a rule of thumb, a platform is supported for running midPoint only as long as the vendor regularly publishes security updates and fixes without requiring any non-standard support agreement.

== See Also

* xref:../system-requirements/[]
