= Installing MidPoint From Source Code
:page-nav-title: From Source Code
:page-wiki-name: Installing midPoint Development Snapshot - Source Code
:page-wiki-id: 4882541
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2012-08-08T17:44:24.330+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-09-19T13:06:15.518+02:00
:page-display-order: 30
:page-upkeep-status: orange
:page-upkeep-note: Missing information about generated password. Also, point to instruction to set up PostgreSQL database.
:page-moved-from: /midpoint/install/source/
:page-toc: top

{% for v in site.data.midpoint-versions %}{% if v.status == null or v.status == "released" %}{% assign lastReleased = v %}{% endif %}{% endfor %}

This guide provides instructions on installing midPoint from the source code.

This installation requires software development tools and expertise to build the product.
It is recommended only to engineers who want to participate in midPoint development or have a deeper interest in the source code.
Other users should consider a simpler installation using a xref:distribution.adoc[distribution package] or xref:../containers/[containers].

[TIP]
.MidPoint 4.0 and later
====
This guide applies to midPoint 4.0 and later.
For older releases, see xref:/midpoint/release[Release Notes].
====

== Before You Start

There are few things to check before you start the installation:

* Make sure to see the xref:/midpoint/release/[Release Notes] for the list of environments that are known to work and for the list of known issues in the current release.

* Make sure the xref:/midpoint/install/system-requirements/[System Requirements] are met.

* See xref:platform-support.adoc[]

* Development versions of midPoint are not yet finalized.
There may be unfinished features, bugs, instability, and a variety of other issues.
Use them at your own risk.

++++
{% include release-install-prereq-j17-j21.html release-version=lastReleased.version %}
++++

Make sure you have the full *Java Development Kit (JDK)*, not just the runtime environment (JRE).
A full set of development tools is needed as you will be building midPoint from source code.

=== Git

The midPoint source is available in Git.
You will need a suitable Git client software to clone the source code.
Many operating systems include that as a standard package.
For example, in Debian-based Linux systems, you can install Git using `apt`:

[source,bash]
----
sudo apt install git
----

=== Maven

MidPoint source code is built using http://maven.apache.org/[Apache Maven].

Download and install *Maven3*: link:http://maven.apache.org/download.html[http://maven.apache.org/download.html]

The `M2_HOME` environment variable should point to the Maven installation path.


== Installation

=== Getting The Source Code

MidPoint source code is hosted on GitHub:

[%autowidth,cols="h,1"]
|===
| GitHub project page
| https://github.com/Evolveum/midpoint

| Git repository HTTPS access
| link:https://github.com/Evolveum/midpoint.git[https://github.com/Evolveum/midpoint.git]

| Git repository SSH access
| `git@github.com:Evolveum/midpoint.git`

|===

Use your Git client to clone the source code tree.
For example, in a Linux system, you can use the `git` command-line client:

[source,bash]
----
git clone -b v{{ lastReleased.version }} https://github.com/Evolveum/midpoint.git
----

Running this command creates the `midpoint` directory containing the midPoint source code tree.

The `-b` option specifies the midPoint version.
You can omit the option to get the latest development version of midPoint (`master` branch):

[source,bash]
----
git clone https://github.com/Evolveum/midpoint.git
----

For more information about the source repository structure, see xref:/midpoint/devel/source/[Source Code].

[NOTE]
====
On Windows, it is highly recommended to add the following switch to the `git clone` command: `--config core.autocrlf=false`

You can also use this switch to disable `autocrlf` on other platforms because, while `autocrlf` works, it does not work well with midPoint projects.
Don't forget to adjust the project settings for your IDE accordingly (this is done automatically when xref:/midpoint/devel/guides/environment/idea/[using IntelliJ IDEA]).
====

[NOTE]
====
Alongside the *master* branch, there are also support branches.
After each release, a respective support branch is created.
It is a working snapshot that collects all bug fixes until another major release is finished.

These branches follow this naming: _support-X.Y_.
For example, for the LTS release 4.8(.x), there is the *support-4.8* support branch.
====

=== Building MidPoint

Go to the directory with the downloaded source code and execute the following command:

[source,bash]
----
mvn install
----

A complete build process also includes unit and integration tests, and it may take more than one hour.
You can speed up the build by skipping automatic tests using the following command:

[source,bash]
----
mvn install -DskipTests=true
----

After a successful build process, you will find a binary distribution package located in the `dist/target` directory.

[TIP]
.Building the JAR file only
====
If the JAR file is all you need, you can speed the build even further by skipping the packaging of the distribution archive.
Use the following command to turn off the `dist` Maven profile:

`mvn clean install -DskipTests=true -P -dist`

Notice the minus character (-) before the profile name. +
The resulting JAR file can be obtained from `gui/admin-gui/target/midpoint.jar`.

Note that for versions older than midPoint 4.6, WAR files were used instead of JAR files.
====
// how do I know the WAR file is all I need?

=== Running MidPoint

Continue with the installation in the same way as for a binary release.
See the xref:distribution.adoc[] page and follow the instructions.
However, instead of downloading a distribution package, you will use your own freshly built distribution package from the `dist/target` directory.


== Next Steps

MidPoint is a comprehensive system, and the source code is extensive.
If you plan to work with the midPoint source code, we strongly recommend getting an *Integrated Development Environment (IDE)*.
Most midPoint developers use IntelliJ IDEA, and there is a xref:/midpoint/devel/guides/environment/idea/[short guide to set up IntelliJ IDEA] for midPoint development.
Eclipse Java IDE can also be used.

MidPoint has to store its own data in a database, which we call _repository_.
MidPoint stores all the data there: users, roles, xref:/midpoint/reference/resources/shadow/[shadow objects] representing accounts, configuration, etc.

MidPoint needs a PostgreSQL database engine.
PostgreSQL is a leading open source relational database engine.
Since midPoint 4.4, midPoint can use features specific to PostgreSQL to its advantage (using a xref:/midpoint/reference/repository/native-postgresql/[native PostgreSQL repository implementation]).

MidPoint also supports other database engines.
However, since midPoint 4.4, such support is deprecated.
Do not use other database engines unless there are historic reasons, and you have a plan for migrating to PostgreSQL.

The xref:/midpoint/reference/repository/configuration/[Repository Configuration] page provides the instructions.

If you plan to participate in midPoint development, see xref:/community/development/[].
If you plan to contribute source code, the xref:/community/development/code-contribution-guidelines/[] page provides essential information.

== See Also

* xref:distribution.adoc[]

* xref:/midpoint/devel/source/[Source Code]

* xref:/midpoint/devel/guides/environment/idea/[]

* xref:/community/development/[]

* xref:/community/development/code-contribution-guidelines/[]

* xref:/midpoint/install/post-install-orientation[]
