= Running midPoint with systemd
:page-nav-title: Running With systemd
:page-wiki-name: Running midPoint with systemd
:page-wiki-id: 24676019
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2017-12-08T11:13:20.027+01:00
:page-wiki-metadata-modify-user: virgo
:page-wiki-metadata-modify-date: 2021-02-08T18:10:14.581+01:00
:page-upkeep-status: green
:page-moved-from: /midpoint/install/systemd/

This page describes the method how to set up xref:distribution.adoc[midPoint server] for systemd run control.
This is the usual setup to start midPoint automatically after system boot on UNIX-like (Linux) systems.

[TIP]
====
This page describe the behaviour with static definition of the systemd service - example.
To generate the systemd service customized to your environment you can use feature of xref:/midpoint/install/midpoint-sh/#generate[midpoint.sh].

/opt/midpoint/bin/midpoint.sh generate
====

The following steps assume the midPoint installation in `/opt/midpoint` directory, owned (both directory and its content) as (previously created) user `midpoint`.
The service will be started as user `midpoint` and will listen on default TCP 8080 port.

. Create a new file `/etc/systemd/system/midpoint.service` with the following content:
+
.midpoint.service
[source,bash]
----
[Unit]
Description=MidPoint Standalone Service
###Requires=postgresql.service
###After=postgresql.service
[Service]
User=midpoint
WorkingDirectory=/opt/midpoint
ExecStart=/usr/bin/java -Xmx2048m -Dmidpoint.home=/opt/midpoint/var -jar /opt/midpoint/lib/midpoint.war
SuccessExitStatus=143
###TimeoutStopSec=120s
[Install]
WantedBy=multi-user.target
----
+
Of course, `-Xmx2048m` needs to be modified for bigger deployments accordingly.
+
`ExecStart` line for versions 4.6 and later is different, because the packaging was changed from WAR to JAR:
+
[source,bash]
----
ExecStart=/usr/bin/java -Xmx2048m -Dmidpoint.home=/opt/midpoint/var -jar /opt/midpoint/lib/midpoint.jar
----

. Run the following commands to enable midpoint service:
+
[source,bash]
----
sudo systemctl daemon-reload
sudo systemctl enable midpoint
----

. Start midPoint as systemd service using the following command:
+
[source,bash]
----
sudo systemctl start midpoint
----

. You can monitor the startup in `/opt/midpoint/var/log/midpoint.log` (standard midPoint log) or in `/var/log/syslog` (the file name may vary; if systemd is used, `/opt/midpoint/var/log/midpoint.out` is *not* used.

. You can stop midPoint as systemd service using the following command:
+
[source,bash]
----
sudo systemctl stop midpoint
----

. To disable automatic midPoint startup/shutdown, use the following command:
+
[source,bash]
----
sudo systemctl disable midpoint
----

If you wish to customize JVM parameters, just modify `ExecStart` directive in the `midpoint.service` file and restart midPoint.

[TIP]
====
Systemd allows you to specify service dependencies.
For example to specify that midPoint requires PostgreSQL database (running as systemd service on the same host), just uncomment the lines `Requires` and `After`.
Systemd will start PostgreSQL before midPoint, and when PostgreSQL goes down, it will also automatically shutdown midPoint.
====

== See Also

* xref:/midpoint/install/[Installation Guides]

* xref:/midpoint/reference/deployment/stand-alone-deployment/[Stand-Alone Deployment]
