= Support Branches
:page-wiki-name: Support Branches
:page-wiki-id: 13074475
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2013-10-09T17:14:07.278+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2018-08-01T09:53:02.964+02:00
:page-upkeep-status: orange
:page-moved-from: /midpoint/install/using-support-branch/
:page-toc: top

== Overview

Support branches are created in Git after every minor release.
They are maintenance versions of midPoint (see xref:/midpoint/versioning/[Release Process]) and they contain the most recent bugfixes.
In support branches, bugfixes accumulate until another major release is done.

Support branches do *not* contain new features planned for the upcoming major or minor releases.
Those are kept in the current main development branch (currently `master` branch).
Note that while support branches are typically reasonably stable, the code in the `master` branch may not be.

== Get Support Branches

Support branches are maintained as branches in the midPoint xref:/midpoint/devel/source/git/[Git repository].
They follow this naming convention:

....
support-x.y
....

"x.y" stand for the last minor release.
Once you have the repository, you can switch the workspace to a support branch by using the `checkout` command.
For example:

[source]
----
git checkout support-4.8
----

As individual Git tools may vary, see the documentation of your Git tool for details.

== Use Support Branches

Once the workspace is switched to a support branch, you can build the system in the usual manner.
Follow the instructions in xref:/midpoint/install/bare-installation/source/[Installing midPoint Development Snapshot - Source Code].
Only instead of `master`, use the `support-4.8` branch name, or another, depending on the current release.

== Binary Files

After you make a new commit into the branch, i.e. you add new content, Jenkins (build server) automatically builds the snapshot version and places the binary into the https://nexus.evolveum.com/[nexus.evolveum.com] repository.
Binaries are available also at the https://evolveum.com/download/[download] page.

== See Also

* xref:/midpoint/versioning/[Release Process]

* xref:/midpoint/devel/guides/backporting-code-to-support-branch/[Backporting Code to Support Branch]

* xref:/support/long-term-support/[Long-Term Support]

