= Installing midPoint as a Windows Service
:page-nav-title: Windows Service Setup
:page-wiki-name: Installing midPoint as a Windows Service
:page-wiki-id: 24676017
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2017-12-08T11:12:37.394+01:00
:page-wiki-metadata-modify-user: virgo
:page-wiki-metadata-modify-date: 2021-02-08T17:21:06.015+01:00
:page-upkeep-status: yellow
:page-moved-from: /midpoint/install/windows-service/
:page-toc: top

{% for v in site.data.midpoint-versions %}{% if v.status == null or v.status == "released" %}{% assign lastReleased = v %}{% endif %}{% endfor %}

This page describes how to setup midPoint servers to run as Windows services.

MidPoint is typically set up to start automatically after the system boot on Windows.
The service is started as "MidPoint" and it listens on the default TCP 8080 port.

++++
{% include release-install-download.html this=lastReleased %}
++++

== Install

Install midPoint as a service by executing the `service.bat` script from the `bin` directory with the `install` argument:

[source]
----
.\Downloads\midpoint\bin\service.bat install
----

The service can be controlled using common Windows Services tools.

Alternatively, you can start, stop, or configure the service using the GUI application `midpointw.exe` which is located in the `bin` directory.

== Uninstall

Uninstall the midPoint service by executing the `service.bat` script from the `bin` directory with the `uninstall` argument.
Stop the service first, then run:

[source]
----
.\Downloads\midpoint\bin\service.bat uninstall
----

[TIP]
====
You can also start/stop service with the Windows Services application.
====

== See Also

* xref:../[Installation Guides]

* xref:/midpoint/reference/deployment/stand-alone-deployment/[Stand-Alone Deployment]