= Comparing prism values

Prism values are compared in various contexts, requiring different definitions of what "equality" means.
Such definitions are called "equivalence strategies" in midPoint code.

The two mostly used strategies are:

== Data

Captures the full meaning of the data, while ignoring minor (mostly serialization-related) aspects that
are not relevant for the parsed data, like namespace prefixes.

The Data strategy is used for `equals` and `hashCode` methods in Java code.

== Real value (with or without considering different IDs)

Captures the "real value" of the data: it is something that we consider equivalent so that
if prism values A and B have the same real value, we do not want to be both present
in the same multi-valued item (like assignment, roleMembershipRef, or whatever).

However, in reality, we usually take container IDs (if both are present) into account,
so if PCV A1 and A2 have equal content but different IDs they are treated as different.
This is reflected in "Real value considering different IDs" variant of this strategy.

"Real value considering different IDs" strategy is used for link:../delta/[delta application].

== Other equivalence strategies

[%header]
[cols="2,8"]
|===
| Strategy | Description
| Literal |
Currently the highest level of recognition. Roughly corresponds to comparing serialized
forms of the data. Useful e.g. for comparing values for the purpose of XML editing.

Ignores aspects that are not covered by serialization e.g. definitions, parent objects,
origin, immutability flag, etc. (These aspects are ignored by all equivalence strategies.)

| Ignore metadata |
Something between Data and Real value: ignores operational items and values, container IDs,
value metadata (just like Real value) but takes reference filters and reference resolution
options (time, integrity) into account (like Data).

It is not quite clear whether and when to use this strategy.
|===

== See also

The link:https://github.com/Evolveum/midpoint/blob/master/infra/prism-api/src/main/java/com/evolveum/midpoint/prism/equivalence/ParameterizedEquivalenceStrategy.java[
`ParameterizedEquivalenceStrategy`] class.

== A bit of notation

[[definitions]]If X is an equivalence strategy, a and b are values, and A and B are sets of values, then:

****
* a &Tilde;~X~ b means that a and b are equivalent under strategy X (we also call them X-equivalent)
* a &in;~X~ B means that &exist;b&in;B: a&Tilde;~X~b
* a &notin;~X~ B means &not;(a&in;~X~B) i.e.  &not;&exist;b&in;B: a&Tilde;~X~b
* A &cap;~X~ B = { a&in;A | a &in;~X~ B }footnote:[We could try to define A&cap;~X~B also as { a | a&in;~X~A &and; a&in;~X~B }
but this is not quite correct. Such definition would result in infinite set of values, because there are many values that are
X-equivalent with any given value. So the set of candidate values must be somehow bound.]footnote:[This also means that &cap;~X~
operation is _not_ commutative! In general, A &cap;~X~ B can be different from B &cap;~X~ A.]
* A -~X~ B = { a&in;A | a &notin;~X~ B }
****

[[definition-del]]
When applying delete deltas, a special set operation has to be defined:

****
* A -~del/X~ B = A - { a&in;A | &exist;b&in;B such that a &Tilde;~del~ b }
****

a &Tilde;~del/X~ b means that value a matches the "deletion pattern" b under equivalence strategy X, and is defined as:

****
a &Tilde;~del/X~ b ⇔ a~id~ = b~id~ ≠ null &or; a &Tilde;~X~ b
****

where a~id~ denotes ID of prism container value a (or null if a is not a prism container value).
