= System Configuration GUI
:page-toc: top

This page summarizes result of tests of 4.5 after new Sysconfig GUI using tiles was introduced.
Most of the xref:/midpoint/reference/concepts/system-configuration-object/[System Configuration]
(`SystemConfigurationType`) elements can be configured via GUI, the rest is mentioned at the end of this document.

The following list is structured based on existing tiles (in 4.5) - for each tile there is
a separate list of detail sections and how these map to the `SystemConfigurationType` elements.
Elements marked with `*` are multi-value, which often means GUI table, but not always.
Known issues are linked from the relevant places.

== System configuration

This covers multiple elements directly under System Configuration object that do not deserve their own section.

* Basic: `globalSecurityPolicyRef` + `modelHooks` non-container list (edit bug bug:MID-7868[]) + basic object attributes (inherited, not sysconfig specific)
* Deployment: `deploymentInformation` container, including `logo` (`IconType`)
* Infrastructure: `infrastructure` container
* Full text search: `fullTextSearch` container (after enabling it, the option to enable/disable full text search as default would be handy - ideally right here, at least from user's perspective)

== Policies

* Object policies: `defaultObjectPolicyConfiguration*` container
* Global policy rules: `globalPolicyRule*` container
* Global projection policy: `globalAccountSynchronizationSettings` container
* Cleanup policy: `cleanupPolicy` container (bug:MID-7825[])

== Notifications

* Event handlers: `notificationConfiguration/handler*`
* Mail transports: `messageTransportConfiguration/mail*` (buggy server edit, it's not container, MID-7815)
* SMS transports: `messageTransportConfiguration/sms*`  (buggy gateway edit, it's not container, MID-7815)
* File transports: `messageTransportConfiguration/file*`
* Custom transports: `messageTransportConfiguration/customTransport*`
* Legacy: `notificationConfiguration/mail` + `file`

== Logging

* Logging: `logging` (`rootLoggerAppender`, `rootLoggerLevel`, `auditing`), how to edit `advanced`? (bug:MID-7821[])
* Class loggers: `logging/classLogger*`
* Appenders: `logging/appender*`

== Profiling

* Profiling configuration: `profilingConfiguration`
* Profiling entry/exit sets `PROFILING` logger (entry/exit = DEBUG, args = TRACE) (bug:MID-7859[])

== Admin GUI

* Basic: `adminGuiConfiguration` (bug:MID-7851[], bug:MID-7884[])
* Additional menu links: `adminGuiConfiguration/additionalMenuLink*` (bug:MID-7887[])
* "User" dashboard links: `adminGuiConfiguration/userDashboardLink*` (bug:MID-7886[])
* Object colleciton views: `adminGuiConfiguration/objectCollectionViews*` (bug:MID-7885[])
* Object detail views: `adminGuiConfiguration/objectDetails` (`objectDetailsPage*` and `shadowDetailsPage*`)
* User dashboards: `adminGuiConfiguration/userDashboard` (seems like a table, but maxOccurs="1"?)

== Workflow configuration

* Workflow configuration: `workflowConfiguration` basic attributes
* Execution tasks: `workflowConfiguration/executionTasks`
* Primary change processor: `workflowConfiguration/primaryChangeProcessor`
* General change processor: `workflowConfiguration/generalChangeProcessor` (bug:MID-7869[])

== Role management

* Basic: `roleManagement` (bug:MID-7873[])
* Relations: `roleManagement/relations/relation*` (missing includeDefaultRelations bug:MID-7874[])

== Internals

* `internals` container

== Access certification

* `accessCertification` container

== Unsupported on GUI:

* `connectorFramework`
* `providedService`
* `mergeConfiguration`
* `expressions`
* `audit`
* `correlation`
