= UI/UX problems in current midpoint administration interface
:page-wiki-name: UI/UX problems in current midpoint administration interface
:page-wiki-id: 22282331
:page-wiki-metadata-create-user: lazyman
:page-wiki-metadata-create-date: 2016-01-26T13:54:23.370+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2016-01-27T17:01:36.033+01:00
:page-upkeep-status: yellow

== Operation results

Operation results should use AdminLTE/Bootstrap css and should show progress if necessary.
They also should be stored in session for some use cases, because user want to see error one more time.

== Error handling

Exceptions are caught and handled quite wildly.
Task/result is created for every small invocation.
Some exceptions are not even logged (mostly in old code).
There is no common way how to handle and process exceptions.


== Breadcrumbs and Back button

Breadcrumbs are not present and Back button is working only on some pages with limited functionality.


== Dialogs/Modal windows

We should use main modal window which is currently attached to PageTemplate, there are couple helper methods to work with content and title of this dialog.
This way we can get rid of nested form elements which causes troubles when updating wicket models.


== AdminLTE template LESS

AdminLTE template is not compiled from LESS, currently we have precompiled CSS files.


== Look and feel uniformity

Many different styles and widgets are used for the same purpose.
We should use the same widget every time for the same purpose.
The entire GUI should have uniform look and feel.


== Usability

Things that are done frequently should be very easy to do.
Ideally one click.

Concrete usability issues:

* Search widget: simple search by name requires three clicks and text entry.
Enter does not work.

* Missing "Edit XML" buttons on pages that modify midpoint objects.

* Missing "Add new" buttons in tables that list midpoint objects.

* Delete buttons on object details pages