= Build and Release
:page-nav-title: Build and Release

== Build

There are three types of Studio builds:

|====
| Build type | Quality | Description

| stable
| production
| Production-quality official releases.

| snapshot
| beta
| Intended for testing, evaluation of new features, gathering of community feedback and so on. Development happens here.

| milestone (deprecated)
| beta
| Intended for testing, evaluation of new features, gathering of community feedback and so on.

| nightly (deprecated)
| varies, no guarantees
| Development happens here.
Latest functionality, but the code may break any time.
Use at your own risk.
|====


== Adding Plugin Repository

Custom repository needs to be added to use snapshot builds:

. Go to menu `File` → `Settings (Preferences)` → `Plugins` → `Manage plugin repositories`

. Add repository:

** `https://plugins.jetbrains.com/plugins/Snapshot/list` for snapshot builds

. Search for `MidPoint Studio` and click on `Install`

== Migrating from nightly/milestone plugin repository to snapshot repository

. Go to menu `File` -> `Settings (Preferences)` → `Plugins`
.. Uninstall MidPoint Studio plugin
. Go to menu `File` → `Settings (Preferences)` → `Plugins` → `Manage plugin repositories`
.. Edit existing url of nightly/milestone repository, change it to `https://plugins.jetbrains.com/plugins/Snapshot/list`
. Search for `MidPoint Studio` and click on `Install`

== Release Procedure

. Pre-release
+
[.purple]#Changes should be done on `master` branch and should go through standard release to snapshot and then to stable branch.#
+
.. Update information about studio version
... Edit `studio-idea-plugin/README.md`, this text will be shown in plugin description.
... Update `studio-idea-plugin/CHANGELOG.md`, this will show up in what's new.
.. Review `studio-idea-plugin/gradle.properties`
... Check `pluginSinceBuild` and `pluginUntilBuild` values.
... Check `settings.gradle.kts` and midPoint version dependency.
+
Make sure no snapshot version is used.
Major and minor version of midpoint must match major and minor version of studio.
We currently support last 3 versions of IDE (4 if there's EAP version available).
... Make sure `platformVersion` contains lowest possible version of supported IDE (based on pluginSinceBuild).
... Make sure `pluginVerifierIdeVersions` contains list of all supported IDE versions, their last patched versions.
... Make sure newest `EAP` version is included in `pluginVerifierIdeVersions` if it's available.
.. Run clean & build if there were changes:
+
[source, bash]
----
./gradlew clean buildPlugin verifyPlugin runPluginVerifier
----
+
. Release
.. Align git branches
... If *snapshot* build is being released: `master` -> `snapshot`. Use git merge:
+
[source, bash]
----
git checkout snapshot
git pull
git merge origin/master
----
+
... If *stable* build is being released: `snapshot` -> `stable`
Stable build should be released from `stable` branch using changes done in `snapshot`.
This means snapshot build was already published and tested by users.
+
[source, bash]
----
git checkout stable
git pull
git merge origin/snapshot
----
+
.. Compile and verify plugin locally
+
[source, bash]
----
./gradlew clean buildPlugin verifyPlugin runPluginVerifier
----
+
... Review verification results in `studio-idea-plugin/build/reports/pluginVerifier/*/report.html`.
.. Push changes to `origin`
+
[source, bash]
----
git push
----
+
.. Execute jenkins job https://jenkins.evolveum.com/view/midPoint-studio/job/midpoint-studio/[midpoint-studio]
+
Use `PUBLISH=true` and proper release branch (`snapshot` or `stable`).
.. Go to `https://plugins.jetbrains.com/plugin/13809-midpoint-studio/versions`
+
Validate published plugin, mainly: version, description, compatibility and _What's new_.
. Post-release
.. After plugin was published to marketplace (and is publicly available), ask someone from engineering team to re-test it.
.. If *stable* version was released:
... Notify marketing team about new release (after it's publicly available).
... Create git tag for released version in format `vX.Y.Z` and push it to `origin`.
... Go to `https://github.com/Evolveum/midpoint-studio/releases`
.... Create new release for tag created in previous step.
.... Add release notes, use notes from `studio-idea-plugin/CHANGELOG.md`.
... On `master` branch
.... Update plugin version in `build.gradle`, key `pluginVersion`.
.... Update `settings.gradle.kts` - midPoint version dependency.
+
Major and minor version of midPoint must match major and minor version of studio plugin.


=== Issues

. in case build wasn't correct but plugin was published to JetBrains Marketplace
.. go to `https://plugins.jetbrains.com/plugin/13809-midpoint-studio/versions`
.. find plugin version you want to hide/delete and click `Hide update` or `Remove update` icon

== See Also

* xref:..[MidPoint Studio]
