= First Steps With MidPoint: Assessment
:page-nav-title: '2. Assessment'
:page-display-order: 110
:page-toc: top
:experimental:

.Goal
TIP: Asses the _real_ data quality, determine practical next steps.
At this point we know what we _really_ have, what we can build on, what needs to be improved.
We can identify the most severe security risks, such as orphaned accounts.
Now we can improve our plan, adding more details based on the _real_ data.

You have some kind of HR data now.
In theory, you should use the HR data to create and manage accounts in target system, such as your Active Directory.
However, in practice, this is not entirely straightforward.

Firstly, it is almost certain that there are errors and inaccuracies in the HR data.
The data were maintained manually for a long time, with no way for automatic validation.
Mistakes in the data might be buried deep, surviving undetected for decades.
Having nothing to compare the data with, there is no telling how good or bad the data are.

Secondly, the data in your target systems (especially Active Directory) certainly leave a lot to be desired.
These were managed manually for years, with no automatic way to make sure they are correct.
There will be account belonging to people that left your organizations years ago.
There will be accounts using maiden names of women that are married now.
There will be strange accounts and identifiers that originated ages ago when your organization was still small and system administration was fun.
There may be all kinds of weirdness and historical baggage frozen in time because nobody remembers what it does and everybody is scared to touch it.

Taking HR data and simply forcing them to Active Directory will never work.
We need much smarter approach.

// TODO: short summary of the process

This is what you have to do:

== 1. Connect HR System

*Connect HR* data source to midPoint.
Set up your HR identity resource in midPoint, using CSV or DatabaseTable connector.
Deal with just the very basic data items for now:

* Names (given name, family name)
* Employee number, student number or similar identifier
* Status (active, former employee, alumni, etc.) and/or validity date/time (based on contract etc.)

You can ignore other fields for now.
We can get back to them later.

TODO: will be the resource in Development mode by default?

Switch the resource to Development mode.

Configure the resource to create users in midPoint with `Person` archetype assigned.

Preview your HR records which will be imported to see if you want to import all of them, or you want to import only a subset of them using a classification filter (e.g. if you want to ignore non-IT personnel).
As the resource is in Development mode, this allows you to redefine classification filters and reclassify your HR accounts as many times as you wish.

[#import-users-from-hr]
== 2. Import Users From HR To MidPoint

*Import users* to midPoint, using HR data.
For simplicity, use HR person identifier (e.g. employee number) as the midPoint username.
We will import the usernames from AD/LDAP later.

//Select appropriate algorithm for midPoint username.
//You surely have some username convention (such as `jsmith`) in place.

Start with importing a single HR account with preview option to see how the user would be created in midPoint.
Then you can simulate the import using a Development mode to see how all the users would be created in midPoint.

When finished, switch the HR resource to Production mode.

Then import the HR data, creating user objects in midPoint.
As we are working with simple data for now, the import should go well.

You can continually improve your imported data by adding more attribute mappings.


TODO: decide the former employees, suspended, deactivated etc.

.User lifecycle
[NOTE]
====
This is where user lifecycle management starts.

We need at least some basic framework for user lifecycle management at this point.
(TODO) Do we import only active users from HR? All users? How we will mark active users? (Auxiliary) Archetype?

If we can identify inactive HR persons, we can utilize this information when checking for accounts in target systems that should not be there (if we do not import inactive users from HR, we will see their accounts in target systems as simply orphaned).
====

[#connect-active-directory]
== 3. Connect Active Directory

*Set up your Active Directory (or LDAP) identity resource* in midPoint and keep it in Development mode.
Set up outbound mappings for the small data set that you have (given name, username and so on).
Set the outbound mappings in Development mode and keep it disabled.
Set the synchronization configuration in Development mode.
We do not want to change any data in Active Directory yet.

.Resource templates
[NOTE]
====
Resource templates can be prepared in advance.

Creating a new resource based on resource template instead of creating it from scratch can save your time as the basic configuration would be pre-defined, and you can enable/update it as necessary.
====

== 4. Correlate Active Directory Accounts

*Correlate Active Directory accounts* with midPoint users.
If you have employee numbers (or similar unique attributes from HR) stored in your Active Directory, then use that for correlation.
As an alternative, you may want to use several attributes for correlation such as names, locality, department etc.
Manual confirmation using midPoint correlation cases can be used to specify midPoint user who should own the Active Directory account if the match is ambiguous.

After configuring correlation and synchronization (in Development mode):

//Otherwise, use the generated midPoint usernames (e.g. `jsmith` convention) as the correlation identifier to match //(assumed) majority of the accounts to their corresponding owners in midPoint:

. Run the simulated _import_ or  _reconciliation_ task on AD resource using Development configuration.
. Then have a look at the task and simulation results in midPoint GUI (interactively).

If you maintained your identifier assignment conventions reasonably well, most identities should correlate well.
MidPoint will show you correlation statistics for your accounts.

Of course, there will be problems of `John Smith` and `Josh Smith` with their `jsmith` and `jsmith42` accounts.
Let's leave that for later.
For now just focus on correlating the bulk of users.

If you get 80-90% users to correlate well, you are done here.

There will be also orphaned accounts (`Unmatched` situation).
Based on your resource configuration, midPoint may report they will be deactivated (but we are still in Development mode).

We will analyze the accounts here, but we will take final decision later in <<6. Clean Up The Accounts>> to not stop us from progressing.

TIP: You can analyze/clean up the data in several iterations.

The orphaned accounts generally fall into the following categories:

. *Obviously orphaned accounts*:
Review the list of orphaned accounts (the accounts in Active Directory not having an owner in midPoint which should mean they are not related to HR data on which midPoint data is based) one by one and make sure these are _not_ system accounts (see the _System (service) accounts_ category).
+
If you are absolutely sure the accounts should be deactivated, you do not need to mark them and leave them to their (later) fate.

. *Orphaned accounts of unclear origin*:
Review the list of orphaned accounts (the accounts in Active Directory not having an owner in midPoint which should mean they are not related to HR data on which midPoint data is based) one by one and make sure these are _not_ system accounts (see the _System (service) accounts_ category).
+
xref:/midpoint/methodology/first-steps/solution/#explicitly_marking_accounts_for_decommissioning[_Mark_ the undesired ones as Decommission later] to be deactivated eventually (but not immediately).

. *System (service) accounts*:
For all accounts that are crucial for Active Directory, we need a different decision.
+
xref:/midpoint/methodology/first-steps/solution/#explicitly_marking_accounts_as_protected[_Mark_ the system accounts as Protected in midPoint] to keep track of them, but ignore them otherwise by midPoint.

. *Accounts unmatched because of data inconsistencies.*
Review the rest of accounts which have not been matched or decided in the previous steps.
This is the time to take care of the Smiths, Johnsons and Browns if no reasonably unique attribute could have been used for their correlation.
Have a look at all the `jsmith`, `smithj` and `jsmith2` accounts.
If possible, update your correlation configuration to use more attributes to find matching users.
+
You can also try to figure out which account belongs to which user and correlate them manually.
+
Or you can mark specific accounts as "Correlate later" to ignore them now and resolve them in later iteration.
+
If you did the previous steps well, there should be just a handful of them.
+
Sometimes there are several accounts (or groups of accounts) which need to be reviewed in more detail and remedied.
To avoid getting stuck in this phase, you may simply mark these accounts for later review (Do not touch) and ignore any provisioning for them fow now.
(This is actually similar to the concepts of protected accounts, but having a different mark allows us to differentiate the accounts. We want them marked only temporarily, and they will be reported.)

We also recommend to *review the accounts marked in previous iterations* to avoid a constant increase of their numbers.

After you have finished marking of your accounts, you can run the simulated _reconciliation_ task with Development configuration.
Your marked accounts should not be reported to be deactivated anymore.
Not marked orphaned accounts should be still reported as to be deactivated.

Switch the resource, object type configuration and all synchronization actions except `Unmatched` to Production mode, and:

. Run the simulated _import_ or  _reconciliation_ task on AD resource using Production configuration.
. Then have a look at the simulation results in midPoint GUI (interactively). Orphaned accounts should not be touched anymore - we will resolve them later.

Correlate the majority of your accounts now:

. Run the _import_ or  _reconciliation_ task on AD resource.
. Check the correlation statistics (TODO where exactly? Resource accounts? The accounts page is planned to be reimplemented in 4.8)
. Majority of your accounts should be linked to their midPoint owners.


Of course, you are doing this for the first time.
Chances are that you have not got all your configuration exactly right at the first try.
You may even need to update your HR resource configuration (e.g. if you forgot to import employee number) and reimport HR data.
Therefore, we assume you will work in iterations.
Simulations will guide you all the way.

//In case of deeper problem, it is still OK to scrap your AD resource and do it again (go back to <<connect-active-directory,step 3>>).
//Maybe you need to grab more data from HR feed (e.g. you may have forgotten to map employee number to midPoint).
//In that case you still can purge all identity data from midPoint, adjust HR configuration and import everything again (go back to <<import-users-from-hr,step 2>>).

== 5. Import Active Directory usernames

Until now, users in midPoint have been created with employee number (or similar) attribute from HR.
But your users already have Active Directory usernames.
We can reuse them also for midPoint users - the advantage will be more obvious later, if we switch the midPoint authentication mechanism to use Active Directory.

Re-configure the original HR inbound mapping for midPoint username: set its strength to weak.
This way it will be still possible to create midPoint users who have no Active Directory account.

Re-configure your Active Directory resource: add a new mapping from AD's login attribute to midPoint username.
Set the new mapping as strong to take precedence over HR, but keep it in Development mode for now.

Simulate the username import:

. Run the simulated _import_ or  _reconciliation_ task on AD resource using Development configuration.
. Then have a look at the simulation results in midPoint GUI (interactively).

For all users with Active Directory account, midPoint will indicate username change.
Inspect the changes and fix the username mapping in Active Directory if needed.

Re-configure your Active Directory inbound mapping: set it to Production mode.

Simulate the username import once again:

. Run the simulated _import_ or  _reconciliation_ task on AD resource using Production configuration.
. Then have a look at the simulation results in midPoint GUI (interactively).

Inspect the changes and fix the username mapping in Active Directory if needed, before you turn import them for real.

Import the usernames now:

. Run the _import_ or  _reconciliation_ task on AD resource.
. Majority of your midPoint users should be renamed according to their Active Directory usernames.
. Users without accounts in Active Directory will keep their original usernames from HR (based on e.g. employee number). Such users (without Active Directory accounts) can be easily found in midPoint.

== 6. Clean Up The Accounts

After the majority of the accounts have been correlated and usernames imported, we can handle the orphaned accounts (in situation `Unmatched`).

As you have already marked your accounts (and intentionally not marked some of them), you can run the simulated _reconciliation_ task with Development configuration once again to see what will happen.

The accounts you have marked previously should not be attempted to be deactivated.
Not marked orphaned accounts should be indicated for deactivation.

You are ready for clean up procedure:

. re-configure synchronization action for `Unmatched` situation: set it to Production mode
. run _reconciliation_ task with Active Directory with Production configuration to see what would happen one last time. If the simulation results correspond to what you have seen earlier with Development configuration, continue.
. run _reconciliation_ task with Active Directory
. not marked orphaned accounts should be deactivated
. additionally, the policy for orphaned accounts is set from now on, but the marked accounts will not be harmed.

You should periodically review your marked accounts, especially those "temporary" states such as "To be decommissioned", "Do not update" and "Correlate later".

You should also periodically run reconciliation task with your Active Directory to detect and deactivate any future orphaned accounts.
Unmarking those accounts and running _reconciliation_ task with Active Directory will remove them.

.##TODO @Radovan##: this paragraph should be probably somewhere else. Where?
====
This phase may seem as pointless phase.
Why not just go directly to automation?
That is what we really want!
However, assessment is all but pointless.
Automation can be done only after the assessment phase is done.
Attempts to automate processes with unreliable data are futile, they invariably lead to failures, usually a very expensive failures.
Speaking from a couple of decades of identity management experience, there is no such thing as reliable data, unless the data are cleaned up and systematically maintained with an assistance of identity management platform.
Simply speaking: you may think that our data is good, but they are not.
====

== 7. Prepare Active Directory for provisioning

Before turning on automation, we need to ensure the provisioning configuration for Active Directory resource is correct.
Especially if you are preparing the configuration in iterations, you need to make sure you are going right direction.
Simulations will guide you all the way.

Prepare / update outbound mappings for your Active Directory attributes.
If you want to force midPoint policy for attributes, you would need to make your mappings strong.
Enable your attribute mappings, but keep them in Development mode.

Prepare / update password outbound mapping(s) for your Active Directory:

. to generate _initial_ (strength: weak) random password for any new Active Directory account from no on.
The password will be forgotten; users need to cooperate with AD administrators or Helpdesk to gain their first credentials.
. to allow passing midPoint password changes to Active Directory (if needed).

Passwords may be also changed via Active Directory as usual (or both).

NOTE: midPoint authentication against Active Directory (or LDAP) is assumed for later steps.

Then you can start your simulations:

. Run the simulated _reconciliation_ task on AD resource using Development configuration.
. Then have a look at the simulation results in midPoint GUI (interactively).
. Inspect the results: if midPoint would change existing attributes in Active Directory or add new values, there should be a reason for, e.g.: policy vs data inconsistency
.. Active Directory attributes are incorrect/missing, midPoint attributes based on HR data are correct.
.. Active Directory attributes are correct, midPoint attributes based on HR data are incorrect
.. mappings have errors (you need to correct them)
. Fix data vs policy inconsistency by using one or several mechanisms:
.. let midPoint to override data in Active Directory
.. fix data in HR/midPoint and reimport
.. adjust midPoint policies (e.g. outbound attribute mappings)
.. define exceptions for specific accounts (e.g. using marks)
.. escalate the situation
. Repeat the process until all simulated changes make sense and can be executed for real

When all the inconsistencies are resolved, you are prepared.
You can turn on the provisioning:

. Set all outbound mappings to Production mode
. Run the simulated _reconciliation_ task on AD resource using Production configuration
. Then have a look at the simulation results in midPoint GUI (interactively) one last time.
. Run the _reconciliation_ task on AD resource

Your Active Directory resource is now configured.
Data inconsistency has been fixed.
Policy is defined, applied and will be followed from now on.
There is no automation between HR and midPoint, but we are already prepared for it.