= Methodology: First Steps With MidPoint: Automation
:page-nav-title: '3. Automation'
:page-display-order: 120
:page-toc: top
:experimental:



.Goal
TIP: Make on-boarding and off-boarding processes more efficient and reliable.
Save some money and improve efficiency by speeding up the processes.
However, the most important goal is enabled by _reliability_ of the automated processes.
Accounts belonging to off-boarded people are automatically disabled.
Orphaned accounts are reliably detected.
The most severe identity-related risks are addressed.


Finally, we have reliable data to build on.
What are we waiting for?

TODO

.User lifecycle
NOTE: We need to have user lifecycle figured, and mostly implemented/pre-configured at this step.
The lifecycle management starts with HR import.
But this is the point where it has to work well.

== Username Generation

We have previously imported all existing Active Directory usernames which became midPoint usernames.
Now it's time to prepare automation for this step.

. Disable (or remove) the inbound mapping in HR resource which populates midPoint username
. Disable (or remove) the inbound mapping in Active Directory resource which populates midPoint username
. Choose and activate (or create your own) username mapping in `Person Object Template` (object template for `Person` archetype) which will generate username based on given name and family name (e.g. `jsmith`, resolving duplicate usernames with suffixes, e.g. `jsmith2`)
+
TIP: The mapping can be used for `sAMAccountName` as it keeps the username under 20 characters (actually 8 + 2 digits for iterator)
. Keep this mapping _weak_. Usernames should never automatically change.

The new username policy is active from now on: for all new users created in the future.

.Naming convention notes
[NOTE]
====
Make sure your naming convention is good enough to not collide with existing AD/LDAP accounts (or other objects) that won't be imported to midPoint.
These include orphaned accounts that won't be imported (but still exist), system accounts etc.

In case of collision, you may want to rename such accounts in AD/LDAP or the colliding users in midPoint manually.

In case you would like to have more automated solution, you may want to create your own naming convention that avoids duplicate usernames in midPoint as well as in AD/LDAP by doing an additional check against AD/LDAP when generating midPoint username.
====

If your HR source already contains new records which have not yet been imported to midPoint, you can use the following mechanisms to double-check the username generator before going live:

* single HR account Import with preview action (_Production_ configuration)
* simulated HR import task (_Production_ configuration)

== On-Boarding Automation (Provisioning)

In this step, turn on the on-boarding automation for the joiners ##(TODO TODO TODOthe accounts will be only created)##.
##TODO TODO TODO The existing accounts will be kept "as is".##
If, however, your data are good, you may roll out the automatic account updates as well.
This is the right time to suspend your legacy on-boarding/provisioning process (e.g. scripts or manual processes).
If the accounts will be also updated, the behaviour in midPoint will be set as "tolerant" for the account attributes which may be still managed by other solution(s), e.g. access rights managed by request/approve process using tickets etc.
After the access right management is moved to midPoint, this tolerance should be turned off.

Until any roles are created and conditions for their automatic assignment are defined, the on-boarding automation may simply create accounts in Active Directory for all people from HR:

. Edit *Person* archetype
. Add inducement for Active Directory resource account for all users with Person archetype
. Create scheduled reconciliation task for HR resource


##TODO##: if we want to allow updates only for accounts created by midPoint (not linked during initial reconciliations), we need to have some additional information/metadata in the shadows.
Maybe even some marking - done before this phase, to mark existing shadows. Such accounts can be then handled similarly to protected accounts - just no errors to be printed, simply ignore provisioning for them.

== Off-Boarding Automation (Deprovisioning)

The automation between HR and midPoint covers on-boarding as well as off-boarding as data is transferred from HR to midPoint and then from midPoint to Active Directory.

##TODO: mention how the lifecycle will behave for former employees. The accounts should be ideally disabled (indefinitely or for some time and then deleted)##

If Lifecycle state is used, `Suspended` users' accounts in Active Directory will be disabled.

Users will be kept in midPoint indefinitely.

== Follow-Up Steps

The next steps can include:

. *Add additional source system* e.g. for additional populations

. *Add additional target system*

. *Automate scans* for orphaned accounts in Active Directory with automatic reaction (or reporting/notification).

. *TODO: Start moving self-service (password change/reset) to midPoint? Probably makes not much sense if only AD is provisioned by midPoint.*

. *Switch from batch mode to event-driven synchronization (Live synchronization) from HR*.

. *Import existing Active Directory groups as roles and assign these roles* to midPoint users corresponding to the AD group members

. (Probably in IGA phase) *Start creating roles* for request/approvals (based on existing roles in the organization). Move request/approval process to midPoint.

. (Probably in IGA phase) *Start creating roles* for automatic/conditional assignment. Use role auto-assignment expressions.