= Methodology: First Steps With MidPoint: Automation
:page-nav-title: '3. Automation'
:page-display-order: 120
:page-toc: top
:experimental:


Finally, we have reliable data to build on.
What are we waiting for?

TODO

TODO When to actually clean up the orphaned/inconsistent data?
[loweralpha]
. at the end of Step 2 (Assessment)
. in Step 3 (Automation, Off-boarding phase)

TODO It makes sense in Step 2, as we are doing clean up, but deleting orphaned accounts is irreversible.
It also makes sense in Step 3, as this is where we already intend to modify the AD.

. *On-boarding automation* (provisioning).
TODO
Create new accounts for users. (Mappings only for create.)
Leave existing accounts "as is".
If your data are good, you may roll-out automatic account updates as well.
This is the right time to suspend your legacy on-boarding/provisioning process (e.g. scripts or manual processes).
+
TODO: in order to "create new accounts for users" we need to know fow who, i.e. we already need to have some conditions.
Even if we don't have roles and simply assign accounts in AD.
E.g. we may want to assign AD accounts for all active employees.
+
TODO where will administrator enter the condition(s) for automatic assignments? Certainly not using object template with XML...
We cannot use role autoassignment, as we do not have any role yet.
+
TODO: if we want to allow updates only for accounts created by midPoint (not linked during initial reconciliations), we need to have some additional information/metadata in the shadows.
Maybe even some marking.
+
TODO: maybe start with reconciliation instead of Live Synchronization to allow thresholds. (Thresholds for Create-only are maybe not relevant, but for updates...) For small organizations, reconciliation should be fast enough to run daily/more often. Batch vs event-driven. In case the source data is deleted instead of disabled, we may need reconciliation for off-boarding phase anyway.

. *Off-boarding automation* (de-provisioning).
* TODO we need to distinguish when to do off-boarding by some conditions (i.e. account assignment should be unassigned when employee is inactive)
* TODO we prefer disabling users in midPoint rather than deleting
* TODO we prefer disabling accounts rather than deleting
* TODO archive midPoint users instead of just disabling?
** This would not be possible using synchronization reaction. If we could distinguish that that account should be considered `archived` in HR (e.g. via configured capability?) we could have a new situation + new reaction *NEW FEATURE REQUIRED*
** lifecycle transition to `archived` can clean up some attributes (GDPR)
** delayed user deletion after X years in `archived`

. *Automate scans* for orphaned accounts.

. *Switch from batch mode to event-driven synchronization from HR*.

*Goal*: Make on-boarding and off-boarding processes more efficient and reliable.
Save some money and improve efficiency by speeding up the processes.
However, the most important goal is enabled by _reliability_ of the automated processes.
Accounts belonging to off-boarded people are automatically disabled.
Orphaned accounts are reliably detected.
The most severe identity-related risks are addressed.
