= Methodology: Group Synchronization
:page-nav-title: 'Group synchronization'
:page-display-order: 140
:page-toc: top
:experimental:
:page-since: "4.9"
:page-visibility: hidden

WARNING: Work in progress!


== Introduction

Evolveum's xref:/midpoint/methodology/first-steps/[First Steps with MidPoint methodology] has been created to quickly deploy midPoint for users and their accounts.

However, it has been prepared to be universal.
This document extends that methodology with the approach of connecting resource _groups_ and migrating them to midPoint _roles_.
After the migration, the groups are to be managed exclusively via midPoint roles.

#TODO more#

Before continuing, please make yourself familiar with xref:/midpoint/methodology/first-steps/[First Steps with MidPoint methodology].

== Connect Active Directory Resource for Groups

Connect Active Directory as a group data source to midPoint.
Decide which type of midPoint objects you want to use to represent the groups (Roles, Organizations, Services).
Roles are most typically used to represent the groups.

Establish a role naming convention that suits your environment.
The role names are typically based on group identifiers, but there could be multiple systems with the same group identifiers, yet the role name must be unique.
The simplest way how to achieve the uniqueness of the role name is to prefix the group name with the resource name.

For example, for group `cn=administrators, . . .` in `AD` resource, you can create role `ad:administrators`.

Create the new object type in `Proposed` lifecycle state to allow simulations.
Configure the object type to create a new archetype for all roles created by its configuration.
It will allow to quickly filter the roles and define provisioning behavior for them: the future roles will have a group projection and all role members will have account in resource and account associated with the group.

Configure synchronization configuration to make Active Directory resource authoritative for role creation and deactivation/deletion based on new/deleted groups.

Create inbound mappings to allow creation of midPoint roles for at least:

* Name
* Display name (optional)
* Description (from group description, if it exists)
* Identifier (from group identifier, e.g. `cn` or `dn`)

The main idea is that you may use group identifier for correlation with midPoint roles and still have unique role name.
Display name may be derived from group identifier and/or can be changed anytime by the administrators.

Configure associations for group membership in `Proposed` lifecycle state.
Create inbound association mappings to allow assignment of midPoint roles based on user accounts' associations (resource group membership) if the role is not already assigned indirectly.

Configure Default operation policy as `Unmanaged` to automatically consider all resource groups as "inbound-only" objects.

If there are _legacy_ groups that cannot be migrated to midPoint because they are still managed by another system (e.g. legacy IDM tool), create Marking rules to explicitly mark such groups as `Unmanaged`.

== Import Groups

Start with import simulation while the object type for groups is in `Proposed` lifecycle state.
Adjust the inbound configuration as necessary.
When finished, switch the object type to `Active` lifecycle state and import the groups to create midPoint roles.

TODO: schedule regular reconciliation?

NOTE: Active Directory resource is authoritative for the groups and role creation.

== Import Group Membership

Start with import simulation while the association type configuration is in `Proposed` lifecycle state.
Adjust the inbound configuration as necessary.
When finished, switch the object type to `Active` lifecycle state and import the group membership to create midPoint role assignments.

TODO: schedule regular reconciliation?

NOTE: Active Directory resource is authoritative for the group membership and role assignments/unassignments.

== Migrate Group Management to MidPoint

Configure the Active Directory resource outbound behavior for groups and their membership (associations).
You don't need to use `Proposed` configuration while the Default operation policy is `Unmanaged` as the provisioning is completely ignored.
We recommend using the role `Identifier` as a source of group identifiers for the following reasons:

. it has been derived from group identifiers for existing groups
. the role name or display name may be changed by administrators and it should not automatically rename the group

The outbound association configuration basically allows account membership management using midPoint role assignments.

The migration of the groups follows in several steps.

=== Migrate Selected Groups to MidPoint

This step allows to _test_ the configuration and/or to allow group-by-group approach: select one or several groups which have been already imported to midPoint as roles.

. mark the selected group(s) with mark(s): *Managed* with lifecycle state: `Proposed`
. edit the corresponding role and attempt to make a simulated modification (using Preview with development configuration) to allow outbound mappings to be evaluated in simulation
. run reconciliation with Active Directory resource accounts with development configuration to allow outbound association mappings to be evaluated in simulation
. update the *Managed* marks: change their lifecycle state to: `Active`

NOTE: MidPoint is now authoritative for the groups with `Managed` mark.
If the groups are updated in Active Directory resource, midPoint will overwrite the group attributes and maintain the group membership according to the role assignments.

NOTE: MidPoint cannot create new groups yet, as the Default operation policy is still `Unmanaged`.

=== Migrate Non-legacy Groups to MidPoint

After you have performed migration of one or several groups in the previous step, you can migrate all non-legacy groups in a single step by changing Default operation policy, while the marking rule for _legacy_ groups is still in place and prohibits migration of such groups to midPoint.

. change Default operation policy: set the lifecycle state for `Unmanaged` to: `Deprecated` and add a new policy: `Managed` with lifecycle state: `Proposed`

. run reconciliation with Active Directory resource groups with development configuration to allow outbound mappings to be evaluated in simulation

. run reconciliation with Active Directory resource accounts with development configuration to allow outbound association mappings to be evaluated in simulation

. if the simulations do not show any incorrect behavior, change the Default operation policy again: set the lifecycle state for `Unmanaged` to: `Archived` and lifecycle state for `Managed` to: `Active`

NOTE: MidPoint is now authoritative for all groups and their membership except the _legacy_ groups which have `Unmanaged` mark.

== Automate Group Integration

Even with _legacy_ groups in place, midPoint is now able to create new groups.

TIP: By editing the group role archetype, you can add focus mappings to only ask administrators for role Identifier and automatically fill in other role properties, such as Name and Display name.

By creating new roles with the group role archetype, the new groups will be automatically created in the Active Directory resource.

After the _legacy_ groups are not created by IDM tool anymore, processes have been updated and administrators trained, restrictions for _legacy_ roles can be removed:

. delete marking rules specific for _legacy_ groups to make midPoint handle them using the Default operation policy (now `Managed`)
. update synchronization configuration to stop  Active Directory resource being authoritative for roles.
Instead, configure midPoint to either delete unmatched groups or mark them automatically.
Also, configure midPoint to re-create any groups forcibly deleted in Active Directory resource.

NOTE: Migration of the Active Directory resource groups to midPoint has been finished.
From now on, midPoint is authoritative for the group creation and deletion and for the group membership based on the role assignments.

== [TODO heading level] Use Person Archetype for Birthrights

If there are any groups (roles) which should be automatically assigned to _all_ users, `Person` archetype can be modified to allow this automation:

. edit `Person` archetype
. edit inducement for the Active Directory resource account and set its lifecycle status to: `Deprecated`
. add new inducements for roles that should be automatically assigned and set their lifecycle status to: `Proposed`
. run a simulated reconciliation task for HR resource with development configuration
. edit `Person` archetype once again, remove (or archive) the inducement for Active Directory account and activate the inducements for the roles that should be automatically assigned to all users of `Person` archetype

You can also do a cleanup - unassign the roles that are now being induced by `Person` archetype, from all users.
For each such role:

. edit the role in midPoint
. unassign all its members (direct role assignments)


== #TODO:# Start Managing Roles (IGA?)

#TODO We can bridge to another methodology; if we manage to have IGA basics in the Group synchronization training, we can have something also here.#

== Conclusion

The approach presented here is not limited just for groups and roles.
In fact, it can be used to synchronize any resource objects with any focal objects in midPoint, for example:

* resource groups with midPoint organization structure
* resource organizational units with midPoint organization structure
* resource printer objects with midPoint services

With a good naming convention, multiple resources having the same names (identifiers, `cn`, `dn` etc.) of resource objects can be connected to unique role-like objects.
One example of such naming convention is suggested in this methodology.


== TODOs

TODO: what about inbounds - forever, but not active because of Unmanaged?