= Make a Deployment Plan
:page-nav-title: 'Make a Plan'
:page-display-order: 70
:page-toc: top
:experimental:

.Goal
TIP: Assess your resources, capabilities and goals.
Set your target.
Decide whether the project is feasible.
Make a rough plan.
Get long-term support from management.
Secure budget.

Now that you have a rough idea of what's an IGA project about, it's time to make a plan.

Before you involve a broader spectrum of people in your organization, devise a rough idea of what you want to achieve and how does it help your organization.
Prepare a pitch-talk making it clear why it's a good idea to implement an IGA solution.

[TIP]
====
Be ready to explain clearly why midPoint is your solution of choice.
====

The sections below contain guidance on how to select your advisory team, what questions to ask, and what to take care of.

== Pick the Team Members

Start with a brainstorming or "kick-off" meeting.
Bring together all the people in your organization who are interested in identity management.
This doesn't have to be a formal team.
The project is not yet formally established anyway.

Here are some tips on whom to invite:

* A *senior IT engineer* or an architect.
Identity management is related to many different areas.
You need someone who can see the big picture and understands IT.

* *Administrator of a critical IT systems* with which you want to integrate midPoint.

* A *member of HR* familiar with HR practices.
HR is going to be your information source and you need someone that can help you assess the impact of HR practices on the IGA project.

* A *security professional*.
Identity management and governance is closely related to information security.
There may be policies, limits, and goals given by company security policy you need to consider in your plans.

In smaller organizations, this can be a meeting of just a couple of people over coffee.
It could be a series of meetings.
Do whatever suits your organizational culture the best.

== Topics for Discussion

Here is a list of topics you should discuss with your team.
You probably won't have all the answers after the first session.
That's OK.
It's important to know that these questions are there to be answered eventually.
The sooner you find the answers, the faster your progress will be.

=== What Are Your Data Sources?

A data source is a system you can consider authoritative and from which you can pull data _into_ midPoint.

You probably have many systems with identity data, but only some can be considered authoritative.
The HR system is likely your first choice because its data usually _are_ correct and authoritative.

[CAUTION]
====
*Do you have other reliable source systems?*
If so, could their data be in conflict?

For example, one system might say that an employee's name is "John," while another system says it is "Johannes."

In that case, which system do you trust?
====

==== Questions Regarding Data Handling

* How do you add records about new employees?

* What happens with data on former employees?
    ** Are the records deleted?
    ** Do you keep them marked as inactive?
    ** Do you only set a layoff date?

* What's the unique identifier of each HR record?
    ** Is it guaranteed to be unique?
    ** Do all your systems share the identifier?

* What happens if a former employee comes back to the organization?
Do you start over with a new ID or can you reuse the old records?

Ask the HR department for some sample data to ensure the data formats will work for you.

If you can, request a few sample data exports (like daily or weekly) to see trends in the data: +
For example, whether the exports include former employees, what's the approximate number of changes per period, etc.

=== What Data Targets Do You Need to Synchronize?

As opposed to data sources, data targets are systems that hold identity data but aren't authoritative.
Your goal is to _push_ data _from_ midPoint _to_ target systems to ensure identity data consistency.

The usual setup is that you mostly write to target systems and use the authoritative source systems to overwrite any conflicting data.
Of course, this depends on your situation.
A system may be both source and target.
You'll see further down the lane how you can temporarily use a target system also as a source for a select attribute.

In this guide, we use an Active Directory (LDAP) server as an example target system.
Whatever target systems you have, discuss their internal data structure with their administrators so that you know what you're going to work with in midPoint.

For example, in the case of an AD/LDAP server:

* How are users distributed among *organizational units*?
* How are *usernames* created?
    Are there conventions for the process?
    Any exceptions to these conventions?
* Is there a reliable *unique identifier* of user accounts?
    Maybe an employee number is conveniently stored in the `employeeNumber` attribute?

Look at live AD data, select a few samples (such as your own account), and roughly assess the situation.
Then, compare the sample with a record of the same account in the HR system.
This will help you see the common attributes and figure out how to map the accounts.

Discuss *other data targets*.
What other systems would you like to connect to your identity management deployment in the future?
Consider just the big picture for now.
You don’t need to go into all the details.
Just roughly set the scope, listing and prioritizing the systems.
Although this step is completely optional, it helps a lot with planning and budgeting.

=== How Much Security Do You Require?

What security measures do you need to implement?
Discuss the limitations, requirements, and wishes given by your information security authorities.

It's important to distinguish _requirements_ and _wishes_.

Your security official will likely give you a long list of _hard requirements_ that _must_ be implemented _right now_.
That's understandable and all right.
However, in this phase, it's important that you don't get distracted by theoretical discussions of information security.

You're doing this whole activity to improve _real_ security, clean up your data, and automate processes.
Not to implement false sense of security on data that are wrong and insecure anyway.
Discuss the practice, the current state, the day-to-day reality.
Be honest with yourself.

Hear the long-term requirements, make a plan to address them, and focus on what's non-negotiable and _possible to implement_ right now.
The rest comes later.

=== Plan your budget

Discuss *resources, timing, and rough plan*.

Keep your plan realistic.
Identity management requires:

* Systematic approach
* Time
* Money
* A lot of patience

Too many projects have failed due to unrealistic plans and expectations.

Set modest goals that you can achieve in a few weeks.
*Start by connecting your first source and target systems to get first results in days.*
Then proceed in iterations, delivering improvements every few weeks.

Discuss who will lead the project, who needs to be involved, what other resources you need.

And most importantly, *prepare for a long run*.
This project doesn't have specific start and end dates.
It will be with you *from now to eternity*.

Last but certainly not least, *discuss money*.

You will need money, even if you plan to do most of the work internally.
You will need training, assistance and support.

.Plan for recurring budget
[TIP]
====
Having a modest budget every year can lead to a successful IGA program.
Having a generous budget for the first year and no budget after that is a certain way to an expensive failure.
====

== Get a Buy-In From Your Management

Once you develop a rough plan and estimates regarding required money and time, *go talk to your management*.
It's crucial to get their buy-in, get them to believe that your IGA mission is meaningful and that it makes sense to invest money in it.

Don't oversell and exaggerate.
Provide honest plan and estimates, set realistic expectations.
Identity management is a long run, any kind of hype or exaggeration is very likely to backfire in the future.
Get a green light—for a long program, not just for a short project.

And with that, you’re ready to go.