= MidPoint Compliance
:page-nav-title: Compliance
:page-display-order: 60
:page-visibility: hidden
:page-upkeep-status: yellow

MidPoint is a practical identity governance and administration platform, designed to address real-world challenges.
MidPoint deployments are subject to numerous regulations, industry standards and similar specifications.
This page provides a summary of compliance frameworks that are likely to affect midPoint deployments.

== International

International Organization for Standardization (ISO) is a prime international standards body, publishing several specifications that affect midPoint deployments.

* *xref:iso27001[ISO/IEC 27000 Series]* of standards deal with information security management systems (ISMS), an essential building block of cybersecurity.
The standard series describes _best practice_ in the field, providing recommendations and guidance.

** xref:/glossary/iso27000/[ISO/IEC 27000] specification provides an introduction and a vocabulary.
+
xref:/glossary/iso27000/[ISO 27000 vocabulary] was xref:/glossary/iso27000/[mapped] to xref:/glossary/[midPoint vocabulary] to improve understanding.
Moreover, some terms of midPoint vocabulary were adapted to standard ISO27000 vocabulary.

** xref:iso27001[ISO/IEC 27001] specification is the normative core of 27000 series.
It specifies requirements for establishing, implementing, maintaining and continually improving an information security management system (ISMS).
Annex A of the specification provides list of concrete information security controls.

** ISO/IEC 27002 specification provides additional information on best practice and further guidance for implementation and maintenance of information security management system (ISMS).
Controls listed in ISO 27001 Annex A are further explained in ISO 27002 document.

// TODO: ISO 24760

NOTE: ISO specifications are not freely accessible, therefore we cannot link to the documents directly.

== European Union

European Union is a global leader in information technology and cybersecurity legislation.
There are numerous regulations and directives, many of which have applicability far beyond the boundaries of European community.
This page lists the most important legislative acts, focusing mostly on the near future.
Many of the acts are at the very beginning of their applicability, or even just being shaped for future use.

* *NIS2 Directive* (link:https://eur-lex.europa.eu/eli/dir/2022/2555[2022/2555]) specifies requirements for security of networks and information systems.

* *Critical Entities Resilience (CER) Directive* (link:https://eur-lex.europa.eu/eli/dir/2022/2557[2022/2557]) deals with resilience of critical entities, such as providers of essential services.

* *Cyber Resilience Act (CRA)* (link:https://eur-lex.europa.eu/eli/reg/2019/1020/oj[2019/1020]) is a proposed regulation, placing responsibility for digital product security on manufacturers, integrators and importers rather than users.

* *Product Liability Directive (PLD)* (link:https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A52022PC0495[COM/2022/495 final]) is a proposed directive that changes the rules of liability for defective products.
The directive places liability for defective products on manufacturers, integrators and importers, including liability for software products and cloud services.

* *Artificial Intelligence Act (AIA)* (link:https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A52021PC0206[COM/2021/206 final]) is a proposed regulation on artificial intelligence, specifying limits of acceptable use of AI technologies.

* *General Data Protection Regulation (GDPR)* (link:https://eur-lex.europa.eu/eli/reg/2016/679/oj[2016/679]) is a broad regulation dealing with protection of personal data.

* *EU Common Criteria (EUCC)* (link:https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=PI_COM:C(2024)560[C(2024) 560 final]) is a proposal of product cybersecurity certification scheme based on Common Criteria.

== United States

// TODO: NIST CSF

== Disclaimer

// TODO: we are not lawyers, best effort
// TODO: most regulations apply to organizations, not products. MidPoint cannot provide compliance out-of-the-box, it can only help.
