= MidPoint Compliance
:page-nav-title: Compliance
:page-display-order: 60
:page-upkeep-status: yellow

MidPoint is a practical identity governance and administration platform, designed to address real-world challenges.
MidPoint deployments are subject to numerous regulations, industry standards and similar specifications.
This page provides a summary of compliance frameworks that are likely to affect midPoint deployments.

// It is quite clear that identity governance and administration (IGA) is an essential part of compliance, providing a solid foundation for cybersecurity.

== International

International Organization for Standardization (ISO) is a prime international standards body, publishing several specifications that affect midPoint deployments.

* *xref:iso27001[ISO/IEC 27000 Series]* of standards deal with information security management systems (ISMS), an essential building block of cybersecurity.
The standard series describes _best practice_ in the field, providing recommendations and guidance.

** xref:/glossary/iso27000/[ISO/IEC 27000] specification provides an introduction and a vocabulary.
+
xref:/glossary/iso27000/[ISO 27000 vocabulary] was xref:/glossary/iso27000/[mapped] to xref:/glossary/[midPoint vocabulary] to improve understanding.
Moreover, some terms of midPoint vocabulary were adapted to standard ISO27000 vocabulary.

** xref:iso27001[ISO/IEC 27001] specification is the normative core of 27000 series.
It specifies requirements for establishing, implementing, maintaining and continually improving an information security management system (ISMS).
Annex A of the specification provides list of concrete information security controls.

** ISO/IEC 27002 specification provides additional information on best practice and further guidance for implementation and maintenance of information security management system (ISMS).
Controls listed in ISO 27001 Annex A are further explained in ISO 27002 document.

* *PCI DSS* (link:https://east.pcisecuritystandards.org/document_library?category=pcidss&document=pci_dss[PCI DSS 4.0]) helps protect the people, processes, and technologies across the payment ecosystem to help secure payments worldwide. It is mandatory to all organizations that participate in the storage, processing, or transmission of cardholder data.

// TODO: ISO 24760

// TODO: ISO/IEC 15408 Common Criteria

ISO specifications are not regulation or legislation, therefore they are not binding _per se_.
However, several legislative documents and regulations are referencing ISO specification either directly or indirectly (as "industry best practice").
Therefore, ISO specifications form a practical baseline for cybersecurity requirements.
Compliance with ISO specifications is required or expected in many legislative and regulatory environments.

NOTE: ISO specifications are not freely accessible, therefore we cannot link to the documents directly.

== European Union

European Union is a global leader in information technology and cybersecurity legislation.
There are numerous regulations and directives, many of which have applicability far beyond the boundaries of European community.
This page lists the most important legislative acts, focusing mostly on the near future.
Many of the acts are at the very beginning of their applicability, or even just being shaped for future use.

* xref:nis2[*NIS 2 Directive*] (link:https://eur-lex.europa.eu/eli/dir/2022/2555[2022/2555]) specifies requirements for cybersecurity of networks and information systems.

* *Digital Operational Resilience Act (DORA)* (link:https://eur-lex.europa.eu/eli/reg/2022/2554/oj[2022/2554]) is a sector-specific regulation applying to financial sector.
It sets rules for financial institutions to follow sound cybersecurity practices, including strict requirements for use of third-party services.

* *Critical Entities Resilience (CER) Directive* (link:https://eur-lex.europa.eu/eli/dir/2022/2557[2022/2557]) deals with resilience of critical entities, such as providers of essential services.
CER directive applies broad approach to security and resilience, including both cybersecurity and physical security practices.

* *Cyber Resilience Act (CRA)* (link:https://eur-lex.europa.eu/eli/reg/2019/1020/oj[2019/1020]) is a proposed regulation, placing responsibility for digital product security on manufacturers, integrators and importers rather than users.

* *Product Liability Directive (PLD)* (link:https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A52022PC0495[COM/2022/495 final]) is a proposed directive that changes the rules of liability for defective products.
The directive places liability for defective products on manufacturers, integrators and importers, including liability for software products and cloud services.

* *Artificial Intelligence Act (AIA)* (link:https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A52021PC0206[COM/2021/206 final]) is a proposed regulation on artificial intelligence, specifying limits of acceptable use of AI technologies.

* *Cybersecurity Act (CSA)* (link:https://eur-lex.europa.eu/eli/reg/2019/881/oj[2019/881]) establishes European cybersecurity certification framework for digital products, services and processes, granting permanent mandate to https://www.enisa.europa.eu/[ENISA].

* *EU Common Criteria (EUCC)* (link:https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=PI_COM:C(2024)560[C(2024) 560 final]) is a proposal of product cybersecurity certification scheme based on Common Criteria.
It is based on framework set up by the Cybersecurity Act (CSA), following principles of ISO/IEC 15408.

* *eIDAS 2.0* (link:https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=COM%3A2021%3A281%3AFIN[COM/2021/281 final]) is a proposed update to European digital identity (eID) framework. It aims at providing secure and trustworthy electronic identification and authentication, including European digital identity wallet.

* *General Data Protection Regulation (GDPR)* (link:https://eur-lex.europa.eu/eli/reg/2016/679/oj[2016/679]) is a broad regulation dealing with protection of personal data.

Most of the listed regulatory acts are based on https://digital-strategy.ec.europa.eu/en/library/eus-cybersecurity-strategy-digital-decade-0[EU Cybersecurity Strategy for the Digital Decade],
a cybersecurity strategy document published in 2020.

EU legislation primarily applies to the European Union member states.
However, as many regulations apply to any entities that participate on European markets, the legislation has much broader applicability.
It is perhaps not an overstatement that EU legislation has a global impact.
Compliance with EU legislation is applicable to many entities with a global reach.

In addition to legislation and regulation, there are recommendations and best practices:

* xref:enisa-baseline[*ENISA Indispensable baseline security requirements for the procurement of secure ICT products and services*] (link:https://www.enisa.europa.eu/publications/indispensable-baseline-security-requirements-for-the-procurement-of-secure-ict-products-and-services[full text]) provides practical, technologically neutral minimum necessary indispensable requirements for secure ICT products and services.

== United States

US National Institute of Standards and Technology (NIST) publishes cybersecurity standards relevant for US environment.

* *NIST Cybersecurity Framework (CSF)* (link:https://www.nist.gov/cyberframework/csf-11-archive[1.1], link:https://csrc.nist.gov/pubs/cswp/29/the-nist-cybersecurity-framework-20/ipd[2.0]) is set of guidelines for mitigating cybersecurity risk.
It provides taxonomy of high-level cybersecurity outcomes that can be used by any organization to better understand, assess, prioritize, and communicate its cybersecurity efforts.

* *NIST SP 800-53* (link:https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r5.pdf[NIST SP 800-53 Rev. 5]) - Security and Privacy Controls for Information Systems and Organizations. It is mandatory for all U.S. federal agencies (federal information systems) except those related to national security. It is also applied to government contractors who operate on or manage federal IT networks.

* *NIST SP 800-171* (link:https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-171r2.pdf[NIST SP 800-171 Rev. 2]) - Protecting Controlled Unclassified Information in Nonfederal Systems and Organizations. Compliance is required for non-federal information systems and organizations that process, store or transmit Controlled Unclassified Information (e.g., contractors for the Department of Defense, General Services Administration, NASA or other federal or state agencies’ supply chain).

* *Gramm-Leach-Bliley Act* (link:https://www.ftc.gov/legal-library/browse/statutes/gramm-leach-bliley-act[GLBA]) - requires financial institutions – companies that offer consumers financial products or services like loans, financial or investment advice, or insurance – to explain their information-sharing practices to their customers and to safeguard sensitive data.

* *Health Insurance Portability and Accountability Act* (link:https://www.hhs.gov/hipaa/index.html[HIPAA]) - healthcare organizations (Covered entities) and their employees that have access to PHI (protected health information) and organizations that provide services to covered entities that involve access to PHI.

* *Sarbanes-Oxley Act* (link:https://sarbanes-oxley-act.com[SOX]) - is required of all companies that are traded publicly in the United States, as well as subsidiaries that are wholly owned. The Act contains provisions affecting corporate governance, risk management, auditing, and financial reporting of public companies, including provisions intended to deter and punish corporate accounting fraud and corruption.

US regulation primarily applies to US government and agencies.
However, it may apply to entities that deal with US government as well, e.g. US government suppliers.
Moreover, NIST publications are considered to describe general best practice, accepted by many organizations and governments globally.
Compliance with NIST CSF may be required even outside US environment.

// TODO: Sector-specific: PCI DSS (International?), HIPAA (US only?)

== Disclaimer

We provide the information on legislation, regulation and compliance in good faith.
However, we are not lawyers, and the globalized international environment can get very complex.
It is not easy to determine which regulation or specification applies to specific entities, under which circumstances, and what are the implementation details for a specific environment.
Please, take the information provided here with caution.
Always seek professional legal advice when in doubt.

Please also note that most compliance requirements apply to organizations, not products.
However hard we might try, midPoint cannot guarantee you compliance with any regulation out-of-the-box.
This is not how it works.
MidPoint, being an identity governance platform, is an essential tool for compliance with almost any cybersecurity regulation.
However, midPoint is just one of the tools that you will need to comply with regulations.
There will be other tools, as well as policies, processes and practices specific for your organization.
We are doing our best to make sure midPoint can help you reach cybersecurity compliance.
However, all we can do is help, the task of being compliant is ultimately up to you.
