= Role Engineering and Maintenance Process
:page-nav-title: Role Engineering and Maintenance
:page-display-order: 200
:page-toc: top
:toclevels: 3
:sectnums:
:sectnumlevels: 3

WARNING: This page is a stub, it is a work in progress.

Role engineering and maintenance process describes process of collection of various technical information and their synthesis and transformation into business object representing way of accessing of the application - the application role. Also, this process involves collection of application roles into business role - business representation of access of particular business user.

This process requires a cross-team cooperation. Although some application roles may be defined by application engineers or administrators themselves, multiple positions must be involved for some other roles. The individual tasks in the process are sometimes unclear. People may understand the concepts and rules differently, the applications may have different internal data models etc.

To have the process manageable, it is designed with the xref:../concepts.adoc[IGA design concepts] in mind.

== The Role Engineering and Maintenance Process

The Role engineering and maintenance process (sometimes just Role engineering process) is designed to be lightweight and fast, but needs to be fully documented and governed by Role manager. Exceptions are to be managed by IGA administrator or Role manager himself.

Each role must be designed by Application engineer. Role definition is technical description how application users are integrated in the organization environment. This is something that application engineer must design during integration process. While defining the application roles, the application engineer transforms this design into IDM technology configuration.

Midpoint must help the application engineer in filling the information needed for configuring role inducements in a way and in terminology that the engineer can easily understand. Where the application engineer can't act independently, the IGA administrator must help.

Details of the process are described here: xref:role-engineering-details.adoc[Role engineering process]

.Application definition

The definition of application roles requires one additional step - definition of application. Applications should be related to application inventory and the objects should be created automatically or manually by application engineer.

. Step 1: Application engineer creates application
. Step 2: Application engineer defines roles for the application

Basic step is the definition of an application. The application object can collect data about how the access into application is defined. Whether existing resource or manual connector.

#TODO# not clear yet, whether this information is needed in application definition or just having it in the roles is not enough.

#TODO# If needed, prepare this procedure in detail.

NOTE: if an application definition requires manual tasks, then probably additional manual resource will be needed for such definition - this will decrease speed of role design and application integration.


=== Application Role definition
Definition of application role is not an easy task. It often can't be performed by one person only. Application engineer knows about the application, but may not have enough knowledge of identity management system. Here, the IDM administrator must help. So this definition is often product of cooperation of these two positions.

To offload IDM administrators, Midpoint must support application engineers with good interface for role definition.
As midpoint configuration may be very complex, the interface must abstract of midpoint terminology and structure and provide the application engineer structured data in a form that the skilled IT engineer is able to fill intuitively or after minimum of learning.

Following schematic interface for xref:iga-schemas-app-role-design.png[Application role design] provides view of what elements should be provided to application engineer for definition.

NOTE: Some operations for roles modification (e.g. massive updates) may be performed by IGA administrator using Midpoint studio.



=== Business role definition

Definition of business role is easier, and therefore it may be managed by business personnel. At least at beginning the business roles definitions and configuration will be managed mostly by Role manager or IGA administrators based on his requests.

The process for engineering of business roles is the same as for application roles. Only difference is that business role creation may be requested by business user.
//TODO: preverit si tabulku detailov.

Schematical description of user interface for business role request is here: xref:iga-schemas-business-role-design.png[Business role design]

=== Role updates and role decommisioning

Of course role definition may be modified. The modification also needs to go through approval process. All existing assignments are updated according to the new definition only after the role modification is approved.

Recompute of users having the role will be needed.
//TODO - linka na recompute do detailov.


== Process Monitoring and Optimization

TODO
// Ako bude prebiehat manazment procesu a jeho optimalizacia.

=== Weekly role design commitee

For increasing of the process throughput ... TODO
// toto je potrebne pre zefektivnnenie procesu - na tejto platforme dokaze efektivnejsie riesit zlozite definicie pri ktorych je potrebna komunikacia. Tu musi vidiet role manager aktualne requesty a musi ich byt schopny rychlo spracuvat - modifikovat, schvalit, vratit na prepracovanie.


== Troubleshooting the process

TODO
// sem popisy, ake problemy mozu nastat a ako ich riesit

== Process examples

TODO
// tuto prejst na prikladoch, ako by taky proces vyzeral, co by bolo potrebne urobit

=== Application deployment

TODO
// tuto prejst popis procesu nasadenia aplikacie - spojenie s definovanim roly a postupne vytvaranie.