= Role Engineering and Maintenance Process
:page-nav-title: Role Engineering
:page-display-order: 200
:page-toc: top
:toclevels: 3
:sectnums:
:sectnumlevels: 3

WARNING: This page is a stub, it is a work in progress.

Role engineering and maintenance process describes process of collection of various technical information and their synthesis and transformation into business object representing way of accessing of the application - the application role. Also, this process involves collection of application roles into business role - business representation of access of particular business user.

The role modeling and governance requires a cross-team cooperation. Although some application roles may be defined by application engineers or administrators themselves, multiple positions must be involved in the role design and configuration for some other roles. The individual tasks in the process are sometimes unclear. People may understand the concepts and rules differently, the applications may have different internal data models etc.

== Concepts

The concepts are defined to have here rules that will lead us to make the IGA deployment not only manageable by skilled IDM personnel, but - and this is even more important - also readable by business people. The IDM system serves the business, so it must be clearly readable by business people in business terminology.

Midpoint is very flexible. This flexibility enables multiple ways of solving the problems - and this generates complexity. The concepts also help to decrease complexity of the solution, which increases readability by business.

Applications::
Applications are basic building blocks for defining access. These objects may contain the definitions of components needed for access (resource, object type, groups). The lifecycle of applications should be interconnected with application inventory.

//TODO: opravnenia v ramci aplikacii by sme mali volat permissions

Application roles::
Basic roles are basic roles. They are related to applications. The application roles are integrating technical components for creation of user access with business description of the access. Business users are working with business description from the application roles, IDM system and IDM administrators are working with technical definitions.

Application Role definition contains all components needed for access::
The application role should contain all components needed for the role assignment. If the role contains rules for automatic assignment, even assignment of the role to the users.

Business roles::
Business roles are just collections of application roles. Business roles should be fully readable by business people.
They can contain sometime other business roles, but too deep hierarchy may decrease readability and increase maintenance costs.

Organization units vs roles::
Even though OUs and roles are basically the same in MP, it should be strictly separated for business users, to decrease confusion. Of course, role may be assigned to OU and through it to its members - this concept is quite natural.

The process is governed by Role manager::
The task of the Role manager in this process is the coordination of the application role design. Often it is needed to correct the naming, description of the roles or other business components, to have the new roles in line with the role model. The Role manager, or IGA administrator, who is processing the request, should be able to align the requirements of the application owner or administrator (the requester) with the role model and technical options and find the best application role design for the application.

Differences in the process between application and business roles::
The processes of role engineering for application roles, business roles and IT roles, are slightly different. The difference is based on complexity of the roles and involved actors. Application roles are more technical and their definition is much more complex. On contrary, the definition of business role is much easier and may be performed by business users.

Differences in user interface between application and business roles::
Business role definition uses different - easier - user interface.

Role assignments::
Following role assignments may be used:

* application role -> user
* application role -> business role -> user
* application role -> business role -> organization unit -> user
+
Each type may be used based on business need. The organization using business roles or even business roles assigned to organization units is preferred over direct assignments of application roles to users.

Minimize number of levels for role structure::
To keep the environment manageable and readable it is important to keep the structure of roles flat. Ideally just 1 level where business roles contain application roles. These business roles are assigned to users directly, via organization units that the users are members.

It is important that the structure of the roles is readable to business people using midpoint - therefore, usage of metaroles that are not visible to users via GUI is not recommended.

Avoid time constrains for role definitions::
To keep environment clear and readable it is good to use time constrains only in assignments. Roles have their lifecycles. The lifecycle stages are managed by IGA personnel and adding time constrains on this level would increase complexity unnecessarily.

Role model::
Each deployment should prepared at least basic business architecture of the roles, role assignments, naming conventions and integration principles. This architecture is referenced as Role model document or `Role model`.

//Access level::
//#TODO - popisat, co znamena - ze  business popisuje uroven pristupu - Standard user, Power user, Privileged user#
// mozno nie tu, ale v deployment methodology. - alebo vsetky tieto pravidla dat do deployment methodhodology

== The Role Engineering Process

The process is designed to be lightweight and fast, but needs to be fully documented and governed by role manager. Exceptions are to be managed by IGA administrator or role manager himself.

Each role must be designed by Application engineer. Role definition is technical description how application users are integrated in the organization environment. This is something that application engineer must design during integration process. While defining the application roles, the application engineer transforms this design into IDM technology configuration.

Midpoint must help the application engineer in filling the information needed for configuring role inducements in a way and in terminology that the engineer can easily understand. Where the application engineer can't act independently, the IGA administrator must help.

=== The process

The definition of application roles requires one additional step - definition of application. Applications should be related to application inventory and the objects should be created automatically or manually by application engineer.

. Step 1: Application engineer creates application
. Step 2: Application engineer defines roles for the application

=== Application definition
Basic step is the definition of application. The application object can collect data about how the access into application is defined. Whether existing resource or manual connector.

#TODO# not clear yet, whether this information is needed in application definition or just having it in the roles is not enough.

#TODO# If needed, prepare this procedure in detail.

NOTE: if an application definition requires manual tasks, then probably additional manual resource will be needed for such definition - this will decrease speed of role design and application integration.

Next step is definition of all roles for the application.

=== Application Role definition
Definition of application role is not an easy task. It often can't be performed by one person only. Application engineer knows about the application, but may not have enough knowledge of identity management system. Here, the IDM administrator must help. So this definition is often product of cooperation of these two positions.

To offload IDM administrators, Midpoint must support application engineers with good interface for role definition.
As midpoint configuration may be very complex, the interface must abstract of midpoint terminology and structure and provide the application engineer structured data in a form that the skilled IT engineer is able to fill intuitively or after minimum of learning.

Following schematic interface for xref:iga-schemas-app-role-design.png[Application role design] provides view of what elements should be provided to application engineer for definition.

NOTE: Some operations for roles modification (e.g. massive updates) may be performed by IGA administrator using Midpoint studio.

.Role engineering process details
Details of the process are described here: xref:role-engineering-details.adoc[Role engineering process]

=== Business role definition

Definition of business role is easier, and therefore it may be managed by business personnel. At least at beginning the business roles definitions and configuration will be managed mostly by Role manager or IGA administrators based on his requests.

The process for engineering of business roles is the same as for application roles. Only difference is that business role creation may be requested by business user.
//TODO: preverit si tabulku detailov.

Schematical description of user interface for business role request is here: xref:iga-schemas-business-role-design.png[Business role design]

=== Role updates and role decommisioning

Of course role definition may be modified. The modification also needs to go through approval process. All existing assignments are updated according to the new definition only after the role modification is approved.

Recompute of users having the role will be needed.
//TODO - linka na recompute do detailov.


== Process Monitoring and Optimization

TODO
// Ako bude prebiehat manazment procesu a jeho optimalizacia.

== Troubleshooting the process

TODO
// sem popisy, ake problemy mozu nastat a ako ich riesit

== Process examples

TODO
// tuto prejst na prikladoch, ako by taky proces vyzeral, co by bolo potrebne urobit

=== Application deployment

TODO
// tuto prejst popis procesu nasadenia aplikacie - spojenie s definovanim roly a postupne vytvaranie.