= Role Engineering Use Cases
:page-nav-title: Role Engineering Use Cases
:page-display-order: 500
//:page-toc: top
//:toclevels: 3
:sectnums:
:sectnumlevels: 3


WARNING: This page is a stub, it is a work in progress.

== Role Engineering Process examples
// tuto prejst na prikladoch, ako by taky proces vyzeral, co by bolo potrebne urobit

=== Case: <Name of the case>

TODO

////
Rado, vies si predstavit nieco ako spajanie vygenerovanych ticketov ?

O co mi ide:
Predstav si situaciu, ze mame aplikacnu rolu APP1:User a v ramci roly mame nadefinovanu manualnu ulohu: Pre vytvorenie ristupu treba dat username uzivatela do grupy XY v aplikacii.  A tuto aplikaciu chceme deployovat na uvod na 100 userov.

Normalne, ako assignujeme userovi rolu, tak system vygeneruje 100 ticketov. Vsetky uplne na to iste, lisia sa len v ID usera. Avsak, casto to narabanie s ITSM ticketmi je narocne - a trva minutu (alebo aj viac).  Lebo ITSM systemy pokryvaju rozne ine oblasti v IT operations a workflow  na zatvaranie ticketov moze byt zlozitejsi.

Bezna operacia (bez IDM) by bola taka, ze ten aplikacny inzinier, ktory takto chce naplnit data, doda prevadzkovemu timu zoznam ludi, ktorych treba naplnit, pripadne si prevadzkovy tim pripravi zoznam z organizacnej struktury, a oni ho do grupy naplnia (mozno copy-paste).

U nas by to ale vyzeralo tak, ze by sme vystrelili 100 ticketov  - co strasne spomali pracu a prevadzkove timy budu mat viac prace s administraciou ticketov ako vlastnou operaciou. A samozrejme to vyrobi chybovost.

Potrebovali by sme nieco, co dokaze chvilu pozdrzat generovanie ticketov z existujucich casov, a nasledne ich spojit, ak sa tykaju rovnakej operacie nad nejakou skupinou pouzivatelov.
////

.Solution

TODO

== Application deployment

TODO
// tuto prejst popis procesu nasadenia aplikacie - spojenie s definovanim roly a postupne vytvaranie.