= Role Engineering Use Cases
:page-nav-title: Role Engineering Use Cases
:page-display-order: 500
//:page-toc: top
//:toclevels: 3
//:sectnums:
//:sectnumlevels: 3

WARNING: This page is a stub, it is a work in progress.

== Application Role Examples

Following chapter contains examples of application roles requirements.

=== Case: Application ABC - Standard User

Role name: ABC:User::
Standard user accessing the application ABC. Application ABC verifies user access via membership in AD groups.

Access requirements::
- Account in AD and membership in AD group `abc-users`.(DN: cn=abc-users,cn=app-groups, dc=organisation, dc=com). Access is assigned automatically.

Solution::
Definition of xref::./examples/role-abc-user.adoc[role ABC:User]

NOTE: User interface must somehow explain Application engineer that attribute values of User object and value of the entitlement is defined in definition of the resource.

=== Case: Application ABC - Power User

Role name: ABC:PowerUser::
User with higher privileges in application ABC. Application ABC verifies user access via membership in AD groups.

Access requirements::
- Account in AD and membership in AD group `abc-power-users`.(DN: cn=abc-power-users,cn=app-groups, dc=organisation, dc=com). Access is assigned automatically.
- Access to shared directory on one application server (hostname: apphost3) for processing the reports. This access is assigned manually by operation team IT:APP:OPERATORS

Solution::
Definition of xref::./examples/role-abc-poweruser.adoc[role ABC:PowerUser]


=== Case: Application ABC - Administrator

*Role name: ABC:Administrator*

Application administrator of application ABC. Application ABC verifies user access via membership in AD groups. Administrator also needs administrator access to application host + access to the application database.

Access requirements::
- Account in AD and membership in AD group `abc-admins`.(DN: cn=abc-admins,cn=app-groups, dc=organisation, dc=com). Access is assigned automatically.
- Administrator access to the hosts (hostnames: apphost1, apphost2, apphost3) . This access is assigned manually by operation team IT:APP:OPERATORS
- Access to database - using LDAP group `app-abc-admins` in LDAP server.

Solution::
Definition of xref::./examples/role-abc-administrator.adoc[role ABC:Administrator]

=== Case: Application DEF - End User. Zero Trust Design Example.

*Role name: DEF:EndUser*

Standard user in application DEF. The application is implemented in environment verifying identities also on network access - application is behind Next Generation Firewall (NGFW).

Access Requirements::
- Account in LDAP and membership in LDAP group def-user. Access is assigned automatically.
- Account in NGFW and adding the application DEF in user's profile in NGFW. Access is assigned automatically.

Solution::
Definition of xref::./examples/role-def-enduser.adoc[role DEF:EndUser]

=== Case: <Name of the case>

====
Priklad 4: EC - > clenstvo v aplikacnej grupe

Nazov roly:

Toto by ale bolo riesene inak - automaticke vytvaranie a nacitavanie roli z CUDu.

Automaticke vytvaranie roly -

====

=== Case: <Name of the case>

====
Priklad 5: EC -> clenstvo v DG

DG v MP je organziacna jednotka a kazda ma pridelenu jednu metarolu.
====

.Solution

TODO

=== Case: <Name of the case>

====
Example 6: Admin role requires VPN

====

.Solution

TODO


== Application deployment

// tuto prejst popis procesu nasadenia aplikacie - spojenie s definovanim roly a postupne vytvaranie.

TODO
