= Connect the HR system
:page-nav-title: Connect the HR system
:page-display-order: 110
:page-toc: top
:experimental:
:icons: font

== Connect the HR System

The first thing to do is to connect the authoritative source system to midPoint.
When you're done with this step, you're going to have the HR accounts in midPoint and can move forth with connecting a target system, such as an Active Directory.

=== Create a resource for the HR system

The HR system exports accounts to CSV files.
A CSV file can be a resource like any other.
To get users from CSV to midPoint, use the CSV connector and configure it according to the structure of the CSV export.

*Use the xref:/midpoint/reference/admin-gui/resource-wizard/create-resource-using-wizard/[guide on connecting a resource to midPoint] to help you with the configuration.*

. Create a new resource from scratch.
. Use the CSV connector.
. Set the lifecycle state to _Proposed_ until you finish the whole configuration of the resource.
. Get back here when you're done.

=== Configure the HR resource object type

The next step after connecting the CSV resource is to configure the resource object type.
In your case, each resource object represents a user account in the HR system.

*Use this guide for xref:/midpoint/reference/admin-gui/resource-wizard/object-type/[instructions on object type configuration].*

. Name the object type _HR Person_, for example.
. The type will be of the _Account_ kind, _default_ (or empty) intent, and with the _Default_ attribute set to _True_.
. Select the _Person_ archetype in the last step.
. Keep the rest of the settings to defaults.
. Get back here when you're done.

After you save your object type, you can preview the resource data to see what you're getting from the resource.

=== Filter out irrelevant HR entries

When you preview the resource objects, you may realize there are some accounts that you don't want or need to manage using midPoint.

These may be AC technicians or people who manage your office greenery.
While their work is indispensable, they simply have no IT accounts to manage.

To prevent these accounts from being imported to midPoint:

. Find a common pattern these entries have in the HR system. +
    It may be that their employee numbers start with a different digit or their employment type is different from others…

. xref:/midpoint/reference/admin-gui/resource-wizard/object-type[Go back to the object type configuration] and select the icon:circle[] *Basic attributes* tile.

. Edit the object type you've created for the accounts and xref:/midpoint/reference/admin-gui/resource-wizard/object-type#filter-resource-objects[set up a filtering query]. +
    For instance, to exclude employees whose number (`empnum`) starts with `8`: `attributes/empnum not startsWith "8"`.

. Save the object and preview the resource objects again.

. xref:/midpoint/reference/tasks/shadow-reclassification-task/[Reclassify the resource object shadows] to reflect your changes in the account list.

. The excluded accounts should no longer appear among the accounts. MidPoint is aware of them but they are no longer considered an _HR Person_ (they are of an unknown kind and intent).

Now, you're ready to proceed to the next steps before you can import your users from the HR system to midPoint.
The next steps are:

* Mapping rules
* Synchronization rules
