= Connect source system
:page-nav-title: Connect source system
:page-display-order: 100
:page-toc: top
:experimental:
:icons: font

.Goal
[TIP]
====
Now that you know what systems you need to manage, it's time to connect them to midPoint and assess the quality of the data you're dealing with.
Use this step to identify serious security risks, such as orphaned accounts.
You'll also get to know how consistent your data are across the systems.
You can use this knowledge to improve your plan based on _real_ data.
====

Let us repeat that for the purposes of this guide, we suppose you have an HR system that exports CSV files with accounts and an Active Directory system implemented using LDAP.
The HR system is considered to be an authoritative source, the AD/LDAP system is considered to be a non-authoritative target system.

Whatever your actual systems are, the concepts presented in this guide are universal and you need to adjust only the implementation details, such as your resource configuration.

.Sample data to test with
[NOTE]
====
If you firstly wish to test the scenarios described in this guide, you can use fictitious sample HR system export CSV file:

* xref:../hris-export-sample.csv[hris-export-sample.csv]

Place is to the home directory of your midPoint instance. See xref:/midpoint/quickstart/#file-paths-in-docker-containers[how to work with file paths in Docker].

Obviously, the caveat of having a static CSV file to test with is that when you want to imitate a change in the HR system, you need to edit the CSV file manually.
====

== Considerations before you connect the source system

In theory, you should give the data in your _source_ HR system absolute authority and use it to fix any inconsistencies in other _target_ systems, such as an Active Directory or other resources.

Reality isn't so straightforward, though.

* Firstly, there are almost certainly errors in the HR data.
    They're managed manually with no automatic validation.
    Having nothing to compare the data with makes it impossible to assess their quality.

* Secondly, target systems like Active Directory are managed by different people and also manually.
    There may be outdated information, such as old names of people who changed their names.
    More serious issues like orphaned accounts of former employees can occur.
    These issues are fairly easy to fix through synchronization with the HR resource, though.

* Thirdly, not all Active Directory accounts need to exist in the HR system.
    Your AD admins may have created some service accounts.
    These aren’t employees and therefore aren't in the HR system.
    That means an HR-based synchronization without proper planning would delete these potentially business-critical accounts.

Overall, when integrating an IGA solution on top of existing account data, *you need to be vigilant*:

* You can't change *usernames* carelessly.
  Many systems in your organization may use them as the primary ID of accounts.

* You mustn't delete any *accounts* unless you're absolutely sure it's the desired action.

* You have to keep *passwords* as they are.
  Otherwise, you'd lock people out of the systems across your organization.