= Connect source system
:page-nav-title: Connect source system
:page-display-order: 100
:page-toc: top
:experimental:
:icons: font

.Goal
[TIP]
====
Now that you know what systems you need to manage, it's time to connect them to midPoint and assess the quality of the data you're dealing with.
Use this step to identify serious security risks, such as orphaned accounts.
You'll also get to know how consistent your data are across the systems.
You can use this knowledge to improve your plan based on _real_ data.
====

Let us repeat that for the purposes of this guide, we suppose you have an HR system that exports CSV files with accounts and an Active Directory system implemented using LDAP.
The HR system is considered to be an authoritative source, the AD/LDAP system is considered to be a non-authoritative target system.

Whatever your actual systems are, the concepts presented in this guide are universal and you need to adjust only the implementation details, such as your resource configuration.


.Sample data to test with
[TIP]
====
If you do not have suitable systems to use as a playground, you can follow this guide using the docker images of midPoint, HRIS, and LDAP systems configured for the MID-301 First steps training.
The MID-301 First steps training is free of charge.
Head over to link:https://evolveum.com/training-and-certification/midpoint-deployment-first-steps-self-paced/[MidPoint Deployment: First Steps - Self-Paced Training] to gain access.
Once logged into the Partner Portal, search for MidPoint Deployment: First Steps Training (MID-301).

You can go through the training to gain the same skill set as by following this guide.
The choice depends mostly on your preference of form (textual guide vs. video training).

When using concrete configuration examples, *this guide uses attribute naming based on the data in the MID-301 training data*.
====

== Considerations before you connect the source system

In theory, you should give the data in your _source_ HR system absolute authority and use it to fix any inconsistencies in other _target_ systems, such as an Active Directory or other resources.

Reality isn't so straightforward, though.

* Firstly, there are almost certainly errors in the HR data.
    They're managed manually with no automatic validation.
    Having nothing to compare the data with makes it impossible to assess their quality.

* Secondly, target systems like Active Directory are managed by different people and also manually.
    There may be outdated information, such as old names of people who changed their names.
    More serious issues like orphaned accounts of former employees can occur.
    These issues are fairly easy to fix through synchronization with the HR resource, though.

* Thirdly, not all Active Directory accounts need to exist in the HR system.
    Your AD admins may have created some service accounts.
    These aren’t employees and therefore aren't in the HR system.
    That means an HR-based synchronization without proper planning would delete these potentially business-critical accounts.

Overall, when integrating an IGA solution on top of existing account data, *you need to be vigilant*:

* You can't change *usernames* carelessly.
  Many systems in your organization may use them as the primary ID of accounts.

* You mustn't delete any *accounts* unless you're absolutely sure it's the desired action.

* You have to keep *passwords* as they are.
  Otherwise, you'd lock people out of the systems across your organization.