= Building .Net Connectors and Connector Framework
:page-wiki-name: Building .Net Connectors and Connector Framework
:page-obsolete: true
:page-upkeep-status: green

[TIP]
====
Information provided on this page was tested on Windows 7 SP1 machine, but it should work on any reasonably recent Windows platform.
====


== Download and install required software

Required software:

link:http://www.microsoft.com/en-us/download/default.aspx[Microsoft download center]

link:https://msdn.microsoft.com/en-US/windows/desktop/hh852363.aspx[https://msdn.microsoft.com/en-US/windows/desktop/hh852363.aspx]



. MSBuild Community Tasks - from link:https://github.com/loresoft/msbuildtasks[https://github.com/loresoft/msbuildtasks]. Tested versions 1.4.0.56 and 1.4.0.88.

. NUnit - from link:http://www.nunit.org/index.php?p=download[http://www.nunit.org/index.php?p=download]. Tested versions 2.6.2 and 2.6.4.

. Windows Installer XML (WiX) toolset - from link:http://wixtoolset.org/[http://wixtoolset.org/]. Tested versions 3.7.1224.0 and 3.9 R2 (3.9.1208.0).

Optional software:

. A development tool (either link:https://www.visualstudio.com/[Visual Studio] or link:http://sourceforge.net/projects/sharpdevelop/[SharpDevelop])


== Set environment variables

Set the following variables - either via .BAT file or directly in the Control Panel.
Of course, use appropriate paths to WiX, NUnit and .Net framework.

[source]
----
set WIX_HOME=C:\Program Files (x86)\WiX Toolset v3.9
set NUNIT_HOME=C:\Program Files (x86)\NUnit 2.6.4
set Path=%Path%;c:\Windows\Microsoft.NET\Framework\v4.0.30319\;%WIX_HOME%\bin

----


== Get and build the framework (ConnId)

Getting the framework:

[source]
----
C:\midpoint\git> git clone https://github.com/Evolveum/ConnId.git

----

...and compiling it:

[source]
----
C:\midpoint\git\ConnId\dotnet> msbuild ConnectorFramework.sln /p:Configuration=Release /p:ZipRelease=true

----

There are some compilation & NUnit warnings, but overall the build finishes with no hard errors.

As a result, in *c:\midpoint\git\ConnId\framework-{version}\ServiceInstall\bin\Release* directory there are *openicf-{version}-dotnet.{zip|msi}* files ready to be installed. +
 Also, in *c:\midpoint\git\ConnId\framework-{version}\Dist* there are yet another relevant .zip files.


== Get and building AD/Exchange connectors



According to link:http://openicf.forgerock.org/development.html#Developing_.NET_Connector_Bundles[the manual], I've created a directory c:\build\icf, holding content of the following zip files:

* Boo.ScriptExecutorFactory-1.1.1.6295.zip

* ConnectorServer-1.1.1.6295.zip

* FrameworkTests-1.1.1.6295.zip

* PowerShell.ScriptExecutorFactory-1.1.1.6295.zip

originally found in c:\build\framework-1.1.1.0\Dist.

(Then I do the same for framework-snapshot -> c:\build\icf-snapshot.)

Then

[source]
----
C:\build> set OPENICF_HOME=c:\build\icf
C:\build> svn checkout https://svn.forgerock.org/openicf/tags/openicf-dotnet-connectors-1.0.0.0/ connectors-1.0.0.0

or

C:\build> set OPENICF_HOME=c:\build\icf-snapshot
C:\build> svn checkout https://svn.forgerock.org/openicf/trunk/connectors/dotnet/ connectors-snapshot

----

...and compiling it (either snapshot or stable version)

[source]
----
C:\build\connectors-1.0.0.0> c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe DotNetConnectors.sln /p:Configuration=Release /p:ZipRelease=true

----

Again, there are some warnings, but overall the build finishes with no hard errors.

I do not wholly understand the version numbering scheme (framework vs.
connectors - 1.1.1.0 vs.
1.0.0.0).
Note: Connectors in last stable version (1.0.0.0) seem not to be different from the snapshot.



Original source: link:http://openicf.forgerock.org/development.html[http://openicf.forgerock.org/development.html]

