= Releasing the Eclipse plugin
:page-wiki-name: Releasing the Eclipse plugin
:page-wiki-id: 24086109
:page-wiki-metadata-create-user: mederly
:page-wiki-metadata-create-date: 2017-05-17T09:55:57.805+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2020-09-25T14:29:57.155+02:00
:page-obsolete: true
:page-upkeep-status: green

[WARNING]
.ABANDONED
====
MidPoint plugin for Eclipse for *abandoned*  in favor of xref:/midpoint/studio/[MidPoint Studio], which is based on open source link:https://www.jetbrains.com/opensource/idea/[IntelliJ platform].

Although the Eclipse plugin was an efficient tool used broadly by the community, maintaining the plugin in Eclipse environment proved to be a challenge.
Most of the midPoint developers migrated to link:https://www.jetbrains.com/opensource/idea/[IntelliJ platform], and the popularity of the platform was also indicated by our wiki:MidPoint+2019+Survey+Results[survey]. Therefore we have decided to abandon the old and de facto derelict Eclipse plugin.
There no plans to maintain the Eclipse plugin any further.
You can go ahead and use it if it works for you, but there will be no further improvements, bug fixes or even security fixes.
====

. Replace any occurrences of old version (e.g. 0.10.3) with the new one (e.g. 0.10.4).
The easiest way is to search for the string over the whole workspace (except for "target" directories).

. Do mvn clean install.

. Copy the file `com.evolveum.midpoint.eclipse.parent\com.evolveum.midpoint.eclipse.update\target\com.evolveum.midpoint.eclipse.update-x.x.x-SNAPSHOT.zip` into the `/var/www/evolveum/downloads/midpoint-eclipse-plugin` directory on the distribution server.

. Delete all the other files from the directory (perhaps except older .zip distribution files).

. Unzip the file:

[source]
----
/var/www/evolveum/downloads/midpoint-eclipse-plugin# unzip com.evolveum.midpoint.eclipse.update-0.10.4-SNAPSHOT.zip
Archive:  com.evolveum.midpoint.eclipse.update-0.10.4-SNAPSHOT.zip
   creating: features/
   creating: plugins/
  inflating: artifacts.jar
  inflating: artifacts.xml.xz
  inflating: content.jar
  inflating: content.xml.xz
  inflating: features/com.evolveum.midpoint.eclipse.feature_0.10.4.201705170733.jar
  inflating: p2.index
  inflating: plugins/com.evolveum.midpoint.eclipse.logviewer_0.10.4.201705170733.jar
  inflating: plugins/com.evolveum.midpoint.eclipse.runtime_0.10.4.201705170733.jar
  inflating: plugins/com.evolveum.midpoint.eclipse.ui_0.10.4.201705170733.jar
----