---
layout: personal
job-title: Software Architect
photo: semancik.jpg
academic-titles: Ing (MSc), PhD.
profile-github: semancik
profile-twitter: rsemancik
profile-linkedin-url: https://www.linkedin.com/in/semancik/
evolveum-blog: https://evolveum.com/author/radovan-semancik_semancik/
gpg-public-key: semancik-gpg-public.key
links:
  - title: "ORCiD 0000-0002-4903-1436"
    url: https://orcid.org/0000-0002-4903-1436
---

= Radovan Semančík

== Short Bio

He graduated from the Slovak Technical University with a master degree in Software Engineering and PhD degree.
He works as a software architect at Evolveum, and he is also one of the founders of the company.
His main areas of interest are digital identity and software architecture.
He was involved in deployment of enterprise identity management solutions since early 2000s.
He is an open-source project contributor and participates in several software development projects.
He dedicates most of his time to guide the midPoint project - the most comprehensive open source identity management and governance system currently available.
He is Apache Foundation committer and project management committee member.

== Education

* Inžinier (Ing., master) degree from https://www.stuba.sk/[Slovak University of Technology]
* Philosophiae Doctor (PhD.) degree from https://www.stuba.sk/[Slovak University of Technology]

== Publications and Talks (selection)

link:/book/[Practical Identity Management with MidPoint] (book)::
since 2016, continuously updated

xref:/midpoint/projects/midprivacy/phases/01-data-provenance-prototype/identity-metadata-in-a-nutshell/[Identity Metadata In A Nutshell]::
2020, supporting document for xref:/midpoint/midprivacy/[midPrivacy] initiative.

https://fosdem.org/2018/schedule/event/idm_midpoint/[Identity Governance and Data Protection with midPoint]::
Presentation at FOSDEM 2018, Brussels (with Katarina Valiliková)

link:/talks/files/2015-11-ldapcon-complete-open-source-iam-solution.pdf[Complete Open Source IAM Solution]::
Presentation at LDAPcon 2015, Edinburgh (with Katarina Valiliková)

link:2008-semancik-dissertation.pdf[Revised World Wide Web Architecture]::
2008, dissertation

link:2007-semancik-basic-properties-of-persona-model.pdf[Basic Properties of the Persona Model]::
2007, Computing and Informatics, Vol. 26, 2007, pp. 105-121.

https://dracones.ideosystem.com/work/papers/2006-infosecon-semancik.pdf[Choosing the Best Identity Management Technology for your Business]::
InfoSeCon 2006 Conference, Dubrovnik, Croatia

== Project Participation (selection)

xref:/midpoint/[MidPoint]::
since 2011, software architect, developer, maintainer and project co-founder

https://github.com/Evolveum/connector-ldap[MidPoint/ConnId LDAP Connector]::
since 2015, developer, maintainer and project co-founder

http://connid.tirasa.net/[ConnId]::
since 2013, major contributor

https://directory.apache.org/api/[Apache Directory API]::
since 2015, committer and project management committee (PMC) member

https://github.com/Evolveum/slapdconf[slapdconf]::
since 2014, developer and maintainer

OpenIDM version 1 (project discontinued)::
2010-2011, developer and architect

OpenICF (project discontinued)::
2011-2014, contributor
