= CSVfile
:page-wiki-name: CSVfile
:page-wiki-id: 3145738
:page-wiki-metadata-create-user: vix
:page-wiki-metadata-create-date: 2011-09-23T15:52:39.707+02:00
:page-wiki-metadata-modify-user: ifarinic
:page-wiki-metadata-modify-date: 2013-10-01T19:23:22.114+02:00
:page-obsolete: true
:page-replaced-by: /connectors/connectors/com.evolveum.polygon.connector.csv.CsvConnector/
:page-toc: top

== Status

Provisioning and synchronization works well.


== Description

The connector can be used for any separated value file (e.g. CSV).
The following steps describe setup for comma-separated value file.

Synchronization checks the last modification timestamp of CSV file.


== Resource Configuration


=== Example File Definition

The CSV file with a header line needs to be created.
The following example is available in `samples/resources/csvfile/midpoint-flatfile.csv`.

.SQL Simple Table Definition
----
"id","firstname","lastname","disabled","password"
----

Sample resource can be imported from `samples/resources/csvfile` directory.


== Recommended Connector

*Framework:* ICF +
*Bundle:* org.forgerock.openicf.connectors.file.csvfile +
*Version:* 1.1.0.0-SNAPSHOT +
*Connector:* org.forgerock.openicf.csvfile.CSVFileConnector



=== Connector Configuration Example

[source,xml]
----
        <connectorConfiguration>

            <!-- Configuration specific for the CSVfile connector -->
                <icfc:configurationProperties
                xmlns:icfccsvfile="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/org.forgerock.openicf.connectors.csvfile-connector/org.forgerock.openicf.csvfile.CSVFileConnector">

                                <icfccsvfile:filePath>/var/tmp/midpoint-flatfile.csv</icfccsvfile:filePath>
                                <icfccsvfile:encoding>utf-8</icfccsvfile:encoding>
                                <icfccsvfile:valueQualifier>"</icfccsvfile:valueQualifier>
                                <icfccsvfile:fieldDelimiter>,</icfccsvfile:fieldDelimiter>
                                <icfccsvfile:multivalueDelimiter>;</icfccsvfile:multivalueDelimiter>
                                <icfccsvfile:usingMultivalue>false</icfccsvfile:usingMultivalue>
                                <icfccsvfile:uniqueAttribute>id</icfccsvfile:uniqueAttribute>
        <!--                    <icfccsvfile:nameAttribute>id</icfccsvfile:nameAttribute> -->
                                <icfccsvfile:passwordAttribute>password</icfccsvfile:passwordAttribute>
                        </icfc:configurationProperties>
                        <!-- Generic ICF configuration -->
        </connectorConfiguration>

----
