= Exchange with .NET Connector
:page-wiki-name: Exchange
:page-wiki-id: 13991976
:page-wiki-metadata-create-user: mederly
:page-wiki-metadata-create-date: 2014-02-20T09:54:43.197+01:00
:page-wiki-metadata-modify-user: mederly
:page-wiki-metadata-modify-date: 2014-06-01T01:14:24.325+02:00
:page-obsolete: true
:page-toc: top

== Status

Provisioning works well. +
 Synchronization is implemented but not tested yet.


== Description

The connector can be used for provisioning to Active Directory and Exchange.
.NET Connector Server with Exchange connector must be installed in AD domain.
Connector host must be configured on midPoint host.

Because Exchange connector provides a superset of Active Directory connector functionality, and is strongly related to it, please *read xref:/connectors/resources/active-directory/[Active Directory resource section] first*. Here we provide only the information specific to Exchange connector.


== Recommended Connector

*Framework:* ICF +
*Bundle:* Exchange.Connector +
*Version:* 1.4.0.20165 +
*Connector:* Org.IdentityConnectors.Exchange.ExchangeConnector

Connector must be installed on .NET Connector Server machine.
Just unzip the connector archive into the .NET Connector Server directory and restart Connector Server service.


== Resource Configuration Example

[source,xml]
----
<connectorConfiguration>
  <icfc:configurationProperties
   xmlns:icfcex="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/Exchange.Connector/Org.IdentityConnectors.Exchange.ExchangeConnector">
    <icfcex:DirectoryAdminName>idmadmin</icfcex:DirectoryAdminName>
    <icfcex:DirectoryAdminPassword><clearValue>secret</clearValue></icfcex:DirectoryAdminPassword>
    <icfcex:ObjectClass>User</icfcex:ObjectClass>
    <icfcex:Container>cn=Users,dc=example,dc=com</icfcex:Container>
    <icfcex:CreateHomeDirectory>true</icfcex:CreateHomeDirectory>
    <icfcex:LDAPHostName>localhost</icfcex:LDAPHostName>
    <icfcex:SearchChildDomains>false</icfcex:SearchChildDomains>
    <icfcex:DomainName>example.com</icfcex:DomainName>
    <icfcex:ExchangeUri>http://exsrv1.example.com/PowerShell/</icfcex:ExchangeUri>
  </icfc:configurationProperties>
</connectorConfiguration>

----


=== Resource Sample

TODO