= MySQLUser
:page-wiki-name: MySQLUser
:page-wiki-id: 5341288
:page-wiki-metadata-create-user: vix
:page-wiki-metadata-create-date: 2012-08-27T12:45:58.303+02:00
:page-wiki-metadata-modify-user: ifarinic
:page-wiki-metadata-modify-date: 2013-10-01T19:27:52.685+02:00
:page-obsolete: true
:page-toc: top


== Status

Provisioning works well. +
 Activation (disable/enable) is not supported. +
 Synchronization is not supported.


== Description

The connector can be used to manage MySQL accounts.


== Resource Configuration


=== Accounts

Two accounts must be created in MySQL database: an administrative account for provisioning and a sample "prototype" account, which privileges are copied for all newly created accounts.

Consider the following example:

.SQL Import File "init-mysql.sql"
----
-- If you encounter problems, you can set query logging on:

-- mysql -u root -p

-- set global general_log_file = '/var/tmp/mysql.log';

-- set global general_log = 1;

-- Do not forget to reset the logging after tests!!! by using

-- set global general_log = 0;

-- Administrative user for midPoint

CREATE USER 'midpointadmin'@'%' IDENTIFIED BY 'secret';

CREATE USER 'midpointadmin'@'localhost' IDENTIFIED BY 'secret';

GRANT ALL on *.* TO 'midpointadmin'@'%' WITH GRANT OPTION;

GRANT ALL on *.* TO 'midpointadmin'@'localhost' WITH GRANT OPTION;

-- Sample prototype user used as User Model in connector

-- This sample user has global SELECT privilege

CREATE USER 'prototypeuser'@'%' IDENTIFIED BY 'secret';

GRANT SELECT on *.* TO 'prototypeuser'@'%';
----

The above example defines the "midpointadmin" account with superuser privileges and the "prototypeuser" account with a global SELECT privilege.
You are encouraged to customize the example for your needs.

Import the above example with:

.Importing SQL Import File
----
mysql -u root -p < samples/mysqluser/init-mysql.sql
----

Sample resource can be imported from `samples/resources/mysqluser`.


== Recommended Connector

*Framework:* ICF +
*Bundle:* org.forgerock.openicf.connectors.db.mysqluser +
*Version:* 1.1.0.0.6162 +
*Connector:* org.identityconnectors.mysqluser.MySQLUserConnector

=== Connector Configuration Example

[source,xml]
----
<connectorConfiguration
  xmlns:icfi="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/bundle/org.forgerock.openicf.connectors.db.mysqluser/org.identityconnectors.mysqluser.MySQLUserConnector"
                       xmlns:icfc="http://midpoint.evolveum.com/xml/ns/public/connector/icf-1/connector-schema-2">

    <icfc:configurationProperties>
        <icfi:driver>com.mysql.jdbc.Driver</icfi:driver>
        <icfi:port>3306</icfi:port>
        <icfi:host>localhost</icfi:host>
        <icfi:user>midpointadmin</icfi:user>
        <icfi:password><clearValue>secret</clearValue></icfi:password>
        <icfi:usermodel>prototypeuser</icfi:usermodel>
    </icfc:configurationProperties>
</connectorConfiguration>

----
