---
layout: personal
job-title: Senior DevOps Engineer
photo: Abaffy.jpg
academic-titles: Ing (MSc)
---

= Michal Abaffy

== Short Bio

Visionary and results-driven software engineer with over 20 years of experience in software engineering, team leadership, and agile product ownership. A long-term enthusiast of artificial intelligence, machine learning, and neural networks, with a proven track record of delivering cutting-edge software solutions that drive business growth and exceed user expectations. Adept at fostering a culture of innovation, leading cross-functional, international teams to push boundaries and achieve project objectives. Excels at creating a collaborative work environment that encourages experimentation, creativity, and continuous learning, while mentoring junior developers to reach their full potential. Passionate about harnessing the power of technology to solve complex problems, improve user experiences, and drive meaningful innovation. A lifelong learner, always seeking out new technologies and methodologies to stay ahead of the curve and drive innovation in the field of AI and machine learning.

== Education

* Master degree (Ing., MSc) from https://uniza.sk/index.php/en/[University of Zilina]

== Publications and Talks (selection)

Transforming Vision into Value::
Presentation at POPInfo 2015, Martin

Issues in teaching programming::
Presentation at POPInfo 2010, Martin

Modelling and simulation of technological processes::
Disertation thesis

== Project Participation (selection)

MidPoint Chatbot::
since 2024, support chatbot developer; Python, LangChain, LangGraph, Streamlit, LitServe

AI chess engine::
neural network governed Monte Carlo search; Cython, PyTorch, Reinforcement learning

AI Mario player::
Students` Professional Activities contest; Python, PyTorch, Stable Baselines, Reinforcement learning

AI Bugtrack::
AI advisor to search for places in the source code that could be affected by the reported bug; Python, C, Self organizing neural network map
