= Community Guidelines
:page-wiki-name: Community Guidelines
:page-wiki-id: 23167156
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2016-08-22T16:41:12.047+02:00
:page-wiki-metadata-modify-user: mederly
:page-wiki-metadata-modify-date: 2020-01-28T18:09:13.244+01:00

MidPoint project has good and vibrant community of users, engineers and developers.
This community has naturally evolved from midPoint early adopters.
Now there are community members with considerably varied skill sets: from novices to masters.
One important thing about midPoint community is that everybody is welcomed.
MidPoint project is xref:/midpoint/introduction/openness/[100% open] and we believe that this is the best way how to develop quality software such as midPoint.


== Mailing List

The primary tool for community communication is xref:mailing-lists.adoc[midPoint mailing list]. Most community members are subscribed there.
Including all the midPoint core developers.
This is the place to post your questions, ideas and suggestions.
However please stick to the link:https://tools.ietf.org/html/rfc1855[netiquette] and good engineering practices when communicating on the mailing list.
This mostly means:

. *Be polite.* Mailing list is a best effort service.
Nobody is (directly) paid to answer mailing list questions.
The engineers that answer the questions are doing that in addition to their day-to-day responsibilities and they are doing that because they want to help the community.
Therefore if you are asking for help, do so politely.
If you are answering a question please respect other members.
Everybody started somewhere and it is natural that novice users do not know everything.
Please tolerate the differences in skill sets.

. *Do some research before asking a question.* Do not ask trivial question that can be easily answered by googling the question, by searching for it in the midPoint wiki or mailing list archive.
If you are getting an error try to read error message very carefully and try to think about the possible causes.
Try to experiment with the configuration a bit.
Look at wiki:Troubleshooting[troubleshooting] section of this wiki.
Spend at least a couple of minutes to make your own research before asking the question.
If that research does not provide the answer then it is a good question for the mailing list.

. *Provide context.* If your post looks like _"my midpoint is broken, please help"_ then it is very unlikely that you will get any answers.
Try to describe your problem in more details.
Make sure to describe relevant bits of your configuration.
Be sure to include error message.
Look in the log files if necessary.
And most importantly: describe what are you trying to achieve.
Maybe the root of your problem is that you are using completely wrong approach.
The community may point your nose in the right direction - but only if they know what is your goal.

. *Give back.* Mailing list is not one way communication channel where users ask questions and developers answer them.
There is already a significant body of knowledge distributed among community members that are not midPoint developers.
If you adhere to these guidelines and ask a question it will most likely be answered.
But for that there needs to be someone who is answering.
Therefore do not just ask the questions.
If you know the answer for the question that someone else asks then please go ahead and answer it.
Do not worry that your answer may not be perfect.
Even a partial answer will be greatly appreciated by any novice user.
Simply speaking: Do not only take from the community.
Try to repay what the community gave you.


== Private Communication

It is very tempting to try to communicate with midPoint developers directly.
However the developers have many midPoint users, partners, customers and contributors to deal with in their day-to-day job.
The first responsibility of any midPoint core developer is to make sure that midPoint development will continue.
The developers naturally prefer to spend time doing tasks that bring funding to the midPoint project.
Therefore the developers will strictly prioritize the communication.
And the priorities are:

* Communication with *platform subscribers* have the highest priority.
This keeps our bills paid and the midPoint project going.

* Communication with customers that have purchased *product support services* is second.
This communication is strictly *limited* to communication about bugs and bug reports.
Configuration issues, installation issues, information about features and documentation are out of scope of midPoint support service.
Those will be considered to be _community__communication_ (if mailing list is used) or _other private communication_.

* *Contributors* to midPoint project are third.
If you have work ready to contribute to the project or if you need to consult your contribution then the developers will listen to you.

* *Community* communication channels go next.
Mailing list is essentially a multicast communication.
Answer to mailing list question will reach many receivers and therefore the knowledge will spread quite efficiently.

* *Other private communication* is the lowest priority.
Absolutely at the very bottom of the priority queue.
Private communication does not scale.
It is not an efficient way how to distribute the knowledge.
Therefore midPoint developers will act accordingly.
We will need to do all the development work, answer all the community questions and only then we handle private communication (if there is any time left).
Therefore be prepared to wait for days or even weeks for the answer.
And it may happen that your mail will just get lost in the flood of other mails that we are getting every day.
While we have processes to make sure that all subscriber and community requests are handled, there is no such process for private communication.
Therefore do not get angry if we do not answer.
We are not rude and we are not ignoring you.
There is just so much work to do on midPoint.
Therefore use this channel at your own risk.
Honestly, you will probably get much faster response if you use the mailing list.


== See Also

* xref:mailing-lists.adoc[Mailing Lists]

* wiki:Troubleshooting[Troubleshooting]