= Dual licensing
:page-wiki-name: Dual Licensing
:page-wiki-id: 27361612
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2019-01-21T17:51:19.810+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2020-09-22T09:22:06.368+02:00
:page-toc: top
:page-description: This article explains dual licensing of midPoint versions 4.0-4.9. It does not apply to midPoint 4.10 and newer.
:page-keywords: dual licence, dual licensing, eupl, apache, public code, funding, open source

MidPoint versions from 4.0 to 4.9 are dual-licensed under the terms of the Apache License 2.0 and the European Union Public License 1.2 or later (EUPL).
This page explains the details and motivation.

Information on *this page does not apply to midPoint 4.10* and newer.

== Introduction

Open source is a great way to make great software.
And we in Evolveum strongly believe that it is also the right way to make software.
We have link:https://evolveum.com/blog/open-source-forever/[declared that in the past] and we still stand true to our word.
MidPoint is open source and it will be open source as long as we have something to say about it.

However, open source funding is a big problem.
A problem that does not have any easy solution.
Various companies are experimenting with methods to fund open source projects.
And some of them are making decisions that are putting the whole concept of open source in danger.
We do not want to go that way.
We do not want to compromise.
MidPoint must remain completely open to any kind of usage.
Which constraints our choices when it comes to Evolveum business model.
All _open core_ and similar approaches are ruled out.
Evolveum has a good business model based on support, subscription and other services around midPoint product.
This business model works in many environments such as enterprise or academia.
However, it does not work very well when public money are directly involved.

== European Union

There are great initiatives such as link:https://publiccode.eu/[Public Money, Public Code]. However, those ideas as not yet universally adopted.
And even those initiatives alone will not provide funding to open source projects.
But all is not lost.
Evolveum is a European company.
And the European Union runs several programs to support open source projects.
For example, there is the link:https://joinup.ec.europa.eu/collection/eu-fossa-2[Free and Open Source Software Audit (FOSSA)] program focused on improving security of open source software.
Even though those programs are very useful, they provide funding for open source testing.
There is no funding for open source maintenance.
Simply speaking, FOSSA will pay for discovery of a bug, but they will not pay for the fix.
But there are other programs and there is a chance to get funding even for the maintenance.
However, there are some limitations for projects to be eligible.
The European Union has created its own license for open source software: link:https://opensource.org/licenses/EUPL-1.2[European Union Public License (EUPL)]. We believe that we can significantly increase our chances to get EU funding if we play by the EU rules.
Simply speaking, we think that if midPoint is licensed under the EUPL we would be able to secure funding that will cover at least some parts of midPoint maintenance.


== Apache

On the other hand, we are completely happy with the Apache License and we do not want to forfeit the liberties that the Apache License provides.
We like the liberty of a software used by anyone for any purpose.
We do not want to forfeit that liberty.
We do not like the idea of software use being limited, not even by a copyleft open source license.
We want to stick with the Apache License.


== Dual licensing

Therefore, we have decided to use dual licensing approach: midPoint (versions 4.0-4.9) is provided under both the Apache License and the EUPL at the same time.
The users may choose the license that suits their needs.
This is almost an ideal approach to have the best of both worlds.

MidPoint versions from 4.0 to 4.9 are released under two licenses:

* Apache License 2.0

* European Union Public License (EUPL) 1.2

Users of midPoint can choose any of those licenses to use midPoint.

== Contributions

Dual licensing may seem like an ideal approach, but there is a catch.
If midPoint were licensed under just one license, the situation would be quite clear.
It would be clear that users are using midPoint under that license.
But even more importantly, it would be clear that contributions are provided under that license as well.
That is why no extra paperwork was necessary to accept contributions to midPoint.

The situation is much more complicated when there are two licenses.
Users may choose any of the two licenses, so we need contributions to be licensed under the two licenses as well.
Therefore, more paperwork is needed for midPoint contributions.

The dual licensing approach forces us to apply the _Contributor License Agreement_ (CLA) to all midPoint contributions.
This agreement gives us the right to publish (re-license) the contributions under the terms of both licenses.

We cannot accept a contribution without the CLA,
even though it means additional paperwork for both us and the contributors.
We are really sorry about that,
but it is a necessary evil to make the midPoint project thrive.

If you contribute as an employee of a company, the CLA needs to be signed by your employer.


== Translations, samples, and more

We can live with CLAs for contributors to the core midPoint code.
MidPoint is quite a comprehensive project.
There is lot of code and the code can be quite complex.
Understanding the code is no simple feat.
Therefore, contributing to the midPoint core has quite a high entry barrier already.
Code contribution is a process with significant overhead, as each code contribution has to be reviewed.
Applying CLAs to code contributions is painful, but it is something that we can live with.

But the situation is quite different for translations, samples, and other parts of midPoint that are more or less supplemental.
We do not want to put a high entry barrier for those.
We consider it essential that the community contribution to those parts of midPoint is as easy as possible.
Therefore, translations and samples are in separate projects.
Those projects are single-licensed under the terms of the Apache License
and *no CLA is necessary to contribute to translations and samples.*

Similarly, connectors remain single-licensed, usually under the Apache License.
See the `LICENSE` file in their particular repo to make sure.

== See also

* xref:development/code-contribution-guidelines.adoc[]

* xref:/copyright/[Copyright and Licensing Guidelines]