= Feedback
:page-wiki-name: Feedback
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2011-04-29T14:40:37.051+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2011-05-10T09:55:21.963+02:00

We appreciate any kind of feedback regarding the software, development process or overall way of interaction with the community.
There are two primary ways how to contact us regarding midPoint:


== midPoint Mailing List

The mailing list is focused on informal, unstructured communication.
This is a good place to ask generic questions and suggest improvements.
The team will also post more or less regular updates regarding midPoint development and ask for opinions.
Therefore the mailing list is a good place to be if you are interested in following midPoint development and influencing its direction.

* link:http://lists.evolveum.com/mailman/listinfo/midpoint[midPoint mailing list web interface] (subscribe/unsubscribe here)

* link:http://lists.evolveum.com/pipermail/midpoint/[midPoint mailing list archives]

See also all other midPoint wiki:Mailing+Lists[Mailing Lists]


== midPoint Jira

We use link:http://jira.evolveum.com/browse/MID[Jira] as an universal issues tracking system.
All bug reports should be filed in Jira, so we will not forget about them.
Similarly for feature requests or any other structured communication.

The important thing is to keep information in Jira structured.
It means that following items should go to Jira:

* *Bug reports* with a good description of the problem, ideally also including some basic diagnostics, log files or at least a description how to replicate the problem.

* *Feature requests* and improvement ideas that are quite mature.
The ideas should be well described, feasible and practical.
If you are not sure about a specific idea, it is better to discuss it on a mailing list first.

* *Documentation issues* - reports of outdated documentation, missing documentation, parts that are not understandable and require clarification, etc.
We would greatly appreciate not only pointing out what's wrong, but also suggest what to add or how to improve existing texts.

Any link:https://jira.evolveum.com/secure/Signup!default.jspa[registered] user can submit issues to Jira.

Unstructured communication, general discussion or vague ideas should first be discussed in mailing lists (see above).