= Outcomes of MidScale Milestone M1
:page-nav-title: M1

*Milestone goal:* Performance environment (part 1) +
*Status:* DONE (26 Nov 2020, on time)

== Activities and Outcomes

There were two major parallel activities during this milestone:

. Preparation of performance testing environment.
The performance environment was link:../design/infrastructure-design/[designed] (in its first iteration),
the design was guided by the link:../design/testing-design/[testing design], which in turn was influenced by link:../design/meeting-overview/[design of other solution components].
The work on preparing the performance testing environment was started and reached its first milestone.

. Design meetings and prototyping.
It was decided to link:../design/meeting-overview/[conduct a series of design meetings] ahead of the plan, to get an overview of the tasks that lie ahead of us.
This activity included a prototyping activities, especially in repository and performance areas.
The results of design meetings were summarized in link:../architecture/[solution architecture document].


== Planning Delta

The activities of this milestone were mostly carried out according to original plan.
Yet, there were some differences:

* It was decided to start design and prototyping activities earlier than it was originally planned.
As the project start date was postponed, more engineers were available to work on the project as was originally planned.
Therefore it was decided to use this to our advantage and reduce future risk by designing the solution details ahead of time.

* More people were involved in the project, outside of the NGI funding.
It was decided to strengthen the architectural part of the project (Radovan Semančík) and support for testing infrastructure (Kamil Jireš).

== Remarks

We have utilized the results of link:/midpoint/midprivacy/phases/01-data-provenance-prototype/[midPrivacy initiative] in this project, especially the link:/midpoint/axiom/[Axiom] modeling language.
This was not included in the original design of midScale, as Axiom did not exist at that time yet.

We have also considered the future of midPoint after the midScale project.
In a related effort, we have worked on a link:/midpoint/devel/design/midpoint-5-vision/[midPoint 5 vision] to make sure that outcomes of midScale project are aligned with a long-term vision for midPoint.
