= Migration from Eclipse Plugin
:page-toc: top

== Importing Eclipse Project

TODO

This is already possible since 7.10.2020.

TODO actually creating a new project with existing files (from eclipse)

Rough list of steps:

. start IntelliJ IDEA
. open directory with old Eclipse project
. press `Shift` key twice to open the IntelliJ IDEA search window
. start to type `midpoint`
. select the row *MidPoint Settings* to open midPoint project settings
. keep *Download file pattern* as is unless you know what you are doing. See also <<Updating Project Settings>>
. keep *Generated file pattern* as is unless you know what you are doing. See also <<Updating Project Settings>>
. click *Import from Eclipse* button
. set the *Master password* for your encrypted properties store (`Keepass`).
* do not set `Old password`, keep it empty
* the master password will be used for encryption of `Keepass` file. See <<Using Keepass File>>.
* the master password will be stored in your operating system key management subsystem to not ask for it each time you start IntelliJ IDEA
. Select a proper *Environment*
* by default there is a `Default` environment for `http://localhost:8080/midpoint`
* you can modify or add new environments for your projects now or later, see <<Working With Environments>>
. click *OK* button

== Limitations

* MidPoint Studio will not automatically migrate environments (as they are global in Eclipse). You have to create your environments manually including references to properties files
* MidPoint Studio will not overwrite `.gitignore` and `pom.xml` files if they existed in the imported Eclipse project

TODO default content of these files
.gitignore: https://github.com/Evolveum/midpoint-studio/blob/master/studio-idea-plugin/src/main/resources/fileTemplates/MidPoint%20Git%20Ignore.git.ft
