= MidPoint In Container
:page-nav-title: Containers
:page-display-order: 20
:page-liquid:

== Quick Start

The containers are the easiest and the fastest way how to start working with midPoint.
In case this is your the fist contact with midPoint please see the xref:../../quickstart[Quick Start] page which contain basic information useful in case of the first contact.

//TODO sync with quick start page...

== Customization of the containers

The image is prepared to be flexible in usage.
All the common settings should be possible to realize without rebuilding the image.

The way the image interact with the docker environment is mainly handled by the following files:

* /usr/local/bin/*healthcheck.sh* +
This file providing information about the health status of the midPoint application back to docker engine.
* /opt/midpoint/bin/*midpoint.sh* +
** <<mpset,*MP_SET_*>> environment variable +
This part cover the most flexible part of the possible customization of the image.

** `<<initNative,init-native>>` +
This part covert all the common needs related to the init of the environment (first run).

** `container` +
The command causing the start of the midPoint itself.
It is set up in the image as default command.
+
.bash syntax
[source,bash]
/opt/midpoint/bin/midpoint.sh container

[NOTE]
====
Bash script defining also TRAPs. +
Without this definition the TERM or KILL signal would not be passed to the midPoint application in case of shutting down of the container.
This situation would not provide application time to properly ends operation. +
With the defined TRAPs signal properly reach the midPoint application and the operations are properly finished. +
From user point of view the termination of the container doesn't need to wait 10s timeout before environment forcing to kill the container and in read the termination take just few seconds.
====
[#initNative]
=== init native

This section is focused on handling available files.
What exactly will happen is controlled by the environment variables.
There are available several environment variables.
Following logic is applied only in case the relevant environment variable is set.

* *MP_CHECK* +
Touch file (can be empty) which existence is checked during midpoint start.
Once the file exists it prevent start of application.
It the file is missing (or it is removed) the start continue as usual.
+
.example of the value
[source]
MP_CHECK=/opt/mp-home/init_in_progress

* *MP_INIT_CFG* +
Sample config.xml file required for native repository will be copied (and properly renamed) to the directory set by the value of the variable.
With this file all the rest required variable can be set using *MP_SET_* prefixed environment variables
+
.example of the value - target directory is /opt/midpoint/var (file will be /opt/midpoint/var/config.xml)
[source]
MP_INIT_CFG=/opt/midpoint/var

* *MP_DB_PW* +
The password for the database access has to be the same on the client and server side.
As far as the roles are split, the password has to be set in advance to be the same on both side of communication.
The value is the path to the file, where the generated password should be saved.
+
.example of the value - the generated password will be saved to /opt/db-pw/dbpassword
[source]
MP_DB_PW=/opt/db-pw/dbpassword

* *MP_PW_DEF* +
A default password for the keystore is "changeit".
The value for this variable says, where the default password should be saved.
+
.example of the value - the default password will be saved to /opt/mp-home/keystorepw
[source]
MP_PW_DEF=/opt/mp-home/keystorepw

* *MP_PW* +
In case you prefer to have your own generated password also for keystore, this option will interest you.
As a value the location for the file is provided.
+
.example of the value - the generated password will be saved to /opt/mp-home/keystorepw
[source]
MP_PW=/opt/mp-home/keystorepw

* *MP_CERT* +
In case a certificate has to be added to certstore the content of the variable will be processed.
The list of certs is processed iteratively so one or more certificates can be provided.
** *MP_KEYSTORE* +
This variable has to be set in order to know where the keystore is stored - where the certificate should be added.
+
.example of the value to add the cert
[source]
----
MP_CERT="-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----"
MP_KEYSTORE=/opt/mp-home/keystore.jceks
----
+
.exaple of the value to add more certs
[source]
----
MP_CERT="-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----"
MP_KEYSTORE=/opt/mp-home/keystore.jceks
----

[NOTE]
Prerequisites for the _MP_CERT_ are _MP_KEYSTORE_ & _MP_PW_ or _MP_KEYSTORE_ & _MP_PW_DEF_ - it is necessary in order to locate and access / generation of the keystore.

=== Environment variables

* *MP_MP_ENTRY_POINT*

The <<entry point, entry point>> can be used to copy some file before the system start. It is usable mainly with container approach like Docker.

* *MP_MEM_MAX*

Alias for *JAVA_OPTS* variable *-Xmx[0-9]*. It may be usefull especially in case the "simply" key=value syntax would be prefered to the complex set of values in one variable.

* *MP_MEM_INIT*

Alias for *JAVA_OPTS* variable *-Xms[0-9]*. It may be usefull especially in case the "simply" key=value syntax would be prefered to the complex set of values in one variable.

* [#mpset]*MP_SET_**

To make the passing the variable for java easier there has been set "mapping" for the environment variables starting with *MP_SET_*. The result will be *-D** parameters in *JAVA_OPTS* which is already passed to java process. The benefit is in maintaining configuration mainly for midpoint run in the containers where passing additional argument mean list all of them and not only new one. With this mapping it is easier to maintain or even generate the configuration for the container instance.

By the processing *MP_SET_* "prefix" is removed and for the rest there is replaced _ with . (dot). The is exception _FILE which is handled. The prefix *-D* is added and the final result is added to the *JAVA_OPTS* variable which is used for the starting.

[[entry-point]]
*MP_ENTRY_POINT* option is pointing to the folder in the container's filesystem, which is handled as a read only source mainly for post-initial-objects.
The content is copied to proper midpoint's structure (/opt/midpoint/var) before starting the midpoint instance with keeping the same sub folder structure.
It can be also used for any other files like csv or jar (e.g. connectors).

During the processing of the *MP_ENTRY_POINT* it checks the existence of the file or file with extension .done (processed post-initial-object is renamed with suffix .done).
Once the file in any form ("exact" name or with the .done suffix) exists, the file is skipped so any future changes on the copied version are kept without overwriting - only new files are copied.
This way the post-initial-objects can be re-used several times with the same behaviour all the time.

.example of the behaviour : MP_ENTRY_POINT=/opt/entry-point
[source]
----
/opt/entry-point
- post-initial-objects
  + user.xml
  - role.xml

/opt/midpoint/var
+ post-initial-objects
  - user.xml.done
----

* *post-initial-objects* exists so no change
* *user.xml* in the destination there exists _user.xml.done_ so no action will happen
* *role.xml* does not exist so it will be copied to */opt/midpoint/var/post-initial-objects/role.xml*

[NOTE]
====
In the theory you can mount it directly to the midpoint's structure but the resulting behaviour will be, the most probably, a little bit different than expected.
With the first run there can be two possible situations:

* the mount point will be in "writable" mode +
In that case the file will be renamed with adding suffix *._done* and respective next run (with new container) will be ignoring the files.

* the mount point will be read-only mode +
The midpoint start will fail and it will not be possible to rename the file, which is handled as critical error.
====

If *MP_ENTRY_POINT* feature is not needed the following lines can be removed:

[source]
- MP_ENTRY_POINT=/opt/midpoint-dirs-docker-entrypoint

[source]
- ./midpoint_server/container_files/mp-home:/opt/midpoint-dirs-docker-entrypoint/:ro

In case the lines are kept in the example, the directory *./midpoint_server/container_files/mp-home* should exists.
Otherwise docker-compose will create it.
As the container runs under root the newly created directory will have the permission set (UID, GID) for the root user.
To prevent this behavior prepare the directory structure in advance.

=== Volumes

Until you will attach the volume all the changes are kept only in the container which may be discarded.
The image is ready to attach the volume to midPoint home - /opt/midpoint/var.
By attaching the external store (volume) you will keep stored data from midPoint home out of container.
This way it is safe to remove the container and create new one attaching the volume (changing image version - e.g. new support branch build)

Volumes are handled in the container similar to mount points.
There may be more volumes mapped in cascade.

.midpoint structure
[source]
----
/opt/midpoint/var
+ connid-connectors
+ export
+ icf-connectors
| - connector-ssh-1.0.jar
+ idm-legacy
+ import
+ lib
| + jython-standalone-2.7.2.jar
| - ojdbc11.jar
+ log
| + midpoint.out
| - midpoint.log
+ post-initial-objects
+ schema
+ tmp
+ trace
- work
----

[NOTE]
====
* connector-ssh-1.0.jar +
** xref:/connectors/connectors/com.evolveum.polygon.connector.ssh.SshConnector/[SSH connector docs page] (internal link)

* jython-standalone-2.7.2.jar +
** xref:/midpoint/reference/support-4.8/expressions/expressions/script/python/[Python script docs page] (internal link)
** link:https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar[download] (external link)

* ojdbc11.jar
** Oracle JDBC
** link:https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html[download] (external link)
====

.local filesystem structure
[source]
----
/tmp/workdir
+ connectors
| - connector-ssh-1.0.jar
- docker-compose.yml
----

In case you want to attach the subdirectory with the connector to container the following definition should be used :

.binding directory from external filesystem to container
[source]
----
- ./connectors:/opt/midpoint/var/connid-connectors
----


[WARNING]
====
Once you will use the volume / mount point the original content will be hidden.
Based on the usage the original content can be copied but not in all the cases.
====

== Build the container

We are building the images in our link:https://jenkins.evolveum.com/view/midPoint-docker/[jenkins] infrastructure.
After basic tests (e.g. the environment can be started) the images are pushed to the public link:https://hub.docker.com/r/evolveum/midpoint[Docker hub] repository.
All the necessary resources for the docker image build are publicly available like other our resources on link:https://github.com/Evolveum/midpoint-docker[GitHub].

=== Base OSs used for the images

* Alpine
* Rocky Linux
* Ubuntu