= MidPoint In Container
:page-nav-title: Containers
:page-display-order: 20
:page-liquid:

== Quick Start

The containers are the easiest and the fastest way how to start working with midPoint.
In case this is your the fist contact with midPoint please see the xref:../../quickstart[Quick Start] page which contain basic information useful in case of the first contact.

== Container docs subtree

This subtree of the docs is focused to the container related information.
The content is split to common information used for containerized installation of the midPoint and to the information / notes related to the specific usage of the containers (e.g. docker, kubernetes).

[NOTE]
====
The usage of the container with the midPoint is not limited only to the provided examples.
In case you are using other tool implementing standardized / common features the container will also work for you (e.g. podman).

The information in this subtree of the docs are mainly for reference, or it can be used as hint how to start working with containerized midPoint.
====

The features mentioned in this subtree are available also outside the containers.
During the design the containers specific behavior has been covered.

++++
{% children %}
++++

We are building the images in our link:https://jenkins.evolveum.com/view/midPoint-docker/[jenkins] infrastructure.
After basic tests (e.g. the environment can be started) the images are pushed to the public link:https://hub.docker.com/r/evolveum/midpoint[Docker hub] repository.
All the necessary resources for the docker image build are publicly available like other our resources on link:https://github.com/Evolveum/midpoint-docker[GitHub].