= MidPoint In Container
:page-nav-title: Containers
:page-display-order: 10
:page-liquid:

== Quick start

To start midpoint there is necessary to have ready also repository (postgres required).
To fulfill this requirements there is available docker compose file which will set up all necessary for you in the containers.
If you want just simply try it out this is the recommended and the easiest way how to start.
[source,bash]
====
docker compose up
====

== Container docs subtree

This subtree of the docs is focused to the container related information.
The content is split to common information used for containerized installation of the midPoint and to the information / notes related to the specific usage of the containers (e.g. docker, kubernetes).

[NOTE]
====
The usage of the container with the midPoint is not limited only to the provided examples.
In case you are using other tool implementing standardized / common features the container will also work for you (e.g. podman).

The information in this subtree of the docs are mainly for reference, or it can be used as hint how to start working with containerized midPoint.
====

The features mentioned in this subtree are available also outside the containers.
During the design the containers specific behavior has been covered.

++++
{% children %}
++++

We are building the images in our link:https://jenkins.evolveum.com/view/midPoint-docker/[jenkins] infrastructure.
After basic tests (e.g. the environment can be started) the images are pushed to the public link:https://hub.docker.com/r/evolveum/midpoint[Docker hub] repository.
All the necessary resources for the docker image build are publicly available like other our resources on link:https://github.com/Evolveum/midpoint-docker[GitHub].