= Vanilla Kubernetes
:page-nav-title: Vanilla Kubernetes
:toc: float-right
:toclevels: 4
:page-keywords:  [ 'insatll', 'kubernetes' ]

This page is related to the midPoint in container context of documentation.
Here will be dedicated samples related to the vanilla kubernetes.

You may be interested in :

* common xref:../[container]  related information +
There is information contains possibilities of customization of the installation.

* xref:./docker/[docker] related information +
Sample configuration related to the docker environment.

[NOTE]
====
Page is under construction.
Please check the page soon for new content.
====

== Prepare to start

When we are starting the environment we have to address few steps to have successful start of application.

* <<_namespace>> (optional) +
There is native isolation concept in kubernetes to group the objects - namespaces.
Even it is not mandatory we recommend to create the namespace to keep the configuration logically grouped.

* repository +
The repository is the relational database where the midPoint's objects are stored.
At the moment of start the repository have to be available and initiated at least on structure level (tables, indexes, etc.).
The definitions for postgreSQL are delivered with the midPoint container.
Initial objects (the content) will be handled by the midPoint itself if needed.

** Init empty structure +
The midPoint can handle the content of DB.
The structure of the repository have to be prepared in advance.
It can be run explicitly one time before first run.
It can be also the part of Init container as conditional block of the code.

** update structure +
Once you have initialized repository there may be need to update the schema with version change - upgrade.
This is usually one time operation with the upgrade.
The upgrade of database schema not necessarily have to be needed with all the midPoint's release - see the xref:/midpoint/release[] page to check if needed.

* required files on filesystem
** configuration file - config.xml +
There have to be proper content of the *config.xml* to be able to start.
Some part can be set / overwritten via environment variables.
** keystore - keystore.jceks +
The keystore is generated automatically in case it is missing.
If you need any additional content (e.g. certificate to establish secured connection to resource) you have to handle explicitly.

* modPoint home
** volumes +

** access "hidden files" behind the mount points

=== Namespace

To have grouped configuration logically separated from the rest of the objects it is good approach to create the namespace.

.Example of the *mp-demo* namespace definition | link:https://raw.githubusercontent.com/Evolveum/midpoint-kubernetes/main/base-environment/namespace-mp-demo.yaml[Github]
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: mp-demo
spec:
  finalizers:
    - kubernetes
----

[WARNING]
====
Once you remove the namespace object from Kubernetes all the objects located in the namespace are also removed.
====

=== Repository



== configuration files
For the native repository there is need to have proper configuration for the db connection.
This configuration is stored in *config.xml* located in midPoint home directory.

To have it ready you have several options how to handle it.

* *configmap* mounted to the pod's filesystem
* *secret* mounted to the pod's filesystem
* *Persistent Volume Claim*
* handle it dynamically in the *initContainer*

