---
layout: personal
job-title: AI/ML Developer
photo: Bielik.jpg
academic-titles: Ing (MSc)
---

= Martin Bielik

== Short Bio

Martin is an AI/ML developer at Evolveum.

He is a SW and AI/ML developer of midPoint at Evolveum. Currently he is a part of the team responsible for the development of role mining and outlier detection in midPoint, and other future AI functionalities.

== Education

* MSc degree from https://uniba.sk/en/[Comenius university]

== Publications and Talks (selection)

Organizing and holding internal courses in Machine learning, AI and Javascript domain (since 2020)

== Project Participation (selection)

xref:/midpoint/[MidPoint]::
since 2024, role mining and outlier detection developer

https://www.kaggle.com/martinbielik/competitions[Kaggle Bronze Medal winner]::
linking writing processes to writing quality; competition by Google

https://play.google.com/store/apps/details?id=com.appleclassify&pli=1[AppleClassify]::
classifies apple varieties by using the device's camera, VertexAI, Android, Tensorflow

https://github.com/madox2/vim-ai[vim-ai]::
integration of OpenAI chat and completions into Vim editor; OpenAI API, vimscript, Python
