= Security Improvements in 4.8
:page-since: 4.8
:page-toc: top

== Authorization Configuration

Before 4.8, we could specify the authorization only at the level of an object.
For example, the logged-in principal could see particular items of a given object, depending on its relation to it.
Or, it could execute some operations on that object.

In 4.8, we need more.
First of all, we need to be able to authorize operations on the level of individual items.

. A user can see or complete case work items assigned to him.
. A user can see or complete case work items assigned to people in organizations managed by him.
. A user can see only closed (or not closed) case work items.
. A user can only see other users' assignments to the roles he is an owner or approver of.
. A user can only see other users' `roleMembershipRef` values related to the roles he is an owner of approver of.

Regarding certifications, things get even more complex:

. A user can see certification cases related to people in organizations managed by him.
. A user can see certification cases related to roles he is an owner or approver of.
. A user can see or complete certification case work items assigned to him.
. A user can see or complete certification case work items assigned to people in organizations managed by him.
. A user can see only closed (or not closed) certification case work items.

NOTE: We cannot guarantee all of the above scenarios to be implemented.
We will provide more detailed analysis here later.

//"Work items and cases, Resource templates, Tasks, Pre-authenticated for scripts"


== Changes

- The `assignee` clause now covers all assignees, not only assignees of open work items (commit https://github.com/Evolveum/midpoint/commit/c97e31dc[c97e31dc]).

== Migration of the Authorizations

Please see xref:/midpoint/devel/design/schema-cleanup-4.8/authorizations.adoc[] more details.
