---
layout: connector-page
display-order: 200
functionality-status: experimental
development-status: unknown
support-status: supportable
origin: Evolveum
support-provided-by: Evolveum
target-systems: Grouper (Internet2 et al.)
connector-protocol: REST, AMQP
source-url-master: https://github.internet2.edu/docker/midPoint-Grouper_connector
description: Identity connector for Grouper.
upkeep-status: yellow
---
= Grouper Connector
:page-wiki-name: Grouper Connector
:page-wiki-id: 34570441
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2019-07-22T16:21:28.127+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-07-22T16:34:48.377+02:00

Connector for Grouper access management system.

The goal of this connector is group membership management.

== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| Schema
| TODO
|

| Provisioning
| TODO
|

| Live Synchronization
| TODO
|

| Password
| NO
| Not needed for group membership management.

| Activation
| TODO
|

| Filtering changes
| TODO
|

| Paging support
| TODO
|

| Native attribute names
| TODO
|

|===


== History


[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | Framework version | Bundled with midPoint | Description

| 0.3
| TODO
| TODO
| link:https://github.internet2.edu/docker/midPoint-Grouper_connector[GitHub (Internet2)]
| TODO
| 1.4.2.14
| none
| TODO

|===


== Interoperability

TODO: Which Grouper versions, limitations, etc.


== Support

This connector is _supportable_ by Evolveum.

Evolveum can provide support for this connector.
However, support for this connector is not provided on a routine basis and some special arrangements and customizations may be needed.
Please contact Evolveum representative for the details.


== Resource Examples

* link:https://github.com/Evolveum/midpoint-samples/tree/master/samples/resources/grouper[Grouper resource samples in midpoint-samples project]


== Notes

This connector is designed to work with wiki:On+Asynchronous+Processing[asynchronous processing] functionality of midPoint 4.x.


== See Also