= Metadata processing model

This is a description how metadata in midPoints are processed.

Because all processing in midPoint is based on relative changes, the following documents provide the necessary background:

* link:change-representation/[Change representation (no metadata)]
* link:change-representation-with-metadata/[Change representation (with metadata)]

Background for background (referenced from the above):

* link:comparing-values/[Comparing values]
* link:delta/[Deltas]

WARNING: The following material has to be updated.

== Data processing model (TODO)

Before trying to describe metadata processing, let us start with something simpler: How midPoint processes ordinary data?

There are three basic conceptual levels of processing, shown here from bottom-up:

1. link:plain/expressions/[Expressions]
2. link:plain/mappings/[Mappings]
3. link:plain/mapping-sets/[Mapping sets]

== Metadata processing model (TODO)

Before thinking about metadata processing let us explore some link:examples/[examples].

Here are some unorganized link:thoughts/[thoughts] about metadata processing and some link:open-questions/[open questions].
