= Who Has Access Where and Why
:page-nav-title: Process Details
:page-display-order: 100

WARNING: This page is a stub, it is a work in progress.

This is main IGA report. It provides information of assignments of specified set of users in business terminology.

Assignment of an application role represents access of the user to an application. Assignment of the business role may represent user's working position.
Assignment of an organizational unit represents user's position in organization or an project.

== Reason

#TODO - view of business data
Also for further processing or analysis of business data with outside the midpoint. To identify business patterns or irregularities.#

== Audience

Role manager, Security officers, but also business managers for some business needs.

== Scope of users

The report normally does not make sense to be build on full scope of the users -

Should be run with defined set of users.

Reasons:

* resource intensive
* too much data for analysis
* risk of revealing of sensitive data out of midpoint

== Report details

For specified list of users the report should provide:
#TODO#

// report moze obsahovat okrem roli aj organizacne jednotky v ktorych je clovek priradeny

== Example
Example of the report is xref:./www-report-example.xlsx[here].

