= MidPoint Quick Start Guide
:page-nav-title: Quick Start Guide
:page-display-order: 10
:page-liquid:
:page-toc: float-right
:toclevels: 2
:page-upkeep-status: green
:page-keywords:  [ 'quickstart', 'quickstart script', 'start script" ]

This guide is here to help you get started and deploy midPoint on your local computer using Docker in minutes.

To make the deployment as easy as possible for you, we provide a shell script you can use to deploy midPoint even if you're not proficient in using Docker.

To manage the environment for midPoint, the script uses link:https://docs.docker.com/compose/[Docker Compose] and multiple containers.

The script is built for *Linux*, and it also works on macOS.
If you're running another operating system, you may spend more time adjusting your system to satisfy the requirements.
Another option is to install Linux on a virtual machine (e.g., using link:https://www.virtualbox.org/[VirtualBox]) and run the script on the virtual machine.

If you know your way around Docker or possibly want to use a different deployment method, you can jump right to the xref:../install/index.adoc[Installation Guides].

== Requirements

Before you proceed further, make sure the following requirements are satisfied on your computer.

=== Docker

You need to have Docker installed on your computer to follow through with this guide.
Check the link:https://docs.docker.com/engine/install/[official Docker documentation] for guides on installing Docker.

.*Quick check if you have Docker installed*
[TIP]
====
Type `docker --version` in your terminal
-- if you get something like `Docker version 27.5.1, build 9f9e405`, you're good.
If not, Docker is not in link:https://en.wikipedia.org/wiki/PATH_(variable)[PATH] and likely not installed at all.
====

=== BASH

BASH is a widely used shell on Linux-based systems.
Usually, if you're on Linux or macOS, no extra step is needed here.
This script is written so that it works on all modern Linux and macOS systems.

If you're on Windows, you'll need to use the link:https://learn.microsoft.com/en-us/windows/wsl/about[Windows Subsystem for Linux (WSL)] or run Linux in a virtual machine.

[NOTE]
====
To achieve compatibility as wide level as possible, the BASH version 3.2 or newer is required.
====

=== Internet Connection

During the initial setup, the script needs Internet connection to pull the Docker image from the Docker hub.
Once everything is set up, you can test midPoint without an active Internet connection.

== Get the Script

Once you confirm you check all the requirements, you can dive right into the deployment.

. Before you download the script, create a directory on your computer. +
You'll use this directory to host the midPoint instance.

. Download the script into the directory. +
To get the latest version of the script, use `curl`: +

[source,bash]
----
curl -O https://raw.githubusercontent.com/Evolveum/midpoint-docker/master/midpoint-quickstart.sh
----

Alternatively, download it from link:https://raw.githubusercontent.com/Evolveum/midpoint-docker/master/midpoint-quickstart.sh[GitHub] using your web browser.

== Usage of the Script

Go to the directory where you saved the quick start script and run it from there.
The script takes various commands to start, stop, or clean up the midPoint environment.
You can also use a couple of parameters to adjust the behavior of the script.
More on that in the sections below.

=== Start midPoint

To start your testing midPoint instance, go to the directory with the script and run it from there with the `start` command.

.Start the midPoint environment
[source,bash]
----
./midpoint-quickstart.sh start
----

[WARNING]
====
When you run the script, your current working directory must be the one with the script.
====

You will see the progress of the deployment (objects created, waiting, healthy, exited, etc.).
Once midPoint is ready, the access URL with the <<access-credentials,default username and password>> appears.

.Access information in case of default values
[%autowidth, cols="h,1"]
|====
| URL | http://localhost:8080/midpoint/
| Username | administrator
| Password | _<generated>_
|====

[[start_output]]
.Sample output of the `start` command
[%collapsible]
====
[source]
----
$ ./midpoint-quickstart.sh start
Starting the Inicialization process...
Creating the directory "/mnt/repo/midpoint-docker/midpoint_home".
Creating the directory "/mnt/repo/midpoint-docker/midpoint_home/post-initial-objects".
Creating the directory "/mnt/repo/midpoint-docker/midpoint_home/connid-connectors".
Creating the directory "/mnt/repo/midpoint-docker/midpoint_home/lib".
Inicialization done.
[+] Running 5/5
 ✔ Network midpoint-docker_net                  Created                       0.2s
 ✔ Volume "midpoint-docker_midpoint_data"       Created                       0.0s
 ✔ Container midpoint-docker-midpoint_data-1    Started                       0.2s
 ✔ Container midpoint-docker-data_init-1        Exited                       14.3s
 ✔ Container midpoint-docker-midpoint_server-1  Started                      14.5s
MidPoint has started...
To access the WEB GUI go to http://localhost:8080/midpoint/ .
 Username : administrator
 Password : bU0lG9yEr4 (if not changed yet - init Password)
----
====

==== Access Credentials

By default, the script generates an initial username and password during the midPoint environment initialization.
You can find these credentials in your terminal after midPoint is started.
The password is stored in plain text in the *init_pw* file (located in the home directory of the instance) to keep it persistent over restarts.

If you want to set the initial password yourself, use the <<initpw,`initpw` option>>.

Better yet, you can change the account credentials post-launch in midPoint.
This is the recommended approach.
Once you change the credentials, the initial username and password are no longer valid.

*We strongly recommend changing the password* if you're up to anything more than a localhost test with dummy data.

Keep the <<password-policy,password policy>> in mind when setting up midPoint passwords.

==== Avoid Using the Same Folder Names For Multiple Instances

The quick start script uses link:https://docs.docker.com/compose/[Docker Compose] to create and maintain the midPoint containers.
Docker uses the name of the directory with the script as a prefix for newly created objects, such as volumes in `/var/lib/docker`).

If you run *multiple midPoint instances*, the last part of the path (directory name) you run the quick start script from needs to differ.
Otherwise, you'd likely face objects reused and overwritten unexpectedly.

* Incorrect names:
** /tmp/a/*mp*
** /tmp/b/*mp*

* Correct names:
** /tmp/*mp_a*
** /tmp/*mp_b*


=== Clean Up the Environment

When you're done experimenting, it's best to "turn off" midPoint cleanly and delete its data, so that unneeded files don't take up your disk space.

.Clean up the environment
[source,bash]
----
./midpoint-quickstart.sh clean
----

If the environment is running, it will first stop.
Afterward, runtime content is removed:

* Generated logs
* Connectors in the midPoint home directory
* Exported data
* CSV resource files

.Sample output of the `clean` command
[%collapsible]
====
[source]
----
$ ./midpoint-quickstart.sh clean
Starting the Clean up process...
[+] Running 5/5
✔ Container midpoint-docker-midpoint_server-1  Removed                       0.2s
✔ Container midpoint-docker-data_init-1        Removed                       0.0s
✔ Container midpoint-docker-midpoint_data-1    Removed                       0.1s
✔ Volume midpoint-docker_midpoint_data         Removed                       0.0s
✔ Network midpoint-docker_net                  Removed                       0.2s
Removing "/mnt/repo/midpoint-docker/midpoint_home"
Clean up process done.
----
====

[NOTE]
====
If you wish to just stop midPoint and continue where you left off later, use the `down` command.
====

== Commands

Here's a list of all the commands you can use to tell the quick start script what you want to do.

.Available commands
[%autowidth]
|====
| Command | Description

| `init`
| Initialize the environment +
Check and create the directory structure for the midPoint home if needed. +
_This is a part of the `up` and `start` commands._

| `clean`
| Clean the environment +
Delete the directory structure for the midPoint home. +

| `reset`
| Reset the environment +
Delete and re-create the directory structure for the midPoint home. +
_Shortcut to `clean` and `init` command._

| `start`
| Start the environment +
Initialize the environment (if needed) and start it up.

| `up`
| Same as `start`

| `down`
| Shutdown the environment +
Stop the environment and remove the container objects except volumes and data in the filesystem. +

| `clean-db`
| Clean the environment +
Delete the container environment, including volumes (such as the home volume and database storage)

| `help`
| Show help information and available options. Also shown if an unknown command or parameter is supplied.
|====

== Command Line Options

There are several possible parameters you can use to customize the behavior of the script.

Every parameter has a predefined default value.
You can use the script with the default values just fine.
However, if you want to test midPoint on a more advanced level, the customization options may be useful for that.

=== Basics

Here are descriptions of the essential customizations you can start with.

.*Options must be specified before the command. For example:*
[NOTE]
====
[source,bash]
----
./midpoint-quickstart.sh -fg start
----
====

.Descriptions of the most used command line options
[cols="1,6,5"]
|====
| Parameter | Description | Example

| `[[initpw]]-initpw`
| Specify the initial password for the administrator user object.
Keep the <<password-policy,password policy>> in mind. +
Intended for the first run only.
Don't use for password change once the user is created.
| `-initpw "Abs0lutely Secure Passphrase!"`

| `-subdir`
| A comma-separated list of directories to be created during the initialization. +
This is useful when you need additional directories, e.g., *exports*.
| `-subdir post-initial-objects,connid-connectors,lib,*exports*`

| `-port`
| Specify the HTTP port for the deployment (`localhost:<port>/midpoint/`). +
Useful for multiple parallel deployments to avoid the "already used port" error and distinguish the deployments by port numbers.
| `-port *8090*`

| `-ver`
| The version of midPoint to use.
The tag published in the link:https://hub.docker.com/r/evolveum/midpoint/tags[public registry] always contains midPoint version. +
Use this attribute to change the required version without the need to specify the whole image name or the complete tag name (including the base OS).
| `-ver *4.8.5*`

|====

==== Password Policy

In case you decide to change the initial password, keep in mind that there is a xref:/midpoint/reference/security/authentication/administrator-initial-password/#default-password-policy[password policy] in place.

When you set a password that doesn’t comply with the policy, the administrator user object won't be imported.
That means that you won't be able to log into midPoint because the administrator is the only user in midPoint after initialization.
And when the administrator isn't imported, there's no account to log into.

Although there are workarounds for this, the easiest way out is to `clean` the environment and `start` (reinitialize) it again with a
proper password.

If you keep the generated initial password, we recommend changing it after the system is properly set up anyway.

=== Advanced Options

You can use the options below for more advanced scenarios.

.Available attributes
[%autowidth]
|====
| Attribute | Description

| `-debug`
| Show operation output for the troubleshooting purpose.

| `-fg`
| Keep attached to the terminal, don't start in the background. Useful to get more insight into the operations of the script.

| `-base <base_dir>`
| Use a custom base directory instead of using the script location for the files.

| `-home <home_dir>`
| Place the home directory outside the base directory.

| `-uid <uid>`
| User ID for the processes in the container +
By default, the currently logged-in user (current session) is used.

| `-gid <gid>`
| Group ID for the processes in the container +
By default, the currently logged-in user (current session) is used.

| `-name <img_name>`
| Docker image name (without a tag) +
Used to construct the final Docker image name for the deployment.
See also `-ver`.

| `-suffix <img_v_suffix>`
| Docker image version suffix +
Used to construct the final Docker image name for the configuration.
See also `-ver`.

| -exec <env_exec_cmd>
| Shell command to run and control the environment. +
The default value is `docker` or `sudo docker` in case the user is not a member of the docker group.

| `-h`
| Show help information and available options. Also shown if an unknown command or parameter is supplied.

|====

== Exit Codes

In case you decide to experiment with the script, there are several exit codes that can help you debug unexpected situations.

.Exit codes
[%autowidth]
|====
^| Exit Code ^| Meaning

^| 0
| Normal exit (expected operation)

^| 1
| No command has been requested.

^| 2
| Can't create the directory.

^| 3
| Can't remove the directory.

^| 101
| Too short path to process (basic security check)

|====
