= MidPoint Quick Start Guide
:page-nav-title: Quick Start Guide
:page-display-order: 10
:page-liquid:
:page-toc: float-right
:toclevels: 2
:page-upkeep-status: green
:page-keywords:  [ 'quickstart', 'quickstart script', 'start script" ]

This guide is here to help you get started and deploy midPoint on your local computer using Docker in minutes.

To make the deployment as easy as possible for you, we provide a BASH script you can use to deploy midPoint even if you're not proficient in using Docker.

To manage the environment for midPoint, the script uses link:https://docs.docker.com/compose/[Docker Compose] and multiple containers.

The script is built for *Linux* and it also works on macOS.
If you're on Microsoft Windows, link:https://www.docker.com/products/docker-desktop/[Docker Desktop] may be of use to you.
However, we don't have documentation on working with Docker Desktop yet.

If you know your way around Docker or possibly want to use a different deployment method, you can jump right to the xref:../install/index.adoc[].

== Requirements

Before you proceed further, make sure the following requirements are satisfied on your computer.

=== Docker

You need to have Docker installed on your computer.
Check the documentation on link:https://docs.docker.com/engine/install/[Docker Engine] for guides on setting up Docker.

.*Quick check if you have Docker installed*
[TIP]
====
Type `docker --version` in your terminal
-- if you get something like `Docker version 27.5.1, build 9f9e405`, you're good.
If not, Docker is not in link:https://en.wikipedia.org/wiki/PATH_(variable)[PATH] and likely not installed at all.
====

=== BASH

BASH is a widely used shell on Linux-based systems.
Usually, if you're on Linux or macOS, no extra step is needed here.

This script is written for the BASH version 3.2 or newer so it works on all modern Linux systems and macOS.

[TIP]
====
Run `bash --version` in your Linux or macOS terminal to find out your BASH version.
====

=== Internet Connection

During the initial setup, the script needs an Internet connection to pull the required Docker images from the Docker hub.
Once everything is set up, you can work with midPoint offline.

== Get the Script

Once you confirm you check all the requirements, you can dive right into the deployment.

. Before you download the script, create a directory on your computer. +
You'll use this directory to host the midPoint instance.

. Use `curl` to download the script into the directory:
+
[source,bash]
----
curl -O https://raw.githubusercontent.com/Evolveum/midpoint-docker/master/midpoint-quickstart.sh
----

    * Alternatively, download the script from link:https://raw.githubusercontent.com/Evolveum/midpoint-docker/master/midpoint-quickstart.sh[GitHub] using your web browser.

. Make the script executable:
+
[source,bash]
----
chmod 744 midpoint-quickstart.sh
----

== Usage of the Script

Go to the directory where you saved the quick start script and run the script from there.

The script takes various commands to start, stop, or clean up the midPoint environment.
You can also use a couple of parameters to adjust the behavior of the script.
More on that in the sections below.

=== Start MidPoint

To start your midPoint instance, run the script with the `start` command:
[source,bash]
----
./midpoint-quickstart.sh start
----

[WARNING]
====
When you run the script, your current working directory must be the one with the script.
====

You will see the progress of the deployment (objects created, waiting, healthy, exited, etc.).
Once midPoint is ready, the access URL with the <<access-credentials,default username and password>> appears.

.Default access information
[%autowidth, cols="h,1"]
|====
| URL | http://localhost:8080/midpoint/
| Username | administrator
| Password | _<generated>_
|====

[[start_output]]
.Sample output of the `start` command
[%collapsible]
====
[source]
----
$ ./midpoint-quickstart.sh start
Starting the Inicialization process...
Creating the directory "/mnt/repo/midpoint-docker/midpoint_home".
Creating the directory "/mnt/repo/midpoint-docker/midpoint_home/post-initial-objects".
Creating the directory "/mnt/repo/midpoint-docker/midpoint_home/connid-connectors".
Creating the directory "/mnt/repo/midpoint-docker/midpoint_home/lib".
Inicialization done.
[+] Running 5/5
 ✔ Network midpoint-docker_net                  Created                       0.2s
 ✔ Volume "midpoint-docker_midpoint_data"       Created                       0.0s
 ✔ Container midpoint-docker-midpoint_data-1    Started                       0.2s
 ✔ Container midpoint-docker-data_init-1        Exited                       14.3s
 ✔ Container midpoint-docker-midpoint_server-1  Started                      14.5s
MidPoint has started...
To access the WEB GUI go to http://localhost:8080/midpoint/ .
 Username : administrator
 Password : bU0lG9yEr4 (if not changed yet - init Password)
----
====

==== Access Credentials

By default, the script generates an initial username and password during the midPoint environment initialization.
You can find these credentials in your terminal after midPoint starts.
The password is stored in plain text in the *init_pw* file (located in the home directory of the instance) to keep it persistent over restarts.

If you want to set the initial password yourself, use the <<initpw,`initpw` option>>.

Better yet, you can change the account credentials post-launch in midPoint.
This is the recommended approach.
Once you change the credentials, the initial username and password are no longer valid.

*We strongly recommend changing the password* if you're up to anything more than a localhost test with dummy data.

Keep the <<password-policy,password policy>> in mind when setting up midPoint passwords.

==== Avoid Using the Same Folder Names For Multiple Instances

The quick start script uses link:https://docs.docker.com/compose/[Docker Compose] to create and maintain the midPoint containers.
Docker uses the name of the directory with the script as a prefix for newly created objects, such as volumes in `/var/lib/docker/volumes`.

If you run *multiple midPoint instances*, run the script from directories of different names.
Otherwise, you'd likely face objects reused and overwritten unexpectedly.

* Correct directory names:
** /tmp/*mp_a*/
** /tmp/*mp_b*/

* Incorrect directory names:
** /tmp/a/*mp*/
** /tmp/b/*mp*/


=== Clean Up the Environment

When you're done experimenting, it's best to "turn off" midPoint cleanly and delete its data, so that unneeded files don't take up your disk space:

[source,bash]
----
./midpoint-quickstart.sh clean
----

If the environment is running, it will first stop.
Afterward, runtime content is removed:

* Generated logs
* Connectors in the midPoint home directory
* Exported data
* CSV resource files

.Sample output of the `clean` command
[%collapsible]
====
[source]
----
$ ./midpoint-quickstart.sh clean
Starting the Clean up process...
[+] Running 5/5
✔ Container midpoint-docker-midpoint_server-1  Removed                       0.2s
✔ Container midpoint-docker-data_init-1        Removed                       0.0s
✔ Container midpoint-docker-midpoint_data-1    Removed                       0.1s
✔ Volume midpoint-docker_midpoint_data         Removed                       0.0s
✔ Network midpoint-docker_net                  Removed                       0.2s
Removing "/mnt/repo/midpoint-docker/midpoint_home"
Clean up process done.
----
====

[NOTE]
====
If you wish to just stop midPoint and continue where you left off later, use the `down` command instead.
====

== Commands

Here's a list of all the commands you can use to tell the quick start script what you want to do.

.Available commands
[%autowidth]
|====
| Command | Description

| `init`
| Initialize the environment +
Check or create the directory structure for the midPoint home if needed. +
_This is a part of the `up` and `start` commands._

| `clean`
| Clean the environment +
Delete the midPoint home directory structure. +

| `reset`
| Reset the environment +
Delete and re-create the midPoint home directory structure from scratch. +
_Shortcut to `clean` and `init` command._

| `start`
| Start the environment +
Initialize the environment (if needed) and start it up.

| `up`
| Same as `start`

| `down`
| Shutdown the environment +
Stop the environment and remove the container objects except volumes and data in the filesystem. +

| `clean-db`
| Clean the environment +
Delete the container environment, including volumes (such as the home volume and database storage).

| `help`
| Show help information and available options. Also shown if you supply an unknown command or parameter.
|====

== Command Line Options

There are several parameters you can use to customize the behavior of the script.

Every parameter has a predefined default value.
You can use the script with the default values just fine.
However, if you want to test midPoint on a more advanced level, the customization options may prove useful to you.

.*Options must be specified before the command. For example:*
[NOTE]
====
[source,bash]
----
./midpoint-quickstart.sh -fg start
----
====

=== Basics

Here are the essential customizations you can start with.

.Descriptions of the most used command line options
[cols="1,6,5"]
|====
| Parameter | Description | Example

| `[[initpw]]-initpw`
| Specify the initial password for the administrator. +
Use only for the first run.
To change the existing administrator password, use midPoint administrative user interface (GUI).
| `-initpw "Abs0lutely Secure Passphrase!"`

| `-subdir`
| A comma-separated list of directories to be created during the initialization. +
This is useful when you need additional directories.
| `-subdir post-initial-objects,connid-connectors,lib,*exports*`

| `-port`
| Specify the HTTP port for the deployment (`localhost:<port>/midpoint/`). +
Useful for multiple parallel deployments to avoid the "port is already allocated" error and distinguish the deployments by port numbers.
| `-port *8090*`

| `-ver` [[version_switch]]
| The version of midPoint to use.
The tag published in the link:https://hub.docker.com/r/evolveum/midpoint/tags[public registry] always contains midPoint version. +
Use this attribute to change the required version without the need to specify the whole image name or the complete tag name (including the base OS).
| `-ver *4.8.5*`

|====

==== Password Policy

In case you decide to change the initial password, keep in mind that there is a xref:/midpoint/reference/security/authentication/administrator-initial-password/#default-password-policy[password policy] in place.

When you set a password that doesn’t comply with the policy, the *administrator account won't be created*.

That means that you won't be able to log into midPoint because administrator is the only account in midPoint after initialization.
And when the administrator isn't there, there's no account to log into.
Although there are workarounds for this, *the easiest way out is to `clean` the environment* and `start` (reinitialize) it again with a
proper password.

[TIP]
====
We recommend changing the initial password as soon as possible after the initial setup.
The goal is to avoid having your actual password saved unencrypted in logs or configuration files.
====

=== Advanced Options

You can use the options below for more advanced scenarios.

.Available attributes
[%autowidth]
|====
| Attribute | Description

| `-debug`
| Show more detailed operation log for the troubleshooting purposes. +

| `-fg`
| Keep the script attached to the terminal, don't start in the background. Useful to get more insight into the operations of the script. +

| `-base <base_dir>`
| Use a custom base directory instead of using the script location for the files. +
_Default: ``./``_

| `-home <home_dir>`
| Place the home directory outside the base directory. +
_Default: ``/<base>/midpoint-home/``_

| `-uid <uid>`
| User ID for the processes in the container +
_Default: the currently logged-in user (current session)_

| `-gid <gid>`
| Group ID for the processes in the container +
_Default: the currently logged-in user (current session)_

| `-name <img_name>`
| Docker image name (without a tag) +
Used to construct the final Docker image name for the deployment.
<<version_switch, See also `-ver`>>.

| `-suffix <img_v_suffix>`
| Docker image version suffix +
Used to construct the final Docker image name for the configuration.
<<version_switch, See also `-ver`>>.

| -exec <env_exec_cmd>
| Shell command to run and control the environment. +
_Default: `docker`. If user isn't in the `docker` group, `sudo docker` is used._

| `-h`
| Show help information and available options. Also shown if an unknown command or parameter is supplied.

|====

== Exit Codes

In case you decide to experiment with the script, there are several exit codes that can help you debug unexpected situations.

.Exit codes
[%autowidth]
|====
^| Exit Code ^| Meaning

^| 0
| Normal exit (expected operation)

^| 1
| No command has been requested.

^| 2
| Can't create the directory.

^| 3
| Can't remove the directory.

^| 101
| Too short path to process (basic security check).

|====

== File Paths in Docker Containers

When you learn to work with midPoint, you can, for instance, xref:/midpoint/reference/admin-gui/resource-wizard/create-resource-using-wizard/[create a resource and import accounts from a CSV file via the CSV connector].
To set up the CSV connector, you need to specify the path to the source CSV file.

Under the hood, midPoint runs inside Docker containers orchestrated by a Docker Compose file.
This setup ensures that midPoint works seamlessly on your machine without requiring you to manage the environment manually.
Our goal is to enable you to benefit from Docker's capabilities without having to interact directly with containers or use Docker commands in most cases.

=== Quickstart Script Structure

When you use the quickstart script, it automatically creates a directory named `midpoint-home` in the location where the script was executed.
This directory acts as the *midPoint home directory* and contains several subfolders that correspond to specific paths inside the Docker container.
These folders are mounted into the container so that midPoint can access their contents.

[%autowidth,cols="1,3",options="header"]
|===
| Subfolder | Purpose
| `import` | Use this folder to add files for import, e.g. CSV files for the built-in CSV connector. When configuring the connector in midPoint, specify the internal path so that midPoint can access the file: `/opt/midpoint/var/import/file-name.csv`.
| `log` | Contains all log files generated by midPoint. You can inspect them directly on your host system without entering the container.
| `schema` | Use this folder to store custom XML schema definitions to extend or customize midPoint configuration. Updating schemas using this folder typically requires restarting midPoint. For more details, see xref:/midpoint/reference/schema/[Schema customization documentation].
| `icf-connectors` | Place custom ICF connectors here if you want to use your own connectors instead of the built-in ones. For more information, see xref:/connectors/[Connectors documentation].
|===

=== Working Directly with Docker

If you do not use the quickstart script and prefer to run midPoint manually with Docker, you can still access all configuration and data within the container.
Inside the midPoint container, the home directory and all its subfolders are located under:

[source,bash]
----
/opt/midpoint/var/
----

You can enter the container and inspect or modify files directly as follows:

. List your Docker containers:
+
[source,bash]
----
docker ps
CONTAINER ID   IMAGE                            COMMAND                 ...
41b8ffa427ff   evolveum/midpoint:4.9.2-alpine   "/opt/midpoint/bin/m…"  ...
98fb6ba2a28f   postgres:16-alpine               "docker-entrypoint.s…"  ...
----

. Enter the container:
+
[source,bash]
----
docker exec -it <midpoint-container-id> bash
cd /opt/midpoint/var/
----

We recommend managing files through the `midpoint-home` directory on your host system. Only troubleshoot or explore advanced configuration directly inside the container when necessary.
