= MidPoint Quick Start Guide for Windows
:page-nav-title: Quick Start Guide for Windows
:page-display-order: 10
:page-liquid:
:page-toc: float-right
:toclevels: 2
:page-upkeep-status: green
:page-keywords:  [ 'quickstart', 'quickstart windows', 'quickstart for windows']

This guide is here to help you get started and deploy midPoint on your local computer with Windows OS using Docker Desktop and PowerShell. 

== Requirements

Before you proceed further, make sure the following requirements are satisfied on your computer.

=== Microsoft Windows 

To proceed with this tutorial, you need to have Windows OS. 
If you're on Linux or macOS, follow xref:index.adoc[Quick Start Guide].

=== Docker Desktop

You need to have Docker Desktop installed on your computer.
See the link:https://docs.docker.com/desktop/setup/install/windows-install/[Docker Desktop installation manual].
Feel free to use the default settings during the installation process.

.*Quick check if you have Docker installed*
[TIP]
====
Type `docker desktop` in the Start Menu search. 
If you see the `Docker Desktop App`, you're good. 
If not, Docker is likely not installed at all. 
====

=== PowerShell

PowerShell is the default command-line shell on modern Windows systems.
If you are using Windows, PowerShell is already installed and available by default, so no additional setup is required.
This script is written for PowerShell 5.1 or newer.

[TIP]
====
To check the installed PowerShell version, run the following command in PowerShell: `$PSVersionTable.PSVersion`
====

=== Internet Connection

During the initial setup, you need to download the Docker Compose file. 
Once everything is set up, you can work with midPoint offline.

== Installing midPoint
This section explains how to start the midPoint environment using Docker Compose. 
You will download the compose file, start the containers, retrieve the administrator password, and access the midPoint web interface.

=== Starting the docker container
A working midPoint environment requires more than just a single application. To simplify the setup, we provide a Docker Compose configuration file. It defines all required components and includes the necessary settings. Running this file creates an isolated environment with all parts properly configured.

. Open PowerShell and navigate to the directory where you want to store the Docker Compose file using the `cd` command.
+
[source,powershell]
----
cd C:\my\desired\path
----
. Paste the following command into PowerShell to download the compose file. 
+
[source,powershell]
----
Invoke-WebRequest -Uri `
"https://raw.githubusercontent.com/Evolveum/midpoint-docker/master/docker-compose.yml" `
-OutFile "docker-compose.yml"
----
+
[TIP]
====
Run `dir` in PowerShell to check the contents of the current directory. You should see the downloaded docker-compose.yml file. 
====
+
It is recommended not to rename the downloaded `docker-compose.yml` file. 
If you use a different name, you need to define it explicitly in all Docker Compose commands with the *-f* parameter. 
+
[NOTE]
====
All objects based on the Docker Compose file will contain the directory name as a prefix.
====

. Start the environment in the background:
+
[source,powershell]
----
docker compose up -d
----
+
The web GUI becomes available once the environment starts and the initiation (loading initial objects into the empty repository, etc.) is completed. 
Depending on your environment, this may take several minutes.

=== Logging into the midPoint
