---
layout: connector-page
display-order: 900
functionality-status: stable
development-status: abandoned
support-status: unsupported
origin: ICF
target-systems: Solaris servers, possibly also other Unix systems.
connector-protocol: SSH/Telnet
source-url-master: https://github.com/Evolveum/openicf/tree/master/connectors/java/solaris
description: Identity connector for Solaris servers, possibly usable for other UNIX-like servers.
connid-bundle-name: org.forgerock.openicf.connectors.solaris-connector
upkeep-status: yellow
---
= Solaris Connector
:page-wiki-name: Solaris Connector
:page-wiki-id: 7307490
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2013-01-29T11:12:49.630+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-07-09T14:12:20.357+02:00

== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| Provisioning
| YES
|

| Live Synchronization
| NO
|

| Password
| YES
|

| Activation
| YES
|

| `su`
| YES
|

| `sudo`
| YES
|

|===


== History

This is mostly the original Sun ICF Solaris connector.
It was extended for Linux use by Evolveum.

[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | Description

| 1.1.0.e6322d
| OpenICF development version, built and tested by Evolveum
| https://nexus.evolveum.com/nexus/repository/openicf-releases/org/forgerock/openicf/connectors/solaris-connector/1.1.0.e6322d/solaris-connector-1.1.0.e6322d.jar[download jar]
| OpenICF: solaris-connector-1.1.1.x-dev branch, revision 6322
| Feb 2013
| Solaris well tested, Linux slightly tested.
There may be problems with sudo authorization.


| 1.1.0.e6327d
| OpenICF development version, built and tested by Evolveum
| https://nexus.evolveum.com/nexus/repository/openicf-releases/org/forgerock/openicf/connectors/solaris-connector/1.1.0.e6327d/solaris-connector-1.1.0.e6327d.jar[download jar]
| OpenICF: solaris-connector-1.1.1.x-dev branch, revision 6327
| Feb 2013
| Works well +
Known issues: sudo password matching


| 1.1.0.em13
| OpenICF Evolveum version
| https://nexus.evolveum.com/nexus/repository/openicf-releases/org/forgerock/openicf/connectors/solaris-connector/1.1.0.em13/solaris-connector-1.1.0.em13.jar[download jar]
| Evolveum OpenICF, revision emark-13-gd1b4de0
| 15 Aug 2013
| Works well


| 1.1.0.em77
| OpenICF Evolveum version
| https://nexus.evolveum.com/nexus/repository/openicf-releases/org/forgerock/openicf/connectors/solaris-connector/1.1.0.em77/solaris-connector-1.1.0.em77.jar[download jar]
| Evolveum OpenICF, revision emark-77-gbbe5fa6
| Oct 2013
| Somehow tested. +
Contains features not available in the OpenICF trunk yet.

|===


== Documentation

[NOTE]
.Patterns
====
The connectors works by matching *patterns* of the input that it receives from the Telnet/SSH channel.
Therefore also some of the configuration parameters are *patterns*. Especially the expected prompt configuration parameters `rootShellPrompt` and `loginShellPrompt`. It is usual to set them to `$` especially if `sudo` is used.
However, the dollar sign is a pattern that matches the end of line.
If set like this it will match too early and offset all the other commands.
The dollar sign needs to be escaped to avoid its special meaning.
Therefore the correct setting for prompt patterns is `\$`.
====

== Troubleshooting


=== Enable Logging

Set appropriate logger in midPoint:

[%autowidth]
|===
| Logger class name |

| `org.identityconnectors.solaris`
| Connector functions


| `com.jcraft.jsch`
| SSH connection details (logs from the underlying JSch library)


| `expect4j`
| Sent and received data, pattern matching (logs from the underlying Expect4j library, see also a note below)

|===

The connector is using Expect4j library to do most functions.
The logging of the connector itself should be enough for normal troubleshooting (e.g. it displays every send and received command).
But for some problems a finer logging is needed.
Unfortunately the Expect4j is using obsolete java.util.logging (JUL) framework that does not work well with ICF.
Yet there is a xref:/midpoint/reference/diag/logging/[workaround for this]. Use the following line in `logging.properties` file to enable Expect4j logging:

.logging.properties
[source]
----
expect4j.level = ALL
----