---
layout: connector-page
display-order: 200
functionality-status: stable
development-status: dormant
support-status: obsolete
origin: Evolveum
support-provided-by: Evolveum
target-systems: Microsoft Windows Server 2012R2
source-url-master: https://github.com/Evolveum/connector-powershell
description: Identity connector for PowerShell script execution on Windows servers.
connid-bundle-name: com.evolveum.polygon.connector.powershell
upkeep-status: green
---
= PowerShell Connector
:page-wiki-name: PowerShell Connector
:page-wiki-id: 44302558
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2020-01-23T15:54:55.356+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2020-10-29T14:00:00.743+01:00


Specialized connector that provides PowerShell scripting capabilities.

This connector is designed to be used as _additional connector_ together with other connectors, usually  Active Directory connector.

.Obsolete
WARNING: This connector is obsolete.
It is no longer supported or maintained.
Please use xref:../com.evolveum.polygon.connector.ssh.SshConnector/[SSH Connector] instead.

== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| Schema
| NO
|

| Provisioning
| NO
|

| Live Synchronization
| NO
|

| Password
| NO
|

| Activation
| NO
|

| Paging support
| NO
|

| Native attribute names
| NO
|

| Scripting
| YES
| Command execution and Powershell by using WinRM (WS-MAN)

|===


== History

[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | ConnId Framework | Bundled with midPoint | Description

| 1.0
| Evolveum
| link:https://nexus.evolveum.com/nexus/repository/releases/com/evolveum/polygon/connector-powershell/1.0/connector-powershell-1.0.jar[download jar]
| link:https://github.com/Evolveum/connector-powershell/tree/v1.0[GitHub]
| 3 Apr 2020
| 1.5.0.0
| None
| Initial version. +
Separated from xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[AD connector] version 2.4


| 1.1
| Evolveum
| link:https://nexus.evolveum.com/nexus/repository/releases/com/evolveum/polygon/connector-powershell/1.1/connector-powershell-1.1.jar[download jar]
| link:https://github.com/Evolveum/connector-powershell/tree/v1.1[GitHub]
| 21 July 2020
| 1.5.0.0
| None
| Option to disable certificate checks.


| 1.1.1
| Evolveum
| link:https://nexus.evolveum.com/nexus/repository/releases/com/evolveum/polygon/connector-powershell/1.1.1/connector-powershell-1.1.1.jar[download jar]
| link:https://github.com/Evolveum/connector-powershell/tree/v1.1.1[GitHub]
| 6 August 2020
| 1.5.0.0
| None
| Fixing disableCertificateChecks: allowing FQDN and CN mismatch.

|===

This connector was part of the xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] bundle.
It was distributed together with xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP Connector] and xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.edirectory.EDirectoryLdapConnector/[eDirectory Connector].
However, it was "unbundled" and it is now a separate connector.

This connector was "separated" from xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)] version 2.4.

== Interoperability

Following versions of Windows servers are supported:

* Microsoft Windows Server 20012R2

This connector is *obsolete*.
It is not supported.
The Win-RM services proved to be very problematic and unstable while using this connector.
Fortunately, recent Windows servers have an option to install SSH servers.
*Use of SSH instead of Win-RM is strongly recommended*.
Please use xref:/connectors/connectors/com.evolveum.polygon.connector.ssh.SshConnector/[SSH Connector] instead of this connector whenever possible.


=== MS Exchange Interoperability

Technically, this connector can be used to provision Microsoft Exchange servers in an indirect way by using PowerShell scripts.

Firstly, the Exchange attributes are accessible in Active Directory when the Exchange software is installed.
The xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)] is needed to manage those attributes.

Secondly, this connector can be used to execute powershell scripts remotely using the WinRM interface.
This feature can be used to manage Exchange mailboxes and additional settings.
Please see xref:/connectors/resources/active-directory/powershell/[Powershell Support in AD/LDAP Connector] page for more details.

However, support for MS Exchange is *not*  included in standard support for this connector (see below).


== Support

This connector was deprecated in favor of xref:/connectors/connectors/com.evolveum.polygon.connector.ssh.SshConnector/[SSH Connector].

This connector is not supported any more (but it is not xref:/support/bundled-support/[bundled] with midPoint support, it has to be purchased separately).

Even when the connector was supported, there were limitations:

* Only some Windows server versions were supported (see above)

* PowerShell scripting implemented in this connector was supposed to be used to supplement creation of Active Directory (windows) accounts by using simple scripts.
It was not supposed to be used to manage Microsoft Exchange accounts.
Management of Exchange accounts can be quite a complex matter, requiring complicated PowerShell scripts.
You can use this connector to manage Exchange accounts if you want to.
However, when it comes to the content of the scripts you are on your own.
You are responsible for the content of the scripts that the connector executes.
Therefore if the script does not do what you think it should be doing then you have to fix it.
This is not covered by support contract.
If the script is not executed at all because of a bug in the connector then it is part of the support contract.
But *we are not responsible for the content of the scripts*, we do not provide any official guidance on how those scripts should look like and what they should do.
There may be some examples or hints in the documentation.
But those should be considered to be examples only.
We do not guarantee that they work.


== Licensing

The connector itself is available under the terms of Apache License 2.0.  We are not using any Microsoft library or any other component that might be subject to Microsoft licensing.
To our best knowledge no extra license is needed to use the connector with Windows servers.
However the Microsoft license texts are not entirely clear and we are not lawyers.
Therefore it is recommended for each user to make his own analysis of the licensing issues.
Please use your Microsoft support program and contact Microsoft with the licensing question when in doubt.


== Resource Examples

* xref:/connectors/resources/active-directory/powershell/[Powershell Support in AD/LDAP Connector]


== See Also

* xref:/connectors/connectors/com.evolveum.polygon.connector.ssh.SshConnector/[SSH Connector]

* xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.ad.AdLdapConnector/[Active Directory Connector (LDAP)]

* xref:/connectors/resources/active-directory/powershell/[Powershell Support in AD/LDAP Connector]

* xref:/connectors/resources/active-directory/tips-tricks/[Active Directory Tips&Tricks]

* xref:/connectors/resources/active-directory/active-directory-howto/[Active Directory HOWTO]