= IGA Is All About Account Synchronization
:page-nav-title: IGA Means Accounts
:page-description: Identity governance and administration (IGA) is not about account synchronization. It is about policies, policies for access control and business-oriented governance policies.
:page-layout: myth
:upkeep-status: green

Identity governance and administration (IGA) systems are all about synchronization of accounts.
They pull data from HR database, synchronize them to Active Directory and handful of other applications.
That is pretty much it.
IGA systems are in fact just glorified data synchronization engines.

This might have been the case in early 2000s.
It may still be quite a good descriptions of products that have not evolved in last 20 years.
However, it is miles away from the truth when it comes to state-of-the-art IGA platforms.

== Synchronization

Just to be completely clear, account feature:identity-lifecycle[lifecycle management] and attribute feature:synchronization[synchronization] are still fundamental functions of every IGA platform.
That makes sense, as we need xref:/iam/myths/my-data-are-perfect/["reliable, clean and consistent data"] to work with.
Synchronization is still there, it is still necessary - it is just not the most important responsibility of IGA platforms.
IGA platforms are doing so much more that mere synchronization is not playing primary role any more.

== Joiner Mover Leaver

Traditional wisdom states that IGA platforms are primarily focused on _joiner-mover-leaver_ (JML) processes.
Indeed, the xref:/midpoint/methodology/first-steps/[first steps] of IGA deployment are usually about JML process automation.
However, that is the very beginning of IGA deployment project, not to even mention long-term identity governance _program_.
Even though JML processes are the traditional first steps, they make up relatively small part of IGA landscape.
In fact, state-of-the-art IGA platforms are not really focusing on processes at all, they are focusing on _policies_.
IGA platform deals with intricacies of complex feature:identity-lifecycle[lifecycle], managing all possible lifecycle states and state transitions.
Of course, the three basic transitions (join, move, leave) are still the most important ones.
However, they are not the only ones.
Real state models are much more complicated than the "JML" thinking would suggest.
User may exist as a candidate before joining, user may be suspended instead of moved (maternal leave, sabbatical), user may still exist after leaving (retiree, alumnus) and so on.
Moreover, lifecycle states of an _identity_ is not nearly enough.
Identity has numerous feature:assignment[_relationships_] to other identities, such as personas, ownership, privileges, membership in organizational units and groups and so on.
These need to be managed as well, and they often have lifecycles on their own.
Reality of identity management is much more complicated that it would seem.

== User Accounts

IGA is not just about _user accounts_ any more.
First of all, there are many types of _accounts_ to manage.
Majority of accounts are still ordinary _user accounts_, belonging to employees, contractors and students.
However, there are _service accounts_ as well, used by _applications_ and other _services_ instead of _users_.
These correspond to _non-human identities_, such as _machine identities_.
State-of-the-art IGA platforms are built to manage non-human identities as much as human identities.
However, there is a large set of non-human identities that correspond to _concepts_.
Groups, roles, entitlements and access privileges are perhaps the most important examples of such identities.
Then there are organizational units, teams, projects, business partners, locations and similar concepts.
IGA platform must be able to handle these concepts, as they are intimately related to access control and policies.
Good IGA platform must be able to manage wide variety of identity types, not just mere user accounts.

== Access Control

One of the primary responsibilities of IGA platform is _access control_.
However, this much easier said than done.
Access control has many shapes and forms.
There are many competing access control models, used to express xref:/iam/myths/policies-are-easy/[access control policy].
Indeed, it is a _policy_ that the IGA systems are built to manage.
IGA platforms effectively act as glossref:pap[policy administration point (PAP)], system which is used to create and manage access control policies.
IGA platform then _provisions_ the policy and related data to other components (glossref:prp[PRP], glossref:pdp[PDP], glossref:pip[PIP]).

It follows that synchronization of feature:entitlement[entitlements] such as groups and roles is one of most useful function of IGA platform.
Entitlements are the lifeblood of access control.
However, each application works with its own set of entitlements: privileges, permissions, groups, roles and other exotic lifeforms of the access control ZOO.
IGA platforms are aligning them, combining them into a unified access control policy.
Given the diversity of access control world, this is not entirely easy job.

Even ordinary xref:/iam/myths/policies-are-easy/[policies are not easy], unified organization-wide policies are even harder.
Static role-based access control (RBAC) models are both very common and very obsolete.
However, state-of-the-art IGA systems provide xref:/iam/myths/rbac-is-static/[dynamic RBAC] models, with policy-based features.
E.g. midPoint provides xref:/midpoint/reference/roles-policies/roles/pdrbac/[policy-driven RBAC] mechanism.

== Identity Governance

Access control policies are the at the very heart of identity _administration_.
But what about identity _governance_?

Identity _governance_ is all about policies.
However, governance policies are quite different from access control policies.
While access control policies specify "who has access to what", governance policies specify "who is responsible for what".
These are high-level, business-oriented policies.
They are critical for maintaining cybersecurity governance at scale.

Governance policies may take many forms.
Some governance policies are at the very boundary of access control, such as feature:sod[segregation of duty (SoD) policies].
Governance policies may require that each feature:application-inventory[application] has an owner, each entitlement and application role has an owner, critical roles are properly staffed, role definitions are regularly reviewed, risk hot-spots are addressed, applications are properly classified, clearances are reviewed, user awareness is regularly refreshed, and so on.
Many governance policies are focused on _ownership_, as ownership forms a foundation for responsibility.
Governance policies are accounting for the technology, yet they are firmly oriented towards business side.
They are the best too for xref:/midpoint/compliance/[identity-based cybersecurity compliance].

Governance policies are the "G" in IGA.
No IGA platform would be complete without implementation of identity governance policies.

== See Also

* xref:/iam/myths/policies-are-easy/[]

* xref:/iam/myths/rbac-is-static/[]
