= Login Roles
:page-description: Creating special-purpose roles that provide basic account properties was a common practice in old IDM systems from 2000s. This complication is not necessary any more.
:page-nav-title: Login Roles
:page-layout: myth
:page-moved-from: /iam/antipatterns/login-roles/
:upkeep-status: yellow

// TODO: use application instead of login role

There is an xref:/midpoint/reference/roles-policies/roles/rbac/[RBAC] practice that is quite common, but mostly wrong.
Many IDM deployments create "login roles" or "default roles" for each application (resource).
Those roles are supposed to define basic properties of the account.
In some cases they are supposed to keep account in existence when such account is unassigned.
While this practice is very common, it is complicated, messy and very difficult to maintain.
MidPoint was specifically designed tn such a way that this practice is not necessary in midPoint deployments.
Default account attributes are easy to set up by using resource definition.
And even the ability to keep unassigned account is directly supported in midPoint by using existence mapping, which will be described later.
Therefore, such "login roles" are not needed at all in midPoint deployments, and they are generally considered to be a bad practice.
