---
layout: connector-page
display-order: 200
functionality-status: experimental
development-status: dormant
support-status: supportable
origin: Evolveum
support-provided-by: Evolveum
target-systems: Gitlab server
connector-protocol: REST
source-url-master: https://github.com/Evolveum/connector-gitlab-rest
description: Identity connector for Gitlab servers.
connid-bundle-name: com.evolveum.polygon.connector.gitlab.rest
visibility: hidden
upkeep-status: yellow
---
= GitLab Connector
:page-wiki-name: GitLab Connector


GitLab connector was implemented for 9.5.0 version of GitLab server. Connector contains basic functionality. This connector was implementing for branch update-delta-op of midPoint 3.5 and for branch update-delta-op of ConnId.

== Capabilities and Features

[%autowidth,cols="h,1"]
|===
| Provisioning
| YES

| *Live Synchronization*
| NO

| *Password*
| YES

| *Activation*
| YES

| *Paging support*
| YES

| *Native attribute names*
| YES

| *Scripting*
| NO

|===

== History

[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | ConnId Framework | Description

| *1.0*
| *Polygon*
| link:http://nexus.evolveum.com/nexus/content/repositories/releases/com/evolveum/polygon/connector-gitlab-rest/1.0/connector-gitlab-rest-1.0.jar[download jar]
| link:https://github.com/Evolveum/connector-gitlab-rest[GitHub]
| *February 2018*
| *1.4.3.0-SNAPSHOT **(branch update-delta-op)*
| *Official release*

|===

== Licensing

The connector itself is available under the terms of Apache License 2.0. To our best knowledge there is no extra license needed to use this connector. (Additional  licensing terms and conditions may apply with services on which the connector is used).


== Known limitations

During creating of this connector were detecting some limitations:

* the filters EndsWithFilter, StartsWithFilter, AndFilter, OrFilter and NotFilter are not supported

* avatars are supported only for inbound (are not supported for outbound)


== Configuration

GitLab connector uses PRIVATE-TOKEN of server administrator for authentication to GitLab server. You can obtain PRIVATE-TOKEN via setting of administrator user in GUI after login.

Mandatory property fields:

* Private Token

* GitLab endpoint

Sample configuration values:

* Private Token: XXXXXXXXXXXXXXXXXXXX (Token from GitLab)

* GitLab endpoint: myGitLabServer.com  (OR 172.36.88.94:8085)


== Setting up tests

The test package consists of several classes with the test methods. Before tests start is needed to enter some mandatory parameters to property file. This property file is located within the connector source bundle in the connector-gitlab-rest git repository in the testProperties folder.

The property file consists of two attribute name/value pairs.

* privateToken represents PRIVATE_TOKEN of administrator from GitLab server, where you will work.

* loginUrl represents URL address of GitLab server, where you will be work.

More objects, which names have to be specific, are used during execution. Following objects  names are used for testing:

* *for users as username:*

** snow

** snow(2-8)

** stark

** user21222example

** testUserPer(0-499)

* *for groups as name:*

** stark

** targaryen Gameofthrones

** lannister

** group145example

** Name testGroupPerformance

** Name testGroupPer(0-499)

** Name testGroupPer(0-499) Update

* *for projects as name:*

** Battle of Bastards

** Attack on Casterly Rock

** Attack on Casterly Rock _.-

** Attack on Highgarden ľščťžýáíéôúňä

** project897example

** Name testProjectPer(0-499)

** Name testProjectPer(0-499) Update

If any objects remain on GitLab server after testing, we can use method deleteUsedObject() which is located in class BasicFunctionForTests.java (whole class address is connector-gitlab-rest/src/test/java/com/evolveum/polygon/connector/gitlab/rest/BasicFunctionForTests.java).

== Resource Examples

* link:https://github.com/Evolveum/midpoint-samples/tree/master/samples/resources/gitlab[Samples on github]
