= Repository Implementation
:page-toc: top

== Repository responsibilities

These are based on https://github.com/Evolveum/midpoint/blob/master/repo/repo-api/src/main/java/com/evolveum/midpoint/repo/api/RepositoryService.java[RepositoryService]
interface and there should be no difference compared to the legacy repository.
Each point contains design/implementation notes.

* _Repository stores midPoint objects (subtypes of `ObjectType`), assigning their OID if missing._
For this `m_object` table with `oid` (UUID) and `fullObject` (BYTEA) columns would be enough.
However, this is not acceptable for `searchObjects` performance see note there.
* _Repository assigns any missing container IDs (CID) for object's containers._
These IDs are unique inside a single object and assigned loosely sequentially.
For this `m_object.cid_seq` is stored in the database and it contains the next available CID.
IDs are assigned only to multi-valued containers, e.g. object's metadata does not need any CID.
* _Repository allows for searching for objects and selected containers with reasonable performance._
This is why objects stored as documents (`fullObject`) is not enough.
Various types are stored in specific sub-tables instead with values extracted to separate columns.
There are other related tables, typically for containers and other multi-value properties.
Not all values are by default searchable/indexable in this way and it must be possible to specify
what other properties are indexed.
These can be properties from the default schema but also from *schema extensions*.
// link to midpoint/prism/schema/basic-definitions.adoc?
* _Each object is a separate "aggregate" and any inter-object references are soft, not constraints
on the database level._
For example, multi-value container `roleMembershipRef` is stored in `m_ref_role_membership` table
which has a foreign key to the


== Adding object

TODO
