= Schrödinger Design Notes

See link:/midpoint/schrodinger/[Schrödinger docs page].

== Plans For MidScale

* Improve handling of component markers.
The markers are not globally-unique.
Search for markers should be properly scoped to componenet element.
API should be prepared for this already, but the implementation is not complete.

* MidPoint instance initialization.
We probably need to add REST client to Schrödinger.

* Performance testing with Schrödinger, hybrid Schrödinger+load testing.
It is unrealistic to expect that Schrödinger will have sufficient performance to fully load midPoint server.
Therefore we will need to combine several Schrödinger clients with clients that can generate massive load.
E.g. JMeter or similar tool may be useful.
+
The goal is for the JMeter to put midPoint server under load, while Schrödinger clients can checks whether midPoint operates correctly.

* Better coverage of GUI functionality in Schrödinger framework code.

* Improve Schrödinger documentation.