= Manual resource
:page-nav-title: Manual Resource Examples
:page-display-order: 600
:sectnums:
:sectnumlevels: 3
:visibility: hidden

// Tento dokument nebude obsahovat presny manuany resource, iba jeho zakladne principy na priklade.



Name: Manual Operations
////
// Budeme mat vyrobene object Typy -> pre kazdy typ operacie. Pre userov sa to bude volat Entitlement type
Priklady:
    Windows Share - to bude pre vytvaranie sharov na windows hostoch, robi to jeden aplikacny tim
    Windows host access - windowsacky prevadzkovy tim, standardne pracovne postupy
    Linux host access - toto realizuje iny team, ine pracovne postupy
    VPN Access Profile - sietari - pripravia ucet vo VPN koncentratore a daju usera do profilu.

// Budu roztriedene podla realizacnych timov -

// priklad - RDP access na windows servery
////
kind: entitlement
intent:
displayName: Host Access

realizationTeam: <tu bude nazov realizacneho timu, ktory robi>


// Pokial aplikacny inzinier bude uz mat pre dany typ operacie pripraveny objectType - tak bude moct robit novu rolu pre dany object type. Pokial nebude, tak b
