= OpenICF
:page-wiki-name: OpenICF
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2013-02-13T16:26:40.747+01:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2018-06-21T10:01:27.325+02:00

[WARNING]
====
MidPoint is no longer using OpenICF framework.
Neither Evolveum nor nLight are cooperating on OpenICF project any longer.

MidPoint is fully migrated to wiki:ConnId[ConnId] framework and Evolveum is an active contributor to the wiki:ConnId[ConnId project].
====

[TIP]
====
OpenICF framework used to be compatible with ConnId.
Due to unilateral changes in OpenICF, OpenICF and ConnId are no longer compatible.
Therefore, stock OpenICF connectors *cannot* be used in midPoint.
Older or modified OpenICF connectors may still be able to work with midPoint.
However, their use is *not longer supported*.
====

== OpenICF

OpenICF was a descendant of Sun Identity Connector Framework (Sun ICF) which was probably the only usable open-source part of Sun Identity Manager.
OpenICF was an open project governed by ForgeRock.
Although there was a significant number of improvements over the original Sun version the basic approach and architecture remains the same.

OpenICF used to be compatible with wiki:ConnId[ConnId framework], it is sharing the same architecture, concepts and significant part of the code base.
But there are some unilateral code changes made by ForgeRock that made the connectors incompatible.
Please refer to the wiki:ConnId[ConnId] and wiki:Identity+Connectors[Identity Connectors] pages for more details.

As far as we can tell, OpenICF is no longer maintained as an open source project.
We strongly recommend to use ConnId instead.

== OpenICF Issues

There are several wiki:ICF+Issues[known and painful issues in ICF design] there are not critical.
These issues are addressed as a joint effort of several companies in cooperation with the wiki:ConnId[ConnId project].


== See Also

* wiki:ConnId[ConnId]

* wiki:ICF+Issues[ICF Issues]