= ConnId Result Handlers
:page-wiki-name: ICF Configuration Tips and Tricks
:page-upkeep-status: green

ConnId _result handlers_ are an artifact of an xref:icf-issues.adoc[original Identity Connector Framework over-engineering].
The handlers are supposed to assist connectors by implementing "mechanism" that the connector or resource does not support - such as search result filtering, data normalization and so on.
However, these handlers are too generic, and they know nothing about the particulars of the resource that the connector connects to.
Therefore, in vast majority of cases, these handlers just get in the way, and they distort the data.
Good connectors usually do not need these handlers at all.
Unfortunately, these handlers are enabled by default and there is no way for a connector to tell the framework to turn them off.
The handlers need to be explicitly disabled in the resource configuration:

[source,xml]
----
<resource>
    ...
    <connectorConfiguration>
        ...
        <icfc:resultsHandlerConfiguration>
            <icfc:enableNormalizingResultsHandler>false</icfc:enableNormalizingResultsHandler>
            <icfc:enableFilteredResultsHandler>false</icfc:enableFilteredResultsHandler>
            <icfc:enableAttributesToGetSearchResultsHandler>false</icfc:enableAttributesToGetSearchResultsHandler>
        </icfc:resultsHandlerConfiguration>
    </connectorConfiguration>
    ...
</resource>
----

We *strongly recommend to disable all the handlers* when working with well-designed connectors in general and when working with our LDAP or AD/LDAP connectors in particular.
