---
layout: connector-page
display-order: 200
functionality-status: stable
development-status: dormant
support-status: supportable
origin: Evolveum
support-provided-by: Evolveum
target-systems: Standard SCIM v1 servers
connector-protocol: SCIM 1.1
source-url-master: https://github.com/Evolveum/connector-scim1
description: Generic identity connector for SCIM 1.1 servers.
connid-bundle-name: com.evolveum.polygon.scim
upkeep-status: orange
---
= SCIMv1 Generic Connector
:page-wiki-name: SCIMv1 Generic Connector
:page-wiki-id: 23691296
:page-wiki-metadata-create-user: matus.macik
:page-wiki-metadata-create-date: 2016-10-19T15:54:09.640+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-07-09T14:22:31.732+02:00

A generic connector for exchange of identity information which implements the 1.1 version of the System for Cross-domain Identity Management (SCIM) standard. Please see the "Interoperability" section below.

== Capabilities and Features

[%autowidth,cols="h,1,1"]
[%autowidth]
|===
| Provisioning
| YES
|

| Live Synchronization
| NO
| Will be implemented if a service is found (for test purposes) which complies to the  scim polling protocol specification.

| Password
| YES
|

| Activation
| YES
| Activation via the active attribute.

| Paging support
| YES
|

| Native attribute names
| YES
|

| Scripting
| NO
|

|===

== Versions

[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | ConnId Framework | Description

| *1.4.2.14*
| *Polygon*
| https://nexus.evolveum.com/nexus/repository/releases/com/evolveum/polygon/scim/connector-scim/1.4.2.16/connector-scim-1.4.2.16.jar[download jar]
| link:https://github.com/Evolveum/connector-scim1[GitHub]
| *October 2016*
| *1.4.2.16*
| Official release

| *1.4.3*
| *Polygon*
| https://nexus.evolveum.com/nexus/repository/releases/com/evolveum/polygon/scim/connector-scim/1.4.3/connector-scim-1.4.3.jar[download jar]
| link:https://github.com/Evolveum/connector-scim1[GitHub]
| *December 2016*
| *1.4.2.18*
| *Official release*

| *1.4.4*
| [.underline]#*Polygon*#
| [.underline]#https://nexus.evolveum.com/nexus/repository/releases/com/evolveum/polygon/scim/connector-scim/1.4.4/connector-scim-1.4.4.jar[download jar]#
| link:https://github.com/Evolveum/connector-scim1[GitHub]
| *March 2017*
| *1.4.2.18*
| *Official release*

|===

== Interoperability

[WARNING]
.SCIM Troubles
====
Due to the nature of SCIM protocol the usefulness of this connector is likely to be *very limited*. SCIM is a very vague standard and almost any practical deployments of SCIM are heavily customizing the protocol to suit their needs.
As this connector implements only standard SCIM operations and schemas, it is unlikely that it can provide a complete functionality for any particular deployment.
Basic operations may work, but there is no guarantee of completeness or even usefulness of this connector in any practical case.

The reason that this connector exists is mostly to allow efficient maintenance of service-specific connectors for SCIM-based services, such as xref:/connectors/connectors/com.evolveum.polygon.scim.ScimConnector/scim1-salesforce/[SCIMv1 Salesforce Connector]. Please have a look at those specific connectors or consider creating a service-specific connector in case you plan to connect to any practical SCIM server.

See also xref:/iam/iga/identity-provisioning/scim-troubles/[] page.
====


== Support

Support for this connector is limited only to standard SCIM operations.
Any non-standard SCIM operation is not supported.
As SCIM is a very vague standard, any operation where the standard is not entirely clear is also not supported.
Which makes practical applicability of this connector very limited.
Therefore we strongly recommend to consider using a service-specific connectors, such as xref:/connectors/connectors/com.evolveum.polygon.scim.ScimConnector/scim1-salesforce/[SCIMv1 Salesforce Connector] or xref:/connectors/connectors/com.evolveum.polygon.scim.ScimConnector/scim1-slack/[SCIM v1 Slack connector].

== Licensing

The connector itself is available under the terms of Apache License 2.0. To our best knowledge there is no extra license needed to use this connector. (Additional  licensing terms and conditions may apply with services on which the connector is used).

== Configuration

There are two methods of authentication supported by the connector represented by two flag values.

* Token

* Password

Choosing one or the other switches between sets of mandatory attributes.Both methods of authentication have the following mandatory attributes in common:

* Scim endpoint: the scim endpoint (e.g. /scim)

* Scim version: the scim version (e.g. /v1)

* Authentication: the authentication method (e.g. token)

The Token authentication methods mandatory values:

* Base URL: url value used to query the SCIM endpoints (protocol + hostname)

* Token: token issued by the service provider

The Password authentication methods mandatory values:

* Username: username of the user registered in the service

* Password: password of the user registered in the service

* Login url: the login url to the service

* Grant type: the service grand type

* Client ID: the client id value issued by the service provider

* Clientsecret: the client secret value issued by the service provider

== Setting up tests

The test suite consists of a bundle of test methods some of which execute a couple of times depending on the amount of tested resource endpoints. The test parameters ale provided by data providers which fetch their data from a test configuration property file. These property files are provided within the connector source bundle in the scimV1 git repository in the link:https://github.com/Evolveum/connector-scim1/tree/master/testProperties[testProperties] folder.

Before the test suite is initialized one has to provide a couple of mandatory values into the property file.The property file consists of a couple of attribute name/value pairs which are mapped to the corresponding test method or utility method. The naming rule is that the word before the underscore character (_) corresponds to the name of the test method provider which will be populated by the provided values. The word after the underscore character is the property name or in some cases it describes a resource on which a test will be executed or a type of test.

Most likely and often changed are the attributes of the test method provider configTestProvider the first three attributes configure some basic properties used in the tests:

* testNumber: The number which defines the order of the following test. The number is used as an ID value which is injected in some unique parameter values (e.g. userName). This is because some services do not delete their resource data (e.g. Account data) but they flag it as inactive or deactivated. The unique parameter value is then still used and can be in some cases referenced. This prohibits the usage of an equivalent value.

* pageSize: This parameter describes the size of the returned list of resource representations.

* pageOffset: Defines the offset used in listing resources. (e.g. I want to list 100 people but i want the list to start from the 15th entry).

The other attributes of the configTestProvider are equivalent to the configuration attributes needed to log into the service and can be seen described above in the Configuration  section.

The change of other test method provider attributes is not recommended and may result in unsuccessful tests.

The tests create one representation of each resource (e.g. user, group) and then they execute all basic methods which are defined in the scim specification. The tests also incorporate negative testing use cases for proper exception reporting. One of the test cases is intentionally commented out. To trip the InvalidCredentialException the test method makes an intentional error in the login credentials while executing an operation. For reasons of unintentional lock out of the service with the runn of this test this test is optional and you can uncomment it when you are sure no harm will be done.

== Documentation

...

== Resource Examples


== See Also

* xref:/iam/iga/identity-provisioning/scim-troubles/[]

* link:http://www.simplecloud.info/[System for Cross-domain Identity Management]