= Role LifeCycle States and Actions
:page-display-order: 300


== Lifecycle states

NOTE: IN PROGRESS

[options="header", cols="5, 10, 10, 10", width=80]
|===
| State
| Who
| What can do
| Actions/buttons

| *Draft*
| Business user. Any user who can create roles. Just his own role.
| Only local update. Playground for definition.
a|
<Set to Proposed> +
<Delete> +
<Archive>

| *Proposed*
a| Owner +
Everyone who has specific authorization for managing roles.
a| Modification of role. +
Modification does not include assignment of the role.
a| <Set to Active> +
<Review business impact> +
<Simulate application of the role> +
<Reject role creation>
<Delete>

| *Active*
a| Owner +
Everyone who has specific authorization for managing roles.
| Role is active. Standard operations with role.
a| <Set to Archived>

| *Archived*
a| Owner +
Everyone who has specific authorization for managing roles.
| Role is archived. It should not be assigned to anybody.
|

|===

Standard actions as <back> <Save> <preview changes> <Delete object> .. are available in all lifecycle states.

== Actions / Action buttons

Following actions should be available for roles during their creation and modification.

Save::
This is standard save.
In lifecycle state Draft it saves role in "Draft" state.
In this state the role can be modified only by the author himself.

Set to Proposed::
Switches role to Proposed state. In proposed state the role can be modified by multiple users.

Set to Active::
Switches the lifecycle state to "Active".
Available when the role is in "Proposed" state.
Activates the role.

Review business impact::
TODO

Simulate application of the role::
TODO

Reject role creation::
TODO


Set to Archived::
TODO

Archive::
TODO


Create copy::
Action that creates copy of the role.
Copy of the role is created in "draft" or "proposed" state. To be able to tune it and prepare for new role.
