= Identity Provisioning
:page-wiki-name: Identity Provisioning
:page-wiki-id: 14745784
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2014-04-06T20:01:41.604+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2020-02-14T19:58:34.994+01:00

Identity provisioning is a technology that synchronizes, merges and maintains many identity stores.
Parts of identity provisioning solutions may be known as synchronization, reconciliation, provisioning or even meta-directory.
Identity provisioning is a functionality of *Identity Management (IDM)* systems.
IDM does a lot of things and there are many ways how to explain it.
Choose the proper way of explaining it from the list below:

* xref:/iam/identity-management-for-dummies[Identity Management for Dummies] is suitable for system administrators, system engineers and other technology-oriented people

* xref:/iam/business-benefits-of-identity-management/[Business Benefits of Identity Management] is suitable for managers, CxOs and other business-oriented people