= Identity Management Project
:page-wiki-name: Identity Management Project

== Identity Management Is Not a Project, It Is a Program

Even though this page describes the IDM _projects_, it is important to remember that Identity Management is not a project.
Identity Management is similar to information security.
It has no beginning and no end.
It has to be implemented continually.It has to be deployed and maintained, policy definitions needs to be updated, reviewed, adjusted and so on.
All the time.
If anyone claims that "you just buy product X and it will solve all your problems" he is probably not telling the truth.
The product matters a great deal.
But no product can be deployed and then it "just runs".
It has to be continually maintained.
If you do not have the capacity to maintain it yourself then make sure you have the budget for IDM program every year.

Therefore we strongly propose to deploy the IDM in a series of iterations.
Each iteration delivers a particular quantity (features) and/or quality.
It is the first few iterations that we call _IDM project_. And undoubtedly, these iterations are the most demanding and most costly.
But the effort does not end after "the project" is finished.
It just transforms to a continuous and sustainable form.


