= Identity Governance and Administration
:page-keywords: [ 'IGA' ]
:page-visibility: hidden

== Identity Governance and Administration Capabilities

=== Identity Lifecycle Management

Alternative names: Lifecycle management, Identity lifecycle

TODO: Maintaining digital identities.
TODO: management of attributes, identifiers (e.g. lookup of unique username)
TODO: credential management?
TODO: identity types/classes/archetypes: person and non-person identities
users, services/applications, devices, things, ...

TODO: lifecyle: creation -> active -> archival -> deletion
Mention pre-provisioning, delayed delete, data erasure, etc.

Administration GUI

common operation modes: B2E, B2B, B2C

Personas

TODO: orgstruct?

=== Entitlement Management

Association between identities and entitlements

Who has access to what - on a low system level: accounts, groups, permissions, system roles (entitlement catalog)

TODO: Are bussiness roles "entitlements"?

=== Fulfillment

Alternative names: Provisioning/deprovisioning

Propagation of changes to target systems.

provisioning dependencies
attribute mapping, type conversions
error handling, retries
provisioning scripts

Automatic or manual.
Semi-manual.

Connectors

=== Synchronization

Synchronization, reconciliation, orphaned account detection

Inbound synchronization, correlation (identity matching)
Connecting new systems with existing data.

Eventual consistency (no transactions), discovery

Synchronization of non-person identities: (application) roles, organizational units, services

Connectors

=== Policy and Role Management

Alternative names: Role management, Role governance, Role modeling, Role lifecycle management, Policies

Role definitions, hierarchies, maintenance.
Role types: application, technical, business.

Rules, automatic assignment of roles and entitlements.

Maintenance of role definitions (role ownership/curation)

Role catalog (maintenance, not presentation to end users).

SoD

Delegated administration, deputies (usually based on organizational management)

Role lifecycle management (modeling) vs RBAC

Role models, versioning, approvals, lifecycle
Role decommissioning process
Role re-certification

Compliance policies.

Initiating remediation, opening cases (but not management/communication on cases)

(application) role synchronization

=== Access Requests

Requesting roles and entitlements
User-friendly GUI (e.g. shopping cart)
Presenting roles in user-friendly way (role catalog)

=== Identity Workflow Automation

Alternative names: Workflow, Identity workflow management

Approvals, escalations, notifications
Dynamic approval schemes, multi-level approvals, optional approvals, risk-sensitive approvals.

Process-based and policy-based approvals

Internal workflow, integration with workflow engines, enterprise workflow.

Case management: maintaining the case, communication, cooperation

Manual remediation

Sometimes: manual fulfilment

=== Access Certification

Alternative names: Re-certification, Attestation

Review and (re)certification of access by (business) managers. Removal of excessive entitlements, principle of least privilege.

Manual action. Need to make many decisions quickly and efficiently.
Distribution of labor.

Re-certification of role definitions.

Campaigns, ad-hoc (microcertification).

=== Auditing

Keeping track of operations (business level). Accountability. Metadata?

Note: Sometimes includes sync/recon and remediation.

=== Identity Analytics and Reporting

Alternative names: Identity analytics and intelligence (IdA)

Risk assessment, reporting, risk-based approach

Excessive access, outliers, identify over-privileged users

Simulation, visualization.

Compliance reporting.

Role mining

== Generic Mechanisms and Infrastructure (TODO)

* Attribute mapping, expressions

* customization mechanisms (e.g. GUI customization)

* Schema management

* Logging and Diagnostics

* Services (API) and integration (e.g. SSO clients)

* Identity connectors

== Related Capabilities

* RBAC/ABAC - evaluation/enforcement

* Organizational structure management (business side, from book)

* Data protection, provenance
