= Identity Governance and Administration
:page-keywords: [ 'IGA' ]
:page-visibility: hidden

// TODO: IGA high-level architecture

== Identity Governance and Administration Capabilities

NOTE: This list of capabilities is based on terminology widely established in the industry.
Although there are numerous ambiguities, we preferred established terms over re-inventing the terminology.
We are pointing out the ambiguities in the description as needed.

=== Identity Lifecycle Management

Alternative names: Lifecycle management, Identity lifecycle

Identity lifecycle management deals with maintenance of digital identities.
It maintains state of digital identities through various lifecycle changes, such as creation, modification, archival and deletion.
Digital identities are usually complex data structures, composed of numerous attributes.
The structure of identity data and its relationship with other identity-related objects is specified by an _identity model_.
Identity lifecycle management is responsible for maintaining _identity model_, keeping the attributes structured and consistent.
This includes management of identifiers, including creation and validation of unique identifier values.
Identity lifecycle management may include management of _credentials_, such as passwords and multi-factor authentication cryptographic material.

Lifecycle state model is often used to manage identity lifecycle.
An identity is transitioned through a set of _lifecycle states_ such as `candidate`, `active`, `deprecated` and `archived`.
Identity lifecycle is often bound to policies and fulfilment actions, creating functionality such as pre-provisioning of accounts for new employee, delayed delete of accounts, erasure of data on archival due to data protection regulations, and so on.

IGA systems deal with many identity _types_ (a.k.a. _classes_ or _archetypes_).
The most important identity types are usually person identities, such as employees, students, customers and citizens.
However, comprehensive IGA systems must routinely deal with non-person identity types as well, such as services, applications, organizations, devices and "things".
Each identity type may have its own characteristics, such as attributes, policies and lifecycle states.
Such variation is used to implement various operation modes, such as business-to-employee (B2E), business-to-business (B2B) or business-to-consumer/citizen (B2C).

Complex identity models may include concept of _personas_, an alternative representation of a person designed for use in a specific context.

Partial management of organizational structure may be included in identity lifecycle management.
Although organizational structure management is not a responsibility of identity governance and administration per se, policies are often bound to organizational structures.
In such case, IGA systems must be able to process organizational structures to be able to evaluate the policies.
Even though the depth of organization structure management required by IGA systems is, in theory, very shallow, practical IGA deployment often need to go much deeper than expected (see notes below).

Identity lifecycle management almost always includes administration user interface, allowing identity administrators to review identities managed in the system, or even manage them manually.
Self-service interface for ordinary users is usually also present, providing means for a user to maintain parts of user profile.

There are some IGA features related to the identity lifecycle, features that require cooperation of several capabilities.
Identity merge/split is related to the synchronization/correlation capability, however it may require support from workflow capability.
Similarly, progressive profiling, self-service registration, invites and similar capabilities require parts of workflow capability, or a special-purpose interface.

=== Entitlement Management

Entitlement management deals with association between identities and entitlements.
Entitlements are assigned to an identity, giving an identity access to a particular asset or an operation.
These are usually groups, permissions, associations to access control lists, low-level system roles and so on.
Simply speaking, entitlement management deals with a question: Who has access to what?

Entitlement management usually works on a lower level, it deals with concepts related to applications, services and directories, such as groups, filesystem permissions and application privileges.
There is an ambiguity whether high-level concepts such as _business roles_ are subject of entitlement management, or whether they are part of a policy that drives entitlement management.
Strictly speaking, in IGA context, a business role does not specify _who has access to what_, it rather specifies _who should have access to what_.
Therefore, business roles are closer to the _policy_ (what _should be_) rather than operational reality (what _is_).
Nevertheless, interpretation and implementation of the concepts of _roles_ and _entitlements_ varies from system to system.

Similarly, there is an ambiguity in the depth of details the entitlement management is concerned with.
For example, it is not clear whether entitlement management is concerned with the name and format of an an attribute that associates LDAP group to LDAP account, or weather this is a responsibility of fullfilment capability.
Strictly speaking, fulfilment is concerned with a propagation of changes to target systems, and group membership is often an information source.
Therefore we consider management of association attributed to be a responsibility of entitlement management.

In comprehensive IGA deployments, entitlements can themselves be identities and vice versa.
E.g. user's membership in an organization, in which organization (identity) is considered an entitlement when assigned to a user.
On the other hand, a role (entitlement) can be considered an identity, for example in a case that it is automatically synchronized with LDAP group or an application role.

=== Fulfillment

Alternative names: Provisioning/deprovisioning, Change propagation

Simply speaking, fulfilment is a capability that deals with propagation of changes to target systems.
Fulfilment creates, modifies and deletes user accounts.
Strictly speaking, this capability fulfils the policy, e.g. by creating an account when such an account is mandated by the policy.
However, fulfilment often needs to read and compare the data in addition to create, modify and delete operations.
This creates a significant overlap with other capabilities, namely entitlement management and synchronization.
Moreover, attribute schema management, interpretation and transformation of attribute values and other functions are required for almost every IGA capability as well as they are required for fulfilment.
Therefore we will be using the term _fulfilment_ to mean all the necessary low-level functions that deal with target and source systems, we will not limit the fulfilment to mere propagation of changes.

The desired implementation of fulfilment is almost always _automatic fulfilment_.
In that case the changes are made to target system automatically, by a connector on an agent that executes the commands of an IGA system.
This is quite obviously the most convenient and reliable method.
However, development and maintenance of a connector or an agent may be quite demanding.
Some target systems may not even provide required capabilities in a form of re-usable programming interface (API).
Therefore, the deployments sometimes opt for _manual fulfilment_.
In that case the change is executed by a human operator, driven by a request from an IGA system.
IT service management (ITSM) systems are often used to deliver instructions to the operator, and to track the progress of the task.
While the manual fulfilment is usually practical and very cost-efficient solution, it has major drawbacks.
As an IGA system cannot reach the target system, it cannot make sure that the account was created correctly, or even more importantly, that the privileges were correctly removed or account deleted.
This creates a serious security issue.
Therefore, some IGA systems provide an option for _semi-manual fulfilment_.
In that case the operations are executed by a human operator.
However, there is process to periodically export the data from the target system and deliver them to IGA platform for inspection.
IGA platform identifies any inconsistencies, and creates tasks for operators to remedy the situation.

Automatic fulfilment is usually implemented using _identity connectors_.
Connectors are relatively small bundles of code, implementing the details of network communication with the target system.
Connectors are using standardized network protocols or interfaces (APIs) to communicate with target system, whenever such protocols or interfaces are available.
Some IGA platforms are using _agents_ instead of connectors.
Agents are installed into the environment of the target system, communicating with the target system locally.
Agents are usually more powerful than connectors, however, they usually create a significant maintenance burden.

Apart from connector management, the fulfilment capability includes significant amount of error handling functionality.
Protocols and interfaces provided by target systems significantly vary as to their capabilities.
E.g. some systems can disable accounts, other cannot.
Some systems can delete an account, other can only permanently disable it.
Some of these details can be addressed in the connector code.
However, many details and edge cases have to be addressed by the fulfilment components.
For example, the fulfilment usually need to simulate capabilities that the target systems do not have, such as simulation of account disable by disabling/changing the credentials.
Error handling is an important part of the functionality, e.g. making sure that an operation is re-tried in case of network failures.
Error handling code is often very complex, as there are numerous interactions with other capabilities, especially synchronization, entitlement management and the policies.

Fulfilment components usually provide additional functionalities, such as ability to execute scripts on target systems.
Such functionality is often used to complete account provisioning, or it is used to archive filesystem data in case of account archival.

=== Synchronization

Alternative names: Reconciliation, Correlation

Synchronization capability provides functions that keep identity data consistent across all the connected systems.
While fulfilment can make sure that the account is created in accord with the policy, it is synchronization that makes sure that it stays compliant with the policy all the time.
This makes synchronization perhaps the most important infrastructural capability of any IGA platform.

Synchronization also provides the means to feed data into the IGA platform.
There is often at least one authoritative data source, in enterprise scenarios usually provided by the human resource (HR) system.
Such data source provides authoritative information regarding legal data and employment status of a user.
However, comprehensive IGA deployments need much more data than just the basic information provided by the HR system.
Therefore, even in relatively simple deployments there are often many data sources with varied levels of authoritativeness.
Such data sources often provide additional details, such as contact information, organizational structure assignment and so on.
Several data feeds are often used to populate IGA platform with data on non-person identities, such as organizational structure, partner organizations, security tokens, devices and "things".
Such "automatic" data sources are often supplemented with data that are maintained manually, usually maintained in form of spreadsheets and manually imported into the IGA system.
It is not unusual that some identity types are maintained manually in an IGA platform as an authoritative source.

There are usually several sources feeding data to IGA system.
Each of the sources is likely to have its own schema, data formats, codes and other specific characteristics.
Such a diverse data need to be mapped and transformed into a form consistent with the identity model of the IGA system.
Moreover, records that describe the same identity have to be _correlated_ and merged.
Correlation is not a completely reliable process, even in enterprise scenarios where some correlation identifiers (such as employee number) are readily available.
The source data were most likely maintained manually, there is relatively high probably of data errors and inconsistencies.
As the IGA system is the system where the data meet for the first time, it is likely that there will be correlation failures and mis-matches that need to be handled manually.
Correlation is even harder in case there is no reliable correlation identifier, or if there are several semi-reliable correlation attributes.
Probabilistic correlation (a.k.a. _identity matching_) can be used in that case.
However, such correlation almost always requires human intervention, resulting in semi-automatic process.
Most of the correlation effort is expected at the time when IGA platform is deployed, or when a new system is connected to IGA platform.
However, the source data are changing all the time, user groups grow and fluctuate.
Therefore identity correlation is a continuous process, a part of day-to-day identity management routine.

There are two fundamental model of continuous data feed from data sources to IGA system:

* *Pull model* (polling): IGA platform is periodically polling for new data.
For example, IGA system may be looking for database rows that were changed since the last poll.
Polling intervals are relatively short, usually in order of minutes.
Therefore, this approach can provide "near-real-time" synchronization, which is sufficient for many common cases.
Pull-based synchronization is usually simple to deploy and maintain, as long as there is a suitable change identifier (change serial number, timestamp, sequence number or similar).
However, there is an inherent synchronization delay (polling interval).
Also, the source system need to keep additional state (change timestamps, change log or similar).
Perhaps the most painful drawback of pull-based mechanisms is detection of deleted objects.
This especially impacts timestamp-based polling mechanisms, where objects are deleted without a trace.
Timestamp-based polling mechanism cannot detect deleted objects in such cases.

* *Push model* (messaging): Source system is actively notifying IGA platform about data updates.
Message-based systems are often used to implement push-based synchronization feeds.
Such feeds can provide synchronization that is very close to real time, given that the circumstances are ideal (low volume of changes, fast processing of changes).
Moreover, push-based synchronization allows moving of state-keeping functions to a dedicated intermediary (message broker), de-coupling source system from IGA platform.
However, this approach usually adds additional components and indirection into the data pathway, increasing complexity of the solution.
It is not clear whether synchronization based on message brokers is an advantage, as it still does not cover all the border cases of message loss (e.g. full message queue, bugs, misconfiguration).
The sender (source system) and/or the receiver (IGA platform) still need additional mechanisms for full reliability of message-based communication.

Clearly, there is no single universal and reliable synchronization mechanism.
The situation needs to be considered on case-by-case basis, which complicated IGA deployments.

Synchronization is meant to enforce continuous consistency of data in all the connected systems.
However, this task is much harder than it may seem.
IGA platform is interconnecting several _independent_ systems, each of them maintaining a database with various data models, access protocols, operational characteristics and consistency constraints.
There is no universal mechanism that can be used to make sure that the data remain consistent even during one simple operation.
Transactional mechanism can be used only for some systems (usually relational databases), and even there the details vary significantly to make such mechanism all but useless for universal cross-system data consistency.
Many systems are based on REST interfaces (APIs), and not provide any data consistency guarantees at all.
The data may change shortly after an operation is completed, or even during execution of an operation.
In such environment, short-term data consistency is definitely a significant challenge.
Long-term data consistency is a colossal task.

Most IGA platforms seem to acknowledge the reality and adopt an _eventual consistency_ approach.
In this paradigm, the data may be inconsistent at some point in time, yet the data will become consistent eventually.
Eventual consistency is achieved by a combination of several mechanisms, while _reconciliation_ is perhaps the most widespread and universal one.

_Reconciliation_ is a process of comparing data stored in IGA platform with the data in target systems.
There are various forms of reconciliation.
The most lightweight reconciliation processes simply look at account existence, ignoring all the attributes and entitlements.
The most heavyweight processes are running a full policy evaluation for each user, checking account status, all the attribute values and entitlements.
All forms of reconciliation can usually detect _orphaned accounts_.
Orphaned accounts are accounts that do not have matching identity in IGA database.
These are usually accounts that should have been deleted, but remained in the system.
The account was not deleted due to human error, because of a bug in the connector code, it might have been manually created by system administrator, perhaps as a testing account, it may be an artefact of disaster recovery, restoring data from an older back-up, or there may be numerous other reasons that the account was overlooked.
Orphaned accounts are often a major security risk, therefore detection and clean-up of orphaned accounts is a critical functionality of IGA deployment.
However, detection of orphaned accounts alone is not sufficient to maintain continuous security level.
Reconciliation have to detect wrong account status, wrong attribute values and wrong entitlements to maintain data consistency and hence security.
This can be achieved by full reconciliation process that checks consistency of information end-to-end: from the data sources, through the IGA platform, all the way to the target systems.
Full reconciliation is a demanding, slow and long-running process.
Yet it is a necessary process.
Full reconciliation is usually the only practical mechanism to make sure that the data are consistent, and remain consistent in the long term.
It should be running periodically.

Reconciliation is often seen as an "auditing" mechanism, making sure that the accounts were provisioned correctly and checking for orphaned accounts.
However, reconciliation is much more than that.
Reconciliation is an essential data consistency mechanism, it is critical for correct operation of the entire IGA platform.
Reconciliation has to be used both on _target_ as well as _source_ sides of the data flows.
As "real-time" synchronization mechanisms are unreliable, reconciliation of data sources is the only practical way to make sure that IGA works with fresh and valid data.
All in all, reconciliation is a crucial failsafe mechanism.
It should be used for all systems and data feeds connected to IGA platform.

Synchronization is an essential tool especially at times when there is a need to connect new system to IGA platform.
New system is likely not to be that new after all.
The system may be running for years, before it is connected to IGA platform.
Therefore there are almost always existing data in the system, that needs to be correlated and reconciled with the data in the IGA platform.
Synchronization is the right tool for this job.
It may look like this functionality will not be needed too often.
However, the reality is quite different.
New systems are added and decommissioned all the time, especially in the era of flexible cloud services.
Synchronization capabilities are used more often than expected, through all the lifetime of IGA deployment.

Synchronization is not just about receiving data feed and comparing data in long-running reconciliation processes, it is an essential capability permeating the entire IGA platform.
Synchronization events may be triggered by unexpected "discoveries" made by IGA platform.
For example, IGA platform may try to modify an account, however the account is no longer there.
Or perhaps the IGA platform tries to create an account, and discovers that an unknown account with a conflicting identifier is already created.
Situation such as these may trigger ad-hoc synchronization events, often leading to automatic remediation of the situation.

Identity management is no longer just about users and accounts.
There are numerous identity types, many of them are non-person identities such as (application) roles, organizational units and services.
Synchronization must be able to handle such identities in much the same way as it handles person identities.
In a slightly counter-intuitive way, non-person identities are often synchronized _from_ systems that are traditionally considered to be _target_ systems.
E.g. IGA platform may automatically create application role for each Active Directory group, allowing proper governance of the privilege (access requests, ownership, certification).
This means that a traditional role of _source_ and _target_ systems is no longer strictly separated, mixed approach is becoming a norm.

Synchronization capability is often implemented by using _identity connectors_, the same connectors that are used for fulfilment.
This makes perfect sense, as the synchronization mechanisms and protocols depend on the systems that we are connecting to.

Synchronization is often an overlooked capability.
It is usually dismissed by the analysts, included in fulfillment or "auditing" without any deeper interest.
This may make sense from the business point of view, as synchronization is often hidden.
When synchronization operates correctly, it is almost entirely invisible to the users.
However, the reality cannot be made invisible, it will always hit back.
Synchronization is essential for reliable operation of all connected systems, and it is absolutely critical for information security.
Synchronization cannot be an after-thought, a mere extension to the IGA platform.
It has to be built into the very core of the platform, as it permeates everything.

=== Policy and Role Management

Alternative names: Role management, Role governance, Role modeling, Role lifecycle management, Policies

Role definitions, hierarchies, maintenance.
Role types: application, technical, business.

Rules, automatic assignment of roles and entitlements.

Maintenance of role definitions (role ownership/curation)

Role catalog (maintenance, not presentation to end users).

SoD

Delegated administration, deputies (usually based on organizational management)

Role lifecycle management (modeling) vs RBAC

Role models, versioning, approvals, lifecycle
Role decommissioning process
Role re-certification

Compliance policies.

Initiating remediation, opening cases (but not management/communication on cases)

(application) role synchronization

=== Access Requests

Requesting roles and entitlements
User-friendly GUI (e.g. shopping cart)
Presenting roles in user-friendly way (role catalog)

=== Identity Workflow Automation

Alternative names: Workflow, Identity workflow management

Approvals, escalations, notifications
Dynamic approval schemes, multi-level approvals, optional approvals, risk-sensitive approvals.

Process-based and policy-based approvals

Internal workflow, integration with workflow engines, enterprise workflow.

Case management: maintaining the case, communication, cooperation

Manual remediation

Sometimes: manual fulfilment

=== Access Certification

Alternative names: Re-certification, Attestation

Review and (re)certification of access by (business) managers. Removal of excessive entitlements, principle of least privilege.

Manual action. Need to make many decisions quickly and efficiently.
Distribution of labor.

Re-certification of role definitions.

Campaigns, ad-hoc (microcertification).

=== Auditing

Keeping track of operations (business level). Accountability. Metadata?

Note: Sometimes includes sync/recon and remediation.

=== Identity Analytics and Reporting

Alternative names: Identity analytics and intelligence (IdA)

Risk assessment, reporting, risk-based approach

Excessive access, outliers, identify over-privileged users

Simulation, visualization.

Compliance reporting.

Role mining

== Generic Mechanisms and Infrastructure (TODO)

* Attribute mapping, expressions

* customization mechanisms (e.g. GUI customization)

* Schema management

* Logging and Diagnostics

* Services (API) and integration (e.g. SSO clients)

* Identity connectors

== Related Capabilities

* RBAC/ABAC - evaluation/enforcement

* Organizational structure management (business side, from book)

* Data protection, provenance
