= Identity and Access Management
:page-wiki-name: Identity Management
:page-wiki-id: 4424181
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2012-06-27T11:33:00.870+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2020-02-14T19:51:06.952+01:00
:page-display-order: 50
:page-upkeep-status: yellow

_Identity and access management (IAM)_ is a set of information technologies that deal with identities in the cyberspace.
There are authentication mechanisms, directory services, authorization systems, access control models, federations, agents, repositories, attributes, claims, certificates, lifecycles, rules, processes, policies and other exotic life forms.

IAM is a broad and diverse set of technologies, some of them are interwoven into an _identity fabric_, others are pretty much stand-alone.
Usually, there are several (incompatible) mechanism to address each problem, except for some problems that seem to be not addressed at all.
Overall, identity and access management is _complex_.
It is a labyrinth of technologies and methods, a letter soup of acronyms referring to inconsistent terminology.
Check out our xref:/glossary/[glossary] to see for yourself.

However, even the most complex labyrinth can be safely navigated by those armed with knowledge.
This part of Evolveum documentation site is dedicated to explanation of IAM concepts, technologies and methods.

== Identity Governance and Administration

xref:/iam/iga/[_Identity governance and administration (IGA)_] is a subfield of identity and access management (IAM) dealing with management and governance of identity-related information.
Simply speaking, IGA deals with all the details concerning maintenance of identity information, ranging from low-level technical details to high-level business policies.

As https://evolveum.com/[Evolveum] is a creator of xref:/midpoint/[midPoint], a powerful IGA platform, it is perhaps no surprise that this site is mostly focused on xref:/iam/iga/[IGA].
There is an entire xref:/iam/iga/[section dedicated to IGA], explaining fundamental principles and providing useful details.

See xref:/iam/iga/[_Identity Governance and Administration_ section] for more details.

== Myths and Best Practice

Being such a complex field, identity and access management (IAM) is a perfect spawning ground for questionable practices.
There are many xref:/iam/myths/[myths and anti-patterns] that seem to be all right at the first sight.
However, they usually end up as very expensive problems.
These practices are so common, that we have dedicated a xref:/iam/myths/[section of this site] to describe them.
There is also a section describing xref:/iam/best-practice/[best practices].

== See Also

* xref:/iam/iga/[]
* xref:/iam/myths/[]
* xref:/iam/best-practice/[]
