---
layout: personal
job-title: AI/ML Developer
photo: photo_new.jpg
academic-titles: Ing (MSc)
profile-github: tchrapovic
profile-linkedin-url: https://www.linkedin.com/in/tade%C3%A1%C5%A1-chrapovi%C4%8D-5959bb265/
---

= Tadeáš Chrapovič

== Short Bio

Graduated from the Technical University of Kosice with a master degree in the study programme of Computer Modelling in the study field of Computer Science.
He started as a Java developer at Evolveum, recently focusing on AI/ML.
His expertise covers the areas of AI/ML, Java, Software Development, Identity Management, and Data Analytics.

== Education

* Inžinier (Ing., master) degree from https://www.tuke.sk/[Technical University of Kosice]

== Publications and Talks (selection)

link:https://docs.evolveum.com/talks/files/2024-09-role-mining.pdf[Role Mining in MidPoint (Transformative Access Governance)]::
link:https://evolveum.com/role-mining-in-midpoint-webinar-summary/[Webinar Summary Blog]::
2024, Evolveum Webinar

Role Mining::
link:https://tiime-unconference.eu/[TIIME Unconference]::
link:https://evolveum.com/evolveums-journey-to-the-tiime-unconference-midpoint-working-group/[TIIME Unconference Summary Blog]::
2024, MidPoint Working Group Copenhagen

== Project Participation (selection)

xref:/midpoint/[MidPoint]::
since 2022, role mining and outlier detection - AI/ML developer

xref:/midpoint/[MidPoint]::
since 2020, software developer

https://github.com/tchrapovic/thesis[Methods of Determining the Reproduction Number in Epidemiology]::
2022, final thesis for master degree

https://github.com/tchrapovic/thesis[Epidemiological Models]::
2020, final thesis for bachelor degree
