= Development Environment Setup
:page-wiki-name: Development Environment Setup
:page-wiki-id: 2654445
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2011-08-08T17:35:32.083+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2014-01-09T13:10:50.422+01:00
:page-upkeep-status: red
:page-upkeep-note: Java 7 ? rly?

== Requirements

You will need:

* Java Development Kit (JDK) 7

* Maven 3

* Tomcat 6 or 7

* IDE


== Installation (Linux)


=== Java

. Install JDK with command[source]
----
sudo apt-get install sun-java7-jdk
----


. Check environment variable JAVA_HOME (should be path to JDK, e.g. */usr/lib/jvm/java-7-sun*)[source]
----
echo $JAVA_HOME

----




==== Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 7

The development environment and midPoint in runtime also requires JCE for cryptographic operations.
You can download it from link:http://www.oracle.com/technetwork/java/javase/downloads/jce-6-download-429243.html[Oracle downloads page]. After downloading zip file follow installation instructions written in README.txt


=== Maven

. Install Maven 3 from repository[source]
----
sudo apt-get install maven3

----



. Check environment variable M2_HOME (should be path to Maven directory, e.g. */usr/share/maven3*)[source]
----
echo $M2_HOME
----




== Tomcat

. Download binary distribution of Apache Tomcat 6.x or 7.x from link:http://tomcat.apache.org/download-60.cgi[http://tomcat.apache.org/download-70.cgi]

. Unpack it into folder where you want to have your tomcat installation, e.g. */opt/apache-tomcat-6.0.32*


== IDE (Eclipse, Idea)

* wiki:How+to+start+with+Eclipse[How to start with Eclipse]

* wiki:How+to+start+with+IntelliJ+IDEA[How to start with IntelliJ IDEA]

* NetBeans should work as well, but we haven't tried to use it for years (since Oracle happened).
If you have any information about midPoint in NetBeans please let us know.


== See Also

* wiki:Source+Code[Source Code]

* wiki:How+to+start+with+Eclipse[How to start with Eclipse]

* wiki:How+to+start+with+IntelliJ+IDEA[How to start with IntelliJ IDEA]