= IGA Capability: Access Certification
:page-nav-title: Access Certification
:page-display-order: 170
:page-keywords: [ 'IGA' ]
:page-upkeep-status: green
:page-visibility: hidden

== Alternative names

* Re-certification

* Attestation

== Access Certification Functions

* *Full certification campaign*.
Broad sweep, distribution of work, scheduling, duration control.

* *Microcertification*.
TODO
Triggers.

* *Certification of role definitions*.
TODO

== Overview

Access privileges have a tendency to grow and accumulate.
There are many ways to efficiently grant a privilege: formal _access request_ processes, privileges are granted manually by system administrators and various informal side channels.
However, privilege accumulation is a risk, as people often keep their privileges forever.
Access certification is a process to remove privileges that are no longer necessary.
During access certification process, responsible persons must _certify_ that users still need the privileges that were granted to them.

Certification is a process designed to counter-act ad-hoc assignment of roles.
Whether the roles were assigned by a formal _access request_ process, or they were assigned manually by an uncontrolled process, they all need to be certified eventually.
Otherwise, the number of roles assignments will grow out of control, and with the number of role assignments the overall risk grows too.
Certification is perhaps the only practical mechanism that can limit the risk posed by ad-hoc role assignments.

However, there are typically many ad-hoc role assignments in a typical organization, and especially in a dynamic enterprise environment where the situation changes frequently.
Therefore, certification processes must be designed to handle a large number of decisions very efficiently.
Simply re-running the approval processes will not work.
There would be too many approvals to make, too many clicks in too many dialogs.
Therefore, certification user interfaces are designed specifically for the purpose of making a lot of decisions very quickly, usually in one user interface dialog.

Certification decisions are almost always made by (business) managers, usually by direct manager of the user whose access is certified.
Direct manager usually has the best overview of the job that a user does, which also means there is a good chance that the manager can spot roles that the user no longer needs.
This approach has an additional effect of distributing the certification effort among many certifiers, thus reducing the overall time needed to complete the certification.

There are usually two types of certification:

* *Certification campaigns* aim at certification of all the roles (other other "access") that a large group of users have.
This is a "mass" action, with many decisions that need to be made by many certifiers in a relatively short time interval.
The users are divided to groups, usually according to organizational structure.
Certification work is distributed to many certifiers, usually managers of organizational units.
The campaign has a fixed duration, usually in order of weeks.
Campaigns are usually repeated based on a regular schedule (e.g. annually).

* *Microcertifications*, also known as _triggered certification_ or _ad-hoc certification_.
This is usually certification of role assignments of access granted to a single user, done by a single certifier.
Microcertification is often triggered by significant events in the identity lifecycle, such as change of organizational assignment of the user.
In that case the new manager of the user has to certify user's role assignments, as the new manager assumes some form of responsibility for user's actions.
Microcertifications can also be triggered by other events, such as overall risk of user's entitlements growing above a specified threshold, detection of a user as an _outlier_, or even a completely random selection aimed at mapping the state of role assignments.

Certification campaigns are systematic, broad-scale solution that has a good potential to address privilege accumulation problem.
However, it is quite difficult to use certification campaigns well.
Certification campaigns require many decisions to be many by many people, resulting in huge overall effort.
Common recommendations in the past were to conduct full certification campaign annually, or even twice a year.
However, the more frequent the campaigns are, the less likely it is to detect excessive role assignments.
If certification campaigns are considered "boring necessary paperwork", the certifiers are likely to certify everything without too much thinking, just to get it done.
Therefore, frequent large certification campaigns can produce completely useless results.

Current certification recommendations favor smart use of microcertifications instead of frequent certification campaigns.
Microcertifications of a single user should be triggered by important lifecycle events, such as change of organizational assignment.
Even more importantly, certifications should be risk-based, triggering microcertification or small certification camp of users that pose higher risk, or users that have unusual combination of access rights (a.k.a. _outliers_).
Smart use of smaller certifications does not eliminate the need for full certification campaigns.
However, it allows to dramatically reduce the frequency of these costly and painful campaigns.

Role structure significantly influences certification effort.
Good role engineering results in well-specified business roles, with high degree of re-use.
This means that a typical user will have just a couple of business roles, that are relatively easy to certify.
On the other hand, poor role engineering means that large number of application roles is assigned directly to users.
This means that a typical users will have tens, or even hundreds of roles.
The result is a huge certification effort, and a very low quality of certification result.
Such situation often results in cases where _access request_ process is over-used, where business role engineering and maintenance is neglected and the users often request the same set of roles as their colleagues.
Such approach inevitable leads to an unmaintainable, and hence insecure system.

Despite good role engineering and smart use of microcertifications, certification is always time-consuming and somehow painful activity, with questionable results, that are very difficult to quality-control.
Similarly to _access request_ process, _certification_ IS necessary component of almost every comprehensive IGA deployment.
However, it is more than desirable to keep both of these to a necessary minimum.
The more roles, entitlements and privileges are assigned (and hence unassigned) automatically, the less need for _access request_ and _certification_ effort.
There is also less room for errors, much more visibility and hence less residual risk.
Therefore, the primary goal of IGA deployment should be as much automation of role assignments as practically possible.

// TODO: Variations: Re-certification of role definitions.

// TODO: summary
Goal: Removal of excessive entitlements, principle of least privilege.
Certification is must have, in case that access request (or similar) process is used.

== Notes

Certification and ABAC.
Theory: certify attribute values, practice: problem

Certification and AI
