= IGA Capability: Entitlement Management
:page-nav-title: Entitlement Management
:page-display-order: 110
:page-keywords: [ 'IGA' ]
:page-upkeep-status: green
:page-visibility: hidden

Entitlement management deals with association between identities and entitlements.
Entitlements are assigned to an identity, giving an identity access to a particular asset or an operation.
These are usually groups, permissions, associations to access control lists, low-level system roles and so on.
Simply speaking, entitlement management deals with a question: Who has access to what?

Entitlement management usually works on a lower level, it deals with concepts related to applications, services and directories, such as groups, filesystem permissions and application privileges.
There is an ambiguity whether high-level concepts such as _business roles_ are subject of entitlement management, or whether they are part of a policy that drives entitlement management.
Strictly speaking, in IGA context, a business role does not specify _who has access to what_, it rather specifies _who should have access to what_.
Therefore, business roles are closer to the _policy_ (what _should be_) rather than operational reality (what _is_).
Nevertheless, interpretation and implementation of the concepts of _roles_ and _entitlements_ varies from system to system.

Similarly, there is an ambiguity in the depth of details the entitlement management is concerned with.
For example, it is not clear whether entitlement management is concerned with the name and format of an an attribute that associates LDAP group to LDAP account, or weather this is a responsibility of fullfilment capability.
Strictly speaking, fulfilment is concerned with a propagation of changes to target systems, and group membership is often an information source.
Therefore we consider management of association attributed to be a responsibility of entitlement management.

In comprehensive IGA deployments, entitlements can themselves be identities and vice versa.
E.g. user's membership in an organization, in which organization (identity) is considered an entitlement when assigned to a user.
On the other hand, a role (entitlement) can be considered an identity, for example in a case that it is automatically synchronized with LDAP group or an application role.

== See Also

* xref:/iam/iga/[]
