= Identity Governance and Administration
:page-keywords: [ 'IGA' ]
:page-toc: top
:page-upkeep-status: green
:page-visibility: hidden

// TODO: IGA high-level architecture

== Identity Governance and Administration Capabilities

NOTE: This list of capabilities is based on terminology widely established in the industry.
Although there are numerous ambiguities, we preferred established terms over re-inventing the terminology.
We are pointing out the ambiguities in the description as needed.

=== Identity Lifecycle Management

Alternative names: Lifecycle management, Identity lifecycle

Identity lifecycle management deals with maintenance of digital identities.
It maintains state of digital identities through various lifecycle changes, such as creation, modification, archival and deletion.

xref:lifecycle.adoc[Read more ...]

=== Entitlement Management

Alternative names: Group management, Privilege management

Entitlement management deals with association between identities and entitlements.
Entitlements are assigned to an identity, giving an identity access to a particular asset or an operation.
These are usually groups, permissions, associations to access control lists, low-level system roles and so on.
Simply speaking, entitlement management deals with a question: Who has access to what?

xref:entitlement-management.adoc[Read more ...]

=== Fulfillment

Alternative names: Provisioning/deprovisioning, Change propagation

Simply speaking, fulfilment is a capability that deals with propagation of changes to target systems.
Fulfilment creates, modifies and deletes user accounts.
Strictly speaking, this capability fulfils the policy, e.g. by creating an account when such an account is mandated by the policy.

xref:fulfillment.adoc[Read more ...]


=== Synchronization

Alternative names: Reconciliation, Correlation

Synchronization capability provides functions that keep identity data consistent across all the connected systems.
While fulfilment can make sure that the account is created in accord with the policy, it is synchronization that makes sure that it stays compliant with the policy all the time.
This makes synchronization perhaps the most important infrastructural capability of any IGA platform.

xref:synchronization.adoc[Read more ...]

=== Policy and Role Management

Alternative names: Role management, Role governance, Role modeling, Role lifecycle management, Policy management

The heart of identity governance is about the policies.
Policies specify how things _should_ be, what is the ideal state of all the systems and data.
As organizations and regulations tend to be quite complex, policies are often complex too.
Moreover, policies tend to change in reaction to changed regulations or organizational needs.
All of that makes policy management quite a challenging thing to do.

xref:policy-and-role-management.adoc[Read more ...]

=== Access Requests

Requesting roles and entitlements
User-friendly GUI (e.g. shopping cart)
Presenting roles in user-friendly way (role catalog)

=== Identity Workflow Automation

Alternative names: Workflow, Identity workflow management

Approvals, escalations, notifications
Dynamic approval schemes, multi-level approvals, optional approvals, risk-sensitive approvals.

Process-based and policy-based approvals

Internal workflow, integration with workflow engines, enterprise workflow.

Case management: maintaining the case, communication, cooperation

Manual remediation

Sometimes: manual fulfilment

=== Access Certification

Alternative names: Re-certification, Attestation

Review and (re)certification of access by (business) managers. Removal of excessive entitlements, principle of least privilege.

Manual action. Need to make many decisions quickly and efficiently.
Distribution of labor.

Re-certification of role definitions.

Campaigns, ad-hoc (microcertification).

=== Auditing

Keeping track of operations (business level). Accountability. Metadata?

Note: Sometimes includes sync/recon and remediation.

=== Identity Analytics and Reporting

Alternative names: Identity analytics and intelligence (IdA)

Risk assessment, reporting, risk-based approach
Alternative names: Role management, Role governance, Role modeling, Role lifecycle management, Policy management

Excessive access, outliers, identify over-privileged users
The heart of identity governance is about the policies.
Policies specify how things _should_ be, what is the ideal state of all the systems and data.
As organizations and regulations tend to be quite complex, policies are often complex too.
Moreover, policies tend to change in reaction to changed regulations or organizational needs.
All of that makes policy management quite a challenging thing to do.

Simulation, visualization.

Compliance reporting.

Role mining

== Generic Mechanisms and Infrastructure (TODO)

* Attribute mapping, expressions

* customization mechanisms (e.g. GUI customization)

* Schema management

* Logging and Diagnostics

* Services (API) and integration (e.g. SSO clients)

* Identity connectors

== Related Capabilities

* RBAC/ABAC - evaluation/enforcement

* Organizational structure management (business side, from book)

* Data protection, provenance
xref:policy-and-role-management.adoc[Read more ...]

