= Identity Governance and Administration
:page-keywords: [ 'IGA' ]
:page-toc: top
:page-upkeep-status: green
:page-visibility: hidden

// TODO: IGA high-level architecture

== Identity Governance and Administration Capabilities

NOTE: This list of capabilities is based on terminology widely established in the industry.
Although there are numerous ambiguities, we preferred established terms over re-inventing the terminology.
We are pointing out the ambiguities in the description as needed.

=== Identity Lifecycle Management

*Alternative names:* Lifecycle management, Identity lifecycle

*Functions:* Identity lifecycle state model, Maintenance of identity attributes, Identifier management, Credential management, Support for diverse identity types, Organizational structure, Personas

Identity lifecycle management deals with maintenance of digital identities.
It maintains state of digital identities through various lifecycle changes, such as creation, modification, archival and deletion.

xref:lifecycle.adoc[Read more ...]

=== Entitlement Management

*Alternative names:* Group management, Privilege management

*Functions:* Entitlement lifecycle management, Maintenance of entitlement associations

Entitlement management deals with association between identities and entitlements.
Entitlements are assigned to an identity, giving an identity access to a particular asset or an operation.
These are usually groups, permissions, associations to access control lists, low-level system roles and so on.
Simply speaking, entitlement management deals with a question: Who has access to what?

xref:entitlement-management.adoc[Read more ...]

=== Fulfillment

*Alternative names:* Provisioning/deprovisioning, Change propagation

*Functions:* Identity resource management, Communication with remote systems, Handling of fulfilment failures, Identity state tracking, Management of manual fulfillment operations

Simply speaking, fulfilment is a capability that deals with propagation of changes to target systems.
Fulfilment creates, modifies and deletes user accounts.
Strictly speaking, this capability fulfils the policy, e.g. by creating an account when such an account is mandated by the policy.

xref:fulfillment.adoc[Read more ...]


=== Synchronization

*Alternative names:* Reconciliation, Correlation

*Functions:* Data feed management, Reconciliation, Data consistency management, Identity correlation, Orphan detection

Synchronization capability provides functions that keep identity data consistent across all the connected systems.
While fulfilment can make sure that the account is created in accord with the policy, it is synchronization that makes sure that it stays compliant with the policy all the time.
This makes synchronization perhaps the most important infrastructural capability of any IGA platform.

xref:synchronization.adoc[Read more ...]

=== Policy and Role Management

*Alternative names:* Role management, Role governance, Role modeling, Role lifecycle management, Policy management

*Functions:* Role-based policies, Role structure, Role modeling and governance, Certification of role definitions, Segregation of Duties, Automatic role assignment, Compliance management, Deputy management

The heart of identity governance is about the policies.
Policies specify how things _should_ be, what is the ideal state of all the systems and data.
As organizations and regulations tend to be quite complex, policies are often complex too.
Moreover, policies tend to change in reaction to changed regulations or organizational needs.
All of that makes policy management quite a challenging thing to do.

xref:policy-and-role-management.adoc[Read more ...]

=== Access Requests

*Alternative names:* Role request and approval, Role request process, Approvals

*Functions:* Access request user interface, Management of approval schemes, Execution of approval processes, Maintenance of approval accountability record, Immediate fulfillment of approved requests

_Access request_ is a process for controlled, user-driven assignment of roles and entitlements to users.
It is usually implemented as request-and-approval process to assign roles to users.
The roles are usually requested by the user using a self-service user interface.
The request is then driven through a series of approval steps.
When approved, the roles are automatically assigned to the user.

xref:access-request.adoc[Read more ...]

=== Identity Workflow Automation

*Alternative names:* Workflow, Identity workflow management, Remediation

*Functions:* Remediation of policy violations, Case management, Process management, Escalation, Notifications

While identity management strives for automation, there are still tasks in identity management and governance that must be done by humans.
These are usually decisions that cannot be made automatically, tasks that do not have algorithmic description, or just a simple notification, letting users know about the progress of a task.

xref:workflow.adoc[Read more ...]

=== Access Certification

*Alternative names:* Re-certification, Attestation

*Functions:* Full certification campaign, Microcertification, Certification of role definitions

Access privileges have a tendency to grow and accumulate.
There are many ways to efficiently grant a privilege: formal _access request_ processes, privileges are granted manually by system administrators and various informal side channels.
However, privilege accumulation is a risk, as people often keep their privileges forever.
Access certification is a process to remove privileges that are no longer necessary.
During access certification process, responsible persons must _certify_ that users still need the privileges that were granted to them.

xref:certification.adoc[Read more ...]

=== Auditing

Keeping track of operations (business level). Accountability. Metadata?

Note: Sometimes includes sync/recon and remediation.

=== Identity Analytics and Reporting

Alternative names: Identity analytics and intelligence (IdA)

Risk assessment, reporting, risk-based approach
Alternative names: Role management, Role governance, Role modeling, Role lifecycle management, Policy management

Excessive access, outliers, identify over-privileged users
The heart of identity governance is about the policies.
Policies specify how things _should_ be, what is the ideal state of all the systems and data.
As organizations and regulations tend to be quite complex, policies are often complex too.
Moreover, policies tend to change in reaction to changed regulations or organizational needs.
All of that makes policy management quite a challenging thing to do.

Simulation, visualization.

Compliance reporting.

Triggering microcertifications.

Role mining

== Generic Mechanisms and Infrastructure (TODO)

* Attribute mapping, expressions

* customization mechanisms (e.g. GUI customization)

* Schema management

* Logging and Diagnostics

* Services (API) and integration (e.g. SSO clients)

* Identity connectors

== Related Capabilities

* RBAC/ABAC - evaluation/enforcement

* Organizational structure management (business side, from book)

* Data protection, provenance

// TODO: functions to document:
//
// Application management (lifecycle), creating/deleting app accounts, managing passwords.
// a.k.a. "service account management"
//
// Infrastructure/built-in accounts (root, administrator, etc.)
// May not even have password, but we need to account for them.
//
// TODO: Where to put it?
// Account ownership management (linking)
