= IGA Capability: Identity Lifecycle Management
:page-nav-title: Identity Lifecycle Management
:page-display-order: 100
:page-keywords: [ 'IGA' ]
:page-upkeep-status: green
:page-visibility: hidden

== Alternative names

* Lifecycle management

* Identity lifecycle

== Identity Lifecycle Management Functions

* *Identity lifecycle state model*
TODO: candidate -> active -> archived, ...

* *Maintenance of identity attributes*
TODO: identity model, schema management
TODO: GUI?

* *Identifier management*
TODO: uniqueness constraints

* *Credential management*
TODO

* *Support for diverse identity types*
TODO: person and non-person

* *Organizational structure*

* *Personas*

== Overview

Identity lifecycle management deals with maintenance of digital identities.
It maintains state of digital identities through various lifecycle changes, such as creation, modification, archival and deletion.
Digital identities are usually complex data structures, composed of numerous attributes.
The structure of identity data and its relationship with other identity-related objects is specified by an _identity model_.
Identity lifecycle management is responsible for maintaining _identity model_, keeping the attributes structured and consistent.
This includes management of identifiers, including creation and validation of unique identifier values.
Identity lifecycle management may include management of _credentials_, such as passwords and multi-factor authentication cryptographic material.

Lifecycle state model is often used to manage identity lifecycle.
An identity is transitioned through a set of _lifecycle states_ such as `candidate`, `active`, `deprecated` and `archived`.
Identity lifecycle is often bound to policies and fulfilment actions, creating functionality such as pre-provisioning of accounts for new employee, delayed delete of accounts, erasure of data on archival due to data protection regulations, and so on.

IGA systems deal with many identity _types_ (a.k.a. _classes_ or _archetypes_).
The most important identity types are usually person identities, such as employees, students, customers and citizens.
However, comprehensive IGA systems must routinely deal with non-person identity types as well, such as services, applications, organizations, devices and "things".
Each identity type may have its own characteristics, such as attributes, policies and lifecycle states.
Such variation is used to implement various operation modes, such as business-to-employee (B2E), business-to-business (B2B) or business-to-consumer/citizen (B2C).

Complex identity models may include concept of _personas_, an alternative representation of a person designed for use in a specific context.

Partial management of organizational structure may be included in identity lifecycle management.
Although organizational structure management is not a responsibility of identity governance and administration per se, policies are often bound to organizational structures.
In such case, IGA systems must be able to process organizational structures to be able to evaluate the policies.
Even though the depth of organization structure management required by IGA systems is, in theory, very shallow, practical IGA deployment often need to go much deeper than expected (see notes below).

Identity lifecycle management almost always includes administration user interface, allowing identity administrators to review identities managed in the system, or even manage them manually.
Self-service interface for ordinary users is usually also present, providing means for a user to maintain parts of user profile.

There are some IGA features related to the identity lifecycle, features that require cooperation of several capabilities.
Identity merge/split is related to the synchronization/correlation capability, however it may require support from workflow capability.
Similarly, progressive profiling, self-service registration, invites and similar capabilities require parts of workflow capability, or a special-purpose interface.

== See Also

* xref:/iam/iga/[]
