= IGA Capability: Policy and Role Management
:page-nav-title: Policy and Role Management
:page-display-order: 140
:page-keywords: [ 'IGA' ]
:page-upkeep-status: green
:page-visibility: hidden

== Alternative names

* Role management

* Role governance

* Role modeling

* Role lifecycle management

* Policy management

== Policy and Role Management Functions

* *Role structure*.
TODO: role hierarchies, metaroles

* *Role modeling and governance*.
Functions allowing creating and maintaining role definitions.
Role model lifecycle, versioning, reviewing and approval process.
Role ownership, role model curation.

* *Role/policy administration interface*.
User interface for role and/or policy administration.

* *Certification of role definitions*.
Process to certify role definition, to make sure their definitions are still applicable.

* *Segregation of Duties*.
TODO

== Overview

The heart of identity governance is about the policies.
Policies specify how things _should_ be, what is the ideal state of all the systems and data.
As organizations and regulations tend to be quite complex, policies are often complex too.
Moreover, policies tend to change in reaction to changed regulations or organizational needs.
All of that makes policy management quite a challenging thing to do.

There are many ways to express an organizational policy.
The policy may be expressed by a completely non-structured free-form text form that can only be interpreted by humans, and even that in quite an ambiguous way.
The policy may be expressed in a compilable code, unambiguously interpretable by computers.
However, none of that extreme approaches work in practice.
Therefore, in reality, the way a policy is expressed is somewhere in between the extremes.

Most methods used to express identity governance polices rely on a concept of a _role_.
A _role_ is a grouping of privileges into a named, manageable set.
Ideally, roles should relate to real-world concepts, such as work positions or organizational responsibilities.
However, such correspondence of roles to real-world concepts is not always possible, and many roles are quite abstract in their nature.
The important characteristic of a _role_ is that it is easier to manage than individual privileges grouped in a role.

_Role_ is a grouping of _entitlements_.
Which in IGA context usually means grouping of application-specific entitlements such as LDAP groups, application privileges, account attribute values that match a specific access control list and so on.
While in traditional RBAC context such role definition is usually processed when user logs into the system (a.k.a. "just in time" approach), in IGA context the roles are processed differently.
Role definition has to be processed before the user logs into the system for the first time.
Membership in an IGA role means that the account will be _associated_ with (made member of) a particular LDAP group or application privilege at the time when the role is assigned to user (a.k.a. "just in case" approach), long before the user logs in.

The roles can usually contain other roles, thus creating a _role hierarchy_.
Role hierarchy can be utilized as a form of re-use, grouping frequently-used privilege groups into role, then including them in other roles.
However, role hierarchy is usually used to divide roles into several types or layers.
The usual role types are as follows:

* *Application roles* grant access to a single application or system.
Application roles often correspond to application-level entitlement such as groups.
They usually grant account and entitlement in a single application.
Many IGA platforms can operate without any need for application roles, managing application-level entitlements directly.
However, even such platforms often use application roles nevertheless, for governance purposes.

* *Technical roles* or *IT roles* are ad-hoc grouping of permissions, mostly for the purpose of re-use in other (business) roles.
They often represent some organizational or administration concepts, such as _reports read-only access_ or _basic OS permissions_, however, they do not represent complete business concept.
Technical/IT roles may span several applications.
They are usually defined as a combination of application roles.

* *Business roles* often represent business-level concepts, such as work position or job responsibility.
Business roles are designed to be understandable to a common user, using organizational and business terminology rather than IT slang.
Ordinary users are supposed to look up appropriate business role in access request process, managers are supposed to review and approve/reject the request.
Therefore it is paramount that business roles use a language that the users can understand.
Business roles are usually defined as a combination of application and/or technical roles.

// TODO

The most challenging part of all the role-based mechanisms is undoubtedly design and maintenance of role definitions.
We refer to this process as _role management_, or, perhaps more precisely, _role lifecycle management_.

// TODO
// Maintenance of role definitions (role ownership and role model curation)
// Metaroles (metaroles vs hierarchy)
// Role catalogs (maintenance, presentation to end users, reporting).

// Role lifecycle management (modeling) vs RBAC

// Role models, versioning, approvals, lifecycle
// Role decommissioning process
// Role re-certification

// Role explosion

.Terminology
NOTE: The terms _role management_ and _role-based access control_ (_RBAC_) are many things to many people.
We use the role-related terms in quite a broad sense.
We do not refer to NIST RBAC model, or any other formalized role-based access control model.
What me mean are generic mechanisms that are based on the concept of a role.
Although the basic principles of most role-based mechanism is similar, there are subtle details.
We try to abstract from such details.
Also, this section is mostly about _role management_, by which we mean the process of creating and maintaining role definitions.
Strictly speaking, this is different from role-based _access control_ (RBAC), which is a process of using roles to control access to assets.

There are methods to express a policy that do not use roles, such as attribute-based access control (ABAC).
Such methods can be very powerful and extremely flexible.
However, with great power comes great responsibility, and management of such policies is almost always problematic as they get longer and more complex.
E.g. it is difficult to split ABAC policy into smaller pieces, each of them managed by an independent delegated administrator.
Roles allow such separation of administration responsibilities.
Moreover, roles simplify governance, as role designers, owners and reviewers can be specified,
roles provide natural boundaries to split certification effort and so on.
Hence, most practical identity governance deployments are role-based, albeit the roles usually provide some degree of ABAC-like flexibility inside their definitions, thus effectively creating an RBAC/ABAC hybrid.


// TODO


Rules, automatic assignment of roles and entitlements.

SoD: role-related policy

Delegated administration, deputies (usually based on organizational management)

Compliance policies.

Initiating remediation, opening cases (but not management/communication on cases)

(application) role synchronization
