= Risk-Based Approach To Identity Governance
:page-nav-title: Risk-Based Approach
:page-visibility: hidden
:page-toc: top

.Draft
WARNING: This is a draft, it is work-in-progress.

== The Problem

Cybersecurity is absolutely essential for almost any organization.
Contrary to the popular belief, cybersecurity is not one-off project with fixed start and end dates.
It is rather _program_, a never-ending cycle of repeating activities, ensuring that all your information assets are secure at all times.
Being a continuous activity with no end, cybersecurity needs proper _governance_, making sure that the cybersecurity activities provide adequate protection, that they are efficient and properly implemented.

Governance of long-running cybersecurity activities is no easy task, as the world is changing.
The environment, requirements, technologies as well as capabilities of the attackers are evolving rapidly.
Security measures that were adequate last year can become absolutely useless next year.
Here comes the notorious cybersecurity cycle of activities, endless turning of the identify-protect-detect-respond-recover activity wheel.

Accurate and up-to-date information regarding security-critical parts of your systems is absolutely essential for cybersecurity governance.
Security countermeasures that are based on inaccurate and/or stale data are useless, such measures are a huge waste of resources, and they leave your systems open to attacks.
However, how do we get quality data to base our cybersecurity program on?
Manual, paper-based cybersecurity analyses are a thing of the past.
Huge spreadsheets of estimated risk levels were mostly based on guesswork.
They include only _known_ risks, completely missing forgotten mis-configurations or orphaned privileged accounts.
As the amount of analytical work is huge and manual work is slow, such analyses are outdated at the very moment the spreadsheet is finished.
It is no wonder that cybersecurity measures based on 20th century methods are no match for 21st century threats.


== The Approach

We have a huge security landscape to cover, and we have very little time.
However, this is not the first time we see a problem like this.
Automation is the key, of course.
If the security analysis has to provide accurate and up-to-date data, and it has to provide it quickly, we need to automate the bulk of data-processing activities.
However, cybersecurity is a vast landscape.
There are parts of cybersecurity that cannot be analyzed automatically.
Such parts will still require close attention of security expects.
Yet, there are parts that can be automated, saving a huge amount of work, and improving accuracy at the same time.

Identity governance is an essential part of every cybersecurity program.
It does not need a lot of imagination to predict the damage that can be done by an attacker exploiting an orphaned privileged account.
This is strongly amplified by multitude of cloud applications, making it impossible to apply traditional security techniques such as perimeter security.
Vast majority of your systems is open to external attack at any time.
To make things even worse, cybersecurity studies consistently indicate _insider threat_ among the most significant threats to the organization.
Consider the amount of damage an external attacker can do, with a limited knowledge of your systems and processes.
Now consider how much worse can be a rouge insider, with intimate knowledge of inner workings of your organization.

The risks originating from identity management and governance form a major part of overall cybersecurity risks of your organization.
However, it is almost impossible to manage such risks manually.
There are just too many users, groups, privileges, roles, accounts and personas to manage.
Automation of identity management and governance is the only way.
This has been known for decades, and there are well-established technologies for identity and access management.
However, the crucial link from identity management to cybersecurity risk management is mostly missing.
Identity management tools can automate identity lifecycle, can create and delete accounts as needed.
However, they do not provide information regarding risk imposed by the accounts and their entitlements.
Yet, identity management systems are in ideal position to assess, analyze and even address the risk.
Identity repositories contain information about users, their organizational membership, entitlements, responsibilities, etc.
The data are there, the technologies to process the data and act on them are not.
Yet.

== The Solution

_Risk_ is a central concept of cybersecurity.
Everything in cybersecurity is about identifying the risks, analyzing them, minimizing them, or preparing for residual risks.
Identity governance provides essential mechanisms for cybersecurity governance.
Identities form such a significant part of the overall risk, that there is no real security without identity governance.
However, for this security-identity cooperation to be efficient, the identity governance has to talk the same language as security professionals use.
_Identity_ governance has to work with concepts of _cybersecurity_ governance.
Therefore, identity governance systems must learn to work with _risk_ as a central concept.

=== Analyze

First step is to _understand_ the risk.
Identity governance systems have to analyze the risk, identify high-risk spots, provide data for informed decision-making.

Identity governance systems have a huge advantage over most other systems in cybersecurity field.
The data that identity governance systems use are _structured_.
Good identity governance system does not only store the data, it _understands_ them.
It knows what is a meaning of user _account_, what _role_ and _entitlement_ mean, what _privileges_ are granted by them.
Such structured information is an ideal foundation for risk modeling.

Identity governance system can be used to assign elemental risk levels to individual entitlements, such as Active Directory groups or application privileges.
This elemental information can be processed by a risk model, computing risks for individual users, organizational units, projects and overall risk for the organization.
This process can be automated, providing almost-real-time information for cybersecurity professionals.

Risk model can be expanded to consider common cybersecurity risks, such as orphaned or unused accounts.
Risk of roles can be automatically computed based on their composition and other parameters, highlighting sensitive roles that require special attention.
The model can identify security hot-spots, such as over-privileged users, or a dangerous accumulation or risk in a single organizational unit.
The model can be used to manage residual risk, making sure residual risk is acceptable, that there are no users with dangerous combinations of privileges.
Moreover, the system is dynamic, always following up-to-date data.
It can be proactive, it can generate real-time notifications when risk grows above acceptable levels.
The model can provide insights at such fidelity and speed that no human analyst could ever match.

This approach is poles apart from the futile paper-based risk modeling of 20th century.
As identity governance data are directly bound to the underlying information systems, the risk information is always reliable, based on real data rather than guesswork.

.Identity analytics
TIP: Several existing identity governance products offer "identity analytics" functionality.
Identity analytics provides insights into identity data, a functionality that is partially similar to risk-based approach.
However, there are crucial differences.
Identity analytics provides partial insights, whereas risk-based approach provides a holistic, integrated view.
Where identity analytics identifies outliers, risk-based approach reflects outliers in the big picture of overall organizational risk.
Where identity analytics provides entitlement insights, risk-based approach also evaluates risks posed by the entitlements and fits that into the overall cybersecurity governance.
Risk-based approach is a superset and an evolution of identity analytics mechanisms.

.TODO
WARNING: Do we need better name than "risk-based approach"?

.Implementation note
NOTE: Risk values can be assigned to entitlements manually or semi-automatically.
Connector can suggest initial risk values for well-known entitlements, e.g. `Domain administrators` group in Active Directory.
Connector can even analyze fine-grained privileges associated with an entitlement (in case that the target system provides such information).
In addition to this, the platform can provide suggestions of risk levels for well-known naming patterns.
E.g. it can automatically assign higher risk value for any group that contains string `admin`.

.Implementation idea
NOTE: Entitlements assigned using a business role provide slightly _lower_ risks, as they are easier to manage (e.g. recertify entire role).

.Implementation note: parametric roles
NOTE: Risk of parametric role is a combination of risk of the entitlement (i.e. "asset") and relation to the entitlement (e.g. `user` or `admin`).

.Open question
WARNING: How to model information assets? As applications? Special kind of services?

=== Act

Second step is an ability to efficient _act_, based on reliable data about risks.

When it comes to identity management, system administrators and security professionals are fighting an uphill battle.
The environment is changing faster than they can act.
New users are being enrolled and retired, privilege assignment is changing every day, there are re-organizations, policy changes, applications are deployed and decommissioned all the time.
Security professionals are not able to pay attention to every change around them.
There are tens of thousands of users and roles spread across hundreds of applications, creating almost unimaginable number of user-role-application combinations that need to be managed.
It is not physically possible to approve every role request, to review every role assignment after every small organizational change, to analyze fine-grained privileges of every minor application.
Security professionals need to _prioritize_, pay close attention to important stuff, delegating the less important tasks.
However, there comes the crucial question: How do we know what is important?
Every security professional knows the answer: _risk_.
Users, roles and applications that pose the highest risk need much more attention than a minor auxiliary applications that pose only marginal risk.

Fortunately, we have our automated risk model.
Now we know where the risks are.
We can prioritize.
We can find users that pose the highest risk for our organization, and we can re-certify their access rights using special micro-certifications.
This approach focuses all the attention to few powerful users, as opposed to traditional re-certification campaigns where the risky users are desperately lost among thousands of other users.
Focused re-certifications increase the probability that privileges will be removed, mitigating a security hot-spot.
As focused micro-certifications require only a fraction of an effort of a full certification campaign, micro-certifications can be triggered more frequently.
The same approach can be applied to review of risky roles, reviewing them much more often than low-risk roles.
Similarly, requests and approval of new roles assignments may be governed by risk information as well.
The obvious option is to apply special approval schemes for sensitive, high-risk roles.
However, a combination of many common roles can also cause a dangerous accumulation of access rights.
Therefore, it would be a good idea to apply special approval schemes for users that have reached high risk score by accumulating many low-risk privileges, avoiding creation of security hot-spots in the first place.
There are many more options when a risk score is processed as a native part of identity governance: identifying risky applications (e.g. application with lot of administrators), automatic deactivation of orphaned privileged accounts, motivating or enforcing on-demand and time-limited assignment of privileged roles and so on.

It is perhaps no big surprise for security professionals that risk information permeates all the usual identity governance processes.
For example, role mining can provide a helpful assistance even without risk information.
Role mining identifies clusters of similar access rights, suggesting creation of new roles.
However, it is often difficult to focus role mining activities on the right combination of privileges.
Role mining algorithms do not understand what the privileges mean, they only focus on how similar they are to each other.
This can be disorienting, misguiding the people to focus a lot of attention at unimportant roles, missing the important ones.
Yet, when supplemented by risk data, role mining can become an indispensable tool in cybersecurity toolbox.
Risk information can focus role mining activities at important, high-risk combination of privileges.
When a high-risk privilege combination is formalized as a role it is much easier to maintain and review, making overall risk more manageable.

Similar benefit can be seen in outlier detection mechanisms.
Outlier is a user that has different access rights than other users in the same category.
Outlier detection algorithms are approximate, working with fuzzy concepts.
Also, it is quite normal that the access rights in your organization are not entirely unified.
Many users will accumulate many unique privileges during their long careers in your organization, effectively making them outliers.
Therefore, it is very likely that there will be huge number of outliers, especially at the early stage when identity governance processes are rolled out.
Once again, risk management can provide an essential assistance at that point.
Outliers with high risk scores can be prioritized,

Risk model can uncover areas of concentrated risk that are far from obvious.
It is quite natural that high-risk roles are subject to special approval and review schemes, to make sure that there are only few users that have high-risk roles.
However, a medium-risk role given to large number of users also creates a high-risk situation, greatly increasing potential attack surface.
It is usually not feasible to apply special approval and review schemes to all medium-risk roles.
Especially frequent re-certification campaigns for popular medium-risk roles require huge amount of effort, often resulting in pointless rubber-stamping exercise.
Risk model can easily identify such roles.
However, as re-certification is not an efficient solution to reduce risk posed by such roles, quite a different mechanism must be employed.
The ideal solution would be to assign and unassign such roles automatically, effectively eliminating the need for huge re-certification campaigns.
However, such automation assumes existence of policy: a rule that can be used to manage role membership automatically.
In simple cases, the rule for automatic role assignment is likely to be quite obvious.
Security professionals might be able to determine the rule by manually analyzing role content, purpose and members.
However, in complex cases the rule may not obvious, or there may be large number of such roles, making manual analysis infeasible.
In such a case, policy mining can be used to suggest rule for automatic rules for role assignment and unassignment.
Policy mining is similar to role mining, it is a pattern recognition mechanism.
However, it analyzes existing members of a role, looking for similarities, such as common organizational unit, work responsibilities, location and so on.
Once a common pattern is identified, rule for automatic role management can be established, based on common attributes.

We are taping into "collective knowledge" of organizational processes and policies.
There is no single person that knows all the policies of your organization.
There is not a even a single department, division or team that knows it.
The policy is divided in thousands of pieces, distributed among many people through the organization.
The policy is not explicitly specified, it is not formalized, it is not written down in sufficient details for automation.
It cannot be used directly.
Fortunately, the practical aspects of the policy are already implemented in your organization.
Roles are created according to the implicit policies, decided by people that created the roles.
Roles are assigned to users according to policy, guided by decisions of many individual approvers.
The policy is there, hidden in a huge pile of accounts, privileges, roles, organizational units and attributes.
We are using mining mechanisms to distill the policy, to find policy facets hidden in the data.
Mining mechanisms can uncover the hidden patterns and rules, suggesting pieces of organizational polices to formalize and automate.
Risk modeling is applied on top of mining algorithms, to focus attention and prioritize the effort.

Risk-based prioritization makes you start your cybersecurity program quickly, focusing attention to the worst problems.
Focus on high-risk areas reduces risk at points with the highest potential gain, rapidly lowering overall organizational risk.


=== Govern

Third step is to _govern_, making sure everything runs smoothly, ensuring continuous improvement.

Security is not a sprint, it is a never-ending marathon.
It is not enough to mine the roles, set up policies and model risk.
The tasks have to be repeated over and over again.
Roles must be maintained, assignments must be reviewed, data must be corrected, policies updated and improved.
The cycle never ends.

Moreover, it is not enough to do the same things over and over again.
Bruce Schneier once said: "Attacks always get better, they never get worse".
The world is evolving, and the cybersecurity processes, programs and practices must evolve too.

"What is measured, improves" is a classic management adage.
Reliable, measurable insights are key to any governance, cybersecurity and identity are no exceptions.
However, there are not many meaningful metrics in cybersecurity and identity fields.
Monitoring number of users or number of roles is easy, yet it does not provide very meaningful information.
Even _risk_ is a tricky metric to grasp.
What does "medium risk" mean, exactly?
How much risk is acceptable?
How much risk is too much?
What units do we use for measuring risk, anyway?

_Risk_ is not an absolute objective value.
It cannot be measured exactly, and it is extremely hard to compare across organizations.
It does not mean much if we know that our overall risk is 42.56 or that our risk level is "low".
However, _risk_ is still a very useful metric when used in a relative way, put into proper context.
We have seen how risk levels can be used to identify parts of the systems that are at higher risk than others.
This is extremely useful for identifying hot-spots, places to focus our security improvements at.
Yet, from a governance point of view, _risk_ plays yet another crucial role.
Even though individual risk values are not very useful, observing change of risk value over time provides essential insights.
We know that we are doing good cybersecurity job if overall risk value steadily decreases.
Our processes need major improvement if risk value consistently rises over long period of time.
It is a critical warning sign if risk value suddenly surges.
We can learn a lot about our cybersecurity efforts by watching the _trends_ of overall risk value.
Risk trends are essential metric of cybersecurity governance.

However, if we want to watch risk value trends, we need reliable, up-to-date and frequent information on organizational risks.
This is not practically feasible without automation.
However, risk-based approach to identity governance can provide crucial part of the risk evaluation, and it can provide it reliably (based on real data) and quickly (in almost-real-time).
It is very hard to imagine proper cybersecurity governance in 21st century without the support of identity governance systems.

== Motivation Brief

Cybersecurity is in big trouble.
The attacks are getting worse.
The situation has changed for the worst even in last few years.
As attacks are getting worse, cybersecurity professionals are having a hard time.
It is very difficult to acquire cybersecurity talent and real expertise.
Security teams are short on staff and time.
They are not able address all the problems at once.
They must prioritize.

Cybersecurity is all about _risk management_.
It is not even theoretically possible to be 100% secure.
Yet, it _is_ possible to be _reasonably_ secure.
Security practitioners need to prioritize according to _risk_, they have to address areas with highest risk first.
However, we need to know _where_ the highest risks are for risk-based prioritization to work.
There are some bad news, though.
Old methods of risk assessment do not really work any more.
Manual risk analysis takes too much time, it requires too much effort.
The results are outdated even before the spreadsheets are finished.
Attackers move much faster than that.
Radically new approach is needed for risk-based security to work again.
Risk assessment has to be automated.
It has to identify risk hot-spots, based on real data, continuously, in real-time.
This is the way to lock on fast-moving threats.

Insider threat is consistently identified as one of the worst risks for organizations.
Network-based methods such as multi-factor authentication or zero-trust approach are not efficient against insider thread.
Such methods guard you against people trying to gain access to your organization.
However, insiders already have perfectly legal access to your data.
Insiders can do enormous damage, by malice or neglect, as they already intimately know your organization.
Something has to be done about it.
Yet, not much has been done for decades.
Security practitioners are still relying on outdated 20th-century methods.

Insider threat is related to _identities_ that you are managing: users, groups, devices, permissions.
Unfortunately, identity data are usually just a huge tangled pile of accounts and entitlements.
This is a complex labyrinth which is extremely difficult to navigate.
Yet there is hope.
There is a class of systems that were designed to manage _identities_.
Identity governance and administration (IGA) systems are designed to navigate the identity labyrinth.
They are in ideal position to process and analyze identity data.
However, contemporary IGA systems are not well-equipped to deal with concept of _risk_.
They do not speak the basic cybersecurity language of risk management.
Yet, that can change.

We can introduce concept of _risk_ into IGA system.
As we let the concept of _risk_ permeate all aspects of identity management, identity management efficiently becomes _risk management_.
As IGA systems are already built to gather and analyze real-wold identity data in real-time, it directly leads to real-time risk assessment as well.
Yet, there are even better news.
Modern IGA systems go far beyond the traditional notion of _user_ and _group_.
IGA system for 21st century is dealing with _applications_ and _device_ identities.
This is a great potential to cover all the places where your data reside, tracking information _assets_ as well.
IGA system can gather real data, process them, analyze them in real time, providing _risk_ data that are always up-to-date.
Yet, there is even more.
IGA system does not only gather the data, it can also _act_, and it can act quickly.
Risk hot-spots can be reduced in seconds by removing unnecessary privileges that were silently accumulating for decades.
Dangerous privileges can be assigned on-demand, granted only for a limited time period.
The system can provide real-time warning when suspicious combination of privileges is requested.
Risk levels can be monitored over a long period of time, providing insights and analyzing trends.
Such information is crucial part of cybersecurity governance.

When IGA systems start to understand cybersecurity concepts, the possibilities seem to be endless.
The attackers already use 21st century methods.
It is about time for cybersecurity technologies to catch up.


== Misc Notes

This has to be holistic set of features that support each other (synergistic features).

Good presentation of results is crucial (dashboards) - using cybersecurity language.

What about "asset"? Can we assign information that is being processes/accessed by application? Could this be used to compute per-application risk levels?

Could perhaps midPoint become *the* platform for risk analysis? Incorporating also non-identity risks? Application risks (SBOM, service endpoints, etc.) might be feasible, we are dealing with applications anyway. Can we process other risks too, e.g. network risk levels? Is this even relevant any more in this cloud era?

TODO: role of AI - training data. Bad organizational practices may be locked in by AI. Need risk information to make sure AI works properly, that it does not systematically increase organizational risk.

TODO: Some tasks can (and must) be delegated to business units.
E.g. approvals, reviews, re-certifications.
However, security staff needs to keep proper oversight.

TODO: real-time data, continuous analysis

TODO: This approach is also essential for management of high residual risk areas, where risk cannot be reduces and must be accepted.
Risk-based approach keeps attention focused to high-risk areas, keeping residual risk under constant supervision.

