= IGA Capability: Identity Workflow Automation
:page-nav-title: Identity Workflow Automation
:page-display-order: 160
:page-keywords: [ 'IGA' ]
:page-upkeep-status: green
:page-visibility: hidden

== Alternative names

* Workflow

* Identity workflow management

* Role approvals

* Approvals

* Approvals

== Identity Workflow Automation Functions

* *Remediation of policy violations*.
TODO

* *Case management*.
TODO

* *Process management*.
TODO

* *Escalation*.
TODO

* *Notifications*.
TODO

== Overview

While identity management strives for automation, there are still tasks in identity management and governance that must be done by humans.
These are usually decisions that cannot be made automatically, tasks that do not have algorithmic description, or just a simple notification, letting users know about the progress of a task.

Many processes in identity management can be automated, and in fact, automation is one of the primary tools of identity management and governance.
However, there are several cases that cannot be easily automated due to their very nature.
Most of such tasks are meant to handle situation when something goes wrong, something that cannot be fixed by an automatic action.

Remediation of policy violations are perhaps the most common case for manual workflow.
Let's suppose that we have a policy that every project in our organization must have at least one manager.
That is a very natural policy, requiring that there is always a person responsible for the project and all the resources associated with it.
However, what should IGA platform do, when a project manager leaves the company?
Operation that deletes or archives the identity of the project manager is causing policy violation, as there will be a project without a manager.
However, IGA platform cannot stop the operation, it cannot refuse to delete the identity.
IGA platform cannot even postpone the operation, as there may be good reasons to immediately disable all access of that person.
Yet, executing the operation leaves the system in a state of policy violation.

This example illustrates relatively common problem in identity governance, a problem that strict enforcement of policies cannot solve.
The usual solution is to proceed with the operation that violates the policy, accept the fact that there is a policy violation, and start a _remediation_ action to get the system back to state of compliance with the policy.
Many remediation actions are manual action that need to be done by a human.
In the case of missing project manager above, a human has to make a decision to nominate new manager for the project, or to close the project.
There are many tasks in identity governance that need human interaction, such as:

* remediate policy violation,

* add missing role definition,

* improve existing role definition,

* resolve dangerous privilege accumulation,

* address high-risk situation,

* eliminate redundancies (e.g. almost-duplicate roles).

While the actual action or actions have to be done by a human, IGA system has a responsibility to monitor progress of the task, to remind participants that the task needs to be done, to report the task and provide similar support and management functionality.
This is known as _identity workflow automation_.

IGA platforms usually use two approaches for workflow automation:

* Process-based approach is using pre-defined sequence of steps.
The process defines what should be done, who should do it, in what sequence and under which conditions.
It is essentially an algorithm, composed of human interactions.
General-purpose workflow engines are usually used to manage the process, business process definition languages (such as BPMN) are usually used to specify such process.

* Case-based approach relies on unstructured or semi-structured cooperation to complete a task.
A _case_ is similar to a trouble ticket used in ITSM systems.
It describes the problem that needs to be resolved, however, it does not specify a predefined steps to resolve it.
The person or persons that the case is assigned to must figure out the specific steps or operations to resolve a case.
A case is initially assigned to a particular person or a group based on simple rules.
However, it is not expected that such initial assignee will be able to complete the case.
The case is often re-assigned to a different person, several persons co-operating on resolving the case, commenting and interacting until the problem described by the case is resolved.
While most of the work and information regarding a case is unstructured, the case almost always has a structured _status_ indicating the progress (_open_, _on hold_, _resolved_, _closed_ and so on).

Traditionally, IGA platforms relied on process-based approach, in a hope that every situation can be formalized and an algorithm can be specified to resolve it.
While this may be formally true, the specific algorithm is seldom known at the time of IGA platform deployment.
In fact, it is seldom known at all, as it may be slightly different for each specific case.
Therefore, many practical IGA deployments tend to utilize a case-based approach, relying on unwritten knowledge of key people in the organization to resolve the cases.
The process-based approach is used for some special purposes, such as on-boarding and off-boarding processes.

Some functions are common to both approaches, such as progress monitoring and escalation functionality.
Escalations are usually triggered automatically, when the problem is not resolved or step in the process is not completed until a specified time interval.
Escalations often rely on organizational structure management, as the task is often escalated to a manager.

Notification functionality is also considered part of workflow automation capability.
Purpose of notifications is to inform users that an action has taken place.
Perhaps the most common form of notifications is an informational e-mail message informing the user that new accounts were created, or new entitlements were assigned.
However, notifications can take many forms, often containing custom messages.

Identity workflow automation capability is often a "catch all" tool, meant to resolve all the problems that other parts of IGA platform are not able to resolve.
// TODO: useful but dangerous, use in moderation, automation and formalization should still be a goal

// TODO: Customization and upgrade problems, especially for IGA platforms heavily based on general-purpose workflow engines.

== Terminology Notes

TODO: confusion with access request / approvals

Sometimes: manual fulfilment


== Workflow Engine Notes

Internal workflow, integration with workflow engines, enterprise workflow.
