= Issue Tracking System
:page-wiki-name: Bug-tracking System
:page-wiki-id: 26411189
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2018-07-23T11:49:23.137+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2018-07-23T11:49:23.137+02:00
:page-moved-from: /midpoint/support/bug-tracking-system/

MidPoint development team is guided by the information in our issue tracking.
The content of issue tracker is the plan.
Developers work on the issues tracked there.
Strictly speaking, they should work *only* on the issues files in the issues tracker.
Therefore, if you want your bug to get fixed or your feature to get implemented then it has to go into issue tracker.
For midPoint subscribers this is often done by the subscriber or partner, as this the best way to maintain communication fidelity.
However, it is also a common practice that midPoint developer creates an issue for the subscriber.
Regardless of the actual method, all bug reports, feature requests, improvement suggestions and other development tasks must be recorded in the issue tracker to make sure they are addressed.

== OpenProject

Evolveum is using OpenProject as a bug-tracking system for midPoint development and support:

https://support.evolveum.com/[]

== Priorities and Support Guidelines

Please see xref:/support/support-guidelines/[Support Guidelines] page for a general introduction to Evolveum support processes.
This involves bugfixing and feature requests.

== Bug Reports

Please see xref:/support/bug-tracking-system/creating-a-bug-report/[Creating a Bug Report] page.
Bug reports that will not comply with the guidelines will be regarded as the lowest priority, or may be entirely ignored.

*DO NOT report security vulnerability the same way as normal bugs!*
Use xref:/midpoint/security/security-guide/#reporting-security-issues[this guide] to report security vulnerability responsibly.

== Feature Requests

Please see xref:/community/feature-request/[Feature Request] page.

== See Also

* xref:/support/bug-tracking-system/creating-a-bug-report/[]
* xref:/support/[]
