= Compliance Design Notes
:page-nav-title: Compliance

This page contains design notes on xref:/midpoint/compliance[compliance], thoughts, missing feature description, etc.

== Configuration Changes

Changes we can make in 4.8 using configuration:

* `Project` archetype and root org.
Appropriate `assignmentRelation` for projects: members, managers, owners (stakeholders).

* Compliance dashboard

* Compliance reports

== Missing Features

(Roughly ordered by priority)

* Password management

** dictionary check: enabled by default? Not showing in GUI. (ISO 27001 5.17)

** dictionary check for combination of dictionary words. (ISO 27001 5.17)

** Forcing password change on next login: how can we make it easier to set up? (ISO 27001 5.17)

** Closer integration with AM/SSO? Force password change, last login, etc. (ISO 27001 5.17)

** enforcing different passwords on resources (ISO 27001 5.17 (D))

** "users acknowledge receipt of authentication information" (ISO 27001 5.17)

** (!!!) Force change of pre-configured administrator password on first login (ISO 27001 5.17)

** "prevent the use of commonly-used passwords and compromised usernames, password combinations from hacked systems" (ISO 27001 5.17)

** Guidance for end-users how to use password on pages that deal with passwords (ISO 27001 5.17)

** Clean up documentation for password reset (it is in really bad shape)

* xref:/midpoint/features/planned/classification/[] (ISO 27001 5.13, 5.8)

* Certification of other parts of (abstract) role, most notably policy rules.
For ISO 27001 5.12, re-certification of policy rules included in classification definitions.

* Making sure that certain requirements are fulfilled before assignment is assigned or activated. (ISO 27001 5.12, 5.13, 5.14)

** Making sure user has enrolled multi-factor authentication before accessing classified system.

** Acceptance of "terms of service" by end user before access to the service can be activated. (ISO 27001 5.10)
Note: Similar flow to GDPR consent.

* Shared accounts (ISO 27001 5.16 (b))

* Risk model

* Risk control related to external identities (social login) (ISO 27001 5.16, 5.19, 5.17)

* Support for passkeys and other non-password credentials? (ISO 27001 5.17) (ISO 24760)

** Default risk of application role may be given by application information label, e.g. all category III applications imply high risk for their application roles.

== Reports and Dashboards

* All special cases (approved exceptions from policy rules)

* SoD policies: all roles with SoD exclusions. All SoD policy rules. Nice to have: all roles that are subject to SoD policy rules (even indirectly).

* SoD violations

* SoD exceptions (approved violations)

* Roles without owners.
Application roles without owners.
Business roles without owners.
Etc.

* Applications without owners.

* Requestable roles without approvers.

* Orphaned accounts

* Active users (dashboard only?)

* Archived users (dashboard only?)

* Temporarily inactive users (exclude archived users)

* "Standing privilege" - manual assignments, including access request

* Privilege assignments to review - manual assignments that were not certified recently

RBAC

* Access included in roles (%)

* Identities with access from roles (%)

Audit

* All accounts created on resource

Later:

* High-risk roles

* High-risk users

== Misc

* "License management" as formal feature?

* "Information classification/labelling" as formal feature?

* Feature idea: self-certification.
User has to certify its own assignments.
User has to confirm that he still needs the privilege.
Maybe as a "zero" stage of regular certification?
+
Important: do not update certification timestamp in this case (or use separate timestamp).
This is not a formal certification, it is just a way to informally clean-up access.

== Work Done So Far

* xref:/midpoint/reference/roles-policies/classification/[]

== List of Necessary Improvements

* xref:/midpoint/features/planned/classification/[]

* xref:/midpoint/features/planned/compliance/[] (old page, needs update)

== Open Questions

* New abstract role subtype "Policy"?

* How to determine classification of a role from classifications of sub-roles and applications?
Similar mechanism should be used to determine risk levels.

* How to make "SoD policy" report?
