= Compliance Design Notes
:page-nav-title: Compliance
:page-toc: top

This page contains design notes on xref:/midpoint/compliance[compliance], thoughts, missing feature description, etc.

== Configuration Changes

Changes we can make in 4.8 using configuration:

* `Project` archetype and root org.
Appropriate `assignmentRelation` for projects: members, managers, owners (stakeholders).

* Compliance dashboard

* Compliance reports

* Pre-defined applicable policies:

** Approval by manager (ISO 27001 5.15, 5.18)

** Approval by role owner (ISO 27001 5.2, 5.15, 5.18)

** Approval by application owner (ISO 27001 5.2, 5.15, 5.18)

** Approval by security office? (Maybe create this only as an example) (ISO 27001 5.2, 5.15, 5.18)

* Idea: pre-defined policySituation for "staff shortage", such as no manager for project, more than two memebers of ciritical team, etc.
Can be used in pre-configured dashboard.

== Missing Features

(Roughly ordered by priority)

* Password management

** dictionary check: enabled by default? Not showing in GUI. (ISO 27001 5.17)

** dictionary check for combination of dictionary words. (ISO 27001 5.17)

** Forcing password change on next login: how can we make it easier to set up? (ISO 27001 5.17)

** Closer integration with AM/SSO? Force password change, last login, etc. (ISO 27001 5.17)

** enforcing different passwords on resources (ISO 27001 5.17 (D))

** "users acknowledge receipt of authentication information" (ISO 27001 5.17)

** [red]*(!!!)* Force change of pre-configured administrator password on first login (ISO 27001 5.17)

** "prevent the use of commonly-used passwords and compromised usernames, password combinations from hacked systems" (ISO 27001 5.17)

** Guidance for end-users how to use password on pages that deal with passwords (ISO 27001 5.17)

** Clean up documentation for password reset (it is in really bad shape)

** Check that we use "approved cryptographic techniques for passwords" (encryption, hashing) (ISO 27001 5.17)


* xref:/midpoint/features/planned/classification/[] (ISO 27001 5.13, 5.8)


* Approval improvements

** Rule of 4 eyes: requestor cannot be approver, even if he is specified as approved in the policy (ISO 27001 5.15, 5.18)

** Handling of situation when there are no valid approvers, e.g. in case the "rule of 4 eyes" disqualified the only approver.  (ISO 27001 5.15)


* Idea: Initial configuration wizard, executed at first login of administrator after installation.

** Change administrator password (if it was not generated)

** Ask for name of organization, set up root object for organizational structure

** Ask for basic archetypes to use? E.g. employee, student, etc.


* Privileged access (ISO 27001 5.15, 5.18, 8.2)

** Make `Privileged Access` label (classification) much more visible in GUI.
Display it at prominent location in details page, maybe find a way how to mark it in lists.
Mark privileged access in certifications. (ISO 27001 5.18)

** Mark for "Privileged access", applied to all objects that deal (directly or indirectly) with privileged access.
Can be used in searching or GUI.

** ConnId pre-defined attribute `PRIVILEGED_ACCESS`, can be used for groups such as `Domain Administrators` or accounts such as `root`.

** Ability to set `Privileged Access` classification on application roles that originated from groups marked as privileged by the connector.


* Provide ability to inform user when gaining a privilege, asking user to confirm acceptance of terms before assigning the privilege. (ISO 27001 5.10)


* Certification of other parts of (abstract) role, most notably policy rules.
For ISO 27001 5.12, re-certification of policy rules included in classification definitions.


* Making sure that certain requirements are fulfilled before assignment is assigned or activated. (ISO 27001 5.12, 5.13, 5.14)

** Making sure user has enrolled multi-factor authentication before accessing classified system.

** Acceptance of "terms of service" by end user before access to the service can be activated. (ISO 27001 5.10)
Note: Similar flow to GDPR consent.


* Shared accounts (ISO 27001 5.16 (b))


* Introduce "asset" as a first-class citizen in midPoint (later, in synergy with risk assessment).


* Risk model


* Risk control related to external identities (social login) (ISO 27001 5.16, 5.19, 5.17)


* Support for passkeys and other non-password credentials? (ISO 27001 5.17) (ISO 24760)

** Default risk of application role may be given by application information label, e.g. all category III applications imply high risk for their application roles.


* Improve instructions on initial password delivery and self-service password reset


* Idea: mark reference to compliance frameworks (e.g. ISO or NIS2) in midPoint objects (e.g. reports).
Could be used by GUI to display "This is part of NIS2 compliance".

== Examples and Configurations

Examples and configuration recommendations that we need to prepare:

[%autowidth]
|===
| Name | Description | Controls | Status

| Policies for information security
| How can midPoint reports help with preparing of security policies?
All policies, all special cases (exceptions), all policy violations, access included in/from roles, ...
| ISO 27001 5.1
| Requirements not clear

| Application and role governance
| Setting up role owners, application owners, security office team.
Using pre-defined "applicable polies" to set up approval.
Setting up basic orgstruct, setting up approval by manager.
Set up certification campaigns, considering role/application owners and managers.
Use minAssignees policy rule to mark roles that are not assigned to anyone, e.g. in case that we have no auditor, or we have less two members of security team (no peer redundancy).

Overlap with "Application/asset management", should we merge?
| ISO 27001 5.2, 5.15, 5.18
| Requirements quite clear

| SoD policy enforcement
| Setting up SoD policy rules, applying gradual enforcement: do not enforce, just report, clean up violations, finally go for full enforcement.
Use dashboard to monitor progress.
| ISO 27001 5.3
| Requirements clear

| Project management
| Use pre-defined archetype and org root to create a project, assign manager, assign members, specify access rights for manager and members.
Authorizations for project manager to modify project (maybe members).
Set up AD project groups.
Set general policy for all projects at the archetype level, e.g. setting policySituation for all projects that do not have a manager.
Include information classification.

See also "Automatic management of access rights".
| ISO 27001 5.8, 5.12, 5.13, 5.14
| Requirements somehow clear, need more work

| Application/asset management
| Setting up application inventory, specifying owners and classifications for applications.
Use dashboard to find applications/roles without owners/classifications.

Overlap with "Application and role governance", should we merge?
Should we specialize this example for use of dashboards?
| ISO 27001 5.9
| Requirements not clear

| Audit log analysis
| Use audit log viewer and object history to find access rights of a person in the past?
| ISO 27001 5.10
| Requirements not clear

| Information classification
| xref:/midpoint/reference/roles-policies/classification/[]

Improvements: external access (5.14), include the clearance in archetype+NDA, certification
| ISO 27001 5.12, 5.13, 5.14
| Done, needs improvement (xref:/midpoint/features/planned/classification/[])

| Delegated business role maintenance
| Delegate creation and maintenance of business roles to business users, using role wizard.
Use "applicable policies" to set up access-and-approval scheme.
Use pre-congifured policies for app-owner and role-owner approval, setup of approval by manager.

Overlap with "Application and role governance", should we merge?
| ISO 27001 5.15, 5.18
| Requirements not clear yet

| Incident response
| Manually deactivate a user, e.g. after he was fired.
We do it manually, because HR recon is slow.
Force password change for a large number of users.
| ISO 27001 5.17, 5.18
| Requirements not clear yet

| Automatic management of access rights
| Inducement from orgstruct, role autoassignment, org template autoassignment.
Reuse parts of the book.
| ISO 27001 5.8, 5.18
| Requirements quite clear

| Orgstruct automation
| Inducement from orgstruct.
Micro-certification on orgstruct membership change.
| ISO 27001 5.18
| Requirements incomplete, need to add more

|===

Fit into some scenarios:

* Deliver "acceptable use" statement to user when account is created on a system (notifications). (ISO 27001 5.10)

More ideas:

* Managing privileged access: using the "Privileged access" classification

* Classifications based on TLP protocol

* SANS classification scheme

* Concrete and complete examples on password management, including initial password delivery and self-service password reset

== Reports and Dashboards

* All policies (ISO 27001 5.1)

* All policy violations (ISO 27001 5.1)

* All special cases (approved exceptions from policy rules) (ISO 27001 5.1?, 5.2)

* SoD policies: all roles with SoD exclusions. All SoD policy rules. Nice to have: all roles that are subject to SoD policy rules (even indirectly). (ISO 27001 5.3)

* SoD violations (ISO 27001 5.3)

* SoD exceptions (approved violations) (ISO 27001 5.3)

* Roles without owners.
Application roles without owners.
Business roles without owners.
Etc. (ISO 27001 5.2)

* Applications without owners. (ISO 27001 5.2, 5.9)

* Applications without classification. (ISO 27001 5.9, 5.12, 5.13, 5.14)

* Requestable roles without approvers. (ISO 27001 5.2, 5.15, 5.18)

* Active projects without managers (ISO 27001 5.8)

* Staff shortage (dashboard): projects and teams with vacancies at important positions.

* Orphaned accounts (ISO 27001 5.16)

* Active users (dashboard only?) (ISO 27001 5.16)

* Archived users (dashboard only?) (ISO 27001 5.16)

* Dormant users / sleepers (users without any privileges) (ISO 27001 5.16)

* Temporarily inactive users (exclude archived users) (ISO 27001 5.16)

* "Standing privilege" - manual assignments, including access request (ISO 27001 5.15, 5.18)

* Privilege assignments to review - manual assignments that were not certified recently (ISO 27001 5.18)

RBAC

* Number of roles by type (ISO 27001 5.1, 5.15, 5.18)

* Access included in roles (%) (ISO 27001 5.1, 5.15, 5.18)

* Identities with access from roles (%) (ISO 27001 5.1, 5.15, 5.18)

* Unused roles (roles without active assignment) (ISO 27001 5.1, 5.15, 5.18)

* Idea: some role hierarchy metric? How many roles are included in other roles?

Audit

* All accounts created/deleted on resource (ISO 27001 5.10, 5.16, 5.18)

* Roles assigned/unsassigned, automatically/manually (ISO 27001 5.10, 5.16, 5.18)

Later:

* High-risk roles

* High-risk users

NOTE: "Without owner" shoudl really mean "whithout active owner".
Only active users should be considered valid owners.

== Misc and Notes

* "License management" as formal feature? (ISO 27001 5.11)

* Feature idea: self-certification.
User has to certify its own assignments.
User has to confirm that he still needs the privilege.
Maybe as a "zero" stage of regular certification?
+
Important: do not update certification timestamp in this case (or use separate timestamp).
This is not a formal certification, it is just a way to informally clean-up access.

* ISO 27001 is often referencing "assets", which in our parlance refers to application.
This makes the policies quite application-centric, rather than role-centric.
E.g. approval by application owners, rather than role owner.

== Work Done So Far

* xref:/midpoint/reference/roles-policies/classification/[]

== List of Necessary Improvements

* xref:/midpoint/features/planned/classification/[]

* xref:/midpoint/features/planned/compliance/[] (old page, needs update)

* Docs: link features to IGA capabilities

* Docs: ISO27001 controls: show "Implementation plan" section (when we are ready)

* Docs: Link ISO27001 controls to IGA capabilities?

* Docs: Show ISO27001 control type (e.g. #preventive), concepts and other attributes?
Is it legal? (copyright)

* Docs: Highlight ISO27001 controls that are closely related to IGA (capability==#Identity_and_ac-
cess_management?)

== Open Questions

* New abstract role subtype "Policy"?

* How to determine classification of a role from classifications of sub-roles and applications?
Similar mechanism should be used to determine risk levels.

* How to make "SoD policy" report?

* Licence management as a feature? (ISO 27001 5.11)
What do we need to do? License archetype?

* Certification for classifications: replacing assignment of classification, instead of removing it?

