= Compliance Design Notes
:page-nav-title: Compliance

This page contains design notes on xref:/midpoint/compliance[compliance], thoughts, missing feature description, etc.

== Configuration Changes

Changes we can make in 4.8 using configuration:

* `Project` archetype and root org.
Appropriate `assignmentRelation` for projects: members, managers, owners (stakeholders).

* Compliance dashboard

* Compliance reports

== Missing Features

* User schema

** `clearance`: multi-value, list of clearances. e.g. NDAs, formal clearances to secret documents, user categories (external, internal), knowledge gained at mandatory trainings (e.g. security training, health and safety briefing), etc.
May be as simple as list of strings, but it will be better to have it more structured (e.g. clearances as roles?).
In that case it may not be an attribute at all, we can just use assignment and special archetype.

* Abstract role / all objects schema

** `informationLabel`: multi-value, list of information labels that this object has.
This may be formal confidentiality label such as "top secret", system category (NIS1-SK "category III"), etc.
Should be similar to user clearance.

* Risk model

** Default risk of application role may be given by application information label, e.g. all category III applications imply high risk for their application roles.

== Reports and Dashboards

* All special cases (approved exceptions from policy rules)

* SoD policies: all roles with SoD exclusions. All SoD policy rules. Nice to have: all roles that are subject to SoD policy rules (even indirectly).

* SoD violations

* SoD exceptions (approved violations)

* Roles without owners.
Application roles without owners.
Business roles without owners.
Etc.

* Applications without owners.

* Requestable roles without approvers.

* Orphaned accounts

* Active users (dashboard only?)

* Archived users (dashboard only?)

* Temporarily inactive users (exclude archived users)

* "Standing privilege" - manual assignments, including access request

* Privilege assignments to review - manual assignments that were not certified recently

RBAC

* Access included in roles (%)

* Identities with access from roles (%)

Audit

* All accounts created on resource

Later:

* High-risk roles

* High-risk users

== Misc

* "License management" as formal feature?

* "Information classification/labelling" as formal feature?

* Feature idea: self-certification.
User has to certify its own assignments.
User has to confirm that he still needs the privilege.
Maybe as a "zero" stage of regular certification?
+
Important: do not update certification timestamp in this case (or use separate timestamp).
This is not a formal certification, it is just a way to informally clean-up access.

== Open Questions

* Information classification model. Can we use (archetyped) roles?
New abstract role subtype "Policy"?

* How to determine informationLabel of a role from informationLabels of sub-roles and applications?
Similar mechanism should be used to determine risk levels.

* How to make "SoD policy" report?
