= DOT renderer troubleshooting
:page-wiki-name: DOT renderer troubleshooting
:page-wiki-id: 22741549
:page-wiki-metadata-create-user: mederly
:page-wiki-metadata-create-date: 2016-06-18T13:34:25.160+02:00
:page-wiki-metadata-modify-user: mederly
:page-wiki-metadata-modify-date: 2020-03-31T19:36:30.739+02:00


[WARNING]
.EXPERIMENTAL
====
This feature is *xref:/midpoint/versioning/experimental/[experimental]*. It means that it is not intended for production use.
The feature is not finished.
It is not stable.
The implementation may contain bugs, the configuration may change at any moment without any warning and it may not work at all.
Use at your own risk.
This feature is not covered by midPoint support.
In case that you are interested in xref:/support/subscription-sponsoring/[supporting] development of this feature, please consider purchasing link:https://evolveum.com/services/professional-support/[midPoint Platform subscription].

====

MidPoint currently uses link:https://en.wikipedia.org/wiki/DOT_(graph_description_language)[DOT graph description language] to visualize configurations of resources.
It generates DOT files and sends them to external _DOT renderer_ to convert them to SVG format.
Such renderers are usually part of the link:https://en.wikipedia.org/wiki/Graphviz[Graphviz] package.

So, in order to make the visualization work in your case, please install Graphviz on your midPoint server and check that you can execute the following command:

[source]
----
$ dot
----

This command (with the argument of `-Tsvg` to provide SVG output) is used by midPoint to render DOT files as SVG pictures.


== Configuration

You can configure the DOT renderer by specifying the respective command in `config.xml` file under `configuration/midpoint/dot/renderer`  key, like this:

[source]
----
<configuration>
   <midpoint>
      <dot>
	     <renderer>/path/to/dot/executable</renderer>
      </dot>
      ...
   </midpoint>
</configuration>
----

The default value is `dot` that works well with the default installation of Graphviz.

Note that `-Tsvg`  parameter is always appended to the command specified.
The input DOT file is then sent as a standard input to the process, expecting SVG on standard output.


== Versions

DOT rendering of resource configurations should work with any reasonably recent Graphviz version.
It was tested with 2.38.0.