= Object Names and Labels
:page-wiki-name: Object Names and Labels
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2019-09-02T11:25:56.605+02:00
:page-wiki-metadata-modify-user: petr.gasparik
:page-wiki-metadata-modify-date: 2019-09-02T13:14:52.939+02:00

There may be some confusion how to use object name, label, singular and plural forms.

* *name* is an identifier.
It has to be unique.
It may have a human-friendly form, but it may not.
Primary responsibility of name is to identify the object.

* *display/label* is a human-friendly label of the object.
It describes the object itself, not its members.
Therefore if it is a collection or archetype, it is the name of the collection or archetype.

* *display/singularLabel* (collections only) is a label used for a single member of a collection.
It can be used only for objects that can act as collections and only if they act as collections.
This label can be used to refer to each individual member of the collection.

* *display/pluralLabel* (collections only) is a label used for members of a collection when mentioned collectively.
It can be used only for objects that can act as collections and only if they act as collections.

Why do we need plural/singular forms? Because label is not ambiguous.
Roles and archetypes will typically have label in a singular form ("Admin", "Employee"). While object collections will typically be labeled in plural form ("All tasks", "Active users"). Orgs can be either way ("Project X", "Retired employees"). Therefore we do not have a clear way how to display labels for collections.
Therefore explicit singular/plural labels make it clear.


== Capitalization Rules

TODO: Generaly use sentence case, i.e. capitalize only the first letter


== Examples

[%autowidth,cols="h,1,1,1,1,1,1,1"]
|===
| Property | UserType | RoleType | ArchetypeType | ObjectCollectionType | OrgType | View | View

| name
| `jdoe`
| `admin`
| `Employee`
| `active users`
| `P007`
|
|

| display/label
| `John Doe` +
_but use of fullName is the usual practice_
| `Admin`
| `Employee` +
_or_ +
`Employee archetype` +
_but the "archetype" suffix is not recommended_
| `Active users`
| `Project X`
| `My cases`
| `All users`


| display/singularLabel
| N/A +
_this cannot be collection_
| `Admin` +
_but usually not specified_
| `Employee`
| `Active user`(not yet in schema)
| `Entity involved in Project X` +
_but use of this is not recommended,  +
automatic label should be better,  +
e.g. "Member of Project X", "Manager of Project X"  (derived from relation)_
| `My case`
| `User`


| display/pluralLabel
| N/A +
_this cannot be collection_
| `Admins`
| `Employees`
| `Active users +
`_(not yet in schema)_
| `Entities involved in Project X` +
_but use of this is not recommended, +
automatic label should be better,  +
e.g. "Members of Project X", "Managers of Project X" (derived from relation)_
| `My cases`
| `All users`


| archetypePolicy/ +
    display/label
|
|
| `Employee` +
_this specifies name of the [.underline]#type# as users should see it_
|
|
|
|

| archetypePolicy/ +
    display/singularLabel
|
|
| `Employee`
|
|
|
|


| archetypePolicy/ +
    display/singularLabel
|
|
| `Employees`
|
|
|
|

|===


== See Also

* wiki:Archetypes+Design+Notes[Archetypes Design Notes]

* wiki:Object+Collections+and+Views[Object Collections and Views]