= Understanding ApprovalSchemaExecutionInformationType
:page-wiki-name: Understanding ApprovalSchemaExecutionInformationType
:page-wiki-id: 24674890
:page-wiki-metadata-create-user: mederly
:page-wiki-metadata-create-date: 2017-08-02T15:14:53.839+02:00
:page-wiki-metadata-modify-user: mederly
:page-wiki-metadata-modify-date: 2017-08-02T16:44:27.491+02:00

This information can be obtained from workflowManager e.g. by calling getApprovalSchemaExecutionInformation (requires approval task OID).

It contains information about individual stages of approval:

. for the current stage and previous ones, we can provide exact information - see ApprovalStageExecutionRecordType:

.. events related to the stage (showing decisions done and automated completion events),

.. active work items (for current stage only),



. for future stages, we provide estimates - see ApprovalStageExecutionPreviewType:

.. expectedApproverRef,

.. expectedAutomatedOutcome,

.. expectedCompletionReason,

.. errorMessage (if anything went wrong during preview).



TODO