= Simulations in Model
:page-since: 4.7
:page-toc: top

How should we execute the simulations at the "model" level, i.e. in the Projector, Clockwork, and related components?

The idea is to isolate the "model" from the rest of midPoint using a barrier that will distribute requests (get, search, add, modify, delete operations) to appropriate components: repository, provisioning, task manager, case manager, and _simulation data store_.

NOTE: The question is whether the simulation data store should live alongside provisioning or at the level of repository module.

== First Version

The simulation data store will only "accept" deltas that are to be executed.
It will not process them in any way.

== Later Versions

The simulation data store will execute the deltas by creating a new _variant_ of any object touched.

== Open Questions

. What if we try to add `linkRef` value with embedded shadow pointing to a development resource or object class/type?
Unless (until) simulated shadows are supported, we must not create such a shadow.
Currently, we silently drop the request and skip `linkRef` value creation.
Should we report at least a warning, or even a partial error?
