= Shadows in "Simulation Mode"
:page-since: 4.7
:page-toc: top

Not all shadows are equal.

Some are production, others are non-production, simulated, temporary, preview, or whatever terms we will create for them.
The basic distinctions are:

[%autowith]
[%header]
|===
| Feature | Production shadows | Non-production shadows | Note
| Creation when resource object is seen | yes | yes | 1
| Update when resource object is seen | yes | yes | 1
| Classification | once | each time the object is fetched |
| Correlation | if no owner | if no owner | 2
| Synchronization | full | none | 3
|===

Notes:

. Both types of shadow are created and updated as soon as the corresponding resource object or its delta is seen.
(At least for now.)
. The algorithm of correlation (i.e. determining the shadow owner) is the same for both kinds.
. However, even if the owner for a non-production shadow is determined, the linkage will _not_ occur.
#TODO is this OK? Think again!#

== Determining the Shadow Mode

When a resource object is seen, a shadow is created.
Its mode is determined by looking at the mode of the resource and/or the corresponding object type.
(#TODO# what about refined object classes?)

So, if the resource and the corresponding object type is in production mode, the shadow is created as production.
Otherwise, it is created as non-production.

== Updating the Shadow Mode

* It is done in `ShadowManager.updateShadowInRepository` method, i.e.
** after successful on-resource `getObject` operation,
** during processing of the object found (`ShadowedObjectFound`),
** during processing of the change (`ShadowedChange`).

WARNING: Although the usual change here is from non-production to production mode, nothing prevents a shadow from being switched from production back to non-production.
#Are we OK with that? What if the shadow has already an owner?#

== Open Questions

* TODO: Splitting an object type definition ...
* Other moments for updating the shadow mode? E.g. non-resource `getObject` operations?

