= Shadows in "Simulation Mode"
:page-since: 4.7
:page-toc: top

Not all shadows are equal.

Some are production, others are non-production (simulated, temporary, preview, or whatever terms we will create for them).
They differ in behavior, and that depends on the configuration of the respective object class or object type, and the overall execution mode.

== Shadows Creation

The current task can be executing either in a production or a simulation mode.
A resource object is encountered by such a task.
The whole resource or a particular object class can be in production or a non-production mode.footnote:[Represented e.g. by `active` or `proposed` lifecycle state.]
A classification may be executed, leading to a specific object type.
The type itself can be in production or a non-production mode.

Overall, we have four possibilities:

- task execution mode: production or simulation,
- object class or type mode: production or non-production.

.Mode of shadow created
[%autowidth]
[%header]
|===
| Task execution mode \ Object class or type mode | Production | Non-production
| Production | production | simulated
| Simulation | production (most probably) | simulated
|===

== Working with Shadows Afterwards

[%autowidth]
[%header]
|===
| Feature / Situation | Production shadows in production task | Production shadows in simulation task | Non-production shadows in production task | Non-production shadows in simulation task | Note
| Updatefootnote:[Identifiers or cached attributes, auxiliary object class info, ...] when resource object is seen | yes | yes | yes | yes | 1
| Classification | once | ?? | ?? | each time the object is fetched |
| Correlation | if no owner | if no owner | if no owner | if no owner | 2
| Synchronization | full | ?? | ?? | none | 3
|===

Notes:

. "Simulation" configuration should not differ from the production one in substantial things, like what identifiers are there, attribute types, attribute caching.
. The algorithm of correlation (i.e. determining the shadow owner) is the same for both kinds.
. However, even if the owner for a non-production shadow is determined, the linkage will _not_ occur.
#TODO is this OK? Think again!#

== Updating the Shadow Mode

* It is done in `ShadowManager.updateShadowInRepository` method, i.e.
** after successful on-resource `getObject` operation,
** during processing of the object found (`ShadowedObjectFound`),
** during processing of the change (`ShadowedChange`).

WARNING: Although the usual change here is from non-production to production mode, nothing prevents a shadow from being switched from production back to non-production.
#Are we OK with that? What if the shadow has already an owner?#

== Side Effects of Provisioning Operations

=== Getting the Shadows

==== Regular Mode
. Quick or full shadow refresh - before the GET issued against resource (or after the repo load if noFetch is set).
Arbitrary pending operation can be executed. The shadow may be even deleted by the refresh.
. Discovery process (an event is sent to the listener, typically to model).
. Shadow is updated with the information obtained from the resource:
- cached identifiers and/or other attributes,
- `dead` and `exists` properties,
- (anything else?)
. ...

==== Preview Mode
. No refresh, no execution of pending operations.
. No discovery
. What if we simply not updated the shadow if it is a production one?

== Open Questions

* TODO: Splitting an object type definition ...
* Other moments for updating the shadow mode? E.g. non-resource `getObject` operations?

