= Tagging as a New Feature

NOTE: This is just to record an idea that appeared on a simulations-related design meeting.

_Tagging_ could be a way to implement complex queries, i.e. such that take too long to execute or are even impossible to formulate via current Query API.

Each tag would be connected to a query - or maybe a completely custom code - that would determine if any object being processed (typically, by the clockwork) should be marked with the tag or not.

Such tags can be:

- displayed to users,
- searched for,
- recorded in the audit log, e.g. by listing the changed or actual tags along with each audit record,
- used for dashboards, along with the trends,
- and so on.

Maybe they could be stored separately from the regular object data (?).

Related mechanisms:

- mappings that fill an extension property (that is long-used poor man's tagging),
- policy situations,
- simulation tags (these are not the same as these "production" tags),
- "administrator" tags (see right below).

== "Administrator" Tagging

A related but distinct feature is the tagging done by the administrator himself.
He or she will be able to tag (and untag) any object with a custom mark.
The dictionary of available tags would be customizable.

This is somehow related also to the Shadow Marks feature.
