---
layout: connector-page
display-order: 200
functionality-status: stable
development-status: abandoned
support-status: unsupported
origin: ICF
target-systems: Atlasian Jira server
connector-protocol: REST
source-url-master: https://github.com/Evolveum/connector-jira-rest
description: Identity connector for Atlasian Jira server.
connid-bundle-name: com.evolveum.polygon.connector.jira.rest
upkeep-status: green
---
= Jira Connector
:page-wiki-name: Jira Connector
:page-wiki-id: 24675299
:page-wiki-metadata-create-user: ssurmanek
:page-wiki-metadata-create-date: 2017-09-12T12:18:47.066+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-07-09T14:38:53.270+02:00

WARNING: Maintenance of this connector was stopped.
Support for this connector may be provided if there is enough financial incentive to resume the maintenance.


JIRA Connector is REST connector for execution basic CRUD operations for accounts, projects and groups and operations related to group or projects membership. Connector uses API version 2 and was implemented for JIRA server 7.2.7.

== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| *Provisioning*
| YES
|

| *Live Synchronization*
| NO
|

| *Password*
| YES
|

| *Activation*
| NO
| Not implemented because activation requires plugin Extender for JIRA.

| *Paging support*
| YES
| Just for Account Object Type.

| *Native attribute names*
| YES
| Except for Administrators.users, Administrators.groups, Developers.users, Developers.groups, binaryAvatar

| *Scripting*
| NO
|

|===

== Licensing

The connector itself is available under the terms of Apache License 2.0. To our best knowledge there is no extra license needed to use this connector.

== Versions

[%autowidth]
|===
| Version | Origin | Binary | Samples | Sources | Build Date | Framework version | Description

| 1.0
| Polygon
|
|
| link:https://github.com/Evolveum/midpoint/tree/master/samples/resources/scriptedrest/jira[GitHub]
| N/A
|
| Only for push and get profile avatar picture with resizing - Deprecated

| 2.0
| Polygon
| Download jar
| GitHub
| link:https://github.com/Evolveum/connector-jira-rest.git[GitHub]
| September 12th 2017
| 1.4.2.14
| Stable version

|===

== Limitations

Connector operates with some limitations, which were detected during implementation:

* username cannot contain characters '<', '>' or '&'.

* email address cannot contain any special characters (except for '-', '\_').

* project keys must start with an uppercase letter, followed by one or more uppercase alphanumeric characters.

* groups and projects do not support paging (API v2 supports just option for maximum number of returned groups.

* when creating groups response does not provide UID (connector uses groupname as UID).

* user activation is provided only when Extender for JIRA plugin is  installed.

=== Filters

Connector supports following filters and filter

[%autowidth]
|===
|  | EQUALS | CONTAINS | STARTSWITH | CONTAINSALLVALUES

| *Account Objects*
| name, UID
| all attributes
| all attributes
| -

| *Group Object*
| name, UID
| name
| -
| -

| *Project Objects*
| UID
| all attributes  +
except lead
| -
| Administrators.usersAdministrators.groupsDevelopers.usersDevelopers.groups

|===


* *Starts With**Filter* for Accounts uses just username as the query parameter but JIRA API filters values of all attributes.
*Contains Filter* works same as Starts With Filter.

* *Contains**Filter *and *Contains All Value**Filters* for Projects operate thanks to all obtained values filtering on connector side (all projects or all actors)

== Configuration

Connector configuration requires three property fields, which are mandatory:

* *baseUrl* - connecting to JIRA server (structure: _<ip_address>_:_<port>_)

* *username, password* - authentication

== Tests

JIRA Connector involves package of test classes.
Tests are divided into classes:

* according to ObjectTypes for basic and negative testing,

* for performance tests,

* and for configuration validity and connection tests.

Basic tests use attributes with values containing valid special characters (subset of 'ľščťž$#@%^\*(?' ) for create, update operation tests and schema consistency test.
Filtering and listing tests are divided into methods according to possible filters and options for each object type.

[TIP]
====
Tests implementation expects that users, groups and projects with the same or similar attribute values as used in tests do not exist in JIRA environment.
====

Configuration properties are written into static variables of JiraTestHelper class.
All the test classes contains cleanUp methods for reverting state of JIRA environment into initial state after test failure and thrown exception.
CleanUp methods are called within connector initialization test initTest in each test class separately for each Object type.