= IGA Use Cases: Operations and Data Governance
:page-nav-title: Operations use-cases
:page-display-order: 200
:page-toc: top
:toclevels: 3
:sectnums:
:sectnumlevels: 3

WARNING: This page is a work in progress.

Following use-cases are defined in the area of operations and data governance.

Operation teams are managing IGA data of individual users or objects and/or of bulk of objects.



== Single object operations

=== Modify roles without approval

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Modify role assignments without approval

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Recompute the role assignments

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Troubleshoot the recompute operation

Scenario::

Actors::

Motivation::

User Story::

#TODO#

[#_approvereject_request_on_behalf]
=== Approve/Reject request on behalf

Scenario::
An manager can't technically perform approval, but he decided offline. The operation must be performed by IGA team. It should be documented in the approval.
+
The operation may relate to both approvals in access request process and in the role engineering process.

Actors::
The operation should be performed by IGA operator, IGA administrator or Role manager.

Motivation::
Some situations require fast approval when the approver is not available. This operation allows to overcome such critical situation.

User story::
IGA operator with sufficient privileges opens the defined request and approves/rejects it. The approval process proceed to next step. The operation is listed in the approval log as "Approved by <real approver - the IGA operator> on behalf of <original approver>".

Probably this operation should have individual authorization, as some deployment may not allow this scenario.

== Bulk operations

[#_define_set_of_usersobjects_for_bulk_operation]
=== Define set of users/objects for bulk operation

Scenario::
The IGA operator must perform an operation over list of users (or other objects) he obtained. There is no specific query for defining the users.

Actors::
Typically, this is performed by IGA operator or IGA administrator.

Motivation::
When managing bulk of objects, the operators must be able to define the set by specific query, or just by listing the users - because there is not anything common to define the query. Sometimes the list of users may contain thousands of names

User Story::
When running some bulk task, the set of users for bulk operations may be defined by specific query, or just by list of users (object). The list of objects is provided externally in the form of csv file.
+
The IGA operator or administrator writes the query for bulk task or uploads this list of users as a source for the bulk task and runs the task.
+
Note: The objects in csv should be defined by one of unique attributes - typically name. It may be large (up to number of users in mp).

=== Update attributes / assignments for set of users

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== #TODO#

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== #TODO#

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== #TODO#

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== #TODO#

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== #TODO#

Scenario::

Actors::

Motivation::

User Story::

#TODO#