= IGA Use Cases: Operations and Data Governance
:page-nav-title: Operations use-cases
:page-display-order: 200
:page-toc: top
:toclevels: 3
:sectnums:
:sectnumlevels: 3

WARNING: This page is a work in progress.

Following use-cases are defined in the area of operations and data governance.

Operation teams are managing IGA data of individual users or objects and/or of bulk of objects. Most (if not all) the tasks should be performed using GUI.

== Single object operations

Normally, IGA operators and administrators perform actions based on some tickets or decision of responsible persons (e.g. Role manager or Security officer). They need to perform some operations out of standard approval process, otherwise the process would be very complex.

=== Modify role without approval

Scenario::

Actors::

Motivation::
This operation is needed sometimes in specific situations and for some fields - e.g. changing owner when original owner left and can't approve, or changing some typos in description, or some reconstructions.

Open question: how to define such operation. Whether by fields, or leave whole role for specific modification and just log it to audit. Then identification of this specific operation in audit is needed.

User Story::

#TODO#

=== Modify role assignments without approval

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Recompute the role assignments

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Troubleshoot the recompute operation

Scenario::

Actors::

Motivation::

User Story::

#TODO#

[#_approvereject_request_on_behalf]
=== Approve/Reject request on behalf

Scenario::
An manager can't technically perform approval, but he decided offline. The operation must be performed by IGA team. It should be documented in the approval.
+
The operation may relate to both approvals in access request process and in the role engineering process.

Actors::
The operation should be performed by IGA operator, IGA administrator or Role manager.

Motivation::
Some situations require fast approval when the approver is not available. This operation allows to overcome such critical situation.

User story::
IGA operator with sufficient privileges opens the defined request and approves/rejects it. The approval process proceed to next step. The operation is listed in the approval log . E.g. as "Approved by <real approver - the IGA operator> on behalf of <original approver>".

Probably this operation should have individual authorization, as some deployment may not allow this scenario.

== Bulk operations

[#_define_set_of_usersobjects_for_bulk_operation]
=== Define set of users/objects for bulk operation

Scenario::
The IGA operator must perform an operation over list of users (or other objects) he obtained. There is no specific query for defining the users. The list is obtained externally - not from midPoint. E.g. in the form of csv file.

Actors::
Typically, this is performed by IGA operator or IGA administrator.

Motivation::
When managing bulk of objects, the operators are defining the search filters by query. Sometimes, the query is not good solution, as
they need to perform operation on set of objects that does not have anything in common to build a well readable query.
+
Defining query by naming all users is not practical and not well readable. Importing such list as scope definition for bulk task or bulk action would help the operator to solve the problem easily.

User Story::
The IGA operator or administrator upload the list of objects (in csv form to midPoint). Then he prepares the bulk task or bulk operation definition and references the uploaded file as source in the search filter. Then he performs the operation.
+
Note: The objects in csv should be defined by one of unique attributes - typically name. It may be large (up to number of users in mp).

=== Update attributes / assignments for set of users
E.g. Disable/enable set of users

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Update attributes for set of roles
E.g. change ownership or approver of set of roles when user leaves.

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Change approver of pending requests
E.g. when person leaves the company and some approvals are left opened.

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== List and compare attributes for set of users

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== List and compare role assignments (access) for set of users

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== List and compare entitlements for set of users

Scenario::

Actors::

Motivation::

User Story::

#TODO#