= IGA Use Cases: Role Engineering and Governance
:page-nav-title: Role engineering use-cases
:page-display-order: 100
:page-toc: top
:toclevels: 3
:sectnums:
:sectnumlevels: 3

WARNING: This page is a work in progress.

Following use-cases are defined in the area of role engineering and governance.

// High level - ze sluzi na pripravu struktury roli - prepojenie business a technologickej vrstvy - vytvorenie business modelu pre riadenie pristupov v organizacii.
// Ze vyzaduju samostatny approval process.

== Role creation

[#_create_application_role]
=== Create application role

Scenario::
Application engineer wants to start managing access to the particular role / privilege in the application via IGA solution.

Actors::
Typically this operation should be performed by engineer or owner of the application that is being integrated with IGA solution - the application engineer in cooperation with IGA administrator.
+
The operation may be initiated upon request of Security officer or Role manager.

Motivation::
The application role is key component interconnecting business and IT world of access management. It is hiding technical components of access from the business users.
End-users interact with application roles and business roles business to manage and review their access.

User Story::
====

#The story for creating of application role is described in xref:../role-engineering/index.adoc[Role engineering and maintenance process] page.#
+
#TODO - rewrite the scenario here#

Toto je o tom, ze application engineer navrhne rolu - navrhne, ako ma vyzerat.
====

[#_create_business_role]
=== Create business role

Scenario::
Business manager or Role manager wants to organize access to multiple applications to one business role - to better represent some business position.

Actors::
Typically this procedure is initiated by an business manager or IGA Role manager. It may be performed by business users with higher privileges - *power user*, *Role manager* or *IGA administrator*.
+
The *author* of the role is typically the business user.

Motivation::
Structuring of application roles to business roles enables mapping user access to organization needs and increases readability of user access. Creation of business roles for specific projects or business tasks helps business users during self-service.

User Story::
The story for creating of business role is described in xref:../role-engineering/index.adoc[Role engineering and maintenance process] page.
+
#TODO - rewrite the scenario here#

[#_create_new_application]
=== Create New Application

Scenario::
Application engineer wants to start managing access to an application via IGA User Story::. He needs to create new application in IGA, define all roles for the application and start using them in role definition and access request.

#When the application is integrated, maybe the <upratanie user accessu je potrebne > - pokial uz bola aplikacia pouzivana predtym#

Actors::
* Application engineer
* IGA administrator
* Role manager

Motivation::
Application engineer wants to integrate his application with IGA User Story::, so the access to his application can be managed by IGA.

User Story::
#TODO#
# Tu musim doplnit jednotlive kroky - mozno z toho bude treba este urobit jednotlive use-cases#

== Role modification

=== Modify business attributes of application role

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Modify provisioning configuration of application role

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Modify content of business role

Update of business role is probably the most common operation in the process.

Most often it is the addition or removal of an application role from the business role. Specific workflow may be defined for  this operation. Because 2 roles are affected - the business role being modified and also the application role that will be included into the business role. Owners of both roles should approve this operation.

Scenario::

Actors::

Motivation::

User Story::

#TODO#


== Role decommissioning

=== Remove role
#TODO - see Role decommissioning#

Scenario::
There may be different situations why the role needs to be deleted. E.g.:
* Role owner of application role wants to remove the role, because the application access model is changed and the role is
* Role owner of business role wants to remove the role, because the business function is being decommissioned.
* Role manager performs role cleanup / organization structure is changing and the role becomes obsolete.

Actors::
The operation may be performed by business people as well as aby administrators. This operation should g through normal approval process

Open question: Should we allow the operation to be performed by business people (business manager deleting business role) ?

#Open question: When Role manager performs cleanup ? Should he still go through approval process ?#

Motivation::
Performing cleanup of the roles is necessary. When IGA solution allows easy role removal, then more clean environment is being kept.

Open question: Normally, business teams will not request for this - well, maybe we don't need to implement role removal as a process.

#users access must be handled when the role is being decommisioned#

User Story::
#Standard role removal must go through approval process, if the#

#TODO#

=== Decommission application

Scenario::

Actors::

Motivation::

User Story::

#TODO#


== Other
=== Define approval policy

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Define auto-assignment rule for specified role

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Update/remove role auto-assignment

Scenario::

Actors::

Motivation::

User Story::

#TODO#
