= IGA Use Cases: Role Engineering and Governance
:page-nav-title: Role engineering use-cases
:page-display-order: 100
:page-toc: top
:toclevels: 3
:sectnums:
:sectnumlevels: 3

WARNING: This page is a work in progress.

Following use-cases are defined in the area of role engineering and governance.

== New role

Following use-cases are identified for creation of new roles.

* Creation of application role
* Creation of business role
* Deployment of new application - definition of all roles for the application

[#_new_application_role]
=== New application role

Scenario::
Application engineer wants to start managing access to the particular role / privilege in the application via IGA solution.

Actors::
Typically this operation should be performed by engineer or owner of the application that is being integrated with IGA solution - the *application engineer* - in cooperation with *IGA administrator*.
+
The operation may be initiated upon request of Security officer or Role manager.

Motivation::
The application role is key component interconnecting business and IT world of access management. It is hiding technical components of access from the business users.
End-users interact with application roles and business roles business to manage and review their access.

Solution::
The story for creating of application role is described in xref:../role-engineering/index.adoc[Role engineering and maintenance process] page.
+
#TODO - rewrite the scenario here#

[#_new_business_role]
=== New business role

Scenario::
Business manager or Role manager wants to organize access to multiple applications to one business role - to better represent some business position.

Actors::
Typically this procedure is initiated by an business manager or IGA Role manager. It may be performed by business users with higher privileges - *power user*, *Role manager* or *IGA administrator*.
+
The *author* of the role is typically the business user.

Motivation::
Structuring of application roles to business roles enables mapping user access to organization needs and increases readability of user access. Creation of business roles for specific projects or business tasks helps business users during self-service.

Solution::
The story for creating of business role is described in xref:../role-engineering/index.adoc[Role engineering and maintenance process] page.
+
#TODO - rewrite the scenario here#

[#_deployment_of_new_application]
=== Deployment of New Application

Scenario::
Application engineer wants to start managing access to an application via IGA solution. He needs to define all roles for the application in IGA.

Actors::
TODO

Motivation::
TODO

Solution::
TODO

== Role Modification

TODO

== Role Decommissioning

TODO
