= IGA Use Cases: Role Engineering and Governance
:page-nav-title: Role engineering use-cases
:page-display-order: 100
:page-toc: top
:toclevels: 3
:sectnums:
:sectnumlevels: 3

Following use-cases are defined in the area of role engineering and governance.

The main goal of the role engineering use-cases is interconnection of technological and business layer of access management - by developing of role objects and interconnecting them to hierarchical structure. This will build the business model for management of access in the organization.

NOTE: Fot the time being, the operations over the roles are not approved or otherwise processed. The operations should be performed by IGA engineer, IGA operator or Role manager.

////
The approval process is too complex to be implemented now.
These use-cases require approval process independent of access request process.

Following actors are active in the use-cases:

* *Author* - the person, who created the request for the role.
** _Application engineer_ is typically author of application roles.
** _Business user_ is typically author of business roles.
* *Role Owner* - performs decisions of role modifications and assignments. It is often the _application engineer_ for application roles and _business manager_ for business roles.
* _IGA administrator_ - reviews the roles and applications definitions and verify them from the viewpoint of technical accuracy and processing details.
* _Role manager_ - governs the roles structure. Reviews the roles from the view of their position in the whole model and business functionality.
////

== Role creation

[#_create_application_role]
=== Create application role

Scenario::
Application engineer wants to start managing access to the particular role/privilege in the application via IGA solution. He wants to create new role. The operation is performed by _IGA administrator_.
+
The application, that the role should be related to, is already prepared in the midPoint.

Actors::
Typically this operation should be performed by _IGA administrator_ upon request of _Application engineer_ (i.e. engineer or owner of the application that is being integrated with IGA solution), _Security officer_ or _Role manager_.

Motivation::
The application role is key component interconnecting business and IT world of access management.
It is providing standard business description of the access to end-users. For IT staff it defines all technical components required to build the access when the role is assigned.
+
End-users interact with application roles and business roles to manage and review their access.

User Story::

* IGA administrator creates in UI the role, defines its business attributes and technical elements (e.g. construction). He connects the role to the application.
// TODO: Link to application role content.

* IGA administrator can start building the role as a copy of existing role - very often it can be another role from the application.

* When the role is created, the role owner is notified. He can review the role content in UI in the form xref:visibility-uc.adoc#_role_content_in_business_readable_form[understandable to him].


[#_create_business_role]
=== Create business role

Scenario::
Business manager or _Role manager_ wants to organize access to multiple applications to one business role. E.g. to better represent some business position.

Actors::
Typically this procedure is initiated by business manager or _Role manager_. This operation is typically performed by _IGA administrator_.

Motivation::
Structuring of application roles to business roles enables mapping user access to organization needs and increases readability of the user access. Creation of business roles for specific projects or business tasks helps end-users find relevant roles during self-service.

User Story::

* IGA administrator creates in UI the role, defines its business attributes and selects the content (the application roles.)

* IGA administrator can start building the role as a copy of another business role and modifying the content.

* When the role is created, the role owner is notified. He can review the role content in UI in the form xref:visibility-uc.adoc#_role_content_in_business_readable_form[understandable to him].

[#_create_application_resource_role]
=== Create application resource role (and template)

Shares on file-servers or spaces in Confluence may be managed as application resources. The application resources represent xref:../role-engineering/parametric-access.adoc[the parametric access]. Each resource has only one role and the access level is defined as relation in the assignment.

Application engineer or IGA administrator wants to define new role for application resources for some application.

There are 2 stages:

* Create a template for application resources - that each new application resource
* Create application resource role for the new resource.

Technically, for some implementation, the _application resource role template_ may be replaced by metarole - but the readability of the content may be affected. If the role is build on template, then the resource, the resource owner, and other components may be easier to read than anything computed by metarole.

User story::

* Application engineer or IGA administrator create the template of application resource role. He identifies the resources and defines the set of relations that will be used for the roles from the list of relations defined in MP. The relations are represented for end-users as access levels.

* If the connector for the application (midpoint resource) supports identification of new application resources, then the new application resource roles may be created automatically. By some scheduled task or initialized by livesync.

* If the connector can't identify the new resources, or it is not possible to define algorithm for new application resource roles (e.g. role owner can't be specified alorithmically), each role must be created manually by application engineer or IGA administrator. The application resource role template is used as the source.

[#_create_new_application]
=== Create New Application

Scenario::
_Application engineer_ wants to start managing access to an application via IGA.
He wants to create new application in IGA, define all roles for the application and start using them in role definition and access request.
+
The operation is performed by _IGA administrator_.

Actors::
Typically this operation should be performed by _IGA administrator_ upon request of _Application engineer_ (i.e. engineer or owner of the application that is being integrated with IGA solution), _Security officer_ or _Role manager_.

Motivation::
When new application is deployed, or the existing application needs to be integrated with IGA solution, then the application must be created in IDM.
+
The application definition (as service object) and its whole lifecycle should be integrated with an organization application inventory, if such inventory exists. Then the applications should be created automatically and their attributes may be automatically updated.
+
This use-case assumes situation, when the applications are created manually.

User Story::

* IGA administrator creates the application (new service object) in UI.

* IGA administrator creates definitions for each application role for the application. See xref:#_create_application_role[create application role] use-case.

* If the application was used before and some entitlements are already assigned, then IGA administrator assigns the application role to the particular users. It can be performed manually using GUI, using xref:operations-uc.adoc#_define_set_of_usersobjects_for_bulk_operation[bulk operation] or some reconciliation with the resource.

////
NOTE: these use-cases are not priority now.

== Role modification

=== Modify business attributes of application role

Scenario::

Actors::

Motivation::
// scenar - standardne operacie, ked sa meni vlastnik, popis roly, alebo nejake jej parametre.
// Kedze sa to zmenilo, tak je potrebne, aby definicia roly presla standardnym schvalovacim procesom.


User Story::

#TODO#

//NOTE: TODO - tu napisat, ze v niektorych situaciach mozu byt vyzadovane aj zmeny bez schvalovania. A na to je proces v operations - linku.

=== Modify provisioning configuration of application role

Scenario::

Actors::

Motivation::
// TODO - toto su situacie, ked sa meni konfiguracia aplikacie - zmena manazovanych objektov, alebo nastavovanych atributov, alebo zmena resourcu. Vacsinou toto inicuje inzinier aplikacie.

User Story::

#TODO#

=== Modify content of business role


Scenario::

Actors::

Motivation::
Update of business role is probably the most common operation in the process.

Most often it is the addition or removal of an application role from the business role. Specific workflow may be defined for  this operation. Because 2 roles are affected - the business role being modified and also the application role that will be included into the business role. Owners of both roles should approve this operation.

User Story::

#TODO#


== Role decommissioning

=== Remove role

Scenario::
There may be different situations why the role needs to be deleted. E.g.:
* Role owner of application role wants to remove the role, because the application access model is changed and the role is
* Role owner of business role wants to remove the role, because the business function is being decommissioned.
* Role manager performs role cleanup / organization structure is changing and the role becomes obsolete.

Actors::
The operation may be performed by business people as well as aby administrators. This operation should g through normal approval process

Open question: Should we allow the operation to be performed by business people (business manager deleting business role) ?

#Open question: When Role manager performs cleanup ? Should he still go through approval process ?#

Motivation::
Performing cleanup of the roles is necessary. When IGA solution allows easy role removal, then more clean environment is being kept.

Open question: Normally, business teams will not request for this - well, maybe we don't need to implement role removal as a process.

// TODO: #users access must be handled when the role is being decommisioned#

User Story::

#TODO#


=== Decommission application

Scenario::

Actors::

Motivation::

User Story::

#TODO#


== Other
=== Define approval policy

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Define auto-assignment rule for specified role

Scenario::

Actors::

Motivation::

User Story::

#TODO#

=== Update/remove role auto-assignment

Scenario::

Actors::

Motivation::

User Story::

#TODO#
////
