= IGA Use Cases: Self-service
:page-nav-title: Self-service use-cases
:page-display-order: 300
:sectnums:
:sectnumlevels: 3

== Request access to application resource

Shares on file-servers or spaces in Confluence may be managed as application resources. The application resources represent xref:../role-engineering/parametric-access.adoc[the parametric access]. Each resource has only one role and the access level is defined as relation in the assignment.

Access to application resources requires selection of not only the application role, but also setting of relation to the resource. The list of application resources may be large and end-user may not know he must define relation.

The relation is displayed to user as access level. The list of relations is specific to particular application resource role.

User story::
* While requesting access to application resource, the user selects application resource role (probably from list of application resource roles for specific application he has chosen prior).
* Then the user select access level (relation) from the list of predefined access levels for the application resource.

////
// NOTE: This use case are not priority now.
WARNING: This page is a work in progress.

This chapter describes only self-service use cases that relates mostly to access visibility and management.

== Access management

=== Request new access for myself / for somebody else


=== Update parameters of the access
E.g. the validity period


=== Remove access for myself / for somebody else


== Data visibility

=== What is my access ?


=== Do I have access to the application "A"? Why?
Identify role that is providing me access to the application.


=== What role should I request to get access to the application "A"?


=== Review all my request


=== Review all requests for me


=== Review all my approvals


=== View approval history of the request
How did I get this access ?


=== View actual state of the request
Why is the request not approved yet ?


== Approvals

=== Approve/Reject the request


=== Approve/Reject multiple requests at once


=== Automatic approval if requestor is the same as approver


=== Transfer all approvals to deputy
When I'm on leave, my deputy should obtain all approval cases


== End user operations

=== Setting somebody as deputy


=== Which role is providing access to the specified application (direct / indirect) ?
NOTE: this is special case of UC Hierarchy of roles 1 - just for one role.


=== What access is this role providing ?
NOTE: this is special case of UC Hierarchy of roles 2 - just for one role.


=== What everything is this role doing ?

////