= MidPrivacy Terminology
:page-nav-title: Terminology

Data::
Information about an object.
The ordinary things that we know, such as `fullName` or `emailAddress`.
Data items can be primitive (string, number) or complex (structured), they can be single-valued or multi valued and so on.

Meta-data::
Information about the data.
In context of midPrivacy we understand meta-data as information about every _value_ of the data.
For example multi-valued property `policySituation` that has two values will have two meta-data sets, one for each value.

Schema::
TODO

(Data) Model::
TODO

(Data) Provenance::
Meta-data that specify where a particular data item originated, how it was transformed and so on.
Provenance meta-data may explain the reasons for existence of a particular data item.

Data Protection::
Field of study that is focusing on control over *use* of data, particularly of personal data stored in computer systems.
Data protection is different than security. Data protection is not about confidentiality (secrecy), integrity and availability of the data.
Data protection is about proper _use_ of the data.
Data protection will deal with question whether it is OK to use particular data item for a particular purpose.
Can we use this data item because it is necessary to fulfil our employment contract with the user?
Can we use this data item because the user has given us a consent to use the data item?
Or do we need to delete the data idem because we do not have any valid reason to mantain it?
