---
layout: connector-page
display-order: 200
functionality-status: stable
development-status: active
support-status: supportable
origin: Evolveum
support-provided-by: Evolveum
target-systems: Office365, Azure Active Directory
connector-protocol: Microsoft Graph API
source-url-master: https://github.com/Evolveum/connector-microsoft-graph-api
description: Identity connector for Microsoft Azure services (Office365, Azure AD) based on Graph API.
upkeep-status: green
---
= Microsoft Azure (Graph API) Connector
:page-wiki-name: Microsoft Graph API Connector
:page-wiki-id: 15433824
:page-wiki-metadata-create-user: paulheaney
:page-wiki-metadata-create-date: 2014-05-22T10:52:19.550+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2019-07-09T13:58:18.591+02:00

== Capabilities and Features

[%autowidth,cols="h,1,1"]
|===
| Schema
| YES
|

| Provisioning
| YES
|

| Live Synchronization
| YES
| * Not supported for Licences object type

| Password
| YES
|

| Activation
| YES
|

| Script execution
| No
|

|===


== Versions

[%autowidth]
|===
| Version | Origin | Binary | Sources | Build Date | Description

| 1.0.0.1
| Evolveum
| link:https://nexus.evolveum.com/nexus/repository/releases/com/evolveum/polygon/connector-msgraph/1.0.0.1/connector-msgraph-1.0.0.1.jar[download jar]
| link:https://github.com/Evolveum/connector-microsoft-graph-api[Evolveum git repository (master)]
| Jan 21 2022
| Stable version

| 1.0.1.0
| Evolveum
| link:https://nexus.evolveum.com/nexus/repository/releases/com/evolveum/polygon/connector-msgraph/1.0.1.0/connector-msgraph-1.0.1.0.jar[download jar]
| link:https://github.com/Evolveum/connector-microsoft-graph-api[Evolveum git repository (master)]
| Nov 15 2022
| Fixes related to Licence handling and Group management improvements.

| 1.0.1.1
| Evolveum
| link:https://nexus.evolveum.com/nexus/repository/connectors/com/evolveum/polygon/connector-msgraph/1.0.1.1/connector-msgraph-1.0.1.1.jar[download jar]
| link:https://github.com/Evolveum/connector-microsoft-graph-api[Evolveum git repository (master)]
| Mar 02 2023
| Fix related to user account delta/delete operations.

| 1.0.1.2
| Evolveum
| link:https://nexus.evolveum.com/nexus/repository/connectors/com/evolveum/polygon/connector-msgraph/1.0.1.2/connector-msgraph-1.0.1.2.jar[download jar]
| link:https://github.com/Evolveum/connector-microsoft-graph-api[Evolveum git repository (master)]
| Mar 03 2023
| Fix related to handling actions on already deleted accounts.

| 1.0.2.0
| Evolveum
| link:https://nexus.evolveum.com/nexus/repository/public/com/evolveum/polygon/connector-msgraph/1.0.2.0/connector-msgraph-1.0.2.0.jar[download jar]
| link:https://github.com/Evolveum/connector-microsoft-graph-api[Evolveum git repository (master)]
| Mar 14 2023
| Role object class introduced for the management of role members and also the "mamanger" attribute
management feature and some minor fixes.


| 1.0.2.1
| Evolveum
| link:https://nexus.evolveum.com/nexus/repository/public/com/evolveum/polygon/connector-msgraph/1.0.2.1/connector-msgraph-1.0.2.1.jar[download jar]
| link:https://github.com/Evolveum/connector-microsoft-graph-api[Evolveum git repository (master)]
| Mar 24 2023
| Changes in query url construction for the AccountObjectClass
(can be extended for other object classes in the future)

| 1.0.2.1
| Evolveum
| link:https://nexus.evolveum.com/nexus/repository/public/com/evolveum/polygon/connector-msgraph/1.0.2.2/connector-msgraph-1.0.2.2.jar[download jar]
| link:https://github.com/Evolveum/connector-microsoft-graph-api[Evolveum git repository (master)]
| Apr 20 2023
| Changes in query url construction for the GroupObjectClass
(can be extended for other object classes in the future)


|===


== Documentation


=== Introduction

TODO


=== Limitations

Currently three object types are supported by the connector. Accounts, groups and licence objects.
There are some limitations in case of more complex relationship parameters (i.e. "App role assignments" in regards of the User
type objects), which are not present in the schema because of the current connID API limitations.
The group objects "distribution lists" and "mail and security" groups are read-only due to graph API limitations. General
provisioning and deprovisioning of group objects is otherwise permitted. Licences objects access is possible and read-only.
Role object class is currently implemented as read only, except role membership management.

Only basic query features are supported fo Licence and Role objects.

== Supporter filters for Licence and Role Objects (other than all filter)

[%autowidth]
|===
| ObjectClass | Parameters | Filter | Note

| Role
| Uid, Display Name
| Equals Filter
|

| Role
| Display Name
| Contains Filter
| Contains filter will be translated to "Starts With" filter

| Role
|
| Contains All Values
| Contains filter will be translated to "Starts With" filter


| Licence
| Uid, Id
| Equals Filter
|

|===

[WARNING]
====
Past usage of the API permitted the update of membership information regarding "distribution lists"
and "mail and security" groups objects. This seems to have changed in a future version of the
graph API referencing this as a bug.

link: https://github.com/microsoftgraph/microsoft-graph-docs/issues/14899[Microsoft documentation bug report]
====

Query url construction for Accounts and Groups now gives the possibility to specify complex queries using
Composite filters (‘And’, ‘Or’) and also ‘Not’ filter. There are a couple of api limitations in the
usage of filters.


- Contains filter: Although the graph API documentation states that a contains filter functionality
is provided, in reality the usage is quite limited (seems that not possible for the Account objects,
please see https://github.com/microsoftgraph/microsoft-graph-docs/issues/15837[this article] ).
To compensate for this the connector leverages the “search” functionality which in some cases can
partially work as a ‘contains’ filter (tokens).
Please see https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http#using-search-on-directory-object-collections[this article].
- Less than, Greater than filter: The construction of the filter queries is implemented properly
yet the API responds mostly with an exception hinting that “Less than or equals” or “Greater
than or equals” filtering should be used instead (did not find the reason for this in the API
documentation yet).
- Not and Ends with filter have implicitly the “count” parameter set to true.
This is requested by the API, please see https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http[this article].
- Generally you might experience specific limitations for other attributes. Usually you will be prompted with a corresponding exception.


When using a query which has a “contains” filter with other types of filter preset
(Other than composite filters or the ‘NOT’ filter). The part of the query with the contains filter
(either the single contains or other composite filter or not filter with only contains filters) has
to be directly on the left or right side of the first ‘AND’ filter clause. This is due to API limitations
regarding the combination of the ‘filter’ and ‘search’ clause, please see
https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http#using-search-on-directory-object-collections[this article].

Please also keep in mind the way you structure the queries related to this fact. MidPoint will automatically generate some parts
of the ‘AND’ filter tree based on the notation used in your configuration. In case of the usage of ‘Contains’ filter, please divide the ‘AND’ clauses directly in the configuration.
Please see the example below:

.Rather than structuring the queries with a single and ale letting midPoint divide the
it for the API, divide the query into specific AND blocks (right and left sides):
[source,xml]
----
<q:and>
    <q:and>
        <q:or>
            <q:substring>
                <q:path>attributes/name</q:path>
                <q:value>A</q:value>
            </q:substring>
            <q:substring>
                <q:path>attributes/name</q:path>
                <q:value>B</q:value>
            </q:substring>
        </q:or>
        <q:not>
            <q:substring>
                <q:path>attributes/department</q:path>
                <q:value>FOO</q:value>
            </q:substring>
        </q:not>
    </q:and>
    <q:and>
        <q:not>
            <q:substring>
                <q:path>attributes/name</q:path>
                <q:value>Baar</q:value>
                <q:anchorEnd>true</q:anchorEnd>
            </q:substring>
        </q:not>
        <q:not>
            <q:substring>
                <q:path>attributes/name</q:path>
                <q:value>XYZ</q:value>
                <q:anchorStart>true</q:anchorStart>
            </q:substring>
        </q:not>
    </q:and>
</q:and>
----

== Notes

The following ssl certificates are need for the connector deployment:
[source]
----
DigiCert Global Root CA
DigiCert Global Root G2
----

Some API resources might have a limit on the amount of API calls. This called 'resource throttling' might have an effect on the general performance of the connector. The connector itself copes with this by invoking the request for a specific resource multiple times (if needed) with a pause between each attempt. The length of the 'wait time' depends on the reply from the API endpoint, which provides the connector with the information about the availability of the endpoint. For more information see "https://docs.microsoft.com/en-us/graph/throttling".

== Configuration parameters

[%autowidth]
|===
| Parameter | Note

| clientId
| The Application ID that the 'Application Registration Portal' (apps.dev.microsoft.com) assigned to your app.

| clientSecret
| The Application Secret that you generated for your app in the app registration portal.

| tenantId
| Either Domain name of the Azure AD tenant or the tenant's guid identifier.

| proxyPort
| Port number of the HTTPS proxy to use to connect to cloud services. For this setting to take any effect, ProxyHost needs to be configured as well.

| proxyHost
| Hostname of the HTTPS proxy to use to connect to cloud services. If used, ProxyPort needs to be configured as well.

| pageSize
| The number of entries to bring back per page in the call to the Graph API

| disabledPlans
| List of the SkuId:ServicePlanId,[ServicePlanId2...]. These service plan will be disabled during assignment of the each license

| inviteGuests
| Whether to allow creation of guest accounts by inviting users from outside the tenant (based on e-mail address only)

| sendInviteMail
| Whether to send an email invitation to guest users.

| inviteRedirectUrl
| Specify a URL that an invited user should be redirected to once he claims his invitation. Mandatory if 'InviteGuests' is true

| inviteMessage
| Custom message to send in an invite. Requires 'InviteRedirectURL'

| throttlingRetryWait
| Max time period in between requests impacted by throttling. Define as number of seconds. Default 10

| throttlingRetryCount
| Max retry count in case of an request impacted by throttling. Default 3.

|===

== Resource Sample
xref:/connectors/resources/msgraph/[Microsoft Azure (Graph) Samples]
