= Connect your target LDAP system
:page-nav-title: Connect target LDAP system
:page-display-order: 210
:page-toc: top
:experimental:
:icons: font

The steps you're to take to connect the target system are very similar to what you did with the HR source system.

*Use the xref:/midpoint/reference/admin-gui/resource-wizard/create-resource-using-wizard/[guide on connecting a resource to midPoint] to help you with the configuration.*

. Create a resource from scratch.
. Use the xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP connector].
. Name the resource descriptively, such as _LDAP with users_.
. Configure connection to the LDAP server.
    ** The connector configuration is more complex.
       If you're unsure, your LDAP server admins can help you fill in the right values.
       The xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/#resource-examples[LDAP resource examples] may also help.
. Create the resource in the _Proposed_ lifecycle state.

[TIP]
====
If you want to follow this guide for learning purposes but don't have an LDAP system at hand, you can imitate it using a CSV resource instead.

To imitate the LDAP resource used in this guide and achieve similar situations, use the this link:../ldap-users-sample.csv[CSV file exported from our training LDAP server].
In such a case, you'd use a CSV connector and an object type of the _AccountObjectClass_ class instead, but the rest of the configuration would stay largely the same.
====

=== Configure the LDAP resource object type

Similarly to the HR system, the LDAP needs a resource object type for the accounts stored on it as well.

*Use this guide for xref:/midpoint/reference/admin-gui/resource-wizard/object-type/[instructions on object type configuration].*

. Name the object type _Normal Account_, for example.
. The type will be of the _Account_ kind, _default_ (or empty) intent, and with the _Default_ attribute set to _True_.
. Set *object class* to _inetOrgPerson_.
. On the data specification screen, set *Type* to _User_ and leave the *Archetype* empty.
. Keep the rest of the settings to defaults.

After you save your object type, you can preview the resource data to see what you're getting from the resource.