= Connect your target LDAP system
:page-nav-title: Connect target LDAP system
:page-display-order: 210
:page-toc: top
:experimental:
:icons: font

The steps you're to take to connect the target system are similar to what you did with the HR source system.

*Use the xref:/midpoint/reference/admin-gui/resource-wizard/create-resource-using-wizard/[guide on connecting a resource to midPoint] to help you with the configuration.*

[NOTE]
====
If you use the MID-301 First Steps Training Docker images, you can create the LDAP resource as a copy of the template that is prepared there.
Alternatively, you can configure the resource from scratch, i.e., without using the template.
If you use your own LDAP or Active Directory server and are unsure how to fill in the connection details in midPoint, ask your server admins for help.

The MID-301 training uses an LDAP server as an Active Directory server simulation.
====

. Create a resource from scratch.
    ** Use *Copy From Template* if you wish to use the template in MID-301 container.
. Use the xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/[LDAP connector].
. Name the resource descriptively, such as _LDAP with users_.
. Configure connection to the LDAP server.
    ** The connector configuration is more complex.
       If you're unsure, your LDAP server admins can help you fill in the right values.
       The xref:/connectors/connectors/com.evolveum.polygon.connector.ldap.LdapConnector/#resource-examples[LDAP resource examples] may also help.
. Create the resource in the _Proposed_ lifecycle state.

The LDAP connection details for the MID-301 training Docker images:

* Host: `ad`
* Port: `389`
* Bind DN: `cn=idm,ou=Administrators,dc=example,dc=com`
* Bind password: `secret`
* _The rest of the required settings is pre-configured in the template_

== Configure the LDAP resource object type

Similarly to the HR system, the LDAP needs a resource object type for the accounts stored on it as well.

Both object types are preconfigured in the MID-301 training LDAP template.

*Use this guide for xref:/midpoint/reference/admin-gui/resource-wizard/object-type/[instructions on object type configuration].*

. Name the object type _NormalAccount_, for example.
. Make the object type of the _Account_ kind, _default_ (or empty) intent, and with the _Default_ attribute set to _True_.
. Set *object class* to _inetOrgPerson_.
. On the data specification screen, set *Type* to _User_ and leave the *Archetype* empty.

Since there are also groups on LDAP servers, you need an object type for them as well.

. Name the object type _AD Group_, for example.
. Make the object type of the _Entitlement_ kind, _adGroup_ intent, and with the _Default_ attribute set to _True_.
    ** You can name the intent as fits your needs.
. Set *object class* to _groupOfNames_.
. On the data specification screen, leave *Type* and *Archetype* _Undefined_ and empty.

After you save your object type, you can preview the resource data to see what you're getting from the resource.