= Integrate target system
:page-nav-title: 3. Integrate target system
:page-display-order: 200
:experimental:
:icons: font

After connecting the source application to midPoint, you can move on to a target application or system.
A target application is a resource that acts as a recipient of data _from_ midPoint.
It is not authoritative, yet it has data on the same accounts that you have imported _to_ midPoint from the source system.

When a resource is not authoritative, it means that it cannot overwrite data in midPoint.
Moreover, midPoint is supposed to overwrite (read: rectify) the data on the resource if they happen to mismatch the data in midPoint.
This is useful in cases when someone creates an unauthorized ("illegal") account on the target system, for example.
Such an account needs to be deleted and midPoint does so as soon as it finds it, if instructed to do so.

The target system in this guide is an LDAP server that mimics Active Directory.
We will refer to this system as Active Directory or AD henceforth.

[[every-coin-has-two-sides]]
.No coin is one-sided
[TIP]
====
Target systems may not be authoritative in general,
yet they sometimes contain data we do not have in other systems and need to pull them _into_ midPoint
rather than delete them on the resource as superfluous.

In the case of this guide, it is be the situation with usernames.
We will read the usernames from the otherwise write-only non-authoritative AD application.
More on that in the modules about mappings and correlation rules.
====

== Next steps

The initial steps to integrate a target system are the same as with the source system.
You will define the resource for the application to enable connection between midPoint and the remote system the application runs on.

[.nowrap]#icon:arrow-right[] *xref:/midpoint/methodology/first-steps/integrate-target-system/connect-ad/[]*#