= Outcomes of MidScale Milestone M5
:page-nav-title: M5

*Milestone goal:* PostgreSQL, Performance environment (2), UX Analysis & Design +
*Status:* DONE (31 May 2021, on time)

== Activities and Outcomes

There were many parallel activities during this milestone:

. *Native PostgreSQL Repository implementation*
Native PostgreSQL Repository prototype was released in midPoint 4.3.
The evolutionary prototype was further extended and improved in M5, progressing towards a production-ready implementation.

. *User interface testing* using link:../../design/schrodinger-design/[Schrödinger testing framework].
More testing scenarios were added to the Schrödinger testing suite.

. *Performance testing environment*.
Testing environment was mostly completed in M5, first comprehensive performance tests were prepared and executed in the environment.
Please see xref:/midpoint/projects/midscale/design/testing-design/system-perf-test/[] page for details.

. *Task management improvements*.
Several improvements for midPoint task management components were proposed during M5.
The improvements are necessary as a preparatory work for implementing task autoscaling capabilities.
It was decided to start the preparation early, to reduce project risk.

. *User experience (UX) analysis and design*.
MidPoint user interface was analyzed, to identify the most problematic parts with respect to user experience, especially for administration of complex and large-scale deployments.
There were several proposed improvements.
The plan is to implement selected GUI and UX improvements in subsequent milestones.

. *Technology workshops*.
Several on-line technology workshops were conducted, to spread the knowledge about midScale project results in midPoint community.
Recording of the workshops is available in https://www.youtube.com/channel/UCSDs8qBlv7MgRKRLu1rU_FQ[Evolveum YouTube channel].

. *Coaching session #2*.
Second session with NGI_TRUST coaches was conducted during M5.
Please see link:/midpoint/projects/midscale/project/2021-05-midscale-coaching-2.pdf[slides] from the coaching session presentation for more details.

== Planning Delta

The activities of this milestone were mostly carried out according to original plan.
Yet, there were some differences:

* Preparatory work on task management improvements was started earlier than planned (originally planned as part of autoscaling implementation).

* More people were involved in the project, outside of the NGI funding.
It was decided to strengthen the architectural part of the project (Radovan Semančík) and support for testing infrastructure (Kamil Jireš).
