= Outcomes of MidScale Milestone M7
:page-nav-title: M7

*Milestone goal:* Migration Procedure, GUI Improvements, Auto-scaling
*Status:* DONE (31 August 2021, on time)

== Activities and Outcomes

There were many parallel activities during this milestone:

. *Native PostgreSQL Repository implementation*
Implementation of native PostgreSQL Repository was finished in M7, with some minor leftovers to be finished during first week of M8.
Regression and integration testing of repository implementation was done in M7.
Also, new SQL audit implementation was developed, supporting database partitioning.

. *Migration procedure* was addressed, implementing the designed capabilities, testing migration from midPoint 4.0 to midPoint 4.4, testing migration procedure for changing database implementations.

. *Auto-scaling* mechanisms were developed in M7, allowing midPoint cluster to scale automatically in cloud environment.
This activity included further improving, polishing, and documenting tasks (activities) framework code, including the bucketing (multi-node distribution) mechanism. Improving multi-node thresholds in activities.

. *Performance testing* was further improved, developing system-level real-world-like performance test.
Perfomance testing environment was further developed, improving the configuration, improving manageability.
Started implementation of detailed activity performance reporting.

. *User interface testing* using link:../../design/schrodinger-design/[Schrödinger testing framework].
Code of Schrodinger framework was adapted due to changes in MidPoint GUI.

. *User experience improvements* were implemented in various parts of midPoint user interface.

. *Testing and bugfixing* was intensified, as midPoint 4.4 is getting closer to release.

== Planning Delta

The activities of this milestone were mostly carried out according to original plan.
Yet, there were some differences:

* More people were involved in the project, outside of the NGI funding.
It was decided to strengthen the architectural part of the project (Radovan Semančík) and support for testing infrastructure (Kamil Jireš).
