= Outcomes of MidScale Milestone M8 (Finish)
:page-nav-title: M8

*Milestone goal:* Release: Acceptance testing, solution review, Documentation (project finish) +
*Status:* DONE (14 October 2021, on time)

== Activities and Outcomes

There were many parallel activities during this milestone:

. *Acceptance testing and bugfixing*
All parts of midPoint were tested, on a road to midPoint 4.4 release.
Testing was focused on midScale features.
However, the testing was holistic, making sure that existing midPoint features and new midScale functionality works together well.

. *Solution review*.
The data from testing were reviewed and analyzed.
Tests were adjusted and executed until the last day of the project, to gain maximum amount of data for future application of project results.

. *Documentation* was extended, adding few missing pieces and/or re-structuring existing documentation to reflect project outcomes.

. *Final coaching session* was conducted on October 7th.
See xref:../project/2021-10-midscale-coaching-3.pdf[coaching session presentation slides].

. MidPoint 4.4 Release Candidate was published.
See link:https://github.com/Evolveum/midpoint/tree/milestone/4.4-RC1[source code on github].

. *Final project report* was prepared and submitted on the last day of the project.

== Planning Delta

The activities of this milestone were mostly carried out according to original plan.
Yet, there were some differences:

* More people were involved in the project, outside of the NGI funding.
It was decided to strengthen the architectural part of the project (Radovan Semančík), support for testing infrastructure (Kamil Jireš) and junior test engineer (Ján Mederly).
