= Outcomes of MidScale Milestone M8 (Finish)
:page-nav-title: M8
:page-visibility: hidden

*Milestone goal:* Release: Acceptance testing, solution review, Documentation (project finish) +
*Status:* In progress (planned for 14 October 2021, on track)

NOTE: This is preliminary information, the milestone is still in progress.

== Activities and Outcomes

There were many parallel activities during this milestone:

. *Acceptance testing and bugfixing*
All parts of midPoint were tested, on a road to midPoint 4.4 release.
Testing was focused on midScale features.
However, the testing was holistic, making sure that existing midPoint features and new midScale functionality works together well.

. *Solution review*.
The data from testing were reviewed and analyzed.
Tests were adjusted and executed until the last day of the project, to gain maximum amount of data for future application of project results.

. *Documentation* was extended, adding few missing pieces and/or re-structuring existing documentation to reflect project outcomes.

. *Final coaching session* was conducted ... TODO.

. *Final project report* was prepared and submitted on the last day of the project.

== Planning Delta

The activities of this milestone were mostly carried out according to original plan.
Yet, there were some differences:

* More people were involved in the project, outside of the NGI funding.
It was decided to strengthen the architectural part of the project (Radovan Semančík) and support for testing infrastructure (Kamil Jireš).
