= Community Pre-release Testing
:page-wiki-name: Community Pre-release Testing
:page-wiki-id: 22741302
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2016-05-09T16:49:07.648+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2016-05-09T16:59:16.903+02:00
:page-upkeep-status: orange

// TODO: alias the page to proper place in "Community" site section?

MidPoint development has a semi-fixed development cycle: first, there is a phase of intense feature development.
Then there is a feature freeze.
Then there is a testing and bugfixing phase and finally a release.
If you are reading this it means that are most likely in the testing and bugfixing phase and we need your help.

*Community members are more than welcome to join midPoint testing.*


== Why should I do midPoint testing?

MidPoint is a complex software.
It is heavily configurable and customizable.
Although we are paying a lot of attention to QA, we simply cannot realistically cover all possible combinations of all possible configurations in all possible environments.
If you join midPoint testing then:

. You will help us to *make midPoint better*. Better for everybody.
Including you.

. You will make sure that the *next midPoint release will work* for your specific settings and in your specific environment.

It is usually too late to report a bug after midPoint is released.
Unless you are a midPoint subscriber your bug will be fixed in the following midPoint release, which is usually 6 months after the previous release.
It is a long time to wait.
On the other hand if you take part in the the pre-release testing then the chances are high that the bug will be fixed before the release and you won't need to wait.


== How do I join? What do I do?

It is simple: just try to use midPoint in your environment.
Try your own use cases.
That is the best input for us.
If we are asking for the community participation then we have tried midPoint in our environment and for our use cases.
We are looking for input from different environment.
Like yours.
So just try the new version of midPoint for yourself.
And let us know how it worked.

Ideally try to build the midPoint development snapshot.
Or use a automatically built binary.
But in development phase it is quite common that several bugs are fixed every day, so the automatically built binary may be already too old when it is built.
Building your own fresh midPoint is the best choice.
But regardless of how you get the development snapshot simple deploy it and use it.
That's all.

Please not that the development snapshot is an early access to next midPoint release (other project may call it _release candidate_ (RC) or _milestone_ (M), we just do not have any special name for that).
Which means that there may be some "upgrade" steps to take (usually xref:/midpoint/reference/upgrade/database-schema-upgrade/[database schema upgrade]).
Please see the release notes in the xref:/midpoint/release/[midPoint Releases] part of this wiki.

If you really really do not know what use cases to test there is our test of basic test cases that are part of our testing drill: xref:/midpoint/devel/testing/test-scenarios/[Test Scenarios].
Making sure that these works in your specific environment will also help.


== What do I do when I find a bug?

xref:/midpoint/reference/diag/creating-a-bug-report/[Create a bug report], of course.
The more diagnostic effort you put into the report the better.
This greatly improves the changes that your bug will be fixed quickly.

If you do not find any bugs and everything works please let us know as well (e.g. on a xref:/community/mailing-lists/[mailing list]). This will help us assess the overall quality of the release.

And if you really participate in any way in the testing there is one big *THANK YOU* from the midPoint team.


== See Also

* xref:/midpoint/reference/diag/creating-a-bug-report/[Creating a Bug Report]

* xref:/midpoint/devel/testing/test-scenarios/[Test Scenarios]

* xref:/midpoint/reference/diag/troubleshooting/[Troubleshooting]

* xref:/midpoint/reference/diag/troubleshooting/usual-troubleshooting-steps/[Usual Troubleshooting Steps]
