= Dummy Resource
:page-wiki-name: Dummy Resource
:page-wiki-id: 22741917
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2016-07-21T14:59:54.706+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2016-07-21T15:43:41.148+02:00
:page-upkeep-status: green

Dummy resource is a simple Java object that simulates real resource.
There is also a ConnId connector for that.
The dummy resource is fully embedded and it is using only local Java interfaces.
It is designed for the sole purpose of being used in the tests.

The resource can be configured for variety of configurations: it can support activation or not to support it, it can be case sensitive or case ignore, it can use persistent identifiers or just usernames and so on.
It can also simulate various errors.
Therefore it is much easier and much more flexible to use the dummy resource in tests than a real resource.

Components:

[%autowidth,cols="h,1,1"]
|===
|   | Source path |

| Dummy Resource
| icf-connectors/dummy-resource
| The resource itself.
This is pure Java code that is entirely independent (not dependent on ConnId).
This can be set up or inspected directly in the test, so end-to-end test cases are possible.


| Dummy Connector
| icf-connectors/dummy-connector
| ConnId connector for dummy resource.


| Fake Dummy Connector
| icf-connectors/dummy-connector-fake
| ConnId connector that presents itself in almost the same way as the dummy connector.
It just has different version number.
And it does not really works.
This is used for some border-case testing scenarios.


|===


== Controlling the Resource in Tests

There is a `DummyResourceController` class that can be used to conveniently control dummy resources.
There is no need to start the dummy resources and the dummy resource instances are created automatically when they are first used.
But the `DummyResourceController` can be used to initialize resource schema, to get resource namespaces and attribute QNames and so on.
This is a very convenient class.

// TODO: how to deploy dummy resource to running midpoint instance (dummy resource JAR)

== See Also

* wiki:Integration+Tests[Integration Tests]