= Testing midPoint pre-releases
:page-wiki-name: Testing midPoint pre-releases
:page-wiki-id: 18382860
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2015-07-13T15:30:05.536+02:00
:page-wiki-metadata-modify-user: semancik
:page-wiki-metadata-modify-date: 2015-07-13T15:30:05.536+02:00
:page-upkeep-status: orange

This page provides a guidelines for testing midPoint in "feature freeze" stage.
This is usually the stage when all the features are implemented and roughly tested.
This state begins few weeks before midPoint release.
This is the time when all feature development is stopped and intense testing and bugfixing takes place.
This state lasts for a few weeks and ends with midPoint release.

Any bugs identified during this stage will be most likely fixed in the immediate midPoint release.
Any bugs identified after that release will be fixed in the next release (unless a midPoint subscriber asks for a backport) - which is usually approx.
6 months later.
Therefore anyone interested in using midPoint is strongly advised to take part in the pre-release testing after midPoint feature freeze.


== Getting and installing midPoint pre-releases


=== Building pre-releases from source code

Simply use source code from the link:https://github.com/Evolveum/midpoint[master branch].


===  Getting binary pre-releases

Our continuous integration server (Bamboo) is building the source code every night.
You can get a binary from Evolveum Nexus: https://nexus.evolveum.com/


== Testing

Simply set up midPoint in a way that you need for your deployment.
Make sure that all the functionality that you need works.

A good way is to start by using the xref:/midpoint/reference/samples/[Configuration Samples].


== Reporting a bug

// TODO opdocs - fix registration link (and create-a-bug-report link?)
Please use our https://support.evolveum.com[Issue Tracking System] to report a bug (link:https://jira.evolveum.com/secure/Signup!default.jspa[free registration] is needed).
Please see the xref:/support/bug-tracking-system/creating-a-bug-report/[Creating a Bug Report] page.

Please follow the xref:/midpoint/reference/diag/troubleshooting/usual-troubleshooting-steps/[Usual Troubleshooting Steps] to make sure that your issue is a midPoint bug and not just a configuration problem.

If you are not sure you can use xref:/community/mailing-lists/[Mailing Lists] to discuss the issue that you are experiencing.


== See Also

* midPoint Development Snapshot

* xref:/support/bug-tracking-system/creating-a-bug-report/[Creating a Bug Report]

* xref:/midpoint/reference/diag/troubleshooting/usual-troubleshooting-steps/[Usual Troubleshooting Steps]