---
release-version: '1.7'
---
= Installing MidPoint 1.7 "Prometheus" From Binary Distribution
:page-layout: release-install-legacy
:page-nav-title: Installation Instructions
:page-wiki-name: Installing midPoint from Binary Release - 1.7
:page-wiki-id: 1867798
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2011-05-16T23:06:45.907+02:00
:page-wiki-metadata-modify-user: mamut
:page-wiki-metadata-modify-date: 2011-08-05T11:58:53.845+02:00
:release-version: 1.7
:page-liquid:

{% for v in site.data.midpoint-versions %}{% if v.version == page.release-version %}{% assign this = v %}{% endif %}{% endfor %}

== Pre-requisites


=== Java SE Development Kit 6

The development environment requires JDK 6. Recommended is JDK 6  update 11 or above.
Update 4 contains the JAX-WS 2.1 but there are some  issues, so we suggest something after update 11 or the latest  which you  can download at link:http://java.sun.com/javase/downloads/widget/jdk6.jsp[http://java.sun.com/javase/downloads/widget/jdk6.jsp]

`JAVA_HOME` environment variable should point to the JDK 6 installation path.


=== MySQL Database

Currently midPoint supports only MySQL database.
More databases will be  supported in later releases.

MySQL can be downloaded from link:http://www.mysql.com/downloads/mysql/5.1.html[http://www.mysql.com/downloads/mysql/5.1.html]. Optionally you can download also MySQL workbench, a GUI interfaces for databases from link:http://dev.mysql.com/downloads/workbench/5.2.html[http://dev.mysql.com/downloads/workbench/5.2.html].

For GNU/Linux, you can also use your distribution packages.


=== Apache Tomcat

midPoint needs an application server.
Currently, Apache Tomcat 6.0.x is supported.
More application servers will be supported in later releases.

Apache Tomcat can be downloaded from link:http://tomcat.apache.org/download-60.cgi[http://tomcat.apache.org/download-60.cgi]. The Apache Tomcat installation directory is further referenced as <tomcat>.

After installation, please copy `mysql-connector-java-5.1.X.jar` into `<tomcat>/lib/` (the "X" stands for MySQL minor version number and may vary).

Hint: For Debian/Ubuntu GNU/Linux distribution, you need to install "`libmysql-java`" package.

Hint: For RPM-based GNU/Linux distribution, you need to install "`mysql-connector-java`" package.


== Prepare midPoint software


++++
{% include release-install-download-v1.html this=this %}
++++

=== Initialize Database

Initialize repository database by executing:

Locate appropriate database initialization script from the following location:

[%autowidth,cols="h,1"]
|===
|  Release  |  DB Scripts

|  Nightly Build
| link:https://svn.evolveum.com/midpoint/trunk/repo/repo-db-impl/src/main/scripts/[https://svn.evolveum.com/midpoint/trunk/repo/repo-db-impl/src/main/scripts/]


|  Release 1.7
| link:https://svn.evolveum.com/midpoint/tags/1.7-prometheus/repo/repo-db-impl/src/main/scripts/[https://svn.evolveum.com/midpoint/tags/1.7-prometheus/repo/repo-db-impl/src/main/scripts/]


|===

Execute the script.
For MySQL the command is as follows:

[source]
----

mysql -u root < create_openidm_tables_mysql.sql

----

The script will create schema "midPoint" (replacing existing schema) with default proxy user MIDPOINT_PROXY and all necessary objects.

Use -f switch if you get drop errors.
Use  -v switch to watch the progress.


=== Deploy midPoint

To deploy midPoint WAR file, use the following steps:

. Stop Tomcat if it's already running.

. Copy `gui/admin-gui/target/idm.war` to `<tomcat>/webapps directory`.

. Start Tomcat.
It should pick up and deploy the "idm" application.


== Test midPoint administration GUI

Log in to the midPoint administration console using the following URL:

link:http://localhost:8080/idm/[http://localhost:8080/idm/]

[%autowidth,cols="h,1"]
|===
|  Username  |  administrator

|  Password
|  secret


|===

A home page of the midPoint console should be displayed.
This is a  pretty dynamic web application using AJAX for better user interaction.
The look&feel is quite minimalistic now, we are working on an  improvement just now.

If there is a problem, please check Tomcat logs in `<tomcat>/log/catalina.out` and `<tomcat>/log/idm.log`.

For an quick introduction to use of midPoint please follow the instructions on wiki:First+Steps[First Steps] page.


== See Also

* wiki:First+Steps[First Steps]

* wiki:midPoint+Releases[midPoint Releases]