---
release-version: '2.2'
---
= MidPoint 2.2 "Crius"
:page-layout: release-skeleton
:release-version: 2.2
:page-wiki-name: Release 2.2
:page-wiki-metadata-create-user: semancik
:page-wiki-metadata-create-date: 2013-03-04T20:55:28.959+01:00
:page-wiki-metadata-modify-user: mederly
:page-wiki-metadata-modify-date: 2013-09-07T13:04:35.079+02:00
:page-liquid:

Release {release-version} is an eighth midPoint release code-named _Crius_.
The {release-version} release brings numerous new features and many improvements.

++++
{% include release-data.html %}
++++

== Features

midPoint 2.2 provides following features:

* Basic user data model suitable for easy integration

** Numerous built-in properties based on IDM de-facto standards (LDAP inetOrgPerson, FOAF, ...) and experience

** Extensibility by custom properties

** Off-the-shelf support for user password credentials

** Off-the-shelf support for user activation

*** Enabled/disabled states (extensible in the future)

*** Support for user validity time constraints (valid from, valid to)

** Object template to define policies, default values, etc.

*** Ability to use conditional mappings (e.g. to create RB-RBAC setup)

*** Ability to include other object templates

*** Global and resource-specific template setup



* Account provisioning (create, read, update, delete accounts)

** wiki:Synchronization+Examples[Enabling and disabling accounts]

** Support for wiki:Mappings+and+Expressions[mapping and expressions] to determine account attributes

** Support of multi-value attributes

** Processing and computation fully based on wiki:Relativity[relative changes]

** wiki:Resource+Schema+Handling[Multi-layer attribute access limitations]

** wiki:Provisioning+Dependencies[Provisioning dependencies]

*** Higher-order dependencies (enables partial support for circular provisioning dependencies)

** wiki:Consistency+mechanism[Provisioning robustness] - ability to provision to non-accessible (offline) resources

** wiki:Consistency+mechanism[Provisioning consistency] - ability to handle provisioning errors and compensate for inconsistencies

** Support for wiki:Resource+Schema+Handling#ResourceSchemaHandling-AttributeDefinitions[tolerant attributes]

*** Ability to select tolerant and non-tolerant values using a pattern (regexp)

** Matching rules to support case insensitive attributes (extensible)

** Ability to execute scripts before/after provisioning operations

** Advanced support for account activation (enabled/disabled states)

*** Standardized account activation that matches user activation schema for easy integration

*** Ability to simulate activation capability if the connector does not provide it

*** Support for account validity time constrains (valid from, valid to)

*** Support easy wiki:Resource+Schema+Handling:+Activation[activation existence mappings] (e.g. easy configuration of "disables instead of delete" feature)

*** Support for wiki:Mapping[mapping time constraints] in activation mappings that allow configuring time-related provisioning features such as wiki:Resource+Schema+Handling:+Activation[deferred account delete or pre-provisioning].

** Ability to specify set of wiki:Protected+Accounts[protected accounts] that will not be affected by IDM system


* Integration of wiki:Identity+Connectors[Identity Connector Framework (OpenICF)]

** wiki:Unified+Connector+Framework[Unified Connector Framework (UCF) layer to allow more provisioning frameworks in the future]

** Automatic generation and caching of wiki:Resource+Schema[resource schema] from the connector

** wiki:ConnectorType[Local connector discovery]

** Support for connector hosts and remote wiki:ConnectorType[connectors], wiki:Identity+Connectors[identity connector] and wiki:ConnectorHostType[connectors host type]

** wiki:OpenICF+Documentation[Remote connector discovery]


* Web-based administration wiki:GUI+Subsystem[GUI] (AJAX)

** Ability to execute basic identity management operations on users and accounts

** Basic account-centered views (browse and search accounts directly)

** Built-in XML editor for identity and configuration objects


* wiki:Identity+Repository+Interface[Flexible identity repository implementations] and wiki:SQL+Repository+Implementation[SQL repository implementation]

** wiki:SQL+Repository+Implementation[Identity repository based on relational databases]

** wiki:Administration+Interface#AdministrationInterface-Keepingmetadataforallobjects%28Creation,modification,approvals%29[Keeping metadata for all objects] (creation, modification, approvals)

** wiki:Removing+obsolete+information[Automatic repository cleanup] to keep the data store size sustainable


* Synchronization

** wiki:Synchronization[Live synchronization]

** wiki:Relativity[Reconciliation]

*** Ability to execute scripts before/after reconciliation

** Correlation and confirmation expressions

*** Conditional correlation expressions

** Concept of _channel_ that can be used to adjust synchronization behaviour in some situations


* Advanced RBAC support and flexible account assignments

** wiki:Expression[Expressions in the roles]

** wiki:Roles#Roles-RoleHierarchy[Hierarchical roles]

** Parametric roles (including ability to assign the same role several times with different parameters)


* Several wiki:Projection+Policy[assignment enforcement modes]

** Ability to specify global or resource-specific enforcement mode

** Ability to "legalize" assignment that violates the enforcement mode


* wiki:Expression[Customization expressions ]

** wiki:Groovy+Expressions[Groovy]

** wiki:ECMAScript+Expressions[JavaScript (ECMAScript)]

** wiki:XPath+Expressions[XPath version 2] andwiki:XPath2+Tutorial[XPath Tutorial]

** Built-in libraries with a convenient set of functions


* wiki:PolyString[PolyString] support allows automatic conversion of strings in national alphabets

* wiki:Custom+Schema+Extension[Custom schema extensibility]

* wiki:Common+Interface+Concepts[Enhanced logging and error reporting]

* wiki:Task+Manager[Multi-node task manager component with HA support]

* Rule-based RBAC (RB-RBAC) ability by using conditional mappings in wiki:Object+Template[user template]

* Basic wiki:Auditing[auditing]

** Auditing to wiki:Audit+configuration[file (logging)]

** Auditing to wiki:Audit+configuration[SQL table]


* wiki:Password+Policy[Password policies]

* Lightweight deployment structure

* Support for Apache Tomcat web container

* wiki:Import+resource[Import from file and resource ]

** wiki:Object+References[Object schema validation during import] (can be switched off)

** wiki:Object+References[Smart references between objects based on search filters]


* Simple wiki:Consistency+mechanism[handling of provisioning errors]

* wiki:Protected+Accounts[Protected accounts] (accounts that will not be affected by midPoint)

* wiki:Segregation+of+Duties[Segregation of Duties] (SoD)

** wiki:Segregation+of+Duties[Role exclusions]


* Export objects to XML

* Enterprise class scalability (hundreds of thousands of users)

* API accessible using a web service and local JAVA calls

* wiki:Workflows+(midPoint+3.x)[Workflow support] (based on link:http://www.activiti.org/[Activiti])

* wiki:Notifications[Notifications]


=== Disabled Features

* Preview changes page


== Changes With Respect to Version 2.1.x

* Change to Apache License version 2.0

* wiki:Workflows+(midPoint+3.x)[Production-quality workflow integration] (using Activiti)

* wiki:Authorization[Authorizations for GUI] and web service integrated into RBAC mechanism

* Support for rename operations

* wiki:Resource+Schema+Handling[Multi-layer attribute access limitations]

* Fetch strategy in schema handling to support attributes that are not returned from connector by default

* Numerous wiki:Resource+Schema+Handling:+Activation[activation] enhancements

** Redesigned wiki:Resource+Schema+Handling:+Activation[activation support] with richer set of activation states and mappings

** Support for user validity time constraints (valid from, valid to)

** Support for account validity time constrains (valid from, valid to)

** Support easy wiki:Resource+Schema+Handling:+Activation[activation existence mappings] (e.g. easy configuration of "disables instead of delete" feature)

** Support for wiki:Mapping[mapping time constraints] in activation mappings that allow configuring time-related provisioning features such as wiki:Resource+Schema+Handling:+Activation[deferred account delete or pre-provisioning].


* Introducing concept of wiki:Roles+and+Policies+Configuration[inducement] as a generalization of the user-account assignment concept

* wiki:Administration+Interface#AdministrationInterface-Keepingmetadataforallobjects(Creation,modification,approvals)[Keeping metadata for all objects] (creation, modification, approvals)

* More wiki:Assignment+Configuration[expression variables] to support complex RBAC assignment/inducement structures and dynamic roles

* Improved internal resource caching

* Improved import overwrite operation

* Ability to use dynamic expression in wiki:Resource+Configuration[provisioning script] arguments

* Reconciliation wiki:Resource+Configuration[provisioning scripts]

* Introducing wiki:Matching+Rules[matching rules] which means a better support for case-insensitive resource attributes (especially identifiers)

* Option not to ignore the source attribute when using simulated activation

* Improved handling of wiki:Protected+Accounts[protected accounts]

* Improved handling of tolerant attribute values using patterns (regexp)

* Ability to limit wiki:Mapping[inbound mappings to a specific channel]

* wiki:Model+context+serialization[XML-based synchronization context serialization] to support seamless upgrades of running processes

* Built-in wiki:Upgrade+HOWTO[object migration capability] for easier system upgrades and data model migrations

* wiki:Removing+obsolete+information[Cleanup task] to automatically clean up old data from the system and make the data store sustainable

* Numerous schema improvements and generalizations

* Auditing login and logout events

* Improved internal consistency mechanism to handle more failure cases

* More built-in functions available to scripting expressions

* Resource-specific object templates

* Include mechanism for wiki:Object+Template[object templates]

* Resource-specific assignment enforcement policies

* New wiki:Projection+Policy["relative" assignment enforcement policy]

* Configurable wiki:Projection+Policy[legalization] of accounts that are violating assignment policy

* Improved correlation expression to support more cases

* Improved handling of task results and readability of the information

* Additional report types

* Ability to invoke reconciliation of a specific user from GUI

* wiki:Notifications[Significantly improved notifications]

* Higher-order dependencies (enables partial support for circular provisioning dependencies)

* Conditional correlation expressions

* Performance and scalability improvements

* Improved documentation

== Quality

Release 2.2 (_Crius_) is intended for full production use in enterprise environments.
All features are stable and well tested.

== Platforms

MidPoint is known to work well in the following deployment environments.
The following list is list of *tested* platforms, i.e. platforms on which midPoint team or reliable partners personally tested this release.
The version numbers in parentheses are the actual version numbers used for the tests.
However it is very likely that midPoint will also work in similar environments.
Also note that this list is not closed.
MidPoint can be supported on almost any reasonably recent platform (please contact Evolveum for more details).


=== Java

* Sun/Oracle Java SE Runtime Environment 7 (1.7.0_25)

Please note that Java 6 environment is no longer supported (although it might work in some situations).


=== Web Containers

* Apache Tomcat 6 (6.0.32, 6.0.33)

* Apache Tomcat 7 (7.0.30, 7.0.32)

* Sun/Oracle GlassFish 3 (3.1)


=== Databases

* H2 (embedded, only recommended for demo deployments)

* PostgreSQL (8.4.14, 9.1, 9.2)

* MySQL +
Supported MySQL version is 5.6.10 and above (with MySQL JDBC ConnectorJ 5.1.23 and above). +
MySQL in previous versions didn't support dates/timestamps with more accurate than second fraction precision.

* Oracle 11g (11.2.0.2.0)

* Microsoft SQL Server (2008, 2008 R2, 2012)


=== Unsupported Platforms

Following list contains platforms that midPoint is known *not* to work due to various issues.
As these platforms are obsolete and/or marginal we have no plans to support midPoint for these platforms.

* Java 6

* Sun/Oracle GlassFish 2



++++
{% include release-download.html %}
++++


== Background and History

midPoint is roughly based on OpenIDM version 1. When compared to OpenIDM v1, midPoint code was made significantly "lighter" and provides much more sophisticated features.
Although the architectural outline of OpenIDM v1 is still guiding the development of midPoint almost all the OpenIDM v1 code was rewritten.
MidPoint is now based on relative changes and contains advanced identity management mechanisms such as advanced RBAC, provisioning consistency and other advanced IDM features.
MidPoint development is independent for more than two years.
The development pace is very rapid.
Development team is small, flexible and very efficient.
Contributions are welcome.

For the full project background see the wiki:midPoint+History[midPoint History] page.


== Known Issues

. Extra values in tolerant multi-value attributes with high-order dependencies bug:MID-1561[]. Workaround: set the attribute to non-tolerant.

. AD connector does not distinguish error types (bug:MID-1562[]) therefore the applicability of consistency mechanism on AD is limited (bug:MID-1556[]). Workaround: use liveSync or frequent reconciliation.

. Slow shadow listing on debug page from MySQL when there is >500k shadows in database (bug:MID-1586[]). MySQL does not choose correct index during ordering.

. Under certain circumstances account links disappear (bug:MID-1575[]).

. Search filters are not resolved when using Roles->Edit role as well as in debug pages (bug:MID-1571[]). Workaround: Maintain roles configurations in XML files outside midPoint.
When you need to upload updated version of a role to midPoint, use "import from file" function.

. When importing large number of accounts from LDAP server (import from resource), be sure to suspend LDAP live sync task as it may cause severe performance problems (bug:MID-1549[]) - this is basically caused by live sync task trying to process LDAP changelogs, which have already been processed by import itself.
If you forgot to suspend live sync task during initial LDAP import, there is another workaround.
Simply suspend LDAP live sync task, then edit this task on debug pages and delete <token> element in <extension> element.
Then resume LDAP live sync task and issue is fixed.

. Linux/Solaris connector can't fetch users - account attributes invalid names (bug:MID-1547[]).

. Midpoint incorrectly detects Script capability for resources (bug:MID-1511[]).